### ISSUE TITLE
Wrong stings are used in settings

### ISSUE THREAD

**Issue by okainov** [cgeo/cgeo#7095] opened 2018-08-05 11:44 UTC
##### Detailed steps causing the problem:
1. Go to Settings - System
2. Make sure a lot of bullets have duplicated description instead of actual one (valid strings can be found on crowdin)
![image](https://user-images.githubusercontent.com/918446/43685567-aa62e228-98b5-11e8-9af7-9f03660f703a.png)

##### Version of c:geo used:
2018.08.05-NB-4a08c8a

##### System information:
--- System information ---
Device: SM-A320FL (a3y17ltexc, samsung)
Android version: 8.0.0
Android build: R16NW.A320FLXXU2CRE3
c:geo version: 2018.08.05-NB-4a08c8a
Google Play services: enabled - 12.8.74 (040306-204998136)
Low power mode: inactive
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: rotation vector
Hide own/found: true
Map strategy: auto
HW acceleration: enabled (default state)
System language: en (c:geo forced to English)
System date format: M/d/yy
Debug mode active: no
System internal c:geo dir: /data/user/0/cgeo.geocaching (745.8 MB free) internal
User storage c:geo dir: /storage/emulated/0/cgeo (725.8 MB free) external non-removable
Geocache data: /storage/3133-3335/Android/data/cgeo.geocaching/files/GeocacheData (6.7 GB free) external removable
Database: /data/user/0/cgeo.geocaching/databases/data (124.0 MB) on system internal storage
Fine location permission: granted
Write external storage permission: granted
Geocaching sites enabled:
   geocaching.com: Logged in (Login OK) / BASIC
   Geocaching.su
Geocaching.com date format: d. M. yyyy
Installed c:geo plugins:  none
--- End of system information ---

**Comment by pstorch** [comment] 2018-08-05 14:00
Duplicate of #5592

**Closed** 2018-08-05 14:00 UTC
