### ISSUE TITLE
New "Log geocache" page on website 

### ISSUE THREAD

**Issue by alan666notb** [cgeo/cgeo#6378] opened 2017-03-03 17:04 UTC
Are you aware that there seems to be a fairly major change to the 'Log geocache' page on the website on the way?

Sometimes (not always) when I try to log a cache on the website, I get a blue bar at the top of the page asking me to try the 'new logging experience'.
It looks very simplistic, I didn't actually get it to work.
I'm afraid I can't get it to re-appear now to get a screen shot.

Just thought you might like a heads-up.

**Comment by alan666notb** [comment] 2017-03-03 17:05
Ah - other people have seen it as well, there's a thread on the 'Geocaching UK' facebook page,

**Comment by kumy** [comment] 2017-03-03 17:18
I think a full page dump would be useful as well as the screen capture.

On March 3, 2017 6:05:10 PM GMT+01:00, alan666notb <notifications@github.com> wrote:
>Ah - other people have seen it as well, there's a thread on the
>'Geocaching UK' facebook page,
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/cgeo/cgeo/issues/6378#issuecomment-284010890

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by pstorch** [comment] 2017-03-14 21:16
We got a mail from Bryan today:

> Please note that in the near future, our team will deprecate the [old log-in page](https://www.geocaching.com/login/default.aspx) and route folks to the [new log-in page](https://www.geocaching.com/account/login?returnUrl=%2fplay). We're doing this so that we're not maintaining multiple log-in pages.

**Comment by rsudev** [comment] 2017-03-14 21:26
@pstorch I'd says that warrants a new issue of its own. I'll create one.

**Comment by pstorch** [comment] 2017-03-14 21:26
@rsudev my bad, mixed log with log-in

**Comment by Lineflyer** [comment] 2018-01-08 13:12
Duplicate of #6519

**Closed by Lineflyer** 2018-01-08 13:12 UTC
