### ISSUE TITLE
Export GPX - pass through gpsbabel - import GPX - fail

### ISSUE THREAD

**Issue by steve8x8** [cgeo/cgeo#5099] opened 2015-07-17 11:15 UTC
I think the XML parser is a bit on the strict side: If I
  * export a GPX
  * run "gpsbabel -i gpx -o gpx -f export.gpx -F import.gpx"
  * try to import the resulting file

I get the famous XML parsing error.
gpsbabel 1.5.0-3 (Debian Jessie)

**Comment by rsudev** [comment] 2015-07-17 11:19
This is not too helpful - could you post the exported and mangled gpx? Everything else would mean fumbling in the dark.

**Comment by Bananeweizen** [comment] 2015-07-17 16:06
If this is about empty lat/lon like in some other issues of yours, I'm tempted to close the issue. The GPX schema does not allow empty coordinates, and we are parsing this by means of XML parsing, not by means of String manipulation.

**Comment by steve8x8** [comment] 2015-07-17 17:21
@Bananeweizen: It's not - we're talking c:geo only here.
Let me start with a fresh c:geo (07-16 nightly), and fetch GC2WYQH. This doesn't even come with waypoints.
Store it to "Stored" which is otherwise empty. (Still no wpts.)
Enter cache description, select "Export > GPX", GC2WYQH.gpx gets written.
"adb pull" that file.
Run "gpsbabel -i gpx -o gpx -f GC2WYQH.gpx -F newGC2WYQH.gpx".
"adb push" the new file.
Try to import. Get "Import Failed. Bad File format. Cannot parse .gpx file as GPX 1.1: could not parse XML [OK]"

I cannot upload the gpx files, but I can make them available on my webserver:
http://steve8x8.faehrwiese.selfhost.me/cgeo/issue5099/
Apologies for that...

**Comment by rsudev** [comment] 2015-07-17 18:33
This looks like a bug. The gpx from gpsbabel is GPX 1.0, something we should read as well, shouldn't we?

**Comment by Bananeweizen** [comment] 2015-07-18 13:59
I have not verified if gpsbabel is still confused, but I'm quite confident that it will now work with schema valid GPX files.

**Comment by steve8x8** [comment] 2015-07-19 15:54
I'm sorry but the bug apparently hasn't been fixed in 2015-07-19 nightly build (as there was a change between 18 and 19 NB from /1/0 to /1/0/1 in two places I presume the patch was incorporated into the build)
New files (same cache) have been uploaded to the same place...

**Comment by SammysHP** [comment] 2015-07-19 19:18
@Bananeweizen 
I'm not really sure what you've fixed, but definitely not this issue. There is a bug during import, not export.

Btw: you forgot the `xmlns:groundspeak="http://www.groundspeak.com/cache/1/0/1"` (and the same for GSAK), so it's still not valid.

**Comment by Bananeweizen** [comment] 2015-07-20 15:07
@SammysHP Please run the files through an XML schema validation (like validome), for me the currently exported files validate fine, even though they don't explicitly put the namespace to the prefix (and I'm not an expert, so I have no idea when exactly that must appear in the XML file).

I'm also not sure, where you miss the namespace, as it is contained even in the empty export file, see https://github.com/cgeo/cgeo/blob/ef409cb4bedc0b094f4e430379b0bf79369b93c3/tests/src/cgeo/geocaching/export/GpxSerializerTest.java#L37

The fix I applied was actually bringing the sequence of elements into the right order, as those must be ordered correctly. My assumption was that gpsbabel might run into issues because the input is already not a valid GPX file.

However, I will probably install gpsbabel locally on my secondary machine, and try to reproduce the import issue.

**Comment by SammysHP** [comment] 2015-07-20 15:16
Hmm… I used the file from @steve8x8.

> New files (same cache) have been uploaded to the same place...

**Comment by Bananeweizen** [comment] 2015-07-23 18:37
To me this is an error in gpsbabel. Your cgeo produced input file is valid and contains this namespace declaration: xmlns:groundspeak="http://www.groundspeak.com/cache/1/0/1" 
The output file from gpsbabel misses that namespace and promptly every XML parser throws "Namespace prefix groundspeak on cache is not defined". You just need to open the second file in Chrome or Firefox to see this.

**Closed by Bananeweizen** 2015-07-23 18:37 UTC
Labels: Bug

**Comment by steve8x8** [comment] 2015-07-31 19:07
You may be right :( gpsbabel 1.5.2 behaves completely different but again produces a file that doesn't pass an XML validator. The good old days when one could combine geocaching gpx files using gpsbabel seem to be gone :'(

Sorry for the spam.

**Comment by gpsbabel** [comment] 2020-06-26 05:20
I found this issue in a search for something related. If there really is a bug suspected in GPSBabel, please report it in a way that's less afoul of https://www.gpsbabel.org/FAQ.html#bad_help . :-) I get that is issue is long in the history and I'm not really sure what's going on in this issue. I certainly don't know of any "famous XML reporting issue", so a clear, self-contained (data files, full command and version #'s of everything involved) will be helpful 

Trying to reconstruct the above, to GPSBabel, points without location are a bit nonsensical, but we don't (usually) go out of our way to vaporize them on input.


% cat /tmp/blah
,,Barf
% ./gpsbabel -i csv -f /tmp/blah -o gpx -F -
<?xml version="1.0" encoding="UTF-8"?>
<gpx version="1.0" creator="GPSBabel - https://www.gpsbabel.org" xmlns="http://www.topografix.com/GPX/1/0">
  <time>2020-06-26T05:04:36.025Z</time>
  <bounds minlat="0.000000000" minlon="0.000000000" maxlat="0.000000000" maxlon="0.000000000"/>
  <wpt lat="0.000000000" lon="0.000000000">
    <name>Barf</name>
    <cmt>Barf</cmt>
    <desc>Barf</desc>
  </wpt>
</gpx>

It's easy to argue that sending such points to "Null Island" isn't very awesome and I'd probably agree.

If you really are feeding it input without lat/lon, this doctor would prescribe Not Doing That. However, software is software and generally, we can bend it work for us. Given a good test case, we should be able to treat the absence of valid input as a warning in WaypointList::waypt_add(Waypoint* wpt) or an error if necessary. We need a working, failing test case to help make it all

**Comment by SammysHP** [comment] 2020-06-26 10:32
@gpsbabel This is the bug tracker for c:geo. Our team has not reported a bug to gpsbabel.
