### ISSUE TITLE
Multi-filter in offline list would be great

### ISSUE THREAD

**Issue by TofLaBeuze** [cgeo/cgeo#5764] opened 2016-05-31 16:10 UTC
##### Detailed steps causing the problem:
- No multi-filter possibility

##### Actual behavior after performing these steps:
- Current workaround : apply a first filter, move all results in a temporary list, applu the second filter

##### Expected behavior after performing these steps:
- A multi-filter fonction (that imagine complicated to implement)

##### Version of c:geo used:
- 2016.05.09

##### Is the problem reproducible for you?
Yes

##### Other comments and remarks:
It's a feature request, of course.

Geo-regards,
Tof

**Comment by SammysHP** [comment] 2016-05-31 19:39
Duplicate of #135.

**Closed by SammysHP** 2016-05-31 19:39 UTC
