### ISSUE TITLE
PN upload button - do not hide when no network is useable

### ISSUE THREAD

**Issue by bekuno** [cgeo/cgeo#9680] opened 2021-01-05 11:08 UTC
**Is your feature request related to a problem?**
The PN upload button will be hidden when the network is not useable.
But he is not easily automatic reactivated and the user has no control to check if it is later useable.

**Describe the solution you'd like**
Instead of hiding the button the button should be everytime visible.
If a upload is not possible then a toast should be shown after clicking the button.

**Comment by Lineflyer** [comment] 2021-01-05 16:42
Is that really intentional if no network is available?
If I switch off all data connections I can still see the button.

IMHO this can somehow be a problem if the user never logged in (due to no network) so his premium status is unknown and the button therefore unavailable.

**Comment by bekuno** [comment] 2021-01-05 20:32
Im not sure what the reason is for this problem.
But problay it has nothing to du with the member state.
See e.g. the image in https://github.com/cgeo/cgeo/issues/9656#issue-777649172

Mostly it is necessary to really close and restart c:geo to have the button back again.
On FB (c:geo Fangruppe) this problem is often reported. (eg. yesterday)

**Comment by Lineflyer** [comment] 2021-01-05 21:28
I am pretty sure, that it happens if the member state value for some reason is not/no longer set to premium, which is precondition, that this button is shown.
No idea however when this happens codewise. Is the button using the same mechanism for its visibility like we do for other PM features (e.g. favorite points). Or the other way around: Whoever notices the issue should take a look if the "Add to favorite" icon is still shown for found caches at this state.

**Comment by MagpieFourtyTwo** [comment] 2021-01-05 23:18
> Mostly it is necessary to really close and restart c:geo to have the button back again.

But even that is not deterministic.  Did not experience a missing upload button for a really long time (although I had no network coverage at all very often), but then had it last week (with most definitely *very* good network coverage).  Had to close c:geo four or five times (and add. remove it from memory several times) until the button was there again.  Very strange.

> I am pretty sure, that it happens if the member state value for some reason is not/no longer set to premium, which is precondition, that this button is shown.

Maybe, but in my case membership issues can definitely be excluded, as my member state did not change for years now.

**Comment by Lineflyer** [comment] 2021-01-06 08:31
> Maybe, but in my case membership issues can definitely be excluded, as my member state did not change for years now.

What I meant is, that for some reason (e.g. lost login due to no network) something happens in background which resets the memership status inside c:geo. Even if you are PM but c:geo no longer knows at this moment. Only a relogin (which might or might not be triggered by restarting c:;geo) solves this problem then.

**Comment by MagpieFourtyTwo** [comment] 2021-01-07 00:20
At least following the message in the footer of the start page, c:geo logs in to e. g. gc.com every time it has been closed, removed from memory, and re-opened.  And as I did this several time last week, without getting the upload button back, I would consider the re-login not as sufficient to getting the button back.

**Comment by moving-bits** [comment] 2021-05-16 07:14
duplicate of #7850, let's continue over there

**Closed by moving-bits** 2021-05-16 07:14 UTC
Labels: Feature Request
