### ISSUE TITLE
Show better name when selecting file from `downloads`

### ISSUE THREAD

**Issue by fm-sys** [cgeo/cgeo#12760] opened 2022-02-16 20:06 UTC
### Tell us your idea!

When choosing a file from the downloads folder, an unique ID is shown instead of the file name. 

![Screenshot_20220216_195119_copy_323x486](https://user-images.githubusercontent.com/64581222/154345834-184a8809-b0e1-4817-a376-d69e6611f7b4.jpg)

### What solution would you suggest?
Show a better display name.

**Comment by MagpieFourtyTwo** [comment] 2022-02-16 23:15
Renaming would be of course nice, but in a first approach and esp. as default value I would prefer to see the filename there - as in most cases the filename is a mnemonic one anyway.

**Comment by fm-sys** [comment] 2022-02-17 06:49
When selecting a GPX which is not stored in the downloads folder, we already show the filename. However, the downloads folder seem to behave kinda strange in the SAF selector...

**Comment by moving-bits** [comment] 2022-02-17 19:29
related to or maybe a duplicate of #12587

**Comment by fm-sys** [comment] 2022-02-18 11:29
Good catch, haven't remembered that issue. So let's focus on the default naming here... (I've renamed the issue accordingly)

**Comment by fm-sys** [comment] 2022-02-25 23:50
https://stackoverflow.com/a/25005243/13513639 might give a clue, how we could get the correct file name even when selecting a file from the `downloads` directory...

**Comment by eddiemuc** [comment] 2022-02-26 07:38
> https://stackoverflow.com/a/25005243/13513639 might give a clue, how we could get the correct file name even when selecting a file from the `downloads` directory... 

Sorry for replying so late...

But you can simply use `ContentStorage`'s method `getName(Uri uri)` to get the display name (using exactly the way described in aboves SO thread). You can also use `getFileInFo(Uri uri)` to get more Infos about the file e.g. it's size.

**Closed** 2022-03-06 09:33 UTC
Labels: Bug, Unverified
