### ISSUE TITLE
Cache list styling

### ISSUE THREAD

**Issue by andrixnet** [cgeo/cgeo#6719] opened 2017-09-01 08:49 UTC
I've noticed a styling problem in the cache list.

Caches that have a color marker on the left (found, etc) have the following differences from caches without this marker:
- cache icon is larger. (AFAIK cache icon is composed from multiple images, that of the cache type, that of the found, that of having waypoints)
- text is offset to right with the width of the border-left and a padding-left (without marker, there is no spacing for the marker width and padding-left=0)

This creates a visually disturbing zig-zag effect.

IMO cache type icons (with or without composition) should be the same size and the contents of the first column should be aligned at a constant position, leaving space for that marker where it is missing.

![screenshot_20170818-144941](https://user-images.githubusercontent.com/3382777/29962223-1ad3f5fc-8f0b-11e7-8902-992913fed98e.png)

**Comment by SammysHP** [comment] 2017-09-01 10:08
Duplicate of #5193.

**Closed by SammysHP** 2017-09-01 10:08 UTC
