### ISSUE TITLE
Feature Request: Allow to add a label to coordinates from personal notes

### ISSUE THREAD

**Issue by ControlTheBit** [cgeo/cgeo#6963] opened 2018-03-26 08:44 UTC
I would like to see the same labels that I use on geocaching.com also in the c:geo app when I open the waypoints of a cache.

Example:
On the geocaching.com page, I add the Stage1 and Final coordinates to my personal notes:
![image](https://user-images.githubusercontent.com/9163917/37895494-b93aab6e-30e1-11e8-8540-b9928e10a68e.png)

When I now open the same cache in c:geo, my labels are missing and replaced with "Personal Note X":
![image](https://user-images.githubusercontent.com/9163917/37895574-0197bbb8-30e2-11e8-8a76-40e02f0148f2.png)

It would be perfect if the label (or "name") of my coordinate from the personal notes would also show up in the waypoints of a cache in c:geo. So instead of "Personal Note X", I would expect my lables "Final" and "Stage 1".

##### Version of c:geo used
2018.02.05

##### Other stuff
Thank you all for the amazing work you are doing on this app every day! I would definitely pay for this app. Would be cool if there was a donate button or something in the app, so that I can pay you a "Kasten Bier" via the play store :-) Cheers and thanks a bunch!

**Comment by SammysHP** [comment] 2018-03-26 10:26
Duplicate of #4228.

There is a donation button in "about c:geo". ;)

**Closed by SammysHP** 2018-03-26 10:26 UTC
