### ISSUE TITLE
Log books are empty

### ISSUE THREAD

**Issue by alan666notb** [cgeo/cgeo#6177] opened 2016-12-07 19:40 UTC
On refreshing the caches stored in c:geo, no log entries are displayed.
I found an old issue concerning date formats with spaces in, I changed mine from "7 Dec 16" to "7/12/16" but it didn't make any difference.

##### Detailed steps causing the problem:
- load a cache into c:geo
- refresh it
- View the log entries.

##### Actual behavior after performing these steps:
There is a message containing the number of log types present (e.g. 70xfound, 3xWrite note)
It then says "The logbook of this cache is empty", no individual entries are displayed.

##### Expected behavior after performing these steps:
The log entries should be displayed

##### Version of c:geo used:
2016.11.28-RC

##### Is the problem reproducible for you?
Yes

##### System information:
```--- System information ---
Device: E6683 (E6683, Sony)
Android version: 6.0.1
Android build: 32.2.A.0.253
Cgeo version: 2016.11.28-RC
Google Play services: enabled
Low power mode: inactive
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: rotation vector
Hide own/found: false
Map strategy: auto
HW acceleration: enabled (default state)
System language: en_GB
Log date format: 29/11/2016
Debug mode active: no
Fine location permission: granted
Write external storage permission: granted
Geocaching sites enabled:
   geocaching.com: Logged in (Login OK) / PREMIUM
Geocaching.com date format: dd MMM yy
Installed cgeo plugins:  none
--- End of system information ---
```

**Comment by rsudev** [comment] 2016-12-07 19:51
I can confirm that, likely rather a change on the website.

**Comment by Lineflyer** [comment] 2016-12-07 20:16
Can also confirm with current master.
Oh dear.

**Comment by Lineflyer** [comment] 2016-12-07 20:17
My date format parsed is:
`dd.MMM.yyyy`

**Comment by SammysHP** [comment] 2016-12-07 20:23
It's not related to the date format. GC changed the way the logbook is loaded. Using GCLittleHelper shows me `dataElement.pageInfo is undefined`.

**Comment by Lineflyer** [comment] 2016-12-07 20:24
Here is a log:
```
21:20:14.736 Debug cgeo 7915  [OkHttp] GET https://www.geocaching.com/seek/geocache.logbook?tkn=wffITq-HTVGgZQImBTnEn7Kxj9UO1FGDv4Op-qbCQyd0U993--RJv51QZhuqLCvYorhsi7ohKP0jb7GllTKjqQVaSpZK2SpozyVZr0ckSrnqgGkGQiK99cGbaYtOSFex1KvCe3CNlR-fCrbF_ReLioGzOyC45y9iSx73EbyKgPBUbLiexLZN1ZdQntIP9eUQd_Kdg--XU3StQXZ1cxr32qHnGSzqs7Z-3ZjidGFWT85EyIuZctM9PVCw2BRZ3vIhg5y2KzHF7Yby9hLQYYiKxxOKALXHsuvW3_D-tN0nQuhm5Zw3rUwXpcD1LU2HDitq0&idx=1&num=35&decrypt=false&sf=true
21:20:14.736 Debug cgeo 7915  [OkHttp] GET https://www.geocaching.com/seek/geocache.logbook?tkn=wffITq-HTVGgZQImBTnEn7Kxj9UO1FGDv4Op-qbCQyd0U993--RJv51QZhuqLCvYorhsi7ohKP0jb7GllTKjqQVaSpZK2SpozyVZr0ckSrnqgGkGQiK99cGbaYtOSFex1KvCe3CNlR-fCrbF_ReLioGzOyC45y9iSx73EbyKgPBUbLiexLZN1ZdQntIP9eUQd_Kdg--XU3StQXZ1cxr32qHnGSzqs7Z-3ZjidGFWT85EyIuZctM9PVCw2BRZ3vIhg5y2KzHF7Yby9hLQYYiKxxOKALXHsuvW3_D-tN0nQuhm5Zw3rUwXpcD1LU2HDitq0&idx=1&num=35&decrypt=false&sp=true
21:20:14.736 Debug cgeo 7915  [OkHttp] GET http://gcvote.com/getVotes.php?version=cgeo&cacheIds=eda5ecba-a7ba-4cb4-bad1-b1729aea47a3
21:20:14.845 Debug cgeo 7915  [OkHttp] 200 (67 ms) GET http://gcvote.com/getVotes.php?version=cgeo&cacheIds=eda5ecba-a7ba-4cb4-bad1-b1729aea47a3 (http/1.1)
21:20:14.954 Debug cgeo 7915  [OkHttp] 200 (186 ms) GET https://www.geocaching.com/seek/geocache.logbook?tkn=wffITq-HTVGgZQImBTnEn7Kxj9UO1FGDv4Op-qbCQyd0U993--RJv51QZhuqLCvYorhsi7ohKP0jb7GllTKjqQVaSpZK2SpozyVZr0ckSrnqgGkGQiK99cGbaYtOSFex1KvCe3CNlR-fCrbF_ReLioGzOyC45y9iSx73EbyKgPBUbLiexLZN1ZdQntIP9eUQd_Kdg--XU3StQXZ1cxr32qHnGSzqs7Z-3ZjidGFWT85EyIuZctM9PVCw2BRZ3vIhg5y2KzHF7Yby9hLQYYiKxxOKALXHsuvW3_D-tN0nQuhm5Zw3rUwXpcD1LU2HDitq0&idx=1&num=35&decrypt=false (http/1.1)
21:20:14.954 Warning cgeo 7915  [network--6] GCParser.loadLogsFromDetails: status is error
21:20:15.500 Debug cgeo 7915  [OkHttp] 200 (718 ms) GET https://www.geocaching.com/seek/geocache.logbook?tkn=wffITq-HTVGgZQImBTnEn7Kxj9UO1FGDv4Op-qbCQyd0U993--RJv51QZhuqLCvYorhsi7ohKP0jb7GllTKjqQVaSpZK2SpozyVZr0ckSrnqgGkGQiK99cGbaYtOSFex1KvCe3CNlR-fCrbF_ReLioGzOyC45y9iSx73EbyKgPBUbLiexLZN1ZdQntIP9eUQd_Kdg--XU3StQXZ1cxr32qHnGSzqs7Z-3ZjidGFWT85EyIuZctM9PVCw2BRZ3vIhg5y2KzHF7Yby9hLQYYiKxxOKALXHsuvW3_D-tN0nQuhm5Zw3rUwXpcD1LU2HDitq0&idx=1&num=35&decrypt=false&sp=true (http/1.1)
21:20:15.500 Warning cgeo 7915  [network--7] GCParser.loadLogsFromDetails: status is error
21:20:15.500 Debug cgeo 7915  [OkHttp] 200 (721 ms) GET https://www.geocaching.com/seek/geocache.logbook?tkn=wffITq-HTVGgZQImBTnEn7Kxj9UO1FGDv4Op-qbCQyd0U993--RJv51QZhuqLCvYorhsi7ohKP0jb7GllTKjqQVaSpZK2SpozyVZr0ckSrnqgGkGQiK99cGbaYtOSFex1KvCe3CNlR-fCrbF_ReLioGzOyC45y9iSx73EbyKgPBUbLiexLZN1ZdQntIP9eUQd_Kdg--XU3StQXZ1cxr32qHnGSzqs7Z-3ZjidGFWT85EyIuZctM9PVCw2BRZ3vIhg5y2KzHF7Yby9hLQYYiKxxOKALXHsuvW3_D-tN0nQuhm5Zw3rUwXpcD1LU2HDitq0&idx=1&num=35&decrypt=false&sf=true (http/1.1)
21:20:15.500 Warning cgeo 7915  [network--1] GCParser.loadLogsFromDetails: status is error
```

**Comment by Lineflyer** [comment] 2016-12-07 20:25
Dont' how how fast and/or easy this is to fix and if someone has time.
Otherwise I would change the notification and post on FB as support mail keep coming in since some minutes.

**Comment by pstorch** [comment] 2016-12-07 20:27
I have some time this evening. If no one is working on it yet, I can take it.

**Comment by Lineflyer** [comment] 2016-12-07 20:32
Notification posted/updated.
FAQ updated

**Comment by Lineflyer** [comment] 2016-12-07 20:39
Posted to social networks.

**Comment by pstorch** [comment] 2016-12-07 20:40
This is the resp Object:
```
{"status":"error","value":"2","msg":"Tucson.Common.InvalidQueryStringException: Exception of type 'Tucson.Common.InvalidQueryStringException' was thrown.\r\n   at Tucson.Common.SecureQueryString.decrypt(String encryptedQueryString)\r\n   at Tucson.Common.SecureQueryString..ctor(String encryptedString)\r\n   at Tucson.Business.Geocaching.GeocacheLogbookHandler.ProcessRequest(HttpContext context)"}
```

Maybe the parameters changed. I'll compare with the browser.

**Comment by alan666notb** [comment] 2016-12-07 20:59
Don't know if this is related but uploading of Personal notes is also broken.
But that doesn't even work in a browser (Firefox) at the moment.

**Comment by pstorch** [comment] 2016-12-07 21:01
I suspect that there is something with the `userToken`

**Comment by SammysHP** [comment] 2016-12-07 21:05
`userToken` appears twice on the page. Maybe we use the first match which is `null`?

**Comment by pstorch** [comment] 2016-12-07 21:07
It has a value, but it looks much different when I compare it in c:geo with my browser. Maybe it has to be decrypted somehow?!?

**Comment by pstorch** [comment] 2016-12-07 21:11
The one I see in my browser is only uppercase and digits. The one received in c:geo is mixed case with digits and has - and _ characters.

**Comment by pstorch** [comment] 2016-12-07 21:40
As an example this is a (probably broken) `userToken` received in c:geo (shortened):

```
wffITq-HTVGgZQImBTnEnwqVXNo-05IzdRKqezcGczeVju6n5DQwK3sGUrNiynaOEExZ4CFgSf6bJLaJaHNqVhhR-G-VSyclDtOUYcOHZEqGBvKdA79NTQCSkUXyREzaRiNMnBtZZxwVY5toll4nA1STxy_...
```
It consists of upper and lower case characters as well as digits and - and _.


A working `userToken` from manual test in browser looked something like this (shortened):
```
ID5R2NBJDBPQZ4VUQYTUPZMPM5R2YVFD2WN6R5V3GJC2EWOBCSZFRNLN6EE7FK654O2UCK...
```

It consists of upper case characters and digits only.

**Comment by SammysHP** [comment] 2016-12-07 21:50
I noticed that I got the `[a-zA-Z0-9_-]` also in the web browser, but some minutes later `[A-Z0-9]` again.

**Comment by Lineflyer** [comment] 2016-12-07 22:01
Replies from socila media and mail also imply that it is working again.
I suggest we close this if it does not come back before the weekend.

**Comment by pstorch** [comment] 2016-12-07 22:01
Maybe a deployment gone wrong on some of their servers and some others were ok. Hard to say.

**Comment by Lineflyer** [comment] 2016-12-07 22:02
Indeed. Or just "bad" timing while you were testing.

**Comment by Lineflyer** [comment] 2016-12-08 10:41
Status now: Logbooks are working.

**Comment by Lineflyer** [comment] 2016-12-09 14:26
Logbook functionality is still normal. Closing this hoping it was a temporary server failure.

**Closed by Lineflyer** 2016-12-09 14:26 UTC
Labels: Bug, GC, high, Regression
