### ISSUE TITLE
[Nightly] Upload of PN containing a list of "Stored WPs" shows up inclomplete on gc server

### ISSUE THREAD

**Issue by MagpieFourtyTwo** [cgeo/cgeo#8785] opened 2020-08-11 13:42 UTC
**Describe the bug:**
Have a PN with a list of WPs, stored via the button ``Store Waypoints``.
After uploading the PN to gc.com, the WP list's endmarker ``</----->`` is missing in gc.com's presentation of the note.

**To Reproduce:**
Can provide the data of my scenario, of course, but would prefer to not do it over here, cause it contains a bunch of stage coordinates needed for solving a quite complex letterbox ... ;) So, @eddiemuc, if you need additional info, please let me know.

**Expected behavior/state after performing these steps:**
After uploading the PN to server, it should have the same content on gc.com as it has in c:geo.

**Version of c:geo used:**
2020.08.11-NB-a35a379

**Is the problem reproducible:**
Yes

**System information:**
```
--- System information ---
Device: VOG-L29 (VOG-L29EEA, HUAWEI)
Android version: 10
Android build: VOG-L29 10.1.0.140(C431E19R2P5)
c:geo version: 2020.08.11-NB-a35a379
Google Play services: disabled - 20.26.14 (120400-320008519)
Low power mode: inactive
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: rotation vector
Hide caches: -
Hide waypoints: visited
HW acceleration: enabled (default state)
System language: de_DE
System date format: dd.MM.yy
Debug mode active: no
System internal c:geo dir: /data/user/0/cgeo.geocaching (77,5 GB free) internal
User storage c:geo dir: /storage/emulated/0/cgeo (77,4 GB free) external non-removable
Geocache data: /storage/emulated/0/Android/data/cgeo.geocaching/files/GeocacheData (77,4 GB free) external non-removable
Database: /data/user/0/cgeo.geocaching/databases/data (281,8 MB) on system internal storage
Fine location permission: granted
Write external storage permission: granted
Geocaching sites enabled:
   geocaching.com: Logged in (Anmeldung OK) / PREMIUM
   extremcaching.com: Logged in (Anmeldung OK)
Geocaching.com date format: dd MMM yy
Installed c:geo plugins: contacts
--- End of system information ---
```

**Additional context:**
As @Lineflyer already mentioned in #8747, this usually seems to work - so perhaps it's because of a special combination ...?

**Comment by eddiemuc** [comment] 2020-08-11 14:42
Hi @MagpieFourtyTwo , I am currently in vacation with no Access to my laptop, but I will take a Look at this next week.
One wild (and probably unlikely) guess: is it possible that the PN reached its provider-sided storage limit (2500 at gc as far as I know) and was cut from the end?

**Comment by MagpieFourtyTwo** [comment] 2020-08-11 15:16
> that the PN reached its provider-sided storage limit 

Already checked in advance, but the PN is by far shorter. Nevertheless shorted the content to about 200 chars, but to no avail.

**Comment by eddiemuc** [comment] 2020-08-12 06:49
OK this was embarassingly easy to reproduce. As @MagpieFourtyTwo already suspected I fear GC interprets the closing tag as HTML and Strips it away.

As soon as I have access to laptop again I will replace opening/closing marker with something else. I am currently thinking 
```
{{cgeo: ... :cgeo}}
```

I am open for Other suggestions though. Conditions are:
* Opening and closing tag must be different from each other
* Must be something that the user will never ever use anywhere else in the PN
* Personal Wish: should not contain any text which needs translation in other languages

Some other ideas:
```
{={={= ... =}=}=}
{{===== =====}}
{{cgeo- ... -cgeo}}
```

**Comment by Lineflyer** [comment] 2020-08-12 09:37
I would suggest to use your initial idea containing `cgeo` because it also helps the user to understand where this note content comes from. You must always expect some not so teccie-save users.
The other important thing would be to make it as short as possible to save note spache but as long as necessary to identify the strings.

**Comment by MagpieFourtyTwo** [comment] 2020-08-12 09:41
I am in fact still fighting for every single byte, as the 2.5k are sometimes really limited, esp. with complex multis and mysteries. And, unfortunately, these are exactly the ones where forwarding would be most helpful

Question: Is parsing and interpreting strongly line orientated? If not, "Opening and closing tag (...) different from each other" would not be a must, but would even reduce the number of pattern alternatives to half and moreover even reduce reliability of detection.
If a lookahead would be possible, a way less complex pattern can be used, and additionally this would decrease probability of false detection tos/th like half (greetings from the milkmaid ;) ), cause this pattern has to appear twice, at start and end, which is way less likely then just one appearance of one out of two patterns.

So, I would prefer s/th like e. g. :WP: or $WP$, which IMHO is pretty unique, esp if additional rules are a) must be on a separate line, b) case sensitive, c) appear twice, with d) noting else than lines starting with @ (tesp. " in very next line, if comment is present) between these two markers ...

**Comment by eddiemuc** [comment] 2020-08-12 14:41
> Question: Is parsing and interpreting strongly line orientated? 
 There is no special parsing mechanism for inbetween the Tags, same mechanism is used for whole PN (it was "just" extended to enable also name and user Note parsing). However, a name is indeed only recognized if containing Line Starts with a `@`

The most important role of the Tags right now is that when you Press "Store WPs" and a tagged section is recognized, it is deleted in the PN and a freshly created WP list is appended to PN. Opening and closing tag being different simply reduces the Chance of deleting the wrong content in Case of User inserting such Tags manually.

> If a lookahead would be possible, a way less complex pattern can be used, 
Pattern may be less complex to save a few chars while still being different in Start and end.example:
```
{CG: ... :CG}
```
This would work I guess (CG is short for cgeo)


> So, I would prefer s/th like e. g. :WP: or $WP$, which IMHO is pretty unique
I agree that this is unique. I would however Like to use something not directly associated only - with waypoints (for reasons explained in )

**Comment by moving-bits** [comment] 2020-08-12 19:26
> I am in fact still fighting for every single byte, as the 2.5k are sometimes really limited, esp. with complex multis and mysteries.

Does the text for the saved coordinates has to be human-readable?
If we use sort of a base64 encoding we could stay with about 9 chars per coordinate.
(N/S: 1 bit, XX.xx.xxx 7+6+10 bits, E/W: 1 bit, XX.xx.xxx 8+6+10 bits - sum: 49 bits)

Alternatively, if we want to stay human-readable: We could use a fixed length format and leave out separators and spaces.

Although both approaches only help for storing the coordinates in a more compact format. If the user writes long texts as waypoint notes, the above will not help.


OTOH:
> And, unfortunately, these are exactly the ones where forwarding a list of WPs would be most helpful

When you're speaking about "forwarding a list of WP" - you could do that using a GPX file. Do we include waypoint notes and/or cache notes in that?

**Comment by MagpieFourtyTwo** [comment] 2020-08-12 20:01
GPX export notes delivers PN, but not notes of WPs.

**Comment by MagpieFourtyTwo** [comment] 2020-08-12 20:04
Nevertheless, currently the ``Store waypoint`` function shortens WP notes to 50 chars anyway ...

**Comment by eddiemuc** [comment] 2020-08-13 07:17
> Nevertheless, currently the ``Store waypoint`` function shortens WP notes to 50 chars anyway ... 

The current logic shortens the waypoint representation depending on how many chars are left in the PN (with regards to max upload size). First it tries to shorten User Note, then leaves User Note out completely, then removes Name and Type.

**Comment by eddiemuc** [comment] 2020-08-13 07:31
> Does the text for the saved coordinates has to be human-readable?
> If we use sort of a base64 encoding we could stay with about 9 chars per coordinate.
> (N/S: 1 bit, XX.xx.xxx 7+6+10 bits, E/W: 1 bit, XX.xx.xxx 8+6+10 bits - sum: 49 bits)

I would personally like a human-readable format, but storage could be optimized best with this approach. 
When we stay human-readable, we could save a few bytes by leaving Out the pharentesis around the Type identifier and the " around User Note If it does not contain line Breaks.

If storage optimization is a big concern for many Users:
What about letting the user choose between different storage Formats in the settings?

**Comment by eddiemuc** [comment] 2020-08-13 07:51
Human non readable: I assume easiest way to get close-to-max compression would be to create waypoint text as in human-readable way, but then ZIP it and store Base64-encoded.

**Comment by MagpieFourtyTwo** [comment] 2020-08-13 09:58
I'm pretty sure that base64 well lead to a lot of very surprised faces ... and most of them will probably not even try to look for the reasons, but just delete this "scrambled garbage" and never ever use it again, most probably even contact support to file an issue ... ;)

**Comment by MagpieFourtyTwo** [comment] 2020-08-13 10:24
> The current logic shortens the waypoint representation depending on how many chars are left in the PN (with regards to max upload size). First it tries to shorten User Note, then leaves User Note out completely, then removes Name and Type.

This appears to be way to restrictive to me ... as size becomes an issue on uploading only, I would prefer to let the user decide what he wants to strip. Cause sometimes you may just want to use ``Store Wayponts`` to transfer all the waypoint notes to PN to continue editing/saving/using them over there - and that would not be possible if this function removes all the stuff ... even worse, as the implemented strategy is not obvious nor comprehensible to the user.

**Comment by Lineflyer** [comment] 2020-08-13 10:49
> I would personally like a human-readable format, but storage could be optimized best with this approach.

I would also prefer to stay human-readable as also some users (which maybe currently unaware of the existing parsing) might then be able to easily reuse it to create waypoints by adding such format to their PNs on the website to have them later in c:geo.

**Comment by eddiemuc** [comment] 2020-08-13 11:06
> > The current logic shortens the waypoint representation depending on how many chars are left in the PN (with regards to max upload size). First it tries to shorten User Note, then leaves User Note out completely, then removes Name and Type.
> 
> This appears to be way to restrictive to me ...

Considering size limit for Upload was requested in l original issue, thus I included These Rules. (But a toast appears warning you that waypoints were shortened). I can easily remove this, I personally do not need this.

**Comment by eddiemuc** [comment] 2020-08-13 11:13
> I'm pretty sure that base64 well lead to a lot of very surprised faces ... and most of them will probably not even try to look for the reasons, but just delete this "scrambled garbage" and never ever use it again, most probably even contact support to file an issue ... ;)

I wouldn't make it the Default Option but allow Users to.enable it in the settings. I would Not use such an Option myself, I prefer a human-readable way, but if size is the main issue thus would be the best way to reduce it.

**Comment by moving-bits** [comment] 2020-08-14 15:34
Ok, thanks for the feedback. Let's stay with a human readable format only.

As for the delimiters: I'd like to have the word "cgeo" or "c:geo" in it - it gives users a hint where this comment comes from. We could even name it something like `{c:geo waypoint backup}` ... `{c:geo}` - this is a couple of chars longer, but does explain more clearly where this is coming from.

**Comment by Lineflyer** [comment] 2020-08-14 15:56
How about `{c:geo WP backup} ... {c:geo}`

**Comment by moving-bits** [comment] 2020-08-14 15:59
> How about `{c:geo WP backup} ... {c:geo}`

yes, ok for me

**Comment by eddiemuc** [comment] 2020-08-14 16:53
I would leave out the "WP" too and be even more generic: 
```
{c:geo data} ... {c:geo}
```
(and I would explicitely not make this translatable)

Would that be ok too?

**Comment by Lineflyer** [comment] 2020-08-14 16:56
> Would that be ok too?

Sounds reasonable

**Comment by eddiemuc** [comment] 2020-08-15 15:52
On another note: when all this is said and done I would really like to see the whole personal-note-parsing documented somewhere in the user guide. 
* Should I open a separate issue for this?
* Of course I volunteer to do this. But what is the process here? I seem to need an account to edit the user guide, and I don't know what the process is here...

**Comment by Lineflyer** [comment] 2020-08-15 16:06
> Of course I volunteer to do this. But what is the process here? I seem to need an account to edit the user guide, and I don't know how review/approval works here...

Thats my ToDo.
I wanted anyway to migrate it into an open wiki to let the community maintain it. 
Anyhow until then I will create an account for you.
Could you please open a reminder issue and assign me to it. I am not at home now.

**Comment by eddiemuc** [comment] 2020-08-15 16:23
> Could you please open a reminder issue and assign me to it. I am not at home now.

I created #8806 but I lack permission to assign issues to users.

**Comment by moving-bits** [comment] 2020-08-15 16:32
> > Could you please open a reminder issue and assign me to it. I am not at home now.
> I created #8806 but I lack permission to assign issues to users.

I set the attributes accordingly.

**Comment by eddiemuc** [comment] 2020-08-17 10:31
While playing around with GUI the tags didn't feel completely right. I went with following for now:
`{c:geo-start} ... {c:geo-end}`
If size is still an issue, I am willing to implement optional storage as non-human-readable info block, but maybe we should then have a separate issue for this?

**Comment by moving-bits** [comment] 2020-08-17 13:57
> If size is still an issue, I am willing to implement optional storage as non-human-readable info block, but maybe we should then have a separate issue for this?

Let's stay with the human-readable format for now. If size limit is an issue hitting us frequently, we can still add the other functionality.

**Closed** 2020-08-17 17:36 UTC
Labels: Bug
