### ISSUE TITLE
Add parsing waypoints for main description

### ISSUE THREAD

**Issue by GodfatherThe** [cgeo/cgeo#6260] opened 2017-01-16 04:38 UTC
Right now there is automatic coordinates in personal notes parsing and creating waypoints from them. Could you please also add the same for main cache description? Reason - if service doesn't have waypoints functionality (like SU) then all steps for multi cache are just in the description. So I have to copy-paste description to personal notes to get waypoints

P.S. Is there possibility to assign waypoint name thru parsing? Once I found out that if I write like "final - <coords>" than type of WP will be "final destination". Is it documented somehow?

**Comment by pstorch** [comment] 2017-01-16 14:59
Related to or duplicate of #3410 and #1249

**Comment by Lineflyer** [comment] 2017-01-17 20:57
@pstorch is correct. Please kindly continue in the mentioned issues.

**Closed by Lineflyer** 2017-01-17 20:57 UTC
Labels: Feature Request
