### ISSUE TITLE
Spoiler of GC3CJ0K cache is not displayed

### ISSUE THREAD

**Issue by TofLaBeuze** [cgeo/cgeo#4693] opened 2015-02-22 09:04 UTC
Hi c:geo team,
sometimes, spoilers or log photos of geocaches are not displayed in c:geo, when storing cache for offline use (or even online).
Example : spoiler of http://coord.info/GC3CJ0K
cgeo version 2015.01.20, android version 4.4.2 or android version 4.1.2

Other example with missing some log images : GC1PCV7 

If you could something... thanks :)

**Comment by SammysHP** [comment] 2015-02-22 11:05
This works for me. We have fixed some issues regarding hints and spoiler images in the last weeks. You can try the [nightly build](http://www.cgeo.org/c-geo-nightly.apk) (and don't forget to refresh the cache).

**Comment by samueltardieu** [comment] 2015-02-22 11:11
I can reproduce it with a developer build from Friday night.

**Comment by SammysHP** [comment] 2015-02-22 11:40
@samueltardieu 722578c

**Comment by samueltardieu** [comment] 2015-02-22 11:41
I've seen it. I am on the ski tracks right now and cannot confirm right away whether that fixed it or not. I'll check it.

**Comment by rsudev** [comment] 2015-02-22 11:52
I was able to reproduce it with an older build on my phone as well and can confirm it fixed now. Checking the spoiler imagae link in the cache description confirms, that it is a duplicate of #4691 and fixed by 722578ca067b8ebe8e4548f0d1a9e13f2c549.
As mentioned there this is also fixed on release and therefore will be part of the next either bugfix or feature release.

**Closed** 2015-02-22 13:01 UTC

**Comment by Bananeweizen** [comment] 2015-02-22 15:43
I'm wondering if we should create a new release from the release branch. It's not easy to tell how many users are affected by the URL change.

**Comment by rsudev** [comment] 2015-02-22 16:09
If you suspect this is a recent change from gc.com side, I would suggest to schedule a bugfix-release.

**Comment by samueltardieu** [comment] 2015-02-22 16:21
I think there has been two users writing about this today (Tof and a mail to support).

**Comment by TofLaBeuze** [comment] 2015-02-22 16:26
Other people told me having similar problem on a french forum, and a friend also through private message.
Thank you for all your efforts.

**Comment by TofLaBeuze** [comment] 2015-02-24 20:43
Thanks, it works with the yesterday's bugfix release (at least for this cache).
