### ISSUE TITLE
WP Calc - Guided mode now turned off by default

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#12597] opened 2022-01-23 11:33 UTC
### Describe your problem!

I noticed, that recently the default state of "Guided mode" in the new WP calc seems to have changed from on to off.

I propose to have it switched on in first (ever) use and afterwards remember the state for subsequent waypoints.

### How to reproduce?

Create new caluclated waypoint

### Actual result after these steps?

Guided mode is always off.

### Expected result after these steps?

Should remember the last setting.
If there is no last setting, it should be enabled.

### Reproducible

Yes

### c:geo Version

2022.01.23-NB

### System information

```text
Samsung S20, Android 12
```

**Comment by eddiemuc** [comment] 2022-01-23 11:47
There's no setting for this yet. Current implementation wil always start with guided mode = off for new coordinates. SO this is a valid feature request (but not a bug imho, this was actually never requested before)

**Comment by eddiemuc** [comment] 2022-02-11 14:47
I looked into this and i would like to suggest a slightly different approach than a setting. Instead, I feel that the guided mode should be chosen based on the selected coordinate mode in the normal coordinate input dialog.

For example consider the following:

![image](https://user-images.githubusercontent.com/6909759/153612291-2fea21ec-bac5-4689-90df-8e011043f03f.png)

If user clicks "Calculated Coordinates (new)" here then IMHO the dialog should open in guided mode with format DMS selected

However, consider the following:

![image](https://user-images.githubusercontent.com/6909759/153612457-c83db842-10de-4e4a-9f63-5b2be2992898.png)

Here I think the calculated coordinate dialog should open in plain mode.

The remaining question is: what should happen if the current coordinate input is not parseable, e.g. like here:

![image](https://user-images.githubusercontent.com/6909759/153612638-09a32225-6641-4a1a-88ef-62c17862abbe.png)

IMHO, in this case the calculated dialog should open in plain mode, and either empty or taking over the content as best as possible

And there's the special case of "no input at all" e.g. like this:

![image](https://user-images.githubusercontent.com/6909759/153612863-8eac0c03-137c-41d4-8a04-be47dbac4d7a.png)

IMHO this should open in plain mode with empty fields as well.

What do you think?

**Comment by eddiemuc** [comment] 2022-02-19 16:25
Duplicate of #12751

**Closed by eddiemuc** 2022-02-19 16:25 UTC
Labels: Feature Request
