### ISSUE TITLE
OC Authentication not possible (Android 4.x)

### ISSUE THREAD

**Issue by mirabilos** [cgeo/cgeo#7497] opened 2019-04-14 22:05 UTC
##### Detailed steps causing the problem:

- start c:geo
- see it cannot login to OC.DE
- try to reauthenticate via Settings → Services
- see it fail

##### Actual behavior after performing these steps:

it fails

##### Expected behavior after performing these steps:

it should login to OC.DE

##### Version of c:geo used:

NB 2019-04-13 375874c

##### Is the problem reproducible for you?
Yes

##### System information:

can do if needed

**Comment by Lineflyer** [comment] 2019-04-15 06:49
Thanks for your report.
Can you explain in more detail, what failure happens?
Does your browser open to present the login page of oc.de?

What Android version are you using (system information could be indeed helpful here).

**Comment by mirabilos** [comment] 2019-04-15 14:23
Hi Lars,

>Can you explain in more detail, what failure happens?
>Does your browser open to present the login page of oc.de?

OK, I’ve just upgraded to today’s NB, and the errors are the same.

In Browser, I’m logged into OC. I’m starting c:geo, and the status
line shows that GC is logged in, but OC.DE is “Login failed”.

I go to ⋮ → Settings → Services → Opencaching.de → Authorise c:geo again
then hit the “Start authorisation” button, then there’s a popup saying
“Waiting for opencaching.de…” (I think, it goes away very quickly) and
a… I think it’s called toast… saying “c:geo failed to initialise autho‐
risation process”.

Neither Browser pops up nor Fennec nor the dialogue in which I can
choose which browser to use.

>What Android version are you using (system information could be indeed helpful here).

LiquidSmooth 3.2 (KitKat), with microG (which, for some reason, is
not recognised as Google Play services, despite having UnifiedNLP
positioning and all).

--- System information ---
Device: HTC Desire (htc_bravo, htc_wwe)
Android version: 4.4.4
Android build: liquid_bravo-userdebug 4.4.4 KTU84Q c5fea05051 test-keys
c:geo version: 2019.04.15-NB-017b502
Google Play services: unavailable
Low power mode: inactive
Compass capabilities: yes
Rotation vector sensor: absent
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: magnetometer & accelerometer
Hide own/found: true
Map strategy: detailed
HW acceleration: enabled (default state)
System language: en_GB
System date format: yyyy/MM/dd
Debug mode active: no
System internal c:geo dir: /data/data/cgeo.geocaching (824.6 MB free) internal
User storage c:geo dir: /storage/sdcard0/cgeo (3.4 GB free) external
Geocache data: /storage/sdcard0/Android/data/cgeo.geocaching/files/GeocacheData (3.4 GB free) external
Database: /data/data/cgeo.geocaching/databases/data (30.9 MB) on system internal storage
Fine location permission: granted
Write external storage permission: granted
Geocaching sites enabled:
   geocaching.com: Logged in (Login OK) / PREMIUM
   opencaching.de: Not logged in (Login failed)
Geocaching.com date format: yyyy-MM-dd
Installed c:geo plugins:  none
--- End of system information ---

**Comment by fusselwolf** [comment] 2019-04-23 19:04
Hi Lars,
i've just exact the same issue on Blackberry Z10 with OS 10,3,3.21,37.
c:geo-release is 20190416.
oc.nl and oc.uk are cinnecting normal!

**Comment by Lineflyer** [comment] 2019-04-23 19:28
As its working normal for me I assume some device or device browser related issue.
As no browser app selection dialog is displayed, one try could be to remove your current default browser from being used as default (in device app manager) and try authorizing again.

After clicking "Authorize" the browser should open...then we can try to find out more clues or if the problem is connected with a certain browser.

Other options:
- Did you ever try to delete the login information completely by long pressing the "Authorize again" in c:geo?
- Did you try to logout in your phone browser and then start the process in c:geo to authorize?

**Comment by fusselwolf** [comment] 2019-04-24 10:25
Hi Lars,
the behavior with diffent browsers was the same. Since Rel. 2019.04.16 no button "uthorize again" is displayed, the other options where both unsuccessful.
Then i deleted c:geo and installed first 2019.02.23 --> all ok! Then updated to 2019.04.04 --> ok.
After this i updated to the current 2019.04.16 --> "OC.DE (...) Anmeldung fehlgeschlagen", while GC and OC.UK displays "Anmeldung ok"

**Comment by Lineflyer** [comment] 2019-04-24 10:38
> Since Rel. 2019.04.16 no button "uthorize again" is displayed, the other options where both unsuccessful.

There should be (in german: "cgeo neu autorisieren") the button if you long press it it resets the account information.

> Then i deleted c:geo and installed first 2019.02.23 --> all ok! Then updated to 2019.04.04 --> ok.
After this i updated to the current 2019.04.16 --> "OC.DE (...) Anmeldung fehlgeschlagen", while GC and OC.UK displays "Anmeldung ok"

Thanks for testing this. I will take a look into the changes..really strange.

**Comment by Lineflyer** [comment] 2019-04-24 10:41
Between version 2019.04.04 and 2019.04.16 I do only see one suspicious change which could IMHO be related: 9dde8215159d77d0b2adcb6dab2211282ca1a90b

@samueltardieu @UniQP 
Could it be, that the OKHTTP introduced such kind of bug in authorization to OC?

**Comment by samueltardieu** [comment] 2019-04-24 11:36
Absolutely, hence my comment https://github.com/cgeo/cgeo/issues/7453#issuecomment-479034301

**Comment by mirabilos** [comment] 2019-04-24 17:15
Lars dixit:

>As its working normal for me I assume some device or device browser
>related issue.

Hm, interesting. But, on the other hand, this stopped working with
a c:geo update: it said OC login failed even before I went to the
services menu to try and relogin.

Nothing else changed.

>Other options:
>- Did you try to logout in your phone browser and then start the
>  process in c:geo to authorize?

As I said: yes, I'm logged in in Browser.

>- Did you ever try to delete the login information completely by long
>  pressing the "Authorize again" in c:geo?

Ah, so long pressing logs out. Gah, this was neither obvious
nor documented.


fusselwolf wrote:
> oc.nl and oc.uk are cinnecting normal!

I've just tried reactivating OC.PL, and I get the browser selection
dialogue for it, can login in Browser, and it works. With OC.DE, I
don't get even the selection dialogue.

>As no browser app selection dialog is displayed, one try could be to
>remove your current default browser from being used as default (in
>device app manager) and try authorizing again.
>
>After clicking "Authorize" the browser should open...then we can try
>to find out more clues or if the problem is connected with a certain
>browser.

Even after restting all app preferences, I don't get the popup.

**Comment by Lineflyer** [comment] 2019-04-24 21:12
So it seems the issue was caused by our upgrade of okhttp libraries, however it is strange, that his only affects some devices and only some/one oc plattform.

I think, this needs to be investigated a bit deeper.

**Comment by Lineflyer** [comment] 2019-04-24 21:13
Up to now we have it only on Android 4.4.x (kitkat) and Blackberry (whatever Android version is below).

**Comment by Lineflyer** [comment] 2019-04-24 21:23
I can maybe reproduce the problem on a 4.4.2 device, however the ADB driver is not working, so cant get a trace now.

**Comment by Lineflyer** [comment] 2019-04-25 21:32
Some other field reports now, all with Android 4.4.x

I can still not get ADB interface working on my devices....so if someone can reproduce with an 4.4 emulator and get a stacktrace, this would be appreciated.

**Comment by mirabilos** [comment] 2019-04-25 21:49
Lars dixit:

>someone can reproduce with an 4.4 emulator and get a stacktrace, this
>would be appreciated.

What is necessary to get that, just a logcat is something I can do
on my actual device easily (no need for an emulator), it has S-OFF,
root and USB/ADB debugging and all that.

**Comment by Lineflyer** [comment] 2019-04-25 22:02
@mirabilos 
Yes, activate debug log in c:geo Settings - System
Then run the oc.de auth procedure and capture the logcat please.

**Comment by Lineflyer** [comment] 2019-04-25 22:05
Note:
The debug log might contain some keys which are personal information.
You might therefore want to replace them by placeholder and/or send the log to support@cgeo.org rather than posting it here.

**Comment by Lineflyer** [comment] 2019-04-27 12:39
Finally got ADB runing on my Android 4.4.2 phone:
```
14:31:17.977 Debug cgeo 4810  [OkHttp] GET https://www.opencaching.de/okapi/services/oauth/request_token?oauth_callback=callback%3A%2F%2Fwww.cgeo.org%2Fopencaching.de%2F&oauth_consumer_key=REMOVED&oauth_nonce=REMOVED&oauth_signature_method=HMAC-SHA1&oauth_timestamp=1556368275&oauth_version=1.0&oauth_signature=REMOVED%3D
14:31:18.085 Warning cgeo 4810  [OkHttp] Failure (62 ms) GET https://www.opencaching.de/okapi/services/oauth/request_token?oauth_callback=callback%3A%2F%2Fwww.cgeo.org%2Fopencaching.de%2F&oauth_consumer_key=REMOVED&oauth_nonce=REMOVED&oauth_signature_method=HMAC-SHA1&oauth_timestamp=1556368275&oauth_version=1.0&oauth_signature=REMOVED%3D (javax.net.ssl.SSLHandshakeException: javax.net.ssl.SSLProtocolException: SSL handshake aborted: ssl=0x63525988: Failure in SSL library, usually a protocol error
14:31:18.085 Warning cgeo 4810  error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure (external/openssl/ssl/s23_clnt.c:741 0x5da11004:0x00000000))
14:31:18.085 Error cgeo 4810  [network--9] requestToken: cannot get token
```

I assume it is because the device does not support sslv3 ?!

Strange enough that for other OC-sites the token request works normal.
Is this caused by a change on our side (as discussed above) or on OC.de?

**Comment by Lineflyer** [comment] 2019-04-27 12:49
Addition:
I tested it on the same device but using release 2019.04.04 (before the OKHTTP library change) and its working towards OC.de.

So I assume a change in that library combined with a more strict security setting on OC.de.

**Comment by mirabilos** [comment] 2019-04-27 20:13
Lars dixit:

>I assume it is because the device does not support sslv3 ?!

No, it does. But s23_clnt.c is the code for sending an SSLv2-compatible
SSLv3(=TLS) ClientHello, which OpenSSL servers without SSLv2 support do
not handle correctly (I fixed this in OpenSSL in MirBSD, but…).

The fix here is to disable SSLv2 support on the client side, so that
only SSLv3/TLSv1.0 (and later) are supported, then it will send a
“native” SSLv3 ClientHello. The easiest way to do this is to build the
bundled OpenSSL library without SSLv2 support.

**Comment by Lineflyer** [comment] 2020-02-24 19:48
I stumbled upon this issue once again as I have another user on support with this problem.
The last status was, that OC,de handshake fails due to protocol mismatch caused by OKHTTP which we use on client side.
Is there any easy fix (in contrast to the proposal by @mirabilos ) possible on our side?
Is there any potential workaround which we could ask the server side to implement?

If there is no easy fix, I would just add a FAQ entry, that OC.de usage is not possible below Android 5 with c:geo. Android 4.x support in c:geo should IMHO be dropped rather soon anyhow

**Comment by Lineflyer** [comment] 2020-02-24 19:54
@teiling88 Crossposting to you, probably you can do something on your side?!

**Comment by teiling88** [comment] 2020-02-24 20:38
@Lineflyer If I remember correctly the actual SSL-Protocol is not supported from such old Devices.

The only possible solution would be on our side to disable the ssl enforcement. And this only for very very old devices or?

**Comment by Lineflyer** [comment] 2020-02-24 20:53
This problem occurs on Android 4.x devices (this is from 2012-2014) but still in use by our users as we currently support back to Android 4.1

**Comment by mirabilos** [comment] 2020-02-24 21:36
Thomas Eiling dixit:

>@Lineflyer If I remember correctly the actual SSL-Protocol is not
>@supported from such old Devices.

No, it worked before the OC connector update, it works with
all other OC instances, and it works in other places on the
system.

(There’s also the possibility for OC.DE to lower their
requirements; they’re not a bank after all, and if they
want to be open they should be usable by many.)

**Comment by jonas-koeritz** [comment] 2020-02-24 21:43
If a device is not capable of connecting to the website at all (which would
be the case when the SSL/TLS Version isn't supported anymore or the root
CAs are not available on the device) we should not put any effort into
creating a workaround. The web has to move forward and web sites beeing
unavailable on old TLS clients will be a common problem.
c:geo should fail gracefully, notify the user and/or disable the provider
when such an exception occurs.

mirabilos <notifications@github.com> schrieb am Mo., 24. Feb. 2020, 22:37:

**Comment by jonas-koeritz** [comment] 2020-02-24 21:49
Related to #8120 (would allow upgrading OKHTTP).

**Comment by mirabilos** [comment] 2020-02-25 08:01
Jonas Köritz dixit:

>If a device is not capable of connecting to the website at all (which would
>be the case when the SSL/TLS Version isn't supported anymore or the root
>CAs are not available on the device) we should not put any effort into

But as I just told you the device is perfectly capable of doing that.

**Comment by jonas-koeritz** [comment] 2020-02-25 08:07
I already edited that comment. If the fix would be updating OKHTTP, which breaks c:geo for your Android version completely we got a problem.

**Comment by samueltardieu** [comment] 2020-02-25 09:01
cgeo for Android 4.x could become the legacy version and get fixed independently (if someone has the resources to do it) of the main version.

**Comment by jonas-koeritz** [comment] 2020-02-25 11:36
I will have a look at disabling sslv3 in our current code. Have to do it blind because I don't own such a device.

**Comment by Lineflyer** [comment] 2020-02-25 11:45
> I will have a look at disabling sslv3 in our current code. Have to do it blind because I don't own such a device.

I don't think its meaningful to go the risk of modifying this in general in our code just for the sake of some 4.4 devices trying to use OC.de.
IMHO we should rather go into the direction of cutting out 4.x versions into a legacy version as proposed by @samueltardieu and #8120

**Comment by jonas-koeritz** [comment] 2020-02-25 12:21
I tried to get to the bottom of this. This is the list of supported ciphers by opencaching.de:

- TLSv1  256 bits  ECDHE-ECDSA-AES256-SHA
- TLSv1  128 bits  ECDHE-ECDSA-AES128-SHA
- TLS11  256 bits  ECDHE-ECDSA-AES256-SHA
- TLS11  128 bits  ECDHE-ECDSA-AES128-SHA
- TLS12  256 bits  ECDHE-ECDSA-AES256-GCM-SHA384
- TLS12  256 bits  ECDHE-ECDSA-AES256-SHA384
- TLS12  256 bits  ECDHE-ECDSA-AES256-SHA
- TLS12  128 bits  ECDHE-ECDSA-AES128-GCM-SHA256
- TLS12  128 bits  ECDHE-ECDSA-AES128-SHA256
- TLS12  128 bits  ECDHE-ECDSA-AES128-SHA

This is the list of ECDSA Ciphers in `APPROVED_CIPHER_SUITES` used by our OkHttp Client:

- TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256
- TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
- TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256

So there would only be a match if the client is using TLSv1.2 wich not all phones do support. Does the phone support TLSv1.2? There might be a logcat line stating `Error while setting TLS 1.2` while c:geo is trying to explicitly enabling TLSv1.2 on a pre lollipop device. If this is the case we could potentially add `ECDHE-ECDSA-AES256-SHA` to the list of ciphers we support to fix this.

**Comment by mirabilos** [comment] 2020-02-25 12:25
Jonas Köritz dixit:

>I will have a look at disabling sslv3 in our current code. Have to do
>it blind because I don't own such a device.

Can you put it into a nightly? I’m using them anyway and
so can easily test things.

**Comment by jonas-koeritz** [comment] 2020-02-25 12:57
I just created a pull request. I'm not 100% happy with this solution as I make several assumptions about what is actually going wrong. As the website is accessible on the affected phone it has to support one of the cipher suites offered by the server.

**Comment by bekuno** [comment] 2020-02-25 21:26
The login isn´t done by parsing the website. It uses the okapi (https://www.opencaching.de/okapi/introduction.html). It seems that opencaching.de updated the opaki version.
Its now on the same version as other OC sites.

@teiling88 
Do you know differences in this area to other OC sites, eg. oc.pl or oc.ro?

@mirabilos 
Can you login on other OC sites? (maybe you can create an account there and test it?)

**Comment by teiling88** [comment] 2020-02-25 21:32
@bekuno the okapi is the same version on oc.de and oc.pl. The only for me known difference is the supported SSL version.

**Comment by mirabilos** [comment] 2020-02-26 07:49
Bernd dixit:

>@mirabilos 
>Can you login on other OC sites? (maybe you can create an account there
>and test it?)

Yes, I’m using OC.PL and Benelux as well, successfully.

**Comment by mucek4** [comment] 2020-02-27 12:50
> 
> 
> As the website is accessible on the affected phone it has to support one of the cipher suites offered by the server.

Some browswers have their own SSL implementations (like Chrome) and they support higher version of SSL even if it's not avaibile on system.

**Comment by mirabilos** [comment] 2020-02-27 19:01
mucek4 dixit:

>Some browswers have their own SSL implementations (like Chrome) and
>they support higher version of SSL even if it's not avaibile on system.

I’m not stupid… I did use the system browser.

**Comment by mirabilos** [comment] 2020-06-13 15:51
> @moving-bits commented 25 minutes ago

>We plan to cut off a new legacy version from the release we are currently preparing, and then apply the #7497 fix to it.

Where can I subscribe to status updates regarding this? Or, probably, just being notified when this is going to be closed should suffice, I guess…

Moving questions here because it’s more relevant here than in the minSDK thread…

What about data migration… I assume the “legacy” one will use a different äpp ID… so can I just dump the database and the settings from my current (Dec 2019) nightly and then import them into the legacy release then uninstall the old nightly? Or how?

**Comment by Lineflyer** [comment] 2020-06-13 16:12
The legacy version (once build) will be delivered as a normal update via Google Play if you device fits into the criteria of having a SDK version between 16 and 20.

**Comment by Lineflyer** [comment] 2020-06-13 16:15
BTW:
@mirabilos If you are using c:geos nightly versions on a device running Android <5.0 you should probably no longer use it (or stop updating it) as we just started implementing feature sets which might be incompatible with your device.

**Comment by moving-bits** [comment] 2020-06-13 16:47
> If you are using c:geos nightly versions on a device running Android <5.0 you should probably no longer use it

All new nightlies (starting yesterday) won't work any longer on systems running an Android version < 5.0, as we've increased the min SDK version and started removing old support code for legacy versions on `master` branch.

**Comment by Lineflyer** [comment] 2020-06-13 17:19
> All new nightlies (starting yesterday) won't work any longer on systems running an Android version < 5.0, as we've increased the min SDK version and started removing old support code for legacy versions on master branch.

Well, if you have the APK you can install it. AFAIR minSDK is not evaluated upon local installation but only used for version distribution systems as e.g. Google Play. 
If the app will work....thats another topic ;)

**Comment by mirabilos** [comment] 2020-06-13 17:46
Lars dixit:

>>>The legacy version (once build) will be delivered as a normal update
>>>via Google Play if you device fits into the criteria of having a SDK
>>>version between 16 and 20.

Erm yes, I don’t have Google on that device (I tried it on an identical
one with the same ROM, but it makes the whole system utterly unusably
slow even when nothing is using it). Just F-Droid, or direct APK install
(which is where I got the nightly from).

>moving-bits dixit:

>>>BTW:
>>>@mirabilos If you are using c:geos nightly versions on a device
>>>@running Android <5.0 you should probably no longer use it (or stop
>>>@updating it) as we just started implementing feature sets which
>>>@might be incompatible with your device.

Yes, that’s what I referred to above, when I said I didn’t update it for
six months already because I wasn’t clear when you’d do that.

>> All new nightlies (starting yesterday) won't work any longer on

Ah okay, yesterday then. But meh, I’ll just stick to the currently
installed version until there’s a usable release for me.

>> systems running an Android version < 5.0, as we've increased the min
>> SDK version and started removing old support code for legacy versions
>> on `master` branch.
>
>Well, if you have the APK you can install it. AFAIR minSDK is not
>evaluated upon local installation but only used for version
>distribution systems as e.g. Google Play. If the app will work....thats
>another topic ;)

Eh, I’d rather not chance it ☻

I just read somewhere that Google is killing off everything below
Windows 10, erm sorry, Android 10, by November or so. This is crazy.
Planned obsolescence. “Wir brauchen weniger haltbare Hinkelsteine.”

Thanks,
//mirabilos
-- 
<diogenese> Beware of ritual lest you forget the meaning behind it.
<igli> yeah but it means if you really care about something, don't
    ritualise it, or you will lose it. don't fetishise it, don't
    obsess. or you'll forget why you love it in the first place.

**Comment by Lineflyer** [comment] 2020-10-21 18:19
@mirabilos 
Meanwhile there is a dedicated legacy version available for Android 4.x devices.
Besides Google play it also available here on Github in https://github.com/cgeo/cgeo/releases/

Please feel free to tell us here if OC authentication has a problem with that version.

**Closed by Lineflyer** 2020-10-21 18:19 UTC
Labels: Bug, Connector OC, Regression

**Comment by mirabilos** [comment] 2020-10-21 20:30
Lars dixit:

>Please feel free to tell us here if OC authentication has a problem with that version.

“c:geo failed to initialize authorization process.”

Just installed the 2020-10-10 legacy version and restored
settings and database from backup which I made before
uninstalling the 2019-12-xx NB.

**Comment by mirabilos** [comment] 2020-10-21 20:35
Dixi quod…

>Lars dixit:
>
>>Please feel free to tell us here if OC authentication has a problem with that version.
>
>“c:geo failed to initialize authorization process.”

From logcat:

W/cgeo    ( 5903): [OkHttp] Failure (328 ms) GET https://www.opencaching.de/okapi/services/apisrv/installation?langpref=en&consumer_key=J6M7x5rNz9YFJX38fE9n (javax.net.ssl.SSLHandshakeException: javax.net.ssl.SSLProtocolException: SSL handshake aborted: ssl=0x4d8204c8: Failure in SSL library, usually a protocol error
W/cgeo    ( 5903): error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure (external/openssl/ssl/s23_clnt.c:744 0x4ba7ad74:0x00000000))

I think the problem is that the library sends an SSL23_GET_SERVER_HELLO
instead of an SSL3_GET_SERVER_HELLO (which will then make it TLSv1).

The SSL23_GET_SERVER_HELLO is an SSLv3/TLSv1 hello in a format understood
by SSLv2 servers; stock OpenSSL without SSLv2 support refuses to accept
those (I’ve patched mine to accept it, but I doubt you’d get the OC.DE
people to patch their server similarily).
