### ISSUE TITLE
Default line appearances have changed

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#8477] opened 2020-06-20 09:24 UTC
I appreciate the possibility to customize thw different line colors and widths, however it would be good if the default values would result in the same appearance that users as used to. Otherwise I assume a lot of users will think of it as a fault, beeing unaware of the new settings.

I just now thought the direction line is broken, as it was hard to see after all. From the former big red line its now only a very thin line.

**Comment by moving-bits** [comment] 2020-06-21 12:54
Are the lines smaller in current release already (due to setting the same settings for both Google Maps and OSM, using a thinner default value, see #8394 and #8369), or did they get smaller after introducing the customization (see #8447)?

**Comment by Lineflyer** [comment] 2020-06-21 21:00
Google maps does not have a routing line, so it cant be the the former default). I assume you took the trail line prefs as default for all of them?
Could we have the individual route and cache route just have the previous values as defaults?

**Comment by MagpieFourtyTwo** [comment] 2020-06-21 21:26
As @moving-bits explained a while ago. the current default values do result in the same width - at least for him. ;)

But over here we had to at least double the default values, to make them visible enough to be able to work with them again. First I thought, this may probably be a special Huawei problem (P30 Pro with Android 10.1), so they possibly handle screen density factor different, but after upgrading our Sony Xperia Z5 Premium (Android 7.1.1) this morning, it was the same: Width must at least be 12 to make the lines visible.

**Comment by moving-bits** [comment] 2020-06-22 10:16
@Lineflyer 
I'm still unsure about what version you're talking - current release or a nightly?
(So what is the "previous value" you're comparing to.)

For current release, the change is in #8394 and #8369. Up until that version Google Maps and OSM had very (!) different line settings (so no common previous value), and I unified them to a Google Maps like style. So compared to the old OSM settings, it's much thinner now. For Google Maps, it should not have changed significantly.

Line color & width customization is on current master branch only, and I've tried to use the same settings which were used after the change described in the last paragraph. But that's tested with the emulator only (and seems to work there). - I will recheck the source, if there are any other parameters which may influence the width.

**Comment by MagpieFourtyTwo** [comment] 2020-06-22 13:28
> Google maps does not have a routing line

Of course it has - at least in the nightly, which you are using as well, AFAIK.
Over here line width is set to 12 (opacity 128) - and it has the same width in GM and OSM.

Perhaps my current values may help to find appropriate defaults (width/color/opaqueness):
- history line:  18/dark brown/255 (mapline_trailcolor: -16764160)
- direction and individual route:  12/strong blue/128 (mapline_direction/routecolor-2144141108)
- trackline: 12/black/64 (mapline_trackcolor: -2147483648)
- circle frame: 12/light red/50 (mapline_circlecolor: 855572480)
- circle fill color: 12/light red/5 (mapline_circlefillcolor: 93913088)

BTW: The mainly white history line is really hard to read in walker's zoom levels 50 to 10 m in urban regions, if you set it to values which make it possible to still see the map in zoom levels 50 to 500 m (while driving). So I would suggest to draw it the same way the others are implemented, moreover as different strategies may possibly lead to confusion.

**Comment by Lineflyer** [comment] 2020-06-22 18:24
Sorry for being not precise enough:

I am talking about your latest changes in our nightlies with configurable line parameters.

> Of course it has - at least in the nightly, which you are using as well, AFAIK.

Oh, yes it has. I up to now mostly use the direction line by setting a cache/waypoint as a target from the popup on live map. This particular feature is what is not (yet) implemented on GMaps. But just now I see, that a direction line is drawn if I open a cache map. Did honestly never use the cache map with GoogleMaps for a looong time. Sorry about that.

This also means, that my experience is quite subjective as I mostly used OSM and it differs quite a bit from GMaps line parameters.

Pragmatically thinking: Should we set the new default to the mean value between small GMaps thickness and bigger OSM thickness? So the visual difference for users of each map type would be minimal.

**Comment by MagpieFourtyTwo** [comment] 2020-06-22 18:59
I still don't get where you see the difference in the line's widths between GM and OSM ... for me it looks like they display the lines with the same width ... strange.

**Comment by moving-bits** [comment] 2020-06-22 20:13
Found a bug (different formulas used for calculating default values and returning the actual values) + increased default sizes a bit => #8522.

**Comment by MagpieFourtyTwo** [comment] 2020-06-24 00:55
FYI: Lines in the map appear about five times wider after this change, at least over here,
which is a little bit more than I had expected (as divisor changed from 5 to 2).

In fact I had to divide my settings mentioned above by 4 to get where I was before
and ended up at e. g. 3 for for direction/route line.

As you additionally increased all default values by 1, defaults may possibly be too wide, now.
Perhaps @Lineflyer should test the new default values on his device,

Strange effect: Seemed to me as if the opaqueness has changed, too, had to increase all these by about 50 ...
Can't imagine how this can be ... or is it just an optical illusion?  ;)

**Comment by Lineflyer** [comment] 2020-06-24 07:28
> Perhaps @Lineflyer should test the new default values on his device,

I took a short look:
While making my proposal about possible defaults I was unaware, that the defaults are different for each line type.
Right now the individual route line looks reasonable for me, I agree that the direction line is somehow to wide.

How about setting default 10 (current default for individual route) for all types and then thats it?

I also see a difference between Google and OSM regarding the drawing mode (or is this the mentioned opaqueness?). On OSM it are dots with lines whereas on Google its a smooth line. Screenshots below might explain better.

Here is the current look:
![Screenshot_20200624-092029_cgeo](https://user-images.githubusercontent.com/949669/85514864-c5044980-b5fc-11ea-89b8-0c9da6978a68.jpg)
![Screenshot_20200624-092001_cgeo](https://user-images.githubusercontent.com/949669/85514866-c6357680-b5fc-11ea-9dc9-cd3e3417b279.jpg)

**Comment by moving-bits** [comment] 2020-06-27 07:46
> I also see a difference between Google and OSM regarding the drawing mode (or is this the mentioned opaqueness?). On OSM it are dots with lines whereas on Google its a smooth line. Screenshots below might explain better.

I've created #8531 to avoid this effect on OSM. Reason for this was that we used single line entities on OSM maps instead of a path - no problem as long as we've been drawing with full opaqueness, but clearly visible when using partial transparency.

**Comment by moving-bits** [comment] 2020-06-27 07:50
@Lineflyer 

Different question: Some proposed to draw the history trail like any other line, meaning a single line only, not a combination of line + underlying "shadow" we do currently.
(Today's solution is actually just drawing two lines on top of each other, the top one being half the width of the "shadow", resulting in this "two thin separate lines" effect, which only really works with full opaqueness.)

Proposal is to drop the "shadow", making it a regular line.

This could be combined with setting all default widths to the same value.

**Comment by Lineflyer** [comment] 2020-07-14 19:31
@moving-bits 
I have a preference on this (in fact I rarely use the history track).
But keeping the principle of a consistent UI, we should make it just the same as all other lines and configurable as just recently implemented like the other lines.

**Comment by moving-bits** [comment] 2020-07-14 19:53
> But keeping the principle of a consistent UI, we should make it just the same as all other lines and configurable as just recently implemented like the other lines.

Ok, created #8640 for this.

**Comment by Lineflyer** [comment] 2020-07-29 21:40
@moving-bits This is solved, isn't it?

**Comment by MagpieFourtyTwo** [comment] 2020-07-30 13:29
I guess, this question can only be answered by a "real world user" with a fresh installation ... as e. g. the emulator seems to report a significantly different value for screen density, which results in way wider lines ...

As for me: I have set the lines configuration on an Xperia Z5 lately (a week ago or so), and I had to tweak all of them until they met the user's expectations ... but high density displays may be different anyway, as I had major problems with the P30Pro, too, so testing on mine would probably not be really meaningful.

Don't know which device you're using, but maybe it's more "normal", so, perhaps you may test yourself, by saving your settings, re-installing c:geo and before restoring your settings backup have a look at the map how lines are shown on your device ...?

**Comment by moving-bits** [comment] 2020-07-30 20:24
I'm in favor of closing this, as the original issue and most/all? of the subsequent issues have been taken care of. The last article IMHO points to a difference coming from the switch from fixed width line to density-related width which is a bit older than making the widths configurable, so strictly speaking no regression. - Let's see how the current setting works, and open fresh issues on demand.

**Closed by moving-bits** 2020-07-30 20:24 UTC
