### ISSUE TITLE
Map view zoom level reset on many occasions

### ISSUE THREAD

**Issue by mirabilos** [cgeo/cgeo#8073] opened 2020-01-13 23:31 UTC
**Describe the bug:**

Since a few weeks (NBs), the map zoom level is reset often. (regression)

This issue is related to #7953 and #5087 but more encompassing.

**To Reproduce:**
Steps to reproduce the behavior: do one of these:

- tap Live Map in the main menu
- tap (or long-tap, by default, but I configure map on short tap) the navigation rose icon when in cache details
- within an existing map view, use the menu to select another map, online or offline

For #5087 it’s slightly different: be in a list view and click the “view *this* list on the map” icon.

**Actual behavior/state after performing these steps:**

The zoom level changes immediately.

**Expected behavior/state after performing these steps:**

For switching between different maps (online (which is #7953) or offline) while already being in a map view, the zoom level must be kept. (Of course, if it’s below the minimum or above the maximum for a map (it’s annoying that online maps can’t be zoomed in this far, but understandable), it needs to be adjusted to become within valid bounds.

For the other two (starting Live Map, and navigating using the map view to a cache), the previous behaviour was that different zoom levels for these two were remembered, and when going out and going in again, that zoom level was reused. The new behaviour always starts at a specific zoom level, which may be intended but is not configurable. Ideally, starting zoom levels for these two should be configurable, and the old behaviour (just keep the previous setting) one of the options.

For the “view *this* list on the map now!” (#5087) it’s not as easy. Certainly, the behaviour of “adjust zoom level to the largest one that shows all caches on the list” is very desirable. However, if you have a list of caches clustered, plus just one in another city (e.g. because I have to switch trains there), this can be annoyingly much out. Perhaps, having two buttons, one with the existing behaviour, and one with the same behaviour as these described above (ideally using the same (remembered or configured) zoom level as going to the Live Map would use).

**Version of c:geo used:**

2019.11.22-NB-…

**Is the problem reproducible:**
Yes

**Comment by Lomanic** [comment] 2020-01-14 08:00
Duplicate of #8068?

**Comment by mirabilos** [comment] 2020-01-14 16:57
Not a duplicate, and I haven’t had these symptoms with Mapsforge maps, but perhaps all of them are related somehow.

**Comment by moving-bits** [comment] 2020-01-15 20:22
@mirabilos 

Is this OSM only, or is Google Maps affected as well?

**Comment by mirabilos** [comment] 2020-01-20 01:40
moving-bits dixit:

>Is this OSM only, or is Google Maps affected as well?

I tried Google Maps, but it doesn’t work at all, so I cannot say.

Incidentally, switching back and forth multiple times decreases
the zoom level further each time at least twice (10m, then 4m),
so perhaps there’s some mistake instead of a deliberate change…

**Comment by moving-bits** [comment] 2020-01-20 17:35
> Incidentally, switching back and forth multiple times decreases the zoom level further each time at least twice (10m, then 4m), so perhaps there’s some mistake instead of a deliberate change…

Hm, strange. If I start with live map from main screen, I start with 200m in OSM. Switching to GM leads to 60m. Beginning from that I can switch between the two and always get the same zoom level. (It's still a bug, but at least with a constant mismatch of two zoom levels.)

**Comment by MagpieFourtyTwo** [comment] 2020-01-20 18:34
Same over here.
Add. these things:
- map center moves forth and back sometimes
  (correctly centered in OSM/OpenAndroMaps, off center to south east in Google Map/Sat)
- assuming a cache with several waypoints, OSM/OAM map will of course be "off center"
   (as a result of this very questionable "AutoZoom" function to show all waypoints,
   even when starting from the listing page's compass rose),
   but when switching to Google Sat in this view,
   the red line to the cache will no longer end at the cache
   but in the center of the map ... somewhere in the wild ...

**Comment by Lineflyer** [comment] 2020-01-20 20:16
> assuming a cache with several waypoints, OSM/OAM map will of course be "off center"
> (as a result of this very questionable "AutoZoom" function to show all waypoints,
> even when starting from the listing page's compass rose),
> but when switching to Google Sat in this view,
> the red line to the cache will no longer end at the cache
> but in the center of the map ... somewhere in the wild ...

I heard the same today on support mail.
@YCan you please open a dedicated issue for this problem? That would be great also to track this seperately.

**Comment by MagpieFourtyTwo** [comment] 2020-01-20 21:53
Ok - but which one? I in fact adressed three major bugs (as I would call it) over here:
1. weird AutoZoom (BTW: have a look at [this screenshot](https://user-images.githubusercontent.com/9889015/72759580-67477d80-3bd6-11ea-88a2-483ec735468c.jpg) for a story telling example)
2. Google Map/Sat getting off center (compared to OSM/OAM)
3. Routing line to cache points to center of map (resp. to center of the waypoints mentioned in 1.)

;)

**Comment by moving-bits** [comment] 2020-01-20 21:56
> Ok - but which one? I in fact adressed three annoying bugs (as I would call it) over here:

That would result in three separate new issues, then :-)

**Comment by MagpieFourtyTwo** [comment] 2020-01-20 23:07
Ok, tomorrow then.  As for now:

>     3. Routing line to cache points to center of map (resp. to center of the waypoints mentioned in 1.)

it in fact is *not* the center of the map, but the center of the waypoints.

Just had a cache with just two waypoints (Start and Final) and the red line on Google Map *always* ends exactly in the middle between these two (BTW: no matter if GM has been opened from the listing page's compass rose, from the one in the Waypoint list or has just been switched to fro OSM/OAM). Switching back to OSM/OAM brings the red line back to the cache's coordinates (i. e. Final), whereas going back to GM puts the red line between these two points again ...

**Comment by Lineflyer** [comment] 2021-12-26 13:44
@mirabilos 
Can you double check if your issue is still relevant.
Seeing that #7093 is fixed and I cannot reproduce it for switching the map sources any longer, I suggest to close here.

**Comment by Lineflyer** [comment] 2021-12-26 13:44
Please reopen if you still see this problem.

**Closed by Lineflyer** 2021-12-26 13:44 UTC
Labels: Bug, Unverified
