### ISSUE TITLE
Map Themes

### ISSUE THREAD

**Issue by Willabee** [cgeo/cgeo#4573] opened 2015-01-01 13:44 UTC
In the past, downloaded maps and themes from openandromaps with no problems. Now, the maps are OK but selecting any theme other than the default theme causes no map to be visible. Just caches and current location are visible.

**Comment by rsudev** [comment] 2015-01-01 13:59
So obviously they changed something....
I use those maps and themes as well, but did not download anything fresh the last month, will give it a check.

**Comment by Lineflyer** [comment] 2015-01-01 22:04
I use the most recent openandromaps map of Germany with the delivered themes (those for Locus).
All is working well for me.
Can you give more details about what map, what theme is not working?

**Comment by Willabee** [comment] 2015-01-02 23:21
Great Briton map and Locus themes.

**Comment by Willabee** [comment] 2015-01-03 13:31
Also tried on another previously working device which now is broken. All themes are selectable but only the default theme displays the map.

**Comment by Lineflyer** [comment] 2015-01-04 22:05
> Also tried on another previously working device which now is broken.

Does this mean it started with an update of c:geo or did you also install new maps/themes on that device.

**Comment by Lineflyer** [comment] 2015-01-04 22:29
I just tried this download:
http://www.openandromaps.org/maps/europe/Great_Britain.zip

The map itself and the delivered andromaps themes are working flawless.
 @Willabee Are you sure you copied the themes correctly including XML and all graphic ressources in subdirectories as contained in the *.zip?

**Comment by Willabee** [comment] 2015-01-05 10:24
c:geo is latest version. Everything copied from zip file. The only difference is the maps go in a 'maps' folder and all the theme folders go in a 'themes' folder, that is, all the sub-folders from within 'andromaps_locus' are copied into 'themes'. c:geo is correctly mapped to these folders (maps and themes). The maps work perfectly with the default theme but disappear when any of the downloaded themes are selected. The themes are the Locus versions. Everything is on an external SD card.

**Comment by Lineflyer** [comment] 2015-01-05 13:20
Same setup here is working.
Can you please check (or redownload) the newest source from 
http://www.openandromaps.org/maps/europe/Great_Britain.zip

I do see this as some kind of device issue at the moment as we can not reproduce the behavior and also the themes are unchanged comparing version from mid 2014 and end of 2014 (despite of some graphic icons).

**Comment by Willabee** [comment] 2015-01-05 22:53
Re-downloaded but still same behaviour.

**Comment by Lineflyer** [comment] 2015-01-06 20:55
I am little clueless here, because we use the same maps/themes and same version of c:geo.
@rsudev Would a debug log show anything in this case?

**Comment by Willabee** [comment] 2015-03-22 19:58
I think it may have something to do with c:geo locating the themes folder on the external SD card. Could c:geo not auto locate the themes folder in the same way that it finds GPX files and offline maps.

**Comment by rsudev** [comment] 2015-03-22 21:00
No, it cannot, because themes don't have a specific extension. and it would also not help, because as long as you can select another theme c:geo has located it correctly. So either the theme is damaged/broken/not working or some files belonging to the theme are not working.
I just download again the map of great britain and unpacked the map and the andromaps_locus theme package from within there into a folder on my device and selected the appropriate folders in the settings. Everything worked.
Then I renamed the 'patterns' subfolder of the theme I tried to something else and tired the map again - blank.
So please verify, that the theme you selected on your device really is complete (symbols folder with files therein, additionally patterns folder with the complete set of files).
If that doesn't help, please post a screenshot of your map settings, which theme you selected and which files and folders (file count in each) you have on your device and in which folder they reside.

**Comment by Willabee** [comment] 2015-04-02 15:01
Success. Previously, I had been using Airdroid to copy across all the extracted files. This time, I used a USB connection, which wanted confirmation of any .xml files. Now all is fine.

Thanks for your re-assurance that it should work.

As an aside, do you keep all the locus themes, or are just one or two of them sufficient for geocaching?

**Comment by Lineflyer** [comment] 2015-04-02 15:12
@Willabee 
Thanks for your feedback.
So it seems, that the previously used tool corrupted the files in some kind.

Regarding what themes to be used:
That is a pure personal preference. I myself do use themes provided by openandromaps.org as they have isohypses which is good for hiking and offer a light theme with less details and focus on hiking trails.

Closing.

**Closed by Lineflyer** 2015-04-02 15:12 UTC
Labels: Bug, Unverified

**Comment by SammysHP** [comment] 2015-04-02 17:46
Many maps require special themes to render correctly, e.g. "Freizeitkarte".
