### ISSUE TITLE
No login with Android 4.0.x (e.g. Garmin Monterra)

### ISSUE THREAD

**Issue by Monterra** [cgeo/cgeo#7079] opened 2018-07-07 08:43 UTC
##### Detailed steps causing the problem:
Since 2 days my Garmin Monterra GPS, Android 4.0.4, newest firmware can not log on to geocaching.com in the mainscreen of Cgeo
I tried everything mentioned in http://faq.cgeo.org/#login-failed but still no luck.
If I tell Cgeo to connect to the website everything works fine and I am connected to geocaching.com and my account.
If I tell Cgeo, after trying to verify my login credentials, to make a new account, I am instantly connected to the geocaching.com website and automatically logged on to my account.
I tried Pocket Query Creator. This app returns with the message that there is something wrong with an SSL 
My browser (Chrome) connects to the geocaching.com website perfectly.

I use the latest version of Cgeo (2018.06.26)

##### Is the problem reproducible for you?
Yes

##### System information:
```
Attach system information here if available (see c:geo menu -> About c:geo -> Swipe right to System)
Keep the apostrophe at beginning and end to have it properly formatted
```

**Comment by pstorch** [comment] 2018-07-07 11:11
Can you try build in browser (not Chrome)?
I guess it is a duplicate of #7078 and #5800

**Comment by Monterra** [comment] 2018-07-07 11:29
Hi Peter,
I have no built in browser. Only Chrome.

Op za 7 jul. 2018 11:11 schreef Peter Storch <notifications@github.com>:

**Comment by pstorch** [comment] 2018-07-07 11:50
Hmm, the problem with Chrome is that it has its own tls Stack, but c:geo uses the system implementation.

**Comment by Monterra** [comment] 2018-07-07 15:15
Strange thing is that Cgeo logs on fine if you tell it to contact the
geocaching website from the menu.


Op za 7 jul. 2018 11:50 schreef Peter Storch <notifications@github.com>:

**Comment by pstorch** [comment] 2018-07-07 20:35
> Strange thing is that Cgeo logs on fine if you tell it to contact the geocaching website from the menu.

Hmm, I'm not sure if I understand completely. What menu item exactly?

**Comment by Monterra** [comment] 2018-07-08 08:17
I mean the menu:
Main screen / Settings / Services / Geocaching.com / Open website
And also:
When entering the login details for geocaching.com, you can choose: Create
account. That connects you to the website too

Op za 7 jul. 2018 20:35 schreef Peter Storch <notifications@github.com>:

**Comment by Monterra** [comment] 2018-07-08 08:48
Yes, it uses https

Op zo 8 jul. 2018 08:24 schreef Peter Storch <notifications@github.com>:

**Comment by pstorch** [comment] 2018-07-08 09:31
> Garmin does not seem to maintain their devices.. :(

And it was supposed to be a premium device

**Comment by Lineflyer** [comment] 2018-07-08 09:33
I posted a notification on FB and G+ regarding login problems for API 14

**Comment by Lomanic** [comment] 2018-07-08 14:29
> I mean the menu:
Main screen / Settings / Services / Geocaching.com / Open website

This menu opens the website in a dedicated browser (Chrome for example), not a webview. That's why it works, it doesn't use the system TLS implementation.

If you really want to open geocaching.com in a webview, you can install [RedReader](https://github.com/QuantumBadger/RedReader) and open any of [these links](https://old.reddit.com/domain/geocaching.com/) inside it.

**Comment by mucek4** [comment] 2018-07-08 16:36
@Monterra It's not the c:geo that logs in to GC.com, but a cookie in browser. If I follow your link with chrome I am logged in. If I do it with Firefox It asks for password as I never submitted credentials in Firefox on mobile.
I'll close this issue as #7078 is identical and it contains more technical info.

**Closed by mucek4** 2018-07-08 16:36 UTC
Labels: Bug

**Comment by Monterra** [comment] 2018-07-09 08:31
Hi Peter, I see my post is closed because it appeared to be similar to
another post. Being new here and not very familiar with forums, I would
like to know how to continue. I will address Geocaching HQ because I can
not login on their website, Garmin because they leave their
Monterra-customers without any form of support. And I will ask a friend if
he can provide me with a work around. I have been trying some other things.
I downloaded a pocketquery ftom geocaching.com and imported it into Cgeo.
Than, in the list- menu clicked "refresh" and..... Cgeo connected to
geocaching.com and refreshed the caches. I have the impression fixing the
problem I, and other Monterra users, have can be easily solved. Thanks a
lot for your help.

Op zo 8 jul. 2018 08:24 schreef Peter Storch <notifications@github.com>:

**Comment by pstorch** [comment] 2018-07-09 08:42
@Monterra the discussion continues in issue #7078, because it affects all devices < Android 4.1. You can follow the discussion there.

My personal opinion is that GS has done the right thing to increase the security level of their TLS implementation and discard insecure protocol versions. I think it's more an issue of Garmin who don't support their premium devices with updates anymore.

**Comment by mucek4** [comment] 2018-07-09 08:43
We will see if we can fix the app. You can try official GC app, but I think it will not work. Subscribe to other issue and you will receive notifications.

**Comment by Monterra** [comment] 2018-07-09 14:51
Indeed, the official GC-app does not work on the Monterra. Already tried
that. I will subscribe to the other thread. Thanks

Op ma 9 jul. 2018 08:43 schreef mucek4 <notifications@github.com>:

**Comment by mucek4** [comment] 2018-07-10 19:55
@Monterra can you please paste sysinfo shown in c:geo unser Menu - About c:geo - Swipe to "System".

**Comment by Monterra** [comment] 2018-07-10 20:17
Is this wat you need?

--- System information ---
Device: Monterra (monterra_us, Garmin)
Android version: 4.0.4
Android build: IMM76D
c:geo version: 2018.06.26
Google Play services: enabled - 12.6.85 (000300-197041431)
Low power mode: inactive
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: rotation vector
Hide own/found: false
Map strategy: auto
HW acceleration: disabled (default state)
System language: nl_NL
System date format: dd-MM-yyyy
Debug mode active: no
System internal c:geo dir: /data/data/cgeo.geocaching (3,7 GB free) internal
User storage c:geo dir: /mnt/sdcard/cgeo (3,7 GB free) external
Geocache data: /mnt/sdcard/Android/data/cgeo.geocaching/files/GeocacheData
(3,7 GB free) external
Database: /data/data/cgeo.geocaching/databases/data (456,0 KB) on system
internal storage
Fine location permission: granted
Write external storage permission: granted
Geocaching sites enabled:
   geocaching.com: Not logged in (Geen login informatie opgeslagen)
Geocaching.com date format: MM/dd/yyyy
Installed c:geo plugins:  none
--- End of system information ---

Op 10 jul. 2018 19:55 schreef "mucek4" <notifications@github.com>:

**Comment by mucek4** [comment] 2018-07-11 11:08
Yes, thank you. The problem is I can't find any old device with Android 4.0.x for testing if a fix can be made.

**Comment by Monterra** [comment] 2018-07-11 11:10
Well, if I can help, let me know

Op wo 11 jul. 2018 11:08 schreef mucek4 <notifications@github.com>:
