### ISSUE TITLE
[Nightly] Live Map crash with OSM and OpenAndroMaps

### ISSUE THREAD

**Issue by MagpieFourtyTwo** [cgeo/cgeo#8126] opened 2020-02-14 18:31 UTC
**Describe the bug:**
When Live Map shows a reasonable amount of caches, moving the map around crashes the map.

**To Reproduce:**
1. open e. g. GC7NDVZ
2. open map view by e. g. clicking listing page's compass rose
3. select an offline map (I tested OSM and two different OpenAndroMaps)
4. zoom out to a scale of 2 km
5. activate "update map" (as for me I see 364 caches right now)
6. move the map around a bit ... (500 m west then 1000 back east is sufficient over here)
7. crash ... then listing page will be shown

**Version of c:geo used:**
2020.02.14-NB-7d86095

**Is the problem reproducible:**
Yes

**System information:**
```
--- System information ---
Device: VOG-L29 (VOG-L29EEA, HUAWEI)
Android version: 10
Android build: VOG-L29 10.0.0.178(C431E19R2P5)
c:geo version: 2020.02.14-NB-7d86095
Google Play services: disabled - 20.04.14 (120400-294335909)
Low power mode: inactive
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: rotation vector
Hide own/found: true
HW acceleration: enabled (default state)
System language: de_DE
System date format: dd.MM.yy
Debug mode active: no
System internal c:geo dir: /data/user/0/cgeo.geocaching (24,4 GB free) internal
User storage c:geo dir: /storage/emulated/0/cgeo (24,4 GB free) external non-removable
Geocache data: /storage/emulated/0/Android/data/cgeo.geocaching/files/GeocacheData (24,4 GB free) external non-removable
Database: /data/user/0/cgeo.geocaching/databases/data (263,9 MB) on system internal storage
Fine location permission: granted
Write external storage permission: granted
Geocaching sites enabled:
   geocaching.com: Logged in (Anmeldung OK) / PREMIUM
   extremcaching.com: Logged in (Anmeldung OK)
Geocaching.com date format: dd MMM yy
Installed c:geo plugins: contacts
--- End of system information ---
```

**Additional context:**
Maps used are current OSM (online) and OpenAndroMaps "Germany_South" and "Baden-Wuerttemberg" (offline) as of June 2019, as well as current BaWü, freshly downloaded at http://download.openandromaps.org/mapsV4/Germany/baden-wuerttemberg.zip (as of 29/01/2020) - the latter takes some more moves, but crashes at the end, too. The more caches are displayed, the sooner the map crashes.

**Comment by MagpieFourtyTwo** [comment] 2020-02-20 10:50
Gets worse and worse ... moving map around while it has nothing else to display than just the current cache works like a charm, but as soon as I set "Enable Map Update" (i. e. enable "Live Map"), it takes just a few moves and c:geo crashes and restarts with the listing page of the cache, where I initially came from.

It is not even necessary to zoom out, even giving the map some time to finish it's update does not help anymore. All it needs, is a reasonable amount of cache symbols displayed (right now a dozen is more than enough) and then just a few moves of sometimes a kilometre and sometimes just a few meters are "sufficient" to let the crash happen.

I even set up some test scenarios like:
- doing this while moving (in the car) and while sitting still in a room
- with "Routing" set to "Car" or "Bee line"
- with "Show Track History" enabled, deleted, completely disabled
- with OpenAndroMaps BaWü, DE South, OSM
- ...

None of the above makes a difference, I would not even say that these factors make a difference with regard to the number of moves or wiping speed "needed" to crash it, although this is hard to say, cause intensity or distance of necessary moves is not deterministic.  Only thing which seems to be constant: The more cache symbols are displayed, the faster it crashes. But sometimes even three symbols are sufficient ...  :(

Moreover I have the (unverified) *impression* that it happens even faster, when moving forth and back.

Ah, yes: With Google Maps and Google Sat View everything is fine (apart from this "Route line goes into the middle of all waypoints", what in fact makes these Maps unusable for moving to a cache, too), but with these the map can be moved hassle-free, even with thousands of cache symbols displayed.

Just tried the following: Displaying Live Map at my current position, but map for "Austria" activated, thus there is no map to be rendered on the current screen - nevertheless the crash happens. Even if I directly start Live Map from it's dedicated start screen button. It just takes a little bit longer and some more moves.

Any idea?

**Comment by moving-bits** [comment] 2020-02-20 18:05
Thanks for further testing. Sadly, I still cannot reproduce the problem here. I have tested again with today's master and release branches as well as with current release. Started with a single cache, opened map, activated "enable live", and set a zoom factor to display something between 300 and 800 caches. Then started moving around l/r/u/d, but even after 20+ rapid moves everything works as expected.

Maybe a logcat can give us some hints which direction to look further.

@Lineflyer  I think I remember you had written sometime that you've produced a logcat on a physical mobile. Can you describe how to? Thx!

**Comment by bekuno** [comment] 2020-02-20 20:06
I can reproduce it on my Samsung S3 (Android7). 
I will check it.

**Comment by bekuno** [comment] 2020-02-20 20:22
Here is the exception:
~~~
 E/MessageQueue-JNI: java.lang.ArrayIndexOutOfBoundsException: length=401; index=404
        at java.util.concurrent.CopyOnWriteArrayList.get(CopyOnWriteArrayList.java:121)
        at org.mapsforge.map.layer.Layers.get(Layers.java:336)
        at org.mapsforge.map.android.input.TouchGestureHandler.onScroll(TouchGestureHandler.java:241)
        at android.view.GestureDetector.onTouchEvent(GestureDetector.java:634)
        at org.mapsforge.map.android.view.MapView.onTouchEvent(MapView.java:446)
        at cgeo.geocaching.maps.mapsforge.v6.MfMapView.onTouchEvent(MfMapView.java:110)
        at android.view.View.dispatchTouchEvent(View.java:10717)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2859)
~~~

Maybe this refers to 
https://github.com/mapsforge/mapsforge/issues/1114
and  Issue #7034 ?

**Comment by Lineflyer** [comment] 2020-02-20 20:26
I can not reproduce this scenario on my Android 10 device using the sequence described in the initial posting. But #7034 happens for quite some users. No idea, under which circumstances this happens.

**Comment by bekuno** [comment] 2020-02-20 20:30
There is on more exception later in the logcat:
~~~
 E/TileDownloadThread: SSL handshake timed out
    java.net.SocketTimeoutException: SSL handshake timed out
        at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
        at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:364)
        at com.android.okhttp.Connection.connectTls(Connection.java:1510)
        at com.android.okhttp.Connection.connectSocket(Connection.java:1458)
        at com.android.okhttp.Connection.connect(Connection.java:1413)
        at com.android.okhttp.Connection.connectAndSetOwner(Connection.java:1707)
        at com.android.okhttp.OkHttpClient$1.connectAndSetOwner(OkHttpClient.java:133)
        at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:466)
        at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:371)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:503)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:438)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getHeaders(HttpURLConnectionImpl.java:166)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getHeaderField(HttpURLConnectionImpl.java:210)
        at java.net.URLConnection.getContentEncoding(URLConnection.java:522)
        at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getContentEncoding(DelegatingHttpsURLConnection.java:142)
        at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getContentEncoding(HttpsURLConnectionImpl.java)
        at org.mapsforge.map.layer.download.TileDownloader.getInputStream(TileDownloader.java:34)
        at org.mapsforge.map.layer.download.TileDownloader.downloadImage(TileDownloader.java:71)
        at org.mapsforge.map.layer.download.TileDownloadThread.downloadTile(TileDownloadThread.java:81)
        at org.mapsforge.map.layer.download.TileDownloadThread.doWork(TileDownloadThread.java:60)
        at org.mapsforge.map.util.PausableThread.run(PausableThread.java:149)
 E/ContactsProvider_EventLog: Flush buffer to file cnt : 1 size : 1Kb duration : 4ms lastUpdatedAfter : 60105 ms mFlush_time_threasold : 2000 mCurrentSize : 796
~~~
I don't know if it related to the crash or a result of it.

**Comment by bekuno** [comment] 2020-02-20 20:50
Also this crash with okhttp:3.14.6:
~~~
 E/AndroidRuntime: FATAL EXCEPTION: main
    Process: cgeo.geocaching, PID: 6920
    java.lang.ArrayIndexOutOfBoundsException: length=178; index=178
        at java.util.concurrent.CopyOnWriteArrayList.get(CopyOnWriteArrayList.java:121)
        at org.mapsforge.map.layer.Layers.get(Layers.java:336)
        at org.mapsforge.map.android.input.TouchGestureHandler.onScroll(TouchGestureHandler.java:241)
        at android.view.GestureDetector.onTouchEvent(GestureDetector.java:634)
        at org.mapsforge.map.android.view.MapView.onTouchEvent(MapView.java:446)
        at cgeo.geocaching.maps.mapsforge.v6.MfMapView.onTouchEvent(MfMapView.java:110)
        at android.view.View.dispatchTouchEvent(View.java:10717)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2859)
~~~

**Comment by MagpieFourtyTwo** [comment] 2020-02-20 20:59
Thx for dealing with this issue - pls let me know if I can be of any help.

**Comment by moving-bits** [comment] 2020-02-23 21:32
@rsudev 
Looking at the Logcat it might be connected to layer handling of NewMap. Can you possibly crosscheck the recent (since last release 2019-12-30) changes to NewMap, whether they miss something necessary for the internal workings of NewMap?

**Comment by Lineflyer** [comment] 2020-02-24 21:32
I did my very best trying to reproduce this, but keep failing with release and nightlies.
But as said #7034 exists on our crash reports, but there seem to be some special situations or prerequisites where this exists.

**Comment by MagpieFourtyTwo** [comment] 2020-02-25 23:18
Would you please try the following:
- open any cache
- display on OSM or OpenAndroMap
- zoom out to 2 km
- activate map update (a few hundred caches increase "chance" of crash)
- write one or two big figure 8s on the screen
Over here the map crashes every single time: With 300 cache symbols most of the times when the first 8 figure is nearly complete. With this many symbols I had not a single time where the second 8 had at least a chance to start. With ~15 caches on display, one and a quarter 8 figure is possible. And if there are no symbols at all (and just map), I can draw 8s till the end of time without any crash at all ...

Same applies to direct call of Live Map, just takes one or two 8 figures more ...  :/

BTW: Made the same test with a Sony Xperia Z5 Premium (Android 7.1, IIRC), same nightly, with the very same result.

**Comment by Lineflyer** [comment] 2020-02-29 22:46
I tried with you sequence but failed, however today I was out caching (on the MEGA in Bonn) and suddenly this problem appeared in a certain region where I was  using the live map. 

I was still unable to determine the exact conditions which need to apply. I was using the same map file and app version, just another combination of saved caches and region. 
Due to the fact, that the Google Play reports showed similar stack traces in the past versions of c:geo already but I did see this problem the first time ever, I tend to think, that this problem is there since a longer time but now triggering more often or under other conditions.

I will take a deeper look into our beta crash reports and try to estimate whether the appearance increased in our beta compared to the current live version.

**Comment by MagpieFourtyTwo** [comment] 2020-03-01 00:47
Stumbled upon your "saved caches" and thought, it would probably be interesting to make another test:
- activated Google Map
- swiped to a region where I have no saved caches at all, but an installed OpenAndroMap (in fact: near Graz, AT)
- activated OpenAndroMap AT
- activated "Map Update" (resulted in about 100 caches)
- drawed my 8 figure
- crash after about three quarters of the 8 figure

After that I even deleted all my saved caches and did the same again. Result:
- crash after about half of the 8 figure

I'm not pretty sure if this gives add. info, as I don't know exactly, when c:geo *really* deletes a "deleted" saved cache, but based on my limited knowledge I would say, the crashes are not primarily related to displaying saved caches, but to displaying cache symbols at all.

BTW: If I delete c:geo's data from Android App settings, will *everything* be back, i. e. as it was before, after restoring the backup? Had in mind that some settings have to be rebuilt by hand ... but I'm not sure ... (and I of course don't want to lose anything ;) ).

**Comment by MagpieFourtyTwo** [comment] 2020-03-01 18:38
Nevertheless, it seems as if the whole thing depends on speed, too: The faster I move the map, the faster c:geo crashes. Moving it just a few millimeters per touch, c:geo stays alive way longer ...

What seems to be consistent with the observation that the more caches are displayed, the faster (and more reliable) the crash comes.

**Comment by MagpieFourtyTwo** [comment] 2020-03-01 18:43
Ah, yes: With "Old Mapsforge v3" set, the crash does not happen.
Or at least not in a reasonable count of 8 figures.

**Comment by jakedot** [comment] 2020-03-01 19:04
I have observed frequent crashes of the map too. What intrigued me was that
with the 161m circles enabled, some circles seem to get a deeper shade of
red - maybe something with the waypoints getting duplicated in the
background? Might fit in with the IndexOutOfBoundsExceptions... I could not
make out an obvious reason for getting a 'multiple circle', but it seemed
to happen more often to caches with final/physical stage waypoints at the
headers. Sometimes only after opening the listing for the first time.
Closing and reopening the map seems to reset it.

I'm using the Freizeitkarte AUT+ map and my device info is attached.

--- System information ---
Device: SM-J415FN (j4primeltecis, samsung)
Android version: 9
Android build: PPR1.180610.011.J415FNXXU5BSL2
c:geo version: 2020.02.24-RC
Google Play services: enabled - 20.04.14 (100300-294335909)
Low power mode: inactive
Compass capabilities: no
Rotation vector sensor: absent
Orientation sensor: absent
Magnetometer & Accelerometer sensor: absent
Direction sensor used: magnetometer & accelerometer
Hide own/found: true
HW acceleration: enabled (default state)
System language: de_AT
System date format: dd.MM.yy
Debug mode active: no
System internal c:geo dir: /data/user/0/cgeo.geocaching (10,2 GB free)
internal
User storage c:geo dir: /storage/emulated/0/cgeo (10,2 GB free) external
non-removable
Geocache data:
/storage/emulated/0/Android/data/cgeo.geocaching/files/GeocacheData (10,2
GB free) external non-removable
Database: /data/user/0/cgeo.geocaching/databases/data (80,4 MB) on system
internal storage
Fine location permission: granted
Write external storage permission: granted
Geocaching sites enabled:
   geocaching.com: Logged in (Anmeldung OK) / PREMIUM
Geocaching.com date format: dd/MM/yyyy
Installed c:geo plugins: contacts
--- End of system information ---

**Comment by moving-bits** [comment] 2020-03-01 21:07
I was able to reproduce this for the first time (using current master, in emulator). Some observations:
- Does not happen when coming from a stored list, with either "live enabled" or not.
- Does not happen when "waypoint limit" set to 0.
- Only happens when using "live map" from c:geo main screen, having set "waypoint limit" to > 0, with either "lime enabled" switched on or off.

Can someone confirm this?

**Comment by Lineflyer** [comment] 2020-03-01 21:33
> Does not happen when "waypoint limit" set to 0.

I always use a limit >0, so it could be a factor.

**Comment by MagpieFourtyTwo** [comment] 2020-03-01 23:37
> I was able to reproduce this for the first time (using current master, in emulator). Some observations:
>     * Does not happen when coming from a stored list, with either "live enabled" or not.

Over here:
- "live disabled": does not crash
- "live enabled": does crash on the very first half 8 figure

>     * Does not happen when "waypoint limit" set to 0.

Changing "waypoint limit" has no effect at all over here.
Tested with Live Map and coming from a stored list.

>     * Only happens when using "live map" from c:geo main screen,
>       having set "waypoint limit" to > 0,
>       with either "lime enabled" switched on or off.

Nop, does crash in any starting scenario for "live enabled" I've tested (and I can think of).
As soon as "live enabled" is set, it's just a matter of time (resp. movement) till it crashes,
no matter from where I have entered the map page.
Only thing that seems to prevent the crash over here is using Mapsforge v3.

**Comment by Lineflyer** [comment] 2020-03-14 21:05
Any idea for this one?

I can more or less confirm (having used the current release and the nightlies over the last week), that the problem came in to the code (or the exiting underlying problem changed its frequency of occurrence) after 008d5eecd9df8d350ccdc7c1baf8d65182c4373d

**Comment by jonas-koeritz** [comment] 2020-03-14 21:11
I did a quick fix for this, but it's really dirty and just catches the exception...I didn't investigate what the root cause is.

**Comment by moving-bits** [comment] 2020-03-14 21:17
I've written to @rsudev and asked him to look at the map changes between December release and current master - maybe he can spot the trigger.

**Comment by moving-bits** [comment] 2020-03-27 21:34
I've dug deep into the code during the last days, and to me it currently looks like a synchronization problem with the layers - adding / removing map layers (= geoitems) overlaps with handling the scroll/move touch events reading from the same layers.
I've created a PR proposal for this, but please test thoroughly, as I'm not 100% sure.

**Closed** 2020-03-29 18:57 UTC
Labels: Bug, Regression
