### ISSUE TITLE
Mass warnings:  java.lang.NullPointerException: Attempt to invoke virtual method

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#8646] opened 2020-07-16 18:37 UTC
On my Samsung Galxy Tab S4, Android 10 I recognized, that c:geo got a bit slower than usual, so I just took a look into the logfile.
Not sure if these warnings are of any relevance and not sure whether they cause the slowness.

I was using an offline map to browser caches stored on a list and some time later activated map update at the time of log.

However I think those warnings should not be there.

[logcat_2020-07-16_08-11.txt](https://github.com/cgeo/cgeo/files/4933473/logcat_2020-07-16_08-11.txt)

2020.07.16-NB

**Comment by Lineflyer** [comment] 2020-07-16 18:42
Similar but not same warning on my other device:
Samsung Galaxy S10, Android 10, 2020.07.16-NB, Same scenario

[logcat_2020-07-16_08-09.txt](https://github.com/cgeo/cgeo/files/4933505/logcat_2020-07-16_08-09.txt)

**Comment by Lineflyer** [comment] 2020-07-17 07:38
Both types of warnings still shown with todays nightly 2020.07.17-NB

**Comment by moving-bits** [comment] 2020-07-17 21:19
Hm, I'm still unable to reproduce either of those errors.
- opened a map
- activated live map and stored all caches for this area
- disabled live
- moved map around a bit
- enabled live
- moved map around a bit

nothing unusual happened

Are you using any specific settings?
Following the error message I had activated general proximity notification.

**Comment by Lineflyer** [comment] 2020-07-17 21:35
@moving-bits I send you my app settings an whatsapp channel.

**Comment by moving-bits** [comment] 2020-07-18 08:26
Thanks, but still no luck.
This time tried with a list of a bit more than 1000 caches and offline map.
Started in offline mode, moved around a bit, enabled live mode, moved around a bit more. Still nothing unusual and no runtime exceptions.

**Comment by moving-bits** [comment] 2020-08-30 14:06
@Lineflyer 
Do the errors still occur with current nightlies?

**Comment by Lineflyer** [comment] 2020-08-30 19:42
Need to check, assigning myself.

**Comment by moving-bits** [comment] 2020-12-26 08:40
@Lineflyer 
Can we close this issue?

**Comment by Lineflyer** [comment] 2021-04-07 13:58
The second warnings/exceptions are no longer shown.
The first warnings/exceptions look real similar to #10071

**Comment by moving-bits** [comment] 2021-05-16 06:54
If the first warnings look similar to #10071 and the second warnings do no longer appear, then let's close this rather old issue (and open a new one if needed at some later point in time).

**Closed by moving-bits** 2021-05-16 06:54 UTC
Labels: Bug, Unverified
