### ISSUE TITLE
WP Calc: Input focus jumps to another variable

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#12510] opened 2022-01-09 16:41 UTC
### Describe your problem!

I experienced the issue, that while typing values (and other variables) into the fields below the coords the input field changed while typing. Unfortunately I was unable to reproduce it afterwards.

### How to reproduce?

- I used the guided input to assign single variables to some digits of the coordinate. Something like: N 51° MN.OPQ E006° RS.TUV
- Then I used the the variable fields below(!) to enter formulas for M, N, ....

BTW:
Only later I realized, that there is no need to use this complicated way of entering formulas. So its just to potentially reproduce the issue.

### Actual result after these steps?

On entering something like M=A+B-C the fields for A, B and C are created while typing. Thats fine.
But on that occasion it happend that suddenly the input field for "B=" was active while I was still typing into "M=". 

Difficult to describe, how you can follow.

### Expected result after these steps?

Focus should stay in the variable which is currently edited.

### Reproducible

Unclear

### c:geo Version

2022.01.09-NB

### System information

```text
Samsung S20, Android 12
```

**Comment by eddiemuc** [comment] 2022-01-09 16:50
Yeah, the focus handling is a big problem when you're in a field in a recycler view while elements are added to it. I already build in some fixes to the default behavior (which would be to reset focus totally), but apparently I missed some cases...

**Comment by Lineflyer** [comment] 2022-01-09 16:55
The question is, if this WP view needs the variables to be editable at all or if we completely refer the user to the new cache tab for that.
You probably integrated it to keep the WP calc usable as stand-alone feature, right?

**Comment by eddiemuc** [comment] 2022-01-09 17:05
> The question is, if this WP view needs the variables to be editable at all or if we completely refer the user to the new cache tab for that.
> You probably integrated it to keep the WP calc usable as stand-alone feature, right?

I would keep the variables editable here to ease the editing process (user should not be bothered switching too much between activities). This was also not difficult to implement, so I would keep it.

The technical challenges come with the auto-var- creation feature and the filter-vars-not-used-un-this-wp feature. Both are not needed in main cache tab. Some rather "wild" approaches are needed on implementation side esp for the focus problem.

**Comment by eddiemuc** [comment] 2022-01-15 09:38
I could reproduce this as follows:
* open a cache where there is a var A already defined, but vars M and L are not yet defined
* create new waypoint in this cache, open "new calculated coordinate dialog"
* enter "M" in plain mode lat or lon field -> var M appears -> ok
* go to M, enter "A+" in the field -> after entering "A" the var appears, after entering "+" nothing special happens, focus is ok
* now enter "L" behind the "A+" (forming "A+L) -> new var L appears (ok), but focus shifts to "A" input field (wrong)

Analysis shows that RecyclerView decides internally to recreate the whole view in this case for a yet unknown reason. Problem is that on recreation of all views focus is naturally lost (since also all edit fields are dropped and recreated)

**Comment by eddiemuc** [comment] 2022-01-15 09:57
I found that I can prevent RecyclerView from doing that by adding new vars always at the end. I think I will go for this one

**Comment by eddiemuc** [comment] 2022-01-16 09:54
Notes to myself:
maybe this can be approached in a totally different way, handling the focus-problem and the cursor-position-problem together:
* Modity VariableListView such that it ALWAYS tracks current varname in focus, current TextField in focus and current cursor position for this selection (change/update cursor pos on every text change, change/update focus on focuschange-listener in textfield -> TODO: associate this listener with the varname!)
* On every view-modifying action (esp adding vars!) save the current info and restore it later (have a flag "restoration mode" which is used in onCreateView and onBindView to requestFocus and setSelection if necessary)

**Comment by eddiemuc** [comment] 2022-01-16 15:47
Fixed with PR #12542 as described in previous comment (introduced own new focus + cursorpos handling)

**Closed** 2022-01-17 10:34 UTC
Labels: Bug, Unverified
