### ISSUE TITLE
ArrayIndexOutOfBoundsException 

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#8066] opened 2020-01-12 13:58 UTC
From Google Play for version 2019.12.30 occuring on Android 8,9,10

java.lang.ArrayIndexOutOfBoundsException: 

at java.util.concurrent.CopyOnWriteArrayList.get (CopyOnWriteArrayList.java:385)

at java.util.concurrent.CopyOnWriteArrayList.get (CopyOnWriteArrayList.java:398)

at org.mapsforge.map.layer.Layers.get (Layers.java:230)

at org.mapsforge.map.android.input.TouchGestureHandler.onSingleTapConfirmed (TouchGestureHandler.java:253)

at android.view.GestureDetector$GestureHandler.handleMessage (GestureDetector.java:316)

at android.os.Handler.dispatchMessage (Handler.java:106)

at android.os.Looper.loop (Looper.java:214)

at android.app.ActivityThread.main (ActivityThread.java:7156)

at java.lang.reflect.Method.invoke (Native Method)

at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:494)

at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:975)

**Comment by moving-bits** [comment] 2020-01-12 14:27
Duplicate of #7034

**Closed by moving-bits** 2020-01-12 14:27 UTC
Labels: Bug, Duplicate, Google Play or Beta feedback

**Comment by Lineflyer** [comment] 2020-01-12 14:29
Thanks  for looking it up
