### ISSUE TITLE
Nearby search when offline

### ISSUE THREAD

**Issue by triakcz** [cgeo/cgeo#5103] opened 2015-07-18 19:29 UTC
Hi,

I discovered, that when I go offline, nearby search feature is unusable at all. I would recommend showing 20 nearest caches from local storage with warning that it's only from local storage, because internet connection was not sucessfull.

What do you think about this ?

Sometimes it will help users with many lists of caches, to just see what's around (using offline list with 3000 caches from pocketquery is difficult on many devices).

Thanks for your opinion.

TriakCZ

**Comment by Lineflyer** [comment] 2015-07-18 19:48
This is a duplicate AFAIR.

**Comment by triakcz** [comment] 2015-07-18 19:49
So I'm sorry for that, because I already tried to find it, and I was not
successful.

2015-07-18 21:48 GMT+02:00 Lars <notifications@github.com>:

> This is a duplicate AFAIR.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cgeo/cgeo/issues/5103#issuecomment-122588223>.
>



-- 
Ondřej Kunc

**Comment by rsudev** [comment] 2015-07-18 19:56
Duplicate of #734

**Comment by triakcz** [comment] 2015-07-18 19:59
Ok, do you want me to implement it ? I hope that it will not be so
difficult.

2015-07-18 21:56 GMT+02:00 rsudev <notifications@github.com>:

> Duplicate of #734 <https://github.com/cgeo/cgeo/issues/734>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cgeo/cgeo/issues/5103#issuecomment-122588888>.
>



-- 
Ondřej Kunc

**Comment by rsudev** [comment] 2015-07-18 20:10
The main issue IMO would be,.to consistently detect the 'offline' state. The search and result handling itself shouldn't be a big deal.
So, from my point of view you would be very welcome!

**Closed** 2015-07-18 20:41 UTC
