### ISSUE TITLE
Nightly: App Crash on "Show as List"

### ISSUE THREAD

**Issue by MagpieFourtyTwo** [cgeo/cgeo#7860] opened 2019-09-20 11:08 UTC
**Describe the bug:**
When selecting "Show as List" from the Live Map Menu, c:geo immediately restarts

**To Reproduce:**
1. Open "Live Map" and move to a region with at least two caches
2. Click on "Show as List"
3. c:geo immediately restarts, ending up in start screen, logging in into geocaching,com

**Version of c:geo used:**
2019.09.20-NB-28ab651

**Is the problem reproducible:**
Yes

**System information:**
```
--- System information ---
Device: VOG-L29 (VOG-L29EEA, HUAWEI)
Android version: 9
Android build: VOG-L29 9.1.0.193(C431E4R2P2)
c:geo version: 2019.09.20-NB-28ab651
Google Play services: disabled - 19.2.75 (100400-269183835)
Low power mode: inactive
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: rotation vector
Hide own/found: true
HW acceleration: enabled (default state)
System language: de_DE
System date format: dd.MM.yy
Debug mode active: no
System internal c:geo dir: /data/user/0/cgeo.geocaching (31,4 GB free) internal
User storage c:geo dir: /storage/emulated/0/cgeo (31,4 GB free) external non-removable
Geocache data: /storage/emulated/0/Android/data/cgeo.geocaching/files/GeocacheData (31,4 GB free) external non-removable
Database: /data/user/0/cgeo.geocaching/databases/data (287,2 MB) on system internal storage
Fine location permission: granted
Write external storage permission: granted
Geocaching sites enabled:
   geocaching.com: Logged in (Anmeldung OK) / PREMIUM
   extremcaching.com: Logged in (Anmeldung OK)
Geocaching.com date format: dd MMM yy
Installed c:geo plugins: contacts
--- End of system information ---
```

**Additional context:**
I'm pretty sure this worked with the previous nightly (as I update frequently and use this feature a lot), thus it may be related to one of the latest changes.

**Comment by bekuno** [comment] 2019-09-20 11:55
Which map provider (google, osm, offline)?

**Comment by MagpieFourtyTwo** [comment] 2019-09-20 15:23
Doesn't matter. They all crash.

**Comment by bekuno** [comment] 2019-09-20 20:13
Error is 
~~~
   java.lang.RuntimeException: Unable to start activity ComponentInfo{cgeo.geocaching/cgeo.geocaching.CacheListActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2927)
...
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
        at android.support.v4.app.LoaderManagerImpl.createAndInstallLoader(LoaderManagerImpl.java:371)
        at android.support.v4.app.LoaderManagerImpl.initLoader(LoaderManagerImpl.java:404)
        at cgeo.geocaching.CacheListActivity.onCreate(CacheListActivity.java:524)
        at android.app.Activity.performCreate(Activity.java:6942)
...
~~~

**Comment by Lineflyer** [comment] 2019-09-20 21:53
Working normal with 2019.09.13-NB-3fcf30b

**Comment by bekuno** [comment] 2019-09-20 22:23
The problem is caused by upgrading the Support Library to the latest 27.x version. (27.1.0)
The last version without this problem is 27.0.2.

The error is raised in CacheListActivity line 1868.
(context.startActivity(cachesIntent);)

@moving-bits Can you create and push a PR with this library version so that it will be the next nightly?

**Comment by MagpieFourtyTwo** [comment] 2019-09-20 23:29
FYI: just updated to 2019.09.21-NB-28ab651 - still crashing.

BTW: Is there a nightly repository out there?

**Comment by moving-bits** [comment] 2019-09-21 06:16
@bekuno

I'm AFK, but if you create a PR for downgrading the support library, I can merge it.

**Comment by moving-bits** [comment] 2019-09-21 06:40
@bekuno

Can you try support lib v28.0.0? When moving to compile & target SDK 28 we should try to use the most recent support lib anyway. Thanks.

**Comment by bekuno** [comment] 2019-09-21 08:00
@moving-bits 
support lib 28.0.0 does not compile, also not with targetSdk/compileSdk 28

**Comment by moving-bits** [comment] 2019-09-21 08:22
@bekuno

Hm, it did compile fine on my dev machine, see my PR (which does not compile on the CI yet due to SDK licence agreement not being accepted yet).

Anyway: I'll be back at my dev machine tomorrow evening, can try to tackle this issue then.

**Comment by bekuno** [comment] 2019-09-21 08:36
@moving-bits AFK now, more tomorrow, i hope

**Closed** 2019-09-21 10:13 UTC
Labels: Bug

**Comment by MagpieFourtyTwo** [comment] 2019-09-21 23:01
Working like a charm - thx a lot! :)

**Comment by bekuno** [comment] 2019-09-22 10:54
With default changes to tagetSDK28 it does not work, but has another exception:
~~~
    java.lang.RuntimeException: Unable to start activity ComponentInfo{cgeo.geocaching/cgeo.geocaching.CacheListActivity}: java.lang.IllegalArgumentException: Object returned from onCreateLoader must not be null
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2927)
~~~
W should not reopen the PR, but test this in the SDK28 PR #7653

**Comment by moving-bits** [comment] 2019-09-22 15:39
> W should not reopen the PR, but test this in the SDK28 PR #7653

Thanks for catching this. I opened issue #7865 to track it.
