### ISSUE TITLE
List of caches disappears after minimising app

### ISSUE THREAD

**Issue by rigor-** [cgeo/cgeo#3448] opened 2013-12-04 14:57 UTC
The issue is that when I download certain number of caches (say 40 nearby caches) and I minimise the app, say just for a phonecall, and than I bring c:geo back, in many ocations the caches will be gone and I have to download the list again. It does not matter if I just got them in the list or opened them in a map. The only caches which will remain are those which I have allready opened (not downloaded for offline, just opened).
It does not happen regularly, but still quite often and it can be especially anoying in places with weak network coverage. It happened to my on my HD2 running 2.3.7 and it happens on my SIII, no matter if on stock 4.0.1 - 4.1.2 or custom 4.2.2 - 4.3.1. 

Related to this issue, it would be very helpfull to add list saving ability like the one built in GCZII. I really would like to be able to save lists of caches when I need it without a need to download all caches details. Also a return to last list would help a lot, as I many times accidentally pushed back button while on list of nearby caches, bringing me to the home screen and than I had to download all the cache list again - very "pleasant" with poor data signal.

**Comment by Lineflyer** [comment] 2015-07-27 10:35
Duplicate of #2100.

**Closed by Lineflyer** 2015-07-27 10:35 UTC
Labels: Bug
