### ISSUE TITLE
opening offline map from the cache-details crashes c:geo

### ISSUE THREAD

**Issue by schafma** [cgeo/cgeo#6236] opened 2017-01-08 21:58 UTC
##### Detailed steps causing the problem:
- premise: map source is set to an offline map
- Select a stored Cache from a list
- Switch to compass
- open map

##### Actual behavior after performing these steps:
 c:geo crashes

##### Expected behavior after performing these steps:
c:geo should show the map

##### Version of c:geo used:
2016.12.28

##### Is the problem reproducible for you?
Yes

##### System information:

--- System information ---
Device: SM-G800F (kminiltexx, samsung)
Android version: 5.1.1
Android build: LMY47X.G800FXXU1BOK7
Cgeo version: 2016.12.28
Google Play services: enabled
Low power mode: inactive
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: rotation vector
Hide own/found: true
Map strategy: auto
HW acceleration: enabled (default state)
System language: de_DE (cgeo forced to English)
Log date format: 1/8/2017
Debug mode active: no
Fine location permission: granted
Write external storage permission: granted
Geocaching sites enabled:
geocaching.com: Logged in (Login OK) / PREMIUM
Geocaching.com date format: dd MMM yy
Installed cgeo plugins: calendar, contacts
--- End of system information ---

##### Other comments and remarks:
a) If an online-map is selected c:geo work without any issues.
b) Live-map works with offline maps
C) calling the map from a list works
d) issue occured with update to the current version (2016.12.28)

**Comment by Lineflyer** [comment] 2017-01-09 19:44
Thanks for your report, but I cannot reproduce this issue.
Did you try to reboot your phone and try again?

I could imagine a shortage of memory causing this.

Did you send a crash report if asked for?
In any case please redo that and refer to this issue in your comment to the crash report.

**Comment by Lineflyer** [comment] 2017-01-09 19:46
Forgot another point regarding a known issue:
If the problem remains despite rebooting, please go to Menu -> Settings -> Map and **disable** the option "Show direction line" and try again. If this solves your issue, then the problem will already be fixed with the next release.
Anyway you could still help us by becoming a beta tester of c:geo on Google Play and try the current beta version to test if the fix for this is working as intended.

**Comment by schafma** [comment] 2017-01-09 19:56
Hey Lars,
thanks for the quick feedback. The restart didn't solve the issue but the second recommendation did the job!
I will be glad to help you. How can I become a beta tester? 

Nochmal Danke
Marcus

**Comment by Lineflyer** [comment] 2017-01-09 20:17
Great. Then the problem was probably caused by #6206.

You can become beta tester by opening this link and logon with your Google account:  http://goo.gl/g7NhzY
Afterwards you will receive beta versions as a normal update via Google Play.

Would be great if you try if the beta version also works for you with the mentioned option enabled.
Please report back in #6206.

**Closed by Lineflyer** 2017-01-09 20:17 UTC
Labels: Bug, Unverified

**Comment by samueltardieu** [comment] 2017-01-09 22:53
Pending a logfile, I'm not sure this is related to #6206.

**Comment by schafma** [comment] 2017-01-10 08:38
Yes I did. But I received an email from Samuel Tardieu:
"Pending a logfile, I'm not sure this is related to #6206 
<https://github.com/cgeo/cgeo/issues/6206>.".

I'm not quite sure if the Log create with aLogcat on my Android 5.1.1 is 
very usefull.
But I didn't find any other description on your site how to create a log 
with with Android >=5 without rooting the phone.

**Comment by Lineflyer** [comment] 2017-01-10 11:15
@schafma 
Oh, I see, you mailed it to us.

I was only asking if you can send us a crash report via Google Play.
This means, if the app crashes you should be asked if you want to send a crash report on your mobile. Please send this and add a user comment refering to your username or the issue on Github.

Nevertheless I will also take a look into what you send us. But I am afraid it wont be helpful unless you did it with root access rights.

**Comment by schafma** [comment] 2017-01-10 11:23
@lars just sent it.

Am 10.01.2017 um 12:15 schrieb Lars:

**Comment by Lineflyer** [comment] 2017-01-10 15:16
@schafma 
Thank you. Found it. It is in fact a new problem where I will open a new issue in order not to mix up anything. 
I will make a reference to this issue, so that you will find the link to the new issue if you look into Github.
