### ISSUE TITLE
[Feature Request] Beep alert proximity

### ISSUE THREAD

**Issue by MacAre** [cgeo/cgeo#5751] opened 2016-05-23 19:00 UTC
### Detailed steps causing the problem:
No problem => SUGGESTION

##### Other comments and remarks:
Hint: it might be practical in c:geo to have a warning beep (or a ringtone of your choice) when passing near a geocache (with distance / adjustable radius). It would be warned when you are cycling for example.
MyTrails (FrogSparks) does. I happened to export caches to MyTrails for that, but it's even more applications to run on the smartphone and it is not best for the battery (although I have a Powerbank ).

**Comment by SammysHP** [comment] 2016-05-23 19:08
Duplicate of #417, #617, #1669, #2003, #4145, #5730.

**Closed by SammysHP** 2016-05-23 19:08 UTC
