### ISSUE TITLE
List not updated after deletion

### ISSUE THREAD

**Issue by Bananeweizen** [cgeo/cgeo#4842] opened 2015-04-04 06:37 UTC
Delete a cache from the details screen. Afterwards go back to the list. It is still there. Did someone modify the notifychanged code?

**Comment by samueltardieu** [comment] 2015-04-05 11:14
This area has been recently touched to fix #4741, but I can't reproduce it. Can you be more specific?

**Comment by Bananeweizen** [comment] 2015-04-05 14:03
Actually I also cannot reproduce this anymore right now, although this happened multiple times in the last week. I know for sure that on several different days when I deleted a past event from the cache details and went back to my event list, it would not refresh the list and show the same number of caches. Back to main and then reopening stored caches showed less caches afterwards, as expected.

**Comment by samueltardieu** [comment] 2015-04-05 14:18
Your event list is a regular offline list, right?

**Comment by Bananeweizen** [comment] 2015-04-05 15:16
Yes, it just happens to contain only events, thereby using event sorting automatically.

**Comment by Lineflyer** [comment] 2015-04-07 12:07
I have not experienced such a problem on my last weeks of caching and I did the described operation multiple times.
@Bananeweizen: Did you use the `Delete` button or the delete option in the action bar menu?

**Comment by Lineflyer** [comment] 2015-05-04 21:37
@Bananeweizen Any more clues on this or close it?

**Comment by Lineflyer** [comment] 2015-05-28 12:38
Closing due to lack of feedback and not being reproducible with current master.

**Closed by Lineflyer** 2015-05-28 12:38 UTC
Labels: Bug, Unverified
