### ISSUE TITLE
Found ALC not hidden in searches although "Hide own/found" active

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#10566] opened 2021-05-08 19:23 UTC
## Bug description 

With current nightly the hiding of ALC marked as found works perfect. But it seems in searches the global "Hide own/found" falg is ignored as found ALC are contained in the result

### Steps to reproduce the problem

- Activate Settings - Cache-Details - "Hide own/found"
- Have some stored nearby ALC marked as found locally
- Perform nearby search or other search returning those ALCs as part of the result

### Actual result after these steps 

The found ALC show up in the list (marked as Found)

### Expected result after these steps 

The ALC should not be on the result list, if the user selected to "Hide own/found"

## c:geo version 

2021.05.08-NB

## Reproducible 

Yes

**Comment by moving-bits** [comment] 2021-05-08 19:27
How about UDC, will they also show up in that case?
(I'm asking because they use the same mechanism to mark them as found. So if yes, we would have to add something to that mechanism, and if no, then the cause is probably somewhere in the LC connector, although I have no idea at hand what that could be.)

**Comment by Lineflyer** [comment] 2021-05-08 20:45
> How about UDC, will they also show up in that case?

Just checked that: No, they do not show up..**BUT** UDC seem to never show up in nearby results as those only query connectors online not the offline data.
So the difference is, that UDC simply are not used in that part of the code.

**Comment by baiti** [comment] 2021-05-15 18:56
Is this bug still there in recent nightlys? In what I curretnly use it is a "NRP" (not reproducable).

**Comment by Lineflyer** [comment] 2021-05-15 20:05
Yes, still reproducible for me with 2021.05.15-NB

**Comment by baiti** [comment] 2021-05-15 20:21
I was in live map and used "Quick Settings" and unchecked "Own/found caches" ... that seems to work. You are refering to a different scenario and I do not know what exactly that means: "Activate Settings - Cache-Details - "Hide own/found". Where is "Activate Settings"?

**Comment by moving-bits** [comment] 2021-05-15 20:22
It's in the preferences:

Go to Settings => Cache details => Hide own/found

**Comment by baiti** [comment] 2021-05-15 20:23
Ah .. ok but that checkbox correlates to the flag in quick settings, right?

**Comment by baiti** [comment] 2021-05-15 20:24
If one is toggled, the other one is toggled two, just one is the inverse of the other

**Comment by moving-bits** [comment] 2023-07-02 08:46
Fixed with #14318

**Closed by moving-bits** 2023-07-02 08:46 UTC
Labels: Bug, Connector AL
