### ISSUE TITLE
download offline maps via user interface

### ISSUE THREAD

**Issue by Bananeweizen** [cgeo/cgeo#991] opened 2012-01-15 08:06 UTC
Using offline maps involves copying files manually from PC to device. We should avoid this. The MapsForge team has a website where you can download map files. We should have some user interface, which can browse and download a map file that way. Restrictions:
- We should first ask the Mapsforge team if it is OK to browse their server that way.
- The download shall only be possible if WIFI is used.

**Comment by Lineflyer** [comment] 2019-04-23 21:14
Meanwhile duplicate of #7529  
Closing here as this issue is rather old compared to the recent discussions.

**Closed by Lineflyer** 2019-04-23 21:14 UTC
Labels: Feature Request, Frontend Design
