### ISSUE TITLE
need a way to exit a WIG

### ISSUE THREAD

**Issue by ztNFny** [cgeo/cgeo#16224] opened 2024-10-16 17:13 UTC
There needs to be an easier way to exit WIG mode and return to c:geo.

Example:
1. Load Waldmeisters reverse
2. go into "Play" mode
you're now faced with the dialog to provide the 3*6 numbers. But that dialog is impossible to exit without valid input. The only button is OK and that one first requires 6 valid numbers. But it's likely that at this point the user needs to switch back to the listing to find those numbers.

Expectation:
- a possibility to terminate the WIG, no matter where inside it I currently am
- a possiblity to switch back to a cache in c:geo

**Comment by eddiemuc** [comment] 2024-10-17 05:35
While this is a perfectly valid request, it is not straightforward to solve because of the nature of how Wherigos work.

A wherigo "forces" its clients to display Dialogs exactly when the cartridge commands it. There is no option foreseen to cancel such Dialogs. Means: you can ignore them, but this will basically pause the game "forever" (Dialogs will not get retriggered).

I see two solutions:
- add a "Terminate game" option. That's a rather radical solution though. Even if we save the game , depending on how cartridge is programmed, it is not clear whether user can recover his state at a later point in time
- "cancel" the dialog. We add a "cancel" button, dialog closes but c:geo remembers its state. C:geo can then re-display dialog at a later time. Question is: how should this be triggered? I would suggest a button "continue with pending dialog" or something alike

Oinions?

**Comment by ztNFny** [comment] 2024-10-17 05:56
Slight misunderstanding there. I'm not saying it should be possible to kill the WIG, but it must be possible to exit the WIG-mode of c:geo, e.g. to return to the cache and retrieve the numbers.
So more like pausing the WIG.

Maybe a solution is to always have bottom nav visible and allow using it even in that dialog.

**Comment by fm-sys** [comment] 2024-10-17 08:02
Generally speaken, you can just use the back button and cgeo will return to wherever you where before. The WIG will continue to run in background.

BTW, this was discussed in the team meeting as well as in https://github.com/cgeo/cgeo/discussions/16172

Bei able to do this while a dialog is visible is indeed a topic though.

**Comment by ztNFny** [comment] 2024-10-17 21:16
> Generally speaken, you can just use the back button and cgeo will return to wherever you where before.

oops, as i was testing in emulator I tried everything but that ...

Still I'd think it'd be nice if everything WIG-related was running inside the WIG tab instead of the dialogs currently used.

**Comment by eddiemuc** [comment] 2024-10-18 04:27
Using the back button will most likely make the same dialog reappear immediately in current implementation (at least I think this is the case, need to check).

The issue is absolutely real and will be fixed

**Comment by eddiemuc** [comment] 2024-10-19 13:35
Update: I tried the back button. This will indeed close the dialog, but it will not bring it back! In other words you can't continue playing the cartridge. Also saving and loading does not help. One yould have to start anew. This is not ok, I have to think about this

**Comment by eddiemuc** [comment] 2024-10-19 18:25
PR #16246 will enable the Wherigo Player to pause and unpause the latest input dialog.

Currently GUI-wise this is implemented by adding a "pause" button to all input dialogs:

![image](https://github.com/user-attachments/assets/8011167e-a64d-4436-ab8a-6fd87d2cf413)

Question is of course: how and where can user "unpause" (= resume) the dialog. PR above adds an action button for this which into Wherigo Activity which for now looks like this (this is probably not final GUI-wise :-)):

![image](https://github.com/user-attachments/assets/610b9450-0da6-41f1-b23f-5730219acd42)

It has to be empathized that such handling is NOT really supported by OpenWIG. So I hope we don't run into side effects at a later point in time.

**Comment by fm-sys** [comment] 2024-10-19 20:38
I would suggest implementing it as if the dialog and the inventory activity were glued together.

So pressing back button would not only close the dialog but also the WIG inventory below (if applicable). Reentering the WIG player would open up both again if a dialog is currently paused. That would probably also mitigate potential side effects mentioned above. 

BTW, I'm still struggling with the full screen dialog approach. I would suggest to either make it a real dialog (WIGs are mostly designed for way smaller screens anyway) or make it a real activity with actionbar.

**Comment by ztNFny** [comment] 2024-10-19 20:42
> make it a real activity with actionbar.

+1. I'd prefer all WIG stuff to be inside the activity, also visually.

**Comment by eddiemuc** [comment] 2024-10-19 23:31
>  I would suggest implementing it as if the dialog and the inventory activity were glued together.
> 
> So pressing back button would not only close the dialog but also the WIG inventory below (if applicable). Reentering the WIG player would open up both again if a dialog is currently paused. That would probably also mitigate potential side effects mentioned above. 

Input Dialogs may pop up whenever the cartridge wants it. So they will in many cases pop up when the user is in another activity eg the map.

That's the whole reason I chose the dialog approach. The cartridge may choose at any time (eg based on geo fence or time trigger) to open any dialog: to show something, to ask for input, to show an item from the cartridge or even an error message.

However, I can retrigger paused dialogs automatically when user enters the wherigo activity. That's probably a good idea.


> BTW, I'm still struggling with the full screen dialog approach. I would suggest to either make it a real dialog (WIGs are mostly designed for way smaller screens anyway) or make it a real activity with actionbar. 

No problem making the dialogs smaller.

**Comment by eddiemuc** [comment] 2024-10-20 07:30
> > make it a real activity with actionbar.
> 
> +1. I'd prefer all WIG stuff to be inside the activity, also visually.

That's not possible duento "asynchronous" nature of wherigos

**Comment by fm-sys** [comment] 2024-10-20 07:47
> > > make it a real activity with actionbar.
> > 
> > 
> > +1. I'd prefer all WIG stuff to be inside the activity, also visually.
> 
> That's not possible due to "asynchronous" nature of wherigos

It shouldn't make a difference whether you open a dialog or a new activity...?

**Comment by eddiemuc** [comment] 2024-10-20 07:58
> > > +1. I'd prefer all WIG stuff to be inside the activity, also visually.
> > 
> > That's not possible due to "asynchronous" nature of wherigos
> 
> It shouldn't make a difference whether you open a dialog or a new activity...? 

Maybe a misunderstanding.

It is possible to open an activity instead of a dialog, that's true. But I think this would be major disruptive to the user when he is eg on the map. I think a dialog fits better here.

However: I don't think the user cares whether the used technology is an Activity or a Dialog. The user cares for her UX experience. This is why I started using fullscreen dialogs btw. If an "activity style" is wanted then we can easily make them style like "a typical c:geo activity" e.g. give them an Action bars and the activity background color.

**Comment by fm-sys** [comment] 2024-10-20 08:27
> I don't think the user cares whether the used technology is an Activity or a Dialog.

Totally agree. But please decide for one design which is familiar to the user and nothing in between :)

**Comment by eddiemuc** [comment] 2024-10-20 08:33
> > I don't think the user cares whether the used technology is an Activity or a Dialog.
> 
> Totally agree. But please decide for one design which is familiar to the user and nothing in between :) 

Ah, you know GUI design is not my strongest side 😄😄😄 As of now I "just" did a technical implementation. I totally expected and embrace a discussion about it

**Comment by ztNFny** [comment] 2024-10-20 08:51
> > make it a real activity with actionbar.
> 
> +1. I'd prefer all WIG stuff to be inside the activity, also visually.

This request was with the assumption that WIGs are played inside the WIG activity. You're right in your statement though, that WIG dialogs could open at any point in time and from any activity - and I guess this could include *anything*, e.g. a log dialog or editing a waypoint format.
In those cases as a user i'd NOT want a WIG dialog to kill the current activity, that might lead to data loss. So the current dialog approach is maybe the better one - at least for those actions (but maybe not for something like inspecting the inventory - let's discuss).
@eddiemuc did you test a scenario like entering the zone while writing a log? What happens with the current approach?

**Comment by eddiemuc** [comment] 2024-10-20 09:10
> > > make it a real activity with actionbar.
> > 
> > 
> > +1. I'd prefer all WIG stuff to be inside the activity, also visually.
> 
> This request was with the assumption that WIGs are played inside the WIG activity. You're right in your statement though, that WIG dialogs could open at any point in time and from any activity - and I guess this could include _anything_, e.g. a log dialog or editing a waypoint format. In those cases as a user i'd NOT want a WIG dialog to kill the current activity, that might lead to data loss. So the current dialog approach is maybe the better one - at least for those actions (but maybe not for something like inspecting the inventory - let's discuss). 

@eddiemuc did you test a scenario like entering the zone while writing a log? What happens with the current approach?

I tested this. I will answer you in an own issue which I will create during next half an hour or so. I feel this topic deserves its own discussion point :-)

**Comment by eddiemuc** [comment] 2024-10-27 15:08
Works meanwihile with "cancel" mechanism and ability to resume cancelled dialogs. Completed with PR #16273 

![Image](https://github.com/user-attachments/assets/b276cb96-ba2c-4cd8-b425-6bfe751b21a7)

![Image](https://github.com/user-attachments/assets/339c812b-3ed5-43e5-bcaa-e2d6a4c0fd42)

![Image](https://github.com/user-attachments/assets/73337c93-e453-4a6f-bfdd-8d1164e9f563)

Please open new issues for more GUI detail discussions.

**Closed by eddiemuc** 2024-10-27 15:08 UTC
