### ISSUE TITLE
Can't import 2 new geocaches, while other work

### ISSUE THREAD

**Issue by bfankd** [cgeo/cgeo#5079] opened 2015-07-08 04:45 UTC
HI
I received a mail anouncing a new GC. Normally importing from mail or by gc-code search works perfectly but for these 2 new GC:
GC5YR5P and GC5YR9B

Thanks for fixing.
My System: Samsung S4 GT-I9505 BE AUT, Android 4.4.2 stock rom, rooted. C:GEO 2015.06.19

**Comment by rsudev** [comment] 2015-07-08 05:24
I was able to to reproduce this right now. It doesn't seem to be tied to these specific caches, but to a change on the website and the fact, that they contain waypoints.
Seems to be related to #5051. I was able to save a website with this content, will take a look.

**Comment by Lineflyer** [comment] 2015-07-08 06:38
Indeed. Duplicate of #5069 and related to a website change probably (as I just got release notes from the forum).

**Closed by Lineflyer** 2015-07-08 06:38 UTC
