### ISSUE TITLE
Waypoint extraction made up digits

### ISSUE THREAD

**Issue by geocachermgo** [cgeo/cgeo#13311] opened 2022-08-06 16:37 UTC
### Describe your problem!

I have a personal note: 
"R1=10k, R2=680 R3 not used R4=18k, R5=330 R6=2k2
18K=4, 680+2k2=8, 20k= 1, 330=5, 680=2"

From this note the following waypoint is extracted:
{c:geo-start}
@Persönliche Notiz 1 (W) N1 19.800 E5 40.800 "=2"

{c:geo-end}
Note that there is no digit 9 in the note but in the extracted waypoint

### How to reproduce?

Add mentioned text as personal note.

### Expected result after these steps?

No waypoint should be created from that note.
More generell no digit should occur in a waypoint ghat are not in the note

### Reproducible

Yes

### c:geo Version

2022.08.03-NB-f95d463

**Comment by eddiemuc** [comment] 2022-08-06 22:13
The waypoint creation seems to be triggered by the following subsequence: 
`1, 330=5, 680`

**Comment by eddiemuc** [comment] 2022-08-06 23:03
Suspicion confirmed. `1, 330=5, 680` is interpreted as `N1,300 E5,680` in DDD-format, which in DMS-format is `N1 19.800 E5 40.800`

Fixed with PR #13320

**Comment by geocachermgo** [comment] 2022-08-06 23:04
N 01° 19.800' E 005° 40.800' is equal to 1.330° 5.680° so the conversion routine recognized the dd.ddd format.
Thanks for the analysis and fix

**Comment by geocachermgo** [comment] 2022-08-06 23:06
A plain letter is not working as separator.

**Comment by geocachermgo** [comment] 2022-08-06 23:09
" =" and " = " are also working as separators but should not (I think)

**Comment by eddiemuc** [comment] 2022-08-07 09:54
> " =" and " = " are also working as separators but should not (I think)

Haven't tried those. I just focused on the concrete bug. 

Is there a more general wish to redesign coordinate parsing functionality of c:geo?

**Comment by geocachermgo** [comment] 2022-08-07 11:49
Since I do not know the rules I cannot judge it. Normally it works fine.

The following things speak against dd.dd Interpretation in my example

comma instead of point
no (white)space behind number
space after decimal separator

Just two plain numbers should not and are not interpreted as dd.dd.
I used 49 9 because its a cache name and its coordinate
Not extracted:
49 9
49.0 9
49 9.0
a49.0,9.0b
a40.0 9.0b
49.0x9.0
x
49.0 0 0 9.0 0 0
Nord 49.0 East 9.0
N49.0 E9.0
x
49.0 9.0b
49. 0 9. 0

Extracted:
41.0 9.0
a40.0 9.0 (note: trailing letter prevents extraction)

49.0x42.0

9.0 0 0 9.0 0 0 (as 42.0 (first line), 9.0 (third line))

43. 00 9. 00 (note: single 0 are not extraced)

**Comment by geocachermgo** [comment] 2022-08-07 11:50
Summary: if "=" is treated like a letter then I'm fine with it.

**Comment by eddiemuc** [comment] 2022-08-07 12:21
> Summary: if "=" is treated like a letter then I'm fine with it.

This should be the case once the PR is merged

**Closed** 2022-09-04 11:27 UTC
Labels: Bug, Unverified
