### ISSUE TITLE
Projection/Offset do not create variables

### ISSUE THREAD

**Issue by DaTechniker** [cgeo/cgeo#15922] opened 2024-07-28 08:07 UTC
### Tell us your idea!

I am using extended formulas a lot.
There are some caches, that simply need a projection or offset from some waypoint
This words fine, except, I manually need to create variables. When Opening a waypoint, and I add a formula with vars, the these are created automatically

### What solution would you suggest?

automatically create variables when formulas are added to projection/offset

### Additional Information

Tested with: c:geo version: 2024.07.20-RC

**Comment by Lineflyer** [comment] 2024-07-28 15:29
Confirmed. IMHO a bug as it AFAIR worked already before.

You are able to enter variables or formulars for distance/direction but the corresponding variables are not automatically created on the variable tab.

**Comment by eddiemuc** [comment] 2024-07-28 15:35
Variables entered as part of distance and/or bearing of a projection were never created automatically. Valid feature request but not a.bug imho

**Comment by SammysHP** [comment] 2024-07-28 16:41
Duplicate of #15756.

**Closed by SammysHP** 2024-07-28 16:41 UTC
Labels: Bug, Feature Request
