### ISSUE TITLE
keep one cache on multiple list

### ISSUE THREAD

**Issue by revolvermann76** [cgeo/cgeo#4914] opened 2015-04-27 07:32 UTC
In the current version of c:geo it is only possible to _move_ a cache from one list to another. It would be nice to have a feature to _copy_ them too. Often you want to hold one cache on more than one list. 

An example case, where it is useful to keep one cache on multiple lists could be:
- Caches in my Hometown
- Caches, that I want to find today
- Caches that I have not found and plan to retry in the future
- Caches that I have found

Another annoying thing is, that when I import a GPX file into one list it removes caches with the same IDs from other lists.

**Comment by SammysHP** [comment] 2015-04-27 08:13
Duplicate of #87.

**Closed by SammysHP** 2015-04-27 08:13 UTC
