### ISSUE TITLE
waypoints and caches dissapear from the map when zooming in

### ISSUE THREAD

**Issue by andrixnet** [cgeo/cgeo#7205] opened 2018-11-29 19:00 UTC
I recently encountered a usability problem with c:geo, working woth vector offline map and current masforge v4 library. 

As I zoom in, either waypoints, caches or both dissapear from the screen.
See the following sequence of screenshots:

![screenshot_20181104-150820](https://user-images.githubusercontent.com/3382777/49244907-98388200-f419-11e8-87f1-9d9f109e690b.png)
![screenshot_20181104-150824](https://user-images.githubusercontent.com/3382777/49244908-98388200-f419-11e8-913f-9d433d1224e8.png)
![screenshot_20181104-150836](https://user-images.githubusercontent.com/3382777/49244910-98388200-f419-11e8-82a4-b9c2652be496.png)
![screenshot_20181104-150957](https://user-images.githubusercontent.com/3382777/49244911-98d11880-f419-11e8-84fd-887269a325ee.png)

Note: screenshots taken on november 4th using the latest c:geo at that time. 

I had to activate the old Mapsforge 3 library to have a consistent display of cache icons across all zoom levels.

The problem appeared after app kill and restart.
The problem appeared after phone restart (Galaxy S6)

**Comment by SammysHP** [comment] 2018-11-29 19:17
I'm sure there is another issue at the moment because I experience the same issue for several weeks. Sadly I'm not able to find it (or there no issue).

**Comment by okainov** [comment] 2018-11-29 19:20
Same issue here.

@SammysHP I was experiencing this much-much longer that few weeks ago

**Comment by Lineflyer** [comment] 2018-12-03 11:36
Related to #5900

**Comment by Lineflyer** [comment] 2018-12-03 11:40
@andrixnet 

What version did you use when you found this behavior?
The main issue of #5900 should be fixed already on current master, but some other regression appeared then (see comments in that issue).

**Comment by andrixnet** [comment] 2018-12-03 18:14
c:geo version 2018.10.13

screenshots taken 2018.11.04

**Comment by andrixnet** [comment] 2018-12-03 18:16
--- System information ---
Device: SM-G920F (zerofltexx, samsung)
Android version: 7.0
Android build: NRD90M.G920FXXU6ERD3
c:geo version: 2018.10.13
Google Play services: enabled - 14.5.74 (040400-219897028)
Low power mode: inactive
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: rotation vector
Hide own/found: false
Map strategy: auto
HW acceleration: enabled (default state)
System language: en_GB
System date format: dd/MM/y
Debug mode active: no
System internal c:geo dir: /data/user/0/cgeo.geocaching (6.6 GB free) internal
User storage c:geo dir: /storage/emulated/0/cgeo (6.6 GB free) external non-removable
Geocache data: /storage/emulated/0/Android/data/cgeo.geocaching/files/GeocacheData (6.6 GB free) external non-removable
Database: /storage/emulated/0/Android/data/cgeo.geocaching/files/databases/data (6.3 MB) on user storage
Fine location permission: granted
Write external storage permission: granted
Geocaching sites enabled:
   geocaching.com: Logged in (Login OK) / BASIC
Geocaching.com date format: yyyy-MM-dd
Installed c:geo plugins:  none
--- End of system information ---

**Comment by Lineflyer** [comment] 2018-12-04 09:59
In this case, this is most likely the issue which is already been solved on our 'master' branch. Refer to #5900.

Note: 
#5900 is still open due to a follow up problem.
To make it more clear, I will also close #5900 and open up a dedicated issue for the followup problem.

**Closed by Lineflyer** 2018-12-04 09:59 UTC
Labels: Bug, New Map, Unverified

**Comment by andrixnet** [comment] 2019-02-06 09:03
> 
> 
> In this case, this is most likely the issue which is already been solved on our 'master' branch. Refer to #5900.
> 
> Note:
> #5900 is still open due to a follow up problem.
> To make it more clear, I will also close #5900 and open up a dedicated issue for the followup problem.

which is ?

**Comment by Lineflyer** [comment] 2019-04-23 22:05
I think it is #7209
