### ISSUE TITLE
Manual "purge DB" option

### ISSUE THREAD

**Issue by ztNFny** [cgeo/cgeo#15841] opened 2024-07-04 21:03 UTC
When deleting a stored cache it's not deleted from DB right away but only after some time (30 days?). So if you have a cache with custom info, e.g. personal note, waypoints, .. and you delete it and save it again all this personal info will reappear.

Sometimes i have the need to delete all "non-official" info from a cache - however the above mechanism prevents that. 

I'd like to have a button in settings to purge the DB to delete all orphaned cache data.

**Comment by fm-sys** [comment] 2024-07-04 22:48
AFAIK it's 3 days and manual purge can already be triggered via settings > offline data > delete orphaned files. Hope this helps!

**Comment by ztNFny** [comment] 2024-07-05 05:15
> AFAIK it's 3 days and manual purge can already be triggered via settings > offline data > delete orphaned files. Hope this helps! 

Nope, the button doesn't do that. Neither according to the description nor to my tests.

**Comment by fm-sys** [comment] 2024-07-05 08:10
It's supposed to be like that though... See https://github.com/cgeo/cgeo/pull/11766

**Comment by ztNFny** [comment] 2024-07-05 17:13
Then I'll mark this as bug 😉

**Comment by moving-bits** [comment] 2024-07-06 16:06
Seems to work here as expected. My test case:
- open map
- create a user-defined cache
- open cache popup, press the "delete" button
- close map
- go to settings => offline => data and start maintenance function
- return to map

Newly created user-defined cache is gone.

**Comment by ztNFny** [comment] 2024-07-06 16:14
Scenario:
Store cache from GC
Add personal note - don't upload
Add waypoint in cgeo
Delete cache
Maintance
Load same cache from GC again
Note+waypoints are still there

**Comment by fm-sys** [comment] 2024-07-06 16:32
> Newly created user-defined cache is gone

UDCs have a special handling though... (#13409)

**Comment by moving-bits** [comment] 2024-07-06 19:56
I cannot reproduce this behavior. New test case:
- opened map, enabled live mode
- downloaded a new cache
- added waypoint and personal note to this cache (without uploading it)
- deleted the cache
- closed map, started settings => offline data => maintenance
- opened map (cache was shown as "unsaved")
- downloaded the cache

Neither personal note nor own waypoint was shown => ok.

You should find a debug message in your logfile (if debugging mode is enabled within c:geo) listing the number of caches removed by calling that method: `Log.d("forced database clean: removing " + withoutOfflineLogs.size() + " geocaches ignoring grace period");`

I had added some additional debug log statements in `DataStore.removeCaches()` (which is being called by `DataStore.removeObsoleteGeocacheDataDirectories()`, which is what gets called when pressing the "delete orphaned files" button). All of them showed up, including the one I place after the `database.setTransactionSuccessful()` statement.



Maybe there's some code difference between your personalized version and current `master`?

**Comment by ztNFny** [comment] 2024-07-09 20:08
hm, now I'm no longer able to repoduce ... how I hate such situations... I think the difference might be that I used a gpx for loading the cache, but even using that old gpx still in my download folder it's no longer repoducable. So I guess we could close here as unrepoducable. 


But: What do you think about refining the text describing the feature? Right now it only talks about orphaned images but doesn't mentioned this usecase (deleted caches)

**Comment by fm-sys** [comment] 2024-07-09 21:11
Yes, definitely +1 for enhancing the description.

**Comment by Lineflyer** [comment] 2024-07-10 18:43
That feature worked well for me all the time.
But indeed, cleaning up deleted caches should be part of the description.
Assigning to myself.

**Closed** 2024-07-13 16:36 UTC
Labels: Bug
