### ISSUE TITLE
UI / UX overhaul - The big picture

### ISSUE THREAD

**Issue by Pixelfahnder** [cgeo/cgeo#5927] opened 2016-08-28 12:29 UTC
After reading through the issues regarding UI stuff I was slightly shocked how many issues exist and how many people in here are willing to change the UI and the user experience.

The main points I identified reading through the ideas / bug report issues are the following:
# Customer onboarding

cgeo has many users new to Geocaching so they have to be introduced to the game / sport. Therefore issues exist for implementing a new dashboard (like #4597). Also people discussed about a showcase that has been implemented (#4175) which more or less was replaced by customer onboarding wizards and are seen seldom in market apps nowadays.
# Offline maps / Connection to data providers

The choice between maps should be existent, users should have an easy way to switch from whatever map they want to a different one like to the new GMaps API (which obsoletes the old one somewhen soon as pointed out in your long term list). Also people should be able to use the APP without a ogin at first hand or at least see their login status upfront.
# Other stuff

Many other UI overhaul wishes exist like replacing older libs to fully support tablets and so forth.

As this is a rather complex task to do this induvidually I would like to suggest a complete new UI concept that can incorporate into all the functionality of the app and should at first reside aside of the main UI product. Therefore I like to collect as much concerns about the current UI as possible. Please help me on that as I like to come up with a proper idea that affects as many concerns as possible and also helps to build a good long term product strategy as well as beeing as easy to implement as possible.

I thought to follow the material design approach as it is the status quo on Android and users are used to it combined with some elements of general flat design approaches using shapes as material describes as well but not in a full covered way.

It would also help very much if you could help me to come up with a list of all current functionality to maybe rethink the navigation structure and positioning of the functionality throughout the app.

**Comment by SammysHP** [comment] 2016-08-28 14:36
Sadly I cannot agree with your priorities and plans (although I really appreciate your effort in this topic).

### Customer onboarding

Yes, we had (and have) some issues with new user introduction / tutorials / help. As a power-user and developer you have a totally different view of things. IMHO an app must be usable without tutorials and help, just by using it. This is definitely not the case with c:geo. We tried several approaches (like the showcase which I never liked), thought about a new help, but ended with lots of support mails and a [too long FAQ](http://www.cgeo.org/faq.html).

What we need: A more intuitive UI with a minimal initial setup (create account, let's go), on-demand help (hey, what's this?) and a tips&tricks section on the website and social media.

### Offline maps / Connections to data providers

There are so many apps available, we cannot support all of them (we could, but that would be a lot of work, just compare it with Locus). On the other hand: We do not need to support so many map sources. c:geo just needs some good basemaps and my experiences show that Google Maps (and Satellite) and OSM (online + offline) are enough for most users. There's always the possibility to send a cache to a different app.

I agree that we need the new version of Google Maps and Mapsforge running in short time, but that's easy to say. At the moment only @rsudev is working on it and although he made some steps in the right direction we are not nearly to the point where it supports all features of the old implementation.

Regarding the login: Most sources work only with a login. Thus I'd say that you cannot do much without a login. Of course you could use c:geo offline via GPX imports and that already works perfect. But again, new users don't know how to work with GPX files etc. The problem is that we target new inexperienced users with long-term power-users.

### Other stuff

The UI is old. It grew during the last years. It failed and got fixed. I'm also in favor of a completely new UI. We already got some ideas (you listed some of them), but the point is: Most of the code is UI. Although there is some separation between logic and view, most of them have dependencies and are interwoven.

> It would also help very much if you could help me to come up with a list of all current functionality

Sorry, but that is not possible. c:geo has so many features that it is impossible to list all of them. There are not only directly accessible "press this and get that" functions (a lot of them hidden in deep menus and long-press actions), but also implicit functionality that happen somehow automatically in the background. c:geo was not made from scratch with a huge list of requirements and technical specifications. It was developed over years (almost 8 years already!) and new ideas were added and some old code replaced.

### Conclusion

Yes, please! We really need a new user interface which might improve the user experience. But although I suggested some drastic, fundamental changes in the past, I really doubt that they are possible. We need a lot of small steps.

**Comment by Pixelfahnder** [comment] 2016-08-28 18:54
@SammysHP I don't aggree with that. First of all you need a UI concept. To create such a base list of features supported in this new UI is nessesary as this list affects the overall concept of the interaction model as whole. Implementing is not the big problem of all of this, but the concept is! As you mentioned the target group is divers: power users vs. first timers. Out of a concept the small step by step tasks are build. One could be to open the way for a new UI by encapsulate as much of the logic to controller classes as possible and use the Android message system with handler and message objects for Frontend / Backend communication. In the meantime the overall concept can be build and can be changed step by step.

Regarding the switch of maps / different geocaching services / offline via GPX usage: This is the key part: You named it! Making this switch easy is the key to user experience. UI can be good or can be bad but the key driver is the interaction. Therefore this is not a real coding task but a task on a meta perspective, meaning thinking about how the "new" shape could be and thend discover the stept to achieve that. That means a real coding task will come out of this after people have thought how the APP should be used, meaning use case driven conceptioning of interaction models. Therefore the current existing features are a necessary list. I already spoke with a guy from here who suggested me to support with an UI overhaul and he was open to help me to come up with a list of current existing features on a screen by screen base.

**Comment by Pixelfahnder** [comment] 2016-08-28 18:56
@SammysHP by use case driven conceptioning I mean that we should look at the use cases users with different experience backgrounds have and try to find a way for them to achieve them.

**Comment by SammysHP** [comment] 2016-08-28 19:28
Have you used c:geo? If yes, you should be able to create a list yourself. We can extend it afterwards if something is missing.

PS: I've studied this sort of stuff and I know that it might work in theory, but also might fail if it is forced for something that did it in a different way.
You try to create a new app, not to change c:geo. Just looking at the kloc and changes during the years it should be obvious that an app like c:geo cannot be recreated by a few people in a few months during their spare time. If you want to do all the requirements engineering, fine. Please do it and help us making this app better. But I really doubt that anyone of us has enough time to do so much work.

**Comment by SammysHP** [comment] 2016-08-28 20:52
Just FYI: we talked about this issue in the IRC: http://irclogs.cgeo.org/?year=2016&month=8&day=28

**Comment by Pixelfahnder** [comment] 2016-08-28 21:38
@SammysHP all good. I guess you got my point wrong. I just wanted to come with a concept first before triggering all other things. I just wanted to throw it in for discussion. Maybe I was too ambigous for the first start.

Let me come up with something and we see where it all goes.

Btw. I used the APP for several years so I can and will do some of the analytics.

**Comment by Pixelfahnder** [comment] 2016-08-30 16:25
I started to collect the current functionality and will post it as an iterative list in here:

# Screen "Dashboard" (main APP entry point)

**Navigation links**
- Live-Map
- Nearby caches
- Saved caches
- Search
- Go to
- All caches

- About c:geo (twice)
- quick search
- history
- settings
- helpful APPs
- scan geocode
- invite friends

**Information**
- no. of current sattelites
- walking speed
- accurancy
_ "combined" (what is this?)


# Screen "Live map"

This features the map itself with different markers for different cache types.

- Locate me (?, it's just aguess as seems to not work for me)
- map layer (Google: map; Google: sattelite; OSM: mapnik render; OSM: open bike map)

- disable actualization
- safe for offline usage
- map settings
- strategy (strategy for what?)
- show as list (see screen **Nearby caches**)


# Screen "Helpful apps"
 THis screen features a list of other apps helpful to use when using c:geo


# Screen "Nearby caches"

This shows a list of caches with attributes like the distance and the direction compared to true north as well as the name, the GC code, difficulty and terrain values, the cache size and the count how often the cache was saved as favourite. An icon describes the cache type.

- filter (a list of applyable filters)
- sorting
- select mode
- invert selection
- save selected to list
- show on map (twice, one time with filter for different map types, one type with link to maps.me)


TBC, feel free to add / correct features identified in the screens

**Comment by pstorch** [comment] 2016-08-30 18:06
@Pixelfahnder: when you are premium member you have the menu entry "Pocket queries" between history and settings. There are some menus which change depending on current context. 
Also long click on some UI elements are used at some places to provide extra features.

**Comment by Pixelfahnder** [comment] 2016-08-30 19:33
@SammysHP the above list is far away from beeing complete but I think of how to prepare the next steps therefore it would be good to know the oldest API level to be supported by c:geo. Is it the one mentioned (9) in the manifest / gradle build file?

**Comment by Pixelfahnder** [comment] 2016-08-30 19:34
@pstorch I added it to the comment above.

**Comment by pstorch** [comment] 2016-08-30 19:39
@Pixelfahnder Map strategy is explained here: http://www.cgeo.org/faq.html#map-strategy

**Comment by SammysHP** [comment] 2016-08-30 20:17
@Pixelfahnder 
I'm not really sure about the required version. We have some compatibility code for older versions, but I don't know what is actually working.

**Comment by pstorch** [comment] 2016-08-30 20:25
`minSdkVersion="9" ` is mentioned in the `build.gradle` and the `AndroidManifest.xml`
This corresponds to Android 2.3 which is mentioned on Google Play.

**Comment by fm-sys** [comment] 2021-05-18 15:59
Let's close this issue. Things have changed since Aug. 2016 and there's not much unique in this _only-first-3-days-activly-used_ issue thread. I will move everything which is still relevant into the newly created "c:geo UX roadmap - another big picture" (#10679)

**Closed by fm-sys** 2021-05-18 15:59 UTC
Labels: Feedback required, Frontend Design
