### ISSUE TITLE
Unified map - Still artifacts when using it

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#15460] opened 2024-03-14 21:21 UTC
### Describe your problem!

Despite #15100 has been closed/fixed I do still see some regular map visualization problems while using the newest nightlies.

Such problems still appear rather often to me. I would estimate at least once per day while using c:geo.
If this is not a kind of device depending issue (just for me) I think the unified map is not ready for replacing the old map.

As I did not follow all issues I hope this is no duplicate. Else please feel free to link and close.

### How to reproduce?

It is not clearly reproducible, but AFAICS mostly occurring in kind of this scenario:
- Map a list of cache
- Use the map
- Open a cache
- Return to mapped list

Sometimes it also appears when "Enabling live" on a mapped list

### Actual result after these steps?

Here is a video which contains all artifacts I have encountered at once:
- Blinking elements
- Depending on zoom: Tiles showing strange colors
- Depending on zoom: Elements get completely "torn"
- Flickering/Blinking continues to happen also if I stop interacting with the map (just leaving it open)

Closing/Restarting the map always solves the problem.

Video capture (downsized to upload here):

https://github.com/cgeo/cgeo/assets/949669/f3517261-a546-47fa-aec1-d882421e778a

### Expected result after these steps?

No such glitches.

### Reproducible

Yes

### c:geo Version

2024.03.10-NB

### System information

```text
Samsung S24
Android 14
Netherlands OAM map (downloaded as of 10.03.2024)
Elevate theme
Map rotation automatic / energy saving (not sure if it depends on rotation)
```

**Comment by Lineflyer** [comment] 2024-03-14 21:25
Addition:
Just seeing that the fix for #15100 was only merged on March 10th:
For my capture I used 2024.03.10-NB, so this fix was most probably not part of it.

Will therefore monitor the issue next days to make sure it still appears on my device.

**Comment by Lineflyer** [comment] 2024-03-15 19:43
Not seen today on my caching trip.
@moving-bits : I guess this is also solved by your commit to solve #15100.

Closing for now

**Comment by moving-bits** [comment] 2024-03-15 21:18
Phew, I'm relieved! Thanks for cross-checking!

**Comment by MagpieFourtyTwo** [comment] 2024-03-17 09:37
Nevertheless, there are still some glitches. Happens from time to time that some rectangles are not rendered but just stay gray. This phenomenon is then limited to one zoom level; zooming in or out shows the area correctly, but returning to the "disturbed" zoom level shows the same gray rectangle again.

Had this yesterday, thus with yesterday's nightly. Most regretfully at this moment there was no time to capture a video, but will do so as soon as possible. 

Another thing I observed is that areas like woods turn white (i. e. are not rendered) on zooming in to 20 m and 10 m. Anybody else? Did not open an issue yet, as this may poss. be a theme issue. Happens with Openandromaps, offline, theme Elevate (Locus), but with theme "Standard", too. GMap and GSat are working fine at these levels.

**Comment by MagpieFourtyTwo** [comment] 2024-03-17 09:51
Tried to reproduce the vanishing woods, to get a reproducible scenario. But this time it worked. Strange. The I restarted c:geo, switched from a single OSM map (Openandromaps) to "Combined" and again got the artifacts. First the entire tile turned blue, like in @Lineflyer's video, but after zooming in and out the blue turned to gray - from where I was even able to capture a video, but did not find a way to upload it in the app. Will do so as some I get my fingers on a laptop.

**Comment by MagpieFourtyTwo** [comment] 2024-03-17 10:13
Forgot: I made a screenshot of the blue stuff, which can even now be uploaded - looked as if the route went wild ...?

![Screenshot.jpg](https://github.com/cgeo/cgeo/assets/9889015/c3dee1d2-53dc-4e56-8f3d-0aadcfe191f4)

**Comment by MagpieFourtyTwo** [comment] 2024-03-17 10:28
Forgot: I made a screenshot of the blue stuff, which can even now be uploaded - looked as if the route went wild ...?

![Screenshot.jpg](https://github.com/cgeo/cgeo/assets/9889015/c3dee1d2-53dc-4e56-8f3d-0aadcfe191f4)

And for now another try to upload a compressed version of the video:

https://github.com/cgeo/cgeo/assets/9889015/08e74490-4e8e-4210-ba02-f17ea9869b81

**Comment by MagpieFourtyTwo** [comment] 2024-03-17 10:31
Aah, and there you can even see the vanishing woods. ;)

All this BTW with today's nightly.

**Comment by fm-sys** [comment] 2024-03-17 16:35
Could reproduce as well when opening a second live map and go back to the fist one.

Maybe there is a bug that the fragment doesn't get recreated although it should?

(the orange thing is not my individual route) 

https://github.com/cgeo/cgeo/assets/64581222/bb921bc7-2304-4a37-9d4f-3bbdd3e5b324

**Comment by moving-bits** [comment] 2024-03-17 18:00
> Maybe there is a bug that the fragment doesn't get recreated although it should?

you could cross-check this by setting `feature_delayedMapFragment` to `false` which then destroys the map fragment in every `onPause` of `UnifiedMapActivity`

**Comment by MagpieFourtyTwo** [comment] 2024-03-17 21:51
> (the orange thing is not my individual route)

Interesting color. Never seen one like that in my artifacts. Do you have anything defined in ``Map appearance`` that matches this color?  OTOH there is another difference: My "possibly route-induced artifact" is not that uniform, but has several areas with different opacity. Although this could also be just due to my settings ... my routes have an opaqueness of 40 %. And history, direction and individual route have a quite similar blue, just differ in width and opacity.

**Comment by fm-sys** [comment] 2024-03-17 22:25
Sorry, just realized that I had the latest beta installed. Not today's nightly... So cannot say if situation did change in the last days. 

(things seem to get even more colorful in beta ;-)) 

![Screenshot_20240317-231537](https://github.com/cgeo/cgeo/assets/64581222/93359d94-2e2e-4267-bc6f-1d498a66cfe6)

**Comment by eddiemuc** [comment] 2024-03-18 05:45
It's almost artwork :-)

**Comment by Lineflyer** [comment] 2024-03-20 10:52
> Sorry, just realized that I had the latest beta installed. Not today's nightly... So cannot say if situation did change in the last days.
> 
> (things seem to get even more colorful in beta ;-))

Such views were gone for me in latest nightly after the PR from @moving-bits was merged.
You should try if you still see such issues in latest nightlies.

**Comment by fm-sys** [comment] 2024-03-20 17:19
Yes, can confirm. Problems are gone with the new official release.

Still wondering about @MagpieFourtyTwo's artifacts though...

**Comment by MagpieFourtyTwo** [comment] 2024-03-20 20:57
Haven't seen them since. 
But that could just be because UM is deactivated (again) most of the time. :/
Had to go back due to massive routing problems.
Will be described in #15473 

Moreover I downloaded Openandromap BalticStates and Poland - and these are completely unusable when viewed with UM activated. May also be a theme issue, but renders it nevertheless unusable. Zoom level 20 km does not show a single road - until c:geo crashes. Then 20 km suddenly shows roads, but 50 km is white again. But the regions of eastern sea covered by these are still missing completely.

**Comment by MagpieFourtyTwo** [comment] 2024-03-20 21:03
Just tested the example from [2002397845](https://github.com/cgeo/cgeo/issues/15460#issuecomment-2002397845) again:
Artifacts did not appear again, but the woods are still vanishing.

**Comment by bekuno** [comment] 2024-03-20 22:56
Bad news from my side. 
With the new release 2024.03.19 are the background artefacts not gone on my Samsung S22/Android 14 mobile.
![Screenshot_20240320_201449_cgeo_2](https://github.com/cgeo/cgeo/assets/32555742/76bf43b3-f6eb-4c6f-9e7d-28dab1fd35f6)

**Comment by MagpieFourtyTwo** [comment] 2024-03-22 11:03
Most regretfully, must retract my statement from [2010634485](https://github.com/cgeo/cgeo/issues/15460#issuecomment-2010634485):  Had the artifacts again  With today's nightly.
Happened at zoom level 500 m. I then zoomed out to 1 km, which was fine after first touch - but while writing this (phone just sitting there on the table, showing the map in zoom 1 km), the map suddenly turned blue again, like [over here](https://github.com/cgeo/cgeo/issues/15460#issuecomment-2002397845).

**Comment by tholehm** [comment] 2024-05-11 12:33
The same from my side. Samsung Galaxy S22, Android 14, cgeo version 2024.04.25. I am using the [Freizeitkarten](https://www.freizeitkarte-osm.de/android/de/index.html) maps, incl. the available themes. Unified map refreshing, when moving/rotating or zoom in/out, is buggy. "Flickering" areas, not the ful map is displayed with the correct (same) theme etc. The map loading feels very  fragmented. The issue prevents me from switching to the unified map currently.

**Comment by moving-bits** [comment] 2024-05-25 12:31
> Bad news from my side. With the new release 2024.03.19 are the background artefacts not gone on my Samsung S22/Android 14 mobile.

This might be a device-specific OpenGL issue, see the VTM discussion in https://github.com/mapsforge/vtm/discussions/1128

**Comment by Lineflyer** [comment] 2024-05-25 12:34
I did never see any issue since that above mentioned PR back in the day was merged. 
Using Samsung S24, Android 14.

**Comment by MagpieFourtyTwo** [comment] 2024-06-29 21:51
Status update: I switched back to UM after @eddiemuc made PR #15777 - and had a good user experience so far.
Although there are still some issues with individual routing and re-routing plus backgrounds like woods etc. are still vanishing at zoom levels of 20 and 10 meters, but all over all UM appears to be usable now. And, last but not least, did not have artifacts anymore, at least with the new hardware.

**Comment by moving-bits** [comment] 2024-09-22 10:54
Let's close this rather crowded issue and open separate ones if new issues arise.

Keep in mind that we may switch from VTM for UnifiedMap to Mapsforge for UnifiedMap due to several underlying problems with VTM on some systems (probably related to bugs in OpenGL implementations on some devices), and also due to unclear future of VTM due to upcoming new restrictions introduced by Google ("16kB pages" etc.)

**Closed by moving-bits** 2024-09-22 10:54 UTC
Labels: Bug, Unverified, Map: Unified
