### ISSUE TITLE
Livemap not able to access Caches on same coord

### ISSUE THREAD

**Issue by BudBundi** [cgeo/cgeo#2967] opened 2013-07-09 08:04 UTC
E.g. http://www.geocaching.com/map/default.aspx?ll=53.01587,9.26718&z=14#?ll=53.01587,9.26718&z=14
are 2 and more mysterys on same coord, gc than show a next and a Prev button to access them.
Maybe we can also make this and also phrase it to find this on livemap.
![multicoord](https://f.cloud.github.com/assets/886907/766821/199cb7c0-e86e-11e2-957f-545762d889db.png)

**Comment by Lineflyer** [comment] 2017-02-14 21:52
This is solved in Mapsforge Beta already (by providing a selection dialog) and will probably alos fixed on Google once we have V2.

**Comment by SammysHP** [comment] 2017-02-14 22:05
This is about live map parsing when multiple caches share the same marker/icon. Don't know how it is handled currently as there were some changes meanwhile.

**Comment by Lineflyer** [comment] 2017-02-14 23:03
As I mentioned above. @rsudev implemented a solutionnfor mapsforge beta at least.

**Comment by SammysHP** [comment] 2017-02-15 10:09
A solution would fix it for all map types at the same time because the problem is that multiple caches share the same coordinate and icon in the data that we receive from gc.com. It is not about the way c:geo displays the data.

**Comment by rsudev** [comment] 2017-02-15 10:41
Here it really is about gc.com live-map parsing and I didn't do anything in that area. We also have the issue of accessing nearby caches on the map displayed in c:geo on teh device, and there I implemented a solution on mapsforge beta.

**Comment by Lineflyer** [comment] 2017-02-15 11:07
OK, I see. This issue is more about how to retrieve the data for cahces on the same position from the server rather than how we display it. So nevermind regarding my comment above. We just keep it open as a known limitation.

**Comment by Lineflyer** [comment] 2019-04-23 21:56
Let me close here as:
- Feature already implemented on new OSM map
- No more new feature planned for GMapsV1
- Already a new issue created for GMapsV2

**Closed by Lineflyer** 2019-04-23 21:56 UTC
Labels: Bug, Live Map
