### ISSUE TITLE
Incorrect Date format 

### ISSUE THREAD

**Issue by Bugsy1905** [cgeo/cgeo#6609] opened 2017-06-21 13:05 UTC
##### Detailed steps causing the problem:
- 
- recently bought Xperia XZ Premium and the date format is not correctly showing my format. 
- ...

##### Version of c:geo used:

22.05.2017

##### Is the problem reproducible for you?
Yes

##### System information:
```
--- System information ---
Device: G8141 (G8141, Sony)
Android version: 7.1.1
Android build: 45.0.A.1.229
c:geo version: 2017.05.22
Google Play services: enabled - 11.0.55 (448-156917137)
Low power mode: inactive
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: rotation vector
Hide own/found: true
Map strategy: auto
HW acceleration: enabled (default state)
System language: en (c:geo forced to English)
System date format: M/d/yy
Debug mode active: no
System internal c:geo dir: /data/user/0/cgeo.geocaching (44.6 GB free) internal
User storage c:geo dir: /storage/emulated/0/cgeo (44.6 GB free) external non-removable
Geocache data: /storage/emulated/0/Android/data/cgeo.geocaching/files/GeocacheData (44.6 GB free) external non-removable
Database: /data/user/0/cgeo.geocaching/databases/data (7.0 MB) on system internal storage
Fine location permission: granted
Write external storage permission: granted
Geocaching sites enabled:
   geocaching.com: Logged in (Login OK) / PREMIUM
Geocaching.com date format: d.MM.yyyy
Installed c:geo plugins:  none
--- End of system information ---

```

##### Other comments and remarks:
e.g. Reference to other issues, projects, sources, etc.

**Comment by UniQP** [comment] 2017-06-21 13:59
Can you give an example? What format did you see and what format did you expect?

**Comment by Bananeweizen** [comment] 2017-06-21 14:59
According to your settings, a date for a log of today should be shown as "6/21/17".

**Comment by Bugsy1905** [comment] 2017-06-21 23:13
Yes you are correct, the date shows 6/21/17, I set the date format to be 21.06.2017 on Geocaching.

I can't find a way to change the setting on the smartphone it's just set as default.

**Comment by Bananeweizen** [comment] 2017-06-22 05:36
Then I think this is a duplicate of #6526. cgeo uses the date format provided by the selected Locale (read "language") for displaying. There is currently no option to override that date format.

**Comment by Lineflyer** [comment] 2017-06-22 07:56
I do see one possibilty: I do see that you forced c:geo to english. In this case it will NOT follow ypur system preference but use american date style. Please check if it changes if you disable the forced englisch in Menu Settings Appearance

**Comment by Bugsy1905** [comment] 2017-06-22 08:01
Removing the force English in cgeo settings has now cleared the issue. The dates are showing correctly now, thanks for all your help...

**Comment by Lineflyer** [comment] 2017-06-22 09:01
@Bananeweizen Its somehow strange, that this happens so often (quite some on support mail). Is it possible that we accidentally activate the force option when cgeo is running on english locale which implicitly enforces the en-us date format?

**Comment by Bananeweizen** [comment] 2017-06-23 05:37
This is not strange, this is by design. And I thought that is known. :)
You are not enforcing English language, but English _Locale_. That means _everything_ related to the country and position changes. Remember the region settings in Windows? If you change the region, you change language, currency format, datetime format and some other things all together. Same principle here.

And as far as I know, we cannot change _only_ the language.

**Comment by Lineflyer** [comment] 2017-06-23 07:50
You maybe misunderstood: I understand that the locale used if this menu option is active...however I have quite some english speaking users on support where this option is active on their english language phones without  them having activated it.

**Comment by Bananeweizen** [comment] 2017-06-23 13:35
I'm not aware of anything like that. The hard coded default is false: https://github.com/cgeo/cgeo/blob/master/main/res/xml/preferences.xml#L465, the value is not modified anywhere from the settings activity via code: https://github.com/cgeo/cgeo/blob/master/main/src/cgeo/geocaching/settings/SettingsActivity.java, and the initialization of the Locale dependns only on that setting: https://github.com/cgeo/cgeo/blob/master/main/src/cgeo/geocaching/settings/Settings.java#L1393. Also the preference key is not used twice: https://github.com/cgeo/cgeo/blob/master/main/res/values/preference_keys.xml#L62

No more ideas for how this could wrongly become enabled.

**Comment by Lineflyer** [comment] 2017-06-23 19:08
Thanks for checking the code. Maybe most likely a user fault then.

**Closed** 2017-06-23 19:08 UTC
Labels: Unverified
