### ISSUE TITLE
Sorting lists: selection not persisted and "date logged" does not relate to MY log

### ISSUE THREAD

**Issue by baiti** [cgeo/cgeo#11495] opened 2021-08-18 13:29 UTC
### Describe your problem!

When I use "Sort" for lists, it comes up by default with "distance". If I select any other choice, that choice is not persisted across calling  that list. Not sure but somehow I believe this used to be persisted in older versions of the app.

So in general, I think the selected sort method or sort criteria should be persisted on a per list basis.

Also, when I select "date logged" I always had assumed this means the date "**I**" had logged that cache but it just seems to be ordered by **ANY** log. I maintain a single list of all my finds and I'd like to have the capability to sort this list by my found date, newest first.

Can we clarify what "date logged" means and if it is not my log, can we then add an entry called: "Date found by me"

### How to reproduce?

See above

### Reproducible

Yes

### c:geo Version

2021.08.15

**Comment by eddiemuc** [comment] 2021-08-18 15:24
This seem to be two feature requests in one: The request for a persistent "sort" by list might be a duplicate of #8981

As for the second part (sort by "date logged"): this sort is implemented by cgeo.geocaching.sorting.VisitComparator and sorts caches by the field visitedDate. This field is set for DNF and found logs for a cache when it is refreshed via connector (but only for gc.com and su), when an offline log is created or when a cache is imported via GPX. Whether this behaviour is correct must be investigated in more detail. I dimly remember that we discussed about this before sometime.

**Comment by eddiemuc** [comment] 2021-08-18 15:26
> As for the second part (sort by "date logged"): this sort is implemented by cgeo.geocaching.sorting.VisitComparator and sorts caches by the field visitedDate. This field is set for DNF and found logs for a cache when it is refreshed via connector (but only for gc.com and su), when an offline log is created or when a cache is imported via GPX. Whether this behaviour is correct must be investigated in more detail. I dimly remember that we discussed about this before sometime.

Found the issue: #7919

**Comment by baiti** [comment] 2021-08-18 18:05
Now that I browsed through the referenced issue the clouds are clearing up a bit. I do not persist offline logs. Or better: only until the field notes have been uploaded then I clear all offline logs in history, then I do a "refresh all". And same as stated in the other issue, after I do a refresh of the caches in History, which were sorted perfectly before the refresh they are screwed up once the refresh completes.

I believe the issue is that GC truncates the timestamp when logs are submitted (or updated). No matter whether this is done via the proxy API or the partner API. At least, no timestamp is coming back when logs are retrieved from GC via any API / method.

So I am afraid there is nothing we can really do to fix the issue. Unfortunately.

**Comment by moving-bits** [comment] 2021-09-05 19:43
Just for info: Persisting sort order asked for again in support email.

**Comment by Lineflyer** [comment] 2022-12-29 10:32
The sorting persistence if handled in other issues (and already implemented) and the remaining problem has the state:

> So I am afraid there is nothing we can really do to fix the issue. Unfortunately.

**Closed by Lineflyer** 2022-12-29 10:32 UTC
Labels: Bug, Unverified
