### ISSUE TITLE
Allow main screen background to be solid color

### ISSUE THREAD

**Issue by bailey293** [cgeo/cgeo#8131] opened 2020-02-21 19:59 UTC
**Is your feature request related to a problem?**
I recently changed my background from all black to something not all black... and noticed that the main screen background is transparent. This is fine for those that like it, but I preferred the all black.

**Describe the solution you'd like**
A setting under appearance to select a transparent background or not. If not, the background could either follow the theme, (black for dark or white for light,) or be selectable

**Comment by Lineflyer** [comment] 2020-02-22 09:46
Duplicate of #1361

**Closed by Lineflyer** 2020-02-22 09:46 UTC
Labels: Feature Request, Unverified
