### ISSUE TITLE
Picture is lost while log offline

### ISSUE THREAD

**Issue by LosRichart** [cgeo/cgeo#6688] opened 2017-08-16 10:41 UTC
##### Detailed steps causing the problem:
- Step 1 I log the cache and take a picture (to remember the cache with no much text to write) using the tool Take a Picture in CGeo.
- Step 2 I press Save offline (I'm translating from Spanish version, so this can appear with different words). 

##### Actual behavior after performing these steps:
When I try to log it online some time later, the text I entered is ok but the picture I took is not shown. Although the picture is still saved in the proper folder of my mobile, it is not associated to the proper cache. So after several finds, it is a mess to try to remember the association...

##### Expected behavior after performing these steps:
Seeing the text I entered AND the picture I took in that cache, so I can save it online both text and picture. Pictures are important to remember the caché with no much text. It let me do the log in the field very quick... but I waste a lot of time logging it later at home, because of this problem.

##### Version of c:geo used:
2017.07.24

##### Is the problem reproducible for you?
Yes

##### System information:
```
--- System information ---
Device: SM-G935F (hero2ltexx, samsung)
Android version: 7.0
Android build: NRD90M.G935FXXU1DQGR
c:geo version: 2017.07.24
Google Play services: enabled - 11.3.02 (448-161239932)
Low power mode: active
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: orientation
Hide own/found: false
Map strategy: detailed
HW acceleration: enabled (default state)
System language: es_ES
System date format: d/M/yy
Debug mode active: no
System internal c:geo dir: /data/user/0/cgeo.geocaching (18,7 GB free) internal
User storage c:geo dir: /storage/emulated/0/cgeo (18,6 GB free) external non-removable
Geocache data: /storage/emulated/0/Android/data/cgeo.geocaching/files/GeocacheData (18,6 GB free) external non-removable
Database: /storage/emulated/0/Android/data/cgeo.geocaching/files/databases/data (1,8 MB) on user storage
Fine location permission: granted
Write external storage permission: granted
Geocaching sites enabled:
   geocaching.com: Logged in (Acceso conseguido) / PREMIUM
Geocaching.com date format: dd/MMM/yyyy
Installed c:geo plugins:  none
--- End of system information ---

```

**Comment by Lineflyer** [comment] 2017-08-16 10:44
Thanks for your report.
We are aware of this problem and your report is a duplicate of #2553

**Closed by Lineflyer** 2017-08-16 10:44 UTC
