### ISSUE TITLE
c:geo only scans internal memory for maps

### ISSUE THREAD

**Issue by kurly1** [cgeo/cgeo#5653] opened 2016-04-08 18:34 UTC
##### Detailed steps causing the problem:
- going to Menu -> Settings -> Map -> Directory with offline maps
##### Actual behavior after performing these steps:

It only Shows maps located in /storage/emulated/0/ (internal phone Memory), the one located on the SD Card are not shown.
##### Expected behavior after performing these steps:

Showing all maps regardless if they are located in internal Memory or on SD card.
##### Version of c:geo used:

2016.03.06
##### Is the problem reproducible for you?

Yes, I even reinstalled the app
##### System information:

Device: HTC One_M8 (vodafone_ch-de, htc)
Android Version: 6.0
Android build: MRA58K release-keys
Cgeo Version: 2016.03.06
Google Play Services: enabled
Low power mode: inactive
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: Rotation vector
Hide own/found: flase
Map strategy: Auto
HW acceleration: enabled (Default state)
System language: de_DE
Geocaching sites enabled:
• geocaching.com: logged in (Login OK) / PREMIUM Installed cgeo plugins: none
##### Other comments and remarks:

Because the folder cannot be selected manually (see #5652) there is no way to access the maps on the SD card from c:geo.

**Comment by Lineflyer** [comment] 2016-04-10 20:26
Can confirm this on my Galaxy S4 with Android 5.0.1. My maps on extSD are also not found.

That is AFAIK an issue we already discussed somwhen. At this time the outcome was, that that the implementation of external SD-cards was not well standardized (i.e. the directory location) thus it was not possible. But thinks might have changed or the statement was wrong?!

**Comment by rsudev** [comment] 2016-04-20 18:57
We should discriminate to cases here:
* maps in multiple directories: that is what I read from the description (one map internal, one on external sdcard). We stop scanning after finding the first directory with  maps (AFAIK)
* not searching the external sd-card: If this is still true or depends on the Android version, I would have to take a deeper look into myself. In older Android version there was no supported way to find external sd cards in case of internal-external memory present. The workarounds party possible there then fail on newer versions, where there are some with a certain level of support for this (but even there not really consistent) IIRC

**Comment by kurly1** [comment] 2016-04-20 21:15
I deleted the maps from the internal memory. But it still does not search the sd card for maps.

But since the manual selection is now working on my phone, I was able to switch manually to the maps located on the sd card.

**Comment by rahu** [comment] 2016-05-15 07:01
I also had this some time ago. Uninstalling locus app solved this for me...

**Comment by Lineflyer** [comment] 2016-05-15 13:46
> not searching the external sd-card: If this is still true or depends on the Android version, I would have to take a deeper look into myself. In older Android version there was no supported way to find external sd cards in case of internal-external memory present. The workarounds party possible there then fail on newer versions, where there are some with a certain level of support for this (but even there not really consistent) IIRC

I can confirm the behaviour, and the above mentioned will be the reason AFAIR

**Comment by polarbearing** [comment] 2016-12-23 00:49
Confirming the problem (2016.06.09 on Samsung Tab A, Android 5.1.1). Map file on internal memory is found automatically by scanning, but not in external SD. Together with #5652 I am not able to select the map in the external SD.

**Comment by polarbearing** [comment] 2016-12-26 00:44
Now that my own problem in #5652 is sorted, I can at least select the map. Still does not scan for it.

**Comment by moving-bits** [comment] 2021-01-16 17:05
@eddiemuc 
Won't that issue be obsolete with SAF due to then not being able any longer to scan the whole folder tree?
If so we should close this issue.

**Comment by eddiemuc** [comment] 2021-01-16 17:14
That's true, we can close this.

**Closed by eddiemuc** 2021-01-16 17:14 UTC
Labels: Feature Request
