### ISSUE TITLE
Can not choose Theme directory

### ISSUE THREAD

**Issue by Medvidas** [cgeo/cgeo#8578] opened 2020-07-04 09:17 UTC
**Describe the bug:**
Can not choose MAP Theme directory in SETTINGS/MAP. Pressing the "MAP THEMES DIRECTORY" does not open the directory
browsing dialog but CGEO return to its main screen. The corresponding "Directory with offline map" dialog is working ok on the same device.

**To Reproduce:**
1. Go to SETTINGS/MAP
2. Click on "MAP THEMES DIRECTORY"

**Expected behavior/state after performing these steps:**
It should open directory browsing dialog.

**Version of c:geo used:**
2020.07.02

**Is the problem reproducible:**
**Yes** / No

**Screenshots:**
You may attach screenshots if applicable and helpful to explain your problem

**System information:**
```
--- System information ---
Device: POT-LX1 (POT-LX1EEA, HUAWEI)
Android version: 10
Android build: POT-LX1 10.0.0.197(C431E3R4P1)
c:geo version: 2020.07.02
Google Play services: disabled - 20.21.17 (120408-316502805)
Low power mode: inactive
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: rotation vector
Hide caches: own/found disabled archived
Hide waypoints: -
HW acceleration: enabled (default state)
System language: cs_CZ
System date format: dd.MM.yy
Debug mode active: no
System internal c:geo dir: /data/user/0/cgeo.geocaching (12,4 GB free) internal
User storage c:geo dir: /storage/emulated/0/cgeo (12,4 GB free) external non-removable
Geocache data: /storage/emulated/0/Android/data/cgeo.geocaching/files/GeocacheData (12,4 GB free) external non-removable
Database: /data/user/0/cgeo.geocaching/databases/data (6,6 MB) on system internal storage
Fine location permission: granted
Write external storage permission: granted
Geocaching sites enabled:
   geocaching.com: Logged in (Přihlášení bylo úspěšné) / BASIC
Geocaching.com date format: dd.MM.yyyy
Installed c:geo plugins:  none
--- End of system information ---
```

**Comment by Trallali** [comment] 2020-07-04 16:25
I have exactly the same problem, but with the MAPS dialog. The THEME dialog works.
When trying to set the offline maps location (which is set now to a not anymore existing directory due to data migration from another device) a short “Searching on local directories" dialog appaers, finds nothing, then disappears, then I have a "choose directory" button. Pressing it goes instantly back to Settings->Maps. Trying this again leads to an App Crashed Dialog.

--- System information ---
Device: SM-A515F (a51nseea, samsung)
Android version: 10
Android build: QP1A.190711.020.A515FXXU3BTD4
c:geo version: 2020.07.02
Google Play services: enabled - 20.21.17 (120400-316502805)
Low power mode: inactive
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: rotation vector
Hide caches: disabled 
Hide waypoints: -
HW acceleration: enabled (default state)
System language: de_DE
System date format: dd.MM.yy
Debug mode active: no
System internal c:geo dir: /data/user/0/cgeo.geocaching (95,5 GB free) internal
User storage c:geo dir: /storage/emulated/0/cgeo (95,4 GB free) external non-removable
Geocache data: /storage/emulated/0/Android/data/cgeo.geocaching/files/GeocacheData (95,4 GB free) external non-removable
Database: /storage/emulated/0/Android/data/cgeo.geocaching/files/databases/data (828,0 KB) on user storage
Fine location permission: granted
Write external storage permission: granted
Geocaching sites enabled:
   geocaching.com: Logged in (Anmeldung OK) / PREMIUM
Geocaching.com date format: dd.MM.yyyy
Installed c:geo plugins:  none
--- End of system information ---

**Comment by bekuno** [comment] 2020-07-04 16:45
@Trallali Your problem description is the same as in #8525. Please see the state there.

**Comment by Trallali** [comment] 2020-07-04 16:55
@bekuno Thanks, I will wait for the next Locus release next week an test again.

**Comment by Medvidas** [comment] 2020-07-04 20:11
The same behavior on another device. On both of them is also Locus installed.

**Comment by Lineflyer** [comment] 2020-07-04 20:19
Duplicate of #8525. Please monitor and comment on that issue.

**Closed by Lineflyer** 2020-07-04 20:19 UTC
Labels: Bug, Unverified
