### ISSUE TITLE
Field notes work only with GC

### ISSUE THREAD

**Issue by Czarodziej** [cgeo/cgeo#4965] opened 2015-05-22 15:17 UTC
I can't save my offline log to field notes when waypoint of my cache is "OPxxxxxx". Need fix it for opencaching.

**Comment by SammysHP** [comment] 2015-05-22 15:21
Does it support uploading field notes?

**Comment by Czarodziej** [comment] 2015-05-22 15:25
For garmin file schema, yes:
http://opencaching.pl/log_cache_multi_send.php?lang=en

2015-05-22 17:21 GMT+02:00 SammysHP <notifications@github.com>:

> Does it support uploading field notes?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cgeo/cgeo/issues/4965#issuecomment-104688488>.
>



-- 
-------------------------------------------------------------------
Michał Żyłowski
http://mzylowski.pl
tel: 508057316

**Comment by Lineflyer** [comment] 2015-05-23 21:39
Duplicate of #3941 ?

**Comment by rsudev** [comment] 2015-05-24 07:49
Exactly. Closing here or there?

**Comment by Lineflyer** [comment] 2015-05-26 08:41
Here.

**Closed by Lineflyer** 2015-05-26 08:41 UTC
