### ISSUE TITLE
SAF: Picture attached via Google Fotos gets attached twice

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#10061] opened 2021-02-21 22:36 UTC
2021.02.21-NB (feedback from a nightly user):

- Create new log
- Select quick icon to attach existing image
- SAF selector is opened 
- Open hamburger menu and select the app Google Fotos (titled "Fotos" in german) and select an existing image from there

Result:
The selected picture is attached twice.
Note according to the user: If you selet multiple images only the first image is attached twice

**Comment by eddiemuc** [comment] 2021-02-22 06:06
I have a hunch what this could be.

Questions: 
* Is this reproducable?
* Does this also happen in release?
* On which device/SDK?

**Comment by Lineflyer** [comment] 2021-02-22 08:00
>   Is this reproducable?

Yes, for me and for the user

>    Does this also happen in release?

Not tested yet.

>    On which device/SDK?

For me on Android 11, for the user on Android 9

**Comment by eddiemuc** [comment] 2021-02-23 06:01
Can't reproduce on emulator.
Still I have a guess: in intent result there are two different places (fields) where image Uris are stored depending on whether user selects a single file or multiple files. I check both for uris because in my tests only one of them was filled always

My guess is that in your case both are filled (one with the first selected uri, the second one with the complete list). So I have to introduce a duplicate-uri-check.

If my guess is correct, same error should happen in release version though. This is why it would be great if this could be checked.

I hope I can tackle this on weekend.

**Comment by fm-sys** [comment] 2021-02-23 07:23
For me it is reproducible as well but only with Google Fotos. Your idea sounds logical, I will confirm if the problem has been solved, as soon as your PR is out...

**Comment by eddiemuc** [comment] 2021-02-23 17:11
@fm-sys thanks for the hint with Google Photos. With this I can reproduce also on my normal device (with release version 2021.02.14). Almost sure it is the uri thing above

**Comment by eddiemuc** [comment] 2021-02-23 18:12
Should be fixed with PR #10067 (on `release`)

**Closed** 2021-02-23 20:50 UTC
Labels: Bug, Regression

**Comment by Lineflyer** [comment] 2021-02-24 21:25
User confirmed the fix in todays nightly. Seem to work perfect.
