### ISSUE TITLE
Filtering caches from different services on the map

### ISSUE THREAD

**Issue by GodfatherThe** [cgeo/cgeo#6314] opened 2017-02-11 07:06 UTC
Problem statement:
- I'm a .SU and .COM geocaching player
- I prefer .SU caches everywhere, but in many countries there are a few .SU caches (which I definetely want to visit.) and thousands of COM caches (I will visit some of them).
- I want to have ability to see only SU caches on the map.

Solution I'm using now:
- Go to Settings -> Services and disable .COM, relaunch application, see\check\remember\save all SU caches, than enable .COM again and relaunch app. It works somehow, but pretty obvious that is't absolutely not convenient (plus, I had an issue with deleting all stored caches from service I disable, but it's another issue, so nevermind).

Suggestion:
- Add option to select desired services to show just from the map activity. Something like selecting a list to store a cache - available services with checkboxes plus button "show all".

**Comment by Lineflyer** [comment] 2017-02-21 21:48
This is a very rare usecase IMHO. 
Instead of implementing a full new feature set for this on the map I suggest, that you use the workaround to make a nearby search and filter the result by source instead.

BTW: Is the cache icon used for .SU the same as for .COM? In this case we could make the icon look like OC icsons (sqaure instead of round) or EC (brown background). Maybe that would help to distinguish on the map without needed to disable a source.

**Comment by GodfatherThe** [comment] 2017-02-22 05:16
Icons are different, for SU they're with brown background. It helps to distinguish, but it doesn't help to download "all su caches in the area"
Nearby is not a case for me because it shows only a few caches around (20 or so).  In my case I often want to save all su caches offline (as soon as I dont have internet outside of hostels often)
Filter by source is not implemended afaik.

**Comment by Lineflyer** [comment] 2017-02-23 22:24
What if you select "Show as list" after live map finished loading, then filter to Source -> SU and save the resulting list.

**Comment by GodfatherThe** [comment] 2017-03-01 13:12
Hmmm, interesting, I've never used this "show as a list" option before. Looks like it can solve almost every of my issues described.. except one - when I'm exploring new city, I still need to wait for hundreds caches to load on the map (just looked around Munich - 7 SU caches vs 300 com caches just in ~7x7km square) before I can apply filter. It would be perfect to have something like "do not load .com caches on live map right now" to avoid unnecessary load both of GC.COM and my internet connection

**Comment by zstatman** [comment] 2017-03-11 13:45
Not actually sure how to add a Feature Request so placing it here since similar:

The ability to allow multiple Diff or Terrain levels, e.g. 2.0-2.5 and also 3.0-3.5 so get all between 2.0 and 3.5

Tks

**Comment by Lineflyer** [comment] 2017-03-14 15:21
@GodfatherThe Duplicate of #4469 then.

@zstatman This is technically not possible at the moment. Still the general feature request to allow a better selection and filtering is covered by multiple issues already.

**Closed by Lineflyer** 2017-03-14 15:21 UTC
Labels: Feature Request, Feedback, Requires submitter feedback

**Comment by zstatman** [comment] 2017-05-31 15:46
Thanks Godfarther
