### ISSUE TITLE
[Nightly] After logging a cache from bottom sheet, bottom sheet is all black

### ISSUE THREAD

**Issue by MagpieFourtyTwo** [cgeo/cgeo#15120] opened 2023-12-29 23:44 UTC
### Describe your problem!

After finishing to (offline) log a cache from the hamburger menu of the bottom sheet,
c:geo's view switches back to map page with the bottom sheet still opened (which is pretty fine).
But, the bottom sheet is all black (with dark theme activated).
You have to touch and move it a little bit to make the content appear again.

### How to reproduce?

1. open map page
2. open bottom sheet for any cache
3. use hambuger menu to log the cache (offline)
4. save the log
5. c:geo will return to map view, with the bottom sheet still open (which is fine)

### Actual result after these steps?

6. Bottom sheet is empty, i. e. completely black
7. you have to touch and move the sheet a bit to make the content visible again

### Expected result after these steps?

Bottom sheet should immediately show it's content (after returning from log page).

### Reproducible

Yes

### c:geo Version

2023.12.29-NB-a3b34d4

**Comment by moving-bits** [comment] 2023-12-30 18:33
Additional info from a quick test: There is some "leftover" from the "swipe info fragment" shown:

|directly after returning from offline log|after moving the "leftover" slightly"|
|---|---|
|![image](https://github.com/cgeo/cgeo/assets/3754370/376d1d64-e9b8-4c99-80e7-84cf7dedcd24)|![image](https://github.com/cgeo/cgeo/assets/3754370/52562366-3168-405b-b926-c7b866c76cd9)|

If you move this slightly, the regular cache sheet is shown.

**Comment by moving-bits** [comment] 2024-01-03 22:33
It's not about remaining alpha value as I thought first (and what seemed to work in the beginning), so neglect above's commit.

Somehow the "swipe to open details view" fragment ends up on top of the details fragment (in terms of z-order), although fragments get removed and recreated in correct order.

**Comment by MagpieFourtyTwo** [comment] 2024-01-03 23:46
Made an add. observation:
- may be I'm wrong, but in my latest tests it seemed as if you get the BBS only if you added some text to the offline saved log
  (i. e. just saving my default log [with nothing but the automatically inserted signature], it did not end up in the BBS (today) but did always show a completely fine bottom sheet)
- if the black bottom sheet (BBS) shows up, there are two different ways c:geo will "react", which depend on the distance you pull the black bottom sheet up:
   - if you pull the BBS just a few millimeters up, i. e. until the text slightly starts to appear, and then immediately lift your finger off the display, the correct bottom sheet will be displayed.
   - BUT if you pull the BBS further, at least two thirds of the screen height, c:geo will crash

The same will BTW happen, if you do it in two steps, i. e. first pull the BBS just a little bit up, until it is displayed correctly - and if you *now* pull it a second time further up, to go to the cache listing, c:geo will crash, too, and will restart in map view with the previous bottom sheet opened.

**Comment by moving-bits** [comment] 2024-01-04 16:39
Strange: I had been able to reproduce the issue 100% a couple of days ago, but today it works without a flaw. *Sigh*
I'll cross-check on my other computer...

**Comment by fm-sys** [comment] 2024-01-04 18:41
Would it be that it was fixed by https://github.com/cgeo/cgeo/pull/15151?

**Comment by MagpieFourtyTwo** [comment] 2024-01-04 22:45
> Would it be that it was fixed by #15151?

Will check tomorrow ...

**Comment by moving-bits** [comment] 2024-01-04 23:44
> Would it be that it was fixed by #15151?

If it should fix that error, it would be accidentally. #15151 just intends to add a drag handle as additional "swipe up" indicator. The underlying "swipe up fragment" has not been removed by that PR.

But it seems to help with #14874 (at least when using a mouse in the emulator - have not tested yet with a real device). A good test case for this is the Lab Adventure "Der Hausmeister vom Palast der Republik" in Berlin, near the Museuminsel.

**Comment by MagpieFourtyTwo** [comment] 2024-01-05 09:35
Unable to check, because today's nightly does not work at all, even crashes immediately as soon as I try to log a cache.  And this no matter how you entered the cache, i. e. if trying to log via bottom sheet or from the already opened details page.  :(((

Seems as if there is a problem with getting additional (TB) data ...? 

First thought of changed website, but with an older nightly logging still works (cross-checked with my partners c:geo).

To reproduce:
- open any cache
- log visit
- after a second or two, c:geo crashes
- restarts with the cache in view
- next try to log crashes c:geo again ... 
- after repeating this several times, c:geo eventually does not crash, but gives the toast that additional data (TB and favorite) could not be downloaded
- when going back to main screen, I noticed that after this "half successful" log I am no longer logged in as premium, but as basic member only.  In order to be premium again, c:geo has to be closed, removed from recent apps, and must be restarted from scratch.

Very strange.  And bad, too, cause this completely spoils our tour today ... :/ But, hey, this is part of tester's life. :)

**Comment by MagpieFourtyTwo** [comment] 2024-01-05 09:38
https://github.com/cgeo/cgeo/assets/9889015/7bffb10d-e14b-466d-87a9-c3a828299e9e

**Comment by MagpieFourtyTwo** [comment] 2024-01-05 09:41
Another thing I noticed, which may also be related to the Basic/Premium chaos, therefore not opened a dedicated issue yet: when leaving geocaching.com service settings (after the above crashes), c:geo shows the following:

https://github.com/cgeo/cgeo/assets/9889015/c570b0b8-8eef-46d7-b353-3809c2684824

**Comment by eddiemuc** [comment] 2024-01-05 10:20
@MagpieFourtyTwo can you provide a log file?

**Comment by eddiemuc** [comment] 2024-01-05 10:29
> Another thing I noticed, which may also be related to the Basic/Premium chaos, therefore not opened a dedicated issue yet: when leaving geocaching.com service settings (after the above crashes), c:geo shows the following:
> 
>  SVID_20240105_092130_1.mp4

At first glance this seems unrelated. I get it too while changing a non-related other setting

**Comment by MagpieFourtyTwo** [comment] 2024-01-05 10:29
Detail or Standard?

**Comment by eddiemuc** [comment] 2024-01-05 10:30
> Very strange. And bad, too, cause this completely spoils our tour today ... :/ But, hey, this is part of tester's life. :)

Very very sorry for that. This is most likely a bug of mine since I changed major parts of logging in recent days/weeks...

**Comment by eddiemuc** [comment] 2024-01-05 10:30
> Detail or Standard?

always detail :-)

**Comment by MagpieFourtyTwo** [comment] 2024-01-05 10:32
Gebratene an extended one with no additional options set. Should I send it via mail or post it here as attachment? Not sure about contained data ...

**Comment by eddiemuc** [comment] 2024-01-05 10:40
(Unfortunately I have no access to the support email of c:geo)

Alternatively, you may open the logfile. I am searching for exception stack traces, they look a bit like the following example (this is totally unrelated, just to show the format). You may just post this stack trace.

```
Failed to build document stack for uri: content://com.android.externalstorage.documents/document/user%3A0%2Fcgeo.geocaching.developer%2Ffiles%2Fpublic%2FBASE
                                                                   java.io.FileNotFoundException: No root for user
                                                                   	at java.lang.reflect.Constructor.newInstance0(Native Method)
                                                                   	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
                                                                   	at android.os.ParcelableException.readFromParcel(ParcelableException.java:56)
                                                                   	at android.os.ParcelableException$1.createFromParcel(ParcelableException.java:82)
                                                                   	at android.os.ParcelableException$1.createFromParcel(ParcelableException.java:79)
                                                                   	at android.os.Parcel.readParcelable(Parcel.java:3334)
                                                                   	at android.os.Parcel.createExceptionOrNull(Parcel.java:2421)
                                                                   	at android.os.Parcel.createException(Parcel.java:2410)
                                                                   	at android.os.Parcel.readException(Parcel.java:2393)
                                                                   	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:190)
                                                                   	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:142)
                                                                   	at android.content.ContentProviderProxy.call(ContentProviderNative.java:732)
                                                                   	at android.content.ContentProviderClient.call(ContentProviderClient.java:601)
                                                                   	at android.content.ContentResolver.call(ContentResolver.java:2440)
                                                                   	at android.provider.DocumentsContract.findDocumentPath(DocumentsContract.java:1643)
                                                                   	at com.android.documentsui.DocumentsAccess$RuntimeDocumentAccess.findDocumentPath(DocumentsAccess.java:148)
                                                                   	at com.android.documentsui.LoadDocStackTask.run(LoadDocStackTask.java:80)
                                                                   	at com.android.documentsui.LoadDocStackTask.run(LoadDocStackTask.java:45)
                                                                   	at com.android.documentsui.base.CheckedTask.doInBackground(CheckedTask.java:65)
                                                                   	at android.os.AsyncTask$3.call(AsyncTask.java:394)
                                                                   	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
                                                                   	at com.android.documentsui.ProviderExecutor.run(ProviderExecutor.java:104)
```

**Comment by eddiemuc** [comment] 2024-01-05 10:57
Thanks! Issue is caused by an unhandled null-reference. For reference here is the relevant stack trace (one example of it):

Fixed with PR #15166. I will merge as soon as CI is through.

@moving-bits , @Lineflyer : is it possible to build a new nightly with this fix?

**Comment by moving-bits** [comment] 2024-01-05 11:04
> Fixed with PR #15166. I will merge as soon as CI is through.
> @moving-bits , @Lineflyer : is it possible to build a new nightly with this fix?

Yes, that's possible. Never have done it myself yet, but interface to start this job seems easy enough. I will run that job as soon as #15166 is merged an build is green.

**Comment by eddiemuc** [comment] 2024-01-05 11:07
PR is merged

**Comment by bekuno** [comment] 2024-01-05 11:20
I have started a rebuild of the nightly with NIGHTLY_NAME `2024.01.05-NB-602a5e-2`.

**Comment by bekuno** [comment] 2024-01-05 11:33
I have to retrigger a build  - the name was build to `2024.01.05-2024.01.05-NB-602a5e1-2-74d0947` - so only a `NB2` should used in the CI.

**Comment by moving-bits** [comment] 2024-01-05 11:46
New nightly build is available from https://ci.cgeo.org/job/cgeo%20nightly/lastSuccessfulBuild/artifact/main/build/outputs/apk/bin/cgeo-nightly.apk

**Comment by bekuno** [comment] 2024-01-05 11:49
Build is finished, the new version is `2024.01.05-NB2-74d0947`, see https://ci.cgeo.org/job/cgeo%20nightly/3292/console.

**Comment by MagpieFourtyTwo** [comment] 2024-01-05 12:41
Logging is working again - BIG thanks!

**Comment by eddiemuc** [comment] 2024-01-05 13:03
> Logging is working again - BIG thanks!

Thanks to you for permanently taking on the risk of alpha-testing :-) That's really super-helpful!

**Comment by MagpieFourtyTwo** [comment] 2024-01-05 13:07
> > Another thing I noticed, which may also be related to the Basic/Premium chaos, therefore not opened a dedicated issue yet: when leaving geocaching.com service settings (after the above crashes), c:geo shows the following:
> > 
> >  SVID_20240105_092130_1.mp4
> 
> At first glance this seems unrelated. I get it too while changing a non-related other setting

This BTW is still happening.
Will open an issue tonight, once we're back home.

**Comment by MagpieFourtyTwo** [comment] 2024-01-05 19:01
@moving-bits 
> > > > SVID_20240105_092130_1.mp4
> I've noticed something similar today. Probably related to the change in #15096. I'll take care of it.

Ok, so I should resp. don't need to open a dedicated issue, I guess. Feel free to do so yourself, if "needed".  :)

**Comment by moving-bits** [comment] 2024-01-05 19:06
> @moving-bits
> 
> > > > > SVID_20240105_092130_1.mp4
> > > > > I've noticed something similar today. Probably related to the change in #15096. I'll take care of it.
> 
> Ok, so I should resp. don't need to open a dedicated issue, I guess. Feel free to do so yourself, if "needed". :)

I've done so already - Issue is #15171, fix is #15172 :-)

**Comment by MagpieFourtyTwo** [comment] 2024-01-05 19:10
Even better. ;)

**Closed** 2024-01-16 15:09 UTC
Labels: Bug

**Comment by MagpieFourtyTwo** [comment] 2024-01-19 08:28
Ah, forgot about it (had already gotten so used to my workaround ;) ): Bottom sheet is working perfectly fine now - thanks for your effort!
