### ISSUE TITLE
Less map data on mapsforge beta

### ISSUE THREAD

**Issue by andrixnet** [cgeo/cgeo#6069] opened 2016-10-26 14:31 UTC
Mapsforge default. Please note the level of map details, including points of interest and labels.

![screenshot_2016-10-26-15-13-42](https://cloud.githubusercontent.com/assets/3382777/19729670/7ad8f128-9ba0-11e6-9c27-b7ec022114ca.png)

Mapsforge beta. Notice there are almost no labels and many points/features of interest (e.g. parking, etc)
## ![screenshot_2016-10-26-15-14-00](https://cloud.githubusercontent.com/assets/3382777/19729688/8c131306-9ba0-11e6-9892-6398cc8e6efa.png)

Disregard caches shown, they are not the object of this issue.
No custom map theme was used.

**Comment by Lineflyer** [comment] 2016-10-26 14:41
What theme was used and what version was the mapfile created for?

**Comment by andrixnet** [comment] 2016-10-26 14:44
- Traffic lights are missing.
- labels shown for a few inconsequential streets, while the higher rated roads have no labels, or the wrong labels (DN4 here should be Bulevardul Magheru within the city limits)
- fountain, parking, church, hotel, bar, restaurant, bus stop, theatre, etc, are missing
- some building labels are missing
- subway station at center, shown on new map, has no label, but the nearby park that has label can be mistaken as the station's label.

**Comment by andrixnet** [comment] 2016-10-26 14:49
I used the default theme. No custom theme, in fact I never even attempted custom themes for the offline map to date.

Official mapsforge download site: 
romania.map from http://download.mapsforge.org/maps/europe/

I know of no documentation and/or instruction to say otherwise.

I haven't tried the alternate maps from the other suggested download sites.

**Comment by Lineflyer** [comment] 2016-10-26 17:03
@rsudev Is the default theme cgeo uses adapted to 0.5 mapsforge?

**Comment by rsudev** [comment] 2016-10-26 17:33
The default theme is part of the mapsforge library (in both versions) and not our making. Whether we have any options to influence the default presentation I currently cannot say.

**Comment by andrixnet** [comment] 2016-10-26 17:40
should this then be escalated as issue to mapsforge? (I cannot do it because I don't know the internals)

**Comment by Bananeweizen** [comment] 2016-10-27 12:59
I actually recommend to try one of the custom themes. For me the difference between the standard theme and the "Freizeitkarte" theme is so huge, I wouldn't believe its the same map data, if I didn't know that for sure.

**Comment by SammysHP** [comment] 2016-10-27 13:55
Please keep in mind that the Freizeitkarte depends on the Freizeitkarte theme (and vice versa).

**Comment by andrixnet** [comment] 2016-10-28 10:18
Since then I have installed romania.map also from : 
- http://www.openandromaps.org/
- http://openmaps.eu/mapsforgedownload
- http://www.androidmaps.co.uk/

I got all the 4 themes from http://openmaps.eu and unpacked them on my SDcard and told c:geo where they are. c:geo then recognizes the themes as such, but activating any of them (other then default) results in an empty map, on mapsforge default.

On mapsforge beta I get the following results: 
- locus V7 high-res: error - theme not valid for this mapsforge version, reverting to builtin
- locus V7 low-res: error - theme not valid for this mapsforge version, reverting to builtin
- orux v7 : different color scheme, shows more labels, no POI, no usable street names
- vectorial v7 : looks the same as orux v7

**Comment by Lineflyer** [comment] 2016-11-01 20:31
The Orux and Locus are not meant to be used with c:geo as they are possibly adapted to those apps.

You should please try your openandromap with the elevate theme: http://www.openandromaps.org/wp-content/users/tobias/Elevate4.zip

**Comment by Lineflyer** [comment] 2018-02-15 15:45
@andrixnet 
Did you meanwhile try the elevate4 themes as mentioned above?

**Comment by Lineflyer** [comment] 2018-04-10 19:17
@andrixnet Any feedback?

**Comment by andrixnet** [comment] 2018-04-11 06:30
recheck and will get back to you.

**Comment by andrixnet** [comment] 2018-04-12 13:43
I tried several maps. 
romania.map from mapsforge downloads, v4 does not work.
romania.map from mapsforge downloads, v3 does work.
romania.map from openandromaps does work.

I tried elevate4 theme and it works (mapsforge new, nightly).
It shows things differently, not just colorwise, but also some items (points or ways) that are not shown on the default theme are visibile on elevate theme.
Also the other way around. And at different zoom levels. 

elevate4 shows some info at a lower zoom level then mapsforge default (such as traffic lights, some labels, some amenities), but shows building number only at very high zoom level.
It did render some ways like the outline of a stadium not shown on mapsforge default.

mapsforge default shows less info at lower zoom levels in general. Only shows some additional data at higher zoom levels. (higher then older version, maybe too high IMO).
It does show building numbers at a bit lower zoomlevel then elevate though.

So, IMO it's both pros and cons between elevate4 and mapsforge default.
Besides, elevate4 is more like for hiking and cycling.

------------
I am not sure about what the conclusion might be. 
That other themes show map data differently? This is confirmed, it works. 

The point of this issue is IMO about the default theme. 
Definitely the mapsforge default theme is lacking (in the newer version). 
The lack of some labels at certain zoom levels is most frustrating, as seen in the screenshots.

For example, elevate4 theme shows more items and labels, but in a significantly different way. Not just coloring. And it's for hiking in nature, mainly. 

----------------
mapsforge default I presume is the builtin theme of the library. If so, this issue is escalatable at mapsforge. 
If mapsforge bundles the default theme, maybe c:geo might have it's own derived variant.

**Comment by Lineflyer** [comment] 2018-04-16 12:48
> The point of this issue is IMO about the default theme.

Agree.

> mapsforge default I presume is the builtin theme of the library. If so, this issue is escalatable at mapsforge.

AFAIR @rsudev told me, that the new version of the library also contains a new default them (which we use) as part of it. 
As far as I understand the mode of these themes, the threshold to display more info is configurable within these themes. As you wrote above the info seems not to be missing, but only visible at other/higher zoom levels. So its rather not a bug but a not so nice threshold selected my mapsforge.

So I would like to break this issue down to the topic, to check and maybe optimize the default theme used for the new mapsforge library. OK for you @andrixnet ?

**Comment by andrixnet** [comment] 2018-04-17 07:43
Sure

**Comment by Lineflyer** [comment] 2019-04-24 08:46
@andrixnet 
Can I ask you to take a look again whether this shortcomings of the default theme as still there, because the current nightlies are using a newer mapsforge version thus also a new default theme (which might have changed meanwhile).

**Comment by andrixnet** [comment] 2019-04-25 19:14
Will take a look this weekend and return

**Comment by andrixnet** [comment] 2019-05-07 09:25
![combine_screenshot_20190426](https://user-images.githubusercontent.com/3382777/57288652-8f339700-70c2-11e9-83c2-3af460289a66.png)

Comparing v3 and v4: 
Mapsforge v3:
- - very small amenity icons
- + thin countours
- + thin roads
- + additional street names
- ~ additional names of points (sometimes too much)
- + one way arrows

Mapsforge v4:
- + good sized amenity icons
- ~ thicker countours _(sometimes helps visibility, but also obscures other details)_
- - thick roads. _(just look at the blobbing in "Parcul Coltea" and DN4 in southern part)_
- - less street names
- ~ some point names replaced with icons
- - mising one way arrows.

**Comment by andrixnet** [comment] 2019-05-07 09:33
![combine_screenshot_2019042-](https://user-images.githubusercontent.com/3382777/57289329-d706ee00-70c3-11e9-8eed-e40932adecc4.png)

Another comparison at different scale. 
Mapsforge v3:
- clearer streets
- less visible icons (too small)
- more icons (useful)
- more point labels (a bit too much clutter)

Mapsforge v4:
- no amenity icons (though many would still be useful and relevant)
- roads too large, some leading to blobbing
- no street labels at all

Overall v4 is cleaner but blobbier, with less useful information besides shapes.

**Comment by andrixnet** [comment] 2019-05-07 09:40
At different zoom levels, v3 has some advantages over v4, with more (useful and relevant) information.

v4 seems cleaner (due to less info) and with better render of amenity icons on high res devices.
But some/many shapes are blobbier at multiple zoom levels which damages map shapes readablity.
And it displays significantly less useful information besides shapes.

Both seem to favour building numbers over street name, with v4 not displaying street names at any but very high zoom levels.

**Comment by bekuno** [comment] 2019-05-07 09:58
Please have a look at the different rendering styles for differen map themes and theme options.
Eg., I can see one way arrows in map theme "standard", but not in Elevate or Elements.
(some of them are self installed from map providers)
WIth the theme options to map styles you can view/hide some map elements.

**Comment by SammysHP** [comment] 2019-05-07 13:48
I think these screenshots look absolutely fine. It should be obvious that the development did not only happen at the backend but also at the frontend (default theme). Some differences are to be expected.

**Comment by andrixnet** [comment] 2019-05-08 07:34
Well, the new style in v4 is cleaner, has better icons. 
Except for: 
- way blobbing (this is the most significant)
- lack of street names

**Comment by andrixnet** [comment] 2019-08-22 09:57
To further this point, now with additional tests following the release of 2019.08.18: 

OSM (online tiles) display a better map as regard to additional information shown. 
This shows proper street names and some significant POI in a very useful fashion. 

![Screenshot_20190822-124704_cgeo](https://user-images.githubusercontent.com/3382777/63505327-05c29c00-c4dc-11e9-9ee3-5fe4c6faba4b.jpg)
 
This offline OSM mapsforge v4 map shows much less street names (at this zoom level having names only for the primary roads is waaay to little).
Doesn't show several POI visible in the online tiles. 
Shows street numbers (without street names) which are practically useless for (most scenarios of) geocaching.
![Screenshot_20190822-124714_cgeo](https://user-images.githubusercontent.com/3382777/63505525-589c5380-c4dc-11e9-85f0-966d56dda121.jpg)

**Comment by Lineflyer** [comment] 2019-08-22 10:19
Did you already check the recently implemented theme-option menu in the map menu?
This should allow to customize the appearance and display of different elements.

**Comment by SammysHP** [comment] 2019-08-22 10:35
Also keep in mind that every map creator includes a different amount of details. Some maps do not use the limited set of default map features and require special themes. And as lineflyer said, some themes allow further customization.

**Comment by SammysHP** [comment] 2019-08-22 10:37
IMHO we can close this as it is not related to c:geo. What do you think, @Lineflyer?

**Comment by Lineflyer** [comment] 2019-08-22 10:53
Lets wait for the feedback of @andrixnet. 
I did not in depth test the theme option implementation, so I would love to get some user feedback.

**Comment by andrixnet** [comment] 2019-08-26 20:13
@SammysHP I am writing all this from an **end-use perspective**, and, although I am fairly skilled myself, I strive to put myself in the shoes of a **less skilled users**. I have personally helped a good number of users configure and install offline maps into their c:geo because it was beyond their skill level and/or simply too complex a task to attempt, not necessarily due to laziness (_though it has it's part_). 

In all my examples I use the mapsforge provided maps. (same as the library authorship, right?) Both v3 and v4 (or newer). This is the first link in c:geo documentation, thus the likeliest to be tried by the user. 
Also I do understand (_from previous discussions_) that, technically, c:geo uses the default, mapsforge library builtin theme, which has it's limitations and is also IMO suboptimal for geocaching purposes.

@Lineflyer I've known about the "theme" option for a long time now. I've tested it sometime this spring with mixed results. I have no knowledge about theme authoring and I tried to use existing themes. First, finding themes was quite a pain. >99% of the users would've given up long before me. I found some. Then I downloaded several versions (none of which were listed as "for c:geo"), hoping at least one of them would be suitable. Then I copied them to my device and tried to make sense which theme (as it appeared in the UI) was which file, because more then half the themes I tried back then did not work. Those that worked didn't really appear that much different (maybe those that had previews with different coloring didn't work?).
The discussion here also highlights these difficulties: https://github.com/cgeo/cgeo/issues/6071
Anyway, it was a very discouraging experience. 

-----------------------

In conclusion: 

All my points are intended for a reasonably optimal-for-geocaching map display (theme) by default, considering the most likely map provider = the same as library provired = mapsforge. (See also the issue about UI based map download) in ways that makes it easy for the non-technical, non-skilled user and does not require extended patience and digging.

If the current API UI refers to selecting a predefined theme file that one has to search and download for manually, then IMO is of little interest, except maybe for few advanced users. 

If the API UI would provide a dialog with multiple switches to allow the user to select what map features to display and what to hide, including per-zoom-level, then indeed this would be a useful feature. 
Here is a suggestion from OSMAND: 
![Screenshot_20190826-230250_OsmAnd](https://user-images.githubusercontent.com/3382777/63719534-c5ee1280-c855-11e9-80b1-336ba756760c.jpg)

**Comment by SammysHP** [comment] 2019-08-27 04:31
I think you should forward your requests to the mapsforge team. They decided, which features their default theme should include. We cannot really improve the theme. Don't forget that every map can use its own rules for the internal naming of features and thus might require a special theme.

AFAIK we have listed some other map providers in our FAQ. Not sure if we list any providers in c:geo at all.

**Comment by jonas-koeritz** [comment] 2019-08-27 07:56
I really think many mapsforge themes need an update, I personally use Elevate 2 and can verify that the missing street names are a major problem. Mapsforge had several issues discussing when a streetname could be rendered and it's kind of dependent on font size and street width (they want the street name to fit inside the road or they don't draw it at all).

Maybe it's time to create out own theme to bundle with c:geo thats specifically made for geocaching. I really understand that it's hard for users to get the whole offline maps and theme thing right and bundling a different default theme would make things a lot prettier and easier (+ we can kind of give c:geo the look we want ;)).

I think I will give this a shot, should be a seperate project IMO that c:geo can depend on.

**Comment by rsudev** [comment] 2019-08-27 08:33
I don't think we have the capacity to jump into the map-making business, there are other projects providing that as their core competence (openandromaps, freizeitkarte, ...)
Regarding easier integration, this is not as easy as it may look. On the one hand we would need a provider which allows us to integrate his map download area with c:geo. And on the other hand do we want to avoid having separate map file storage if you have another mapsforge-compatible application on your device. I personally e.g. share my maps between c:geo and orux maps.

In order to make progress in this area, we need IMO:
* a concept, how to integrate offline map handling into c:geo in a way that fulfills the mentioned considerations:
  * end-user 'compatible'
  * usable maps (good themes, maintained regularly, we are allowed to integrate)
  * map storage sharing with other mapsforge apps
* resources to implement it

**Comment by jonas-koeritz** [comment] 2019-08-27 09:06
> If the API UI would provide a dialog with multiple switches to allow the user to select what map features to display and what to hide, including per-zoom-level, then indeed this would be a useful feature.

Thats what "Theme Options" does in c:geo. So the App already provides these options when using a theme that supports it (e.g. Elevate 4). Am I missing something here?

**Comment by andrixnet** [comment] 2019-09-09 08:55
@jonas-koeritz I don't know what are you refering to, the only UI things about theme in c:geo that I can see are about selectin which predefined map theme to use (the default, or alternate, if user installed them manually, outside c:geo). 
My usage context is the simplest for the user (although somewhat difficult for most non-technical people I had contact with) with an offline map from mapsforge (using "default" theme).

**Comment by jonas-koeritz** [comment] 2019-09-11 09:21
It depends on the map theme you have selected, if your map theme supports it there will be options to show/hide some details on the map. The default theme IMO is pretty limited and I am already thinking about how to handle this problem.
#6072 could be a major improvement in this area.

**Comment by andrixnet** [comment] 2019-11-28 20:06
Using default theme (as per c:geo install and only map file provided by user) I could find no such menu.

**Comment by SammysHP** [comment] 2019-11-28 20:26
The default theme does not support such options. You should see map and theme as a bundle that comes together and one cannot work without the other.

IMHO we should not try to make our own default and just ask the mapsforge dev team if they can improve their default theme.

**Comment by andrixnet** [comment] 2019-11-29 14:55
Installing a map file for offline use is easy with the help of the FAQ. Finding and adding a custom theme took me a lot more digging and trying and many errors, until I simply gave up and stuck to the default, as I saw no significant differences in the themes that I did manage to get working. 

So either way, there is room for improvement and I hope things will get better in the not too distant future. 
Thank you.

**Comment by SammysHP** [comment] 2019-11-29 19:58
Then please address the Mapsforge team, they are responsible for the default style. Maps like Freizeitkarte require a specific theme and won't work with the default theme (missing elements).

**Comment by Lineflyer** [comment] 2019-11-29 20:47
> Finding and adding a custom theme took me a lot more digging and trying and many errors, until I simply gave up and stuck to the default, as I saw no significant differences in the themes that I did manage to get working.

May I suggest, that you give it another try on openandromaps.org?

They have a broad base of country maps available incl. the matching theme "elevate4". Once you installed these you will most probably have all you requested in your postings above. 
Thats nothing which can be solved within c:geo.

**Comment by Lineflyer** [comment] 2019-12-02 12:44
@andrixnet 
I used some spare time to generate a tutorial for maps and also for themes and their adaption. It also lists some sources for more sophisticated maps and themes. Using this you should be able to find a suitable map/them for your requirements and configure it correctly.

I think this is all we can do right now.

https://manual.cgeo.org/en/offlinemaps

**Closed by Lineflyer** 2019-12-02 12:44 UTC
Labels: Feedback required, New Map OSM
