### ISSUE TITLE
Save for offline saves also already stored caches

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#6878] opened 2017-12-10 20:08 UTC
From support mail (translated by myself):

Since this version (2016.12.06) I have the problem, that if I e.g. see 50 caches on the map and I select "Save for Offline" all 50 caches are saved but not only those currently not yet saved. This worked in previous versions.

**Comment by pstorch** [comment] 2017-12-10 20:44
I saw a similar issue mentioned on FB. The user has 12.000 caches saved in a list and from time to time opens the Live Map to see if there are new caches around. Then wants to save only the new ones.

Isn't it a duplicate of #6831 ?

**Comment by pstorch** [comment] 2017-12-10 21:03
The two issues are not 100% duplicates but have the same cause. This here is about storing already stored caches and the #6831 is about the visibility of the menu item.

The reason for this regression is the fix for #6654. I don't think we want to revert it. 
There are two use cases:
1. a user wants to store all visible caches on the map to a certain list regardless of if some caches are already on another list
1. a user wants to store (a.k.a. download) only those caches visible on the map which are not already downloaded

To support both use cases we have to check which are not yet offline available and download only those but store all of them to the selected list(s). Right?

**Comment by Lineflyer** [comment] 2017-12-10 21:08
Depends.
We could also split into two functions in the menu:
Store all 
Store unsaved

**Comment by pstorch** [comment] 2017-12-10 21:09
Yes, that would make it more explicit.

**Comment by pstorch** [comment] 2017-12-11 20:45
Let me check

**Closed** 2017-12-15 21:42 UTC
Labels: Bug, Regression, Unverified
