### ISSUE TITLE
Quick access to filter from map view

### ISSUE THREAD

**Issue by dl1ely** [cgeo/cgeo#3346] opened 2013-10-08 15:03 UTC
I would like to see a possibility to have quick access to the filters applied on caches from the (live)-map view, without going back to the main menu. Redrawing the map takes too long to enjoy jumping back and forth between the map and the main menu,

**Comment by caco3** [comment] 2016-05-13 12:01
According to @Lineflyer comment this is a regression bug.
Did anybody trace down when/why it got broken?

**Comment by fm-sys** [comment] 2020-07-14 05:13
7 Years later the bug is still unfixed :-(

Maybe the function was disabled because the map had problems applying this filter change...

**Comment by jakedot** [comment] 2020-07-15 09:39
I agree, it is quite tedious to always have to say "show as list" on the map to apply filters, only to then have to open a new map activity and with only the caches in the viewport at the initial map. This should be fixed by changing the global "cache type" filtering to a modern, new filter activity imo.

**Comment by fm-sys** [comment] 2020-07-15 14:36
@jakedot Are there any more specific plans?  I think the current UI is anything but user-friendly... 
If there's nothing else, I'd like to draw a first sketch!

The new user interface should solve the following issues:
- multiple filters at once 
- better usability 
- combination of values for D/T filtering (enabled by from-to-sliders) 
- combine cache type and property filter
- Usage also directly in the live map (in limited form, the cache attributes are not loaded yet AFAIK)

Are there any other? Please tell me, so that I can complete the list...

**Comment by jakedot** [comment] 2020-07-15 15:01
thanks for listing all those points, they're all valid imo. I have looked through the various existing issues that mention "filter" and I think most of them have popped up somewhere before.

I think we could use the filter activity in the GS official app as a possible design template, and add our more complicated filters. The most unclear for me is what a UI that allows chaining filters together multiple filters might look like, if you want to be able to also negate filters / use and/or semantics etc.

**Comment by Lineflyer** [comment] 2020-07-15 15:32
@fm-sys If you browser our issues (e.g. for keywords "filter" or "UI design") you will probably find a bunch of issues, some with a specific request, others which discuss the big picture of a UI overhaul and the corresponding discussion.

None of these however are currently ongoing.
I guess it will make sense to first of all start with a generic new UI approach (following Android style guidelines) to some extent and later on implement specific new features into it following that UI design.

**Comment by fm-sys** [comment] 2020-07-15 16:23
I don't want to change the whole UI.  The dark mode from Android 1 - 4 is now modern again 😁

I think it is difficult to redesign an app that has been growing for over 10 years. Already in 2011 there were ideas that were never implemented except for small selective changes... 

So i don't think we should wait to restructure the filters. The problem is to find someone who can & wants to implement this extensive change...

**Comment by jakedot** [comment] 2020-07-15 16:29
I want to, but I haven't been able to do much more but wanting since I (partly) implemented the country filters. so I don't know about "can"

**Comment by fm-sys** [comment] 2020-07-16 18:53
> The most unclear for me is what a UI that allows chaining filters together multiple filters might look like, if you want to be able to also negate filters / use and/or semantics etc.

Negate filters and use and/or is not needed everywhere... 

- Type (checkboxes - or) 

- Size (checkboxes - or) 

- Terrain (only 1 or 5 doesn't makes sense, so you don't need negating - you would just have the slider) 

- Difficulty (same as terrain) 

- Attributes (and - but here maybe an and/or switch and also negating for each Attribute would be useful - this could be tricky to design) 

- Status (checkboxes - maybe also an and/or switch)  

- Saved (drop-down box) 

- Origin (could a cache have multiple linked services? If not this is also only or) 

- Distance (slider) 

- Favorites (slider)  

- Favorites [%] (slider) 

- With own information (and/or switch) 

- Assigned to a list (and/or switch) 

- Country / Region (or)

And all single categories are linked to each other with *and*. 

But do we need all this listed and/or stuff for every category? For example, why should I filter for Caches in Germany *or* France? Even if we leave out some options, it is still a huge step forward! And every change where we have to change not only the front end but also changes to the code makes development more difficult... We should not want to improve too much at once.  How about implementing and/or within the categories later (if it comes to that at all)?

**Comment by jakedot** [comment] 2020-07-20 12:56
Right now if we choose to just implement the current behaviour in the lists for the map also, I think we have enough to worry about:

- the "global" cache type filter, which is applied and displayed additionally to the selected filter in a list
- only one filter concurrently applicable in the lists
- what about map being opened from a filtered list, do we display those filters?
- interactions of existing "map - list - filter - map" chains - how would we know multiple filters have been applied already, if only the last list's filter is known?

So I think that starting from scratch is easier here, and for that we might need a new activity, as the current one just supports selecting one filter.

Probably we should consistently display all filters applied so far in both list and map views. Maybe also the source of the initial map or list view (live search result, stored list, ...)?

**Comment by fm-sys** [comment] 2020-07-20 18:14
I'm currently working on the new OFFLINENUM signature variable, but when that's done we could try to develop this new activity together, if you like. 

Unfortunately I have never coded for Android before, so I'm not sure if we will manage it. But maybe also other developers would like to help us, if we have a specific problem...

**Comment by eddiemuc** [comment] 2021-05-17 04:57
I would consider this closed with new filter available in map (quick settings for now, but let's see where it ends up :-))

**Closed by eddiemuc** 2021-05-17 04:57 UTC
Labels: Bug
