### ISSUE TITLE
Selection box "NEIN" in status filter is cut off

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#11120] opened 2021-07-06 18:20 UTC
On my device there is plenty of space, still the "NEIN" bo is cut off with "NE...". Can't provide a screenshot at this time, but will file another issue.

Screenshot will follow next week.

_Originally posted by @Lineflyer in https://github.com/cgeo/cgeo/issues/11117#issuecomment-874982035_

**Comment by eddiemuc** [comment] 2021-07-07 09:38
Is it still cut of when you change layout to "landscape"?

**Comment by murggel** [comment] 2021-07-07 10:40
> Is it still cut of when you change layout to "landscape"?

In my case yes:
portrait:
![Screenshot_20210706-164115_cgeo.jpg](https://user-images.githubusercontent.com/70113341/124620455-c0ae7580-de79-11eb-8fa1-8b54199ae13c.jpg)

landscape:
![Screenshot_20210707-122925_cgeo.jpg](https://user-images.githubusercontent.com/70113341/124745530-3705b300-df20-11eb-9d41-99c28766eb90.jpg)

**Comment by eddiemuc** [comment] 2021-07-07 11:16
Ok I think I know what the problem is.

You should know that there's a logic to force the three buttons to have the same width for all lines (for nice design). So I assume the "hat eigene Wertung" Line is responsible for the cut-off in portrait mode.

When you turn to landscape, I assume this width is not recalculated which is why it is cut off there too


@murggel to test my theory: would it be possible for you to add a new status filter while in landscape mode (my assumption is that there's no cut-off in this case)?

**Comment by murggel** [comment] 2021-07-07 11:20
Sorry, but the landscape screenshot was taken with filter opening already in landscape and add the status filter, so there is already a problem on initialization

**Comment by murggel** [comment] 2021-07-07 11:24
I will try to set it to English... probably depends on translation behavior? 

Hm, but there the strings are really short...

**Comment by eddiemuc** [comment] 2021-07-07 11:32
Hmm, then it must be something different...

**Comment by eddiemuc** [comment] 2021-07-07 13:29
This is strange. Look at how it looks in my device (SDK29 emulator) when I make the texts very long:

![image](https://user-images.githubusercontent.com/6909759/124767424-18131b00-df38-11eb-8c84-00a6542fc470.png)

**Comment by murggel** [comment] 2021-07-07 13:36
I will check on my emulators...

**Comment by murggel** [comment] 2021-07-07 13:40
With a one tick smaller font int the phone-settings it looks good

**Comment by eddiemuc** [comment] 2021-07-09 19:53
Almost forgot about this one... fixed with PR #11160

**Closed** 2021-07-10 04:52 UTC
