### ISSUE TITLE
changing storage location crashes with android.view.InflateException: Binary XML file line #44: Error inflating class <unknown>

### ISSUE THREAD

**Issue by muelli** [cgeo/cgeo#8062] opened 2020-01-07 17:29 UTC
**Describe the bug:**
cgeo crashes when I try to move data to the SD Card

**To Reproduce:**

Go to Settings -> Offline Data -> Select Geocache data directory and select the SD Card

**Actual behavior/state after performing these steps:**

```
01-07 18:23:17.369 11803 11803 D AndroidRuntime: Shutting down VM
01-07 18:23:17.374 11803 11803 E AndroidRuntime: FATAL EXCEPTION: main
01-07 18:23:17.374 11803 11803 E AndroidRuntime: Process: cgeo.geocaching, PID: 11803
01-07 18:23:17.374 11803 11803 E AndroidRuntime: android.view.InflateException: Binary XML file line #26: Binary XML file line #44: Error inflating class <unknown>
01-07 18:23:17.374 11803 11803 E AndroidRuntime: Caused by: android.view.InflateException: Binary XML file line #44: Error inflating class <unknown>
01-07 18:23:17.374 11803 11803 E AndroidRuntime: Caused by: java.lang.reflect.InvocationTargetException
01-07 18:23:17.374 11803 11803 E AndroidRuntime: 	at java.lang.reflect.Constructor.newInstance0(Native Method)
01-07 18:23:17.374 11803 11803 E AndroidRuntime: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:430)
01-07 18:23:17.374 11803 11803 E AndroidRuntime: 	at android.view.LayoutInflater.createView(LayoutInflater.java:645)
01-07 18:23:17.374 11803 11803 E AndroidRuntime: 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:787)
01-07 18:23:17.374 11803 11803 E AndroidRuntime: 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:727)
01-07 18:23:17.374 11803 11803 E AndroidRuntime: 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:858)
01-07 18:23:17.374 11803 11803 E AndroidRuntime: 	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
01-07 18:23:17.374 11803 11803 E AndroidRuntime: 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:861)
01-07 18:23:17.374 11803 11803 E AndroidRuntime: 	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
01-07 18:23:17.374 11803 11803 E AndroidRuntime: 	at android.view.LayoutInflater.parseInclude(LayoutInflater.java:994)
01-07 18:23:17.374 11803 11803 E AndroidRuntime: 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:854)
01-07 18:23:17.374 11803 11803 E AndroidRuntime: 	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
01-07 18:23:17.374 11803 11803 E AndroidRuntime: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:518)
01-07 18:23:17.374 11803 11803 E AndroidRuntime: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:426)
01-07 18:23:17.374 11803 11803 E AndroidRuntime: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:377)
01-07 18:23:17.374 11803 11803 E AndroidRuntime: 	at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:412)
01-07 18:23:17.374 11803 11803 E AndroidRuntime: 	at com.android.internal.app.AlertController.installContent(AlertController.java:252)
01-07 18:23:17.374 11803 11803 E AndroidRuntime: 	at android.app.AlertDialog.onCreate(AlertDialog.java:423)
01-07 18:23:17.374 11803 11803 E AndroidRuntime: 	at android.app.ProgressDialog.onCreate(ProgressDialog.java:198)
01-07 18:23:17.374 11803 11803 E AndroidRuntime: 	at android.app.Dialog.dispatchOnCreate(Dialog.java:395)
01-07 18:23:17.374 11803 11803 E AndroidRuntime: 	at android.app.Dialog.show(Dialog.java:294)
01-07 18:23:17.374 11803 11803 E AndroidRuntime: 	at cgeo.geocaching.activity.Progress.show(Progress.java:55)
01-07 18:23:17.374 11803 11803 E AndroidRuntime: 	at cgeo.geocaching.storage.LocalStorage.changeExternalPrivateCgeoDir(LocalStorage.java:340)
01-07 18:23:17.374 11803 11803 E AndroidRuntime: 	at cgeo.geocaching.settings.SettingsActivity.lambda$null$4$SettingsActivity(SettingsActivity.java:334)
01-07 18:23:17.374 11803 11803 E AndroidRuntime: 	at cgeo.geocaching.settings.-$$Lambda$SettingsActivity$xe5YyUxpWGDqicGAfhf2okVoqDw.onClick(lambda)
01-07 18:23:17.374 11803 11803 E AndroidRuntime: 	at com.android.internal.app.AlertController$ButtonHandler.handleMessage(AlertController.java:166)
01-07 18:23:17.374 11803 11803 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
01-07 18:23:17.374 11803 11803 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
01-07 18:23:17.374 11803 11803 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6119)
01-07 18:23:17.374 11803 11803 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
01-07 18:23:17.374 11803 11803 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
01-07 18:23:17.374 11803 11803 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
01-07 18:23:17.374 11803 11803 E AndroidRuntime: Caused by: java.lang.UnsupportedOperationException: Failed to resolve attribute at index 3: TypedValue{t=0x2/d=0x1010036 a=1}
01-07 18:23:17.374 11803 11803 E AndroidRuntime: 	at android.content.res.TypedArray.getColorStateList(TypedArray.java:528)
01-07 18:23:17.374 11803 11803 E AndroidRuntime: 	at android.widget.TextView.<init>(TextView.java:775)
01-07 18:23:17.374 11803 11803 E AndroidRuntime: 	at android.widget.TextView.<init>(TextView.java:704)
01-07 18:23:17.374 11803 11803 E AndroidRuntime: 	at android.widget.TextView.<init>(TextView.java:700)
01-07 18:23:17.374 11803 11803 E AndroidRuntime: 	at com.android.internal.widget.DialogTitle.<init>(DialogTitle.java:41)
01-07 18:23:17.374 11803 11803 E AndroidRuntime: 	... 32 more
01-07 18:23:17.384  2774 18032 W ActivityManager:   Force finishing activity cgeo.geocaching/.settings.SettingsActivity
01-07 18:23:17.405  2774 18032 D ActivityTrigger: ActivityTrigger activityPauseTrigger 
01-07 18:23:17.406  2774 11996 W DropBoxManagerService: Dropping: data_app_crash (3148 > 0 bytes)

```

**Expected behavior/state after performing these steps:**

I expected the app to do anything but crash.

**Version of c:geo used:**

2019.12.30 from f-droid

**Is the problem reproducible:**
Yes, 100%, all the time.

**System information:**
```
--- System information ---
Device: Aquaris X5 Plus (Aquaris_X5_Plus, bq)
Android version: 7.1.1
Android build: 2.7.0_20181002-1711
c:geo version: 2019.12.30
Google Play services: enabled - 19.8.31 (040308-284611645)
Low power mode: inactive
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: rotation vector
Hide own/found: false
HW acceleration: enabled (default state)
System language: en_GB
System date format: dd/MM/y
Debug mode active: no
System internal c:geo dir: /data/user/0/cgeo.geocaching (629.2 MB free) internal
User storage c:geo dir: /storage/emulated/0/cgeo (629.2 MB free) external non-removable
Geocache data: /storage/emulated/0/Android/data/cgeo.geocaching/files/GeocacheData (629.2 MB free) external non-removable
Database: /storage/emulated/0/Android/data/cgeo.geocaching/files/databases/data (4.6 MB) on user storage
Fine location permission: granted
Write external storage permission: granted
Geocaching sites enabled:
   geocaching.com: Logged in (Login OK) / BASIC
   opencaching.de: Logged in (Login OK)
Geocaching.com date format: d. M. yyyy
Installed c:geo plugins:  none
--- End of system information ---
```

**Additional context:**

**Comment by moving-bits** [comment] 2020-01-07 21:44
Duplicate of #7533

**Closed by moving-bits** 2020-01-07 21:44 UTC
Labels: Bug, Duplicate
