### ISSUE TITLE
Waypoint calculator: Accept and resolve more formulas

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#7912] opened 2019-10-23 20:16 UTC
Stumbled upon this issue while trying to solve https://coord.info/GC58ZXR:

If you copy the formula in the listing `N41°53. ((A/(B/3))+D)/2 E12°28. (C*B)+(A*(B/2))+(A+(C*4)-1)` to the waypoint calculator (wpc) and enter values for A, B, C and D, the wpc is not able to solve the calculation. It stays at something like "N41° 53.1234/2" and "E12°28.30+123+45" (those are not the actual values, but you get the idea).

Feature wish is to detect such settings and calculate the final coordinates.

**Comment by Lineflyer** [comment] 2021-12-26 14:14
@eddiemuc 
Something to consider or at least a complex example for the new variables. Not sure whether I should add it to your project, therefore just pinging you.

**Comment by eddiemuc** [comment] 2021-12-26 15:07
This should already work with the new calculator. But I can't try it out currently, so I just add it to the project.

**Comment by eddiemuc** [comment] 2021-12-31 10:13
Ok, I tried this out, this is the result:

![image](https://user-images.githubusercontent.com/6909759/147817260-423505ae-5003-423a-85c8-d4087faa618b.png)

As you can see the coordinate is parsed. BUT it is probably not parsed as expected by the user. 

The reason is the space between the Minutes decimal point and the part behind this decimal point (why on earth did the owner put this space there btw?). Current coordinate parser interprets the part before the space (e.g. "53.") as minutes and the part after the space (e.g. "((A/(B/3))+D)/2") as seconds. I implemented it this way so the parser would be able to handle cases where users don't explicitly specify °, ' and/or ". For example:

* N48 12.345 -> is parsed as N48° 12.345'
* N48 12 34.567 -> is parsed as N48° 12' 34.567"

If I remove the spaces, then the coord is parsed as probably expected by the user (as DD MM.MMM):

![image](https://user-images.githubusercontent.com/6909759/147817539-9269a403-9137-443d-8516-6cac5fc75620.png)


Are there any suggestions on how coordinate parsing should be changed to avoid this?

**Comment by eddiemuc** [comment] 2021-12-31 10:17
BTW, a happy new year and all the best wishes for 2022 to all of you!

**Comment by Lineflyer** [comment] 2021-12-31 10:59
@eddiemuc Happy New Year also to you!

Shouldn't we just trim the user imput automatically by removing all white spaces in between? I am sure there are also formulas out there like this:
`N41°53. ((A / (B / 3)) + D) / 2 E12°28. (C * B) + (A * (B / 2))+(A + (C * 4)- 1)`

**Comment by eddiemuc** [comment] 2021-12-31 11:09
> @eddiemuc Happy New Year also to you!
> 
> Shouldn't we just trim the user imput automatically by removing all white spaces in between? I am sure there are also formulas out there like this: `N41°53. ((A / (B / 3)) + D) / 2 E12°28. (C * B) + (A * (B / 2))+(A + (C * 4)- 1)`

If you simply remove all whitespaces then other problems appear. For example:

`N48 12.345` -> `N4812.345` -> `N4812.345°` (instead of the obsiously meant `N48° 12.345'`)

BTW: the parser is clever enough to now when a space is inside of `()` and when not (and inside `()` spaces are already ignored). So while your formula example will not work indeed, at least the following will work:

`N41°53.(((A / (B / 3)) + D) / 2)` (note that I put an additional pair of `()` around the expression after the `.`)

See screenshot:

![image](https://user-images.githubusercontent.com/6909759/147820137-ace75578-582d-4bb6-b657-8ce212072d86.png)

**Comment by fm-sys** [comment] 2021-12-31 13:21
> If you simply remove all whitespaces then other problems appear. For example:
>
>N48 12.345 -> N4812.345 -> N4812.345° (instead of the obsiously meant N48° 12.345')

However, `N 4 8 ° 1 2 . 3 4 5` should be parsable, cause it's totally unambiguous. Maybe some kind of if/else to catch both cases?

**Comment by eddiemuc** [comment] 2021-12-31 14:10
> > If you simply remove all whitespaces then other problems appear. For example:
> >
> >N48 12.345 -> N4812.345 -> N4812.345° (instead of the obsiously meant N48° 12.345')
> 
> However, `N 4 8 ° 1 2 . 3 4 5` should be parsable, cause it's totally unambiguous. Maybe some kind of if/else to catch both cases? 

Would be happy to see the pseudo-code for this magic if/else... :-)

The challenge of course is not to optimize parsing for single cases but to find a decent (and fast) algorithm which can handle all common cases. 

I would not bother much to make the above case parseable. Although it might be unambiguous, whoever writes.something like that clearly does not want his coordinate to be parsed anyway.

Do not confuse this discussion with a future discussion about a "scan for waypoints" function which can also find formulas. Here we simply talk about what should be possible if the user enters the coordinate himself into the calc coordinate dialog (he might start with a copy from somewhere but he can always edit it)

**Comment by eddiemuc** [comment] 2021-12-31 14:33
I just had an idea how to resolve this:

since the problem is simply caused by "too many spaces" in some cases, I propose to simply add a button "Remove Spaces" to the "calculated coordinate" dialog. Tapping it removes all spaces from the formulas. If this results in unwanted coordinates (e.g. "N4812.345°" then the user can correct this manually.

Could look like this (pseudo):

![image](https://user-images.githubusercontent.com/6909759/147828437-4dac3b41-f3e8-40a6-bc3d-be7bddcfc0e3.png)

**Comment by eddiemuc** [comment] 2021-12-31 14:35
What do you think?

**Comment by fm-sys** [comment] 2021-12-31 15:09
That sounds like a good workaround 👍

**Comment by eddiemuc** [comment] 2022-01-08 11:04
"Remove Space" button is now part of master, so closing this:

![image](https://user-images.githubusercontent.com/6909759/148641773-d62c6547-f046-4eac-b78e-eb6ec5ea1a26.png)

**Closed by eddiemuc** 2022-01-08 11:04 UTC
Labels: Feature Request, WP Calc
