### ISSUE TITLE
New "integrated" checker from Groundspeak is ignored

### ISSUE THREAD

**Issue by MagpieFourtyTwo** [cgeo/cgeo#7013] opened 2018-05-09 14:14 UTC
##### Detailed steps causing the problem:
- in a web browser open a mystery with Groundspeak's integrated checker (e. g. https://coord.info/GC7MD0Z)
- have a look at the the checker, integrated into the listing
- open the same mystery in c:geo
- look for the checker ...

##### Actual behavior after performing these steps:
- there is no checker at all, not even a hint, that there would be one in the web browser ...

##### Expected behavior after performing these steps:
- show the checker or at least a hint to change to the web version to be able to use the checker

##### Version of c:geo used:
- 2018.02.05

##### Is the problem reproducible for you?
Yes

##### System information:
--- System information ---
Device: E6853 (E6853, Sony)
Android version: 7.1.1
Android build: 32.4.A.1.54
c:geo version: 2018.02.05
Google Play services: disabled - 12.5.29 (040408-192802242)
Low power mode: active
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: rotation vector
Hide own/found: true
Map strategy: auto
HW acceleration: enabled (default state)
System language: de_DE
System date format: dd.MM.yy
Debug mode active: no
System internal c:geo dir: /data/user/0/cgeo.geocaching (7,2 GB free) internal
User storage c:geo dir: /storage/emulated/0/cgeo (7,2 GB free) external non-removable
Geocache data: /storage/emulated/0/Android/data/cgeo.geocaching/files/GeocacheData (7,2 GB free) external non-removable
Database: /data/user/0/cgeo.geocaching/databases/data (209,0 MB) on system internal storage
Fine location permission: granted
Write external storage permission: granted
Geocaching sites enabled:
   geocaching.com: Logged in (Anmeldung OK) / PREMIUM
   extremcaching.com: Logged in (Anmeldung OK)
Geocaching.com date format: dd MMM yy
Installed c:geo plugins: contacts
--- End of system information ---

Would be great if this could be fixed.

Thanks a lot in advance!

**Comment by Lineflyer** [comment] 2018-05-09 14:16
Thanks for your issue, we already have this listed as a feature request here: #6792 

Closing as duplicate of #6792

**Closed by Lineflyer** 2018-05-09 14:16 UTC
