### ISSUE TITLE
Caches from disabled sources shown on live map

### ISSUE THREAD

**Issue by c64datenklo** [cgeo/cgeo#3097] opened 2013-08-02 22:34 UTC
Hi,

Opencaching works fine, but I like do deactivate it. In the Menu, i can do this, but the past shown caches are still there and the MAP cannot be refreshed or cleaned.

The problem is, that the icons won't disappear. For example, if you logged a GC Cache, the OC Icon will Overlay the GC Icon. You cannot see, if you have logged the GC Cache. So you want to be able to deactivate the OC Icon.

Reconstruction of this issue:
1. Use a GC Account in gceo
2. add the OC Option without an account
3. be happy to see the OC Caches.
4. Remove the OC Option because the GC Caches are overlayed.
5. View the result. Both Cache Types are Shown

regards..

**Comment by Lineflyer** [comment] 2017-02-14 22:05
Duplicate of #3779

**Closed by Lineflyer** 2017-02-14 22:05 UTC
Labels: Live Map, Refactoring
