### ISSUE TITLE
Waypoint list not updated after creating a waypoint by click on map

### ISSUE THREAD

**Issue by MagpieFourtyTwo** [cgeo/cgeo#7136] opened 2018-09-08 11:11 UTC
##### Detailed steps causing the problem:
1. verify that option "Old Mapsforge V3" is not set
2. open a cache listing
3. switch to map view using compass icon on either Listing or Waypoint list page
    if Google Map or Satellite view is active, switch to a Mapsforge map (e. g. Mapnik or Openandromap),
    leave map view and reopen it
4. long click on map -> "Add waypoint" dialogue will open -> click "Save"
5. New Waypoint will be shown on map
6. leave map and go back to Waypoint list page

##### Actual behavior after performing these steps:
The newly created Waypoint is not shown in the list - until you refresh or leave and re-enter the cache listing.

##### Expected behavior after performing these steps:
The newly created Waypoint should appear in the list immediately.

##### Version of c:geo used:
2018.08.14

##### Is the problem reproducible for you?
Yes

##### System information:
--- System information ---
Device: E6853 (E6853, Sony)
Android version: 7.1.1
Android build: 32.4.A.1.54
c:geo version: 2018.08.14
Google Play services: disabled - 12.8.74 (040408-204998136)
Low power mode: active
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: rotation vector
Hide own/found: true
Map strategy: auto
HW acceleration: disabled (manually changed)
System language: en (c:geo forced to English)
System date format: M/d/yy
Debug mode active: no
System internal c:geo dir: /data/user/0/cgeo.geocaching (8.4 GB free) internal
User storage c:geo dir: /storage/emulated/0/cgeo (8.4 GB free) external non-removable
Geocache data: /storage/emulated/0/Android/data/cgeo.geocaching/files/GeocacheData (8.4 GB free) external non-removable
Database: /data/user/0/cgeo.geocaching/databases/data (255.4 MB) on system internal storage
Fine location permission: granted
Write external storage permission: granted
Geocaching sites enabled:
   geocaching.com: Logged in (Login OK) / PREMIUM
   extremcaching.com: Logged in (Login OK)
Geocaching.com date format: dd MMM yy
Installed c:geo plugins: contacts
--- End of system information ---

##### Other comments and remarks:
Is this feature already documented? Stumbled upon a while ago by accident while using OpenAndroMap with new Mapsforge version - and although it reads pretty straight forward, when looking at the list of prerequisites below, it took a while until I figured out, how, where and when this wonderful new possibility for Waypoint creation pops up ...  ;)
Please correct me, if I'm wrong, but it seems as if it just works with
a) OSM maps
b) new Mapsforge version
c) when entering map via cache listing
d) if so, it does not matter if "Enable live" is set or not
Am I correct?

**Comment by MagpieFourtyTwo** [comment] 2018-09-10 09:51
So I at least got it right.  ;)
And thanks for checking it.

> Its only possible for map of a cache listing as the new WP needs to be associated to a cache.

This is pretty obvious - but it would be fine (and more intuitive and straight forward, I guess) if it would work too, when entering the map using the compass rose of a waypoint of a cache, as this is the context of a cache, too ...  :)

**Comment by MagpieFourtyTwo** [comment] 2018-09-10 09:55
That it does not work, when looking at a waypoint map, was in fact the most irritating thing when trying to get used to this feature. ;)

**Comment by rsudev** [comment] 2018-09-10 19:07
Not fully correct. You can get a cache context on any (new mapsforge) map by selecting it (or a waypoint of it) as navigation target. Than a long-press creates a new waypoint for that cache (see also https://github.com/cgeo/cgeo/wiki/%27New-Map%27-feature-description)

**Comment by MagpieFourtyTwo** [comment] 2018-09-10 21:10
Hmm. Just tried. Interesting. And good, of course!

But doing so, (and while reading the quoted description "When in navigation mode, a long press on the map jumps into a waypoint creation dialog for the target cache and the selected location") it seems to be even more incomprehensible to me, why it does not work when tapping the compass rose icon of a waypoint in the cache's waypoint list, as I understand this tap as just another way of entering the same (navigation) mode ... or do I just don't get "Navigation Mode" right?

BTW: This "When tapping more than one cache" list thingy is very cool stuff, too! Thx a lot!  ;)

**Comment by rsudev** [comment] 2018-09-11 11:58
One reason could be, that I virtually never use the 'waypoint map' (that's how it is called internally) and therefore it likely didn't occur to me to check and enable it in that situation as well. I'll take a look whether this can be easily achieved, as it for sure would be more consistent that way.

**Comment by MagpieFourtyTwo** [comment] 2018-09-11 13:55
Great! Thanks a lot!

P.S.: Waypoint map's essential for us when doing Multis.

**Comment by geocachermgo** [comment] 2018-10-03 21:31
Super Feature!
Does not work any more if I switch from OSM to other map and back to OSM.
Would love it to work also with the offline maps.

**Comment by Lineflyer** [comment] 2020-05-04 08:28
Duplicate of #8292

**Closed by Lineflyer** 2020-05-04 08:28 UTC
Labels: Bug, New Map OSM
