### ISSUE TITLE
Tapping on zoom button opens cache, if cache icon beneath zoom controls

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#14136] opened 2023-03-25 14:42 UTC
### Describe your problem!

User report on support:

Tapping on zoom controls opens cache/waypoint popup, if cache/waypoint icon is located beneath the zoom button

### How to reproduce?

- open Google Maps
- pan map until a cache or waypoint icon is located beneath the zoom controls
- hit zoom control

### Actual result after these steps?

cache/waypoint popup opens

### Expected result after these steps?

zoom control should be activated instead of cache/waypoint popup opening

### Reproducible

Yes

### c:geo Version

2023.02.25

### Additional Information

ticket number 808999

Mapsforge `NewMap` does not seem to be affected.

**Comment by fm-sys** [comment] 2023-03-25 15:34
Duplicate of #7569

**Closed by fm-sys** 2023-03-25 15:34 UTC
Labels: Bug, Map: GMapsV2

**Comment by moving-bits** [comment] 2023-03-25 18:47
> Duplicate of #7569

good catch
