### ISSUE TITLE
Logging stopped working after updating to newest version

### ISSUE THREAD

**Issue by katzamum** [cgeo/cgeo#15634] opened 2024-04-18 04:11 UTC
### Describe your problem!

Error message:
Posting Log failed.

Reason: It seems that your log was not posted.  Please check it on the cache originating website.

The website responded with following message:
LOG ERROR(user=katzamum):
Problem pasting log, response is: cgeo.geocaching.connector.gc.GCLOgApi$GCWebLogResponse, status=403, isSuccessful=false, response=REsponse{protocol=http/1.1,code=403, message=Forbidden, url=https://www.geocaching.com/api/live/v1/logs/GCAFX7Y/geocacheLog}, body = 

I received the same error with GC7TTV3, GC9P62K, G80YM6, GCA19TG

### How to reproduce?

1. enter cache log on c:geo app
2. click the "send" icon to post the log
3. receive the error message as above

### Actual result after these steps?

The error message above is shown.

### Expected result after these steps?

Log is posted, verification received.

### Reproducible

Yes

### c:geo Version

2024:04:13

### System information

```text
DEVICE
Device type: SM-G991W (o1qcsx, samsung)
Available: 8
Android version: 14
Android build: UP1A.231005.007.G991WVLSAFXC1
Screen resolution: 1080x2176px (360x725dp)
Pixel density: 3.3000002
System font scale: 1.1 / used scale 1.1
Sailfish OS detected: False
Google Play services: enabled - 24.12.17 (190408-623887440)
Memory: Available: 2.2 GB Total: 7.2GB Threshold: 390.0MB, low: false
```

**Comment by eddiemuc** [comment] 2024-04-18 05:19
Closing as duplicate of #15633

**Closed** 2024-04-18 05:19 UTC
Labels: Bug, Unverified
