### ISSUE TITLE
Proximity Notifications Not Working When Screen is Turned Off

### ISSUE THREAD

**Issue by anondev-sudo** [cgeo/cgeo#15533] opened 2024-03-29 19:18 UTC
When the option to play sound for closest or most distant geocaches or waypoints is enabled in the settings, proximity notifications do not trigger when the phone screen is turned off. This results in missed geocaches as notifications are not received while the phone is in the pocket.

Steps to Reproduce:
Enable the option to play sound for closest or most distant geocaches or waypoints.
Turn off the phone screen.
Approach a geocache or waypoint to trigger proximity notifications.
Note that no notifications are received while the screen is off.

Expected Behavior:
Proximity notifications should still trigger and play sound even when the phone screen is turned off, ensuring users are alerted to nearby geocaches or waypoints.
Actual Behavior:
Notifications are not received when the phone screen is off, leading to missed geocaches and the need to backtrack.

**Comment by moving-bits** [comment] 2024-03-29 20:54
Closing here as duplicate of #15193, but I've copied your more detailed description over there

**Closed by moving-bits** 2024-03-29 20:54 UTC
Labels: Duplicate
