### ISSUE TITLE
Mapsforge beta: no display of stored caches on Live map in offline mode

### ISSUE THREAD

**Issue by kirchwitz** [cgeo/cgeo#6330] opened 2017-02-18 03:02 UTC
##### Detailed steps causing the problem:
The following problem only occurs with the experimental map rendering library "Mapsforge beta". With the default map rendering library (old Mapsforge) everything is absolutely fine.

As prerequisite, have some geocaches stored so that they can be displayed on Live map even when offline. Then go to Settings/System, enable the experimental map rendering library "Mapsforge beta". Go back to the Live map and select "Disable live" mode (no auto-loading of geocaches).

Your previously stored geocaches (for offline use) will no longer be displayed. The map is completely empty. No geocaches at all.

Switch to "Enable live" mode, and magically all previously stored geocaches pop up.

This is independent of an existing network connection (mobile or WiFi).

##### Actual behavior after performing these steps:
Basically, "Disable live" mode on Live map no longer works with "Mapsforge beta". The Live map always has to be in "Enable live" mode to display any caches. But in this mode the only way to keep c:geo from loading additional caches is to disable all network connections completely (which might not be desirable).

##### Expected behavior after performing these steps:
Live map in "Disable live" mode (offline mode) should still display all stored caches (like it does now with the old default mapsforge library). This is useful to run c:geo in a battery saving mode. Then c:geo works very similar to a traditional GPS device. I usually have my mobile network connection enabled most of the time so that those apps that really need Internet access may use it. In opposite to that, cool apps like c:geo allow to store everything offline (caches + maps) which is really great because it saves a lot of battery power even if there's an existing network connection.

##### Version of c:geo used:
Official from Google Play store (currently 2017.02.07). However, happens since at least August 2016.

##### Is the problem reproducible for you?
Yes

##### System information:
```
--- System information ---
Device: GT-I9305 (m3xx, samsung)
Android version: 4.4.4
Android build: KTU84P.I9305XXUFNL1
Cgeo version: 2017.02.07
Google Play services: enabled - 10.2.98 (036-146496160)
Low power mode: active
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: rotation vector
Hide own/found: true
Map strategy: auto
HW acceleration: enabled (default state)
System language: en_US
System date format: yyyy/MM/dd
Debug mode active: no
Fine location permission: granted
Write external storage permission: granted
Geocaching sites enabled:
geocaching.com: Logged in (Login OK) / PREMIUM
opencaching.de: Logged in (Login OK)
Geocaching.com date format: yyyy-MM-dd
Installed cgeo plugins: none
--- End of system information ---
```

##### Other comments and remarks:
That problem might seem low priority as long as "Mapsforge beta" is not the default map rendering library. However, it may keep c:geo users from trying "Mapsforge beta" and giving feedback about other problems they might discover. So in the end, it may also help you with development.

Personally, I'd really like to try out "Mapsforge beta" more often because it seems quite usable already and most map providers no longer support themes for old mapsforge libraries. Soon, using old themes may cause more headaches than using an experimental map renderer.

In any way, I've filed this issue so that the problem doesn't get forgotten, whenever you may be ready to fix it. Now or later.

Keep up the good work!

**Comment by SammysHP** [comment] 2017-02-18 06:41
Duplicate of #5929. Can you test a nightly build? (Don't forget to make a backup.)

**Comment by Lineflyer** [comment] 2017-02-19 20:40
@kirchwitz As @SammysHP has stated, this is a duplicate and has already been solved some days ago. I tested it today, and it should now work as with the non-beta maps (despite other small glitches on the beta already listed as an issue here).

**Closed by Lineflyer** 2017-02-19 20:40 UTC
