### ISSUE TITLE
Send to c:geo disappeared in Firefox browser

### ISSUE THREAD

**Issue by Pafka63** [cgeo/cgeo#6622] opened 2017-06-30 14:52 UTC
##### Detailed steps causing the problem:
I upgraded Firefox last week to 52.2.1 version. After this I cannot see "send to c:geo" button/link on any geocaching page (ie, listing w/o button, detail on map w/o link, etc). 

Open, eg:
https://www.geocaching.com/geocache/GC77V28_princezna-v-kocare

##### Actual behavior after performing these steps:
no button Send to c:geo next to "Send to My GPS"

##### Expected behavior after performing these steps:
button Send to c:geo next to "Send to My GPS"

##### Version of c:geo used:
Send to c:geo FF plugin version 0.38

##### Is the problem reproducible for you?
Yes

##### System information:
Windows 7 SP1, Firefox 52.2.1 (32-bit)

##### Other comments and remarks:
On Toolbar, on www.geocaching page, there is "monkey button". After clicking arrow next to it, I can see "Sent to cgeo" and "Geocaching map enhancement" both marked as active. But, as I said, no button.
![s2c](https://user-images.githubusercontent.com/29800035/27741162-7801ee1a-5db4-11e7-9417-7bacef50aa14.png)

**Comment by SammysHP** [comment] 2017-06-30 14:53
Wrong repository and duplicate of cgeo/send2cgeo#36.

**Closed by SammysHP** 2017-06-30 14:53 UTC
