### ISSUE TITLE
Cannot switch to English c:geo

### ISSUE THREAD

**Issue by gcey** [cgeo/cgeo#9156] opened 2020-10-06 14:13 UTC
**Describe the bug:**
When I switch c:geo to English, most of its user interface is still German

**To Reproduce:**
1. "Einstellungen"
2. "Erscheinungsbild"
3. "Auf Englisch"
4. Leave c:geo
5. Even reboot the mobile phone
6. Restart c:geo

**Actual behavior/state after performing these steps:**
The homescreen still shows the German words "Live-Karte", "In der Nähe", ...
But one is English now: "All Cache Types"
Also many menu items are still German, e.g. "Einstellungen"

**Expected behavior/state after performing these steps:**
The whole user interface should be English.

**Version of c:geo used:**
2020.10.04

**Is the problem reproducible:**
Yes

**System information:**
```
Device: SM-G965F (star2ltexx, samsung)
Android version: 10
Android build: QP1A.190711.020.G965FXXSBETH2
c:geo version: 2020.10.04
Google Play services: enabled - 20.36.15 (120400-333172415)
Low power mode: inactive
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: rotation vector
Hide caches: own/found
Hide waypoints: -
HW acceleration: enabled (default state)
System language: en (c:geo forced to English)
System date format: M/d/yy
Debug mode active: yes
System internal c:geo dir: /data/user/0/cgeo.geocaching (9.2 GB free) internal
User storage c:geo dir: /storage/emulated/0/cgeo (9.2 GB free) external non-removable
Geocache data: /storage/0000-0000/Android/data/cgeo.geocaching/files/GeocacheData (129.0 GB free) external removable
Database: /storage/emulated/0/Android/data/cgeo.geocaching/files/databases/data (96.2 MB) on user storage
GPX import path: /sdcard/gpx
GPX export path: /sdcard/gpx
Offline maps path: /storage/0000-0000/LocusExtSD/mapsVector
Map render theme path:
Live map mode: true
Global filter: display all caches
Fine location permission: granted
Write external storage permission: granted
Geocaching sites enabled:
geocaching.com: Logged in (Login OK) / PREMIUM
Geocaching.com date format: yyyy-MM-dd
Installed c:geo plugins: contacts
BRouter connection available: false
```

**Comment by fm-sys** [comment] 2020-10-06 14:29
duplicate of #8709 / #7991

**Closed by fm-sys** 2020-10-06 14:29 UTC
Labels: Bug, Unverified
