### ISSUE TITLE
Moto G compass fails completely

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#5250] opened 2015-10-20 21:23 UTC
From support mail.

A user performed an upgrade to Android 5.2 which was offered by Motorola for his device.
Afterwards the compass of c:geo stopped working.

I first advised to try the setting of using the orientation sensor...He reported back that it is not selectable.

Other compass apps are working all the time before and after the upgrade.

The sys info is as follows:
```
--- System information ---
Device: XT1032 (falcon_retde, motorola)
Android version: 5.1
Android build: LPB23.13-56
Cgeo version: 2015.09.28
Google Play services: disabled
Low power mode: inactive
Compass capabilities: yes
Rotation sensor: absent
Orientation sensor: present
Hide own/found: false
Map strategy: detailed
HW acceleration: enabled (default state) 
System language: de_DE 
Geocaching sites enabled:
- geocaching.com: logged in (Login OK) / Premium
 Installed cgeo plugins: none
--- End of system information ---
```

@samueltardieu 
Is it really possible that the device does not provide rotation sensor but only orientation?

**Comment by samueltardieu** [comment] 2015-10-20 21:52
Yup, this is possible. I don't know what is wrong.

**Comment by GSNord** [comment] 2015-10-22 11:01
Having the very same problem since the last Motorola system update. It was not an Android update; still Android 5.1; it was a firmware update for my Moto G device.
Android Version 5.1
Kernel Version 3.4.42-g89906d6
System Version 221.21.56.falcon_umts.Retail.en.DE

I performed a compass recalibration using GPS Status+Tools app. So the compass seems to work using GPS Status+Tools, but with some strange behaviour. It points to north most of the time, but movement is faster since the system update. Also the compass is influenced by the horizontal g-sensor; i.e. if I shake the device left to right the compass starts rotating.

Using cgeo, the compass initially points to the direction of the cache, but it will not move any more when I turn the device.

**Comment by GSNord** [comment] 2015-10-23 08:55
Checked it with Google Maps today. It is my out-of-the-box never-updated version 9.4.0 Google Maps of 2014.
It rotates the map correctly when I rotate my device. However, it also turns the map for some degrees when I shake the device horizontally.

**Comment by samueltardieu** [comment] 2015-10-25 17:30
@GSNord Can you please double-check that you haven't activated the GPS-only mode (from the Compass screen)?

**Comment by GSNord** [comment] 2015-10-25 21:56
I noticed that the new cgeo version can switch between compass+GPS and GPS only in the compass screen. The described behaviour is when I use compass+GPS.
When I switch to GPS only, the pointer works correctly but only when I move, like my Magellan Explorist which has no magnetic sensor.

**Comment by samueltardieu** [comment] 2015-11-07 17:00
Assigning to @Lineflyer for field testing before merging this into `release`. I'll try to find a tester myself, a friend of mine happens to have a Moto G.

**Comment by GSNord** [comment] 2015-11-07 21:18
Have been in contact with Motorola support. They feel no responsibility for this issue. They recommend a factory reset of my phone an a re-install of cgeo; which I will not do because I know that won't help.
There is another app, clever-tanken.de, which does not turn its map any more since the firmware update.

**Comment by rsudev** [comment] 2015-11-07 21:24
@GSNord  You can now try the latest nightly build whether this fixes the issue for you

**Comment by GSNord** [comment] 2015-11-07 22:54
Checked out the NB version, and I can confirm that normal compass functionality is back on Motorola G. 
I appreciate your work. Thank you!

**Comment by Stapvoetje** [comment] 2015-11-16 09:20
@GSNord  Where can I find the NB version because I have the same compass problem after the upgrade.

**Comment by kumy** [comment] 2015-11-16 09:53
@Stapvoetje you may find them there: http://www.cgeo.org/status.html. Links are on the first column.

**Comment by SammysHP** [comment] 2015-11-16 10:34
Or on our website: http://www.cgeo.org/development.html#download-nightly-builds

**Comment by Stapvoetje** [comment] 2015-11-16 13:44
@kumy and @SammysHP ,

Thanks for the help. The compass works fine now with use of the NB version

**Comment by Lineflyer** [comment] 2015-11-19 22:53
As users are confirming the fix and I can confirm that there does not seem to be a regression it is OK for me to merge into `release`

**Comment by Lineflyer** [comment] 2015-11-19 22:53
Assigning @samueltardieu for merging to `release`

**Comment by Stapvoetje** [comment] 2015-11-20 10:26
I have used the compass in c:geo NB version and must say it works fine. I'm happy!

**Comment by samueltardieu** [comment] 2015-11-20 10:46
Merged into `release`.

**Closed by samueltardieu** 2015-11-20 10:46 UTC
Labels: Assigned-non-collab, Bug, Field test

**Comment by GSNord** [comment] 2015-12-11 19:36
So how can I go back to Release channel now? I installed the nightly build from apk file. Now Google Play store says I am current and does not allow any update.

**Comment by rsudev** [comment] 2015-12-11 19:49
You could uninstall c:geo and then re-install from Play, but unfortunately would you loose you stored caches, as the database structure changed on master, and downgrades are not supported.
So you would have to wait until the next feature release, to switch back over.
