### ISSUE TITLE
POI symbols WAY too big

### ISSUE THREAD

**Issue by MagpieFourtyTwo** [cgeo/cgeo#7505] opened 2019-04-15 19:19 UTC
##### Detailed steps causing the problem:
- ensure setting "Old Mapsforge V3" is off ([_]) 
- open Live Map
- activate an OpenAndroMap with any Elevate map style
- have a look at the POI symbols ...

##### Actual behavior after performing these steps:
- POI symbols are WAY too big

##### Expected behavior after performing these steps:
- POI symbols should be scaled down (as they have been before today's Nightly)

##### Version of c:geo used:
- c:geo version: 2019.04.15-NB-017b502

##### Is the problem reproducible for you?
- Yes

##### System information:
```
--- System information ---
Device: E6853 (E6853, Sony)
Android version: 7.1.1
Android build: 32.4.A.1.54
c:geo version: 2019.04.15-NB-017b502
Google Play services: disabled - 16.0.89 (040408-239467275)
Low power mode: active
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: rotation vector
Hide own/found: true
Map strategy: detailed
HW acceleration: enabled (default state)
System language: de_DE
System date format: dd.MM.yy
Debug mode active: no
System internal c:geo dir: /data/user/0/cgeo.geocaching (6,3 GB free) internal
User storage c:geo dir: /storage/emulated/0/cgeo (6,3 GB free) external non-removable
Geocache data: /storage/emulated/0/Android/data/cgeo.geocaching/files/GeocacheData (6,3 GB free) external non-removable
Database: /data/user/0/cgeo.geocaching/databases/data (238,6 MB) on system internal storage
Fine location permission: granted
Write external storage permission: granted
Geocaching sites enabled:
   geocaching.com: Logged in (Anmeldung OK) / PREMIUM
   extremcaching.com: Logged in (Anmeldung OK)
Geocaching.com date format: dd MMM yy
Installed c:geo plugins: contacts
--- End of system information ---
```

##### Other comments and remarks:
With yesterday's Nightly sizes of POI symbols were perfectly fine; after applying today's update, they are HUGE. After setting option "[X] Old Mapsforge V3" their size is as usual again ...

**Comment by MagpieFourtyTwo** [comment] 2019-04-15 19:20
![190415 Map POI Symbols](https://user-images.githubusercontent.com/9889015/56159177-51ac8400-5fc4-11e9-8d56-98ca0a81e931.jpg)

**Comment by Lineflyer** [comment] 2019-04-15 19:37
@rsudev 
That seems to be related to the upgrade to mapsforge 0.11.0, I can however not reproduce that with todays NB using openandromap with elevate style.

@MagpieFourtyTwo 
Can you point out the exact source (URL) of your map and theme?

**Comment by MagpieFourtyTwo** [comment] 2019-04-16 19:42
Just reinstalled the theme, but to no avail, symbols are still enormous.
My Downloads:
- http://download.openandromaps.org/maps/Germany/baden-wuerttemberg.zip (e. g.)
- https://www.openandromaps.org/wp-content/users/tobias/Elevate2_OruxMaps_XL.zip
Doesn't matter which Elevate style is activated.

**Comment by Lineflyer** [comment] 2019-04-16 21:24
Elevate 2 is outdated and for older mapsforge versions (and also no longer maintained by openandromaps).

Please try with Elevate 4:
https://www.openandromaps.org/wp-content/users/tobias/Elevate4.zip

**Comment by MagpieFourtyTwo** [comment] 2019-04-18 09:55
Ui - did not even have a clue that c:geo has become compatible with Elevate v4 yet.  Tried it a few months ago, but did not work.

Ok - after installing v4 POI symbols are fine again (although I liked v2 better ;) ) - thx a lot for the hint!

Nevertheless, on https://www.openandromaps.org/kartenlegende/elevation-hike-theme c:geo is still listed for "legacy version v2" - this may lead to some confusion for c:geo users, esp. as they will still need v2, too, if "[X] Old Mapsforge V3" is set.  So, apart from adding this dependency to the release notes, we probably should drop ChristianK from OpenAndroMaps a note that c:geo's next release will per default need Elevate v4?

**Comment by rsudev** [comment] 2019-04-18 13:32
The new map is the default since 2018.06.26, seven releases ago (if I count in the one from two days ago)...
Would have been a good idea to notify him, will do.

**Comment by rsudev** [comment] 2019-04-18 17:29
(Done)

**Comment by rsudev** [comment] 2019-04-19 19:19
I guess we can now close this topic, right?

**Closed by rsudev** 2019-04-19 19:19 UTC
Labels: Bug, New Map OSM
