### ISSUE TITLE
Search bar should close on selection

### ISSUE THREAD

**Issue by Bananeweizen** [cgeo/cgeo#4725] opened 2015-03-08 15:48 UTC
When selecting a cache from the search bar of the main activity, the the search field should be deactivated and the keyboard should go away. Otherwise users may be very confused when returning from the cache and finding the keyboard opening suddenly.

**Comment by MrYaz** [comment] 2015-04-03 20:18
I Agree!
The History Icon is also hidden when the search field is active.
Since I use the History list alot I find it annoying that I either has to use overflow->History or restart the app completely to show the Icon again.

**Comment by rsudev** [comment] 2015-04-03 21:37
@MrYaz: Does pressing back not close the search bar for you? Nevertheless this should be fixed, just wondering.

**Comment by MrYaz** [comment] 2015-04-03 21:40
No it doesn't. That is the expected behavior and I have accidentally exited the app while trying to close the search bar.

**Closed** 2015-04-05 14:18 UTC
Labels: Bug

**Comment by MrYaz** [comment] 2015-04-05 23:24
It works as expected now when selecting a cache in the search list. 
But when closing the search field by pressing back only the search and the overflow icons  remains in the navigation bar. 
And you should only have to press back once, not twice, to close the search field.
