### ISSUE TITLE
Displaying pictures for which the URL is given in the "notes" field

### ISSUE THREAD

**Issue by dounyy** [cgeo/cgeo#5621] opened 2016-04-02 18:33 UTC
_This is a feature request._

**Feature requested**
When a URL is given in the "notes" field, if the URL targets a picture, cgeo displays it in the pictures tab.

**Motive**
I think this feature would help a lot in case of a Mystery for which the spoiler is given in the Geocheck. Thus, the user would only have to copy/paste the URL of the picture in the "notes" field to have it displayed in cgeo.

**Comment by Bananeweizen** [comment] 2016-04-02 18:47
What is the criteria for "targets a picture"? Any URL can potentially return an image. And having an URL like http://example.com/somescript.php?image.png (that looks similar like an image file name) might return something completely different than an image.

**Comment by kumy** [comment] 2016-04-02 19:15
Maybe a HEAD request to obtain the mime type...

On April 2, 2016 8:47:42 PM GMT+02:00, Michael Keppler <notifications@github.com> wrote:
>What is the criteria for "targets a picture"? Any URL can potentially
>return an image. And having an URL like
>http://example.com/somescript.php?image.png (that looks similar like an
>image file name) might return something completely different than an
>image.
>
>---
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/cgeo/cgeo/issues/5621#issuecomment-204773629

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by Dounyy** [comment] 2016-04-02 20:24
The main purpose would be handling the spoilers hosted on geocheck, so basically the parsing would be finding a string like http://geocheck.org/md5pics/[0-9a-f].jpg

**Comment by Bananeweizen** [comment] 2016-04-03 14:40
I now understand what your need is. But to me that still sounds very specific, and reminds me of the more general discussion of attaching notes, images, text and other objects to caches. For that we decided to not have any specific functionality in cgeo and to leave that to apps like evernote.

I tend to close this as a duplicate of #817, #4880 or #4486.

**Comment by Dounyy** [comment] 2016-04-03 14:58
I have originally formulated my request because of this exact reason. I assumed that a such feature would help, and not only for geocheck spoilers. But anyway, if you consider it as too specific, it probably is.

**Comment by Lineflyer** [comment] 2016-04-03 19:54
If a hyperlink is contained in the note we do linkify it (make it clickable), do we?
In this case I also tend to close this with reference to general ability to attach data to a cache listing.

**Comment by speedy-1702** [comment] 2018-05-01 11:04
Great idea, I would like to have such a feature in c:geo.

**Closed** 2022-03-06 10:51 UTC
Labels: Feature Request, Feedback required
