### ISSUE TITLE
Hint function in compass not working

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#6091] opened 2016-11-06 10:53 UTC
##### Detailed steps causing the problem:
- Open cache details of a cache having a hint(spoiler) text (reported example: GC3QWMQ)
- Start the compass
- Select the "show hint" button in compass

##### Actual behavior after performing these steps:
 Hint text not shown, nothing happens

##### Expected behavior after performing these steps:
Hint should be shown as a toast

##### Version of c:geo used:
2016.10.23 / 2016.11.05

##### Is the problem reproducible for you?
No, but was reported by several users on support mail.
Will try to collect more examples of devices with this problem to get a clue.

##### System information:
This bug seems to depend on the device, e.g. a user reported:
Working on a Samsung Glaxy Tab 3 with Android 4.4.2:
```
--- System information ---
Device: GT-P5210 (santos10wifixx, samsung)
Android version: 4.4.2
Android build: KOT49H.P5210XXUBOH1
Cgeo version: 2016.10.23
Google Play services: enabled
Low power mode: inactive
Compass capabilities: yes
Rotation vector sensor: absent
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: magnetometer & accelerometer
Hide own/found: false
Map strategy: auto
HW acceleration: disabled (default state)
System language: nl_BE
Log date format: 27-10-2016
Debug mode active: no
Geocaching sites enabled:
   geocaching.com: Logged in (Ingelogd) / BASIC
Installed cgeo plugins:  none
--- End of system information --- 
```` 

Not working on a Samsung Grand Neo (currently waiting for the system information of that device).

##### Other comments and remarks:
Not reproducible for me on any of my devices

**Comment by Bananeweizen** [comment] 2016-11-06 10:58
Please ask one of the reporters whether the hint is visible at all in the cache details. A parsing error (and the hint missing completely) seems more reasonable than the displaying of toasts not working anymore.

**Comment by Lineflyer** [comment] 2016-11-06 11:06
Good idea. Will do.

**Comment by samueltardieu** [comment] 2016-11-10 09:05
I can't reproduce it either, both as a premium and as a basic member.

**Comment by Lineflyer** [comment] 2016-11-12 12:08
Feedback from user:
Hint is visible in cache details but still not shown when selecting that function in compass. So it is no parsing problem....

**Comment by Lineflyer** [comment] 2016-11-28 21:51
One of the two users affected wrote again (translated):

The problem was bound to my mobile phone SM-G900F. Now I changed to a new mobile phone and the problem is no longer existing. No idea about the reason.

---

I suggest to close this if no more clues come in.

**Comment by Lineflyer** [comment] 2017-05-10 15:49
Reopen as we have another case of this.
For the user the hint is neither shown on the "map of a cache" (Menu -> Show hint) nor in compass of this cache (Action bar -> Show hint).
It happens nothing (no toast displayed at all, no error message or crash).

Sys info:
```
--- System information ---
Device: SM-G925F (zeroltexx, samsung)
Android version: 7.0
Android build: NRD90M.G925FXXU5EQDF
c:geo version: 2017.05.09
Google Play services: disabled - 10.2.98 (440-146496160)
Low power mode: inactive
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: orientation
Hide own/found: false
Map strategy: detailed
HW acceleration: enabled (default state)
System language: de_DE
System date format: dd.MM.yy
Debug mode active: no
System internal c:geo dir: /data/user/0/cgeo.geocaching (16,4 GB free) internal
User storage c:geo dir: /storage/emulated/0/cgeo (16,4 GB free) external non-removable
Geocache data: /storage/emulated/0/Android/data/cgeo.geocaching/files/GeocacheData (16,4 GB free) external non-removable
Database: /storage/emulated/0/Android/data/cgeo.geocaching/files/databases/data (3,3 MB) on user storage
Fine location permission: granted
Write external storage permission: granted
Geocaching sites enabled:
   geocaching.com: Logged in (Anmeldung OK) / BASIC
Geocaching.com date format: dd.MM.yyyy
Installed c:geo plugins:  none
--- End of system information ---
```

Any idea?

**Comment by Lineflyer** [comment] 2018-01-15 09:44
Another user with this problem on support mail:

```
--- System information ---
Device: SM-G920F (zerofltexx, samsung)
Android version: 7.0
Android build: NRD90M.G920FXXS5EQL6
c:geo version: 2017.12.17
Google Play services: enabled - 11.9.51 (440-177350961)
Low power mode: inactive
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: orientation
Hide own/found: false
Map strategy: auto
HW acceleration: enabled (default state)
System language: nl_NL
System date format: dd-MM-yy
Debug mode active: no
System internal c:geo dir: /data/user/0/cgeo.geocaching (13,1 GB free) internal
User storage c:geo dir: /storage/emulated/0/cgeo (13,0 GB free) external non-removable
Geocache data: /storage/emulated/0/Android/data/cgeo.geocaching/files/GeocacheData (13,0 GB free) external non-removable
Database: /storage/emulated/0/Android/data/cgeo.geocaching/files/databases/data (9,0 MB) on user storage
Fine location permission: granted
Write external storage permission: granted
Geocaching sites enabled:
   geocaching.com: Logged in (Ingelogd) / PREMIUM
Geocaching.com date format: dd/MM/yyyy
Installed c:geo plugins:  none
--- End of system information ---
```

**Comment by goeranu** [comment] 2019-07-09 17:06
For your information:

My daughter and I both use c:geo, and she recently showed me how to get the hint while in compass view.  I tried it on my phone, and didn't get anything.  Now, we both had the same version of c:geo (2019.06.06) and have the same model of phone (Samsung A3), so we looked for some other difference.

It turned out that in the application settings she allowed notifications from c:geo while I had it disabled.  When I changed that setting and allowed it on my phone, I too could also see the hints in the compass view.

I guess this makes sense from some perspective, but to me it is rather counterintuitive.  I would have thought that setting controlled what could show up in the top bar on the initial page, and possibly some similar situations.  But what happens when I press a button in the app, I would expect to behave the same regardless of this setting.

Now I know better, but I thought I'd mention it since others than me might be fooled.

**Comment by Lineflyer** [comment] 2019-07-09 19:42
That makes indeed sense, as the toast we show can be interpreted as notifications. But if you switch them off you might also miss some other important infos (such as upload confirmation of modified coordinates, cacache opening failures, etc.).

Question to the programmers: Are "toasts" maybe the wrong method of showing such infos acc. to android guidelines?

**Comment by Lineflyer** [comment] 2020-10-19 20:31
The hint problem should be solved by some of the recent changes explicitly for this problem (do not remember the commit / issue ID right now).

**Comment by jallwork** [comment] 2021-04-19 17:26
I have this problem and have had so for a long time, certainly over a year. I think it happened after a CGEO update. I don't recall changing devices when I noticed it. (I've had my current smartphone for about 2.5 years)
I have c:geo version 2021.04.15
My phone is  Galaxy-J3
Model number SM-J330FN
Android version 9

I'll report the bug from the phone too.

**Comment by Lineflyer** [comment] 2021-04-20 09:56
@jallwork 
Does it happen for you for stored caches or for caches you just started navigation from the live map.
In the second case, the hint will not be available as c:geo does not get the hint information from the data is loaded via live map.

**Comment by Lineflyer** [comment] 2021-04-20 09:57
Support ticket: Ticket #473950

**Comment by jallwork** [comment] 2021-04-20 10:50
This is what I've tried
I have a saved (unfound ) cache GC99B6V in stored caches
If I open the cache in CGEO, click the compass and then the hint icon,
nothing happens.
If I go to the live map, click the GC99B6V icon > More details> compass >
hint . Nothing happens.
If I  go back to the live map, click a nearby found cache icon (say
GC8E4DH) > More details> compass > hint . Nothing happens.
BUT I might at some point have stored that in cgeo,
SO trying a cache that I would not have saved,
Go back to the live map, pick a random unfound cache icon (say GCX77D) >
More details> compass > hint . Nothing happens.

Not sure why you say "c:geo does not get the hint information from the data
is loaded via live map."
as If I open a cache from the live map, I'm able to go to the listing page
and click the Hint to see it (just not from the compass page)

All of this hasn't bothered me, because I can always go back to the cache
listing page and look at the hint there.

I'm happy to help with any debugging for you

Regards
John

**Comment by Lineflyer** [comment] 2021-04-20 10:59
> Not sure why you say "c:geo does not get the hint information from the data
is loaded via live map."
as If I open a cache from the live map, I'm able to go to the listing page
and click the Hint to see it (just not from the compass page)

Sure, but if you only see the cache on the map and start the compass directly from the live map popup (without loading/opening the cache before) then the hint cannot be there. Thats whay I asked.

But in your scenarios it should work.

Another question:
If you tap on a cache and use the lightbulb icon in the popup, does the hint show up then.

**Comment by jallwork** [comment] 2021-04-20 15:58
That works fine.
If I select a cache that I've saved it shows the light bulb icon next to
'More details' and touching that brings up the hint.

The light bulb icon doesn't appear with caches that I've not saved, I
presume that's how it's supposed to work

John

**Comment by eddiemuc** [comment] 2023-11-19 20:38
Teammeeting 19.11.23: could not be reproduced. Also c:geo has changed a lot since issue was filed. We are closing for now, please feel free to reopen if issue still exists.

**Closed by eddiemuc** 2023-11-19 20:38 UTC
Labels: Bug, Unverified
