### ISSUE TITLE
Idea: list of inventory/owned trackables

### ISSUE THREAD

**Issue by Hadena** [cgeo/cgeo#7564] opened 2019-04-28 08:09 UTC
Hi,
Maybe it is an idea if there is a feature added where we can directly see which trackables are in possession. Now I first need to pretend logging a cache before I see the list.
Just an idea.
Best wishes an thanks for the app!

**Comment by Lineflyer** [comment] 2019-04-28 09:20
Thanks for your idea, however a duplicate of #420

**Closed by Lineflyer** 2019-04-28 09:20 UTC
