### ISSUE TITLE
Fieldnotes for yesterday get wrong date/time

### ISSUE THREAD

**Issue by MagpieFourtyTwo** [cgeo/cgeo#11726] opened 2021-09-25 17:59 UTC
### Describe your problem!

Wrote a forgotten offline log today, saved it offline with yesterday's date and uploaded it as fieldnote to gc.com, where it then was displayed with the date of the day *before* yesterday.

Checked the fieldnotes.txt file, and there is indeed a false timestamp:
- saved the offline log at about 3 pm CEST on 25.09.21
- date in the fieldnotes.txt: 2021-09-23T23:00:00Z
- fieldnote shows up on gc.com with "23 September 2021"

BTW: An offline log of the current day has been saved as follows:
- saved the offline log some minutes after 3 pm CEST on 25.09.21
- date in fieldnotes.txt: 2021-09-25T13:03:48Z
- fieldnote shows up on gc.com with "25 September 2021"
... thus I assume, the time will be saved as GMT ...?

### How to reproduce?

.

### Actual result after these steps?

.

### Expected result after these steps?

Date and time of offline logs saved with a different date than today should get at least the correct date.
While I would assume to additionally just use the current time when the offline log has been saved ...

### Reproducible

Yes

### c:geo Version

2021.09.23-NB-fabed08

### System information

```text
Device:
-------
- Device type: VOG-L29 (VOG-L29EEA, HUAWEI)
- Available processors: 8
- Android version: 10
- Android build: VOG-L29 10.1.0.150(C431E19R2P5)
- Screen resolution: 1080x2147px (423x841dp)
- Sailfish OS detected: false
- Google Play services: disabled - 21.33.14 (120400-395723304)
- HW acceleration: enabled (default state)

Sensor and location:
-------
- Low power mode: inactive
- Compass capabilities: yes
- Rotation vector sensor: present
- Orientation sensor: present
- Magnetometer & Accelerometer sensor: present
- Direction sensor used: rotation vector

Program settings:
-------
- Settings: v8, Count:272
- Set language: en_DE (system default)
- System date format: dd/MM/y
- Time zone: GMT+02:00
- Debug mode active: no
- Last backup: 23 Sep, 01:18
- Routing mode: Car
- Live map mode: true
- OSM multi-threading: true / threads: 4
- Map: _  DE BaWü Vosges (Offline)
  - Id: cgeo.geocaching.maps.mapsforge.MapsforgeMapProvider$OfflineMapSource:0123-4567:Locus/mapsVector/_  DE BaWü Vosges.map
  - Atts: Maps: (c)Christian Kernbeis, Themes: (c)Tobias Kuehn, www.openandromaps.org 2012-2021
  - Theme: Elevate F140 L120 S110 EB.xml

Filters:
-------
- Hide waypoints: -
- LIVE: - Live (Hide Found, Offline logged & Archived) ([- Live \(Hide Found, Offline logged & Archived\):inconclusive=false:advanced=false]AND(status:found_no:has_offline_log_no:has_offline_found_log_no:exclude_archived))
- OFFLINE: None ([:inconclusive=false:advanced=true])

Services:
-------
- Geocaching sites enabled:
   geocaching.com: Logged in (Login OK) / PREMIUM
   extremcaching.com: Logged in (Login OK)
- Geocaching.com date format: dd MMM yy
- Routing: external / BRouter installed: true
- Installed c:geo plugins: contacts

Permissions & paths:
-------
- Fine location permission: granted
- Write external storage permission: granted
- System internal c:geo dir: /data/user/0/cgeo.geocaching (49,1 GB free) v2 internal isDir(7 entries)
- Legacy User storage c:geo dir: /storage/emulated/0/cgeo (49,1 GB free) v2 external non-removable isDir(4 entries)
- Geocache data: /storage/emulated/0/Android/data/cgeo.geocaching/files/GeocacheData (49,1 GB free) v2 external non-removable isDir(1439 entries)
- Internal theme sync (is turned ON): /data/user/0/cgeo.geocaching/MapThemeData (49,1 GB free) v2 internal isDir(8 entries)
- Public Folders: #11
  - BASE: /cgeo (User-Defined)[/cgeo[DOCUMENT#0:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo, Av:true, files:>=10, dirs:>=11, totalFileSize:>=1,3 GB, free space: 49,1 GB, files on device: 13278715)
  - OFFLINE_MAPS: ‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‎SD card‌‌‌‌‌‎/Locus/mapsVector (User-Defined)[‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‎SD card‌‌‌‌‌‎/Locus/mapsVector[DOCUMENT#0:p-content://com.android.externalstorage.documents/tree/0123-4567%3ALocus%2FmapsVector::]] (Uri: content://com.android.externalstorage.documents/tree/0123-4567%3ALocus%2FmapsVector/document/0123-4567%3ALocus%2FmapsVector, Av:true, files:449, dirs:4, totalFileSize:20,7 GB, free space: 151,7 GB, files on device: 0)
  - OFFLINE_MAP_THEMES: ‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‎SD card‌‌‌‌‌‎/Locus/mapsVector/_themes/Elevate4 (User-Defined)[‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‎SD card‌‌‌‌‌‎/Locus/mapsVector/_themes/Elevate4[DOCUMENT#0:p-content://com.android.externalstorage.documents/tree/0123-4567%3ALocus%2FmapsVector%2F_themes%2FElevate4::]] (Uri: content://com.android.externalstorage.documents/tree/0123-4567%3ALocus%2FmapsVector%2F_themes%2FElevate4/document/0123-4567%3ALocus%2FmapsVector%2F_themes%2FElevate4, Av:true, files:418, dirs:1, totalFileSize:3,4 MB, free space: 151,7 GB, files on device: 0)
- LOGFILES: /cgeo/logfiles (Default)[/cgeo/logfiles[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/logfiles]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Flogfiles, Av:true, files:1, dirs:0, totalFileSize:119 B, free space: 49,1 GB, files on device: 13278715)
  - GPX: /Download/GPX (User-Defined)[/Download/GPX[DOCUMENT#0:p-content://com.android.externalstorage.documents/tree/primary%3ADownload%2FGPX::]] (Uri: content://com.android.externalstorage.documents/tree/primary%3ADownload%2FGPX/document/primary%3ADownload%2FGPX, Av:true, files:10, dirs:0, totalFileSize:161,6 KB, free space: 49,1 GB, files on device: 13278715)
  - BACKUP: /cgeo/backup (Default)[/cgeo/backup[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/backup]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Fbackup, Av:true, files:>=14, dirs:>=7, totalFileSize:>=2,2 GB, free space: 49,1 GB, files on device: 13278715)
  - FIELD_NOTES: /cgeo/field-notes (Default)[/cgeo/field-notes[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/field-notes]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Ffield-notes, Av:true, files:44, dirs:0, totalFileSize:151,9 KB, free space: 49,1 GB, files on device: 13278715)
  - SPOILER_IMAGES: /cgeo/GeocachePhotos (Default)[/cgeo/GeocachePhotos[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/GeocachePhotos]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2FGeocachePhotos, Av:true, files:0, dirs:0, totalFileSize:0 B, free space: 49,1 GB, files on device: 13278715)
  - ROUTING_BASE: /cgeo/routing (Default)[/cgeo/routing[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/routing]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Frouting, Av:true, files:15, dirs:1, totalFileSize:582,3 MB, free space: 49,1 GB, files on device: 13278715)
  - ROUTING_TILES: /cgeo/routing/segments4 (Default)[/cgeo/routing/segments4[PERSISTABLE_FOLDER(ROUTING_BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/routing/segments4]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Frouting%2Fsegments4, Av:true, files:5, dirs:0, totalFileSize:582,2 MB, free space: 49,1 GB, files on device: 13278715)
  - TEST_FOLDER: [Legacy]/data/user/0/cgeo.geocaching/files/unittest (Default)[/data/user/0/cgeo.geocaching/files/unittest[FILE#1:p-file:///data/user/0/cgeo.geocaching/files::/unittest]] (Uri: file:///data/user/0/cgeo.geocaching/files/unittest, Av:true, files:0, dirs:0, totalFileSize:0 B, free space: 49,1 GB, files on device: -1)
- Map render theme path: Elevate F140 L120 S110 EB.xml
- PersistedDocumentUris: #1
- TRACK: null
- Persisted Uri Permissions: #4
  - content://com.android.externalstorage.documents/tree/primary%3ADownload%2FGPX (24 May, 00:17):RW
  - content://com.android.externalstorage.documents/tree/0123-4567%3ALocus%2FmapsVector%2F_themes%2FElevate4 (20 May, 23:38):RW
  - content://com.android.externalstorage.documents/tree/primary%3Acgeo (20 May, 23:37):RW
  - content://com.android.externalstorage.documents/tree/0123-4567%3ALocus%2FmapsVector (20 May, 23:37):RW
- Database: /data/user/0/cgeo.geocaching/databases/data (v97, Size:434,5 MB) on system internal storage

--- End of system information ---
```

**Comment by MagpieFourtyTwo** [comment] 2021-09-25 18:04
Ah, short curious addition: The log itself, when finally written on gc.com, will get the right date again (i. e. 24.09,, with the above example) ...

**Comment by Lineflyer** [comment] 2021-09-25 18:06
Duplicate of #11607 ?
And for sure related to #11528

**Comment by MagpieFourtyTwo** [comment] 2021-09-25 18:40
> Duplicate of #11607 ?

Not really. #11607 deals with offline logs of the current day - but over here this date is perfectly fine.

> And for sure related to #11528 

Quite possible.

**Comment by MagpieFourtyTwo** [comment] 2021-09-25 18:42
I, BTW, in both cases used the "Log Visit" menu entry from within the cache listing.

**Closed** 2021-10-03 17:00 UTC
Labels: Bug, Unverified
