### ISSUE TITLE
Blank 'Long description' does not overwrite existing text

### ISSUE THREAD

**Issue by alan666notb** [cgeo/cgeo#6722] opened 2017-09-03 10:19 UTC
##### Detailed steps causing the problem:
- Either create a temporary cache page, or use one you own.
- Fill in both the summary fields and the 'Long description' fields.
- Load the cache into c:geo, check both fields can be seen
- On the website, clear the text from the 'Long description' so that it is blank, save the cache
- Refresh the cache in c:geo

##### Actual behavior after performing these steps:
The text in the 'Long description' field is not erased from display in c:geo, 
there's no way to get rid of it.

##### Expected behavior after performing these steps:
The 'Long description' text should be deleted to reflect the cache page shown on the website.

##### Version of c:geo used:
2017:08:23

##### Is the problem reproducible for you?
Yes

##### Other comments and remarks:
This was discovered as a result of issue #6720

**Comment by pstorch** [comment] 2017-09-03 10:42
Nice catch. I guess this could affect other fields, too. When we merge the cache data, we use values frome the old version (the one from the database).
See: https://github.com/cgeo/cgeo/blob/master/main/src/cgeo/geocaching/models/Geocache.java#L302

**Comment by pstorch** [comment] 2017-09-03 10:47
The problem is, sometimes we have to do it. When we load cache data from the map or the search result, the data is incomplete. So we merge it with the data we already have from a previous load.

**Comment by rsudev** [comment] 2017-09-03 15:41
The overall goal of the implementation is, to be able to detect if the information is missing or empty. For some fields we already have that, perhaps with the long description we currently cannot.
This is from memory, not from inspecting the sources right now...

**Comment by fm-sys** [comment] 2021-08-29 22:33
> The overall goal of the implementation is, to be able to detect if the information is missing or empty.

Imagine there's a website change and the description cannot be parsed anymore. What would you like to see after a refresh? The old description or nothing? I think the current behavior is intended and would suggest to close this issue...

**Comment by fm-sys** [comment] 2021-09-01 08:52
As no further feedback occurred, let's close as intended behavior / "won't fix"

**Closed by fm-sys** 2021-09-01 08:52 UTC
Labels: Bug
