### ISSUE TITLE
GPX export by listname

### ISSUE THREAD

**Issue by jelleruben** [cgeo/cgeo#13442] opened 2022-09-25 14:49 UTC
### Tell us your idea!

I have lots of lists in c:geo, for my Garmin GPS, I must export the  lists. So I can them import in an other app for my Garmin device. 

### What solution would you suggest?

It would be nice, if I export a list. That the file name get the name of the list and not the long export name (export-2022-09-25-16-44-05-7.gpx).

**Comment by moving-bits** [comment] 2022-09-25 18:02
Duplicate of #2724

**Closed by moving-bits** 2022-09-25 18:02 UTC
Labels: Feature Request, Duplicate
