### ISSUE TITLE
Cache logging problem, wrong date

### ISSUE THREAD

**Issue by lupendotcz** [cgeo/cgeo#6398] opened 2017-03-13 13:43 UTC
##### Detailed steps causing the problem:
-11.3. I was prepared a cache log wit date 11.3.
- today 13.3. I sent log to geocaching.com
- ...

##### Actual behavior after performing these steps:
the cache id logget with date 13.3. not 11.3.
all TB are loget with date 13.3
this happens after maintenance window of geocaching.com about 11-12 CET
before maintenance it working fine

After reload cache c:geo read no logs!

##### Expected behavior after performing these steps:
cache will be logged with date set in c:geo, not with actual date

##### Version of c:geo used:
last, 2017.02.07

##### Is the problem reproducible for you?
Yes

##### System information:
```
Attach system information here if available (see c:geo menu -> About c:geo -> Swipe right to System)
Keep the apostrophe at beginning and end to have it properly formatted
```

##### Other comments and remarks:
e.g. Reference to other issues, projects, sources, etc.

**Comment by UniQP** [comment] 2017-03-13 13:53
@lupendotcz Can you please add your system information (as described in the issue template)?

**Comment by lupendotcz** [comment] 2017-03-13 13:57
Device: SM-G900F (kltexx, samsung)
Android version: 6.0.1
Android build: MMB29M.G900FXXS1CQBW
Cgeo version: 2017.02.07
Google Play services: enabled - 10.2.98 (438-146496160)
Low power mode: inactive
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: rotation vector
Hide own/found: true
Map strategy: auto
HW acceleration: enabled (default state)
System language: cs_CZ
System date format: dd.MM.yy
Debug mode active: no
Fine location permission: granted
Write external storage permission: granted
Geocaching sites enabled:
   geocaching.com: Logged in (Přihlášení bylo úspěšné) / PREMIUM
Geocaching.com date format: MM/dd/yyyy
Installed cgeo plugins:  none

**Comment by lupendotcz** [comment] 2017-03-13 14:07
--- System information ---
Device: SM-G900F (kltexx, samsung)
Android version: 6.0.1
Android build: MMB29M.G900FXXS1CQBW
Cgeo version: 2017.02.07
Google Play services: enabled - 10.2.98 (438-146496160)
Low power mode: inactive
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: rotation vector
Hide own/found: true
Map strategy: auto
HW acceleration: enabled (default state)
System language: cs_CZ
System date format: dd.MM.yy
Debug mode active: no
Fine location permission: granted
Write external storage permission: granted
Geocaching sites enabled:
   geocaching.com: Logged in (Přihlášení bylo úspěšné) / PREMIUM
Geocaching.com date format: MM/dd/yyyy
Installed cgeo plugins:  none
--- End of system information ---

**Comment by Lineflyer** [comment] 2017-03-13 14:24
Thanks for your report.
Can you please open this geocache logbook on your PC browser

https://www.geocaching.com/seek/cache_logbook.aspx?guid=ba954eb7-29c5-4b4a-a6d8-8546b05b5bae

and tell us how the date is formatted on top right of the log entries (e.g. the newest log entry as of today should have day=9 month=03 year=2017)

Please post exactly as it is shown to you on that website.

**Comment by lupendotcz** [comment] 2017-03-13 14:35
9.3.2017

**Comment by Lineflyer** [comment] 2017-03-13 14:55
Thanks.

According to the system information we detect `Geocaching.com date format: MM/dd/yyyy` which should result in 09/03/2017 but not 9.3.2017

Couls someone from the team provide the URL to @lupendotcz which we use to read out the date format. I think it may be wise to get a dump of this HTML in its current condition.

@lupendotcz Please kindly don't modify any setting on the website yet.

**Comment by lupendotcz** [comment] 2017-03-13 15:06
Hi, 
I am litle confused. There is not problem with date format, there is problem with calendar date. Im my c:geo I set date of Found it log as "11.03.17" After sending to geocaching.com, displayed date is 13.3.1017, not 11.3.2017. Geocaching.com store actual date, not date as setting in c:geo.

**Comment by Lineflyer** [comment] 2017-03-13 15:28
The root cause of your problem is a mismatch in date format used in c:geo with the date format we assume geocaching.com is awaiting according to your account settings.
Due to the mismatch you don't see logs after refresh and it also make a wrong date when posting finds. 

Please open https://www.geocaching.com/account/settings/preferences on your browser and without editing any of the settings just save the HTML page with your browser (File - Save as - only HTML).
Could you please share this HTML via mail to support[at]cgeo.org ?

**Comment by lupendotcz** [comment] 2017-03-13 15:37
Mail was sent.
I don't change this settings and setting of c:geo a long time.
It working fine yesterday and today morning.

**Comment by Lineflyer** [comment] 2017-03-13 15:48
Thanks, but you only send a screenshot. We would kindly need the saved HTML page (File - Save as -)

**Comment by lupendotcz** [comment] 2017-03-13 16:00
Page was sent

**Comment by Lineflyer** [comment] 2017-03-13 16:07
Thanks.

The page looks alright according to what you see in the browser:
```<option selected="selected" value="d.M.yyyy">13.3.2017</option>```

So the question is, why c:geo thinks you use `MM/dd/yyyy` but in reality it is `d.M.yyyy`

Can you just restart your phone, start c:geo, wait for login OK and then again post the system information. Lets find out if this mismatch is persistent or only caused by server problems (or similar).

**Comment by lupendotcz** [comment] 2017-03-13 16:15
System info after phone restart
Date format changed

--- System information ---
Device: SM-G900F (kltexx, samsung)
Android version: 6.0.1
Android build: MMB29M.G900FXXS1CQBW
Cgeo version: 2017.02.07
Google Play services: enabled - 10.2.98 (438-146496160)
Low power mode: inactive
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: rotation vector
Hide own/found: true
Map strategy: auto
HW acceleration: enabled (default state)
System language: cs_CZ
System date format: dd.MM.yy
Debug mode active: no
Fine location permission: granted
Write external storage permission: granted
Geocaching sites enabled:
   geocaching.com: Logged in (Přihlášení bylo úspěšné) / PREMIUM
Geocaching.com date format: d.M.yyyy
Installed cgeo plugins:  none
--- End of system information ---

**Comment by lupendotcz** [comment] 2017-03-13 16:21
Loging working fine again after restart. Thank you.

**Comment by Lineflyer** [comment] 2017-03-13 16:26
You're welcome....we only need to find out why this keeps happening for some users sometimes.

BTW: To what date format do we default if we fail detecting it?

**Comment by lupendotcz** [comment] 2017-03-13 16:38
It happens after it I was not able to login to geocaching.com. After approx. one hour login working fine and there was problem with date format
Usual date format in Czech Republic is d.m.yyyy. No leading zeros..

**Comment by pstorch** [comment] 2017-03-13 17:43
I think it is similar to the empty logbook problem we get reported sometimes. Looks like in some cases the detection of the user dateformat fails.

**Comment by Lineflyer** [comment] 2017-03-14 14:52
@pstorch Yes, I assume that as well. That why I asked the user for the mentioned details. Therefore also my question about the default format we use if detection fails? Might this be `MM/dd/yyyy`?

**Comment by pstorch** [comment] 2017-03-14 21:04
@Lineflyer yes, it is `MM/dd/yyyy`, see https://github.com/cgeo/cgeo/blob/80f030051665ffc44cd29a0702b887d68e06c3cf/main/src/cgeo/geocaching/connector/gc/GCConstants.java#L34

**Comment by Lineflyer** [comment] 2017-03-22 11:58
Still no clear evidence about when and how it can happen, that we are unable to parse the date and fallback to default. Closing for now.

**Closed by Lineflyer** 2017-03-22 11:58 UTC
Labels: Bug, Unverified
