### ISSUE TITLE
c:geo does insufficient cleanup

### ISSUE THREAD

**Issue by andrixnet** [cgeo/cgeo#4357] opened 2014-09-15 09:02 UTC
I have a list of 324 caches. Some of them also have supplemental data stored in folders under .cgeo.
Assume I do a "remove all". 
Now c:geo no longer has them stored. 

Problem 1: I am offline yet I still see all the caches I just removed on the map. Caching some of the data is ok, but I really want to get rid of them. See them gone. 
What do I have to do, other then manually deleting all files under .cgeo?

Problem 2: all per cache folders under .cgeo are still there. They occupy storage space. I don't want them anymore. I removed the caches from storage, I want all their data gone. 
After managing several imports and them removed them, I was left with 3000 folders and several GB of space blocked this way. 

Problem 3: while online I consulted several caches in the area (via the map). Stored several of interest, left the rest. Now I go offline. I still see all caches that c:geo showed while online on the map. 
While caching them for some people may be of interest, I am only interested in the ones I stored, the rest are now cluttering the map. 
I cannot get rid of them unless I manually delete all files under .cgeo.

The hard to access deep in the settings "delete orphaned files" command does not help with either of these problems.

**Comment by pstorch** [comment] 2018-01-26 21:49
I would like to reopen the discussion here.

I'm in favor of @rsudev 's comment in https://github.com/cgeo/cgeo/issues/5773#issuecomment-360854217 and support the idea to switch to 'delete right away'.

Some pros and cons I can think of at the moment:

Pros:
- a real delete is what most (as I think) users would expect, it is the behavior of least surprise (other apps do it this way, too)
- I guess the 3 day delay was implemented at a time when mobile data plans where rather expensive and limited
- accidental deletes are mitigated by the undo function anyway
- the 3 day delay causes the device not to free up space
- the 3 day delay causes some unintended behaviors like #5773
- a delete + fresh download is not possible at the same date (the refresh with merge has its own issues, like #6853 or #6722)

Cons:
- Some users are used to this safetynet and might rely on it
- the undo timeframe might be a bit short
- still some users have a limited mobile data plan or are in areas with bad to no reception


Anything else? Please add your thoughts.

**Comment by pstorch** [comment] 2018-01-26 22:27
Thinking about it a few more minutes: An undo of big lists might not be possible anymore. At the moment we just remove the relationship to the lists. The list IDs fit easily into memory and can be reinserted on undo. But with 'delete right away', we would  have to keep the whole caches in memory as long as the undo is possible.

**Comment by SammysHP** [comment] 2018-01-27 08:00
Another scenario: Imported caches from a GPX file, that is not available on the device anymore.

Undo should be possible even if several caches are deleted at once or one by one.

**Comment by pstorch** [comment] 2018-01-27 09:08
> Another scenario: Imported caches from a GPX file, that is not available on the device anymore.

Then the user has deleted the caches a second time. I don't know if we should consider all mistakes.


The undo function needs some rework for sure. I'm also thinking about a DB snapshot (a backup) before a bigger delete. So the user has a chance to restore.

**Comment by SammysHP** [comment] 2018-01-27 11:16
Yes, reliable undo would be enough in most situations. I just wanted to demonstrate that an accidentally deleted cache cannot be recovered without undo in some situations.

**Comment by pstorch** [comment] 2018-01-29 12:30
That sounds like a plan:
1) implement reliable undo
2) change to 'delete right away'

**Comment by andrixnet** [comment] 2018-01-30 10:39
This should somehow include clearing History as well.
Consider the scenario where you show the map with live=enabled. Store some caches. Either/or have more caches stored. (existing, GPX import, etc). 
Next you want to disable live and clear the map of all but the stored caches.

**Comment by pstorch** [comment] 2018-01-30 20:53
@andrixnet 
> This should somehow include clearing History as well.

Yes, the History also loads the caches from the database. When 'delete right away' would be implemented, the history would be cleard as well.

Your other scenario is solved by simply restarting the map with live=disabled. I would remove the 'not yet saved caches' from the map when switching off the live mode.

**Comment by radams-mpusd** [comment] 2018-07-12 15:18
I found this through a search while ripping great wads of hair from my head because c:geo slipped into Live Map mode and pulled in massive clutter.

How has this progressed?

I use c:geo almost exclusively offline.  Manage my own PQs so I know what I'm looking for.  In very congested areas I only wish to see puzzles I've solved, not the 500 I haven't, saves money on those hair transplants, eh!

I very much enjoy using c:geo while caching in the relatively local area as well as when undertaking very long road trips.  PQs are loaded as stored caches so I see what was of interest to me while planning my trip.  New caches can be added with a "catch up" PQ which finds anything within accepted types published since xx/xx/xxxx, so all goes pretty smoothly.

Unfortunately there are times c:geo starts up in live map and utterly destroys all my hard work with the best of intentions, by bringing in everything.

**Comment by Lineflyer** [comment] 2018-07-16 21:24
@radams-mpusd 
Given your usage description you are probably referring to the three days buffering of saved data. There is no plan to change this behavior as it has high advantages for the "normal user".
However in your case it should be sufficient (as faar as I remember) to restart c:geo to clear the clutter loaded on the unintentional live map...isn't it?

**Comment by radams-mpusd** [comment] 2018-07-16 21:43
I'll suggest defining "normal user" as those who use it within its limitation is confining an otherwise fine product.

I uninstalled c:geo and reinstalled it which cleared the unwanted 3-day wait clutter.   As others have mentioned an ability to clear all caches right now would be very helpful.

**Comment by okainov** [comment] 2018-11-09 21:10
It was never ever mentioned in the app about "3 days something"! 

My typical use case:
- Go to new city
- Store all caches around my district
- Find out that there are some caches which are 20+ steps multi without English translation, spamming the map with its waypoints I'm not going to visit anyway
- So I go to this cache and click "delete". And I expect that it will be deleted. No more spamming waypoints on the map!
Currently it doesn't work like this and it's annoying :(

**Comment by Lineflyer** [comment] 2018-11-09 21:46
@okainov But you are looking on the live map in this case. It will show all information it has, and thats the purpose.

I still of course understand what you mean...but e.g. I would love to have it the other way around if gc.com.live map would support it: Show all waypoints of caches on the map even if not stored.

**Comment by okainov** [comment] 2018-11-09 21:56
Currently live map and c:geo knows only about waypoints of stored caches and I'm absolutely fine with this behavior. IMO spamming with all waypoints is not necessary especially taking into account usual amount of caches in EU cities.

**Comment by rsudev** [comment] 2018-11-09 22:03
I have been turning this over in my head also already quite a number of times, as it has very many faces. One solution which comes to mind could be, to not just return deleted caches to an unstored state, but introducing a deleted state which moves them to some kind of wastebasket, where you can restore them from, but they are no longer shown in other lists or on the map.

**Comment by SammysHP** [comment] 2018-11-10 07:39
I often have the following scenario: Sitting at a cafe or something similar. On the live map (or nearby search) open some nearby caches that I might want to visit, then start to go in that direction and open the next cache again. If I log it, it will be stored automatically.

**Comment by PEPEInvest** [comment] 2018-11-10 16:48
> It was never ever mentioned in the app about "3 days something"!
> 
> My typical use case:
> 
> * Go to new city
> * Store all caches around my district
> * Find out that there are some caches which are 20+ steps multi without English translation, spamming the map with its waypoints I'm not going to visit anyway
> * So I go to this cache and click "delete". And I expect that it will be deleted. No more spamming waypoints on the map!
>   Currently it doesn't work like this and it's annoying :(

@pep_peter

**Comment by PEPEInvest** [comment] 2018-11-10 16:49
![af0c7adf-2f2f-4141-9297-1ff6e70715a2](https://user-images.githubusercontent.com/35347421/48303905-f2c47980-e510-11e8-9b81-023a16b0dc66.jpeg)

**Comment by Lineflyer** [comment] 2018-11-10 17:44
Spam? deleted

**Comment by Lineflyer** [comment] 2021-12-12 11:38
The cleanup process via "Delete orphaned files" does now also empty the "72h cache", thus it can be used to avoid the different scenarios described in this issue. Therefore I guess/hope this can be considered as fixed by that.

**Closed by Lineflyer** 2021-12-12 11:38 UTC
Labels: Feedback required
