### ISSUE TITLE
Crash on startup after import of older backup

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#9307] opened 2020-10-29 08:08 UTC
- Use c:geo 2020.10.10
- It works normal
- Restore DB backup created with 2020.08.04

Result:
- Crash on startup (permanent)

Reported on support mail by some users.
One user agreed to send us the backup file causing this. Will ditribute it to cgeo-dev as soon as I recevied it.

**Comment by eddiemuc** [comment] 2020-10-29 08:37
As a first step, a log would be helpful (Extended). Maybe there are exceptions in it helping to clarify this

**Comment by fm-sys** [comment] 2020-10-29 08:47
Maybe it is already fixed with #9132 which is currently only at master...

**Comment by moving-bits** [comment] 2020-10-29 18:42
This can happen if the backup being imported is somewhat older, as we have incompatible sequences of updates.

eg: (pseudo code)
- original change was like `CREATE TABLE a field a`, (version x)
- later we have a change `ALTER TABLE a ADD field b` (version y)

With the second statement we also update the table declaration.

The problem arises when somebody tries to migrate coming from a version < x, as the create statement uses the updated table declaration, so that the second statement will fail, as field b already exists.

There are ways to prevent this, but we have implemented them only for the more recent updates.


To make a long story short: Please forward the user's backup file. I can look into it.

**Comment by Lineflyer** [comment] 2020-10-30 14:31
sent to @moving-bits 

As far as I understood its a backup from 2020.08.04 no longer importable in 2020.10.10

**Comment by moving-bits** [comment] 2020-10-30 20:45
Couldn't reproduce in the emulator, running current master. Returned the converted database.
Only exception in logcat is a `SQLiteException` on trying to rename the `cg_table_route` table to `cg_route` in version 83, which did not apply in this case, as `cg_route` was created (version 81) after the point the backup came from (version 76), thus already got the final name during migration. This is an exception to be expected and does not break the restore process.

**Comment by fm-sys** [comment] 2020-10-30 20:57
Does restoring also work with the release branch?  If it doesn't, we can close this issue and just need to start the new beta phase ;-)

**Comment by moving-bits** [comment] 2020-10-31 12:14
I'll retest with `release`

**Comment by moving-bits** [comment] 2020-10-31 16:24
@fm-sys 
You were right. Testing against `release` made the error reproducible, and, yes, on `master` this had been fixed already with #9132. I extracted the important line for this issue and created PR #9322 for it, targeted to `release`.

**Comment by fm-sys** [comment] 2020-10-31 16:47
IMHO it would be better to retarget all of  #9132 to release. 

But is it necessary at all? We will start the new beta phase hopefully rather soon, so do we really want to prepare a third bugfix release before it?

**Comment by moving-bits** [comment] 2020-10-31 22:23
#9132 would have to be adapted if targeted to release branch, since it includes a line for update to v87 which is on master only.

We can leave #9322 unmerged for now. If there's need for another small bugfix release, we can include it, but if we start a new beta cycle soon, we can ignore it.

**Comment by Lineflyer** [comment] 2020-11-01 00:28
Some more users with instant crash problem. I guess some users only randomly update their apps, so they skipped a few versions and only now run into this problem.

Maybe it would be wise to issue another bugfix release next week as also if we plan on `master` it will need some weeks of beta phase.

**Comment by Lineflyer** [comment] 2020-11-01 11:33
@moving-bits 
Can you explain to me in what scenario this crash appears?
Meaning: What is the problematic DB version and what release is it related to? Does it already happen if users upgrade (or use a backup file) from version 2020.08.04 or should this work normal and the problem only appears with data from even older releases?

**Comment by moving-bits** [comment] 2020-11-01 11:58
It will happen for databases older than (internal) version 81, thus having the "route" table not yet created. During database migration the table will get created with the current table definition, but a few steps later this definition will be changed again. This step will fail, as the table already has the most recent definition.

This is a conceptual problem we currently have with our database updates if we create a table and change it significantly later on. Example (pseudo code):

Version 10:
`CREATE TABLE test (a INT);`

Version 15: (renames column a to b)
`ALTER TABLE test CHANGE a b INT;`

The table definition is stored in a string. At the time version 15 is being rolled out, the string is changed to the new definition (`CREATE TABLE test (b INT)`). This is no problem, if the user's database is somewhere between 10 and 15, but if you are coming from a version < 10, the update statement for version 10 will already use the new table definition, thus the update statement for version 15 will fail.

This is partly mitigated with the recent addition of the "CreateColumnIfNotExists" (or something like that) method, which allows for adding columns in a compatible way, and partly by the additions to the "CreateIndices" method, but for table creation this is yet to be done.

**Comment by Lineflyer** [comment] 2020-11-01 12:04
Thanks for the explanation.
version 81 refers to which release of c:geo?

**Comment by moving-bits** [comment] 2020-11-01 12:43
As DB upgrade to version 81 introduces the `cg_route` table, this should be the first release supporting the individual route feature - AFAICS this is 2020.04.25.
(The database you had sent me for cross-checking was version 76 and had a file date from January 2020.)

BTW: You can see what gets changed by a DB upgrade by looking at `storage/DataStore.java` around line 1200.

**Closed** 2020-11-01 14:13 UTC
Labels: Bug
