### ISSUE TITLE
Found OC caches shown on live map as unfound

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#11291] opened 2021-07-21 22:00 UTC
### Describe your problem!

Similar to #11253 also the live map shows OC caches I have found (while having the found filter active) but as unfound.
As soon as I open the cache the (correct) found state is shown.

### How to reproduce?

1. Have OC.de active
2. Open live map on a position where you have found OC caches

### Actual result after these steps?

OC caches shown as not found

### Expected result after these steps?

OC caches either shown as found or correctly filtered out (if found filter is active)

### Reproducible

Yes

### c:geo Version

2021.07.21-NB

### Additional Information

Reference to #11253

**Comment by eddiemuc** [comment] 2021-07-22 05:11
Am I understanding correctly that the fix for  #11253 simply does not work? Ornis this now only happening in live map (and not in nearby search)?

**Comment by Lineflyer** [comment] 2021-07-22 09:29
> m I understanding correctly that the fix for #11253 simply does not work? Ornis this now only happening in live map (and not in nearby search)?

The fix works (was for searches), but now I found this problem on the live map as well. Not sure if it was there already before.

**Comment by eddiemuc** [comment] 2021-07-24 18:06
Confirmed, but can be reproduced by me without involving found filter. Following is for me to reproduce (and debug) secnario later:
* Use an already found and locally stored oc-cache (in my case e.g. OCD964)
* OPen live map and navigate to cache
     * not sure if related, but I had a filter "origin=oc.de" active
=> cache is shown as NOT FOUND
* open cache detail popup, then close it again immediately
=> FOUND smiley appears for a short time, then disappears again

**Comment by eddiemuc** [comment] 2021-07-24 18:08
Additional note: seems to "work" only after immediate opening of "live map". If the filter is changed afterwards (regardless how it is changed), the issue seems "fixed" afterwards. 

Maybe also important: Google Maps was used

**Comment by eddiemuc** [comment] 2021-07-24 18:32
Problem seems to be that cache in question resides in "cacheCache" with found flag = false, while it has "found=true" in DB. 

Is there anyone out there who can point me to some sort of documentation on how this mysterious cacheCache works?

**Comment by Lineflyer** [comment] 2021-07-24 18:41
I don't think the cachecache is the main problem here, but the fact, that the found state is not derived when calling caches for the map, thus resulting in this flapping found state.
Did something change recently with how live map data is presented? I am pretty sure my found OC have never shown up on live map before (saved and not saved).

**Comment by eddiemuc** [comment] 2021-07-24 18:41
Ok, problem seems to be that cache data returned from oc.de does not contain the "found" flag.
Set breakpoint in Datastore around line 1965 as follows to evaluate further:

```
public static void saveCache(final Geocache cache, final Set<LoadFlags.SaveFlag> saveFlags) {
        saveCaches(Collections.singletonList(cache), saveFlags);
    }
```

**Comment by Lineflyer** [comment] 2021-07-24 18:42
Might also be a bug on OC.de or was there a change on what we request from them?

**Comment by eddiemuc** [comment] 2021-07-24 18:59
Fixex with PR #11309. Man, this was a long search!

**Comment by Lineflyer** [comment] 2021-07-24 19:30
Oh, wow. Good catch!

**Comment by eddiemuc** [comment] 2021-07-25 07:59
retest this please

**Comment by eddiemuc** [comment] 2021-07-25 08:00
> retest this please

hehe, probably does not help to write this into the issue instead of the PR :-)

**Closed** 2021-07-25 08:20 UTC
Labels: Bug
