### ISSUE TITLE
Calculating waypoints with variables defined once

### ISSUE THREAD

**Issue by andrcoding** [cgeo/cgeo#9993] opened 2021-02-09 20:15 UTC
It would be very nice if defined variables for a coordinate calculation of one specific waypoint (in the waypoint menu of a gc) are available for all coordinate calculations of this cache. This would improve the usage for multis.

**Comment by moving-bits** [comment] 2021-02-10 19:54
Duplicate of #6691

**Closed by moving-bits** 2021-02-10 19:54 UTC
Labels: Duplicate, Feature Request
