### ISSUE TITLE
Google maps crashes on Android 10

### ISSUE THREAD

**Issue by CyanBlob** [cgeo/cgeo#7369] opened 2019-03-14 17:11 UTC
##### Detailed steps causing the problem:
- Upgrade to the Android Q beta
- Open c:geo
- Select "Live map" view

##### Actual behavior after performing these steps:
The app immediately crashes

##### Expected behavior after performing these steps:
The app does not crash

##### Version of c:geo used:
2019.02.23

##### Is the problem reproducible for you?
Yes, even post-reboot

##### System information:
```
--- System information ---
Device: Pixel 3 (blueline, google)
Android version: Q
Android build: QPP1.190205.018.B4
c:geo version: 2019.02.23
Google Play services: enabled - 16.0.86 (100400-237483552)
Low power mode: inactive
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: rotation vector
Hide own/found: false
Map strategy: auto
HW acceleration: enabled (default state)
System language: en_US
System date format: M/d/yy
Debug mode active: no
System internal c:geo dir: /data/user/0/cgeo.geocaching (30.6 GB free) internal
User storage c:geo dir: /storage/emulated/0/cgeo (30.6 GB free) external non-removable
Geocache data: /storage/emulated/0/Android/data/cgeo.geocaching/files/GeocacheData (30.6 GB free) external non-removable
Database: /data/user/0/cgeo.geocaching/databases/data (148.0 KB) on system internal storage
Fine location permission: granted
Write external storage permission: granted
Geocaching sites enabled:
   geocaching.com: Logged in (Login OK) / BASIC
Geocaching.com date format: M/d/yyyy
Installed c:geo plugins:  none
--- End of system information ---
```

**Comment by Lineflyer** [comment] 2019-03-15 15:40
Does this happen for you on all map types of the live map?
What about if you try to open a map for a single cache (Cache Details -> Navigate -> Map)?

**Comment by moving-bits** [comment] 2019-03-15 16:40
LogCat shows two different errors while opening live map on a freshly installed c:geo on Android Q:
- some layout inflating problem ("cgeo.geocaching E/AndroidRuntime: FATAL EXCEPTION: main
    Process: cgeo.geocaching, PID: 4788
    java.lang.RuntimeException: Unable to start activity ComponentInfo{cgeo.geocaching/cgeo.geocaching.maps.google.v1.GoogleMapActivity}: android.view.InflateException: Binary XML file line #32: Binary XML file line #32: Error inflating class cgeo.geocaching.maps.google.v1.GoogleMapView")
- "cgeo.geocaching E/AndroidRuntime: Caused by: java.lang.NoSuchMethodError: No virtual method getController()Lcom/google/android/maps/MapController; in class Lcgeo/geocaching/maps/google/v1/GoogleMapView; or its super classes (declaration of 'cgeo.geocaching.maps.google.v1.GoogleMapView'" (which may or may not be a follow up error of the first one)

tested with current master / Android Q preview

**Comment by Lineflyer** [comment] 2019-03-15 18:01
One more reason to get a newer Google Maps implementation.

**Comment by Lineflyer** [comment] 2019-03-25 15:59
Also reported by another user. For that user only Google Maps is affected. With OSM the map is loading normal.

**Comment by Lineflyer** [comment] 2019-03-25 16:01
@moving-bits Your comment seems to imply, that you can reproduce on an emulator, or would it make sense to purchase a real device to be able to have hands on Android Q rather early?

Given I would have a Google phone, is Android Q preview/beta available for everyone?

**Comment by moving-bits** [comment] 2019-03-25 16:57
@Lineflyer  When the report came in I fired up the emulator with Q preview and the then recent version of c:geo, which resulted in the two errors in LogCat. Haven't tried since then.

AFAIK Q preview currently is available for the Pixel series only.

I don't think we need to buy a real device right now. Q is still in preview state, and it will take a long time until it gets a relevant market share. So far emulator is fine IMHO.

**Comment by Lineflyer** [comment] 2019-04-18 20:05
More reports coming in for this.

Is GMapsv1 no longer supported with Android Q??

**Comment by Lineflyer** [comment] 2019-06-12 16:33
Android Q might be release around August 2019. Another reason to get GMapsV2 in until then.

**Comment by crankyOldCanuck** [comment] 2019-09-04 02:05
Just updated to Android 10 today on my Pixel 3 XL. Cannot open Google Map / Satellite from anywhere. All other maps work fine.

**Comment by Lineflyer** [comment] 2019-09-04 18:29
Yes, this is known as can be read here.
It sadly requires quite some steps of changes in the app...we are working on it.

As Q is now release I will add a FAQ entry for it.

**Comment by jonas-koeritz** [comment] 2019-09-04 18:39
Works on my Android 10 device using the MapsV2 Branch, isn't MapsV1 missing
on Android 10?

Lars <notifications@github.com> schrieb am Mi., 4. Sept. 2019, 20:29:

**Comment by jonas-koeritz** [comment] 2019-09-04 18:56
We should push hard for maps V2, the PlayStore version won't show a map on
my device too.

Alternatively we could set Mapsforge as default and disable Google maps on
Android 10 devices until we are ready.

Lars <notifications@github.com> schrieb am Mi., 4. Sept. 2019, 20:29:

**Comment by Lineflyer** [comment] 2019-09-04 19:12
As written in #7798 IMHO we can fast-forward release to current master and then push GMAPv2 into master (together with TargetSDK28) at anytime now.

However it will most probably need several weeks or longer till we have it ready to publish, so plan B like defaulting to OSM and disabling Google on Android Q could be reasonable.

**Comment by alan666notb** [comment] 2019-09-06 07:50
People are posting about this now on the 'Geocaching UK' FB group.

**Comment by Lineflyer** [comment] 2019-09-06 18:19
Maybe we should really prepare a workaround as suggested above if someone has time to do that.

We could default to OSM when Android 10 is used and when someone selects Google show a message that we are working on getting it back.

**Comment by moving-bits** [comment] 2019-09-06 21:58
Created #7823 as temporary workaround: Automatically disables Google Maps on devices running on Android 10

**Comment by Lineflyer** [comment] 2019-09-08 12:01
FYI

Workaround has been set in place with cbbcb48aa5984cdee91c75159a1f7b35cc409bc2
It disables Google Map on Android 10 devices for the time being. Not nice, but better than crashing.

**Comment by moving-bits** [comment] 2019-09-13 14:59
reenabled on master with ed8524a, as Google Maps API v2 branch has been merged by now.

**Comment by moving-bits** [comment] 2019-09-23 16:08
Can be closed as Google Maps API v2 implementation is merged to master and last public release automatically switches to OSM on Android 10.

**Closed by moving-bits** 2019-09-23 16:08 UTC
Labels: Bug, Prio - High

**Comment by prensmiskin** [comment] 2020-01-07 16:23
delete old applications in the emulator.
