### ISSUE TITLE
Waypoint description not updated if new description is shorter

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#6223] opened 2017-01-02 19:17 UTC
##### Detailed steps causing the problem:
- Open a GC cache which has a waypoint that contains a description
- Check that the waypoint is identical to the listing on the website
- Ask the owner to change the description of the waypoint
- Refresh cache in c:geo

##### Actual behavior after performing these steps:
- Waypoint will keep showing the old description

##### Expected behavior after performing these steps:
- Waypoint should be updated with the new description

##### Version of c:geo used:
2016.12.28

##### Is the problem reproducible for you?
Yes

##### Other comments and remarks:
I can volunteer with my owned cache to help debugging this

Set to "High" as this might be not the standard case but still can make it impossible for users to find a cache (e.g. given they stored a cache long time ago and don't get the updated info 

Similar to #3650

**Comment by Lineflyer** [comment] 2017-01-02 19:20
Addon:
This seems to depend on the length of the description.
In my tests the problem did only show up if the new description is shorter than the old description.
If the new description text is longer it will be updated correctly.

**Comment by rsudev** [comment] 2017-01-02 20:00
The main problem is, that we do not now whether the description we have stored is the original one and therefore can be replaced, or if it is a user-modified one. IIRC I once already outlined what needs to be done IMO (can't find the issue right now). We need to separate the original WP description from the user modifications, then can we update the description as in this case.

**Comment by Lineflyer** [comment] 2017-01-02 21:21
That was disccued somewhere already AFAIR.
That was about the split into several waypoint categories.

**Comment by Lineflyer** [comment] 2017-01-08 18:32
After thinking about it, I agree thath this is not possible with our current implementation.
So I think the current method of comparing the length and taking the longer description is the best we can do.
I will let this open nontheless to keep reminded of this issue.

**Comment by pstorch** [comment] 2017-01-11 10:48
Related to #5353 (duplicate of this one, @rsudev mentioned), #5476, #5123
Do we want to continue our discussion here or at #5353? 

User can edit `name`, `note` and `coords` of a waypoint. The `visited` flag is only c:geo local. Is it really necessary to be able to change the `name` of a waypoint?
So we would need 2 or 3 additional database columns for waypoints. A migration strategy (how to handle the current modifications) and UI changes. User defined notes could be an extra field (as @rsudev proposed), but coords are a bit trickier. I guess the user wants his coords to be the ones used, but we need an indication that the coords are changed and offer some way to revert to the original coords.

**Comment by pstorch** [comment] 2017-01-25 10:47
I'll give it a try and work on a solution.

**Comment by pstorch** [comment] 2017-01-26 09:03
While investigating here a bit further I think we shouldn't allow changing the `name` of a waypoint if it is not a user defined waypoint (`isUserDefined()` == `false`). Because it will be (and always has been) overwritten by the value from the server on update and I guess no one has put in some valuable information here.

The `coords` can be changed and are overwritten by the server value on update as well. The only valid usecase is if there are no `coords` on the server side (like most final waypoints). Then the user defined `coords` are kept. Here we could go for only allow editing of the `coords` if it is the user defined WP or if the original `coords` are empty. And in the unlikely event, that the cache owner adds `coords` to a WP on the server side, the user defined `coords` would be lost. In the other cases the user would need to duplicate the WP and change the `coords` on his own copy then.

The `note` is easier: add a second `user_note` field and display it editable below the original `note` field. The original `note` field should be non-editable if it is not a user defined WP.

On Migration:
As @rsudev suggested here https://github.com/cgeo/cgeo/issues/5353#issue-124643320 we can copy all `note` fields to `user_note` field to be on the safe side. Later on update check whether both notes are identical and delete the `user_note`. The only thing is that it might confuse the users to see the notes duplicated (as long as the cache isn't updated). To mitigate this confusion we could hide the `user_note` if it is identical to the `note`.
The other option would be to copy on update if the new `note` is different from the old `note`. But that would cause all changes from the cache owner on the server side to get copied to the `user_note` field. So we would keep the previous version of the `note` field. And that would go on forever. Not so ideal.

Any comments so far?

**Comment by rsudev** [comment] 2017-01-26 22:17
For the migration of the note field, what about the following:
* If a WP is updated and the user_note is empty and the new note is different from the old note than copy the old note to the user_note.
* Otherwise just update the note

By that, either a changed note is preserved as user_note, or the previous version is conveniently made available by us ...

**Comment by pstorch** [comment] 2017-01-27 09:43
I also thought about this strategy. To see the changes of a WP description this way would be very interesting. But what about the WP List? There we show the `note` and I think we should also show the `user_note` there. Then if the CO corrects a typo in the description, we would copy the old version to `user_note` and show two very similar texts in the WP List. I don't know if this is useful.

**Comment by pstorch** [comment] 2017-01-27 21:45
My proposed solution in PR #6283 does not handle the `coords` as I thought. Editing `coords` on WPs from the server which don't have `coords` (like finals), is only working on first edit. After that there are `coords` and the field is set to read only.
I would like to avoid handling `server coords` and `user coords` with all the hassle of synchronizing, overruling and resetting. I would rather like to disable `coords` for server side WPs altogether. If a user want's to set `coords` he/she has to create a user defined WP, either by adding a new one or duplicating an existing one. 
That would be much easier to implement. What do you think?

**Comment by rsudev** [comment] 2017-01-28 07:38
I don't think this is a good idea, as providing waypoints without coordinates for convenient use by the cacher is one of the main points of a good multi-cache - and we should spoil that.
What about having a flag 'modifiable coordinates'? This could be set if a waypoint doesn't have coordinates on download. If the owner later decides to publish some, the modified ones could be copied to the user_note.

**Comment by pstorch** [comment] 2017-01-28 09:22
Yes, a flag might be a good solution.

**Comment by pstorch** [comment] 2017-01-28 14:58
Hmm, such a flag has also some quirks. It would always be `true` for user defined WPs and otherwise only be `true` if the loaded/parsed `coords` were empty. But what if we load WPs from other sources? Imagine a user has prepared WPs in GSAK and exported a GPX to c:geo. Then we would flag the `coords` as non-modifiable. That's also not good I think.

I just compared the behavior with Locus. There you can edit coordinates of all waypoints and on refresh they are silently overwritten by the server value if present. That's the way it works in our current version. Maybe it's not the same issue as with the edited `note` and we simply stick with the `coords` as it is.

As a safety net we could backup all changes to the `coords` to the `user_note` field (as @rsudev suggested, but for all WPs). But if you change a WP often (because you struggle with a formula), then you get a pile of old coords in the `user_note` field.

**Comment by rsudev** [comment] 2017-01-28 15:12
I am not so sure if imported WPs really is a problem. If you assign them coordinates in GSAK, why would you change them in the field? I also would assume that a WP that receives coordinates in the listing later on is the absolute edge case. So we should rather optimise for the main scenarios:
You get WPs with coords from somewhere, than there is typically no need to touch them (duplicate and modify would work still for the edge cases) or you get them without, than you want to set those in c:geo.

**Comment by pstorch** [comment] 2017-01-28 17:07
ack

**Comment by pstorch** [comment] 2017-01-28 17:40
BTW: we don't import WPs from GPX which don't have coordinates. Is that on purpose?

**Comment by pstorch** [comment] 2017-01-28 22:41
Interesting the GPX files from Geocaching.com don't have WPs without coordinates. Even if they have valuable information.

**Closed** 2017-01-31 20:25 UTC
Labels: Bug
