### ISSUE TITLE
Personal Note doubles 

### ISSUE THREAD

**Issue by notspecified** [cgeo/cgeo#5456] opened 2016-02-20 18:43 UTC
Hi!

Im on 2016.02.19-NB-7025585 and I use the personal note to store the variables from the stages of a multi cache. (just local on the device durring Caching, no upload)
So I switch between listing. Map, koordinates in the listing and the personal note.
After a few stages I noticed that the entries have been doubled! -See the screeshot.

I know this behaviour, I experienced it month ago, but I thought this has been fixed?! 
![screenshot_2016-02-20-19-17-28](https://cloud.githubusercontent.com/assets/5119558/13198491/12afccde-d80a-11e5-86d2-f6fd6b5adafe.png)

**Comment by samueltardieu** [comment] 2016-02-21 10:58
Duplicate of #5286, closing this one.

**Closed by samueltardieu** 2016-02-21 10:58 UTC
