### ISSUE TITLE
Add option to edit or delete your existing log

### ISSUE THREAD

**Issue by anondev-sudo** [cgeo/cgeo#14898] opened 2023-11-26 10:17 UTC
### Tell us your idea!

There should be option to edit or delete your log on geocache directly in cgeo without needing to go to geocaching website.

### What solution would you suggest?

When you long press on your existing log , there should be options to edit or delete it. Delete should require confirmation before deleting it. Edit should display same form as when you are sending new log and you should be able to modify log description, add/remove photos, visit/drop trackables and other available options which can be edited. Sometimes when I make typo in log or I want to add there more details or I forget to drop trackables I need to go to geocaching website in my chrome on my phone and edit the log there, I'm sure also others would welcome to have it directly in cgeo

**Comment by ztNFny** [comment] 2023-11-26 11:39
duplicate of #2012

**Closed by ztNFny** 2023-11-26 11:39 UTC
Labels: Feature Request, Unverified
