### ISSUE TITLE
UnifiedMap: set waypoint as target sets cache as target

### ISSUE THREAD

**Issue by ztNFny** [cgeo/cgeo#15488] opened 2024-03-20 11:20 UTC
1. open a cache with multiple waypoints
2. View in map mode (compass - map)
3. Tap a waypoint
4. In WP popup "set as target"

Expected: Navigation line to WP
Actual: Navigation line to cache listing

**Comment by MagpieFourtyTwo** [comment] 2024-03-23 00:57
Duplicate of #15473?

**Comment by moving-bits** [comment] 2024-03-23 21:38
Bug confirmed. Target gets reset as map is still in "geocode" mode (and we trigger a reload since one of the more recent changes on `release`)

**Comment by moving-bits** [comment] 2024-03-23 21:42
see PR #15506

**Closed** 2024-03-26 21:16 UTC
Labels: Bug, Map: Unified
