### ISSUE TITLE
Merge issue in live map: found flag not updated

### ISSUE THREAD

**Issue by rsudev** [cgeo/cgeo#4941] opened 2015-05-18 06:12 UTC
I have seen that on a users device at the giga in Mainz, need to reproduce myself.

Steps probably necessary to reproduce:
- have an unfound cache on your device (detailed yes, stored?)
- have setting filter found caches active
- log the cache as found on the website
- go to the live map showing the cache in question
- the cache is still visible (which is as expected)
- switch the filter found caches setting off
- the cache gets the found smilie attached when refresh finished
- switch the filter found caches setting on again
- the smilie vanishes, the cache is still shown!

**Comment by Lineflyer** [comment] 2016-08-31 20:19
Duplicate of #3136

**Closed by Lineflyer** 2016-08-31 20:19 UTC
Labels: Bug, Live Map, Unverified
