### ISSUE TITLE
Poor notification when unable to send log

### ISSUE THREAD

**Issue by mucek4** [cgeo/cgeo#1646] opened 2012-05-26 09:55 UTC
When you made online log and you are on really bad connection c:geo is sometimes unable to send log. It's only notified as toast and it's almost the same text as found.

I suggest when c:geo fails to send log a popup window should be displayed.
Something like
c:geo failed to post log because server is not responding.

and options. Retry, save offline, go back to editing

**Comment by Bananeweizen** [comment] 2015-08-21 11:34
@Lineflyer Do you want to comment on why this was reopened?

**Comment by Lineflyer** [comment] 2015-08-21 15:49
Because @kumy assigned me for a field test...and I initially did not notice as the issue was closed. Will close it after field test. Thats how we established this testing workflow initially with @samueltardieu which I think is a good approach.

**Comment by kumy** [comment] 2015-08-21 15:52
@Lineflyer if so, more issues should be reopened! I'll do.

**Comment by Lineflyer** [comment] 2015-08-23 20:01
I tested this disabling the network connection once the logging window was fully loaded. It seems to work as intended in 2015.08.23-NB. 

@kumy:
Just one question for clarification: Where do we get the reason (string) for this problem. In my case it was "Login failed" with is implicitly OK but the real reason is that I don't have a connection.

**Comment by kumy** [comment] 2015-08-23 20:53
@Lineflyer I've just replaced the old `Toast` notification by this `Dialog`. Error message is exactly the same as before. (I've just added the string `Reason :`). I remember we've discussed about `tell the user which part has failed (if any)` in #5133 we should open a bug for that. Could you write it, please?

**Comment by Lineflyer** [comment] 2015-08-30 21:01
Will do. Lets close this one then.

**Closed by Lineflyer** 2015-08-30 21:01 UTC
Labels: Feature Request, Field test, Frontend Design

**Comment by samueltardieu** [comment] 2015-08-30 23:17
> Do you want to comment on why this was reopened?

@Bananeweizen The procedure described by @Lineflyer  is a workaround for the limitations of GitHub issue tracker. What I usually do (and @kumy does to apparently) is:
- assign the bug to myself
- fix the bug (which closes it)
- set the milestone to `master`
- reopen it and assign it to @Lineflyer with `Field testing` tag added and ask if this should be merged into `release` if this was based on this branch
- once @Lineflyer has confirmed that the solution is satisfactory, he reassigns it to me (so that we can see who fixed what), removes `Fields testing`, and either closes it or states that he wants it merged into `release` (in which case Iclose the issue and update the milestone to `release` after I have merged it there).

This way, the bug is always opened and assigned to someone in charge until the work on it is done. If we used a better issue system, we would have "field test" and "merge to release" states that we could work with.
