### ISSUE TITLE
Country filter should only offers countries contained in the list to be filtered

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#8716] opened 2020-07-30 23:36 UTC
- Have one list with caches from many countries
- Have another list with caches of one country
- Open the list with caches of one country only
- Select Filter - Country

Result:
Filter options show all countries contained in all lists

Expected Result:
Offer only those countries in the filter which match the list content

Note:
I came across this as a user reported, that calling the filter keeps crashing the app, although he only has a single cache on the list where he tries. It turned out that he has a cache on another list, which causes a problem. (Still trying to find out which cache causes this to open a dedicated issue for that).

**Comment by moving-bits** [comment] 2020-07-31 09:17
Our current filter implementation is not suited for this, as the filters do not have any information regarding the current cache list and its contents. 

Related to #8273

**Comment by eddiemuc** [comment] 2021-05-08 08:16
Isnit ok to close this as duplicate of #8273 (which introduces a broader view on the topic)?

**Comment by eddiemuc** [comment] 2021-05-29 06:14
Before I dive into this deeper: do we really need a country filter? Seems like a rare edge case to me for people living/caching in areas along country borders

**Comment by moving-bits** [comment] 2021-05-29 12:39
Or people wanting to list "what caches have I visited in country xx". (Don't know, though, how frequent that use case is.)

**Comment by eddiemuc** [comment] 2021-06-06 16:23
See PR #10875 for an implementation and a discussion for this implementation

**Closed** 2021-06-07 11:49 UTC
Labels: Feature Request
