### ISSUE TITLE
TB inventory is blank after isActive() has been implemented in TravelBugConnector

### ISSUE THREAD

**Issue by alan666notb** [cgeo/cgeo#7617] opened 2019-05-14 11:43 UTC
Since installing 2019.05.13-RC, the TB inventory page is blank. 
The inventory page appears if there are TB's present, but it is blank. 

- load GC3QGD1 - Reigate Travel Bug Hotel
- swipe across to the inventory page

##### Actual behavior after performing these steps:
The page is blank

##### Expected behavior after performing these steps:
This cache has several TB's present, they should be shown. 

##### Version of c:geo used:
2019.05.13-RC

##### Is the problem reproducible for you?
Yes

##### Other comments and remarks:
This was definitely introduced by 
2019.05.13-RC

**Comment by Lineflyer** [comment] 2019-05-14 11:57
Can reproduce!
@moving-bits Any idea?

The tab is shown, but its empty.
GKs in OC.de caches are shown.

**Comment by moving-bits** [comment] 2019-05-14 21:24
I'll need to debug into this (but won't be able to do so before the weekend).

Strange thing, because the only change regarding TB in the last release was the implementation of the `isActive()` function for the gc.com trackable connector so that now it reflects the actual connection state (`true || false`), whereas before it always returned `false`... ?!

**Comment by Lineflyer** [comment] 2019-05-15 19:44
I did some more testing:
Indeed with 2019.04.29-RC the inventory shows normal, whereas with 2019.05.13-RC the tab is still there but with no content.
So its most probably caused by one of the three commits on `release` between those versions.

**Comment by jonas-koeritz** [comment] 2019-05-15 19:46
I also had some strange behaviour with TBs not beeing shown on the log Activity. There seems to be something going on.

**Comment by UniQP** [comment] 2019-05-15 20:23
It seems like 8415f7f00be6d1ec1ee09c4cb62fb7545b7808b4 causes the issue.

**Comment by Lineflyer** [comment] 2019-05-15 20:37
> It seems like 8415f7f causes the issue.

That is likely and with my limited code knowledge I tried to find out why it prevents the trackable being shown in the inventory tab....but I don't get it.

@jonas-koeritz 
No problem for me when its comes to the inventory in log activity. As I cross tested several versions (see above) I can more or less exclude a server problem.

**Comment by UniQP** [comment] 2019-05-15 22:17
The problem is that the `TravelBugConnector` does not override the `searchTrackables` method and the default implementation always returns an empty list.

**Comment by jonas-koeritz** [comment] 2019-05-15 22:30
Nice Catch! :+1:

**Comment by moving-bits** [comment] 2019-05-16 07:10
> The problem is that the `TravelBugConnector` does not override the `searchTrackables` method and the default implementation always returns an empty list.

But as there has been no change to that part: Shouldn't have this one hit us all the time already?

**Comment by UniQP** [comment] 2019-05-16 07:43
The difference is that with the active connector we populate `processedBrands` in https://github.com/cgeo/cgeo/blob/master/main/src/cgeo/geocaching/CacheDetailActivity.java#L345, which leads to a different result for the if statement in https://github.com/cgeo/cgeo/blob/master/main/src/cgeo/geocaching/models/Geocache.java#L1065.

**Comment by moving-bits** [comment] 2019-05-17 19:31
Hm, I cannot reproduce in the emulator, neither with or without the `searchTrackables` method, neither with release nor with master version. Any specific steps & prerequisites to reproduce (besides the ones mentioned in the opening article)?

**Comment by UniQP** [comment] 2019-05-17 20:03
I tested it on a real device. There, it was sufficient to just follow the two steps of the issue description.

**Comment by Lineflyer** [comment] 2019-05-17 22:06
Timing issue?

**Comment by UniQP** [comment] 2019-05-17 22:42
I could also reproduce the issue with the emulator (current release branch).

**Comment by Lineflyer** [comment] 2019-05-18 09:49
Is someone working on this?

**Comment by UniQP** [comment] 2019-05-18 09:51
@moving-bits ?

**Comment by moving-bits** [comment] 2019-05-18 12:43
I'm able to reproduce the behaviour on a physical device now, but did not find a quick solution. Created a workaround to be able to release.

**Comment by Lineflyer** [comment] 2019-05-18 15:54
Topic changed. See #7624

**Comment by jakedot** [comment] 2019-06-07 19:51
Is this finished or still a problem?

**Comment by moving-bits** [comment] 2019-06-07 20:13
This is still valid. The underlying glitch is that you can search for trackables even if no trackable connector (like geocaching.com or geokrety) is set to active (see #7555). #7561 implemented a fix for this (and #7554 as well) and worked fine with geokrety, but the fix for #7555 triggered some side effects in the TravelBug Connector, as `isActive()` and `searchTrackables()` methods are missing. So we reverted the fix for #7555 and opened this issue.

**Comment by fm-sys** [comment] 2021-10-02 17:01
Can this be closed (together with #7555) as "won't fix"?

IMHO, it's totally ok to search on disabled connectors as well, if the user actively searches for a geocode belonging to a disabled connector...

**Comment by ztNFny** [comment] 2024-12-27 12:05
Closing this as part of the ongoing SearchActivity redesign

**Closed by ztNFny** 2024-12-27 12:05 UTC
Labels: Bug
