### ISSUE TITLE
Filter by menu uses different style then other menues

### ISSUE THREAD

**Issue by fohlsso2** [cgeo/cgeo#4675] opened 2015-02-13 18:59 UTC
Hi.

The 'Filter by' menu in list view is using the older large (huge) style, and so does its sub menues.
Would it be possible to change that so it uses the same style as the list menu and the sort menu?

**Comment by SammysHP** [comment] 2015-02-13 19:16
Duplicate of #3887.

**Closed by SammysHP** 2015-02-13 19:16 UTC
