### ISSUE TITLE
Create waypoints directly from the map view

### ISSUE THREAD

**Issue by TheVoytekBear** [cgeo/cgeo#6561] opened 2017-05-15 04:32 UTC
I just swithed from WM10 where I was using maaloo geocaching. While I'm really impressed with all the features has, there is one I'm already missing very much. Like stated in the subiect, it woild be great to be able to create a waypoint by just taping and holding on the map.

Use case:
- I view the cache I want to drive to and it doesn't have a parking waypoint.
- In the map view I can see an OSM marked parking near by (or any other object that could serve as a parking spot).
- I tap and hold on that spot and a "pin" or createn wew WPT menu appears
- From that menu I can either save it or select "Navigate" option (which I can use to pass the location e.g. to Google maps.

I consider this feature useful because sometimes suitable parking places aren't always on the road closest to the target (therefore the navigation might not lead you to them if you navigate to the cache coordinates). Also, in an unfamiliar country it is best to be navigated straight to the parking as different signs and markings already add to the confusion.

Regards
WW

**Comment by SammysHP** [comment] 2017-05-15 06:30
Duplicate of #5375, #3693, #1141.

**Closed by SammysHP** 2017-05-15 06:30 UTC
