### ISSUE TITLE
Heavy blinking of map

### ISSUE THREAD

**Issue by geocachermgo** [cgeo/cgeo#15108] opened 2023-12-27 20:09 UTC
### Describe your problem!

I used the offline map and at some time the street names were replaced by black rectangles and back with a frequency of about 2Hz. So 20 blinking rectangle were shown.
This happen after turning the map.

### How to reproduce?

I was not able to reproduce it at home

### Reproducible

No

### c:geo Version

2023.12.27-NB-54d0bc0

**Comment by murggel** [comment] 2023-12-27 22:24
I had a similar effect after activating live-mode with current nightly. But also only a one-time effect and not yet reproducible. 
I sent the log-info per Mail

**Comment by moving-bits** [comment] 2023-12-28 21:37
maybe related to or even duplicate of #15100?

**Comment by geocachermgo** [comment] 2023-12-30 18:01
It happend again:
The sector colouring mistakes were also there the last time.
![Screenshot_2023-12-30-14-17-56-652_cgeo geocaching](https://github.com/cgeo/cgeo/assets/43813636/e51f3139-a147-4ddc-8df9-07b06969e5b9)
![Screenshot_2023-12-30-14-18-03-871_cgeo geocaching](https://github.com/cgeo/cgeo/assets/43813636/92ba0ee1-7e52-4c03-916d-56c3f3a1e2e2)
![Screenshot_2023-12-30-14-18-06-090_cgeo geocaching](https://github.com/cgeo/cgeo/assets/43813636/524ca3c5-1a8c-4224-bf11-e879f6c8ddb4)

**Comment by moving-bits** [comment] 2024-02-04 14:54
Let's close this in favor of #15100 where all the discussion about black boxes and other artifacts on our VTM map implementation is happening

**Closed by moving-bits** 2024-02-04 14:54 UTC
Labels: Bug, Unverified, Duplicate
