### ISSUE TITLE
Crash when opening Live map when offline

### ISSUE THREAD

**Issue by GodfatherThe** [cgeo/cgeo#5818] opened 2016-07-09 15:34 UTC
##### Detailed steps causing the problem:
- Disable Internet connections
- open c:geo
- Click Live Map

##### Actual behavior after performing these steps:
App crashes

##### Expected behavior after performing these steps:
App should open map with stored caches and saved map data

##### Version of c:geo used:

2016.07.05-NB-4b95531

##### Is the problem reproducible for you?
Yes

##### System information:
```
Attach system information here if available (see c:geo menu -> About c:geo -> System)
```
--- System information ---
Device: D5803 (D5803, Sony)
Android version: 5.1.1
Android build: 23.4.A.1.232
Cgeo version: 2016.07.05-NB-4b95531
Google Play services: enabled
Low power mode: inactive
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: rotation vector
Hide own/found: false
Map strategy: detailed
HW acceleration: enabled (default state)
System language: en_US
Debug mode active: no
Geocaching sites enabled:
   geocaching.com: Logged in (Login OK) / BASIC
   Geocaching.su
Installed cgeo plugins: calendar, contacts
--- End of system information ---

##### Other comments and remarks:
If click "disable live" in map settings when online, then it diesnt crash when following the use case above. So seems the root cause is connected with incorrect handling live when offline.

**Comment by Lineflyer** [comment] 2016-07-10 21:04
I cannot reproduce that with current master.
Can you post a debug log please?

**Comment by GodfatherThe** [comment] 2016-07-11 05:39
Where can I find the log?

**Comment by samueltardieu** [comment] 2016-07-12 16:12
@GodfatherThe https://github.com/cgeo/cgeo/wiki/Send-log-to-developers

**Comment by GodfatherThe** [comment] 2016-07-12 19:20
It looks like black magic - issue is NOT reproducibke when debug logging is on. But when I turn it off, app starts crashing. Any ideas, what can help you to investigate?
I can only attach video so far https://yadi.sk/i/g4wqyMgftEoaN (note wifi and mobile connections are off)

**Comment by Lineflyer** [comment] 2016-07-14 20:55
Interesting.
As only a debug log will bring new clues on that its difficult...but try a log without having the setting active...maybe we still can get a clue.

**Comment by samueltardieu** [comment] 2016-07-14 22:38
Yes, the log should still contain useful info. I hope so at least, as I cannot reproduce the issue with and without debugging enabled.

**Comment by Lineflyer** [comment] 2016-08-31 20:45
Closing as unreproducible.

**Closed by Lineflyer** 2016-08-31 20:45 UTC
Labels: Bug, Unverified

**Comment by GodfatherThe** [comment] 2016-10-30 15:44
Still reproducible for me btw.. Really stable behavior and crash. So if I forget to uncheck "live map" the I wouldn't be able to do anything when offline due to crash.. And I still has no root on my smartphone..
