### ISSUE TITLE
Feature: Add cache entry manually or semi-automated for offline-caching

### ISSUE THREAD

**Issue by Matze2** [cgeo/cgeo#6214] opened 2016-12-29 00:01 UTC
Use Case: Base Members cannot add PMO caches to lists.

On the other hand, BMs are allowed to log and sometimes have access to PMO listings, e.g. through a Premium Member colleague.

Phase 1 could be to create a cache entry by entering GCCode, Name and Coords manually.
Later some details could be retrieved automatically, e.g. owner, D/T rating. One way to get this information is nearby search.

Currently the only way to enter PMO coordinates is to add a reference point to an already existing different  cache.

**Comment by SammysHP** [comment] 2016-12-29 07:29
Duplicate of #132.

You can use the goto function to navigate to coordinates without context. For PMO caches you can also import a GPX file (you need the coordinates from someone anyway).

**Closed by SammysHP** 2016-12-29 07:29 UTC

**Comment by Matze2** [comment] 2016-12-29 08:58
Sorry I haven't seen #132. Thanks for pointing me to that issue.

Just let me mention that there are other cases, e.g. you get the listing from the owner as text or PDF. Then you do not have a GPX. And of course getting the GPX "ad hoc" is also not very realistic.

But as mentioned in #132, it is enough to have a GPX file generator. And I see that more as a desktop application because it is cumbersome to add more than a few entries in a mobile.
