### ISSUE TITLE
Search by address - result -> different caches when tap on text or map symbol

### ISSUE THREAD

**Issue by bekuno** [cgeo/cgeo#11331] opened 2021-07-26 20:02 UTC
### Describe your problem!

After a successful search for an address you can tap on the text or on the map symbol to open the results.
![Screenshot_20210727-122451_cgeo](https://user-images.githubusercontent.com/32555742/127139300-18cf8aaf-e9a3-4196-bb6f-c29244655763.jpg)

**A** - Tap on the text:
![Screenshot_20210726-215321_cgeo-1](https://user-images.githubusercontent.com/32555742/127050929-d8c827d6-ca52-487b-89c9-fb0f80f83ca8.jpg)

**B** - Tap on the map symbol:
![Screenshot_20210726-215350_cgeo-1](https://user-images.githubusercontent.com/32555742/127050947-a94fdeb3-8368-4623-b429-8715b669fb56.jpg)

Both should show the same result (as list and in map).

### How to reproduce?

- Open the "Search" activity from the main screen.
- In the field "Search by address" type your destination, e.g. "Berlin" and search for it
- you should see the correct result
- tap on the name or on the map symbol

### Actual result after these steps?

- for the results see above

### Expected result after these steps?

- both should have the same result - the list of caches and the caches on the map

### Reproducible

Yes

### c:geo Version

2021-07-26-NB

edited.

**Comment by Lineflyer** [comment] 2021-07-26 21:46
Either I don't understand it or I think its OK.

Tapping on the map icon just opens the live map on that spot. No filtering involved here.

**Comment by eddiemuc** [comment] 2021-07-27 05:50
When Searching by address, the user gets a list of found addresses displayed. He can choose for each entry whether he wants to open result list as list or in map. I assume this is what @bekuno refers to?

@bekuno would it be plausible for you that the result size is zero (e.g. no caches in the area)?

**Comment by bekuno** [comment] 2021-07-27 06:32
> 
> 
> When Searching by address, the user gets a list of found addresses displayed. He can choose for each entry whether he wants to open result list as list or in map. I assume this is what @bekuno refers to?
> 
Yes.
(BTW, you get only one result from this query)

> @bekuno would it be plausible for you that the result size is zero (e.g. no caches in the area)?

No.
I searched in my sample for Berlin.

Now I edited the issue description and filled more details in it. Hopefully it is clearer now.

**Comment by Lineflyer** [comment] 2021-07-27 08:09
I am sorry, but I still don't understand.

- First of all, why is your result list empty? For me it works normal.
- Second: There can't be the exact same result for list and map, because the list returns the search result (with certain limits of cache amount, etc.) while opening the map is not connected to the search but simply starts the live map at the coordinates of "Berlin". So I assume there will be more caches on the map (depending on zoom) as listed in search results
- What should be the same is when you look at the search result list and then map this search result. This should indeed show the same caches first as list, then on map.

**Comment by bekuno** [comment] 2021-07-27 10:27
> 
> 
> I am sorry, but I still don't understand.
> 
>     * First of all, why is your result list empty? For me it works normal.

I'm not sure when you got no result.
See also https://www.facebook.com/groups/cgeo.fangruppe/posts/2683570861941477


> 
>     * Second: There can't be the exact same result for list and map, because the list returns the search result (with certain limits of cache amount, etc.) while opening the map is not connected to the search but simply starts the live map at the coordinates of "Berlin". So I assume there will be more caches on the map (depending on zoom) as listed in search results

The problem is, that you get *no* result from the requested area.
Maybe a viewport to the destination area is also needed for the list view?

> 
>     * What should be the same is when you look at the search result list and then map this search result. This should indeed show the same caches first as list, then on map.

This I don' t  understand.
Tap on the text should show caches in the destination area as list. Thease can of cause be shown later on map.
And this should be nearly the same result, when clicking directly on the map symbol.
I added a aditional screenshot for the first result window above in the issue description.

**Comment by bekuno** [comment] 2021-07-27 14:24
@Lineflyer 
Do you tesed with beta or nightly?
I do have the problem only in the nightly.
The visible difference here is the search bar with the "Distance" entry in the nightly (see picture in the issue description) and no such in the current beta.

**Comment by Lineflyer** [comment] 2021-07-27 14:55
So the main problem here is that your address search is not working for an unknown reason.

I tested with both. 
The address search is working normal for me in both.

What connectors do you have activated (only GC or some others as well)?

Thats how it looks to me:
![Screenshot_20210727-165231_cgeo](https://user-images.githubusercontent.com/949669/127176798-052e470f-c73c-40ef-bad4-2e580ffa9e31.jpg)

**Comment by bekuno** [comment] 2021-07-27 15:28
I had also Lab and OC.de active.
After deactivating both and restarting c:geo the result is unchanged.
@eddiemuc Do you have any idea here?

**Comment by eddiemuc** [comment] 2021-07-27 15:37
@bekuno No idea yet, have to check in code as soon as time permits. I also wonder why this differs between beta and nightly.

What about other searches using coordinates (e.g. "nearby search" or "Search by coordinate"), do those work?
Does it work for other coordinates?

**Comment by eddiemuc** [comment] 2021-07-27 15:39
@bekuno this is a wide shot, but doesnthe search work when you switch language to English?

**Comment by bekuno** [comment] 2021-07-27 15:54
See the screenshots: my search was in (system) language English, @Lineflyer in German.
I switched now to German, restarted c:geo, but no change.
Maybe there is a hidden filter element active?

**Comment by eddiemuc** [comment] 2021-07-27 16:05
@bekuno Inam grasping for straws here, but can you look up the filter definitions for LIVE filter in your system information? If there's a hidden filter it should at least show up there.

**Comment by bekuno** [comment] 2021-07-27 16:09
> What connectors do you have activated (only GC or some others as well)?

Now I had another try with the search on another device with 4 active connectors (c:geo Version 2021.07.17-RC2).
Here I got many results in the list for the "Berlin" search - bot nothing from geocaching.com. (mostly OC.de)

**Comment by bekuno** [comment] 2021-07-27 16:26
Maybe I found the error reason.

After the search without result I changed the filter: Activated the extended mode and deleted the DT-Filter.
Going back to the search list I get now a 200 Caches as result.

For the devide with the beta version I am unsure now.
After a change of the D-Filter now the GC caches are shown and the situation before is not reproducible.

**Comment by Lineflyer** [comment] 2021-07-27 16:31
> After the search without result I changed the filter: Activated the extended mode and deleted the DT-Filter.
Going back to the search list I get now a 200 Caches as result.

Looks like there is something wrong with the initial filter setting here? Did you use the advanced mode ever before since installation?

**Comment by bekuno** [comment] 2021-07-27 16:38
> 
> 
> > After the search without result I changed the filter: Activated the extended mode and deleted the DT-Filter.
> > Going back to the search list I get now a 200 Caches as result.
> 
> Looks like there is something wrong with the initial filter setting here? Did you use the advanced mode ever before since installation?

Yes for both devices.
Maybe the problem is not visible in other situations.

**Comment by Lineflyer** [comment] 2021-07-27 16:41
If this is ever reproducible you should immediately store the system information as it might contain a clue in the filter expression printed out there (as mentioned earlier by @eddiemuc ).

**Comment by bekuno** [comment] 2021-07-27 17:08
Maybe you can ask the FB user to sent you her system information?

**Comment by eddiemuc** [comment] 2021-07-27 17:09
My best guess wrt available info is that there was some leftover information in old filter not parseable any more with a new Cgeo version (maybe a leftover difficulty or terrain filter). This may have lead to some exception in the background, invalidating current search run and left an empty result list.

I can try to reproduce the behavior of Cgeo when given an invalid filter config in the address search case

**Comment by bekuno** [comment] 2021-07-27 17:29
It is reproducible with the nightly.
- Open live map
- open filter
- switch to extended
- delete all filter criteria
- save
- the system information shows
![Screenshot_20210727-191737_cgeo](https://user-images.githubusercontent.com/32555742/127199143-be81a435-1bac-4983-976d-d86f7ba02c7d.jpg)

- open the search
- search for eg. Berlin
- result is as above

**Comment by Lineflyer** [comment] 2021-07-27 18:02
Can't reproduce here. I wonder why the sys info still shows the D/T specific filter.

**Comment by Lineflyer** [comment] 2021-07-27 18:06
Something is strange there...I was also able to reach a state where it shows a D/T filtering in system infor while the filters are all deleted.
Happens for both live and offline., but however I do only see this in the system info without functional impact.

**Comment by eddiemuc** [comment] 2021-07-27 18:57
> Something is strange there...I was also able to reach a state where it shows a D/T filtering in system infor while the filters are all deleted.

This is actually the way in which the new d/t filter represents it's "nothing set" state. It is a result of it's combination of two other existing filters. Can be reworked of course but shouldn't have an impact on functionality (after all this is an internal representation).

Except of course if this leads to exceptional behavior...

**Comment by murggel** [comment] 2021-07-27 19:16
> > Something is strange there...I was also able to reach a state where it shows a D/T filtering in system infor while the filters are all deleted.
> 
> This is actually the way in which the new d/t filter represents it's "nothing set" state. It is a result of it's combination of two other existing filters. Can be reworked of course but shouldn't have an impact on functionality (after all this is an internal representation).
> 
> Except of course if this leads to exceptional behavior..

I can check that

**Comment by murggel** [comment] 2021-07-27 20:06
To shorten the config I can change "difficulty" and "terrain" to "d" and "t", but as this is only internal representation, I would leave it long to avoid conflicts

**Comment by murggel** [comment] 2021-07-29 19:12
PR is on its way

**Comment by fm-sys** [comment] 2021-07-29 22:51
Fixed with  #11361. Commits are merged back to master, but auto close failed as the "fix #xxxx" statement was only part of the PR description, but not contained in the commit message...

**Closed by fm-sys** 2021-07-29 22:51 UTC
Labels: Bug

**Comment by bekuno** [comment] 2021-07-30 06:07
@fm-sys The rext is in the commit  message.
The auto close works on the master branch, but this PR was target to release and not yet merged back to master.

**Comment by fm-sys** [comment] 2021-07-30 06:47
Oh yes, sorry. You are right. I thought I had explicitly checked this, but it seems that it was too late for me yesterday 😅
