### ISSUE TITLE
Send to C:geo dont send gps data

### ISSUE THREAD

**Issue by Ekcum** [cgeo/cgeo#13329] opened 2022-08-10 12:29 UTC
### Describe your problem!

I've send the first time to my samsung the data from geocaching.com. But it hasn't sended the gps data. The cache isn't shown at the map and the distance is "?". Please fix that.

### How to reproduce?

Make what I discribed

### Reproducible

Unclear

### c:geo Version

2022.07.31

**Comment by SammysHP** [comment] 2022-08-10 14:31
Please fill in the "how to reproduce" section with a step-by-step description of what you did. I don't understand what problem you have.

**Comment by fm-sys** [comment] 2022-08-12 13:01
@Ekcum are you logged in inside cgeo? Otherwise for sure cgeo cannot download caches.

Please add additional information, otherwise we're unfortunately unable to help you and will close this issue.

**Comment by fm-sys** [comment] 2022-08-15 00:22
Closing for now, feel free to add additional information...

**Comment by Ekcum** [comment] 2022-10-11 08:06
I'm locked in. The caches are downloaded but without gps data.

Am Mo., 15. Aug. 2022 um 02:22 Uhr schrieb Florian ***@***.***

**Comment by Lineflyer** [comment] 2022-10-11 08:56
Please kindly send us the c:geo system information, so that we can take a closer look into your problem.

You will find the c:geo system information in: c:geo Menu -> About c:geo -> Swipe to "System".

**Comment by Lineflyer** [comment] 2022-12-29 11:51
Closing again due to missing feedback.

**Closed by Lineflyer** 2022-12-29 11:51 UTC
Labels: Bug, Unverified
