### ISSUE TITLE
Icon parsing with template matching

### ISSUE THREAD

**Issue by SammysHP** [cgeo/cgeo#6204] opened 2016-12-27 16:14 UTC
As described in #6175 we should try template matching to detect the cache type.

1. Find bounding box (easy because of transparent background)
1. Calculate center
1. Template matching, select best match

This is more fuzzy than you current solution (comparing single pixel color), uses shape/texture (not only color) that should detect all cache types and it should also work with partially overlapped icons. Optimizations (generalized feature vector) are possible. Anyway the parsing should be much faster than downloading the tiles.

**Comment by Lineflyer** [comment] 2016-12-27 22:25
Could this also help in determining the cache coordinates?

**Comment by SammysHP** [comment] 2016-12-28 08:05
That depends on the accuracy of the icons and the detection quality of the center (overlapping icons). Another possibility would be to use the coarse coordinates and shift the template to find the best match.

**Comment by mucek4** [comment] 2016-12-28 08:36
Currently we look only for color. We have RGB from 0-255 and parse that really quick. The problem is similar colors.
Template matching works good until caches overlap. As soon a template is overlapped we have a problem.
I have tried my theory: use the same type of parsing, but instead of colors use edges. I made grayscale image and compared shapes. results are really good, however I have some problems with white edges around the image. They are all the same at multiple caches. Will see how it will go.

**Comment by Lineflyer** [comment] 2019-04-23 11:13
Obsolete after #7514 was merged.

**Closed by Lineflyer** 2019-04-23 11:13 UTC
Labels: Feature Request, Live Map, Refactoring
