### ISSUE TITLE
Don't change website language on gc.com

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#13228] opened 2022-06-30 21:20 UTC
### Tell us your idea!

We should consider to implement a language independent parsing of the website of geocaching.com.

AFAIR there have already been ideas in the past to base the parsing on language Independent elements and it would BTW also be a comfort for our users to be able to use the website in their native language.

### What solution would you suggest?

Change the parsing to base on elements not language dependent 

### Is there an alternative?

Make use of the official API (or base all whats possible on the webAPI?)

### Additional Information

@cgeo/team Please refer to c:geo team internal message board for further explanation

Link to #4555 , #167

**Comment by Lineflyer** [comment] 2022-09-11 21:06
@fm-sys 
I finally found some minutes to at least update to latest nightly and use that new switch not to change the language.
You (and others) reported, that there is a problem in such case in certain functions. Up to now I could however not see any problems.

Would you mind to summarize here, what parts/functions of c:geo might fail if the website is not in English according to your experience/tests?

**Comment by fm-sys** [comment] 2022-09-11 22:05
After merging cgeo/cgeo#13381 there will be only two language depended patterns left (we know of)

- Parsing of Travelbug Location
- Owner Name parsing for PM only caches viewed by basic members (we can drop this IMHO, as this information is never displayed anyway)

All other features are (already) working fine with different website languages.

IMHO these two regressions are so small that it would even be accessible acceptable to remove the language switch completely on master.

However, we should adapt our unit tests to test website parsing in at least two different languages... (maybe German and English?)

**Comment by Lineflyer** [comment] 2022-09-12 16:59
> Parsing of Travelbug Location

What exactly do you mean by that.
At this moment I do see (current master, w/o language switch) a problem for the TB status where it seems, that some random string of c:geo pops up instead:

![Screenshot_20220912-185715_cgeo](https://user-images.githubusercontent.com/949669/189713043-bfb2c664-16dd-438b-b956-4c7815bf3e6b.jpg)

**Comment by Lineflyer** [comment] 2022-09-12 19:27
After some days of using c:geo without language switch may I suggest (in order to speed up progress):

Lets negate the switch (= on upgrading to that version the switch to english will be off by default) and start a beta rather soon.
We know of some regressions (under clarification with "server side") which can be considered minor and beta users might provide valuable additional information about possible regressions we have overseen.

Other changes needed before beta:
- Clarify this stange TB parsing result in the screenshot above (better show nothing than such strange info)
- Remove the mentioned parsing of PM-only cache owner information for BM

**Comment by fm-sys** [comment] 2022-09-12 21:26
> Lets negate the switch (= on upgrading to that version the switch to english will be off by default) and start a beta rather soon.

IMHO we can drop the language switch + the corresponding setting completely. It won't make a difference whether we tell users on support to enable the automated language switch or to switch GC to English manually.

**Comment by fm-sys** [comment] 2022-09-13 18:22
> Clarify this stange TB parsing result in the screenshot above (better show nothing than such strange info)

How where you be able to get this result? I was not able to reproduce... The mentioned status field is never shown at my device.

**Comment by Lineflyer** [comment] 2022-09-13 19:50
> > Clarify this stange TB parsing result in the screenshot above (better show nothing than such strange info)
> 
> How where you be able to get this result? I was not able to reproduce... The mentioned status field is never shown at my device.

I have no idea.
Did you try with that trackable code from the screenshot while the website is set to german?

**Comment by Lineflyer** [comment] 2022-09-13 19:54
I will open a dedicated issue to track.

**Comment by Lineflyer** [comment] 2022-09-13 19:59
#13412 and created a label "Language Parsing"

**Comment by fm-sys** [comment] 2022-09-13 20:24
> > How where you be able to get this result? I was not able to reproduce... The mentioned status field is never shown at my device.
> 
> I have no idea. Did you try with that trackable code from the screenshot while the website is set to german?
> 
> Edit: Once I change the language to english and refresh the TB page its back to "Status: Gesehen (4. Juni)". It might therefore require a trackable which has been discovered by your account before.

Yes, that was the clue. Only relevant for trackables discovered by the account.

**Comment by fm-sys** [comment] 2022-09-15 23:19
> > Parsing of Travelbug Location
> 
> What exactly do you mean by that.

It's the "last spotted" information. 

Parsing of "in Cache xy" currently works in English and German (however not in other languages). If the trackable is in the hands of the owner / a different user, this can only be parsed in English language currently.

![grafik](https://user-images.githubusercontent.com/64581222/190524391-1cb7334a-d85e-454c-838d-fb3275a3163a.png)

**Comment by fm-sys** [comment] 2022-09-16 22:26
> Other changes needed before beta:
> 
>     * Clarify this stange TB parsing result in the screenshot above (better show nothing than such strange info)

-> https://github.com/cgeo/cgeo/pull/13422 

>     * Remove the mentioned parsing of PM-only cache owner information for BM
-> https://github.com/cgeo/cgeo/pull/13416 

Both is merged meanwhile, and language switch was completely removed in #13417.

Only regression is parsing of current TB location. If this info cannot be parsed, the row will just be hidden so users might not even realize something is missing. So this is not blocking a new beta IMHO. Still it would be nice to be able to show this info again.

**Comment by moving-bits** [comment] 2022-09-24 08:12
New error on Play Console for the beta version:

java.lang.RuntimeException in
cgeo.geocaching.connector.gc.GCLogin.getServerParameters

io.reactivex.rxjava3.exceptions.UndeliverableException

```
Exception io.reactivex.rxjava3.exceptions.UndeliverableException: The exception could not be delivered to the consumer because it has already canceled/disposed the flow or the exception has nowhere to go to begin with. Further reading: https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#error-handling | java.lang.RuntimeException: java.lang.InterruptedException
  at io.reactivex.rxjava3.plugins.RxJavaPlugins.onError (RxJavaPlugins.java:372)
  at io.reactivex.rxjava3.internal.operators.flowable.FlowableFromCallable.subscribeActual (FlowableFromCallable.java:44)
  at io.reactivex.rxjava3.core.Flowable.subscribe (Flowable.java:15917)
  at io.reactivex.rxjava3.core.Flowable.subscribe (Flowable.java:15863)
  at io.reactivex.rxjava3.internal.operators.flowable.FlowableSubscribeOn$SubscribeOnSubscriber.run (FlowableSubscribeOn.java:82)
  at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run (ScheduledRunnable.java:65)
  at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.call (ScheduledRunnable.java:56)
  at java.util.concurrent.FutureTask.run (FutureTask.java:266)
  at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run (ScheduledThreadPoolExecutor.java:301)
  at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1167)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:641)
  at java.lang.Thread.run (Thread.java:920)
Caused by java.lang.RuntimeException: java.lang.InterruptedException
  at io.reactivex.rxjava3.internal.util.ExceptionHelper.wrapOrThrow (ExceptionHelper.java:46)
  at io.reactivex.rxjava3.internal.observers.BlockingMultiObserver.blockingGet (BlockingMultiObserver.java:89)
  at io.reactivex.rxjava3.core.Single.blockingGet (Single.java:3645)
  at cgeo.geocaching.connector.gc.GCLogin.getServerParameters (GCLogin.java:373)
  at cgeo.geocaching.connector.gc.GCLogin.getWebsiteLanguage (GCLogin.java:311)
  at cgeo.geocaching.utils.SystemInformation.getSystemInformation (SystemInformation.java:120)
  at cgeo.geocaching.about.SystemInformationViewModel.lambda$new$0 (SystemInformationViewModel.java:26)
  at cgeo.geocaching.about.-$$Lambda$SystemInformationViewModel$eg9syRTjtHZIwQOXxjR3G6Wa1GA.call
  at io.reactivex.rxjava3.internal.operators.flowable.FlowableFromCallable.subscribeActual (FlowableFromCallable.java:40)
Caused by java.lang.InterruptedException:
  at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly (AbstractQueuedSynchronizer.java:1024)
  at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly (AbstractQueuedSynchronizer.java:1334)
  at java.util.concurrent.CountDownLatch.await (CountDownLatch.java:232)
  at io.reactivex.rxjava3.internal.observers.BlockingMultiObserver.blockingGet (BlockingMultiObserver.java:86)
```

**Comment by moving-bits** [comment] 2022-09-24 08:15
And a second one, seemingly also related to the changed login routine:

java.net.UnknownHostException in
cgeo.geocaching.network.Network$LoggingInterceptor.intercept

java.lang.RuntimeException

```
Exception java.lang.RuntimeException: LiveData does not handle errors. Errors from publishers should be handled upstream and propagated as state
  at androidx.lifecycle.LiveDataReactiveStreams$PublisherLiveData$LiveDataSubscriber$1.run (LiveDataReactiveStreams.java:264)
  at android.os.Handler.handleCallback (Handler.java:938)
  at android.os.Handler.dispatchMessage (Handler.java:99)
  at android.os.Looper.loopOnce (Looper.java:226)
  at android.os.Looper.loop (Looper.java:313)
  at android.app.ActivityThread.main (ActivityThread.java:8663)
  at java.lang.reflect.Method.invoke
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:567)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1135)
Caused by java.lang.RuntimeException:
  at io.reactivex.rxjava3.internal.util.ExceptionHelper.wrapOrThrow (ExceptionHelper.java:46)
  at io.reactivex.rxjava3.internal.observers.BlockingMultiObserver.blockingGet (BlockingMultiObserver.java:94)
  at io.reactivex.rxjava3.core.Single.blockingGet (Single.java:3645)
  at cgeo.geocaching.connector.gc.GCLogin.getServerParameters (GCLogin.java:373)
  at cgeo.geocaching.connector.gc.GCLogin.getWebsiteLanguage (GCLogin.java:311)
  at cgeo.geocaching.utils.SystemInformation.getSystemInformation (SystemInformation.java:120)
  at cgeo.geocaching.about.SystemInformationViewModel.lambda$new$0 (SystemInformationViewModel.java:26)
  at cgeo.geocaching.about.-$$Lambda$SystemInformationViewModel$eg9syRTjtHZIwQOXxjR3G6Wa1GA.call
  at io.reactivex.rxjava3.internal.operators.flowable.FlowableFromCallable.subscribeActual (FlowableFromCallable.java:40)
  at io.reactivex.rxjava3.core.Flowable.subscribe (Flowable.java:15917)
  at io.reactivex.rxjava3.core.Flowable.subscribe (Flowable.java:15863)
  at io.reactivex.rxjava3.internal.operators.flowable.FlowableSubscribeOn$SubscribeOnSubscriber.run (FlowableSubscribeOn.java:82)
  at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run (ScheduledRunnable.java:65)
  at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.call (ScheduledRunnable.java:56)
  at java.util.concurrent.FutureTask.run (FutureTask.java:266)
  at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run (ScheduledThreadPoolExecutor.java:301)
  at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1167)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:641)
  at java.lang.Thread.run (Thread.java:920)
Caused by java.net.UnknownHostException:
  at java.net.Inet6AddressImpl.lookupHostByName (Inet6AddressImpl.java:156)
  at java.net.Inet6AddressImpl.lookupAllHostAddr (Inet6AddressImpl.java:103)
  at java.net.InetAddress.getAllByName (InetAddress.java:1152)
  at okhttp3.Dns$Companion$DnsSystem.lookup (Dns.kt:49)
  at okhttp3.internal.connection.RouteSelector.resetNextInetSocketAddress (RouteSelector.kt:164)
  at okhttp3.internal.connection.RouteSelector.nextProxy (RouteSelector.kt:129)
  at okhttp3.internal.connection.RouteSelector.next (RouteSelector.kt:71)
  at okhttp3.internal.connection.ExchangeFinder.findConnection (ExchangeFinder.kt:205)
  at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection (ExchangeFinder.kt:106)
  at okhttp3.internal.connection.ExchangeFinder.find (ExchangeFinder.kt:74)
  at okhttp3.internal.connection.RealCall.initExchange$okhttp (RealCall.kt:255)
  at okhttp3.internal.connection.ConnectInterceptor.intercept (ConnectInterceptor.kt:32)
  at okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.kt:109)
  at okhttp3.internal.cache.CacheInterceptor.intercept (CacheInterceptor.kt:95)
  at okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.kt:109)
  at okhttp3.internal.http.BridgeInterceptor.intercept (BridgeInterceptor.kt:83)
  at okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.kt:109)
  at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept (RetryAndFollowUpInterceptor.kt:76)
  at okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.kt:109)
  at cgeo.geocaching.network.Network$LoggingInterceptor.intercept (Network.java:394)
  at okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.kt:109)
  at cgeo.geocaching.network.Network$HeadersInterceptor.intercept (Network.java:378)
  at okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.kt:109)
  at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp (RealCall.kt:201)
  at okhttp3.internal.connection.RealCall$AsyncCall.run (RealCall.kt:517)
Caused by android.system.GaiException: android_getaddrinfo failed: EAI_NODATA (No address associated with hostname)
  at libcore.io.Linux.android_getaddrinfo
  at libcore.io.ForwardingOs.android_getaddrinfo (ForwardingOs.java:136)
  at libcore.io.BlockGuardOs.android_getaddrinfo (BlockGuardOs.java:221)
  at libcore.io.ForwardingOs.android_getaddrinfo (ForwardingOs.java:136)
  at java.net.Inet6AddressImpl.lookupHostByName (Inet6AddressImpl.java:135)
```

**Comment by fm-sys** [comment] 2022-09-27 18:49
I was able to reproduce the issue. The crash sometimes happens if you manage to view the sys info before the login process gets started. This may happen e.g. after viewing the changelog. However, it doesn't seem to happen always.

```
09-27 20:36:46.733 22968 23026 W cgeo    : [OkHttp] Failure (11132 ms) GET https://www.geocaching.com/play/serverparameters/params (java.net.SocketTimeoutException: failed to connect to www.geocaching.com/63.251.163.200 (port 443) from /192.168.2.111 (port 43318) after 30000ms: isConnected failed: ETIMEDOUT (Connection timed out))
09-27 20:36:46.735 22968 22968 I BlockMonitor: dispatchingThrewException In MainThread
09-27 20:36:46.735 22968 22968 D AndroidRuntime: Shutting down VM
09-27 20:36:46.741 22968 22968 I QarthLog: [PatchStore] createDisableExceptionQarthFile
09-27 20:36:46.741 22968 22968 I QarthLog: [PatchStore] create disable file for cgeo.geocaching uid is 10865
--------- beginning of crash
09-27 20:36:46.754 22968 22968 E AndroidRuntime: FATAL EXCEPTION: main
09-27 20:36:46.754 22968 22968 E AndroidRuntime: Process: cgeo.geocaching, PID: 22968
09-27 20:36:46.754 22968 22968 E AndroidRuntime: java.lang.RuntimeException: LiveData does not handle errors. Errors from publishers should be handled upstream and propagated as state
09-27 20:36:46.754 22968 22968 E AndroidRuntime: 	at androidx.lifecycle.LiveDataReactiveStreams$PublisherLiveData$LiveDataSubscriber$1.run(LiveDataReactiveStreams.java:264)
09-27 20:36:46.754 22968 22968 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:888)
09-27 20:36:46.754 22968 22968 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:100)
09-27 20:36:46.754 22968 22968 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:213)
09-27 20:36:46.754 22968 22968 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8178)
09-27 20:36:46.754 22968 22968 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
09-27 20:36:46.754 22968 22968 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
09-27 20:36:46.754 22968 22968 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)
09-27 20:36:46.754 22968 22968 E AndroidRuntime: Caused by: java.lang.RuntimeException: java.net.SocketTimeoutException: failed to connect to www.geocaching.com/63.251.163.200 (port 443) from /192.168.2.111 (port 43318) after 30000ms: isConnected failed: ETIMEDOUT (Connection timed out)
09-27 20:36:46.754 22968 22968 E AndroidRuntime: 	at io.reactivex.rxjava3.internal.util.ExceptionHelper.wrapOrThrow(ExceptionHelper.java:46)
09-27 20:36:46.754 22968 22968 E AndroidRuntime: 	at io.reactivex.rxjava3.internal.observers.BlockingMultiObserver.blockingGet(BlockingMultiObserver.java:94)
09-27 20:36:46.754 22968 22968 E AndroidRuntime: 	at io.reactivex.rxjava3.core.Single.blockingGet(Single.java:3645)
09-27 20:36:46.754 22968 22968 E AndroidRuntime: 	at cgeo.geocaching.connector.gc.GCLogin.getServerParameters(GCLogin.java:373)
09-27 20:36:46.754 22968 22968 E AndroidRuntime: 	at cgeo.geocaching.connector.gc.GCLogin.getWebsiteLanguage(GCLogin.java:311)
09-27 20:36:46.754 22968 22968 E AndroidRuntime: 	at cgeo.geocaching.utils.SystemInformation.getSystemInformation(SystemInformation.java:120)
09-27 20:36:46.754 22968 22968 E AndroidRuntime: 	at cgeo.geocaching.about.SystemInformationViewModel.lambda$new$0(SystemInformationViewModel.java:26)
09-27 20:36:46.754 22968 22968 E AndroidRuntime: 	at cgeo.geocaching.about.-$$Lambda$SystemInformationViewModel$eg9syRTjtHZIwQOXxjR3G6Wa1GA.call(Unknown Source:2)
09-27 20:36:46.754 22968 22968 E AndroidRuntime: 	at io.reactivex.rxjava3.internal.operators.flowable.FlowableFromCallable.subscribeActual(FlowableFromCallable.java:40)
09-27 20:36:46.754 22968 22968 E AndroidRuntime: 	at io.reactivex.rxjava3.core.Flowable.subscribe(Flowable.java:15917)
09-27 20:36:46.754 22968 22968 E AndroidRuntime: 	at io.reactivex.rxjava3.core.Flowable.subscribe(Flowable.java:15863)
09-27 20:36:46.754 22968 22968 E AndroidRuntime: 	at io.reactivex.rxjava3.internal.operators.flowable.FlowableSubscribeOn$SubscribeOnSubscriber.run(FlowableSubscribeOn.java:82)
09-27 20:36:46.754 22968 22968 E AndroidRuntime: 	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:65)
09-27 20:36:46.754 22968 22968 E AndroidRuntime: 	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:56)
09-27 20:36:46.754 22968 22968 E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
09-27 20:36:46.754 22968 22968 E AndroidRuntime: 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
09-27 20:36:46.754 22968 22968 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
09-27 20:36:46.754 22968 22968 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
09-27 20:36:46.754 22968 22968 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:929)
09-27 20:36:46.754 22968 22968 E AndroidRuntime: Caused by: java.net.SocketTimeoutException: failed to connect to www.geocaching.com/63.251.163.200 (port 443) from /192.168.2.111 (port 43318) after 30000ms: isConnected failed: ETIMEDOUT (Connection timed out)
09-27 20:36:46.754 22968 22968 E AndroidRuntime: 	at libcore.io.IoBridge.isConnected(IoBridge.java:284)
09-27 20:36:46.754 22968 22968 E AndroidRuntime: 	at libcore.io.IoBridge.connectErrno(IoBridge.java:193)
09-27 20:36:46.754 22968 22968 E AndroidRuntime: 	at libcore.io.IoBridge.connect(IoBridge.java:135)
09-27 20:36:46.754 22968 22968 E AndroidRuntime: 	at java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:142)
09-27 20:36:46.754 22968 22968 E AndroidRuntime: 	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:390)
09-27 20:36:46.754 22968 22968 E AndroidRuntime: 	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:230)
09-27 20:36:46.754 22968 22968 E AndroidRuntime: 	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:212)
09-27 20:36:46.754 22968 22968 E AndroidRuntime: 	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:436)
09-27 20:36:46.754 22968 22968 E AndroidRuntime: 	at java.net.Socket.connect(Socket.java:621)
09-27 20:36:46.754 22968 22968 E AndroidRuntime: 	at okhttp3.internal.platform.Platform.connectSocket(Platform.kt:128)
09-27 20:36:46.754 22968 22968 E AndroidRuntime: 	at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.kt:295)
09-27 20:36:46.754 22968 22968 E AndroidRuntime: 	at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:207)
09-27 20:36:46.754 22968 22968 E AndroidRuntime: 	at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:226)
09-27 20:36:46.754 22968 22968 E AndroidRuntime: 	at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106)
09-27 20:36:46.754 22968 22968 E AndroidRuntime: 	at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74)
09-27 20:36:46.755 22968 22968 E AndroidRuntime: 	at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255)
09-27 20:36:46.755 22968 22968 E AndroidRuntime: 	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)
09-27 20:36:46.755 22968 22968 E AndroidRuntime: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
09-27 20:36:46.755 22968 22968 E AndroidRuntime: 	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
09-27 20:36:46.755 22968 22968 E AndroidRuntime: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
09-27 20:36:46.755 22968 22968 E AndroidRuntime: 	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
09-27 20:36:46.755 22968 22968 E AndroidRuntime: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
09-27 20:36:46.755 22968 22968 E AndroidRuntime: 	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
09-27 20:36:46.755 22968 22968 E AndroidRuntime: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
09-27 20:36:46.755 22968 22968 E AndroidRuntime: 	at cgeo.geocaching.network.Network$LoggingInterceptor.intercept(Network.java:394)
09-27 20:36:46.755 22968 22968 E AndroidRuntime: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
09-27 20:36:46.755 22968 22968 E AndroidRuntime: 	at cgeo.geocaching.network.Network$HeadersInterceptor.intercept(Network.java:378)
09-27 20:36:46.755 22968 22968 E AndroidRuntime: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
09-27 20:36:46.755 22968 22968 E AndroidRuntime: 	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
09-27 20:36:46.755 22968 22968 E AndroidRuntime: 	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:517)
09-27 20:36:46.755 22968 22968 E AndroidRuntime: 	... 3 more
09-27 20:36:46.755 22968 22968 E AndroidRuntime: Caused by: android.system.ErrnoException: isConnected failed: ETIMEDOUT (Connection timed out)
09-27 20:36:46.755 22968 22968 E AndroidRuntime: 	at libcore.io.IoBridge.isConnected(IoBridge.java:275)
09-27 20:36:46.755 22968 22968 E AndroidRuntime: 	... 32 more

**Comment by geocachermgo** [comment] 2022-10-01 09:17
No issue or me, since I started when only English was available and never switched. But I think that was a nuisance for many users. So thank's for the development!

**Comment by fm-sys** [comment] 2022-10-09 19:20
Just this evening we have discovered that there are some date parsing problems. It's not directly related to the language switch, however we need to have a look how we can work around it.

Currently, we call https://www.geocaching.com/play/serverparameters/params and take the date format as parsing target for websites we scrape, e.g. `"dateFormat": "dd.MM.yy"`. However, there seem to be parsing problems at least with `dd.MM.yy` while most other formats are working fine. Needs to be analyzed further.

**Comment by fm-sys** [comment] 2022-10-09 19:31
Sorry. It might be that this was a false positive. After restarting cgeo the dates were parsed correctly again. However, we should test this for more special formats as well.

Luckily, they haven't implemented language specific date formats. E.g. `dd.MMM.yyyy` results in `24.May.2021` (not "Mai") even if language is set to German.

|Normal|After language change|Restart cgeo after language change|
-|-|-
![Screenshot_20221009_211938_cgeo geocaching](https://user-images.githubusercontent.com/64581222/194775639-6e21ba71-4bbe-44a9-84e9-cc765a623042.jpg)|![Screenshot_20221009_211956_cgeo geocaching](https://user-images.githubusercontent.com/64581222/194775641-c74095b4-bc1f-4ccc-a2f5-d68905df2ae5.jpg)|![Screenshot_20221009_211938_cgeo geocaching](https://user-images.githubusercontent.com/64581222/194775639-6e21ba71-4bbe-44a9-84e9-cc765a623042.jpg)


Just for reference, how to change the GC date format:

![grafik](https://user-images.githubusercontent.com/64581222/194775874-bf8c7ea2-038d-4ccd-a779-c3ca14b3a051.png)

**Comment by ztNFny** [comment] 2022-10-09 19:32
Does restarting cgeo not reset the date format?

**Comment by fm-sys** [comment] 2022-10-09 19:40
> Does restarting cgeo not reset the date format?

Nope, and it never had AFAIK. Only the language was switched to English before the recent changes... However it is quite convenient to just use the date pattern provided in the [serverparameters](https://www.geocaching.com/play/serverparameters/params) for parsing.

**Comment by Lineflyer** [comment] 2022-10-09 20:14
We once also set the date format (years ago) AFAIR. But the improved implementation later obtained the used format during login and used that in parsing.

@fm-sys 
Maybe you changed the date format on the website during run-time of c:geo and it was only detected by c:geo on next login?

**Comment by Lineflyer** [comment] 2022-10-09 20:15
BTW:
No such reports from beta users...so I guess there will be no problem there...but a bit of testing might still be helpful to verify.

**Comment by fm-sys** [comment] 2022-10-09 20:44
> @fm-sys
Maybe you changed the date format on the website during run-time of c:geo and it was only detected by c:geo on next login?

Yes, most likely cgeo was still running in background so no new login was triggered. This is still an issue but probably we don't want to fix it as it's only for a short period of time and users won't charge the date format frequently anyway.

**Comment by Lineflyer** [comment] 2022-10-09 20:58
I agree. No need to fix.

**Comment by Lineflyer** [comment] 2022-10-18 20:43
I guess this can be closed as we have dedicated issues for the regression. OK?

**Comment by moving-bits** [comment] 2022-10-21 20:30
We can either keep this issue open as a reminder that we have to adapt trackable owner and status parsing after HQ have implemented their part, or we open a separate issue for that.

**Comment by Lineflyer** [comment] 2022-10-21 23:17
I would be a friend of opening dedicated issues instead of this broad one.
As you can probably better name/describe the remaining issue I would appreciate if you open a dedicated for the TB and close this one afterwards as time permits.

**Comment by moving-bits** [comment] 2022-10-22 08:55
Ok, I've created #13552 for it, so let's close here

**Closed by moving-bits** 2022-10-22 08:55 UTC
Labels: Feature Request, Prio - High, Language Parsing
