### ISSUE TITLE
Found status not updated when logging a visit

### ISSUE THREAD

**Issue by jonas-koeritz** [cgeo/cgeo#7664] opened 2019-06-06 22:06 UTC
When logging a **saved**  cache the found status doesn't always get updated on the map, the cache details or the pop-up.
This is somewhat reproducible but I cannot tell what's the cause right now.
I'm going to further investigate this.

**Comment by Lineflyer** [comment] 2019-06-06 22:50
Maybe related to #6524

**Comment by Lineflyer** [comment] 2019-06-07 09:10
If you try to reproduce: It might depend on 
- The map type
- Live mode or not
- Logged from popup or cache details

**Comment by jakedot** [comment] 2019-06-07 09:46
It's just as unreliable for `unsaved` caches isn't it?

**Comment by jonas-koeritz** [comment] 2019-06-07 14:34
@jakedot I always save caches before going to locations. But thanks for the input, I'll consider that too!

**Comment by jakedot** [comment] 2019-06-07 19:43
My assumtion and experience im the past was that this behaviour was worse, or even only present, for unsaved caches. Thus thw comment.

**Comment by jonas-koeritz** [comment] 2019-07-23 20:24
I think I'm finally on to something, I just logged a cache and all other log entries have vanished from the cache details, my own log is still there but the cache is not marked as found. There has to be something going on with updating the cache in the database/the cache.

**Comment by Lomanic** [comment] 2019-07-24 09:38
It's another issue I think, it was previously reported, might be some race condition between logging in and retrieving the geocache logs according to https://github.com/cgeo/cgeo/issues/6927#issuecomment-362854888.

**Comment by jonas-koeritz** [comment] 2019-07-24 09:49
I still can't reproduce the issue with not marked as found caches on the map when debugging. Must be some kind of race condition, where is the code that loads the caches found status to display it on the map or on the details page?

**Comment by jonas-koeritz** [comment] 2019-07-24 10:02
> It's another issue I think, it was previously reported, might be some race condition between logging in and retrieving the geocache logs according to [#6927 (comment)](https://github.com/cgeo/cgeo/issues/6927#issuecomment-362854888).

I don't think so, they are already loaded and seem to disappear after sending my log. This might be unrelated.

**Comment by Lineflyer** [comment] 2019-07-28 20:16
From my personal experience I would also think its kind of a race condition.
I have also seen this very rarely while logging with c:geo. AFAIR it sometimes happens if I log from map popup or from another place of the app which is not the "default flow" from cache details.

**Comment by jonas-koeritz** [comment] 2019-08-15 15:10
I think this should be adressed after we have finished the migration to SDK28, Google Maps V2 and AndroidX. I already planned to have a look at the database layer then.

**Comment by Lineflyer** [comment] 2020-09-23 11:54
IMHO a duplicate of #9046, where a reproducible way is described.

**Closed by Lineflyer** 2020-09-23 11:54 UTC
Labels: Bug, Unverified
