### ISSUE TITLE
Delay just after selecting "Refresh all"

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#4596] opened 2015-01-07 21:19 UTC
With version 2015.01.07-RC I can see a new behavior:
When selecting Menu - "Refresh all" I experience a short delay before the refresh starts and the progress window is shown.
Subjectively (I have to test) it rises with the amount of caches on the list to be refreshed.
For a list of 100 caches it is a noticeable delay of approx. 1 second.

**Comment by Cappa-d** [comment] 2015-01-11 21:05
@Lineflyer :  offtopic "nice you have the big hotel key TB in your hands atm"

Regarding the described behaviour I can confirm it. I usually load PQ with between 300 and 1000 caches on my mobile device (S4 Mini - Android 4.4.) and since the last update what you described happens.

If it's just 4 caches (my own hides) it just takes a second or so until the loading screen appears.

If I load the 1000 caches PQ and try to refresh them it takes something like 10 or 15 seconds until the loading bar apears and even if its there it takes ages.

Do you need something else? I am happy to provide details...

**Comment by Lineflyer** [comment] 2015-01-11 22:17
@Cappa-d offtopic: Thats a funny coincidence. Is this yours? Either I will take it abroad end of Feb or leave it at an airport before that date.

Just reading your doublecheck:
So you say, that this delay of 15 seconds is also happening on version 2014.12.22 ?

**Comment by Cappa-d** [comment] 2015-01-12 08:21
@Lineflyer offtopic: nope not mine just one I had months ago traveling with me

tests run in version 2014.12.22 while i am typing

4 stored caches: no delay until progress bar is shown -- 7 secs until progress is shown
306 stored caches: 5 secs delay until progress bar is shown -- more than 7 secs until any progress is shown
1009 stored caches: 19 secs delay until progress bar is shown -- 7 secs until any progress is shown

device: s4 mini
os: kitkat 4.4.2

anything else you need?

**Comment by samueltardieu** [comment] 2015-01-12 08:31
It looks like this depends on whether you request the static maps or not. If you do, caches are partitioned in two categories (those that don't have static maps on the device yet and those that do) in order to refresh caches without static maps first.

I haven't checked yet, but it is possible that the check happens somewhere on the UI thread and takes a long time to run.

**Comment by Lineflyer** [comment] 2015-01-12 09:51
@Cappa-d 
Can you do two more tests:
- Try switching off static maps (Menu - Settings - Offline-Data - Disable first two options) and try the refresh again with version 2014.12.22
- Update to the current RC-version (to be found here: http://www.cgeo.org/cgeo-RC.apk) and try again with and without static map loading

With these tests we should be able to see if it is caused by static maps and if the behavior changed between both versions.

**Comment by samueltardieu** [comment] 2015-01-12 10:29
The delay is at least here since September 2013, where I refactored the area, which already did a similar job, so it has probably been there for a long time.

**Comment by Cappa-d** [comment] 2015-01-12 11:29
@Lineflyer Sure will do tonight once I am within reach of my Wlan again ;)

Will post results here.

@samueltardieu It might have changed  awhile ago, but the described behaviour shows just recently. As I am using my device as main caching tool I usually load new PQ every other week, Did not notice this behaviour before and I am sure I have not changed any settings recently. Only thing was display found / owned caches.

**Comment by samueltardieu** [comment] 2015-01-12 12:03
Reopening for field testing by @Lineflyer before merging into `release`.

**Comment by samueltardieu** [comment] 2015-01-12 12:51
Merged to release per @Lineflyer IRC request.

**Closed by samueltardieu** 2015-01-12 12:51 UTC
Labels: Bug, low, Performance

**Comment by Cappa-d** [comment] 2015-01-12 19:55
ok guess the testing is not needed or at least no upgrade to the RC.

With the first two options disabled the delay is gone.
