### ISSUE TITLE
Don't show stages or other waypoints of hidden but saved caches

### ISSUE THREAD

**Issue by vsandre** [cgeo/cgeo#6635] opened 2017-07-13 07:58 UTC
##### Detailed steps causing the problem:
- Save an already found or own Cache in a List (probably also for deactived caches)
- Go to Live Map
- select the option "Hide own/found caches"

##### Actual behavior after performing these steps:
- The Cache icons disapear.
- But the additional waypoints, e.g. Stages, Parking Lots ... stay visible

##### Expected behavior after performing these steps:
If you don't want to see your already found caches, the stages should not be visible too.

##### Version of c:geo used:
2017.05.22

##### Is the problem reproducible for you?
Yes

##### System information:
```
--- System information ---
Device: SM-G900F
Android version 6.0.1
```

##### Other comments and remarks:
-

**Comment by Lineflyer** [comment] 2017-07-17 20:23
Thanks for reporting but duplicate of #2558

**Closed by Lineflyer** 2017-07-17 20:23 UTC

**Comment by Lineflyer** [comment] 2017-07-17 20:25
wow...automatic marking of duplicate issues when using "duplicate of ...." Thanks Github!

**Comment by pstorch** [comment] 2017-07-17 20:29
yes, that is rather new
