### ISSUE TITLE
Offline Logging alongside Online Logging

### ISSUE THREAD

**Issue by brivars** [cgeo/cgeo#7685] opened 2019-06-19 02:17 UTC
**I suggest enabling Offline Logging (specifically the "One Click Offline Log" button) to be able to be activated at the same time as Online Logging (normal "Log Visit" option).**

Currently, it is one or the other. and to switch, I need to go to settings every time and check or uncheck the "Offline Logging" box.

**Why is that an issue?**
In my usage case (which I can only assume is how number of other cachers would use it) I am using offline logging when I'm out on a multi-day geocaching missions where I'm potentially actually offline ranging to simple evening missions around town where I'd find more than one cache. After caching I then submit the field notes to drafts and log caches from my PC.
But I also use the built-in online logging option often enough, usually when I'm logging an FTF or just getting a single cache, or any case where there is time after the find to write a substantial log.
So I often find myself needing to switch between the two options (as the normal Log Visit button is replaced with the OCOL button and vice versa), which involves dropping where I'm at, going back to main menu, going to settings and changing it. 

**I'm proposing to add another check-box in the Logging settings called "Online Logging".
By default, that would be enabled and "Offline Logging" disabled, making things appear exactly as they are now by default** (you just have "Log visit" in your cache menu).

But now there would be an option to enable them both - when both boxes checked, there would be both "Log Visit" and "One Click Offline Log" option. People who still want to just use the offline option could uncheck the Online Logging and only use the offline one, same as now.

**Comment by brivars** [comment] 2019-06-19 02:39
Here is an artists' impression on how it would look like 😃 
![Imgur](https://i.imgur.com/bo5OQm0.png)

**Comment by SammysHP** [comment] 2019-06-19 06:45
But you can choose "log online" in the "one click offline log" menu. It opens the logging window where you can select type and date, enter your log and use the "send" button to log online.

**Comment by Lomanic** [comment] 2019-06-19 07:27
This submenu is called "Log Visit" in English and it is not obvious what it does indeed.

**Comment by brivars** [comment] 2019-06-19 09:45
> But you can choose "log online" in the "one click offline log" menu. It opens the logging window where you can select type and date, enter your log and use the "send" button to log online.

I was blind but now I see.
There is the option there indeed.

I still think that if it was the way I'm suggesting it would be much less ambiguous and would make life a bit easier but I'm happier than I was before because I won't need to go through the settings every time, now it will just be that one tiny extra step every time I want to log directly.

**Comment by Lineflyer** [comment] 2019-06-19 09:52
I will take a look if we can easily change the string (e.g. append "online") to make the meaning a bit clearer.

**Comment by Lomanic** [comment] 2019-06-19 10:25
Or something like "Write a detailed log"? A user doesn't have to send the log online in fact.

**Comment by SammysHP** [comment] 2019-06-19 15:03
Correct. Often I add some notes, store it offline and write an extended log at home.

What about "edit log"?

**Comment by rsudev** [comment] 2019-06-19 17:20
The 'online' notion is correct in this case, as (AFAIR) we request the log page from gc.com (it is different for other connectors) to check available log types and prepare sending the log. I think writing and saving a log will work even without connection, but the dialog expects the data to be available.

**Comment by SammysHP** [comment] 2019-06-19 18:03
> but the dialog expects the data to be available.

Only if you want to post the log online. If the log page cannot be retrieved, c:geo will provide default log types and an empty inventory.

**Comment by Lineflyer** [comment] 2020-09-23 12:00
Closing here as a workaround for the issue owners usecase was provided and no other easy fix possible

**Closed by Lineflyer** 2020-09-23 12:00 UTC
Labels: Feature Request

**Comment by Lomanic** [comment] 2020-09-23 16:48
I don't think that's the issue is closed: UX is not so great, it's not obvious that the "Log Visit" entry is for a detailed log (entering text, changing log type interactively) compared to the Quick logs. Should it be its own issue?
