### ISSUE TITLE
Premium caches are not visible in search result for basic users (degrade)

### ISSUE THREAD

**Issue by YraFyra** [cgeo/cgeo#11508] opened 2021-08-22 05:38 UTC
### Describe your problem!

Search result does not contain Premium only caches (PO)  anymore, behavior changed with the introduction of new search.

I'm a basic member and PO are never listed after the recent change to searching. PO has been an extra challenge to me (you don't know the hint nor the exact location, but I have still been able to find many of them...) Also knowing about them helps a lot when placing a new cache. Logging a PO cache (as part of a group) is also harder.

### How to reproduce?

Login as a Basic member.
Perform any type of search (nearby, keyword, hidden by, ...)

### Actual result after these steps?

Search result does not show PO caches.

### Expected result after these steps?

PO caches should be listed, like they used to be.

### Reproducible

Yes

### c:geo Version

2021.08.15

### Additional Information

PO is still visible on https://www.geocaching.com/seek/nearest.aspx where are these types of searches are possible.

**Comment by eddiemuc** [comment] 2021-08-22 06:06
Duplicate of #11488.

Problem is fixed but not yet released (except in the nightlies of course)

**Closed** 2021-08-22 06:06 UTC
Labels: Bug, Unverified

**Comment by YraFyra** [comment] 2021-08-22 06:41
Nice. I wait for next release.
Thank you!
