### ISSUE TITLE
[NUMBER] off by one in Twitter backend

### ISSUE THREAD

**Issue by Natureshadow** [cgeo/cgeo#4690] opened 2015-02-16 23:20 UTC
The [NUMBER] placeholder is off by one in Twitter.

I suppose that results from the way the value is formed in the tag engine, which I suspect to be $count+1 because the soon to be published log is one number higher than the current found count. The Twitter backend is called after logging, when $count was already incremented, resulting in the off-by-one bug.

**Comment by Lineflyer** [comment] 2015-02-17 14:42
Duplicate of #3392

**Closed by Lineflyer** 2015-02-17 14:42 UTC
Labels: Bug
