### ISSUE TITLE
UnifiedMap: Black boxes and other artifacts

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#15100] opened 2023-12-26 11:50 UTC
### Describe your problem!

This strange behavior is like 90% reproducible on my device:
Once I select "Enable live" on the map of a single cache some map elements get black and stay like that.

Additionally you might notice in the video below, that the zoom "jumps" once I enable live.

### How to reproduce?

- Open cache details
- Long tap compass rose to open cache map
- Select "Enable live" from menu

### Actual result after these steps?

Video:
https://github.com/cgeo/cgeo/assets/949669/ba2eaaee-0216-433a-96d5-b41078e1f37d

### Expected result after these steps?

Map should stay at same zoom and all map elements should stay visible

### Reproducible

Unclear

### c:geo Version

2023.12.26-NB

### System information

```text
Android 13
Germany OAM v5
Elevate theme
Map design: City
```

**Comment by devemux86** [comment] 2023-12-26 12:15
There were reports for multiple maps (not supported) or not properly destroy / re-initialize map (e.g. in fragments):
- https://github.com/mapsforge/vtm/issues/281

**Comment by moving-bits** [comment] 2023-12-27 08:52
Also reported on support, ticket 498670

**Comment by moving-bits** [comment] 2024-01-05 20:13
probably related to #15108

**Comment by moving-bits** [comment] 2024-01-05 20:56
> There were reports for multiple maps (not supported) or not properly destroy / re-initialize map (e.g. in fragments):
> 
>     * [Map renders with black street labels, stops rendering, using two map instances on Android mapsforge/vtm#281](https://github.com/mapsforge/vtm/issues/281)

@devemux86 
We use a single map fragment for VTM only.

But maybe we are missing to call some lifecycle method?
- We call mMapView.xxx for xxx = { `onResume()`, `onPause()` and `onDestroy()` }
- On switching map providers we call `mMap.clearMap()`

**Comment by devemux86** [comment] 2024-01-06 17:21
@moving-bits 

If it helps, there is a fragment sample in vtm-android-example.
Look for the FragmentActivity and [MapFragment](https://github.com/mapsforge/vtm/blob/master/vtm-android-example/src/org/oscim/android/test/MapFragment.java) classes.

**Comment by moving-bits** [comment] 2024-01-06 21:43
Thanks for the pointer. I've tried to align the two example files to our implementation, and they look mostly similar (fragment calling the lifecycle methods as described above). One significant difference is, that we recreate the fragment in `onCreate()`, but even if I let it recreate only if there has been no (VTM) fragment before, behavior does not seem to change.

I have been able to reproduce the black boxes using the following way (in the emulator):
- open VTM with OAM Berlin map and Elevate:Elevate theme (using a zipped theme file)
- go to Berlin, Alexanderplatz
- do a fast combination of repeatedly
  - zooming in/out
  - rotate the map
  - switch screen on/off
  (for maybe 10 seconds)

Then, at some point, black boxes start appearing, but only in certain zoom levels for me. A more prominent example is this:

|img 1|img 2|
|---|---|
|![image](https://github.com/cgeo/cgeo/assets/3754370/c6da3d01-506b-4e52-97d6-d4b037b29e81)|![image](https://github.com/cgeo/cgeo/assets/3754370/c61c8931-3b9c-43d6-b0fe-601b85b9b121)|

It's not a label that's missing in this case, but some graphical elements (cross hatches?), see img 1.

If I zoom out a bit, these black boxes disappear, but a single one appears, at a different (but nearby) place, see red circled black box in img 2.

If I zoom out even further, this box disappears again, but some of the others reappear. Strange.

(This is all without further switching off the screen etc. or otherwise forcing any of the lifecycle methods jumping in.)

**Comment by moving-bits** [comment] 2024-01-15 21:57
Further observations:

- I've tried removing the old fragment first, then creating the new one => no change in my test case (as to be expected, since I do not switch tileproviders; from fragment lifecycle methods, only onStart/onResume are being called, but not onPause/onDestroyView
- I cannot reproduce it with my test case if I'm using "combined" map mode, only if I select a single offline map (in my test case: Berlin (OAM) with Elevate/Elevate theme)
- When I'm able to reproduce it, it's a specific texture (see screenshots above). The specific scenario could be reproduced in different emulators (and by different persons meanwhile) with a 100% probability when using UnifiedMap - but not with eg. Cruiser app or VTM example code.
- I have not yet been able to reproduce the issue shown in the video - in that case it looks like map symbols lead to black boxes (and we had yet different reports showing missing text labels - which I haven't yet been able to reproduce, either)

**Comment by fm-sys** [comment] 2024-01-15 22:07
> only onStart/onResume are being called, but not onPause/onDestroyView

The destroy methods are not called inside the fragment which gets removed? If I understand your debug notes correctly, this could be the root cause of the black box issue... I may also find time to debug into it tomorrow.

**Comment by moving-bits** [comment] 2024-01-16 09:49
> > only onStart/onResume are being called, but not onPause/onDestroyView
> 
> The destroy methods are not called inside the fragment which gets removed?

This is to be expected, as my test case does not involve fragment changes:

- open UnifiedMap with Berlin OAM + Elevevate theme
- go to Berlin, Alexanderplatz
- zoom in & out in rapid succession (eg. by douple-tap + hold to enter zoom mode, then move your finger up and down rapidly)

If I change the map (tile provider), then the other fragment lifecycle methods are involved.

**Comment by fm-sys** [comment] 2024-01-16 16:28
@devemux86 We still have the "black boxes" problem with VTM and are really lost meanwhile how we could fix this. All lifecycle methods are implemented as shown in [MapFragment](https://github.com/mapsforge/vtm/blob/master/vtm-android-example/src/org/oscim/android/test/MapFragment.java) class. Furthermore, it only happens if viewing specific places (like Berlin Alexanderplatz) with specific themes enabled (Elevate). But it's 100% reproducible in the emulator as well as on real devices.

Any idea what could cause this, or anything we could check or debug? Thank you very much!

**Comment by devemux86** [comment] 2024-01-16 17:07
This looks like re-initialization of OpenGL. It appeared in the past with double map views.
Fragments might cause the above side effect > multiple map views > re-initialize OpenGL.

Elevate is a Mapsforge theme, VTM converts some specific rules.
If the artifacts are permanent, perhaps it's https://github.com/mapsforge/vtm/issues/985.

In any case maybe a different approach could be used if want to use fragments.
Create MapView once on parent activity and show / hide it in the required layout.

**Comment by fm-sys** [comment] 2024-01-17 06:21
I think it's most likely related to the render theme, as it happens as well if the VTM map view gets initialized for the very first time. 

Do we have to do anything special for converting the mapsforge theme to VTM, or is it done internally by default? I'm asking because Cruiser does render the very same version of elevation theme without any problems...

**Comment by devemux86** [comment] 2024-01-17 08:55
> Do we have to do anything special for converting the mapsforge theme to VTM, or is it done internally by default?

Everything is processed internally in [XmlThemeBuilder](https://github.com/mapsforge/vtm/blob/master/vtm/src/org/oscim/theme/XmlThemeBuilder.java), some Mapsforge rules are converted, e.g. [here](https://github.com/mapsforge/vtm/blob/master/vtm/src/org/oscim/theme/XmlThemeBuilder.java#L633-L704).
There is a related discussion in https://github.com/mapsforge/vtm/issues/1005

Cruiser uses the latest VTM snapshot version.
If it works there, then it could be a fragment issue or something else.

**Comment by eddiemuc** [comment] 2024-01-17 17:53
> This looks like re-initialization of OpenGL. It appeared in the past with double map views.

@devemux86 is there an way to log or debug into the code place where OpenGL is initialized? So we can check whether our code is doing this by accident.

**Comment by moving-bits** [comment] 2024-01-20 11:42
Have been able to get similar artifacts with built-in VTM "DEFAULT" theme:

![image](https://github.com/cgeo/cgeo/assets/3754370/00f8fa25-923f-4383-bd66-3e08992ee4a6)

This is after a fresh restart of c:geo, launched by Android Studio, directly opening the map, pan to the destination location.

No closing of map (or map fragments) involved, no change of map type, no zooming!

**Comment by moving-bits** [comment] 2024-01-27 15:01
Yet another observation: I got the "black boxes" problem today on a physical device, with OAM map and default c:geo theme (builtin Osmarender) after opening a cache from the map and returning to the map. But this is non-reproducible for me. And location is not in Berlin (as we have for the issue discussed further up).

**Comment by moving-bits** [comment] 2024-02-02 09:13
Tried a different approach (see #15268):

Instead of using our `MapsforgeVtmFragment` I created a new map fragment in a way which mimics the original `MapFragment` example from VTM sources, leaving out (most) c:geo specifics like GeoItemLayer etc., and using VTM default theme only.

Alas I still get those artifacts:

![image](https://github.com/cgeo/cgeo/assets/3754370/b36ebb26-983a-4372-b830-a8702163207d)

@devemux86 
- Any ideas where to debug further? (maybe OpenGL init, see https://github.com/cgeo/cgeo/issues/15100#issuecomment-1896310890)
- FYI: We are using a snapshot version of VTM: `String mapsforgeVTMVersion = '7879086e56' // LineBucket: transparent lines (9d68bdb) + dropDistance (31646b3)`

**Comment by fm-sys** [comment] 2024-02-02 09:35
We are using the `largeHeap` flag since #5039 while the vtm example does not. Could this make any difference?

**Comment by moving-bits** [comment] 2024-02-02 10:33
> We are using the `largeHeap` flag since #5039 while the vtm example does not. Could this make any difference?

I've cross-checked with `largeHeap` disabled, but no difference.

**Comment by devemux86** [comment] 2024-02-02 13:06
(please also show the "correct" image side by side, so we can understand the difference)

Ideally GL map view is used without fragments to avoid their complex nature.
Still don't know what's going on here and it works (?) in VTM samples.

**Comment by devemux86** [comment] 2024-02-02 13:49
> we also get black boxes in icon positions

That's why I thought it could be related to wrong multiple map view initialization / usage (not supported):
(so could be related to fragments)

- https://github.com/mapsforge/vtm/issues/194

**Comment by moving-bits** [comment] 2024-02-03 17:31
@devemux86 
I've created yet another test setting (see #15282), this time using NO map fragment, but directly include `MapView` into the activity's layout. Alas, it's showing the same artifacts as shown in https://github.com/cgeo/cgeo/issues/15100#issuecomment-1923383955, so I guess it's not a fragment issue (or at least, not only one).

Another idea I have could be layer handling. Is there a way to get some debug info if we are doing something wrong with layers / layer assignment etc.? What should we watch for?

**Comment by devemux86** [comment] 2024-02-04 09:21
@moving-bits 

Following the VTM samples should be the safe side, as they are the playground of all tests.

At least this is how it works properly all these years that I use VTM on Android and Desktop.
Using 1 MapView and creating it once. Unless switch as VTM samples with multiple activities.

Probably need to inspect carefully your integration and app / map lifecycle?
Starting with a simple map view and destroy / re-create it if want to switch its view surface.

**Comment by eddiemuc** [comment] 2024-02-10 17:26
I was able to reproducibly enable/disable black artefacts by deactivating the VTM switch `Parameters.TRANSPARENT_LINES`

With this switch set to true:
![image](https://github.com/cgeo/cgeo/assets/6909759/5a094c81-8d96-4de8-b7f1-67a6bc4b112e)


With this switch not set (means: set to false):
![image](https://github.com/cgeo/cgeo/assets/6909759/8a87ce1b-fde1-4217-baa4-15a434e160d1)


Both examples using offline OpenAndroMap in Berlin with elevate theme.

This switch was introduced in VTM with PR https://github.com/mapsforge/vtm/pull/1084 to help solve the c:geo problem https://github.com/cgeo/cgeo/issues/15029 (the "transparency" part of it)

I will provide a PR to switch this parameter off in c:geo.

@devemux86 : it seems we need a way to set this "switch" on a per-line-base (instead of globally) in order not to mess with some artefacts. Would you agree with this assessment? If yes I could try to create a PR

**Comment by moving-bits** [comment] 2024-02-11 08:57
_Posted by @ztNFny in https://github.com/cgeo/cgeo/pull/15310#issuecomment-1937472963:_

Unfortunately this _[edit: PR #15310]_ doesn't solve it either. I get less black blocks but now also some flickering ones.
https://github.com/cgeo/cgeo/assets/1258173/f2708e94-7796-4496-953f-021892d99d0f

**Comment by devemux86** [comment] 2024-02-11 09:24
Probably unrelated as was added later, but better make it a style option:
- https://github.com/mapsforge/vtm/pull/1100

**Comment by eddiemuc** [comment] 2024-02-11 10:53
PR #15316 will set the line trapsarency option on a per-line basis. With this PR merged, the transparency option should no longer impact the tile rendering. However:
* as written above: this seems NOT to remove all artefacts (but at least we can exclude the transparency option as their cause)
* this will also upgrade VTM to the currently latest version on VTM master. Might have other (hopefully positive) side effects

**Comment by bekuno** [comment] 2024-02-11 19:20
Other strange artifacts - background ractangles with different colors:
![Screenshot_20240210_133322_cgeo_2](https://github.com/cgeo/cgeo/assets/32555742/5a1cc573-068c-44ec-9f48-bca161a8dd07)
![Screenshot_20240210_133345_cgeo_2](https://github.com/cgeo/cgeo/assets/32555742/d0038823-7281-4ef6-8c2d-bbb472ddc2fb)
![Screenshot_20240210_133402_cgeo_2](https://github.com/cgeo/cgeo/assets/32555742/191de04b-b31c-4832-8cbc-971540bb6413)
![Screenshot_20240210_133412_cgeo_2](https://github.com/cgeo/cgeo/assets/32555742/bf023dea-85de-4577-869f-93cee9544c26)

**Comment by moving-bits** [comment] 2024-02-12 18:22
@ztNFny 

> Unfortunately this doesn't solve it either. I get less black blocks but now also some flickering ones. [cgeo/cgeo/assets/1258173/f2708e94-7796-4496-953f-021892d99d0f](https://github.com/cgeo/cgeo/assets/1258173/f2708e94-7796-4496-953f-021892d99d0f)

Can you give me some more details about the used settings (which map, which theme etc.) so that I can try to reproduce this in either emulator or on a physical device?
Location seems to be close to Wachtberg, correct? (or you can give me any other location where this happens for you)

**Comment by murggel** [comment] 2024-02-12 19:52
I can reproduce the black boxes on my device with Mapsforge Germany Elevation Elements:
Search for location (e.g. Stuttgart)
Open search result on map -> live mode is disabled
Enable live mode
-> black boxes are shown 

I have a video, but can't upload it

![Screenshot_20240212-204244_cgeo.jpg](https://github.com/cgeo/cgeo/assets/70113341/d773e391-e353-420e-9956-bf07db46dec2)

**Comment by moving-bits** [comment] 2024-02-12 20:04
Thanks, can reproduce it with today's beta version on my physical mobile.

Interesting fact: If I leave the map when the black boxes appeared, then re-enter it (by using the "map" menu entry in bottom navigation"), map stays clear of black boxes even when I re-enable live mode. 🤔 

I will now try with the two special builds.

**Comment by moving-bits** [comment] 2024-02-13 16:05
I may have found something:

On enabling "live mode", `onMapReadyTasks()` get called, which (among other things) resets the `tileProvider`. For VTM, this leads to `addTileLayer()` being called. As far as I can see, those layers get added without having removed them first, which may be the cause for the observed visual problems.

As a workaround I have created PR #15329, which checks on `setTileSource`, whether this is an actual change (and skips follow-up actions, if not). I kindly ask everyone, who can observe one of the incarnations of the "black boxes" problem, to test this PR.

A different solution could be to call `prepareForTileSourceChange()` when enabling live mode, but that would remove all layers and leads to a short flickering. A more proper solution would be to remove only the affected layers (BUILDING and LABELS, in this case) - if my assumptions are correct.

**Comment by murggel** [comment] 2024-02-13 18:40
> As a workaround I have created PR #15329, which checks on `setTileSource`, whether this is an actual change (and skips follow-up actions, if not). I kindly ask everyone, who can observe one of the incarnations of the "black boxes" problem, to test this PR.
> 
I am currently on vacation without the possibility to test. I can test next week.

**Comment by ztNFny** [comment] 2024-02-13 19:36
> As a workaround I have created PR #15329, which checks on setTileSource, whether this is an actual change (and skips follow-up actions, if not). I kindly ask everyone, who can observe one of the incarnations of the \"black boxes\" problem, to test this PR.

First test looks good

**Comment by moving-bits** [comment] 2024-02-16 21:42
> Other strange artifacts - background ractangles with different colors:

I was able to reproduce [this](https://github.com/cgeo/cgeo/issues/15100#issuecomment-1937844192) behavior today with current beta version 2024.02.12. Will need to recheck if it still happens after the recent changes/fixes for VTM.

**Comment by murggel** [comment] 2024-02-19 21:13
I installed the version 2024.02.18-NB-f05cfbb and had the effect of flickering boxes. 

@moving-bits I already sent a email with video and extended log to c:geo-support

**Comment by moving-bits** [comment] 2024-02-19 21:22
> I installed the version 2024.02.18-NB-f05cfbb and had the effect of flickering boxes. I am not sure, if the PR is included

PR #15329 was merged of Feb 16th, so it should be part of the nightlies starting Feb 17th.

> @moving-bits I already sent a email with video and extended log to c:geo-support

thanks, have received it and tried to find something VTM-related in the logs, but wasn't able so (or at least I was not able to link the items to VTM). But a few other things, non map-related - will open separate issues for it.

@devemux86 
Is there a way to enable logging for VTM to catch things that VTM regard as "strange" (errors, warnings, non-expected parameter etc.)?

**Comment by devemux86** [comment] 2024-02-20 07:49
@moving-bits 
Searching the code can only find some booleans in various places for development testing purposes.

**Comment by ztNFny** [comment] 2024-02-24 13:04
I have the "classic" black boxes again in master of 22.2. with OAM Germany map
![Screenshot_2024-02-24-14-02-29-89_a916ceb0c8a82619faeb76fe6b8ae997.jpg](https://github.com/cgeo/cgeo/assets/1258173/a376620d-4f71-4ace-8508-ed60c57d354e)

**Comment by moving-bits** [comment] 2024-02-25 11:03
> I have the "classic" black boxes again in master of 22.2. with OAM Germany map

Do you have a scenario where this is reproducible for you?

I haven't seen the black boxes again for a while now, so it's hard for me to test any possible fixes.

Or, even better, do you have the time to debug into this and try some mitigations? :-)

**Comment by ztNFny** [comment] 2024-02-25 11:45
Sorry, that was while I was out caching, important to know that the original issue it's not solved yet

**Comment by ztNFny** [comment] 2024-02-25 11:48
And it just happened again. OAM offline map, mapping a list, live disabled. Opened Cachedetails, stored a log, back to map and labels have black boxes flickering.
Not sure what i can log in the field about it.

**Comment by murggel** [comment] 2024-02-25 13:32
Happened again on my device, too.
I will send a video to support and I will try to get it reproducable.

I started from map, opened a cache in cache-detail view, mapped it to the map (via navigate to via map), go back, add waypoint (change cache(?) relevant), go back to map
-> flickering

**Comment by murggel** [comment] 2024-02-25 15:20
I have it reproducable with simple steps
1. Open map
2. Open cache from map
3. Start "navigation on map" from action bar of cache ![Screenshot_20240225-161626_cgeo.jpg](https://github.com/cgeo/cgeo/assets/70113341/edcde8a4-3a70-47d2-b0fd-6c5c53ee3a98)
4. Return with back-button back to cache
5. Return with back-button back to  "first" map
This map is now flickering with black boxes

**Comment by moving-bits** [comment] 2024-02-25 16:39
Thanks for the reports and additional info. This leads me to a question:

Further up it was mentioned, that VTM does not support "two maps / map fragments" at the same time.

If we open a map, then open a cache from that map, then open navigation to that cache (which is being displayed on a map) - does that count as "two maps open at the same time"? (same activity, loaded twice)

If so, what would be the correct way to handle that situation?
- create a VTM `MapView` as global var (`CGeoApplication`) and attach it to the respective fragment on demand?
- always close that MapView and destroy the object, when another activity gets started?
- ...?

**Comment by fm-sys** [comment] 2024-02-25 17:50
The second one I would say

**Comment by fm-sys** [comment] 2024-02-26 21:15
Although my understanding of memory leaks on Android is pretty bad, I understood it as storing a activity/fragment/view reference inside a variable which survives onDestroy events thus android is unable to free the memory is necessary. Maybe it would work in the way you described it, but I have quite a bad feeling with it.

**Comment by moving-bits** [comment] 2024-02-27 10:22
Or is this the right trigger to start rethinking our app workflow?

Why do we need a "stacked" access to map => cache details => map => ...?

What if we have only a single map instance, and if we want to do anything on a map, it always gets back to that single instance?
(Eg: Opening a cache from the map: info sheet, then CacheDetailActivity; mapping that cache: closing CacheDetailActivity, signalling the map a new target)

Or even more radical: make c:geo a map-centered map like Cruiser etc.
Opening c:geo starts map view (no homescreen etc. anymore). Every action (eg: search, cache list view, ...) gets started from there, and finally returns to the map.

Many follow-up questions would arise, for sure. Just curious if we would want to discuss possible changes in such a direction at all.

**Comment by fm-sys** [comment] 2024-02-27 15:37
We somehow had that discussion while designing the bottom nav. I would be in favor of it, but not sure if we can build up a consistent concept which contains all existing features and meets the user requirements.

**Comment by moving-bits** [comment] 2024-03-02 13:50
> If so, what would be the correct way to handle that situation?
> * create a VTM `MapView` as global var (`CGeoApplication`) and attach it to the respective fragment on demand?

I've looked into this "option 1" (using application context), and... let's just say, we don't want to have this, although it gives colorful images (similar to what @MagpieFourtyTwo has observed in https://github.com/cgeo/cgeo/issues/15400#issuecomment-1974058371)

So let's try do dive a bit deeper into the other options:
> * always close that MapView and destroy the object, when another activity gets started?

Here are some thoughts about it, please challenge them, comment and add your ideas: ("option 2")
- as only VTM is affected, all handling described next should be applied to VTM only
- destroying and reconstructing the MapView should be done in `onPause` and `onResume` of `UnifiedMapActivity` (VTM fragment would be one step too low in hierarchy, some things for restoring need to be handled in map activity; or you need some callback to trigger those)
- things that need to be done on destroying the MapView:
  - call `onDestroy` on MapView object
  - remove map view from map fragment (for this, the layout file should use some frame around it, which gets filled dynamically, instead of implementing the MapView directly in the layout file)
  - destroy the MapView object (can we trigger an actual destroy?) - or would we need an activity restart in `onResume` anyway for correct initialization of MapView?
- things that need to be done in `onResume`: (assumed that we don't need an activity restart)
  - create new MapView and attach it to the fragment
  - reload tile source and theme
  - repaint route, tracks, history line, direction line, distance views, geopoint cross-hair (whatever has been active before shutdown)
  - reload caches/waypoints (already done in `onResume`)
- if an activity restart is required (instead of `onResume`), then some additional things need to be done
  - save more state-related info (like `saveInstanceState` does)
  - retrigger restart of map activity in `onResume`
- as this seems to be quite costly, an optimization could be to destroy the MapView only if actually required
  - for this, CGeoApplication could hold a WeakReference to current map's activity
  - on creating the MapView, check if one is already present; if so: shut down the old MapView
  - create new MapView and register current activity

Yet another approach could be to avoid stacking of map views altogether: ("option 3")
- no stacking of maps, only a single map instance is in memory at any time
- (not sure if this is possible with our direct invocation links into the app that can be put on the phone's home screen)
- use `startActivity` for maps only, if currently no map is being displayed; otherwise use activity result to inform the map about the new type and focus it should use
- map needs to check for those activity results and act accordingly (refocus, reload new set of caches/waypoints to be displayed etc.)

(The easiest option - for us, at least - would be if VTM could cope with several instances being active at the same time, like Mapsforge and Google Maps can, but that is a huge and difficult task as well, has been tried once in the past, but not finished.)

**Comment by moving-bits** [comment] 2024-03-02 19:07
Found yet another way to get the black labels:
- open map
- tap on filter symbol to open filter activity
- return to map (confirm filter, no need to change anything)
- long-tap on free map space to open context menu

=> black boxes everywhere

- interestingly, the black labels vanish as soon as you close the context menu
- but when you start moving the map after closing the context menu, screen is completely distorted

https://github.com/cgeo/cgeo/assets/3754370/974e3a54-c4cf-4a36-b14b-c2084baa3c11

(BTW: context menu is drawn ok, appearance in the video is a conversion artifact)

**Comment by fm-sys** [comment] 2024-03-03 00:52
I think the better way, instead of just destroying the view which seems quite hacky, may be to destroy the fragment in `onPause` and recreate it on re-entering the activity. (For both, vtm and GM, mainly to avoid inconsistencys between map implementations)

**Comment by moving-bits** [comment] 2024-03-03 11:16
> I think the better way, instead of just destroying the view which seems quite hacky, may be to destroy the fragment in `onPause` and recreate it on re-entering the activity. (For both, vtm and GM, mainly to avoid inconsistencys between map implementations)

I've dived a bit into this: From some quick testing, destroying the whole map fragment leads to crashes in many places, due to the asynchronous nature. There are just too many things going on in the background, which require a map fragment (eg: saving activity instance, updating cache list, updating spinner info). But the same may happen, if we only destroy the map view (eg: as getting map center in saving activity instance requires a map view as well). \**sigh*\*

**Comment by moving-bits** [comment] 2024-03-03 11:59
Ok, I think I mitigated most glitches caused by background activities to make this approach run at all. See PR #15411. Destroying and recreating map fragment is done on demand, so not for every "show cache details" or so, but only if another instance of UnifiedMap is to be started.

Seems to be way better now, but still not bug free. Using [@murggel's test case](https://github.com/cgeo/cgeo/issues/15100#issuecomment-1962972600) I get white (?!) boxes for some of the labels, although the map fragment (and with it the whole MapView) got recreated. Do we really have to restart the whole activity?

**Comment by Lineflyer** [comment] 2024-03-03 18:15
> Seems to be way better now, but still not bug free. Using https://github.com/cgeo/cgeo/issues/15100#issuecomment-1962972600 I get white (?!) boxes for some of the labels, although the map fragment (and with it the whole MapView) got recreated. Do we really have to restart the whole activity?

I also made the observation, that with latest nightlies the black boxes are gone, but now I also have white boxed at the same scenario.

**Closed** 2024-03-10 21:25 UTC
Labels: Bug, Map: Unified
