### ISSUE TITLE
Popup menu for text selection too narrow

### ISSUE THREAD

**Issue by papenmap** [cgeo/cgeo#5917] opened 2016-08-23 07:24 UTC
##### Detailed steps causing the problem:

Using c:geo on Android (Samsung Galaxy 7) in portrait lay-out (vertical)
- View details of a cache
- Select part of the text. Popup menu 'share' appears.
- Touch dots on the right ":" to open the deeper menu (copy, share, select all, assistant, search wikipedia, translate).
##### Actual behavior after performing these steps:

The menu is too narrow. Most menu items are not visible, because you only see the far right part of the menu.

If you do the same in landscape lay-out (horizontal), the popup menu is correct.
##### Expected behavior after performing these steps:

The menu  should be wider so all text is visible.
##### Version of c:geo used:

2016:08:16
##### Is the problem reproducible for you?

Yes
##### System information:

Device: SM-G930F (heroltexx, samsung)
Android version: 6.0.1
Android build: MMB29K.G930FXXU1APGO
Cgeo version: 2016.08.16
Google Play services: enabled
Low power mode: inactive
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: rotation vector
Hide own/found: false
Map strategy: auto
HW acceleration: enabled (default state)
System language: nl_NL
Log date format: 23-08-16
Debug mode active: no
Geocaching sites enabled:
   geocaching.com: Logged in (Ingelogd) / PREMIUM
Installed cgeo plugins:  none

**Comment by SammysHP** [comment] 2016-08-23 07:50
Can you show us a screenshot?

**Comment by papenmap** [comment] 2016-08-23 07:55
Sure. See attachment. One is in portrait mode (the bug) and the other in landscape mode.

I hope that you have a solution. 
Vriendelijke groet,
Martin van Toll



Op 23 aug. 2016 09:50, bij 09:50, SammysHP <notifications@github.com> schreef:

**Comment by mucek4** [comment] 2016-08-23 08:03
Attachments from email don't post here.

**Comment by papenmap** [comment] 2016-08-23 08:24
Did you get the screenshots?  I just received a message that "attachments don't post here". 

Vriendelijke groet,
Martin van Toll



Op 23 aug. 2016 09:50, bij 09:50, SammysHP <notifications@github.com> schreef:

**Comment by mucek4** [comment] 2016-08-23 08:59
No. We did not got screenshot. You need to attach it on github page.

**Comment by papenmap** [comment] 2016-08-23 10:06
I can't send pictures through github.com. Here is a link to my two sreenshots:
http://www.vantoll.nl/download/CGEO_menu_too_narrow.zip

**Comment by papenmap** [comment] 2016-08-23 13:41
Did you succeed in viewing the screenshots?

**Comment by SammysHP** [comment] 2016-08-23 13:57
![1 menu too narrow portrait](https://cloud.githubusercontent.com/assets/922874/17894601/35064048-694a-11e6-8067-90aa7a562296.png)
![2 menu correct landscape](https://cloud.githubusercontent.com/assets/922874/17894606/3a35b0bc-694a-11e6-94d3-d3d243c2f14c.png)

**Comment by Bananeweizen** [comment] 2016-08-28 06:11
duplicate of #5623. solution would be to shorten the translation string for netherlands this time

**Comment by papenmap** [comment] 2016-08-29 07:09
Sounds risky. Is this the only solution???

**Comment by papenmap** [comment] 2016-08-29 11:05
I tried, but no result. With APK Editor I could open the APK of c:geo. Choosing 'full edit' I get a long list of Dutch texts. There is "vertalen naar Engels" (= translate to english) and "vertalen naar %s" (= translate to %s). The advise in #5623 is to shorten the text. 
I tried to change it to "naar Engels" and "naar %s" (or even %s) and pressed SAVE. There was a confirmation that APK had been saved as /storage/emulated/0/ApkEditor/_base.apk. 
After opening c:geo again, there was no change at all.
If I use APK Editor to re-open the APK of c:geo I saw the old version again, without changes. 
But I think this is a dirty and risky solution. 
Isn't there is a real update possible bij the makers of c:geo?

**Comment by rsudev** [comment] 2016-08-29 11:30
The translations for c:geo are maintained on crowdin (https://crowdin.com/project/cgeo). You can suggest shorter translations there, get them approved by one of the Dutch proofreaders (or may do so for testing ourselves if you notifiy us here) and then we will move them into the next nightly, to let you cross check whether it works.

**Comment by kumy** [comment] 2016-08-29 11:31
> There was a confirmation that APK had been saved as /storage/emulated/0/ApkEditor/_base.apk. 

Did you installed the resulting apk?

The "normal" way would be to compile cgeo by yourself...

On August 29, 2016 1:05:53 PM GMT+02:00, papenmap <notifications@github.com> wrote:
>I tried, but no result. With APK Editor I could open the APK of c:geo.
>Choosing 'full edit' I get a long list of Dutch texts. There is
>"vertalen naar Engels" (= translate to english) and "vertalen naar %s"
>(= translate to %s). The advise in #5623 is to shorten the text. 
>I tried to change it to "naar Engels" and "naar %s" (or even %s) and
>pressed SAVE. There was a confirmation that APK had been saved as
>/storage/emulated/0/ApkEditor/_base.apk. 
>After opening c:geo again, there was no change at all.
>If I use APK Editor to re-open the APK of c:geo I saw the old version
>again, without changes. 
>But I think this is a dirty and risky solution. 
>Isn't there is a real update possible bij the makers of c:geo?
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/cgeo/cgeo/issues/5917#issuecomment-243095257

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by papenmap** [comment] 2016-08-29 12:35
@rsudev: Sorry, I am new here. I just created an account for crowdin.com, but is not very clear what to do. Is this the only way to suggest approvements in c:geo? I hope someone can take care of this.

**Comment by kumy** [comment] 2016-08-29 12:38
@papenmap All localizable strings are uploaded to crowdin, cgeo is there https://crowdin.com/project/cgeo. Our wiki page is https://github.com/cgeo/cgeo/wiki/Translation-%28L18N%29

**Comment by rsudev** [comment] 2016-08-30 05:48
I validated the suggestion you made and imported the changes today. @papenmap please check the next nightly.

**Comment by papenmap** [comment] 2016-08-30 06:24
"The next nighty" means "the next automatic update"?

Vriendelijke groet,
Martin van Toll



Op 30 aug. 2016 07:48, bij 07:48, rsudev <notifications@github.com> schreef:

**Comment by kumy** [comment] 2016-08-30 07:15
Current code from the master (unstable) branch is built each night. See page http://www.cgeo.org/development.html for more informations and download links.

On August 30, 2016 8:24:34 AM GMT+02:00, papenmap <notifications@github.com> wrote:
>"The next nighty" means "the next automatic update"?
>
>Vriendelijke groet,
>Martin van Toll
>
>
>
>Op 30 aug. 2016 07:48, bij 07:48, rsudev <notifications@github.com>
>schreef:
>>I validated the suggestion you made and imported the changes today.
>>@papenmap please check the next nightly.
>>
>>-- 
>>You are receiving this because you were mentioned.
>>Reply to this email directly or view it on GitHub:
>>https://github.com/cgeo/cgeo/issues/5917#issuecomment-243339408
>
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/cgeo/cgeo/issues/5917#issuecomment-243344660

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by papenmap** [comment] 2016-08-31 12:46
I installed the latest nighty. Problem has been solved now. Thanks!

**Closed** 2019-12-02 13:51 UTC
Labels: Bug, Frontend Design
