### ISSUE TITLE
 'Your saved log' not cleared when  'Report problem' used.

### ISSUE THREAD

**Issue by alan666notb** [cgeo/cgeo#7039] opened 2018-05-29 17:05 UTC
I'm using the latest beta release 2018.05.28-RC loaded yesterday.
I logged and DNF + 'Report problem' successfully but 'Your saved log' remained on the logbook page.
I can't find a way of reproducing it without logging a NM on someone else's cache, which I don't want to do.

##### Detailed steps causing the problem:
- Open a cache and goto 'Log visit'
- Choose 'DNF' and 'Report problem' -> 'Other'
- Send the log and wait for it to succeed.

##### Actual behavior after performing these steps:
Log isn't cleared from logbook and remains as 'Your saved log' 

##### Expected behavior after performing these steps:
 'Your saved log'  should be removed.

##### Version of c:geo used:
2018.05.28-RC

##### Is the problem reproducible for you?
Haven't tried - see above.

**Comment by Lineflyer** [comment] 2018-05-30 09:01
Thanks @alan666notb for providing feedback regarding the beta version.
This is a duplicate of #6996

**Closed by Lineflyer** 2018-05-30 09:01 UTC
