### ISSUE TITLE
Cannot log

### ISSUE THREAD

**Issue by ThomasKaule** [cgeo/cgeo#8154] opened 2020-03-26 10:23 UTC
**Describe the bug:**
Cannot log via c:geo

**To Reproduce:**

Select a cache
open "log" (a message appears, see below)
enter text
submit log (a message appears, see below)

**Actual behavior/state after performing these steps:**
If I open a log window a message "cannot get additional data" appeared. If I want to submit the log, a massage "send of log failed". This happened yesterday and today again. In the meantime I closed the app I disconnected and reconnected the phone. The same issue at the phone of my wife. I can you the official geocaching app and successfully log. Reload in c:geo results in a proper "found" with a green bar. So it's a c:geo issue and not a geocaching one.

**Expected behavior/state after performing these steps:**
obvious

**Version of c:geo used:**
2020.03.07

**Is the problem reproducible:**
Yes

**Screenshots:**
![Screenshot_20200326-103214](https://user-images.githubusercontent.com/20680558/77633810-4c83e300-6f50-11ea-96c9-e44ff78348f8.png)
![Screenshot_20200326-103254](https://user-images.githubusercontent.com/20680558/77633819-4f7ed380-6f50-11ea-89c3-1f9c30979dc3.png)

url) screenshots if applicable and helpful to explain your problem

**System information:**
```
Attach system information here if available (see c:geo Menu -> About c:geo -> Swipe right to System)
Keep the apostrophe at beginning and end to have it properly formatted
```

**Additional context:**
e.g. Reference to other issues, projects, sources, etc.

**Comment by Lineflyer** [comment] 2020-03-26 10:54
Also reported by other users on our channels and I can reproduce with current nightly.
Website change?!

**Comment by bekuno** [comment] 2020-03-26 12:48
The handling on the new log page is strange.
Only one log type, only the post button, but no trackable part.
The old log page looks ok.
Seems to me like a bug on the website.

**Comment by Lineflyer** [comment] 2020-03-26 13:01
Same here on the website.
Looks like a bug indeed.

**Comment by jonas-koeritz** [comment] 2020-03-26 13:06
We might have a problem here. c:geo gets a 401 from geocaching.com, the request sent by the (new?) Log UI on the web is totally different (json payload).
2020-03-26 14:04:07.022 11209-11254/cgeo.geocaching D/cgeo: [OkHttp] 401 [Unauthorized] (194 ms) POST https://www.geocaching.com/api/proxy/web/v1/geocache/<Geocode>/GeocacheLog

**Comment by Lineflyer** [comment] 2020-03-26 19:56
I triggered a status message to the users for the time being.

If someone has time to look into it, its highly appreciated.

@pstorch Just pinging you, as the new log page was "your baby ", so you might have more insights.

**Comment by pstorch** [comment] 2020-03-26 20:36
> We might have a problem here. c:geo gets a 401 from geocaching.com, the request sent by the (new?) Log UI on the web is totally different (json payload).
> 2020-03-26 14:04:07.022 11209-11254/cgeo.geocaching D/cgeo: [OkHttp] 401 [Unauthorized] (194 ms) POST https://www.geocaching.com/api/proxy/web/v1/geocache//GeocacheLog

Just a quick view: 
the geocode is missing between `https://www.geocaching.com/api/proxy/web/v1/geocache/` and `/GeocacheLog` in the URL to post to. 
Why is it missing?

**Comment by pstorch** [comment] 2020-03-26 21:12
> Sorry, I just redacted it. The brackets got removed by GitHub.

Ah, got it.

> We might have a problem here. c:geo gets a 401 from geocaching.com, the request sent by the (new?) Log UI on the web is totally different (json payload).

That might be the reason. Previously the data was sent as URL parameters, now it is json payload. But why does it result in a 401 Unauthorized error? At least some hint to try to change the payload to json.

**Comment by jonas-koeritz** [comment] 2020-03-26 21:16
The endpoint the website uses is different too, I don't know much about the logging mechanisms but you should have a look how it's currently done on the website.

**Comment by bekuno** [comment] 2020-03-26 21:25
The new log page looks now as before at least with FF on Android. Maybe repaird by GS?

**Comment by johan974** [comment] 2020-03-27 16:50
Hi, 
Howdy, joined your team the last time solving the "logging" issue.
I think geocaching.com is having more issues, because even showing geocaches on a map is not working, giving a white page. E.g. https://www.geocaching.com/play/map?sw=1&zoom=14.
I will also start investigating. 
Kind regards, Johan

**Comment by johan974** [comment] 2020-03-27 19:41
Hi, 
Behind my desktop browser, I replayed a few sample logs. The start is the same with the https://www.geocaching.com/seek/log.aspx?ID={old-gc-id}&lcn=1. After a number of http requests I see a post of a token, just like before. 
[1] **BUT** I don't see a call like https://www.geocaching.com/api/proxy/web/v1/Geocache/GC111111/GeocacheLog. 
[2] When I replay it in my own (private) Android app -- which does the same log process like c:geo -- and I start the request https://www.geocaching.com/api/proxy/web/v1/Geocache/GC11111/GeocacheLog, then I get the Invalid login:401 error. 
So, how is the user log info transferred to geocaching.com? Till so far (via F12 desktop browser logging), I haven't seen it yet ;-(.

**Comment by johan974** [comment] 2020-03-27 20:22
When replaying the current version in my private app, then I can see that the https://www.geocaching.com/api/proxy/web/v1/geocache/GC..../GeocacheLog gives the "invalid login: 401" error. The GC-part (as pstorch wrote) is not missing here. 

As suggested, I replayed logging at my desktop. It is different. 
First to make a step back: geocaching.com has 2 ways of logging: 
[1] the 'opt-out' version: which uses under water the old POST of data to https://www.geocaching.com/seek/log.aspx?ID=6887689&lcn=1. It uses the old VIEWSTATES stuff. 
[2] modern (no opt out): when replaying a log session at a destop browser (with F12 chrome), then I cannot find any statement that posts (or transfers) the user log information. I can see get's and a post of the auth token. 

For me it is a mystery so far. Going back to the old way with those dumm VIEWSTATES is not exactly what I like and want.

**Comment by jonas-koeritz** [comment] 2020-03-27 21:07
You have to enable "preserve logs" in chrome to see the request made before the redirect.

**Comment by jgoestl** [comment] 2020-03-28 01:15
Friday evening I was geocaching and I stumbled across this problem. So I had a look at it tonight and maybe I fixed it. Now it's time to sleep, so I'll tell you more tomorrow.

**Comment by johan974** [comment] 2020-03-28 11:23
For the call to log, I replaced the body of https://www.geocaching.com/api/proxy/web/v1/geocache/GC..../GeocacheLog with the Json payload. I still had the same "Invalid login status: 401". Will continue.

**Comment by johan974** [comment] 2020-03-28 16:10
My compliments @jgoestl ! It was a combination of the JSON payload and removing the authentication token stuff. It works in my app too. (My app is only used by 2 persons).

**Comment by geocachermgo** [comment] 2020-03-29 10:30
When will this be available in the play store?
Maybe the hint that is shown on the main screen be more precise: Logging is not working.
Thanks also from my side fron finding the bug!

**Comment by moving-bits** [comment] 2020-03-29 10:44
@geocachermgo  A PR is proposed already. We're waiting for a code review from the original author of that part of c:geo. Give us one more day or so.

**Comment by geocachermgo** [comment] 2020-03-29 10:53
Thanks for the info. I did not what to whine or nag, it was an honest question.
Will it be published at once or will the be a nighly build or beta in advance?

**Comment by moving-bits** [comment] 2020-03-29 11:01
No problem.

We haven't discussed yet how to publish this fix after a positive review, but if you like, you can install the APK already, see the link in the last test of PR #8157 (currently https://ci.cgeo.org/job/cgeo%20pull%20request/2591/). Be sure to make a backup of your c:geo database first (and for your program settings as well, if you like), using c:geo's backup features.

**Comment by geocachermgo** [comment] 2020-03-29 11:16
both cgeo-debug.apk  and cgeo-basic-debug-androidTest.apk	 ?

**Comment by jgoestl** [comment] 2020-03-29 11:36
Only the cgeo-debug.apk is needed

**Comment by Lineflyer** [comment] 2020-03-29 16:06
According to my tests with new nightly and RC-version this issue is fixed.
There is however a remaining issue AFAICS:  #8166

**Closed by Lineflyer** 2020-03-29 16:06 UTC
Labels: Bug, Prio - High

**Comment by geocachermgo** [comment] 2020-03-29 18:06
cgeo-debug.apk reported "not installed".

**Comment by Lineflyer** [comment] 2020-03-29 18:13
> cgeo-debug.apk reported "not installed".

That does only work if you deinstall any other c:geo installation.

However this is not necessary anymore, you can do the following:

1. If you currently use our nightly builds, simply upgrade to the newest nightly
2. If you use the normal release from Google Play, please load a new version from here: http://download.cgeo.org/cgeo-RC.apk

Feedback is appreciated.
Please note: There seems to be a regression left, that favorite points cannot be assigned.

**Comment by moving-bits** [comment] 2020-03-29 18:13
It's probably a conflict between your currently installed version of c:geo and the debug apk.

Please
- backup c:geo database (and settings) first, using c:geo's backup functions
- uninstall c:geo using your system's functions
- install the apk
- start c:geo, accept file system access (to be able to restore the backups)
- restore database (and settings) using c:geo's restore function

**Comment by geocachermgo** [comment] 2020-03-29 19:02
I now installed the nighly build.
Thanks for the support.
