### ISSUE TITLE
Unable to find activity when trying to open GPX file in c:geo

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#7313] opened 2019-02-19 13:33 UTC
##### Detailed steps causing the problem:
From support mail (unverified and details missing):
- I try to open a GPX file with c:geo from file manager (like Total Commander,etc.)

##### Actual behavior after performing these steps:
An error message appears
![screenshot_20190205-142808_total commander](https://user-images.githubusercontent.com/949669/53018643-2d647900-3453-11e9-9a4d-9160308b6962.jpg)

##### Expected behavior after performing these steps:
c:cgeo should import the GPX

##### Version of c:geo used:
2018.10.13

##### Is the problem reproducible for you?
Yes, for this user but not for me

##### System information:
Waiting for user feedback

**Comment by moving-bits** [comment] 2019-02-19 16:58
I am able to reproduce this with 2018.10.13 release version and total commander app:
- chose gpx file (short tap)
- a popup opens: "open with", "open as", "create link on desktop", "edit file"
- chose "open with" and select c:geo
- error occurs as shown in the screenshot above

I tried to cross-test with a different app and chose my system's file manager. After short tap on the file I receive an error message similar to "error opening file - you have no app which can open this file type..." (translated).

Opening a GPX file received via e-mail attachment does work as well as opening a link to a GPX ZIP file (like those sent by gc.com for pocket queries).

I can't remember, but was c:geo ever intended to open locally stored GPX files via a file manager?
Or only those transferred via URL or intent from a different app (like an e-mail program as tested above)?

**Comment by Lineflyer** [comment] 2019-02-19 18:22
Yes, import of a GPX from file system should have worked and still works for me (not using Total Commander but some other app...need to check).
The user also reported that ZIP is fine, but uncompresssed GPX fails as described.

**Comment by Lineflyer** [comment] 2019-02-19 18:23
Are you also able to reproduce with current master and Total Commander?

**Comment by moving-bits** [comment] 2019-02-19 22:34
The first test was on a physical device with 2018.10.13 release version, API 24.

Did a retest with yesterday's release candidate on an emulated API 26 => same result with Total commander, but internal preinstalled Android app "Files" did work!

Then: rebuild all with today's master, emulated API 26 => same results as before.

**Comment by githubber2222** [comment] 2019-02-20 12:52
Can open files just fine in Total Commander when using different App(s)! Only c:geo is failing!

**Comment by bekuno** [comment] 2019-05-06 23:24
I can also verify it.

- Open TotalCommander
- long tap on the gpx file
- select "open with"
- the application list is presented with "c:geo" and activity "cgeo.geocaching.CacheListActivity" (see image)
![20190507_011621](https://user-images.githubusercontent.com/32555742/57261106-cb390e80-7066-11e9-8924-909e16207b66.jpg)

- after selecting c:geo the error message occures

**Comment by moving-bits** [comment] 2020-04-13 12:43
During my work on #8180 I've again stumbled upon this error. I've reached out to the Total Commander support forum to see if we can get this fixed somehow.

https://www.ghisler.ch/board/viewtopic.php?f=22&t=67743

**Comment by moving-bits** [comment] 2020-04-14 10:05
Got a reply from the author of TC4A: It's a problem with the way the 2.x versions of Total Commander handle intents, as they are using ":" as delimiter, which conflicts with our app name. 

We can do nothing on our side (renaming "c:geo" is not an option :-)), but the upcoming 3.0 version of TC4A will use a different mechanism. We should retest it then.

**Comment by moving-bits** [comment] 2020-04-18 08:28
Version 3.0 of TC4A just got released. It's not available for all Android versions and platforms, though - my physical mobile already got an update, whereas the different emulators I use haven't yet.

At least with my physical mobile I can confirm that TC3.0 is now able to open gpx files within c:geo :-) therefore closing this issue now.

**Closed by moving-bits** 2020-04-18 08:28 UTC
Labels: Bug
