### ISSUE TITLE
Cannot copy cache coordinates

### ISSUE THREAD

**Issue by MrYaz** [cgeo/cgeo#4835] opened 2015-04-03 21:25 UTC
I can no longer copy the cache coordinates.
The clipboard is empty after copying by long-pressing on the coordinates and pressing the copy icon.

I use this build:
2015.04.03-NB-c62c328

**Comment by rsudev** [comment] 2015-04-03 21:34
I did a quick cross-check (my build is slightly newer), but it worked for me.
Does it fail for all caches for you? Can you post your system information, to perhaps further other ideas?

**Comment by MrYaz** [comment] 2015-04-03 22:06
After testing some more it seems like more copy operations in c:geo fails.
Not only coords. Also hints, description and log texts on the Logs Tab
Copy & Paste in edit windows still work. I.e. Log Visit, Edit Waypoint, Edit Personal Note.
Same behavior on all caches.

--- System information ---
Device: Nexus 5 (hammerhead, google)
Android version: 5.1
Android build: LMY47I
Cgeo version: 2015.04.03-NB-c62c328
Google Play services: enabled
Low power mode: inactive
Compass capabilities: yes
Rotation sensor: present
Geomagnetic rotation sensor: present
Orientation sensor: present
Hide own/found: true
Map strategy: detailed
HW-acceleration: enabled (default state)
Geocaching sites enabled:
- geocaching.com: logged in (Login OK) / Premium
System language: sv_SE (cgeo forced to English)
Installed cgeo plugins: calendar contacts
--- End of system information ---

**Comment by MrYaz** [comment] 2015-04-03 22:13
I believe that there also used to be a text at the red arrow describing what shall be copied.
Description, Coordinates, Hint etc.

![image](https://cloud.githubusercontent.com/assets/1811963/6989695/4b3b39ac-da5f-11e4-9ea8-0a68860c433b.png)

**Comment by Lineflyer** [comment] 2015-04-04 08:11
Duplicate of another issue I opened last days, also Lollipop related.
I suggest to keep this one open as it has more details.

Maybe someone can look up the other issue and close + link to this one.

**Comment by rsudev** [comment] 2015-04-04 08:40
You are right, normally there is a title with the copied data. Perhaps did something change in Android so the 'source' of the copy operation is no longer correctly detected.
Does anybody from the devs have a Lollipop device to cross check this?

**Comment by MrYaz** [comment] 2015-04-04 10:18
You're right!
It probably has to do with Lollipop version 5.1 that I installed just a few days ago.
It worked fine before that with Lollipop ver 5.0..

**Comment by kumy** [comment] 2015-04-04 10:39
It ok on 5.0.1.. No 5.1 here...

**Comment by Bananeweizen** [comment] 2015-04-04 15:15
reproducable on 5.1 emulator

**Comment by rsudev** [comment] 2015-04-04 15:33
In the meantime I got a 5.1 emulator running as well (very sloooow).
It seems, that onPrepareActionMode is no longer called when the action mode is first created...

**Comment by Bananeweizen** [comment] 2015-04-05 07:14
@rsudev, use genymotion

**Comment by Lineflyer** [comment] 2015-04-06 22:36
Setting "Regression" label to indicate that his bug is in the field although I am not sure if it was there ever since and only 5.1 shows it. 
However only recently such reports came in...

**Closed** 2015-04-07 09:11 UTC
Labels: Bug, high, Regression
