### ISSUE TITLE
 404 error on Hylly map file download

### ISSUE THREAD

**Issue by fm-sys** [cgeo/cgeo#11793] opened 2021-10-06 05:17 UTC
Just a heads up, the internal downloader is returning a 404 error on the Hylly map file.

_Originally posted by @Vike91 in https://github.com/cgeo/cgeo/issues/10511#issuecomment-935100404_

Side note by @fm-sys:
I can reproduce the issue

**Comment by Vike91** [comment] 2021-11-01 21:03
Tried to reproduce with 2021.10.24-RC, looks like it has been fixed, as both the map file and the theme files were downloaded successfully via the c:geo map download manager.

**Comment by Lineflyer** [comment] 2021-11-05 15:38
@Vike91 @moving-bits Can this be closed then?

**Comment by Vike91** [comment] 2021-11-05 15:42
Tested downloading the map file with 2021.11.04-RC and now I'm getting the 404 error again.

**Comment by Vike91** [comment] 2021-11-05 15:44
Does @pailakka have a hint what might be going wrong?

**Comment by moving-bits** [comment] 2021-11-06 14:03
> @Vike91 @moving-bits Can this be closed then?

As we have not changed anything in the code, neither before opening this issue nor since then, I guess the problem is somehow server-related, maybe a temporarily failing load balancer or some certificate issue (wild guesses). As mentioned in https://github.com/cgeo/cgeo/issues/11793#issuecomment-939076530 I would really like to get some hint from the server logs.

**Comment by moving-bits** [comment] 2022-04-30 20:14
Closing due to lack of feedback regarding the server-side. Feel free to reopen if we have more info.

**Comment by Kolli96** [comment] 2024-01-17 18:54
The same problem still exists in the latest version as well.  His phone One Plus Nord 3 5G.

**Comment by moving-bits** [comment] 2024-01-17 21:26
I've debugged a bit into this: Error comes from the parallel download of theme file "peruskartta.zip", which fails with a 404 error when being done while downloading a map file (but does work, when initiated manually).

Workaround is to download this theme once before downloading the map. (This can be done from the downloader.)
After that, downloading the map does work.

I've reopened the issue as a reminder to fix the underlying problem.

**Comment by Kolli96** [comment] 2024-01-18 07:01
> I've debugged a bit into this: Error comes from the parallel download of theme file "peruskartta.zip", which fails with a 404 error when being done while downloading a map file (but does work, when initiated manually).
> 
> Workaround is to download this theme once before downloading the map. (This can be done from the downloader.) After that, downloading the map does work.
> 
> I've reopened the issue as a reminder to fix the underlying problem.

The map download works if you start the download from the settings. (Like loading a map for the first time) If you start it from c:geo (update offline data->map data), you will get the error message. Even if you manually download the peruskartta.zip file, it won't help.

**Comment by moving-bits** [comment] 2024-01-18 08:26
Thanks @Kolli96 for the additional info, I'll look into this.
(My example was related to the initial download with neither map nor theme file being present yet.)

**Comment by Vike91** [comment] 2024-06-10 06:53
I'd rather not make a new thread as it's related to this issue, but the main map file (mtk_suomi.map) has completely disappeared from the downloadable map assets, leaving only the theme files available.

**Comment by bekuno** [comment] 2024-06-10 13:54
The website source is now:
~~~
                        <tr>
                            <td><a class="dl"
                                    href="https://kartat-dl.hylly.org/2024-06-08/mtk_suomi.map">mtk_suomi.map</a>
                            </td>
                            <td>4 GB</td>
                            <td>2024-06-08</td>
                        </tr>
~~~

This should further map to 
`    private static final Pattern PATTERN_MAP = Pattern.compile("href=\"(https:\\/\\/kartat-dl\\.hylly\\.org\\/(\\d{4}-\\d\\d-\\d\\d)\\/(mtk_suomi\\.map))\">mtk_suomi.map<\\/a>\\s*<\\/td>\\s*<td>(\\d+\\.\\d+ GB)<\\/td>"); // 1:url, 2:date yyyy-MM-dd, 3:file name, 4:size (string)`.
, isn't it?

Maybe a temporarily problem when switching to the updated map file?

**Comment by Kolli96** [comment] 2024-06-13 17:15
The map file got a new update in 11.6.2024 and the map now appears in the c:geo map download window.

**Comment by Kolli96** [comment] 2024-06-13 17:16
The map file received a new update on June 11, 2024, and the map is now displayed in the c:geo map download window.

**Comment by moving-bits** [comment] 2024-06-13 19:48
Thanks for the feedback. It's listed again, as the map size isn't a plain 4 GB any more, but 3.99 (having a decimal point, which the current code checks for). But we have prepared a fix, which will be part of an upcoming update.

**Closed** 2024-06-14 20:14 UTC
Labels: Bug

**Comment by Kolli96** [comment] 2024-07-01 05:37
And the same problem came back.  Is there something wrong with the file on that download page?

**Comment by SammysHP** [comment] 2024-07-01 10:06
See the comment above. A fix was already applied, but it's not included in the latest release.
