### ISSUE TITLE
Wrong default for maximum distance for calculating route

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#10598] opened 2021-05-12 07:51 UTC
## Bug description 

Not sure, whether this was done intentional, I did however just realize, that the default routing distance in Settings - Routing is set to 259km / 160,94mi.
I was triggered by a beta user reporting unresponsiveness of the app when setting a target, which is quite far away. It was caused by the routing engine needing a lot of time to render the route.

### Steps to reproduce the problem

- Install c:geo
- Run wizard
- Open Settings - Routing

### Actual result after these steps 

Calculate route shows 259km

### Expected result after these steps 

I believe the default value was set to something like 20km (?) before.
Maybe we could set it to 50km as a compromise. Longer maximum lengths might however cause delays on older devices.

## c:geo version 

2021.05.11-RC

## Reproducible 

Yes (tested on nightly)

**Comment by murggel** [comment] 2021-05-12 10:47
Probably due to my changes? I will have a look this evening...
@Lineflyer please assign to me

**Comment by murggel** [comment] 2021-05-14 09:39
That was indeed due to may changes in #10534. Now the default-value is converted twice.
I removed the checking against min and max on converting the default value, this is done on showing it to the user, once he changes it. Here I forgot to check / adapt at initializing the value from the saved settings.
With the changes of @moving-bits for unifying the seekbar preferences (PR #8579) the default-value was converted and checked against the min / max (which AFAICS are not set at that time) so it was set to 0. Since I now removed the checking on converting, it is now converted on getting and then one more time on setting the default value (`SeekbarPreference.onSetInitialValue` and `SeekbarPreference.onGetDefaultValue` ).
I would not convert the value on getting but I don't know, where this is used at all, because I am not so deep in the  mechanismus for storing / getting the default-values.

**Comment by murggel** [comment] 2021-05-16 20:35
@Lineflyer I can only reproduce it on master-branch, not on release-branch

**Comment by Lineflyer** [comment] 2021-05-16 20:43
Maybe I mixed up versions while writing that issue. Thats more than possible. Sorry.

**Comment by murggel** [comment] 2021-05-19 18:48
PR #10657 for fix in master

**Comment by murggel** [comment] 2021-06-03 20:08
@Lineflyer Can you please check and close it, if it is ok now?

**Closed** 2021-06-12 20:29 UTC
Labels: Bug, Google Play or Beta feedback
