### ISSUE TITLE
How to sort "List of lists" where the current Cache is stored in

### ISSUE THREAD

**Issue by MagpieFourtyTwo** [cgeo/cgeo#15478] opened 2024-03-17 13:07 UTC
> your remark about "Lists in groups" draw my attention: How is "show lists of current cache at top of list" supposed to work with grouped lists? Would be a deal breaker for me if these lists would remain hidden in their folders ... I would prefer to see these lists at the top, too ... with their entire "coloned name" ...

Yes, that's worth discussing. In the PR I merged this morning it is implemented such that groups with a selection in them are sorted atop, and inside any group selected items are sorted atop. If anything else is wished let's open a new issue for discussion.

_Originally posted by @eddiemuc in https://github.com/cgeo/cgeo/issues/15464#issuecomment-2002452556_

**Comment by MagpieFourtyTwo** [comment] 2024-03-17 13:30
> groups with a selection in them are sorted atop, and inside any group selected items are sorted atop

Good thing as first approach, but in fact a bit impractical: The reason (or at least mine) for grouping lists in folders, is to get a better overview. Which is in fact only (or especially then) needed, if you have a bunch of lists. Moreover a folder of lists most probably contains more than just a few lists (otherwise grouping would not make very much of a difference).

Now imagine folders whose listings are longer than the popup height and a cache, which is stored in several lists, which are organized in different folders (e. g. grouped by T-Rating-Ranges, Quality Levels, Regions, plan for next trips, or stuff which is needed for some special challenges). And now have a look at this cache's "List of lists": Even with the first (open) folder in view you will not be able to see the second list where he is stored in. Not even talked about the list, which is in the third or fourth folder ... got the picture?

This will again end up in scrolling and/or closing and opening folders - which will then be the same amount of or even more hassle as it was without any folders at all. Plus the (at least once on every search) effort to scroll down to the next folder resp. "non foldered list entry", just to find out if there are no more lists where he is stored in ...

TMALSS: With this strategy you *always* have to scroll (even if the cache is in just one list), instead of just getting all lists at a glance.

This I would highly prefer if the lists, where a cache is stored in, would *always* be listed at the top of the list. With the colon in their name. Otherwise IMO the "top of the list" feature makes no sense. And the grouping of lists even less ...

**Comment by MagpieFourtyTwo** [comment] 2024-03-17 14:48
> groups with a selection in them are sorted atop, and inside any group selected items are sorted atop

Just stumbled upon such a case - but the list was *not* at *the top of the "list of lists"* but just at it's "normal" position ... or did I misunderstood your remark and you just meant that the list, where the cache is stored in, is just sorted to the top of it's folder's list? This would make it's finding even harder and more cumbersome, cause you would *always* have to scoll through the entire list of lists and folders, cause right at the end there may be just another folder with a list, where the cache is stored in. Thus simple sorting the containing list to the start of the folder would bring nothing at all anyway ...

**Comment by eddiemuc** [comment] 2024-03-17 14:55
> > groups with a selection in them are sorted atop, and inside any group selected items are sorted atop
> 
> Just stumbled upon such a case - but the list was _not_ at _the top of the "list of lists"_ but just at it's "normal" position ...

I merged the PR just this morning, so the change wouldn't be in yesterday's nightly. 

Current implementation should look like in following example (opened for a cache which is currently in lists challenge:jasmer, challenge:unloved,  rating:hard and test - but not in any list of group/folder place or to log):
![image](https://github.com/cgeo/cgeo/assets/6909759/8257eb66-d24c-49ff-8f53-79282bc5a765)
![image](https://github.com/cgeo/cgeo/assets/6909759/e10dbaea-21bb-4225-8a70-8186d8e4b864)
![image](https://github.com/cgeo/cgeo/assets/6909759/4f450544-0c0f-4bca-a953-ee49b5c034a5)

**Comment by eddiemuc** [comment] 2024-03-17 15:00
If I understand your request correctly, you would want to see something like this in the above case:
![image](https://github.com/cgeo/cgeo/assets/6909759/94f694b1-b0a7-417c-a6b1-27245e1f4de6)
![image](https://github.com/cgeo/cgeo/assets/6909759/6b0d3c3a-2c9e-402b-b261-a9ea03fe4e08)
![image](https://github.com/cgeo/cgeo/assets/6909759/ea8b243f-353c-41dd-8ce7-ae5a9bd95631)

**Comment by eddiemuc** [comment] 2024-03-17 15:07
If this is wanted, it would become reality by mergin PR #15479

**Comment by MagpieFourtyTwo** [comment] 2024-03-17 15:25
> If I understand your request correctly, you would want to see something like this in the above case:

Yes, you read my mind (ok, most probably just the comment ;) ) - [this](https://github.com/cgeo/cgeo/issues/15478#issuecomment-2002500316) is exactly the way I was thinking of.
May be discussed if the ":" entries may *additionally* appear in their "real" group ... but this OTOH may lead to confusion ... I'm undecided in this point. But having all affected lists at the top would already be perfect (IMO).

**Comment by eddiemuc** [comment] 2024-03-17 15:30
> May be discussed if the ":" entries may _additionally_ appear in their "real" group ... but this OTOH may lead to confusion ... I'm undecided in this point. But having all affected lists at the top would already be perfect (IMO).

This would be a bigger thing because it would mess with my whole concept of selection lists in general... I never foresaw that one would want to have the same element appearing twice in the same selection list. Those occurences woould then have to be synced e.g. when you select one "appearance" the other "appearance" has to be selected too.

IMHO c:geo now has one of the most sophisticated/complex item selection concepts I know of.

**Comment by MagpieFourtyTwo** [comment] 2024-03-17 17:11
No problem, I'm absolutely fine with this solution.

**Comment by ztNFny** [comment] 2024-03-17 17:55
imho not too much time should be invested into this. Many of the extreme examples cited above will never happen (a cache in many lists and many lists in groups so that you have to scroll for several pages).

I like the solution "show groups with selected lists" (https://github.com/cgeo/cgeo/issues/15478#issuecomment-2002498818).

Showing the lists ungrouped (https://github.com/cgeo/cgeo/issues/15478#issuecomment-2002500316) creates an unexpected behaviour in UI by displaying the list differently depending on selection state. We'll get support requests: "the list is named correctly, why is it no suddenly not grouped anymore" - and this change will not only affect the selected list but also others if there's only 1 other list of that group remaining.

**Comment by moving-bits** [comment] 2024-03-17 18:04
I'd like to contradict: IMHO it's immensely useful to have the currently selected items at the top, and visible without having to open the groups first

**Comment by ztNFny** [comment] 2024-03-17 18:13
> I'd like to contradict: IMHO it's immensely useful to have the currently selected items at the top, and visible without having to open the groups first

I agree that it's useful to have the selected lists visibile. But afaict that's the case with https://github.com/cgeo/cgeo/issues/15478#issuecomment-2002498818, isn't it?
The groups are displayed at the top and open so the selection is visible.

Only if you have the cache in many lists that are in big groups will the selected lists not all be visible - but how likely is that scenario?

**Comment by eddiemuc** [comment] 2024-03-17 19:23
There are to be different opinions on this. I suggest to vote on PR https://github.com/cgeo/cgeo/pull/15479 to decide whether to merge or not (@ztNFny has already done so)

**Comment by bekuno** [comment] 2024-03-17 20:34
For me the second version looks easier to read than the first.
The checked items are in a separated block, no unchecked entry between.
Users which use the feature of grouped lists should be able to understand the list name with ":".

**Comment by MagpieFourtyTwo** [comment] 2024-03-17 22:02
> imho not too much time should be invested into this. Many of the extreme examples cited above will never happen (a cache in many lists and many lists in groups so that you have to scroll for several pages).

Nothing extreme about it, this is our normal usecase: I have about 90 lists, of which currently 60 are grouped in 8 folders (tendency upwards) and the largest group folder contains 37 lists. 

> I like the solution "show groups with selected lists" (#15478 (comment)).

This in fact completely spoils using lists, cause it's impossible to see and find the lists where a cache is stored in. Would have to drop my folder concept and go with plain lists again, it it really stays this way. Had another hard time today to locate lists ...

And I'm BTW not the only one who uses it this way. The ones who get the concept of list folders use it way more excessive than you may think.  ;)

**Comment by fm-sys** [comment] 2024-03-17 22:30
Maybe as a compromise, show the group twice? Once with the checked lists at the top and once further down...

**Comment by MagpieFourtyTwo** [comment] 2024-03-17 22:52
Following [2002509991](https://github.com/cgeo/cgeo/issues/15478#issuecomment-2002509991) this would mean a lot of work and a mayor change of concept.

**Comment by fm-sys** [comment] 2024-03-18 02:43
I'm suggesting to only let the group appear twice, not it's items... I think this is slightly different.

**Comment by eddiemuc** [comment] 2024-03-18 05:50
> I'm suggesting to only let the group appear twice, not it's items... I think this is slightly different. 

Do you mean to have a "special folder/group" at the top called e.g. "Current selected lists" with all selected lists in it? Or am I misunderstanding?

**Comment by eddiemuc** [comment] 2024-03-18 06:20
> I'm suggesting to only let the group appear twice, not it's items... I think this is slightly different. 

Or do you mean the following (from my example above)?

- have one folder `Selected from challenge`  with two entries `jasmer` and `unloved`
- have one folder `Selected from rating` with one entry `hard`
- both of them on top

**Comment by fm-sys** [comment] 2024-03-18 09:10
I thought of something like this... But maybe this just makes it even more messy...?


![grafik](https://github.com/cgeo/cgeo/assets/64581222/0139fda9-a673-46b9-b34d-1e08e68fe42a)

**Comment by MagpieFourtyTwo** [comment] 2024-03-18 11:47
> a "special folder/group" at the top called e.g. "Current selected lists" with all selected lists in it?

Good idea.  Which additionally may even fit the current concept, I could imagine.

BTW: First thought I had while thinking about such a special "Selected lists" folder was, that the contained lists should still show their "real" folder name. Otherwise it could be hard to distinguish between list names that only differ in folder name, like "HQ:Climbing" and "Tour:Climbing". Which can perhaps easily be achieved by "just" preceding the currently selected lists with a "special folder name" like "Selected lists:HQ:Climbing" and "Selected lists:Tour:Climbing". This way they would automatically appear in the "Selected lists" folder (which should always be on top, of course).

It's just that those "extended" list names must of course be handled in a special way:
- the prefix "Selected lists:" should be suppressed in the cache's ``Details`` page
- same in the two ``Pick a list`` dialogs
  (LongClick on bottom menu entry "Stored" and the ``Pick a list`` DropDown in the list view)

Side note: As a prefix which is *really* named like "Selected lists:" may lead to an additional NLS-challenge ;) it of course may be replaced by a special char or even NLS-string, which only in the GUI will be replaced by the matching translation.  But for the sake of clarity I just continue with the string itself.  ;)

Addendum:

WRT @ztNFny's comment about the possible visual flaw, when (after an automatic list rename, like described above) the previously "real" folder may be reduced from two to just one member, it could be a possible solution to not just rename (i. e. *move*) the list entry in question, but *add* a *second* "shadow list name" entry (i. e. *copy* it) to "Selected lists:\<realfolder\>:\<list\>". This way the selected list can safely appear twice (in its "real" folder plus in the "Selected lists" folder.  Moreover, in the latter it would even show up *with* its "real" folder name - and all this may probably even not collide with the current lists concept ...?  ;)

It's just that those "shadow list names" must of course be handled in a special way, too:
- manual creation of list names starting with "Selected lists" (resp. their NLS placeholder) must not be allowed
- lists with the special prefix "Selected lists:" must not show up in the ``Pick a list`` dialogs
- and they should not appear in the cache's ``Details`` page
- on adding a cache to a list, there would be two lists to maintain:
  the "real" one and the "shadow" list named "Selected lists:\<realfolder\>:\<list\>"
- same of course when removing a cache from a list

But, TBH, although this sounds like a really nice solution (with most probably the least number of support requests ;) ), I would nevertheless doubt that the probably rather low benefits of not having the mentioned visual flaw really justify the effort of maintaining the shadow list. Cause IMO it does not really make sense to have a folder with just two lists, as "grouped" they will occupy even more space (three lines), compared to just two if left alone.  Not even talking of the add. effort to open/close the folder to eventually see the lists. IMO folders only develop their real potential when containing a whole bunch of lists. And then this visual flaw will not appear anyway.

Therefore me personally would "simply" go with just the first idea, i. e. rename the selected list entries to "Selected lists:\<realfolder\>:\<list\>" plus stripping the "Selected lists;" prefix from the strings in the ``Pick a list`` dialogs - which BTW is in fact not really far away from the solution in [2002500316](https://github.com/cgeo/cgeo/issues/15478#issuecomment-2002500316), with "just" an add. folder name.  ;)

**Comment by moving-bits** [comment] 2024-03-18 21:56
> I thought of something like this... But maybe this just makes it even more messy...?

please don't, would be pretty confusing to have the same group headings twice, and you would loose the advantage to have all selected lists "on a view" (at least partally).

With regard to the next proposal (https://github.com/cgeo/cgeo/issues/15478#issuecomment-2003701032):

This is way (!) too over-engineered, IMHO, so much special handling, exceptions etc. - for what? We are still talking about a simple list selection...

IMHO we should stay with what is shown in the left screenshot in https://github.com/cgeo/cgeo/issues/15478#issuecomment-2003269751. Already very sophisticated, but easy to grab its meaning, and (hopefully) ok to handle code-wise.

**Comment by eddiemuc** [comment] 2024-03-19 05:59
My impression from discussion is currently that everything should be left as is now (left screenshot in https://github.com/cgeo/cgeo/issues/15478#issuecomment-2003269751). Am I interpreting this right? Then the issue could be closed.

Not quite sure if there are also votes for a single special group "selected items" at the top?

**Comment by moving-bits** [comment] 2024-03-19 06:56
> Not quite sure if there are also votes for a single special group "selected items" at the top?

What would be the use case for such an extra group?

**Comment by eddiemuc** [comment] 2024-03-19 07:34
> > Not quite sure if there are also votes for a single special group "selected items" at the top?
> 
> What would be the use case for such an extra group?

Would be just Look&Feel. Selected items would maybe not look so "lost" on top of all the groups. 

I am completely neutral to all of this. I just try to collect existing opinions as best as possible :-)

**Comment by MagpieFourtyTwo** [comment] 2024-03-19 09:41
May indeed be good as additional "explanation" to users who just occasionally stumble upon it, and of course looks a bit better.

But as a) list folders will most probably only be used by more experienced users anyway (esp. as setting them up is not really intuitive) and b) the check at the very left already makes pretty obvious what's going on (IMO), I would consider this "nice2have", but not really essential.

As for me, it solely depends on how much you enjoy putting this into practice, I was already happy [over here](https://github.com/cgeo/cgeo/issues/15478#issuecomment-2002542635). ;)

But *if* you implement this, it would be good if this folder would always be opened by default, cause everything else would make no sense in its context. (this is [Wilhelm Busch](https://www.gutzitiert.de/zitat_autor_wilhelm_busch_thema_wunsch_zitat_3490.html) talking ;) )

**Closed** 2024-03-19 12:00 UTC
Labels: Feedback required
