### ISSUE TITLE
[Nightly] All Popup windows: Texts are invisible

### ISSUE THREAD

**Issue by MagpieFourtyTwo** [cgeo/cgeo#15178] opened 2024-01-07 01:39 UTC
### Describe your problem!

All the popup windows I checked like for 'Select List', 'Select Filter', 'Create Filter', 'Add Filter Criteria' are all black (in dark mode) resp. completely white in light mode.  Seems as if the entries are still there, but their text is not visible.

### How to reproduce?

- Open map
- long tap on Filter icon in the Header or on the Lists icon in the bottom
- ...

### Actual result after these steps?

- in the popup window there's no text visible at all (although the entries seem to be there)

### Expected result after these steps?

- entries should be human readable  ;)

### Reproducible

Yes

### c:geo Version

2024.01.07-NB-c97a75c

### Additional Information

Select List via long tap on bottom 'Stored' icon:&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Choose Filter from 'Edit Filter' list:
![01 Select List via longtap on bottom 'Stored' icon](https://github.com/cgeo/cgeo/assets/9889015/4261450b-7b18-4489-b291-f4b38e389f16)&nbsp;&nbsp;&nbsp;![02 Chose Filter from 'Edit Filter' list](https://github.com/cgeo/cgeo/assets/9889015/782539fe-4ece-40d6-987c-d6a3f9e740c7)

Choose Filter via long tap on 'Filter' icon:&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Create Filter:
![03 Chose Filter via longtap on Filter icon](https://github.com/cgeo/cgeo/assets/9889015/fcd3695a-355a-4276-80ca-c2d630f45ebd)&nbsp;&nbsp;&nbsp;![04 Create Filter](https://github.com/cgeo/cgeo/assets/9889015/99ca7e55-a99d-409b-a6b0-c5cb57adfa5a)

Add Filter criterion:
![05 Add Filter criterion](https://github.com/cgeo/cgeo/assets/9889015/26d41b7e-97dc-4ec2-935a-33af4d96a993)

**Comment by MagpieFourtyTwo** [comment] 2024-01-07 02:02
Same applies to the filter critera themselves, as well as map's Quick Settings and Cache select popup:
![06 Filter Definition](https://github.com/cgeo/cgeo/assets/9889015/5f55790a-5e5b-4d11-930f-a74a8a80c4f8)
![08 Cache Popup](https://github.com/cgeo/cgeo/assets/9889015/8ef87a5e-2540-41a7-bb46-c46cdc8cb609)  ![09 Quick Settings](https://github.com/cgeo/cgeo/assets/9889015/2e0090d7-12a1-4af9-b9b9-c9c18309dacd)

**Comment by geocachermgo** [comment] 2024-01-07 08:01
Includes seach history (click on magnifier) on home screen.
![Screenshot_2024-01-07-08-52-03-759_cgeo geocaching](https://github.com/cgeo/cgeo/assets/43813636/b45fe4f5-c31f-44fe-bf58-379c8d95fed9)

**Comment by eddiemuc** [comment] 2024-01-07 08:15
I have the same effect during development sometimes when I switch between release and master branch since we introduced the new developer build package.

Usually in this situation In find that actually two versions of c:geo are installed on my (emulated) device.

To solve I reinstall both versions and reinstall a fresh copy.

I don't know the cause for this though.

@MagpieFourtyTwo could you check whether you have currently two versions of c:geo installed?

**Comment by fm-sys** [comment] 2024-01-07 09:05
I would be surprised if that is the actual cause, as nightly users are not affected by the different app Id. In fact, non of the builts ever done on CI use the changed ID, it should solely affact self-built development versions.

**Comment by MagpieFourtyTwo** [comment] 2024-01-07 09:10
> @MagpieFourtyTwo could you check whether you have currently two versions of c:geo installed?

There is just one version installed.
Never ever have built a second one with different ID, always just download and install "standard" nightly.

**Comment by eddiemuc** [comment] 2024-01-07 09:17
Forget the stuff I was blabbing about above . I found the bug and will provide a fix shortly

**Comment by eddiemuc** [comment] 2024-01-07 09:34
Fixed with PR #15179.

**Closed** 2024-01-07 09:43 UTC
Labels: Bug, Unverified

**Comment by fm-sys** [comment] 2024-01-07 09:45
Just merged the PR and triggered a new nightly build. It'll be available in around 10 minutes.

**Comment by MagpieFourtyTwo** [comment] 2024-01-07 10:15
Just installed 2024.01.07-NB1-9bd14f4 and on first sight it's working again.

Thx for the immediate fix and build!
