### ISSUE TITLE
Make map quick settings for caches/waypoints a two columned table

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#10817] opened 2021-06-01 20:56 UTC
## What function are you missing
With its recent additions and in combination with material theming and migration to a bottom sheet dialog, the map quick settings dialog got pretty long, too long for most screens to fit onto one page.

## Suggested solution
Put the "show" options for caches and waypoints into a two-column layout, like we have in the nice new "type" cache filter.

One possible order could be similar to this:

|first column|second column|
|---|---|
|__caches:__|own|
|found|w/offline log|
|disabled|archived|
|---|---|
|__waypoints:__|visited|
|original|parking|
|---|---|
|__Other:__|circles|

(With `---` indicating a thin horizontal divider line)

Below that table the other existing options (e. g. routing mode) will follow.

## Alternatives/workarounds
Other possible arrangements for above's options are described in #10809

**Comment by eddiemuc** [comment] 2021-06-02 06:46
@moving-bits I thought about a 2-col-layout as suggested by you too (grouping vertically, but with headline as "normal table cell".
Challenge is that due to the right-aligned checkbox design, the two-col-layout looks strange when on both sides is a checkbox but no vertical separator in the middle. Combining this with a "headline-as-tablecell" approach leaves the question where to put vertical separators and where not.

I can probably show this as a screenshot example when implementing two-col-layout

**Comment by moving-bits** [comment] 2021-06-02 07:55
I'm not bound to a specific layout orientation (horizontal / vertical), just keen for a more compact two column layout. (Your screenshot of the new type filter got me fixed ;-))

If it's easier to implement we can try a vertical orientation like you'd proposed in the linked issue, putting the five cache related options into one column, and the three waypoint + heading "Other" + circles option into the other column - would work, too, and would need only a vertical divider.

**Comment by eddiemuc** [comment] 2021-06-02 17:03
While working on this I discovered a problem: I can't find a clean way to assign theme styles to view elements created programatically.

While styles can be assigned to views via constructor, they don't seem to take over values set via theme (e.g. text color for a `TextView`). Even using a `ThemeContextWrapper` for creation does not seem to work.

Does anyone have experience with this problem and knows a solution? Large parts of the filter view are created dynamically and thus programatically...

**Comment by fm-sys** [comment] 2021-06-02 17:28
> Even using a `ThemeContextWrapper` for creation does not seem to work.

What I found on SO:


    Button b = new Button(new ContextThemeWrapper(this, R.style.ButtonText), null, 0);

 - Use a ContextThemeWrapper

AND

 - Use the 3-arguments constructor (won't work without this)
 
  _https://stackoverflow.com/a/50785619/13513639_

So for some reason you need to use the  3-arguments constructor to get tje themewrapper working

**Comment by fm-sys** [comment] 2021-06-02 17:41
Or there are third-party libraries for it, e.g. https://github.com/airbnb/paris

But it would be better if could avoid another dependency for sure

**Comment by eddiemuc** [comment] 2021-06-03 06:59
I dived deeper into this, and I fear I need some help how to apply theme/style in c:geo once more.

For testing purposes, I changed the four different "text colors" defined for dark theme (in night/colors_dark.xml) to very bright colors (red, blue, green, yellow):

![image](https://user-images.githubusercontent.com/6909759/120600814-7d5f8200-c449-11eb-8d32-b9fc4fefe0b9.png)

When opening c:geo now I expected to see those colors applied everywhere. Indeed this could be seen in cache details and (partly) in cache lists:

![image](https://user-images.githubusercontent.com/6909759/120600941-9e27d780-c449-11eb-864f-7e98ab3280b7.png)

But specifically in the map settings, the colors were NOT applied:
![image](https://user-images.githubusercontent.com/6909759/120600991-b13aa780-c449-11eb-9433-5afb67c640cd.png)

(don't mind the upper part, those are my experiments to add elements programmatically while taking over theme-defined styles).

Now I am stumped because I don't know how the "gray" color of the map settings elements (for subtitles and checkbox texts) is even determined. It seems not to come from the theme definition at least. 

Can someone help me out here?

**Comment by moving-bits** [comment] 2021-06-03 07:04
So far we have applied colors only in a few places - most colors still come from original material theme. So maybe you will need to add this to the specific layout (or a style referenced from it).

Or we could apply the `colorText` to our base theme, and only put a color into style/layout if something different is needed. (Probably the better way to go.)

**Comment by eddiemuc** [comment] 2021-06-03 07:17
@moving-bits even if this is the case I don't understand behaviour completely. Take the subtitle "Show on map:" in the screenshot above as example. In the lower part you can see how it is rendered from the layout-file using a gray text color - so guess would be that in material theme this is the default text color for dark mode.

But when I try to add the textview programmatically the text color always ends up white (as you can see in the upper part of the screenshot). I tried following approaches (in layout file the headline gets style "`map_quicksettings_subtitle`")

```
new TextView(new ContextThemeWrapper(activity, R.style.cgeo), null, 0, R.style.map_quicksettings_subtitle)

new TextView(new ContextThemeWrapper(activity, R.style.map_quicksettings_subtitle), null, 0, R.style.map_quicksettings_subtitle)

new TextView(new ContextThemeWrapper(activity, R.style.map_quicksettings_subtitle), null, 0)
```

Haven't been able to figure out where the gray resp. white is coming from...

**Comment by moving-bits** [comment] 2021-06-03 07:27
Hm, strange indeed. Will try to look into the code when I'm back at my dev machine later today.

**Comment by moving-bits** [comment] 2021-06-03 14:43
Looks like the grey is the material dialogs' default text color. So far I have not found a way to influence that app-wide, even not with using this hint, which sounded promising: https://stackoverflow.com/questions/56905297/how-to-change-materialalertdialog-text-color-properly/62099768#62099768

So for changing the `textColor` in the map settings I would add a `android:textColor="@color/colorText"` to the `TextView` in `map_settings_item.xml` for the items, and add the appropriate styling to `map_quicksettings_subtitle` style for the subheadings.

**Comment by fm-sys** [comment] 2021-06-03 16:32
Just a short question: Why do we need to edit the text color at all? IMHO it's just fine...

**Comment by eddiemuc** [comment] 2021-06-03 17:05
> Just a short question: Why do we need to edit the text color at all? IMHO it's just fine... 

My real question is: what is the correct way to apply the correct text colors (and other styles) when creating view items programatically. As explained above, using `ThemeContextWrapper` as well as the Style-argument-taking constructors does NOT work (tested only for text color which ends up white).
I mean it is easy enough to hard-code these things, but I am pretty sure this is not a good idea.

**Comment by eddiemuc** [comment] 2021-06-03 17:12
Following suggestion: I include `android:text color="@colors/color text"` into style `map_quicksettings_subtitle`, and I do the same thing for all other layout aspects (text size etc) for all styles needed in programatic view creation. As of now I think this is the cleanest way to go, and we would not depend on rather "randomly correct fallthroughs" selected by underlying themes and styles any more.

Certainly better than program things like `textView.setTextColor()` I guess

**Comment by Lineflyer** [comment] 2021-06-03 17:18
Isnt the background color the real problem for the map quick settings?
Maybe the text color is fine once we apply the sam background as for the rest of the app?

**Comment by eddiemuc** [comment] 2021-06-03 17:19
@moving-bits and thanks for your analysis! I assume that the default text color of our theme "cgeo" (and it's parents) is white, which would explain why my programmatic attempts ended up in white text color. Whereas the other texts are gray due to this being the default color for material Dialogs. This is at least how I explain to myself now the observed behavior.
All the more reason to explicitly set text color in our styles to keep in control.

Would it make sense to set a system-wide default text color for our theme? E.g. adding `android:textColor="@colors/colorText` in the main cgeo theme? Maybe same for other things like sizes or line spacing?

**Comment by eddiemuc** [comment] 2021-06-03 17:22
> Isnt the background color the real problem for the map quick settings?
> Maybe the text color is fine once we apply the sam background as for the rest of the app?

Background color and text color are set independently from each other.
Also, textColor was just an example which is easy to observe. The same problem might happen with other layout properties as well e.g. text size, line spacing etc.

**Comment by fm-sys** [comment] 2021-06-03 17:27
> and we would not depend on rather "randomly correct fallthroughs"

I would definitely not call the "material" theme a randomly fallthrough. There are probably good reasons why the theme was styled this way. So we should only overwrite attributes where it's necessary, because the whole idea of using the material theme was for explicitly simplifying our styles definitions.

**Comment by moving-bits** [comment] 2021-06-03 17:29
> Would it make sense to set a system-wide default text color for our theme? E.g. adding `android:textColor="@colors/colorText` in the main `cgeo` theme? Maybe same for other things like sizes or line spacing?

I had tried that for both `textColor` and `textSize`. IIRC it did work for `textColor` (and could help avoid having to add `textColor` attribute to each and every style manually), but with adding `textSize` as well, it also reduced the dialogs' headers text size.
Then came some other task and I forgot to either implement only `textSize` in global theme or find a way to set a bigger headings `textSize` for all dialogs (which is somewhat similar to the problem described above and to the problem of consistent background coloring for dialogs, described somewhere else).

So let's either add `textColor` only to our global c:geo theme, or find a way to globally adjust dialogs, add both `textSize` and `textColor` globally, and adjust `textSize` for dialog headers globally.

**Comment by eddiemuc** [comment] 2021-06-03 18:12
> > and we would not depend on rather "randomly correct fallthroughs"
> 
> I would definitely not call the "material" theme a randomly fallthrough... So we should only overwrite attributes where its necessary...

I agree, but then we either haven't integrated it the right way or we don't use things as intended by material.io. because right now we get different text colors depending on the way we add views, and this can't be right I assume. I am willing to take another exit out of this (which does not involve setting colors explicitly in styles), but I currently don't see any. Setting a global "default" text color might be a way to keep the impact small though.

**Comment by MagpieFourtyTwo** [comment] 2021-06-03 19:08
Heretic question: Why not just drop the checkboxes and use the same style as for icons and routing style?
If there is just one word like ``Found``, which is grey for "Off" resp. "don't show" and orange for "show"?

**Comment by MagpieFourtyTwo** [comment] 2021-06-03 19:09
This would save even more space, and the "column problem" will be "solved", too.

**Comment by moving-bits** [comment] 2021-06-03 20:39
@eddiemuc 
Good news and bad news...

First the good one: I got `MaterialAlertDialog` theming to work ;-)
It looks like this:

In the base theme add `<item name="materialAlertDialogTheme">@style/materialAlertDialogTheme</item>`.

Define the alert dialog theme and the corresponding styles:

```
<style name="materialAlertDialogTheme" parent="ThemeOverlay.MaterialComponents.MaterialAlertDialog">
    <item name="materialAlertDialogTitleTextStyle">@style/alertDialogTitleTextStyle</item>
    <item name="materialAlertDialogBodyTextStyle">@style/alertDialogBodyTextStyle</item>
</style>

<style name="alertDialogTitleTextStyle" parent="MaterialAlertDialog.MaterialComponents.Title.Text">
    <item name="android:textSize">@dimen/textSize_headingPrimary</item>
    <item name="android:textColor">@color/colorTextHeadline</item>
    <item name="android:textStyle">bold</item>
</style>

<style name="alertDialogBodyTextStyle" parent="MaterialAlertDialog.MaterialComponents.Body.Text">
    <item name="android:textSize">@dimen/textSize_detailsPrimary</item>
    <item name="android:textColor">@color/colorText</item>
</style>
```

This actually works, for example for the list picker coming from the main screen.

I'll prepare a PR for this.

And now for the bad news:

I have not found a way yet to make it work for customized alert dialogs. As soon as you set your own custom view, the above mentioned theming gets ignored. Looks like to have to apply those styles/themes to your custom layout manually.

**Comment by eddiemuc** [comment] 2021-06-03 22:02
@moving-bits great news overall I think! I think this saves us at least a major part of applying these things on a per-dialog/layout/Style-Base! Thanks for all your efforts!

**Comment by eddiemuc** [comment] 2021-06-04 13:41
![image](https://user-images.githubusercontent.com/6909759/120810373-45406800-c54b-11eb-9f7d-acf2574432e2.png)

**Comment by eddiemuc** [comment] 2021-06-04 13:41
PR will follow

**Closed** 2021-06-04 16:38 UTC
Labels: Feature Request, Frontend Design
