### ISSUE TITLE
Cannot connect and authenticate to geocaching.com

### ISSUE THREAD

**Issue by sgobance** [cgeo/cgeo#5800] opened 2016-06-23 09:30 UTC
##### Detailed steps causing the problem:
- Opening c:geo

##### Actual behavior after performing these steps:
At the bottom of the main screen, the panel displays: "geocaching.com - Logging in..." and c:geo never manages to log into geocaching.com. If I manually check to log in, in the settings panel, I get the error message: "Login failed: Unable to contact Geocaching.com. The website may be down or your internet connection not working..". If I go on geocaching.com website with my android browser, it works properly... The problem only occurs within cgeo.

##### Expected behavior after performing these steps:
I should be logged into geocaching.com.

##### Version of c:geo used:
2016.06.09

##### Is the problem reproducible for you?
Yes

##### System information:
```
Attach system information here if available (see c:geo menu -> About c:geo -> System)
--- System information ---
Device: SM-G386F (afyonltexx, samsung)
Android version: 4.2.2
Android build: JDQ39.G386FXWUAOI2
Cgeo version: 2016.06.09
Google Play services: enabled
Low power mode: inactive
Compass capabilities: yes
Rotation vector sensor: absent
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: magnetometer & accelerometer
Hide own/found: true
Map strategy: auto
HW acceleration: enabled (default state)
System language: fr_FR (cgeo forced to English)
Geocaching sites enabled:
- geocaching.com: not logged in (Logging in…)
Installed cgeo plugins:  none
--- End of system information ---


##### Other comments and remarks:

**Comment by kumy** [comment] 2016-06-23 09:32
On the 2 phone I have here:
* One is failing:
```
--- System information ---
Device: GT-I9305 (m3xx, samsung)
Android version: 4.4.4
Android build: cm_i9305-userdebug 4.4.4 KTU84Q 8142461998 test-keys
Cgeo version: 2016.06.09
Google Play services: enabled
Low power mode: inactive
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: rotation vector
Hide own/found: false
Map strategy: auto
HW acceleration: enabled (default state)
System language: fr_FR
Geocaching sites enabled:
- geocaching.com: not logged in (Connexion…)
Installed cgeo plugins:  none
--- End of system information ---
```

One is working:
```
--- System information ---
Device: m8 (cm_m8, htc)
Android version: 5.1.1
Android build: cm_m8-userdebug 5.1.1 LMY48Y a4d1ba3b73 test-keys
Cgeo version: 2016.06.17-NB-128a15b
Google Play services: enabled
Low power mode: inactive
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: rotation vector
Hide own/found: false
Map strategy: auto
HW acceleration: enabled (default state)
System language: en_US
Debug mode active: no
Geocaching sites enabled:
geocaching.com: Logged in (Login OK) / PREMIUM
Installed cgeo plugins: none
--- End of system information ---
```

**Comment by SammysHP** [comment] 2016-06-23 09:34
@sgobance 
Just out of curiosity: Can you please open this URL in the Android browser? https://www.geocaching.com/login/default.aspx
Please click on it (or make sure that you open the https version) and report if it works.

**Comment by kumy** [comment] 2016-06-23 09:36
I've downgraded my "working" phone to 2016.06.09 and it still work.

**Comment by sgobance** [comment] 2016-06-23 09:37
@SammysHP 
It does not work under Android Browser but it works under Google Chrome on my phone !

**Comment by SammysHP** [comment] 2016-06-23 09:39
@sgobance 
geocaching.com requires at least Android 4.4, see https://www.ssllabs.com/ssltest/analyze.html?d=www.geocaching.com. This is nothing we can change. Groundspeak decided to allow only modern encryption technology and forces an encrypted connection since a few months ago.

**Comment by sgobance** [comment] 2016-06-23 09:43
Strange, because I have the same problem with my Samsung Tab Pro tablet which is under Android 4.4.2 !

**Comment by SammysHP** [comment] 2016-06-23 10:06
Some info:

Supported protocols: https://developer.android.com/reference/javax/net/ssl/SSLSocket.html
Conclusion: Minimum Android 4.1 with code modifications in c:geo, should work fine with Android 5.0 (!)

How to modify our code: http://blog.dev-area.net/2015/08/13/android-4-1-enable-tls-1-1-and-tls-1-2/

**Comment by WulfmanDo** [comment] 2016-06-23 10:24
Since this morning i canot login to geocaching.com by c:geo. ( the last months it worked fine)
 
i check :  the URL in the Android browser ( https://www.geocaching.com/login/default.aspx ) it work fine i can login and go to the site.
I test the Geocaching.App it worked fine, too.
I use a acer Tab with Android 4.2.2

the same problem i have on a Samsung S1 smartphone wirh android 2.3.3.

**Comment by kumy** [comment] 2016-06-23 10:34
I really think we should publish a notification @Lineflyer

**Comment by rsudev** [comment] 2016-06-23 11:03
Notification published.
@kumy @samueltardieu When sending the notification first time, sam-1 failed with 'curl not available'. Therefore i temporarily disabled those nodes. can you check how the configuration should change to bind notifications to master always?

**Comment by yellowduck** [comment] 2016-06-23 11:31
I have the same problem - unable to login since this morning. I'm using an older build
2016.03.10-NB-da0060c.

**Comment by kumy** [comment] 2016-06-23 13:21
ping @samueltardieu maybe you know well this part of code.

**Comment by Krakonos** [comment] 2016-06-23 15:32
Well, my Xiaomi 4.4.4 doesn't work. Friend of mine tested on 4.2.1 and it seems to work.

**Comment by kumy** [comment] 2016-06-23 16:06
> When sending the notification first time, sam-1 failed with 'curl not available'. Therefore i temporarily disabled those nodes. can you check how the configuration should change to bind notifications to master always?

**Comment by sgobance** [comment] 2016-06-23 16:56
I do not know what happened but it works again for me now. Any rollback on Groundspeak's side ?

**Comment by kumy** [comment] 2016-06-23 17:17
@sgobance I'll launch the ssllabs test again, and look for any difference.

**Comment by kumy** [comment] 2016-06-23 17:18
Confirmed, There has been a rollback on groundspeak side.

**Comment by rsudev** [comment] 2016-06-23 17:19
Shall I switch off the notification again?

**Comment by kumy** [comment] 2016-06-23 17:20
@rsudev as you wish. No objection on my side.

**Comment by rsudev** [comment] 2016-06-23 17:44
Notification reset...

**Comment by Lineflyer** [comment] 2016-06-23 19:39
Lets keep this open and wait a few days and/or decide if we want to be prepared (e.g. by implementing something as sugested in the link of @SammysHP)

**Comment by Lineflyer** [comment] 2016-06-29 20:43
IMHO the situation got stable right now.
I suggest we keep the suggested workaround documented here but close this issue without further actions. Objections?

**Comment by rsudev** [comment] 2016-06-29 20:47
Fine with me

**Closed** 2016-06-30 18:28 UTC
Labels: Bug, high
