### ISSUE TITLE
Auto extract coordinates from text

### ISSUE THREAD

**Issue by Bananeweizen** [cgeo/cgeo#3410] opened 2013-11-02 16:06 UTC
If a text contains coordinates, then our context menu should have additional entries to copy each recognized coordinate. Currently one has to copy the complete text into another editor, extract the part with the coordinate and copy it back.

**Comment by Lineflyer** [comment] 2017-01-18 20:41
In fact not only related but a duplicate of #1249

**Closed by Lineflyer** 2017-01-18 20:41 UTC
Labels: Feature Request
