### ISSUE TITLE
Can't draw "proximity circles" on new map version.

### ISSUE THREAD

**Issue by alan666notb** [cgeo/cgeo#7048] opened 2018-06-03 18:27 UTC
I'm using the latest beta release 2018.05.28-RC

There's no longer an option to draw the 161m 'proximity circles' around final locations / physical waypoints.
The option is still there under the V3 version maps.

Need to have this reinstated.

**Comment by SammysHP** [comment] 2018-06-03 18:29
Duplicate of #5885.

**Closed by SammysHP** 2018-06-03 18:29 UTC
