### ISSUE TITLE
Copy selected text

### ISSUE THREAD

**Issue by Eselter** [cgeo/cgeo#4771] opened 2015-03-28 01:57 UTC
Future request:
Please add support for select part of text in cache desc and strip html tags while copying.

**Comment by SammysHP** [comment] 2015-03-28 07:51
Duplicate, but I'm on mobile currently and cannot find it.

**Comment by rsudev** [comment] 2015-03-28 08:26
Duplicate of #3819, closing here

**Closed by rsudev** 2015-03-28 08:26 UTC
