### ISSUE TITLE
Export/Import of waypoints fails or incomplete

### ISSUE THREAD

**Issue by Pentatops** [cgeo/cgeo#8409] opened 2020-06-06 08:14 UTC
This are two bugs:
a) gpx export does not export waypoints without assigned coordinates
b) Gpc export/import does not transfer the "already visited" flag

To Reproduce:
1. create a new empty list of caches
2. load GC84G97, GC8GWH8 and GC84VDM from geocaching.com into the list
3. GC84G97: mark the waypoints "das Tier" and "Wegweiser" as visited
4. do a gpx export of the list (with options transfer and include status)
5. transfer the gpx file to another 2nd device (I used a cloud service)
6. import the gpx file into e new list
==> GC84G97 is missing the waypoints without coordinates, e.g. "Bild 1"
7. Go back to the first device
8. GC84G97: remove the flag "visited" from waypoint "das Tier" and set the flag "visited" at waypoint "Heermannshütte"
9. same export-import as above to the second device
==> the "visited" flags on the 2nd device remain unchanged neither has the flag of "Heermannshütte" be added nor the flag of "das Tier" be removed

Expected behavior/state after performing these steps:
- all waypoints should be transferred, independent if they have valid coordinates
- if, in the source, a waypoint has the flag "visited" set this setting should be transferred, too.

Version of c:geo used: 2020.04.25 on all devices

Is the problem reproducible:
Yes;

**System information:**
 I reproduced it on several different devices (Samsung, ASUS) using different Android versions (4.2; 5.0.1; 7.0; 10)

```
Attach system information of one of the 2nd devices:
Device: P00A (WW_P00A, asus)
Android version: 7.0
Android build: NRD90M.WW_P00A-V5.3.20-20180809
c:geo version: 2020.04.25
Google Play services: enabled - 20.18.17 (040400-311416286)
Low power mode: inactive
Compass capabilities: yes
Rotation vector sensor: absent
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: magnetometer & accelerometer
Hide caches: own/found
Hide waypoints: -
HW acceleration: enabled (default state)
System language: de_DE
System date format: dd.MM.yy
Debug mode active: no
System internal c:geo dir: /data/user/0/cgeo.geocaching (3,0 GB free) internal
User storage c:geo dir: /storage/emulated/0/cgeo (3,0 GB free) external non-removable
Geocache data: /storage/3934-3030/Android/data/cgeo.geocaching/files/GeocacheData (7,3 GB free) external removable
Database: /storage/emulated/0/Android/data/cgeo.geocaching/files/databases/data (108,1 MB) on user storage
Fine location permission: granted
Write external storage permission: granted
Geocaching sites enabled:
   geocaching.com: Logged in (Anmeldung OK) / PREMIUM
Geocaching.com date format: MM/dd/yyyy
Installed c:geo plugins:  none

Thanks for your help

Gunther

**Comment by MagpieFourtyTwo** [comment] 2020-06-15 12:44
[...]
>     6. import the gpx file into e new list
>        ==> GC84G97 is missing the waypoints without coordinates, e.g. "Bild 1"

Workaround: After import of a cache via GPX you have to refresh the listing anyway, in order to get all the information which is not (and can possibly not be) stored in the GPX. The waypoints you mentioned should be created on this refresh (you may want to upload changed coordinates and a poss. existing personal note prior to refreshing).

[...]
>     9. same export-import as above to the second device
>        ==> the "visited" flags on the 2nd device remain unchanged

I would consider this as a feature, as export/import usually is for forwarding a listing (esp. notes and changed coords) to a different user, who has not necessarily walked in my footprints (otherwise s/he would have marked them as visited anyway ;) ), so these WPs are in fact "not visited" now for real ... or did I miss the point?

**Comment by Pentatops** [comment] 2020-06-15 17:52
Thanks for the reply.
And for the workaround.
You are right, transferring the waypont status flag is not a must, depending of the way this funktion is used. You didn't miss the point ....
My workaround ist to not transfer the data by a gpx file but using the database backup instead. That works fine.

Thanks for your help

Gunther

**Comment by Pentatops** [comment] 2020-06-15 17:53
Using the database backup instead of a gpx file solves my issues.

**Comment by Lineflyer** [comment] 2020-06-15 19:48
Lets leave this open, as the problem is still valid.
If I export a GPX from cgeo I would expect to have same data after importing it again into cgeo.

There is AFAIR already an issue about missing attributes and a generic migration to a GPX based backup. I will double check

**Comment by jakedot** [comment] 2020-07-20 08:25
As far as I can remember,  I've experienced issues also in regards to changed coordinates, as importing solved mysteries a friend exported from c:geo didn't include the "final waypoint" flag and the original position waypoints. I'm not sure if they aren't exported or not imported correctly, but I think gpx from e.g. GSAK worked fine so it's probably the export.

**Comment by murggel** [comment] 2020-09-29 18:19
@Lineflyer 
While working on #6914 I stumpled over this issue and I saw a TODO inside the code for new c:geo-extension.
I tried to add an extension-parameter for empty / invalid coords, and export those waypoints and react on import.

The issue is assigned to you, are you working on it?

**Comment by Lineflyer** [comment] 2020-09-29 18:32
@murggel No, the assignment was done in order trying to retest it and provide more information, which I forgot to do. 

Feel free to work on it.

**Comment by murggel** [comment] 2020-10-04 21:57
Created PR

**Closed** 2020-10-19 17:51 UTC
Labels: Bug
