### ISSUE TITLE
Login from GrapheneOS

### ISSUE THREAD

**Issue by Des-Conocido-De** [cgeo/cgeo#15791] opened 2024-06-15 23:55 UTC
### Describe your problem!

The usual.

Login failed. Service requires a Captcha...

### How to reproduce?

Install from github or play store, no diff

Jump through install hoops.

Input login details. Fail.

Login through website. Many attempts before getting captcha, but eventually get in. Do a bunch of stuff inside portal, even open portal successfully through another browser.

Return to app, try again. Fail.

Restart app, try again, same error.

### Actual result after these steps?

Can't login

### Expected result after these steps?

Can login

### Reproducible

Yes

### c:geo Version

2024.06.02

### System information

```text
Services:
-------
- Geocaching sites enabled: None
- Last login error on geocaching.com: Failed to log in to geocaching.com due to captcha required (2024-06-16 09-41)
- Routing: internal / BRouter installed: false

Permissions
-------
- ACCESS_COARSE_LOCATION: granted
- ACCESS_FINE_LOCATION: granted
- READ_CONTACTS: DENIED
- WRITE_EXTERNAL_STORAGE: DENIED
- POST_NOTIFICATIONS: granted

Paths
-------
- System internal c:geo dir: /data/user/0/cgeo.geocaching (28.0 GB free) v3 internal isDir(7 entries)
- Legacy User storage c:geo dir: /data/user/0/cgeo.geocaching (28.0 GB free) v3 internal isDir(7 entries)
- Geocache data: /storage/emulated/0/Android/data/cgeo.geocaching/files/GeocacheData (28.0 GB free) v3 external non-removable isDir(1 entries)
- Internal theme sync (is turned off): /data/user/0/cgeo.geocaching/MapThemeData (28.0 GB free) v3 internal isDir(0 entries)
- Map render theme path: 
- Public Folders: #12
  - BASE: content://com.android.externalstorage.documents/tree/primary:Download/cgeo/document/primary:Download/cgeo (av:true, files:>=0, size:>=0 B, free:>=28.0 GB)
  - OFFLINE_MAPS: content://com.android.externalstorage.documents/tree/primary:Download/cgeo/document/primary:Download/cgeo/maps (av:true, files:>=0, size:>=0 B, free:>=28.0 GB)
  - OFFLINE_MAP_THEMES: content://com.android.externalstorage.documents/tree/primary:Download/cgeo/document/primary:Download/cgeo/maps/_themes (av:true, files:>=0, size:>=0 B, free:>=28.0 GB)
  - OFFLINE_MAP_SHADING: content://com.android.externalstorage.documents/tree/primary:Download/cgeo/document/primary:Download/cgeo/maps/_hgt (av:true, files:>=0, size:>=0 B, free:>=28.0 GB)
  - LOGFILES: content://com.android.externalstorage.documents/tree/primary:Download/cgeo/document/primary:Download/cgeo/logfiles (av:true, files:>=0, size:>=0 B, free:>=28.0 GB)
  - GPX: content://com.android.externalstorage.documents/tree/primary:Download/cgeo/document/primary:Download/cgeo/gpx (av:true, files:>=0, size:>=0 B, free:>=28.0 GB)
  - BACKUP: content://com.android.externalstorage.documents/tree/primary:Download/cgeo/document/primary:Download/cgeo/backup (av:true, files:>=0, size:>=0 B, free:>=28.0 GB)
  - FIELD_NOTES: content://com.android.externalstorage.documents/tree/primary:Download/cgeo/document/primary:Download/cgeo/field-notes (av:true, files:>=0, size:>=0 B, free:>=28.0 GB)
  - SPOILER_IMAGES: content://com.android.externalstorage.documents/tree/primary:Download/cgeo/document/primary:Download/cgeo/GeocachePhotos (av:true, files:>=0, size:>=0 B, free:>=28.0 GB)
  - ROUTING_BASE: content://com.android.externalstorage.documents/tree/primary:Download/cgeo/document/primary:Download/cgeo/routing (av:true, files:>=8, size:>=87.7 KB, free:>=28.0 GB)
  - ROUTING_TILES: content://com.android.externalstorage.documents/tree/primary:Download/cgeo/document/primary:Download/cgeo/routing/segments4 (av:true, files:>=0, size:>=0 B, free:>=28.0 GB)
  - TEST_FOLDER: file:///data/user/0/cgeo.geocaching/files/unittest (av:true, files:>=0, size:>=0 B, free:>=28.0 GB)
- PersistedDocumentUris: #2
  - PROXIMITY_NOTIFICATION_FAR: null
  - PROXIMITY_NOTIFICATION_CLOSE: null
- Persisted Uri Permissions: #1
  - content://com.android.externalstorage.documents/tree/primary:Download/cgeo (16 June, 9:33 am):RW
- Database: /data/user/0/cgeo.geocaching/databases/data (v103, Size:212.0 KB) on system internal storage
```

### Additional Information

RESOLVED.

Seems geocaching.com is preventing authorisation login from devices behind VPNs (grrr), but not via website.

I've continued this issue report to help others.

**Comment by eddiemuc** [comment] 2024-06-16 04:47
Duplicate of eg #9056, see discussion there.

The problem is well known and documented, eg here: [FAQ "Login problems", chapter "5. Possible error messages", Headline "Login failed: Captcha required"](https://cgeo.droescher.eu/en/loginproblems#login_failedcaptcha_required)

As of now I fear there's nothing we can do about that unfortunately

**Closed** 2024-06-16 04:48 UTC
Labels: Duplicate, Connector GC
