### ISSUE TITLE
Map: scale jump

### ISSUE THREAD

**Issue by geocachermgo** [cgeo/cgeo#8912] opened 2020-08-30 09:43 UTC
**Describe the bug:**
If the map is changed (e.g. Google map and Offline OSM combined) the scale changes drastically (300m to 2km)

**To Reproduce:**
1. Live map
2. Zoom to area
3. Change map source
4. Change back to original source

**Actual behavior/state after performing these steps:**
Scale of maps jumps when changing map source

**Expected behavior/state after performing these steps:**
Scale of maps is kept

**Version of c:geo used:**
2020.08.30-NB-8e727e3

**Is the problem reproducible:**
Yes 

**Screenshots:**
see below.

**System information:**
--- System information ---
Device: MI 8 (dipper, Xiaomi)
Android version: 10
Android build: QKQ1.190828.002 test-keys
c:geo version: 2020.08.30-NB-8e727e3
Google Play services: disabled - 20.33.14 (120400-327249014)
Low power mode: active
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: rotation vector
Hide caches: own/found 
Hide waypoints: -
HW acceleration: enabled (default state)
System language: de_DE
System date format: dd.MM.yy
Debug mode active: no
System internal c:geo dir: /data/user/0/cgeo.geocaching (89,5 GB free) internal
User storage c:geo dir: /storage/emulated/0/cgeo (89,5 GB free) external non-removable
Geocache data: /storage/emulated/0/Android/data/cgeo.geocaching/files/GeocacheData (89,5 GB free) external non-removable
Database: /data/user/0/cgeo.geocaching/databases/data (8,8 MB) on system internal storage
Fine location permission: granted
Write external storage permission: granted
Geocaching sites enabled:
   geocaching.com: Logged in (Anmeldung OK) / PREMIUM
Geocaching.com date format: MM/dd/yyyy
Installed c:geo plugins:  none
BRouter connection available: false
--- End of system information ---

**Comment by geocachermgo** [comment] 2020-08-30 09:50
![Screenshot_2020-08-30-11-48-21-773_cgeo geocaching](https://user-images.githubusercontent.com/43813636/91656180-f7c43580-eab6-11ea-9117-9f3701a56ec0.jpg)
![Screenshot_2020-08-30-11-48-11-091_cgeo geocaching](https://user-images.githubusercontent.com/43813636/91656182-fb57bc80-eab6-11ea-86e0-c1129e0a2994.jpg)

**Comment by Lineflyer** [comment] 2020-08-30 10:08
Duplicate of #7953

**Closed** 2020-08-30 10:08 UTC
Labels: Bug, Unverified
