### ISSUE TITLE
Icons are not updated

### ISSUE THREAD

**Issue by Vosoni** [cgeo/cgeo#15940] opened 2024-08-01 16:47 UTC
### Describe your problem!

After a cache is logged, its icon on the map is not automatically updated. I have to update it manually so that it turns into a yellow smiley. Also changing the filter settings has no effect until I close and reopen the map.

### How to reproduce?

1. Activate a filter that hides found caches.
2. Log a cache that appears on the map.
3. The icon remains unchanged.

### Expected result after these steps?

The cache icon should change after the cache is logged. It should disappear from the map if the filter is set not to show found caches.

### Reproducible

Yes

### c:geo Version

2024.07.07

**Comment by eddiemuc** [comment] 2024-08-01 17:11
Possibl a duplicate of https://github.com/cgeo/cgeo/issues/15894 ?

**Comment by Vosoni** [comment] 2024-08-01 17:38
Possibly, looks like the same issue.

**Closed** 2024-08-01 18:28 UTC
Labels: Bug, Unverified
