### ISSUE TITLE
[Unified map] switching between Google/OSM maps scrolls and zooms to a random place

### ISSUE THREAD

**Issue by ztNFny** [cgeo/cgeo#14885] opened 2023-11-25 12:42 UTC
1. View a list
2. zoom in somewhere
3. Switch to other map type (Google vs OSM (online/offline doesn't matter))

-> map zooms out and is centered either on current position or somewhere random

**Comment by moving-bits** [comment] 2023-11-25 15:58
Can't reproduce currently. I've opened a list with about 60 caches, zoomed in and panned the map to one of the outer places, so that a single waypoint was visible in one of the corners. Then I switched the map from Google Maps to OSM online - worked fine. Moved the map a bit so that two waypoints became visible, then switched back to Google Maps - worked as well.
So there seems to be another factor being involved.

**Comment by ztNFny** [comment] 2023-11-25 16:17
https://github.com/cgeo/cgeo/assets/1258173/35cf04e2-81db-4a5d-89c2-d2681f15defc

Here's a video of Google -> OSM switch

**Comment by ztNFny** [comment] 2023-11-25 16:19
And OSM zoomed to Google Maps

https://github.com/cgeo/cgeo/assets/1258173/05cdaa66-19f2-43d7-8e8d-6a5f34941693

**Comment by moving-bits** [comment] 2023-11-26 09:03
Could it be that there are caches in this list, which have waypoints outside of Europe? (Or, to be more specific, some waypoint a couple of 1000 kms away?)

Displaying a list calculates the outer viewport to display all caches, and zooms & pans the map according to it. I noticed that Google Maps cannot zoom out far enough (anymore?), if one of the bounds is in USA west coast, another one somewhere in Europe. This looks like map being zoomed and panned to random.

For testing: I have a list here containg a couple of waypoints over here + a single one in Seattle. => bam!

**Comment by ztNFny** [comment] 2023-11-26 09:44
Nope... I created a list with 1 UDC only which has only 1 WP.
Going to map view i get an unexpected zoom level (way too far out), switching maps it jumps to "somewhere".

My expectation (both being true on old map):
- for displaying list: map should be zoomed to "just" include all caches
- for switching map: kep whatever viewpoint is currently set

https://github.com/cgeo/cgeo/assets/1258173/9bec803d-dcb9-4364-b1bb-3f34c3d2a046

**Comment by ztNFny** [comment] 2023-11-26 09:53
https://github.com/cgeo/cgeo/assets/1258173/fe2a0780-3daf-4d17-ac35-97c304265ad1

Here's another funny scenario. Navigating to a cache with 2 WPs, both very close together, but far away from me.
Initial zoom level doesn't make any sense at all.
And randomly map is completely broken, the last attempt in the video, where map apparently doesn't init correctly as i can't zoom or go to my location.

**Comment by ztNFny** [comment] 2023-11-26 13:53
> Edit: FYI: Zooming for search result is done in `UnifiedMapActivity.onMapReadyTask` in the `case UMTT_SearchResult:` block. Add a log statement to crosscheck the resulting viewport.

Log.e("UnifiedMapViewpoint:getGeocodes: " + mapType.searchResult.getGeocodes().size());
Log.e("UnifiedMapViewpoint:viewport2: " + viewport2.toString());

results in

2023-11-26 14:51:38.227  8487-8487  cgeo                    cgeo.geocaching                      E  [main] UnifiedMapViewpoint:getGeocodes: 1
2023-11-26 14:51:38.228  8487-8487  cgeo                    cgeo.geocaching                      E  [main] UnifiedMapViewpoint:viewport2: (N 52° 31.172' · E 013° 24.174',N 52° 31.172' · E 013° 24.174')

but actual view is

![image](https://github.com/cgeo/cgeo/assets/1258173/5d32f023-3b5b-45ee-b8b5-0529e5400c8d)

**Comment by ztNFny** [comment] 2023-11-26 14:02
I found part of the cause for problems. But as there are many related problems here I'll try to divide them a bit as they could have different causes.

Problem: "Map list on Google Maps" shows the wrong viewport
Cause: I have a geojson (of Germany) loaded but hidden. This causes Google Maps to display the viewport in https://github.com/cgeo/cgeo/issues/14885#issuecomment-1826790442 despite the correct one being calculated

Problem: "Map list on Google Maps" shows wrong zoom level
Details: Mapping the list uses whatever zoom level was last selected instead of the one appropiate for the viewport

Problem: "Map list on Google Maps" uses wrong center
Details: Mapping the list uses current position as center instead of viewport calculated from caches

Problem: "View list on OSM fails to initialize" (Blocker!)
Details: See video in https://github.com/cgeo/cgeo/issues/14885#issuecomment-1826738598

**Comment by ztNFny** [comment] 2023-11-28 17:27
@moving-bits any idea how do debug the 4 issues?

**Comment by moving-bits** [comment] 2023-11-29 21:20
> @moving-bits any idea how do debug the 4 issues?

I can try to look into those over the next days. But will most probably not be before the weekend.

PR #14903 should help a bit already (by no longer setting map center to current position when displaying a list, even if in "follow me" mode).

**Comment by moving-bits** [comment] 2023-12-02 17:44
I've created the following test case:
- create a list with app. 10 caches, all of them located in Berlin
- loaded a track in Amsterdam + hide it
- loaded a GeoJSON file in Amsterdam

Then:
- open the list mentioned above
- select "show on map"

Result:
- map opens with a section of Berlin, displaying the caches of the list

Thus number 1 from above seems to be fixed meanwhile.

Then I moved the map away from Berlin and also changed the zoom level to show a wider area, then returned to home screen. After that I repeated the steps above listed in "Then" section.

Result:
- map returns to the same section of Berlin and a reasonable zoom level (not the one I left the map with)

Thus number 2 and 3 seem to work as well meanwhile.

**Comment by moving-bits** [comment] 2023-12-02 17:50
Created a different test case for number 4:
- Current position is in Paris
- Selected "follow me" => map moves to Paris
- Added two closely related waypoints to one cache in Berlin
- opened the list containing that cache and selected "navigate to"

Result:
- Map is moved to Berlin and zoomed to be able to show cache + its two waypoints

So number 4 seems to be resolved as well meanwhile.

I'll close here for now, all issues seem to be fixed with the changes in #14903.
Feel free to reopen, if any further issues come up for this item.

**Closed by moving-bits** 2023-12-02 17:50 UTC
Labels: Bug
