### ISSUE TITLE
OSM: Support zoom of map text

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#5675] opened 2016-04-17 15:48 UTC
From time to time users complain, that texts and symboles on OSM-Online maps are too small to read on a high res device.
Locus does support a selectable scaling option for that problem. c:geo could have the same.
AFAIR the setting for "Increase text size" does also only work for offline maps...am I right?

Find attached an example screenshot from LG G4 with resolution 2560x1440:
![online_osm_kleinenamen](https://cloud.githubusercontent.com/assets/949669/14588247/966c3774-04c4-11e6-8dab-02d4bdea51d4.png)

**Comment by SammysHP** [comment] 2016-04-20 12:57
Duplicate of #4480, #3830,  #3220.

**Closed by SammysHP** 2016-04-20 12:57 UTC
Labels: Feature Request
