### ISSUE TITLE
restoring backup doesn't work

### ISSUE THREAD

**Issue by Bananeweizen** [cgeo/cgeo#4937] opened 2015-05-15 19:45 UTC
I just tried restoring a backup of my personal device on an emulator. While no error message is shown, the database is empty afterwards.
Have to inspect this when there is some more time...

**Comment by Lineflyer** [comment] 2016-02-15 11:33
@Bananeweizen Are you still able to reproduce/investigate.
Otherwise I suggest closing this issue...couldn't reproduce this issue myself.

**Closed** 2016-02-16 15:20 UTC
Labels: Unverified
