### ISSUE TITLE
IllegalArgumentException in ContentResolverResourceProvider

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#10235] opened 2021-03-21 22:35 UTC
Google Play for 2021.03.20

2 occurrences, Android 9 and 11

```
java.lang.IllegalArgumentException: 
  at android.database.DatabaseUtils.readExceptionFromParcel (DatabaseUtils.java:165)
  at android.database.DatabaseUtils.readExceptionFromParcel (DatabaseUtils.java:135)
  at android.content.ContentProviderProxy.query (ContentProviderNative.java:418)
  at android.content.ContentResolver.query (ContentResolver.java:804)
  at android.content.ContentResolver.query (ContentResolver.java:753)
  at android.content.ContentResolver.query (ContentResolver.java:711)
  at org.mapsforge.map.android.rendertheme.ContentResolverResourceProvider.queryDir (ContentResolverResourceProvider.java:139)
  at org.mapsforge.map.android.rendertheme.ContentResolverResourceProvider.buildCacheLevel (ContentResolverResourceProvider.java:96)
  at org.mapsforge.map.android.rendertheme.ContentResolverResourceProvider.refreshCache (ContentResolverResourceProvider.java:175)
  at org.mapsforge.map.android.rendertheme.ContentResolverResourceProvider.<init> (ContentResolverResourceProvider.java:89)
  at cgeo.geocaching.maps.mapsforge.v6.RenderThemeHelper.createThemeFor (RenderThemeHelper.java:186)
  at cgeo.geocaching.maps.mapsforge.v6.RenderThemeHelper.reapplyMapTheme (RenderThemeHelper.java:148)
  at cgeo.geocaching.maps.mapsforge.v6.RenderThemeHelper.lambda$selectMapTheme$0 (RenderThemeHelper.java:238)
  at cgeo.geocaching.maps.mapsforge.v6.RenderThemeHelper.lambda$selectMapTheme$0$RenderThemeHelper (Unknown Source)
  at cgeo.geocaching.maps.mapsforge.v6.-$$Lambda$RenderThemeHelper$yePm3t3WbuFSs5trufBVFWocVl4.onClick (Unknown Source:10)
  at com.android.internal.app.AlertController$AlertParams$3.onItemClick (AlertController.java:1169)
  at android.widget.AdapterView.performItemClick (AdapterView.java:318)
  at android.widget.AbsListView.performItemClick (AbsListView.java:1192)
  at android.widget.AbsListView$PerformClick.run (AbsListView.java:3169)
  at android.os.Handler.handleCallback (Handler.java:874)
  at android.os.Handler.dispatchMessage (Handler.java:100)
  at android.os.Looper.loop (Looper.java:198)
  at android.app.ActivityThread.main (ActivityThread.java:6729)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:493)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:876)
```

**Comment by Lineflyer** [comment] 2021-03-21 22:36
Similar report?

```
java.lang.RuntimeException: 
  at android.app.ActivityThread.performResumeActivity (ActivityThread.java:4288)
  at android.app.ActivityThread.handleResumeActivity (ActivityThread.java:4328)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:2047)
  at android.os.Handler.dispatchMessage (Handler.java:108)
  at android.os.Looper.loop (Looper.java:166)
  at android.app.ActivityThread.main (ActivityThread.java:7529)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.Zygote$MethodAndArgsCaller.run (Zygote.java:245)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:921)
Caused by: java.lang.IllegalArgumentException: 
  at android.database.DatabaseUtils.readExceptionFromParcel (DatabaseUtils.java:165)
  at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel (DatabaseUtils.java:146)
  at android.content.ContentProviderProxy.openTypedAssetFile (ContentProviderNative.java:698)
  at android.content.ContentResolver.openTypedAssetFileDescriptor (ContentResolver.java:1422)
  at android.content.ContentResolver.openAssetFileDescriptor (ContentResolver.java:1259)
  at android.content.ContentResolver.openInputStream (ContentResolver.java:979)
  at cgeo.geocaching.storage.ContentStorage.openForRead (ContentStorage.java:368)
  at cgeo.geocaching.storage.ContentStorage.openForRead (ContentStorage.java:355)
  at cgeo.geocaching.maps.mapsforge.MapsforgeMapProvider.createMapFileInputStream (MapsforgeMapProvider.java:327)
  at cgeo.geocaching.maps.mapsforge.MapsforgeMapProvider.access$200 (MapsforgeMapProvider.java:48)
  at cgeo.geocaching.maps.mapsforge.MapsforgeMapProvider$OfflineMultiMapSource.createTileLayer (MapsforgeMapProvider.java:231)
  at cgeo.geocaching.maps.mapsforge.v6.NewMap.switchTileLayer (NewMap.java:619)
  at cgeo.geocaching.maps.mapsforge.v6.NewMap.initializeLayers (NewMap.java:715)
  at cgeo.geocaching.maps.mapsforge.v6.NewMap.onStart (NewMap.java:710)
  at android.app.Instrumentation.callActivityOnStart (Instrumentation.java:1339)
  at android.app.Activity.performStart (Activity.java:7403)
  at android.app.Activity.performRestart (Activity.java:7477)
  at android.app.Activity.performResume (Activity.java:7482)
  at android.app.ActivityThread.performResumeActivity (ActivityThread.java:4256)
```

**Comment by eddiemuc** [comment] 2021-03-22 07:51
Two different things but same root cause (which is "trying to access non-existing Uri"). 
 
The upper needs/should be fixed in mapsforge, but can temporarily be safe-guarded in c:geo as well

**Comment by eddiemuc** [comment] 2021-03-22 09:25
PR #10239

**Closed** 2021-03-22 16:32 UTC
Labels: Bug
