### ISSUE TITLE
Store data for trackables offline

### ISSUE THREAD

**Issue by Frogging101** [cgeo/cgeo#1883] opened 2012-07-13 22:25 UTC
c:geo should store trackable data offline along with the cache(s). When I'm geocaching, I often find TBs or something in the Geocache, and end up leaving it there because I don't know the trackable's goal; And I don't like moving trackables without knowi where they are supposed to be going.

I think there should be a feature in c:geo where if you store cache(s) offline, the data for each of the trackables in the inventories of the cache(s) should be stored with it. Then if I ever find a trackable in a cache and forgot to check its info at home, I'll know where it's going so I can pick it up.

**Comment by Lineflyer** [comment] 2017-02-14 21:47
Duplicate of #4394

**Closed by Lineflyer** 2017-02-14 21:47 UTC
Labels: Feature Request
