### ISSUE TITLE
Stored caches won't come up offline

### ISSUE THREAD

**Issue by B2Pi** [cgeo/cgeo#13404] opened 2022-09-05 18:42 UTC
I fear that I don't know when this started happening, but it was in evidence a couple of times yesterday (w/version 2022.09.04).

When I was out of coverage area, I was unable to open a saved cache unless I turned off network entirely.

Steps to recreate:
1. Save a cache
2. Go to an area where there is no data service
3. Attempt to open the saved cache
4. Profit...

**Comment by SammysHP** [comment] 2022-09-05 19:23
Duplicate of #11725.

**Closed by SammysHP** 2022-09-05 19:23 UTC
