### ISSUE TITLE
First Waypoint shows text of second waypoint

### ISSUE THREAD

**Issue by dl1ely** [cgeo/cgeo#4686] opened 2015-02-16 10:48 UTC
Sometimes (unfortunately i cannot reproduce it), the text of the second waypoint is duplicated into the first for saved caches. Screenshot for GC4E28K:
![screenshot_2015-01-27-12-18-09](https://cloud.githubusercontent.com/assets/427752/6210507/bd36f306-b5d0-11e4-9b51-795955b55f38.png)

„Der Yogi bewacht C und D“ belongs to the second WP, Stage 1. Text for first WP (Start) is gone. This is different from #3420. The error is permanent and persists across refreshes of the saved cache. Also WP detail view shows the wrong text.

Unfortunately, the error appears infrequently, and the circumstances are unclear to me. I noticed it 4-5 times during the last months, but never was annoyed enough to open an issue. 

Version 2015.02.16-NB, but i suspect the error occurs during saving of the cache, which was quite a long time ago now, and thus happened with an older version.

**Comment by Lineflyer** [comment] 2015-02-16 19:42
Is it possible that the owner updated the waypoint amount and/or content between your initial save date and the next refresh?
If yes, this is AFAIR a known issue (have to search it first).

**Comment by Lineflyer** [comment] 2015-02-16 19:45
Here we go: #3650  (Please doublecheck)

**Comment by dl1ely** [comment] 2015-02-17 08:51
I have no way to find out whether the WPs did change, sorry.

So we close here. Sorry for not finding #3650 on my own.

**Comment by Bananeweizen** [comment] 2015-02-17 16:31
Can you please export that cache as GPX (as it is now, before trying anything) and send it to our support mail? If I read the cache website right, the first waypoint has a note (about Buchstabenwert...) and that should surely override the existing note when updating the cache.

**Comment by Lineflyer** [comment] 2015-02-17 18:35
@Bananeweizen If you want to try debugging this (and/or #3650) please let me know. I can help my modifying one of my caches if needed.

**Comment by dl1ely** [comment] 2015-02-17 18:37
Is there a way to export a single cache? I only see that for lists?

**Comment by rsudev** [comment] 2015-02-17 19:03
You can use selection mode in the list

**Comment by dl1ely** [comment] 2015-02-17 19:18
Thanks, i mailed the export…

**Comment by dl1ely** [comment] 2015-02-17 19:23
I just peeked quickly into the .gpx: The waypoint has the correct text there. But in c:geo it is still wrong. Just a display problem?

**Comment by dl1ely** [comment] 2015-02-17 19:27
No, i was wrong. "Ursprüngliche Koordinaten" has the correct text for "Start", "Start" has the duplicated text of Stage 1, like in c:geo. Perhaps there is a glitch when you change the coordinates of a WP, and "Ursprüngliche Koordinaten" gets created?

**Comment by Bananeweizen** [comment] 2015-02-18 19:12
That's quite a good idea, as we do a merging of waypoints during update and we really might confuse this one.

**Comment by dl1ely** [comment] 2015-02-21 21:02
OK, that one was way easier to reproduce than expected:

- Take an arbitrary multi cache with waypoints that have a description text. 
- Modify any waypoint with new coordinates, and select to update the cache location with the new coordinates. For this example lets say it is the second WP in list.
- The new waypoint "Ursprüngliche Koordinaten" gets created at the end of list of waypoints. 
- WP descriptions still align with WPs.
- Refresh cache details for the (now) saved cache.
- Recheck Waypoints: "Ursprüngliche Koordinaten" is still last in list of WPs, but has description of first WP in list. First WP in list has text of second WP, second WP (the one with the new, modified coordinates) has text of third WP. But third WP has correct text, and all other WP after that are correct, too.

So when "ursprüngliche Koordinaten" gets created and WP descriptions merged afterwards, all WP descriptions up to the changed WP are off by one.
WP Descreptions 1 2 3 4 become 2 3 3 4 (1) for WP1 WP2 WP3 WP4 (ursprüngliche Koordinaten) when WP2 is modified.

I hope you guys can reproduce that, too…

**Comment by rsudev** [comment] 2015-02-21 21:40
I quickly checked this and even so I didn't get exactly your behaviour (my testcache had only two waypoints) I was able to see some disruption in the waypoint descriptions. It is noteworthy, that I had to also send the changed coordinates to the website to achieve this effect.
Failing to do so resulted in a reset of the cache-coordinates and removal of the 'Ursprünglich Koordinaten' waypoint. Maybe a bug in itself and needs also some investigation.

**Comment by rsudev** [comment] 2015-02-22 10:49
One fundamental issue with waypoints is, that we store the user-notes or changes of the description in the same place as the description itself. This is fine as long as the description never changes...

**Comment by dl1ely** [comment] 2015-02-23 09:24
So what now? Remove "unverified"? More input needed? I guess not.

**Comment by rsudev** [comment] 2015-02-23 09:29
Are you sure that your reproduction scenario covers also the initial case? If so, we can try to address this, even so I have currently no clear idea how to go about it.

**Comment by dl1ely** [comment] 2015-02-23 10:55
I tried on another „fresh“ multi cache, and it reproduced the bug exactly as described 5 comments above.

**Comment by Lineflyer** [comment] 2015-03-10 15:35
This happend to me on two recently found multicaches exactly as written by @dl1ely above.
I am meanwhile quite sure that there is a difference to the abovementioned #3650: 
I did not experience the problem before just by adding "Urspüngliche Koordinaten" while with current NBs I do experience it.

@dl1ely  When originally reporting that issue, did you use the market release or our nightly builds?

**Comment by dl1ely** [comment] 2015-03-10 22:36
@Lineflyer As i wrote in the initial post, it was a NB. I regularly update to the latest NB.

**Comment by samueltardieu** [comment] 2015-03-16 09:15
I'll have a look at it. It looks like the prefix is parsed wrong, and thus the merge happens to be wrong when new data leads to the waypoints to be renumbered on the gc.com page.

**Comment by samueltardieu** [comment] 2015-03-16 09:44
Assigning to @Lineflyer for testing and green light for merging into `release`.

**Comment by samueltardieu** [comment] 2015-03-16 10:12
Note: for testing, I built a new nightly 2015.03.16-NB1, which is already available.

**Comment by Lineflyer** [comment] 2015-03-16 20:34
The fix itself is working (tested with the procedure above).
As just now master was merged to release, no other statement necessary :))

**Closed by Lineflyer** 2015-03-16 20:34 UTC
Labels: Bug, Field test

**Comment by samueltardieu** [comment] 2015-03-16 21:43
Indeed :) Milestones need to be renamed though btw.
