### ISSUE TITLE
Upload more photos to the log

### ISSUE THREAD

**Issue by nimirCZ** [cgeo/cgeo#7123] opened 2018-08-22 11:32 UTC
I need to upload more photos to one log. One is not enough.

**Comment by SammysHP** [comment] 2018-08-22 13:38
Duplicate of #2734. Please use the search function before opening new issues.

**Closed by SammysHP** 2018-08-22 13:38 UTC

**Comment by nimirCZ** [comment] 2018-08-22 15:17
Ok, I'm sorry. I was looking for it, but it is not possible in so many quantity.
