### ISSUE TITLE
Request for Feature: Mass Upload of Saved Offline Logs to Geocaching Website

### ISSUE THREAD

**Issue by anondev-sudo** [cgeo/cgeo#15537] opened 2024-03-29 19:32 UTC
#### Description:
Currently, users of c:geo often save offline logs for geocaches they find and then manually upload them to the Geocaching website after returning home. To streamline this process and enhance user convenience, a feature is needed to enable the mass upload of all saved offline logs to the Geocaching website directly from the app. This functionality would simplify the log submission process and save users time and effort.

#### Proposed Feature:
Introduce an option in the three-dot settings menu while viewing the cache list in c:geo that allows users to mass upload all saved offline logs to the Geocaching website. This feature should specifically target the offline logs associated with the caches in the offline cache list, enabling users to submit multiple logs in bulk without the need for individual manual uploads.

#### Justification:
The addition of a mass upload feature for offline logs in c:geo addresses a common user need for efficient log submission after geocaching trips. By providing a convenient way to upload multiple logs at once, users can save time and effort, enhancing their overall experience with the app and simplifying the process of logging geocache finds.

#### Expected Behavior:
Upon selecting the mass upload option in the three-dot settings menu while viewing the cache list, c:geo should initiate the bulk upload process for all saved offline logs associated with the caches in the offline cache list. This feature should streamline log submission by automating the upload of multiple logs to the Geocaching website in a single action.

**Comment by SammysHP** [comment] 2024-03-29 21:18
Duplicate of #1786

**Closed by SammysHP** 2024-03-29 21:18 UTC
Labels: Feature Request
