### ISSUE TITLE
Import of child waypoints failed (GPX from GSAK)

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#4733] opened 2015-03-14 10:18 UTC
From support mail:

I switched to android from WP8 few days ago and am learning to use it. I have problem with import of GPX file exported from GSAK. Import works, but no child waypoints are imported. I use GSAK for saving solved final waypoints to multis and puzzles and am not able to move those final waypoints to c:geo. Searching for help on your site and googling didn't help. Would you mind telling how to do it, please? 

---
GPX file was sent to cgeo-dev mailing list on 03.03.2015 / 15:00

Assigning @Bananeweizen as per request

**Comment by sd1621** [comment] 2015-03-29 13:53
I've noticed that on import the gpx file with the child waypoints created from pocket queries not found so I am correct in assuming that cgeo does not support these

**Comment by SammysHP** [comment] 2015-05-19 18:02
Duplicate of #4397.

**Comment by Lineflyer** [comment] 2015-05-28 12:37
Does that mean it doe not need a fix as mentioned in #4397 ?

**Comment by SammysHP** [comment] 2015-05-28 12:44
We work with the GSAK GPX extension partially. Maybe we can use it also during import.

**Comment by Lineflyer** [comment] 2015-06-17 11:52
@Bananeweizen  I assigned you to that issue in March as you requested via mailing-list.

Just some new info:
I recently got in touch with a user with this problem.
He tried the possibilities as described by @SammysHP in #4397 but failed. I crosschecked it and can confirm that the child waypoints are not recognized on import.

The GPX looks like:
```
<?xml version="1.0" encoding="utf-8"?>
<gpx xmlns:xsd="http://www.w3.org/2001/XMLSchema"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
version="1.0" creator="GSAK"
xsi:schemaLocation="http://www.topografix.com/GPX/1/0 http://www.topografix.com/GPX/1/0/gpx.xsd http://www.groundspeak.com/cache/1/0/1 http://www.groundspeak.com/cache/1/0/1/cache.xsd"
xmlns="http://www.topografix.com/GPX/1/0">
 <desc>Geocache file generated by GSAK (HasChildren)</desc>
 <author>GSAK</author>
 <email>support@gsak.net</email>
 <time>2015-06-16T21:29:31Z</time>
 <keywords>cache, geocache, groundspeak</keywords>
 <bounds minlat="52.449933" minlon="9.303933" maxlat="52.484283" maxlon="9.365017"/>
 <wpt lat="52.482467" lon="9.303933">
  <time>2013-06-01T08:00:00Z</time>
  <name>GC4DBN3</name>
  <desc>Das A #01 by cachergemein.de (2/1,5)</desc>
  <url>http://www.geocaching.com/seek/cache_details.aspx?guid=dec17101-7462-4d6d-8517-57a2d4f41850</url>
  <urlname>Das A #01 by cachergemein.de</urlname>
  <sym>Geocache</sym>
  <type>Geocache|Unknown Cache</type>
  <groundspeak:cache id="3681472" available="True" archived="False" xmlns:groundspeak="http://www.groundspeak.com/cache/1/0/1">
   <groundspeak:name>Das A #01</groundspeak:name>
   <groundspeak:placed_by>cachergemein.de</groundspeak:placed_by>
   <groundspeak:owner id="4996232">cachergemein.de</groundspeak:owner>
   <groundspeak:type>Unknown Cache</groundspeak:type>
   <groundspeak:container>Micro</groundspeak:container>
   <groundspeak:attributes>
     <groundspeak:attribute id="1" inc="1">Dogs</groundspeak:attribute>
     <groundspeak:attribute id="6" inc="1">Recommended for kids</groundspeak:attribute>
     <groundspeak:attribute id="32" inc="1">Bicycles</groundspeak:attribute>
     <groundspeak:attribute id="41" inc="1">Stroller accessible</groundspeak:attribute>
   </groundspeak:attributes>
   <groundspeak:difficulty>2</groundspeak:difficulty>
   <groundspeak:terrain>1.5</groundspeak:terrain>
   <groundspeak:country>Germany</groundspeak:country>
   <groundspeak:state>Niedersachsen</groundspeak:state>
   <groundspeak:short_description html="True">&lt;center&gt;&lt;img alt height="309" src="http://img.geocaching.com/cache/effc059d-fcfa-43e9-bc49-2f2d18a19a16.png" width="640" /&gt;&lt;/center&gt;
&lt;br /&gt;</groundspeak:short_description>
   <groundspeak:long_description html="True">&lt;p align="center"&gt;&lt;img src="http://imgcdn.geocaching.com/cache/1be2e82e-add7-4556-ac00-b3b3ee43ce64.jpg?rnd=0.774696" border="0" width="645" height="630" usemap="#Landkarte" /&gt; &lt;map name="Landkarte"&gt;
&lt;area shape="rect" coords="140,20,490,300" href="http://cachergemein.de/" alt="cachergemein.de" title="cachergemein.de" /&gt;
&lt;area shape="rect" coords="260,530,380,560" href="http://www.geocaching.com/geocache/GC4BR11_das-a-bonus?guid=6525e3e1-5888-47ac-b467-a14c07572ef4" alt="Bonus" title="Bonus" /&gt;&lt;/map&gt;&lt;/p&gt;
&lt;center&gt;&lt;font size="+2"&gt;&lt;font color="#0006C0"&gt;&lt;b&gt;Das "A 01"&lt;/b&gt;&lt;br /&gt;
&lt;br /&gt;&lt;/font&gt; &lt;img src="http://imgcdn.geocaching.com/cache/large/a5dbfd33-bd98-4946-892b-8079b8ab830e.jpg" /&gt;&lt;br /&gt;
&lt;br /&gt;
&lt;br /&gt;
&lt;a href="http://www.gocaching.de/cochecker.php?check=1B0" target="_blank"&gt;Check it out&lt;/a&gt;&lt;br /&gt;
&lt;font size="+1"&gt;Also jetzt: nicht lang schnacken, Rätsel knacken.....&lt;br /&gt;
Viel Spaß wünscht die Cachergemein.de&lt;/font&gt;&lt;br /&gt;
&lt;br /&gt;
&lt;br /&gt;
&lt;a href="http://www.gocaching.de" target="_blank"&gt;&lt;img src="http://www.gocaching.de/counter.php?cid=1B0" border="0" /&gt;&lt;/a&gt;&lt;br /&gt;
&lt;a href="http://www.gocaching.de/maintenance.php?report=1B0" target="_blank"&gt;&lt;img src="http://www.gocaching.de/maintenance.php?cid=1B0" border="0" /&gt;&lt;/a&gt;&lt;br /&gt;&lt;/font&gt;&lt;/center&gt;</groundspeak:long_description>
    <groundspeak:encoded_hints>Bäumchen</groundspeak:encoded_hints>
   <groundspeak:logs>
  </groundspeak:logs>
   <groundspeak:travelbugs>
   </groundspeak:travelbugs>
</groundspeak:cache>
</wpt>
  <wpt lat="52.123456" lon="9.123456">
    <time>2015-06-14T08:00:00Z</time>
    <name>004DBN3</name>
    <cmt></cmt>
    <desc>A01</desc>
    <url></url>
    <urlname>A01</urlname>
    <sym>Final Location</sym>
    <type>Waypoint|Final Location</type>
  </wpt>
```

**Comment by rsudev** [comment] 2015-06-17 13:26
@Lineflyer I think you misunderstood @SammysHP on IRC. The waypoint lacks everything that is required to link it to a cache in this case. In the waypoint itself the GSAK export has to introduce information in a GSAK-specific extension about the ```Parent``` (don't have the precise syntax the hand) to be recognised...

**Comment by rsudev** [comment] 2015-06-17 13:31
No, sorry I have to correct me. It seems we even look for the name matching according to gc.com rules....

**Comment by Lineflyer** [comment] 2015-06-17 14:21
Additional info by user:

I replaced the currently used prefix `00` with `FN` without success. 
Then I changed the prefix to `17` as this is what c:geo uses in its export, and now it worked. Strange.

**Comment by Bananeweizen** [comment] 2015-06-19 18:37
The issue from March is because of a really bad GSAK export. It uses different names for the waypoints XML and the geocache XML of _one cache_. That in turn leads to us not being able to match the parent title that we get from the child waypoint, because it refers to the _waypoint_ title of the cache, but we have of course taken the _cache_ title of the cache. Given our data structure, this is not fixable on our side.

For that second problem please create a new issue and put the complete GPX file somewhere. I don't even want to start parsing partial files, which might have been mangled by the github markdown parser.

**Closed by Bananeweizen** 2015-06-19 18:37 UTC
Labels: Bug

**Comment by Lineflyer** [comment] 2015-06-20 10:34
Will do.
However I can not paste the complete GPX somewhere publicly as it has a lot of corrected coords in it.
I will try to reduce to 2-3 caches and set fake coords to the final waypoints.

Might take some days until I have time for that.

**Comment by rsudev** [comment] 2015-07-04 19:08
Seems to be a side-effect of 56cefb30ade3425a0a45a266a5a4f90bb4399c30, specifically the change in GPXParser.java,434
No idea what this should achieve, reverting this specific change makes the import work again. Can also be related to #5065

**Comment by onnlinetool** [comment] 2017-04-10 10:54
Downloaden Knack  Downloaden Knack  Downloaden Knack

http://bit.ly/2oWYzXw

http://bit.ly/2oWYzXw

http://bit.ly/2oWYzXw

http://bit.ly/2oWYzXw

http://bit.ly/2oWYzXw

http://bit.ly/2oWYzXw

http://bit.ly/2oWYzXw

http://bit.ly/2oWYzXw

**Comment by kumy** [comment] 2017-04-10 11:12
(dropped spam)
