### ISSUE TITLE
Counter of found caches increased after 'Disable listing' log

### ISSUE THREAD

**Issue by poldekch** [cgeo/cgeo#4882] opened 2015-04-14 11:06 UTC
I've submitted 'Disable listing' log of my cache and counter has been increased (geocaching.com)
After closing the app (completely) and reopening and logging in - the counter has been updated to original value.

I presume not only 'Disable' is affected.

**Comment by Bananeweizen** [comment] 2015-04-14 16:05
Thanks for the report. This has been fixed already, but not yet been released. Duplicate of #4844.

**Closed by Bananeweizen** 2015-04-14 16:05 UTC
