### ISSUE TITLE
Request for Feature: Lock Automatic Screen Rotation Orientation with Toggle Option in Settings

### ISSUE THREAD

**Issue by anondev-sudo** [cgeo/cgeo#15535] opened 2024-03-29 19:23 UTC
#### Description:
When using c:geo with offline OSM maps, users face challenges due to the automatic screen rotation feature conflicting with manual screen rotation adjustments necessary for optimal map orientation. This issue disrupts the user experience and functionality of the app, particularly when rotating the phone screen is essential for map viewing.

#### Proposed Feature:
Introduce a new setting in c:geo that allows users to lock the screen rotation orientation while using the app, with a toggle option in the settings. This feature would enable users to control and customize their screen orientation preferences, preventing automatic rotation interference and ensuring seamless map navigation with offline OSM maps.

#### Justification:
The addition of a toggle option in the settings to lock the screen rotation orientation addresses the usability issues faced by users relying on c:geo with offline OSM maps. Providing this customization option enhances user control and improves the overall experience by allowing users to manage screen orientation according to their specific needs.

#### Expected Behavior:
Upon enabling the toggle option in the settings, users should be able to lock the screen rotation orientation, overriding any automatic adjustments that may disrupt manual orientation settings required for optimal map viewing with offline OSM maps. Users can easily toggle this feature on or off based on their preferences.

**Comment by moving-bits** [comment] 2024-03-29 20:48
I'm not sure I understand this feature request (sorry!):

As written in the other issue: Map rotation is available for Google Maps (old map), Google Maps (UnifiedMap), OSM offline and online maps (UnifiedMap).

In all of those maps you have a menu option to set map rotation to either
- off (keep map fixed as northbound)
- manual (rotate map as you like)
- automatic (according to direction of your movements)

Is there anything missing for you here?

**Comment by SammysHP** [comment] 2024-03-29 21:22
Duplicate of #7565.

**Closed by SammysHP** 2024-03-29 21:22 UTC
