### ISSUE TITLE
FR: Add log button to PMO toast

### ISSUE THREAD

**Issue by Natureshadow** [cgeo/cgeo#6364] opened 2017-02-27 17:05 UTC
PMO caches can be logged even without being PM as the log page does not check access rights (intentionally, according to GS). However, with c:geo, there is no way to log a PMO cache that is not stored offline.

Please add a button to the PMO toast to open the log window nonetheless.

**Comment by SammysHP** [comment] 2017-02-27 17:08
Duplicate of #2288.

**Closed by SammysHP** 2017-02-27 17:08 UTC
