### ISSUE TITLE
Map trail disappears when viewing cache details

### ISSUE THREAD

**Issue by mjarmstr** [cgeo/cgeo#7235] opened 2019-01-13 15:44 UTC
##### Detailed steps causing the problem:
- Open the map view with trail enabled.
- Walk a while so the trail shows up.
- Tap a cache and open the cache details.
- Exit back to the map.

##### Actual behavior after performing these steps:
- When exiting back to the map the trail is gone. 

##### Expected behavior after performing these steps:
- When exiting back to the map the trail remains.

##### Version of c:geo used:
2018.10.13

##### Is the problem reproducible for you?
Yes

##### System information:
```
--- System information ---
Device: moto x4 (payton_fi, motorola)
Android version: 9
Android build: PPW29.69-26
c:geo version: 2018.10.13
Google Play services: enabled - 14.7.99 (100408-223214910)
Low power mode: inactive
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: absent
Magnetometer & Accelerometer sensor: present
Direction sensor used: rotation vector
Hide own/found: true
Map strategy: auto
HW acceleration: enabled (default state)
System language: en (c:geo forced to English)
System date format: M/d/yy
Debug mode active: no
System internal c:geo dir: /data/user/0/cgeo.geocaching (36.7 GB free) internal
User storage c:geo dir: /storage/emulated/0/cgeo (36.6 GB free) external non-removable
Geocache data: /storage/0000-0000/Android/data/cgeo.geocaching/files/GeocacheData (55.0 GB free) external removable
Database: /storage/emulated/0/Android/data/cgeo.geocaching/files/databases/data (12.5 MB) on user storage
Fine location permission: granted
Write external storage permission: granted
Geocaching sites enabled:
   geocaching.com: Logged in (Login OK) / BASIC
Geocaching.com date format: MM/dd/yyyy
Installed c:geo plugins:  none
--- End of system information --
```

##### Other comments and remarks:
In general the impermanence of the trail is disturbing to me.  It is very useful when navigating from cache to cache using the map and when orienting oneself as you approach a cache.

**Comment by SammysHP** [comment] 2019-01-13 15:57
Probably duplicate of #2958 (which should be re-opened if we change our opinion of the trail feature).

I assume that the map activity is destroyed due to memory limitations. The trail is not stored permanently, so it will not be loaded again. A short term solution would be to place the trail in the `Bundle` and restore it on resume. A more complex solution would be to make the trail persistent as requested in #2958, but that would require some management functions as well (and should be discussed in #2958).

**Comment by mjarmstr** [comment] 2019-01-13 16:36
Hmmm....I wouldn't be surprised if that was the case, but this is actually new behavior for me.  I'm not used to the trail disappearing when I switch to the cache details and back.  Perhaps it has do do with my recent upgrade to Android Pie?  Is the memory management more aggressive?

**Comment by SammysHP** [comment] 2019-01-13 19:01
Or maybe it depends also on the map version. I can't check right now, but the new map implementation is not yet feature comparable with the old version (which you can select in the preferences).

**Comment by mjarmstr** [comment] 2019-01-13 22:17
That does appear to be the case. If I select "Old Mapsforge v3" in the
settings, the trail is retained.

**Comment by moving-bits** [comment] 2019-01-14 21:23
> Probably duplicate of #2958 (which should be re-opened if we change our opinion of the trail feature).
> 
> I assume that the map activity is destroyed due to memory limitations. The trail is not stored permanently, so it will not be loaded again. A short term solution would be to place the trail in the `Bundle` and restore it on resume. A more complex solution would be to make the trail persistent as requested in #2958, but that would require some management functions as well (and should be discussed in #2958).

Just for documentation purposes: I added a comment to #2958 with a proposal for improving the trail feature without reinventing the wheel: make trail persistent + add a basic "clear saved trail" management function.

**Comment by Lineflyer** [comment] 2019-01-14 21:34
I reopened #2958 for now, so lets close here.

**Closed by Lineflyer** 2019-01-14 21:35 UTC

**Comment by moving-bits** [comment] 2019-01-19 18:20
> I assume that the map activity is destroyed due to memory limitations. The trail is not stored permanently, so it will not be loaded again. A short term solution would be to place the trail in the `Bundle` and restore it on resume.

If I understand the source in maps/CGeoMap and maps/mapsforge/v6/NewMap correctly, traildata is already put into a `Bundle`, saved in `onSaveInstanceState`, and restored in `onCreate` for both map implementations.

I've dived into the debugger, and as far as I understand, the problem seems to be, that after calling a cache details page from within a map, neither `onCreate` nor `onRestoreInstanceState` get called (which could restore traildata from the `Bundle`), but `onStart` instead, which recreates a blank history (having none saved available).

@rsudev Do you have an idea how to avoid this? Or how to make the `Bundle` available to `onStart`?

**Comment by moving-bits** [comment] 2019-01-19 18:45
(A different solution would be to continually save new trailpoints to permanent storage and restore this in `onStart`, but this leads to #2958. Discussion for that alternative will be continued there.)

**Comment by rsudev** [comment] 2019-02-10 15:26
While researching something else in the new map I came across this bug and decided to still push the simple fix.
