### ISSUE TITLE
Possible waymarking.com support?

### ISSUE THREAD

**Issue by HTSamurai** [cgeo/cgeo#12048] opened 2021-11-04 15:36 UTC
### Tell us your idea!

Waymarking is a similar thing to Geocaching by groundspeak. It would be nice to have support for it in cgeo! 
The link is https://www.waymarking.com/

**Comment by ztNFny** [comment] 2021-11-04 15:52
duplicate of #11521

**Closed by ztNFny** 2021-11-04 15:52 UTC
Labels: Feature Request, Unverified
