### ISSUE TITLE
[Nightly] Hanger when opening cache listing from a mapped list

### ISSUE THREAD

**Issue by MagpieFourtyTwo** [cgeo/cgeo#11461] opened 2021-08-13 01:33 UTC
### Describe your problem!

When displaying a list on map, then entering one of these caches via it's map popup => ``MORE DETAILS``, c:geo hangs a second or two on opening the listing

I would say, this was not the case with yesterday's nightly - at least not that I would have noticed it. But, to be honest, did not do this with a list of >2k caches ...

### How to reproduce?

In my case:
- opened a list with 2768 caches
- display on map
- zoom in until about 10 caches are shown
- click a cache icon
- in the popup click ``MORE DETAILS``

### Actual result after these steps?

c:geo does not immediately jump to the ``Details`` page (as usually), but starts at the ``Waypoints`` page, then begins to scroll to ``Details`` page, but after the first quarter of the scroll it falls asleep, and after one or two seconds it continues the scroll and finally ends up in the ``Details`` page,

Pretty annoying ...  :/

### Expected result after these steps?

Immediately display ``Details`` page without any delay (as usually).

### Reproducible

Yes

### c:geo Version

2021.08.13-NB-8e3607d

**Comment by eddiemuc** [comment] 2021-08-13 06:49
@MagpieFourtyTwo just to be sure: is this only happening when you use a large list (e.g. >2K) as the starting point, or does this happen also when the list is much smaller (e.g. <10 caches)?

**Comment by DaTechniker** [comment] 2021-08-13 07:16
I was able to reproduce this with 2021.08.08-RC
On my Device I could see this with a larger list (~4500 Caches, where this took around 10 sec) and also in a small list with 10 Caches (0,5 sec). In the large map, I could also see a wrong counting of seen caches on the map. This also took some time, 
For me, the issue looks like the following screenshot

![Screenshot_20210813-090527_cgeo](https://user-images.githubusercontent.com/88573756/129319242-88449239-d113-4835-8def-aedc687889b9.jpg)

**Comment by MagpieFourtyTwo** [comment] 2021-08-20 10:51
Nothing new over here?
We're currently out in the woods and working with the lists, prepared for this journey, is no real fun anymore ...

**Comment by MagpieFourtyTwo** [comment] 2021-08-20 10:53
JFTR: Over here it's exactly like @DaTechniker described above.

**Comment by DaTechniker** [comment] 2021-10-15 04:35
> > 75.000+ offline caches
> 
> Admitted, c:geo isn't optimized for such incredible large cache lists. I wonder that it works at all 😅

Good piece of software.  :-)

What I saw, even for the smaller list are small delays in the reaction, after opening a cache, and a wrong counter in the map.
The "Alle" list is quite an extreme test scenario. Most lists I mainly use are up to maximum around 6000 caches.

**Comment by fm-sys** [comment] 2021-10-15 12:33
Problem is, that all caches need to be kept in memory. And when the cache details page gets opened, the map activity is still active in background.

To solve this, it would require to implement the offline list loaders to the map activity as well. So that no longer the cache set needs to be transferred and kept in memory, but only the list id instead.

**Comment by eddiemuc** [comment] 2021-10-16 09:34
So the short answer is: there are no online requests made in list view when displaying stored lists.

**Comment by eddiemuc** [comment] 2021-10-16 09:35
...and whether online requests are made at all in list view does not depend in any way on the filters you select but solely on the context in which you enter the list view

**Comment by fm-sys** [comment] 2021-10-16 10:58
> So the short answer is: there are no online requests made in list view when displaying stored lists.

I understand, that no requests are done in the list view. But what about the live map? What if we no longer transfer the cache set to the live map, but decide to initialize the live map with the offline filter and add the filter "contained in list". 

The goal (independent of this performance issue) is, to let "show on map" open the map as top-level activity, no longer as sub-activity of the list view. 

Then, only those caches will be loaded into memory, which are currently visible on the live map.


---
The question whether online requests will be done is independent of that idea. When I add the filter "contained in list" on the map, no online requests need to be done on the live map, as all caches need to be in the DB anyway. However I understand, that for other searches like in the search activity, online requests still need to be done even if a "contained in list" filter is active...

**Comment by eddiemuc** [comment] 2024-03-10 20:50
Teammtting 10.3.24: meanwhile, with unifiedmap, mapping stored lists to map is implemented very differently (we just transfer list ids, not the caches). Thus this issue is closed.

**Closed by eddiemuc** 2024-03-10 20:50 UTC
Labels: Bug, Unverified
