### ISSUE TITLE
Attachment of multiple images with single Caption

### ISSUE THREAD

**Issue by wargarw** [cgeo/cgeo#5522] opened 2016-03-10 16:36 UTC
###### Detailed steps causing the problem:
- Log Visit cache
- Menu -> Attach Image

###### Actual behaviour after performing these steps:
It is possible to attach only single image with a Caption & Description.

###### Expected behaviour after performing these steps:
It would be possible to attach multiple images with single Caption.

###### Version of c:geo used:
2016.02.03

###### Is the problem reproducible for you:
Yes

###### Attach system information if available (see c:geo menu -> About c:geo -> System):
--- System information ---
Device: LG-D802 (g2_open_com, lge)
Android version: 4.4.2
Android build: KOT49I.D80220h
Cgeo version: 2016.02.03
Google Play services: enabled
Low power mode: inactive
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: rotation vector
Hide own/found: false
Map strategy: auto
HW acceleration: enabled (default state)
System language: en_US
Geocaching sites enabled:
- geocaching.com: logged in (Login OK) / Basic
Installed cgeo plugins:  none
--- End of system information ---

###### Other comments and remarks:

I would like to work on this feature on my own. Any feedback & remarks would be appreciated.

**Comment by kumy** [comment] 2016-03-10 16:42
This is a duplicate of #2734.
Closing here.

**Closed by kumy** 2016-03-10 16:42 UTC
