### ISSUE TITLE
Two instances when started from k9

### ISSUE THREAD

**Issue by Bananeweizen** [cgeo/cgeo#6630] opened 2017-07-02 18:31 UTC
A friend just demonstrated on his phone that he can open a cache from a mail in k9 and then start cgeo normally, and afterwards there are 2 instances running (as you can verify by editing some data without storing to database in one instance). Can we prevent this by adding some flags to our activities?

**Comment by pstorch** [comment] 2017-07-03 21:45
An Activity can have the attribute `android:launchMode="singleInstance"` in the manifest file.

**Comment by Lineflyer** [comment] 2018-01-08 11:40
Duplicate of #6902

**Closed by Lineflyer** 2018-01-08 11:40 UTC
Labels: Duplicate
