### ISSUE TITLE
Wrong state of backup file is displayed when reentering the Settings/System screen

### ISSUE THREAD

**Issue by kia71** [cgeo/cgeo#5191] opened 2015-09-12 12:32 UTC
version 2015.09.12-NB

Starting condition: There is no saved c:geo backup file on the device.
- 'There is no file with a back up.' is displayed on Settings/System screen.
- I save a backup.
- 'Available backup from ...' is displayed on Settings/System screen.
- I leave the System screen.
- I am on the Settings screen now.
- I enter the System screen again.
- 'There is no file with a back up.' is displayed on Settings/System screen.
- The situation is the same if I repeat these steps.
- Now, I leave the System and  the Settings screen also.
- I am on the c:geo main screen.
- I enter the Settings and the System screen again.
- The right 'Available backup from ...' is displayed on Settings/System screen.

The situation is similar if there is a saved backup file on the device before stepping between the screens. However, the problem is more spectacular if there is no save backup file at the beginning.

**Comment by kia71** [comment] 2015-09-20 06:25
--- System information ---
Device: SM-G360F (coreprimeltexx, samsung)
Android version: 4.4.4
Android build: KTU84P.G360FXXU1AOB1
Cgeo version: 2015.09.19-NB-9b1a29c
Google Play services: enabled
Low power mode: inactive
Compass capabilities: no
Rotation sensor: absent
Orientation sensor: absent
Hide own/found: false
Map strategy: auto
HW acceleration: enabled (default state)
System language: hu_HU
Geocaching sites enabled:
 - geocaching.com: logged in (Belépés ok) / Premium
Installed cgeo plugins:  none
--- End of system information ---

**Comment by Lineflyer** [comment] 2016-03-29 17:05
Reproducible with 2016.03.26-NB

**Comment by Lineflyer** [comment] 2020-10-19 20:27
@fm-sys Can you doublecheck this problem with your new implementation? I guess its no longer relevant.

**Comment by fm-sys** [comment] 2020-10-20 07:08
Reading the system information it looks like the same as #6482. I can't reproduce it with the current nightly, so let's close it...

**Closed by fm-sys** 2020-10-20 07:08 UTC
Labels: Bug, Frontend Design
