### ISSUE TITLE
Editing found log fails

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#15665] opened 2024-04-27 09:28 UTC
Reported by user on support (ticket 317918) and reproducible for me:

Editing a found log fails with error 422 "Unprocessable entity".
Editing a write note does work.

Steps to reproduce:
- open a cache yet unfound in c:geo
- write and send a "found log"
- long-tap on this log and select "edit"
- tap "send log" (no change necessary)

Tested with current release 2024.04.25

**Comment by fm-sys** [comment] 2024-06-09 18:44
Team meeting 09.06.: Can't reproduce. Maybe a temporary website bug? Or may be fixed by #15636?

**Closed by fm-sys** 2024-06-09 18:44 UTC
Labels: Bug, Regression, Support
