### ISSUE TITLE
Wrong event date in map popup 

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#14411] opened 2023-07-12 22:21 UTC
### Describe your problem!

A user reported, that an event shows up with different dates on map vs. details.
I was able to reproduce it..maybe a time zone issue.

### How to reproduce?

- Open GCAADAK
- Note, that 15.07.23 is the event date (correct) as per cache details.
- Map the cache
- Tap to open popup
- Note, that event date in popup is still correct (15.07.23)
- Go back and switch to live map (from bottom nav)
- Tap on the cache to open popup

### Actual result after these steps?

Now the event date is shown as 14.07.23 (wrong) instead of 15.07.23 (correct)

### Expected result after these steps?

Always correct date should be shown

### Reproducible

Yes

### c:geo Version

2023.06.18

### System information

```text
Users system information:

c:geo version: 2023.06.18

Device:
-------
- Device type: SM-J600FN (j6ltexx, samsung)
- Available processors: 8
- Android version: 10
- Android build: QP1A.190711.020.J600FNXXSACVB1
- Screen resolution: 720x1384px (360x668dp)
- Pixel density: 2.0
- System font scale: 1.0 / used scale: 1.0
- Sailfish OS detected: false
- Google Play services: enabled - 23.24.14 (100300-544099984)
- Memory:  Available:996,2 MB, Total:2,7 GB, Threshold: 97,6 MB, low:false

Sensor and location:
-------
- Low power mode: inactive
- Compass capabilities: no
- Rotation vector sensor: absent
- Orientation sensor: absent
- Magnetometer & Accelerometer sensor: absent
- Direction sensor used: magnetometer & accelerometer

Program settings:
-------
- Settings: v9, Count:108
- Set language: de_DE (system default)
- System date format: dd.MM.yy
- Time zone: GMT+02:00
- Debug mode active: no
- Log Settings: debug=false, minLevel=WARN, minAddCallerInfo=NONE, addCallerInfoMaxDepth=8, throwOnError=false, transactionSizes=false
- Last manual backup: never
- Last auto backup: 6. Juli, 09:23
- Routing mode: Walk
- Live map mode: true
- OSM multi-threading: false / threads: 1
- Map: Google: Karte
  - Id: cgeo.geocaching.maps.google.v2.GoogleMapProvider$GoogleMapSource
  - Atts: none
  - Theme: none

Filters:
-------
- Hide waypoints: -
- LIVE: Cache-Typ: Event, Status: 3 Elemente ([:inconclusive=false:advanced=false]AND(type:EVENT;difficulty_terrain:d=-:d=-:t=-:t=-;status:found_no:exclude_disabled:exclude_archived))
- OFFLINE: Keine ([:inconclusive=false:advanced=false]AND(type;difficulty_terrain:d=-:d=-:t=-:t=-;status))

Stored Filters (#0):

Services:
-------
- Geocaching sites enabled:
   - geocaching.com: Logged in (Anmeldung OK) / PREMIUM
   - Geocaching.com Adventure Lab
- Geocaching.com date format: dd.MM.yyyy
- Geocaching.com website language: de-DE
- Last login error on geocaching.com: communication error (2023-06-30 18-13)
- Last successful login on geocaching.com: 2023-07-12 18-51
- Routing: internal / BRouter installed: false
- Installed c:geo plugins:  none

Permissions
-------
- android.permission.ACCESS_COARSE_LOCATION:: granted
- android.permission.ACCESS_FINE_LOCATION:: granted
- android.permission.READ_CONTACTS:: DENIED
- android.permission.READ_EXTERNAL_STORAGE:: DENIED
- android.permission.WRITE_EXTERNAL_STORAGE:: DENIED

Paths
-------
- System internal c:geo dir: /data/user/0/cgeo.geocaching (1,5 GB free) v3 internal isDir(8 entries)
- Legacy User storage c:geo dir: /data/user/0/cgeo.geocaching (1,5 GB free) v3 internal isDir(8 entries)
- Geocache data: /storage/emulated/0/Android/data/cgeo.geocaching/files/GeocacheData (1,5 GB free) v3 external non-removable isDir(569 entries)
- Internal theme sync (is turned off): /data/user/0/cgeo.geocaching/MapThemeData (1,5 GB free) v3 internal isDir(0 entries)
- Map render theme path:
- Public Folders: #12
  - BASE: /cgeo/maps (User-Defined)[/cgeo/maps[DOCUMENT#0:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo%2Fmaps::]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo%2Fmaps/document/primary%3Acgeo%2Fmaps, Av:true, files:>=320, dirs:>=10, totalFileSize:>=3,7 GB, free space: 1,5 GB, files on device: 790528)
  - OFFLINE_MAPS: /cgeo/maps/maps (Default)[/cgeo/maps/maps[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo%2Fmaps::/maps]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo%2Fmaps/document/primary%3Acgeo%2Fmaps%2Fmaps, Av:true, files:8, dirs:2, totalFileSize:3,7 GB, free space: 1,5 GB, files on device: 790528)
  - OFFLINE_MAP_THEMES: /cgeo/maps/maps/_themes (Default)[/cgeo/maps/maps/_themes[PERSISTABLE_FOLDER(OFFLINE_MAPS)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo%2Fmaps::/maps/_themes]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo%2Fmaps/document/primary%3Acgeo%2Fmaps%2Fmaps%2F_themes, Av:true, files:0, dirs:0, totalFileSize:0 B, free space: 1,5 GB, files on device: 790528)
  - OFFLINE_MAP_SHADING: /cgeo/maps/maps/_hgt (Default)[/cgeo/maps/maps/_hgt[PERSISTABLE_FOLDER(OFFLINE_MAPS)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo%2Fmaps::/maps/_hgt]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo%2Fmaps/document/primary%3Acgeo%2Fmaps%2Fmaps%2F_hgt, Av:true, files:0, dirs:0, totalFileSize:0 B, free space: 1,5 GB, files on device: 790528)
  - LOGFILES: /cgeo/maps/logfiles (Default)[/cgeo/maps/logfiles[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo%2Fmaps::/logfiles]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo%2Fmaps/document/primary%3Acgeo%2Fmaps%2Flogfiles, Av:true, files:284, dirs:0, totalFileSize:409,2 KB, free space: 1,5 GB, files on device: 790528)
  - GPX: /cgeo/maps/gpx (Default)[/cgeo/maps/gpx[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo%2Fmaps::/gpx]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo%2Fmaps/document/primary%3Acgeo%2Fmaps%2Fgpx, Av:true, files:127, dirs:0, totalFileSize:279,5 MB, free space: 1,5 GB, files on device: 790528)
  - BACKUP: /cgeo/maps/backup (Default)[/cgeo/maps/backup[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo%2Fmaps::/backup]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo%2Fmaps/document/primary%3Acgeo%2Fmaps%2Fbackup, Av:true, files:>=8, dirs:>=6, totalFileSize:>=42,1 MB, free space: 1,5 GB, files on device: 790528)
  - FIELD_NOTES: /cgeo/maps/field-notes (Default)[/cgeo/maps/field-notes[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo%2Fmaps::/field-notes]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo%2Fmaps/document/primary%3Acgeo%2Fmaps%2Ffield-notes, Av:true, files:3, dirs:0, totalFileSize:17,3 KB, free space: 1,5 GB, files on device: 790528)
  - SPOILER_IMAGES: /cgeo/maps/GeocachePhotos (Default)[/cgeo/maps/GeocachePhotos[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo%2Fmaps::/GeocachePhotos]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo%2Fmaps/document/primary%3Acgeo%2Fmaps%2FGeocachePhotos, Av:true, files:0, dirs:0, totalFileSize:0 B, free space: 1,5 GB, files on device: 790528)
  - ROUTING_BASE: /cgeo/maps/routing (Default)[/cgeo/maps/routing[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo%2Fmaps::/routing]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo%2Fmaps/document/primary%3Acgeo%2Fmaps%2Frouting, Av:true, files:9, dirs:1, totalFileSize:81,7 KB, free space: 1,5 GB, files on device: 790528)
  - ROUTING_TILES: /cgeo/maps/routing/segments4 (Default)[/cgeo/maps/routing/segments4[PERSISTABLE_FOLDER(ROUTING_BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo%2Fmaps::/routing/segments4]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo%2Fmaps/document/primary%3Acgeo%2Fmaps%2Frouting%2Fsegments4, Av:true, files:0, dirs:0, totalFileSize:0 B, free space: 1,5 GB, files on device: 790528)
  - TEST_FOLDER: [Legacy]/data/user/0/cgeo.geocaching/files/unittest (Default)[/data/user/0/cgeo.geocaching/files/unittest[FILE#1:p-file:///data/user/0/cgeo.geocaching/files::/unittest]] (Uri: file:///data/user/0/cgeo.geocaching/files/unittest, Av:true, files:0, dirs:0, totalFileSize:0 B, free space: 1,5 GB, files on device: -1)
- PersistedDocumentUris: #1
  - UNUSED_TRACK: null
- Persisted Uri Permissions: #1
  - content://com.android.externalstorage.documents/tree/primary%3Acgeo%2Fmaps (15. Juli 2022, 22:18):RW
- Database: /data/user/0/cgeo.geocaching/databases/data (v99, Size:11,5 MB) on system internal storage

--- End of system information ---
```

### Additional Information

Support ticket 410687

**Comment by ztNFny** [comment] 2023-07-13 06:58
Shows as 14.7. in live map, cache details and the cache description on GC.com ("14 July 2023, 22:00 - 22:30") for me

**Comment by ztNFny** [comment] 2023-07-13 07:25
I guess this is the "normal" issue with dates on GC - they are returned without timezone reference.
In this case it's returned as "placedDate":"2023-07-14T22:00:00" which seems to be the correct time for the timezone the cache is placed in. This datestring is then converted to a real date - and as no further information is available the users timezone is used, which in my case results in "Fri Jul 14 00:00:00 GMT+01:00 2023" but with GMT+2 it'd be "Sat Jul 15 00:00:00 GMT+02:00 2023".

This is the same issue that already exists in many tickets, e.g. wrong time for events in daylight saving time or in other countries.
The only way to address this would be to deliver a complete map of all timezones (and the date they are switching DST!) and for each cache look up the caches timezone there, then convert it to the correct timezone. - OR GC could finally start returning meaningfull dates ...

I suggest closing as wontfix

**Comment by ztNFny** [comment] 2023-07-13 07:44
Duplicate of https://github.com/cgeo/cgeo/issues/4671

**Closed by ztNFny** 2023-07-13 07:44 UTC
Labels: Bug

**Comment by Lineflyer** [comment] 2023-07-14 09:43
I know about those time zone issues, but the problem in here is, that the popup shows another date than shown in cache details. What is the reason for that?

**Comment by ztNFny** [comment] 2023-07-14 09:50
> I know about those time zone issues, but the problem in here is, that the popup shows another date than shown in cache details. What is the reason for that?

Different/More-less infos available in different sources (search results vs cache listing)
