### ISSUE TITLE
Graphic problems in dark mode

### ISSUE THREAD

**Issue by bekuno** [cgeo/cgeo#12343] opened 2021-12-17 21:59 UTC
Feedback at FB:

I noticed a bug while editing the signature (only in dark mode) 

There is a black background color (window) behind the cursor that hides the text while selecting. 

Also, during a selection, the pop-up window for "copy/paste etc" has a huge black background that covers the whole screen. I cannot see the log text when that window is on... It's almost impossible to use those tools (copy / paste / clipboard / select all) 

This only happens on the dark theme.

**Comment by fm-sys** [comment] 2021-12-17 23:22
Duplicate of  #11582 (fix is already contained on master, but impossible to backport as the material theme we use is simply not 100% compatible with the old preferences implementation)

**Closed by fm-sys** 2021-12-17 23:22 UTC
