### ISSUE TITLE
Hillshading toggle in map menu

### ISSUE THREAD

**Issue by SammysHP** [cgeo/cgeo#16176] opened 2024-10-06 07:51 UTC
### Tell us your idea!

Testing hillshading with unified map / MF right now and noticed a drop in render performance (Redmi Note 13 Pro 5G). I want to compare it with and without hillshading quickly, but always have to go back to the settings.

### What solution would you suggest?

1. Add hillshading to the map design option menu. I thought it was already there, but that must have been the old mapsforge implementation.
2. Add shortcut from the map menu to the map preferences (plural) to change sources, rendering of lines etc.

**Comment by SammysHP** [comment] 2024-10-06 07:55
Might be covered by #15847.

**Comment by ztNFny** [comment] 2024-10-06 14:26
It IS already there in master. With the master toggle in settings enabled in maps menu there's a hillshading toggle. So I don't understand this issue ...

**Comment by SammysHP** [comment] 2024-10-06 14:40
![Screenshot_2024-10-06-16-38-27-516_cgeo geocaching](https://github.com/user-attachments/assets/e8ae1430-d761-476f-9f1a-5f1e056ee570)

**Comment by ztNFny** [comment] 2024-10-06 14:41
Master toggle on preferences > map sources enabled?

**Comment by SammysHP** [comment] 2024-10-06 14:43
Yes, and hillshading is working. Looks like "Delete offline map" is also missing and I can't scroll the menu any further.

**Comment by ztNFny** [comment] 2024-10-06 14:44
Delete offline map was removed from that menu

**Comment by SammysHP** [comment] 2024-10-06 14:45
Good to know, I already found the function to delete maps in the menu of the main screen.

**Comment by moving-bits** [comment] 2024-10-06 14:50
I guess, in c:geo repo, the map toggle for hillshading is part of #15847, which is not yet merged due to ongoing discussion.

**Comment by ztNFny** [comment] 2024-10-06 14:51
> I guess, in c:geo repo, the map toggle for hillshading is part of #15847, which is not yet merged due to ongoing discussion.

No, it's not, it was part of the main hillshading PR where I also mentioned it explicitly in the changelog.

**Comment by moving-bits** [comment] 2024-10-06 14:56
I'm using current master as of today. I have enabled the hillshading master switch in Settings => Map Sources. I'm using UnifiedMap Mapsforge, but don't have a hillshading toggle in either Map Sources nor in overflow menu, only "Check for missing hillshading data":

![image](https://github.com/user-attachments/assets/29ce69bb-290a-461d-8f38-5849653eadcf)

**Comment by ztNFny** [comment] 2024-10-06 15:17
wfm on master ...

![image](https://github.com/user-attachments/assets/9313f667-f916-44f2-8ebe-a7d1f1df3f0c)

**Comment by ztNFny** [comment] 2024-10-06 15:19
the relevant line for showing it is MapProviderFactory:94
@moving-bits could you debug why apparently that one is false for you?

**Comment by ztNFny** [comment] 2024-10-06 15:27
> the relevant line for showing it is MapProviderFactory:94 @moving-bits could you debug why apparently that one is false for you?

oops, sorry, that was with the wrong settings - old map

**Comment by ztNFny** [comment] 2024-10-06 16:32
found it - during one of the rebases caused by Unified Mapsforge a commit got lost. Because of that the menu item is still bound to pref_rapidapiKey for Mapsforge maps
https://github.com/cgeo/cgeo/pull/16184

**Closed** 2024-10-19 11:21 UTC
Labels: Feature Request, Unverified
