### ISSUE TITLE
NPE in DataStore

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#9194] opened 2020-10-16 08:05 UTC
Not sure, if we already have listed this, I could however not find it.

This is the most happening bug with 2020.10.10. but also present on previous version(s):
7340 occurences, 497 users affected, various Android versions, various devices

```
java.lang.RuntimeException: 
  at android.app.ActivityThread.handleBindApplication (ActivityThread.java:7365)
  at android.app.ActivityThread.access$2400 (ActivityThread.java:308)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:2295)
  at android.os.Handler.dispatchMessage (Handler.java:110)
  at android.os.Looper.loop (Looper.java:219)
  at android.app.ActivityThread.main (ActivityThread.java:8347)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:513)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1055)
Caused by: java.lang.NullPointerException: 
  at cgeo.geocaching.storage.DataStore$PreparedStatement.getStatement (DataStore.java:3998)
  at cgeo.geocaching.storage.DataStore$PreparedStatement.simpleQueryForLong (DataStore.java:3990)
  at cgeo.geocaching.storage.DataStore.getLists (DataStore.java:3434)
  at cgeo.geocaching.CgeoApplication.onCreate (CgeoApplication.java:55)
  at android.app.Instrumentation.callApplicationOnCreate (Instrumentation.java:1202)
  at android.app.ActivityThread.handleBindApplication (ActivityThread.java:7349)
```

**Comment by MagpieFourtyTwo** [comment] 2020-10-16 09:22
Scenario?

**Comment by eddiemuc** [comment] 2020-10-16 10:17
Duplicate of #9087

**Closed** 2020-10-16 10:19 UTC
Labels: Bug, Google Play or Beta feedback

**Comment by Lineflyer** [comment] 2020-10-16 13:18
thanks @eddiemuc
