### ISSUE TITLE
"Enable Live" not available when waypoints are mapped

### ISSUE THREAD

**Issue by baiti** [cgeo/cgeo#11492] opened 2021-08-18 09:49 UTC
### Describe your problem!

In cache details view, upon long press on the compass icon next to the title I end up on the map with the currently selected cache icon shown and nothing else. The dot menu on the ight, when opened, provides an "Enable Live" function, which allows me to render all the surrounding caches too. An important feature in my workflow.

Now if I go back to the details view, swipe to the right, the waypoints for that cache are shown. If I  now long press the compass icon on one of the waypoints for that cache, I end up on the map again, with that waypoint shown on the map (centered! ... which is important, as it is not centered for the main cache but that might be a separate issue). In that view, the "Enable Live" is not available and it is not clear to me why that is so. Is that a "works as designed" for some reason? At least it would help me a great deal if I could map a waypoint and then enable live to see the surrounding caches

### How to reproduce?

This section is sufficiently described above

### Reproducible

Yes

### c:geo Version

2021.08.15

**Comment by Lineflyer** [comment] 2021-08-18 17:37
Duplicate of #6740

**Closed by Lineflyer** 2021-08-18 17:37 UTC
Labels: Bug, Unverified
