### ISSUE TITLE
Update cgeo-3-4-5 slaves/executors

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#10172] opened 2021-03-15 13:01 UTC
Hi @mucek4,

@eddiemuc investigated in #10171 , that our builds are failing on all slaves except cgeo-1 since we updated a dependency (change meanwhile reverted) which requires JDK8.

As you recently set up cgeo-1 I assume its newer. Shall/Can we apply this version to the other slaves as well?

**Comment by mucek4** [comment] 2021-03-15 13:11
Yes, cgeo-1 is newer, but you said something about not building whereyougo. I have to check if I missed anything and update all versions. Probably master is also not running JDK8.

**Comment by mucek4** [comment] 2021-03-15 13:45
@eddiemuc What do you think it's wrong on https://ci.cgeo.org/job/whereyougo%20(All%20commits)/233/console
Can't seem that new executor is able to build WhereYouGo. Probably something missing, but I can't find what? You have any idea?

**Comment by eddiemuc** [comment] 2021-03-15 14:46
@mucek4 Interesting, no idea how this happened. The commit in question can be seen in history, it was done on 21.8.21 by Lineflyer to burn in the new version "20200820". Immediately afterwards he burned in yet another version "2020.08.21" (because it was after midnight)

Googling showed me the following page with the core advise: 
"Could resolve it by temp. adding a "Wipe out repository & force clone""

http://jenkins-ci.361315.n4.nabble.com/Getting-Jgit-exception-in-a-Job-that-uses-native-Git-td4914637.html

**Comment by eddiemuc** [comment] 2021-03-15 14:48
Interestingly enough, executing "git show-ref --tags -d # timeout=10" does not return the tag in question even on my local machine

**Comment by mucek4** [comment] 2021-03-15 16:59
@eddiemuc I'm updating executor 1 to system-images;android-30;google_apis;x86_64 If it will be OK. I'll update all other executors too.

**Comment by eddiemuc** [comment] 2021-03-16 09:03
@mucek4 : did some more playing around, found the following:
* I went to the last job of yesterday which was executed on a previously empty workspace (https://ci.cgeo.org/job/whereyougo%20(All%20commits)/235/console) and thus had to do an initial clone. I executed the exact same sequence of git commands I found in the console log on a new, empty folder on my local machine. It works out perfectly.
* BUT I found another clue: according to the console log aboive we are doing a "shallow clone". This might be the cause of the issue. Can we maybe do a "full clone" instead and see whether this works? Alternative: can we try to set the "Honor refspec on initial clone" to true in the "Advanced cloning settings"? (I found these hints here: https://issues.jenkins.io/browse/JENKINS-44323, ) 

I don't think I have the necessary Jenkins permissions to do this myself unfortunately...

**Comment by mucek4** [comment] 2021-03-16 12:53
@eddiemuc I have seem the shallow clone too, and as far as I see we don't have that on cgeo repo. Will try both things in the afternoon.

**Comment by mucek4** [comment] 2021-03-17 18:56
@eddiemuc removing shallow clone works. I have cloned our Jenkins to test instance and tried it out.
Will update executors in next days.

**Comment by Lineflyer** [comment] 2021-03-27 09:15
I am not sure, but it seems cgeo-1 has a higher failure rate to start the emulator if you compare with the others:

https://ci.cgeo.org/computer/cgeo-1/builds

**Comment by Lineflyer** [comment] 2021-03-27 09:19
Yes, seems obvious if you e.g. compare with cgeo-4. It has only real failed build whereas for cgeo-1 often build fails due to emulator not starting.

**Comment by Lineflyer** [comment] 2021-04-15 13:33
@mucek4 
cgeo-4 and 5 are down and cgeo-1 seems to fail rather often/always to run the emulator. :(

**Comment by bekuno** [comment] 2022-01-01 20:29
cgeo-1,-4, -5 are running with java11, therefore closing here

**Closed by bekuno** 2022-01-01 20:29 UTC
Labels: CI server / Build tools
