### ISSUE TITLE
Raise minSDK to 21

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#8248] opened 2020-04-25 13:04 UTC
As discussed on the mailing list, let's drop support for Android < 5.0 with the release after the next. Prerequisite is #8246 having been released before and branching a new legacy version from that state of master branch.

**Comment by bekuno** [comment] 2020-04-25 14:56
I see this Issue as duplicate of issue #8120.
Lets discuss the change there.

**Comment by Lineflyer** [comment] 2020-04-25 15:58
ok

**Closed by Lineflyer** 2020-04-25 15:58 UTC
