### ISSUE TITLE
Base folder "c:geo" not selectable

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#10494] opened 2021-04-28 09:44 UTC
## Bug description 

A user on support mail created a folder `c:geo` as his base folder and reported, that taking over the folder during migration fails. After removing the `:` it worked normally.

### Steps to reproduce the problem

- Start migration (or manual base folder selection in Settings - System)
- In the dir chooser create a folder `c:geo`
- Confirm selection

### Actual result after these steps 

c:geo returns to the base folder selection screen (when migration is active) and shows an error toast "Aborting folder selection"

### Expected result after these steps 

Folder should be usable

## c:geo version 

2021.04.25

## Reproducible 

I can reproduce this on my Google Pixel 3a, Android 11, will take a log later.

## System information 

Not yet available

## Additional context
Using a `:` is unusual, but as the system allows such folders and its part of our app name, its not unlikely it might happen to other users as well.

**Comment by Narrat** [comment] 2021-04-28 12:16
This is such a special character... Filesystems on linux mostly do allow the :, but if you need to exchange files with someone who is most likely using something different as a filesystem.. well, avoidable hassle.
The colon is not allowed for folders or files on NTFS, FAT32 (and most likely exFAT).
The one filesystem from Apple also doesn't allow the : for folders or files.
Dunno about the file URI scheme or the URI scheme in general, but as far as I know it is a reserved char, so there is a special meaning or usage possible.
Example for the special handling: internal memory and a sd-card are available. If I create c:geo on the internal memory, it will be created as such. Do I create the same folder on the sd-card it will either error out or change to c_geo.
If there isn't a really simple solution I would abstain from supporting this.

**Comment by eddiemuc** [comment] 2021-04-28 12:50
Funnily enough, the Uri in question in #10457 also contains a : (decoded as %3A) so maybe you are up to something here...

I can however not reproduce this. In emulator using : works fine and on my mobile phone : is not allowed as a filename character.

I would be **very** interested in the log :-)

**Comment by Lineflyer** [comment] 2021-04-28 19:12
I don't know how the hell I created that folder at first place.
It was there and I selected it....some time later I deleted it. Now I wanted to check the log but fail to create it. As described by @Narrat it automatically replaces `:` by `_` on the same storage.

Will try a bit more.

**Comment by Lineflyer** [comment] 2021-04-28 19:22
Seems I created it within Android Studio using its Device Explorer...but unable to create it on the device itself, which means it no relevant scenario for users probably.

This is the log as requested by @eddiemuc (Feel free to close this issue):
```
2021-04-28 21:20:37.220 3026-27674/? E/MediaProvider: File name contains invalid characters
2021-04-28 21:20:37.221 28698-29300/? E/DatabaseUtils: Writing exception to parcel
    java.lang.IllegalStateException: Failed to touch /storage/emulated/0/c:geo/cgeo-file-2021-04-28-21-20-37-8.txt: java.io.IOException: Operation not permitted
        at com.android.internal.content.FileSystemProvider.createDocument(FileSystemProvider.java:271)
        at android.provider.DocumentsProvider.callUnchecked(DocumentsProvider.java:1142)
        at android.provider.DocumentsProvider.call(DocumentsProvider.java:1078)
        at com.android.externalstorage.ExternalStorageProvider.call(ExternalStorageProvider.java:654)
        at android.content.ContentProvider.call(ContentProvider.java:2448)
        at android.content.ContentProvider$Transport.call(ContentProvider.java:517)
        at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:295)
        at android.os.Binder.execTransactInternal(Binder.java:1154)
        at android.os.Binder.execTransact(Binder.java:1123)
2021-04-28 21:20:37.222 27561-27561/? E/cgeo: [main] Error on testing read/write of folder /c:geo[DOCUMENT#0:p-content://com.android.externalstorage.documents/tree/primary%3Ac%3Ageo::], testWrite=true
    java.lang.IllegalStateException: Failed to touch /storage/emulated/0/c:geo/cgeo-file-2021-04-28-21-20-37-8.txt: java.io.IOException: Operation not permitted
        at android.os.Parcel.createExceptionOrNull(Parcel.java:2381)
        at android.os.Parcel.createException(Parcel.java:2357)
        at android.os.Parcel.readException(Parcel.java:2340)
        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:190)
        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:142)
        at android.content.ContentProviderProxy.call(ContentProviderNative.java:732)
        at android.content.ContentResolver.call(ContentResolver.java:2405)
        at android.provider.DocumentsContract.createDocument(DocumentsContract.java:1371)
        at cgeo.geocaching.storage.DocumentContentAccessor.createInternal(DocumentContentAccessor.java:117)
        at cgeo.geocaching.storage.DocumentContentAccessor.create(DocumentContentAccessor.java:98)
        at cgeo.geocaching.storage.ContentStorage.create(ContentStorage.java:179)
        at cgeo.geocaching.storage.ContentStorage.tryTestReadWriteToFolder(ContentStorage.java:502)
        at cgeo.geocaching.storage.ContentStorage.ensureFolder(ContentStorage.java:143)
        at cgeo.geocaching.storage.ContentStorageActivityHelper.handleResultPersistableFolderSelection(ContentStorageActivityHelper.java:319)
        at cgeo.geocaching.storage.ContentStorageActivityHelper.onActivityResult(ContentStorageActivityHelper.java:187)
        at cgeo.geocaching.settings.SettingsActivity.onActivityResult(SettingsActivity.java:710)
        at android.app.Activity.dispatchActivityResult(Activity.java:8310)
        at android.app.ActivityThread.deliverResults(ActivityThread.java:5002)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:5050)
        at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7660)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

**Comment by eddiemuc** [comment] 2021-04-29 05:59
Strange situation indeed. I implemented a read/write test on new folder selection (a dummy file is created then read again, then deleted, to ensure that we really can access the new selected folder). This is the place where the operation is failing. 

Handling of c:geo of this situatio is correct imho. Only thing we could do in addition is showing the exception message to the user ("Failed to touch /storage/emulated/0/c:geo/cgeo-file-2021-04-28-21-20-37-8.txt" in english) instead of the generic "Aborted" message. But I guess this would not really help either. So I would close this.

How disappointing, I thought we might have found the reason for #10457...

**Closed by eddiemuc** 2021-04-29 05:59 UTC
Labels: Unverified
