### ISSUE TITLE
Edit log

### ISSUE THREAD

**Issue by geocachermgo** [cgeo/cgeo#15109] opened 2023-12-27 20:39 UTC
### Describe your problem!

I edited a log with pictures.
After I send it a message with error report showed up.
There was a second, copied log with type changed to remark and the changes.
I checked on the website and the log was successfully changed.
I edited the remark in c:geo and used "Log leeren".
But the log was not dissapearing even after several tries.
When I went back to the home screen and the to the cache the additional log was not there anymore.
![Screenshot_2023-12-27-15-55-20-308_cgeo geocaching](https://github.com/cgeo/cgeo/assets/43813636/8fd2e922-8513-4e62-b519-07d8c666c5db)

### How to reproduce?

Did not systematically try to reproduce but will use and observe further.

### Reproducible

Yes

### c:geo Version

2023.12.27-NB-54d0bc0

**Comment by eddiemuc** [comment] 2023-12-27 23:42
I am not 100% sure what exactly is the observed problem. Is it that after editing a log an offline log appeared which can't be deleted any more?

(Not that unlike newly created logs, an edited log can't be saved offline but just be sent immediately. Well at least this is the intended behavior...)

**Comment by geocachermgo** [comment] 2023-12-28 05:33
From my point I see 3 problems:
1. if a log is successfully edited, it should not be shown as unsuccessful
2. With the edit function no second log should be created. If there are send problems the log should go back to orange (offline stored).
I'm not so sure what should happen if during editing in c:geo the log was also edited on the website.
3. An offlinge stored log should be not undeletable
(4. The german wording "Leeren" = "clear log"? should be replaced by "Löschen")

**Comment by eddiemuc** [comment] 2023-12-28 08:54
Thanks a lot for these details.

> 1. if a log is successfully edited, it should not be shown as unsuccessful

Correct :-) 
Do you have an log file from this? (Might be an exception there) Is this reproducible? Does it (only) happen if you add an image?

> 2. With the edit function no second log should be created. If there are send problems the log should go back to orange (offline stored).

Correct, no second log should be created. If a log is edited then no orange entry should be created at all. (Offline storage for edited log is not supported)

> I'm not so sure what should happen if during editing in c:geo the log was also edited on the website.

We can't technically detect this situation. c:geo would simply override the changed log on the website.

> 3. An offline stored log should be not undeletable

Ok

**Comment by geocachermgo** [comment] 2023-12-28 11:47
Just send logfile via mail to support@

**Comment by eddiemuc** [comment] 2023-12-29 07:32
Nr 2 should be solved with PR #15110
 Nr 3 was most likely a follow -up-problem of Nr 2 and thus also solved.

As of now I couldnt reproduce Nr 3 , but I will keep my eyes open. In general, it can happen that c:geo gets an invalid response back from server but the log was successfully stored/changed nevertheless (we have no control over what the GC.com server is doing and sending), but c:geo should react in a good way towards the user in such situations.

**Comment by eddiemuc** [comment] 2024-01-20 15:17
I assume this is solved and will thus close the issue. If this is wrong, please reopen.

**Closed by eddiemuc** 2024-01-20 15:17 UTC
Labels: Bug, Unverified
