### ISSUE TITLE
Crash when check gcvote with empty string 

### ISSUE THREAD

**Issue by akkatracker** [cgeo/cgeo#5205] opened 2015-09-26 02:29 UTC
Possibly only if service is active and you press check.

**Comment by rsudev** [comment] 2015-09-26 05:46
Doing a short cross-check I was not able to reproduce this directly.
Did you enter valid credentials in your case?
Could you please post your system info (about c:geo - system tab)?

**Comment by samueltardieu** [comment] 2015-09-26 08:54
I could reproduce this. The credentials need to be empty.

**Comment by samueltardieu** [comment] 2015-09-26 10:15
Let this stay on `master` for a few weeks, then if there are no problems we can merge it to `release`. The change touches all kind of username/password credentials, so it needs to be field tested over some time.

Assigning to @Lineflyer for testing.

**Comment by akkatracker** [comment] 2015-09-26 10:59
I presume you don't need system details anymore?

**Comment by rsudev** [comment] 2015-09-26 14:09
Right :)

**Comment by Lineflyer** [comment] 2015-10-06 08:54
@samueltardieu 
Any special test case you would think of for this change.
If I read the code I should probably verify that entering and verifying credentials is possible for all connectors as well as checking the reaction on empty fields.

**Comment by Lineflyer** [comment] 2015-10-19 07:29
User management seems to work flawless with this change.
I also tried several things like empty usernames and passwords and the reaction was always appropriate.
Due to the wide scope of this change I would still leave it on `master` only for the next feature release.

**Closed by Lineflyer** 2015-10-19 07:29 UTC
Labels: Bug, Field test, low
