### ISSUE TITLE
Select cache type directly from within map view

### ISSUE THREAD

**Issue by caco3** [cgeo/cgeo#5740] opened 2016-05-13 11:41 UTC
It would be very handy if one could select the shown cache type directly from inside the map view.
This could be similar to how one currently can select the map source.

As is now, one always has to exit the map, select the new cache type and enter the map again.

**Comment by SammysHP** [comment] 2016-05-13 11:49
Duplicate of #3346.

**Closed by SammysHP** 2016-05-13 11:49 UTC
