### ISSUE TITLE
When moving the map the cache icons are only moved after map tiles loaded

### ISSUE THREAD

**Issue by laking123** [cgeo/cgeo#4365] opened 2014-09-18 07:43 UTC
problem on android geo caches not fixed to map when zoomed in and scrolling slidding of there fixed positions

**Comment by Lineflyer** [comment] 2019-03-31 22:18
Let me retest this on current master.

**Comment by Lineflyer** [comment] 2019-08-01 19:46
I can no longer clearly reproduce this old issue, so lets close here and reopen if new facts come in.

**Comment by Lomanic** [comment] 2019-08-01 20:34
I still reproduce on 2019.07.25-RC. 

Steps to reproduce

1. Open Live Map, set tiles as Google Maps (I think I can't reproduce with OSM: Map)
2. Display some caches on the map
3. Go in Airplane mode
2. Zoom out, cgeo is not able to retrieve tiles for this zoom level (grey background)
3. Watch tiles (from the previous zoom level) move from their position with some kind of arc related of your swiping movement and caches move as if they were on the new zoom level, until you exit Airplane mode and cgeo loads all the tiles. It makes a weird effect as if caches were moving on the map (relatively to the previous zoom level tiles). 

I could even see this behavior on a fast 4G mobile network by trying to move the map as fast as possible just after zooming in/out (without going into Airplane mode), but this is obvious with a slow network or in Airplane mode to reproduce.

**Comment by Lomanic** [comment] 2019-11-15 23:14
This is not an issue anymore on 2019.11.11 thanks to GoogleMapsV2 upgrade.

**Comment by moving-bits** [comment] 2019-11-24 10:34
@Lomanic  Thanks for retesting.
I'll close this issue then.

**Closed by moving-bits** 2019-11-24 10:34 UTC
Labels: Field test, Live Map, Prio - Low
