### ISSUE TITLE
Attach images to logs not supported for The Opencaching network. Why?

### ISSUE THREAD

**Issue by Opencachingna** [cgeo/cgeo#5525] opened 2016-03-11 05:19 UTC
Something with OKAPI? File upload size limits on the individual servers?

**Comment by rsudev** [comment] 2016-03-11 05:23
Not available on OKAPI yet: https://github.com/opencaching/okapi/issues/360

**Comment by Opencachingna** [comment] 2016-03-11 05:24
Thanks! Close it, if you like. Didn't come up on my search.

**Comment by SammysHP** [comment] 2016-03-11 09:36
Duplicate of #4137.

**Closed by SammysHP** 2016-03-11 09:36 UTC
