### ISSUE TITLE
Button to change map type not visible

### ISSUE THREAD

**Issue by balu2003** [cgeo/cgeo#7329] opened 2019-02-25 08:05 UTC
##### Detailed steps causing the problem:
- choose any cache
- tap button for navigation (arrow to the right lower )
- choose maps
- if the view was "satellite", the button for navigate (arrow to the point) ist not visibile, because of white button on white background
- tap on the interspace beetween the buttons "position" and "menü", then then maps dialog pops up and you can choose an other map (like OSM Offline)

The button for "navigation" is working but not visible in satellite mode.

##### Version of c:geo used:
2019.02.23

##### Is the problem reproducible for you?
Yes

##### System information:
```
--- System information ---
Device: SM-G930F (heroltexx, samsung)
Android version: 7.0
Android build: NRD90M.G930FXXU2DRC1
c:geo version: 2019.02.23
Google Play services: disabled - 15.0.90 (040408-231259764)
Low power mode: inactive
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: rotation vector
Hide own/found: false
Map strategy: detailed
HW acceleration: enabled (default state)
System language: de_DE
System date format: dd.MM.yy
Debug mode active: no
System internal c:geo dir: /data/user/0/cgeo.geocaching (16,3 GB free) internal
User storage c:geo dir: /storage/emulated/0/cgeo (16,3 GB free) external non-removable
Geocache data: /storage/0001-4880/Android/data/cgeo.geocaching/files/GeocacheData (37,8 GB free) external removable
Database: /storage/emulated/0/Android/data/cgeo.geocaching/files/databases/data (10,3 MB) on user storage
Fine location permission: granted
Write external storage permission: granted
Geocaching sites enabled:
   geocaching.com: Logged in (Anmeldung OK) / PREMIUM
   opencaching.de: Logged in (Anmeldung OK)
Geocaching.com date format: dd.MM.yyyy
Installed c:geo plugins:  none
--- End of system information ---

sry, my english is worse

**Comment by balu2003** [comment] 2019-02-25 08:39
![20190225_093309](https://user-images.githubusercontent.com/23136373/53324367-e6f29c80-38e0-11e9-9f28-e8ee72595520.jpg)

**Comment by Lineflyer** [comment] 2019-02-25 12:49
Thanks for reporting

**Comment by Lineflyer** [comment] 2019-02-25 14:09
@balu2003 Could you check how the OSM map looks for you?

**Comment by balu2003** [comment] 2019-02-25 15:54
![screenshot_20190225-165152](https://user-images.githubusercontent.com/23136373/53349679-eb897600-391d-11e9-8bf7-72b8098080de.jpg)

OSM offline map

**Comment by moving-bits** [comment] 2019-02-25 16:10
Looks like light theme is selected and respected for satellite map, but OSM new map choses dark theme. And light theme uses the wrong button, then.

**Comment by balu2003** [comment] 2019-02-25 18:00
If I use Settings->Appearance ->NOT Light Skin
and use the maps
Google Maps (white menu background -> button not visible)
Google Satellite (white background -> not visible)
OSM: Mapnik (dark background -> visible
any OSM offline-map (dark background - visible)

If I change the Settings->Appearance -> Light Skin
and use the maps
Google Maps (dark menu background -> button  visible)
Google Satellite (dark background ->  visible)
OSM: Mapnik (dark background -> visible
any OSM offline-map (dark background - visible)

So, when I reported the issue, the light theme was NOT selected.

**Comment by moving-bits** [comment] 2019-02-25 21:49
Ok, thanks for clarifying. So it's the other way around - dark theme chosen, but Google map view does not adhere to that choice. Might be a side effect of the targetSDK26 changes? (@Lineflyer Do you still have a device available with pre-targetSDK26 installed and can compare this?)

**Comment by Lineflyer** [comment] 2019-02-25 22:51
I would need to reinstall an older release which is not a big deal, but interesting here is, that for me the title bar is always black on gmaps. mmh...

**Comment by balu2003** [comment] 2019-02-25 23:05
It's a bit amazing. With my "old" Acer tablet with Android 4.2.2 and NB 2019.02.23 or NB 2019.02.25 everthing is working fine. If I chose the dark theme in settings, all the background (menu) bars for alle map-types are black and the  button is visible. 
My smartphone uses still Android 7.0. And if I understand right, SDK26 ist for Android 8.0 and higher.
If nobody else has this problem with the hidden button, then close the issue. I know how to work around. Thanks for your response.

**Comment by bekuno** [comment] 2019-02-26 07:08
I have the same effect on android 7. The colors and icons differ between the android versions.

**Comment by Lineflyer** [comment] 2019-02-26 17:23
Setting label "High". Lot of users report, that different maps are no longer available...they are, but the button is invisible.
Should be fixed rather urgent.

**Comment by Lineflyer** [comment] 2019-02-26 23:17
I played around with my Android 8.0 device:
When I use the default black skin I see this "older" looking design with black background and cyan line on GMaps and in Settings. 
However when I switch to light skin GMaps and Settings show a similar design as with black skin on new map and other parts of the app.

Could it be, that this is somehow only mixed up.
I mean if we achieve, that the white skin look on GMaps and Settings is used while black skin is activated the whole app would look pretty the same at least on my Android 8 device.

**Comment by Lineflyer** [comment] 2019-02-26 23:18
Cant produce screeb shots as I am on business trip, but if you take an Android 8 emulator it should be reproducible.

**Comment by bekuno** [comment] 2019-02-27 21:34
Maybe it is a problem raised by the appCompat Library?
I created a PR that the result can be checked (without maps API key).

**Comment by rsudev** [comment] 2019-02-28 04:54
I have an idea for the reason, will try to check it later today.

**Comment by rsudev** [comment] 2019-02-28 20:35
Currently I do not have any means to reproduce this issue, unfortunately. I tried emulators from API 17 up to 26 (omitting 20 and 21), but everywhere the google map api action bar was dark...
As we have to use a 'native' theme there (as we cannot derive from the appcompat activity) this might be influenced by the, possibly vendor specific; theme of the device as such.
Anybody with a samsung device who can cross-check?

**Comment by rsudev** [comment] 2019-02-28 22:22
Different approach as a workaround: Add an outline to the icon as the others have (see my PR)

**Closed** 2019-03-01 21:26 UTC
Labels: Bug, Frontend Design, high, sdk26-regression
