### ISSUE TITLE
targetSdk 33

### ISSUE THREAD

**Issue by bekuno** [cgeo/cgeo#14499] opened 2023-08-10 20:51 UTC
### Tell us your idea!

From Google: https://developer.android.com/google/play/requirements/target-sdk
~~~
Starting on August 31, 2023:

   - New apps must target Android 13 (API level 33) or higher; except for [Wear OS](https://developer.android.com/wear) apps, which must target a version between Android 11 (API level 30) and Android 13 (API level 33), inclusive.
   - App updates must target Android 13 or higher and adjust for behavioral changes in Android 13; except for Wear OS apps, which must target Android 11.
~~~

We are currently at targetSdk 31.

### What solution would you suggest?

Move to targetSdk 33 after the next release.

### Is there an alternative?

No, from August 31, 2023

### Additional Information

https://developer.android.com/google/play/requirements/target-sdk#pre13
https://developer.android.com/about/versions/13/behavior-changes-13

**Comment by moving-bits** [comment] 2023-08-13 07:52
From a quick scan at least this section seems to be relevant to us: https://developer.android.com/about/versions/13/behavior-changes-13#granular-media-permissions

**Comment by moving-bits** [comment] 2023-08-19 20:57
PR #14527 will set `targetSDK` to 33. Let's see in the nightlies whether additional adaptions are required.

**Comment by Lineflyer** [comment] 2023-08-23 22:20
I just visited Google Play Console first since longer time.
Seems they are enforcing this requirement, means we need next release either to be SDK33 targeted or need to release prior end of August.

I am posting this, as I remember to have read some threads on here with a (kind of major) regression regarding long tap on map and route planning. So we should thinkn about whether a short term bug fix before end of August makes sense to get rid of that.

Sorry I I missed some other thread dealing with this release scenarios...to less time to catch up at this moment.

**Comment by moving-bits** [comment] 2023-08-24 06:12
I propose to (and can prepare a) release before the weekend. We have reverted the Google renderer update which caused the long tap on map markers problem, and have some minor other fixed on `release` as well.

We have upgraded `master` to targetSDK 33 a couple of days ago and no problems reported for this so far, so we have a possible update in the queue, but it needs some more "time in the wild" before we should release that.

**Comment by Lineflyer** [comment] 2023-08-24 19:52
Sounds good as some tickets from users keep incoming which look related to this long tap problem.

**Comment by moving-bits** [comment] 2023-09-13 19:37
As discussed in our last dev meeting I did some tests regarding `targetSDK` 33:
- Create a fresh API 33-based emulator
- Install c:geo (no backup)
- Upload some files (images and other docs) using Android Studio's "device explorer"
- Try to attach those files to a cache's gallery => alle uploaded files have been visible (I tried with "documents" folder and with root folder)
- Go to map, activate live mode, and select "download unstored caches" => downloading did work fine, and notifications were shown

Sometimes during the test, before trying the "download caches" part, c:geo had asked me to "allow notifications" which I granted. I guess I had triggered some other action that required a notification from c:geo at that time.

Conclusion is: On a quick glance it looks like we do not have to make any adjustments for `targetSDK` 33, which fits well into our nightlies having `targetSDK` 33 since a month or so without any complaints.

I'll start working on preparing a beta version from `release`, if no one stops me in the next couple of minutes :-)

**Comment by Lineflyer** [comment] 2023-09-13 21:53
I am wondering about the notification permission behavior you perceived in your tests.
On my API33 device the notifications are missing and the permission handler does not have the option to enable them. I have constantly used the nightly versions on that device, which implies notifications get lost somehow on that upgrading path to SDK33. Not a severe issue, but I bet some beta testers will experience the same. That would mean, we need to request that permission in our manifest to allow API33 users to have notifications.

**Comment by moving-bits** [comment] 2023-09-14 20:05
That's strange indeed. When reading https://developer.android.com/develop/ui/views/notifications/notification-permission it looks like we need to list the permission in the manifest + trigger the request dialog at some useful place. It explicitly recommends not to do so on program startup (as we do for the other rights with the wizard), but to do so "in context" and "after the user got familiar with the app". I'll open a separate issue for this.

**Comment by moving-bits** [comment] 2023-10-07 18:25
targetSDK 33-enabeld version is out in general release since > 10 days meanwhile, and no specific problems on support so far, so let's close here. We can open specific issues, if something should come up later.

**Closed by moving-bits** 2023-10-07 18:25 UTC
Labels: Feature Request
