### ISSUE TITLE
Archived caches stay in Live map

### ISSUE THREAD

**Issue by balevas** [cgeo/cgeo#7857] opened 2019-09-18 14:09 UTC
**Describe the bug:**
Live map keeps showing archived caches that were once stored locally, even if they have been removed from the list in the meantime.

**To Reproduce:**
1. Find an archived cache (one that you haven't found), e.g. by its GC code - preferably one that had been placed near your current location. (for me, GC2K2YD works well)
2. Save the cache to a list in c:geo (e.g. "Stored")
3. The cache can now be seen in the Live map, having a "diskette" symbol since it is stored locally.
4. Remove the cache from the list

**Actual behavior/state after performing these steps:**
The cache still remains in the live map and the only way how to clear it is to set "Hide disabled caches" in the map settings. But that also hides all disabled (but still living) caches, which is not desired. 
Killing c:geo or restarting the phone does not help.
This issue typically happens when a cache that I had stored in a list before gets archived.

**Expected behavior/state after performing these steps:**
Live map shouldn't normally show archived caches. If an archived cache is stored locally, the live map can show it. However, once that cache is removed from the list it should no longer be shown on the map.

**Version of c:geo used:**
2019.09.08

**Is the problem reproducible:**
Yes

**Screenshots:**
N/A

**System information:**
```
--- System information ---
Device: ASUS_Z00AD (WW_Z00A, asus)
Android version: 6.0.1
Android build: MMB29P.WW-ASUS_Z00A-4.21.40.352_20170623_7598_user
c:geo version: 2019.09.08
Google Play services: enabled - 19.2.75 (040700-269183835)
Low power mode: inactive
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: rotation vector
Hide own/found: true
HW acceleration: enabled (default state)
System language: en_US
System date format: M/d/yy
Debug mode active: no
System internal c:geo dir: /data/user/0/cgeo.geocaching (12.0 GB free) internal
User storage c:geo dir: /storage/emulated/0/cgeo (12.0 GB free) external non-removable
Geocache data: /storage/emulated/0/Android/data/cgeo.geocaching/files/GeocacheData (12.0 GB free) external non-removable
Database: /data/user/0/cgeo.geocaching/databases/data (8.9 MB) on system internal storage
Fine location permission: granted
Write external storage permission: granted
Geocaching sites enabled:
   geocaching.com: Logged in (Login OK) / PREMIUM
Geocaching.com date format: d. M. yyyy
Installed c:geo plugins:  none
--- End of system information ---
```

**Additional context:**
N/A

**Comment by Lineflyer** [comment] 2019-09-18 15:53
The cache will vanish after 72 hours. In this time period previously opened or saved caches are "cached" internally to avoid double loading in case of accidental removal.

**Comment by alan666notb** [comment] 2019-09-19 15:13
Could this be addressed by my recent feature request - #7848

**Comment by balevas** [comment] 2019-09-23 07:36
In my opinion, background caching of caches to avoid double loading is an internal feature of the application (unknown to almost all users) and should not interact with the way how caches are shown on the live map. There should be clear rules how the map works, related to the states of caches and settings of the application that are known to the user, such as:
- show all caches that aren't archived
- show archived caches if they are stored locally
- hide own/found/disabled/... caches according to the application settings
Keeping of the caches in an internal cache should be working in the background and the user should not be aware of it at all, while working with the map or cache list.

**Comment by Lineflyer** [comment] 2019-09-30 20:27
Well, its a live map. All data available on all channels will appear on the map. 
The real problem here is, that we are missing a filter to hide "archived caches" as this is a very rare scenario (they only appear if you have saved list containing them or in the case described above). 

The problem is not, that archived caches are shown, but only the missing filter for it.

**Comment by Lineflyer** [comment] 2019-09-30 20:28
See #7848

**Closed** 2019-09-30 20:28 UTC
Labels: Bug, Unverified
