### ISSUE TITLE
Cache types not updated even when max zoomed

### ISSUE THREAD

**Issue by JosuEleder** [cgeo/cgeo#6840] opened 2017-11-13 15:00 UTC
##### Detailed steps causing the problem:
When I select an area of the map I always see caches that I have already found. I have "Hide owned and found caches" on, and "Detailed" strategy, so they shouldn't appear. Sometimes they appear with "??" but other times no.

I start zooming the area until I'm in an area with just 4-5 caches, but still the already-found caches appear in the map.

##### Actual behavior after performing these steps:
When I click in one of these caches, it actually shows in the Details page that it's already found. When I return to the map this cache finally doesn't appear (the "found" information is already updated), but the rest of the found caches still appear.

##### Expected behavior after performing these steps:
With "Hide found caches" on and "Detailed" strategy I would expect that no found caches appear in the map, at least when I zoom the area to some 20 caches.

##### Version of c:geo used:
2017.10.23 (Spanish)

##### Is the problem reproducible for you?
Yes, it happens every time

##### System information:
```
--- System information ---
Device: ONEPLUS A3003 (OnePlus3, OnePlus)
Android version: 7.1.1
Android build: ONEPLUS A3003_28_171012
c:geo version: 2017.10.23
Google Play services: enabled - 11.7.46 (440-175121617)
Low power mode: inactive
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: rotation vector
Hide own/found: true
Map strategy: detailed
HW acceleration: enabled (default state)
System language: es_ES
System date format: d/M/yy
Debug mode active: no
System internal c:geo dir: /data/user/0/cgeo.geocaching (26,5 GB free) internal
User storage c:geo dir: /storage/emulated/0/cgeo (26,4 GB free) external non-removable
Geocache data: /storage/emulated/0/Android/data/cgeo.geocaching/files/GeocacheData (26,4 GB free) external non-removable
Database: /data/user/0/cgeo.geocaching/databases/data (456,0 KB) on system internal storage
Fine location permission: granted
Write external storage permission: granted
Geocaching sites enabled:
   geocaching.com: Logged in (Acceso conseguido) / BASIC
Geocaching.com date format: MM/dd/yyyy
Installed c:geo plugins:  none
--- End of system information ---

```

**Comment by Lineflyer** [comment] 2017-11-13 15:29
Are you using the option "Use mapsforge beta map as default" in Menu - Settings - System?

**Comment by JosuEleder** [comment] 2017-11-13 15:34
No, I was not. Thank you for the suggestion. I'll try it out.

**Comment by Lineflyer** [comment] 2017-11-14 22:28
> No, I was not, thank you for the suggestion.

I was actually thinking the other way around...the new beta map might have known update problems in your described case.

Besides that: 
As a basic member we retrieve quite few information regarding caches on live map.

Other questions would be: 
- Those caches which are still displayed while found, are they with orange circles?
- Is the live map completed with loading...no more spinning circle in top row?

**Comment by JosuEleder** [comment] 2017-11-15 09:01
Thanks!

Today I was trying to verify the issue and I noticed something strange. I opened gc and just not found caches appeared (as expected). But then, after opened a couple of caches and returned to the map, my already found caches appeared in the map as well, some of them with "??" and others not, and all of them with orange circle. The map completed loading (no circle spinning). 

In short, the program behaved correctly when first opened, but found caches appeared again in live map after opening some caches and returning to the map.

I can provide screenshots if they are of use.

**Comment by JosuEleder** [comment] 2017-11-17 17:25
Just a last test:
I have just launched the app and opened the map to the default position (the position it was when I last used it), and the caches were shown correctly.

Then I have reduced the zoom, to show a larger area, and then the already-found caches have appeared (even in the area that I was seeing earlier). I have done zoom again but the already-found caches have stayed, until I have opened each one of them and "refreshed" their "found" information.

**Comment by Lineflyer** [comment] 2018-01-08 11:25
Meanwhile I received some similar reports on our support channels.
AFAIR we have not changed anything map related explicitly in the last year, however the website changed a lot (DNF marker, Final marker). As map parsing is a difficult topic, I will try to debug this with ADB logging and see if I can find out anything related to this issue.

Anyway as @JosuEleder is a basic member the hiding of found caches is a bit more likely to fail anyway due to known limitations.

**Comment by Lineflyer** [comment] 2018-08-06 20:50
Seems to be a duplicate of #5902.

**Closed by Lineflyer** 2018-08-06 20:50 UTC
Labels: Bug, Field test, Unverified
