### ISSUE TITLE
[latest nightly] Crash when selecting Cache in Live Map

### ISSUE THREAD

**Issue by MagpieFourtyTwo** [cgeo/cgeo#7371] opened 2019-03-14 21:25 UTC
##### Detailed steps causing the problem:
- configure c:geo to use old Mapsforge V3
- open live map
- select a cache

##### Actual behavior after performing these steps:
- app crash ...

##### Expected behavior after performing these steps:
- show popup with cache details

##### Version of c:geo used:
2019.03.14-NB-971f289

##### Is the problem reproducible for you?
Yes

##### System information:
--- System information ---
Device: E6853 (E6853, Sony)
Android version: 7.1.1
Android build: 32.4.A.1.54
c:geo version: 2019.03.14-NB-971f289
Google Play services: disabled - 15.0.90 (040408-231259764)
Low power mode: active
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: rotation vector
Hide own/found: true
Map strategy: detailed
HW acceleration: enabled (default state)
System language: de_DE
System date format: dd.MM.yy
Debug mode active: no
System internal c:geo dir: /data/user/0/cgeo.geocaching (4,8 GB free) internal
User storage c:geo dir: /storage/emulated/0/cgeo (4,8 GB free) external non-removable
Geocache data: /storage/emulated/0/Android/data/cgeo.geocaching/files/GeocacheData (4,8 GB free) external non-removable
Database: /data/user/0/cgeo.geocaching/databases/data (233,6 MB) on system internal storage
Fine location permission: granted
Write external storage permission: granted
Geocaching sites enabled:
   geocaching.com: Logged in (Anmeldung OK) / PREMIUM
   extremcaching.com: Logged in (Anmeldung OK)
Geocaching.com date format: dd MMM yy
Installed c:geo plugins: contacts
--- End of system information ---

##### Other comments and remarks:
Using new Mapsforge is not an option, as it still does not show all Caches (resp. needs to be re/zoomed) and the Waypoints of (seemingly other stored) Caches pollute the map.

**Comment by UniQP** [comment] 2019-03-14 21:44
Might be a duplicate of #7337.

**Comment by MagpieFourtyTwo** [comment] 2019-03-15 13:20
Add. Info:
- when using "Google: Map" or "Google: Satellite", no crash happens, but the popup does not open either (IOW: nothing happens at all ;) ).

**Comment by Lineflyer** [comment] 2019-03-15 15:18
I can reproduce it. Pretty sure it is a duplicate of the mentioned issue. Lets still keep this open to check if the potential fix also fixes the old osm map.

**Comment by Lineflyer** [comment] 2019-03-15 15:39
Solved with  16420dd as assumed

**Closed by Lineflyer** 2019-03-15 15:39 UTC
Labels: Bug, Duplicate, high

**Comment by moving-bits** [comment] 2019-03-15 16:18
confirmed: release branch as of before PR 7368 leads to crash when selecting an icon in live map, whereas release branch including PR 7368 works on my dev machine.
