### ISSUE TITLE
Android Auto

### ISSUE THREAD

**Issue by AlphaDeltaIndigo** [cgeo/cgeo#14518] opened 2023-08-17 12:43 UTC
### Tell us your idea!

I would like to request for cgeo to be listed on the Android Auto platform, to be able to easily navigate to a cache

### What solution would you suggest?

The CGEO app on Android Auto (AA) would be simple, is showing a Google map with an overlay of Geocaches, with only a simple filter option on map showing either found or not found(not found includes dnf) Geocaches. 
This feature would not give the user an option for writing a log. All logs must be typed on a mobile device. 
This feature would not give the user an option to change "found" status in the car.

### Is there an alternative?

No

### Additional Information

Happy to donate or create a fundraiser to assist with this feature request

**Comment by ztNFny** [comment] 2023-08-17 13:22
duplicate of #6684

**Closed by ztNFny** 2023-08-17 13:22 UTC
Labels: Feature Request, Unverified

**Comment by RoNoLo** [comment] 2025-08-25 20:38
I would like to see c:geo on my Android Car Feature. All I want is have the map with all Caches which fit on the screen and a filter for the type. Secondly a Search for a Cache or adress and a Navigate option. 

All other functions like log cache, set waypoints or what not should be prevented, because that is better on a mobile phone. But having a self updating map with caches nearby while driving sounds nice. It's not that far off from having a map where gas stations are displayed. 

Therefore I would really like that feature.
