### ISSUE TITLE
"Message user"

### ISSUE THREAD

**Issue by Technical-13** [cgeo/cgeo#6820] opened 2017-11-02 12:10 UTC
`Message` user should use the [Message Center](https://www.geocaching.com/account/messagecenter) and there could be an optional `Email` user that does what the existing message user does.

Note that if messaging from a cache, the URL should include the `?recipientId=` and `&gcCode=` parameters.  Thanks! :)

**Comment by SammysHP** [comment] 2017-11-02 17:44
Duplicate of #5352. See also #4917 and #5699.

**Closed by SammysHP** 2017-11-02 17:44 UTC
