### ISSUE TITLE
Partially unneccessary map redraw on orientation change

### ISSUE THREAD

**Issue by dl1ely** [cgeo/cgeo#4442] opened 2014-10-28 12:13 UTC
I use the freitzeitkarte offline OSM map. In any map view, when the orientation of the phone changes, all the map tiles get redrawn, even the ones in the center that did not get in or out of view. Even on my rather meaty phones (HTC One, OnePlus One) that redraw takes about 1sec. This is particularly annoying when the orientation change is unintentional due to some accidental movement of the phone.

Is there a way to keep the center part of the map on orientation change, and rerender only the parts that were out of view before the change? That would make for a much nicer user experience.

Version: 2014.10.28-NB-935444e

**Comment by Lineflyer** [comment] 2018-03-12 16:15
Closed as outdated / not updated.
Meanwhile we are about to implement mapsforge v0.9.

Please open a new issue / reopen this issue with updated information if the problem is still existing.

**Closed by Lineflyer** 2018-03-12 16:15 UTC
Labels: Feature Request, Live Map, Performance
