### ISSUE TITLE
Next bugfix or feature release

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#11767] opened 2021-10-02 16:50 UTC
### Tell us your idea!

Release 2021.09.27 is running smoothly so far, so let's start discussing on how to continue from here.

If there will be any urgent fixes coming up, we can publish a bugfix release as next version.

Otherwise we should discuss what to include in a next beta. Beside some smaller changes there are up to three larger changes in progress:
- new icon set (already on `master`), nearly ready for a beta (?)
- WIP for new variables tab - partly on `master`, but no UI part yet AFAIK
- bottom navigation

If I remember correctly, our plan was to publish the new icon set first, and then merge bottom navigation to `master` - correct?
What about the UI parts for the new variables tab. Shall we put it into the same version as bottom navigation, or may it be ready for a beta earlier?

If we have agreed on which of those larger changes to include, we can start collecting blocking issues regarding those to focus on fixing them to get ready for next beta.

**Comment by fm-sys** [comment] 2021-10-02 17:48
> If I remember correctly, our plan was to publish the new icon set first, and then merge bottom navigation to `master` - correct?

Yes, at least that was the idea in our last dev meeting. 

I've created a project to track the remaining issues related to the vector icons: 
https://github.com/cgeo/cgeo/projects/22

> What about the UI parts for the new variables tab. Shall we put it into the same version as bottom navigation, or may it be ready for a beta earlier?

I cannot speak for the variables, but at least for the bottom navigation there's nothing left to do from my side. I'm just waiting for the day, it finally gets merged :)

But in general, I think it's always better to wait until a feature is fine-tuned, instead of releasing something that works poorly...

---

BTW, we are still carrying a regression bundle with us: #11607 / #11726 / #11528

**Comment by eddiemuc** [comment] 2021-10-02 18:19
Wrt variable Tab I would suggest to merge with some kind of developer switch to turn it on/off. We can e.g. use the debug mode flag for that. As of now the feature is totally unconnected to any part of c:geo, but I would really like to get feedback from real user experience (for now targeting nightly users only though)

**Comment by Lineflyer** [comment] 2021-10-02 19:35
> BTW, we are still carrying a regression bundle with us: #11607 / #11726 / #11528

Those should really be tackled...quite some of the same reportings around time zone issues since some releases.

For the generic release topic:
I suggest to finalize the vector issues (or conclude which regressions might not be so urgent) and then go for a bit longer beta phase with the new icons.
During the time the beta is running, we can merge and fine tune the bottom navigation.

**Comment by fm-sys** [comment] 2021-10-02 21:45
> > BTW, we are still carrying a regression bundle with us: #11607 / #11726 / #11528
> 
> Those should really be tackled...quite some of the same reportings around time zone issues since some releases.

I think I have found a solution, fixing all of those issues. See #11769

**Comment by fm-sys** [comment] 2021-10-03 17:22
Many outstanding bugs are fixed now, including a fix for the timezone issues (targeted to `release`).

The only real blocker is IMHO #11591

**Comment by Lineflyer** [comment] 2021-10-06 20:18
Sounds good in general.
I will strive over the open issues one more time to doublecheck issues and we should maybe give those changes some days on nightly before launching a beta.

**Comment by ztNFny** [comment] 2021-10-08 16:44
Search on main screen is broken, see #11803 , this is a blocker for beta

**Comment by Lineflyer** [comment] 2021-10-08 18:36
See also #11804

**Comment by moving-bits** [comment] 2021-10-08 19:59
Started preparing a bugfix release:
- [x] Check/Insert correct version name
- [x] Build release on CI server
- [ ] Perform smoke test with resulting cgeo-release.apk before continuing
- [ ] Upload and publish cgeo-release.apk to Google Play
- [ ] Tag the release on Github
- [ ] Publish the release on Github including upload of cgeo-release.apk to Github
- [ ] Publish release on F-Droid
- [ ] Trigger notification to status.cgeo.org
- [ ] Post release info to Facebook
- [ ] Post release info to Twitter

**Comment by fm-sys** [comment] 2021-10-10 20:07
IMHO not a blocker for the new beta, but should definitely be tackled: #11839

**Comment by ztNFny** [comment] 2021-10-10 20:11
Due to the high visibility of the new icons I expect there'll be a lot of feedback, at least compared to normal releases (the same for bottom nav probably), did you talk about how to handle that?

**Comment by fm-sys** [comment] 2021-10-10 20:21
> 
> 
> IMHO not a blocker for the new beta, but should definitely be tackled: #11839

@moving-bits if you haven't started with the beta, you could merge #11840. It will fix the issue described in #11839.



> 
> 
> Due to the high visibility of the new icons I expect there'll be a lot of feedback, at least compared to normal releases (the same for bottom nav probably), did you talk about how to handle that?

Not explicitly. There will always be a few people saying, "everything was better before...", but users will get used to it after a few weeks I guess.

**Comment by ztNFny** [comment] 2021-10-10 20:32
No, no good idea tbh... There'll be some "everything was better in the past", but that can only be ignored imho.
We should avoid having loads of issues open. For constructive criticism maybe we can bundle it into one issue for each topic. Like if we get some more feedback on the EC icon close them as dups of that already existing issue - but of course also read what's in there and try to improve where possible, then maybe have another updated option or two ready for the next dev call and decide there.

**Comment by Lineflyer** [comment] 2021-10-10 20:35
For later on:
Once the beta is out and we have a better view on the questioned icons, we could elaborate some options and e.g. make a Facebook survey in "c:geo Fangruppe" to find the best option.

**Comment by Lineflyer** [comment] 2021-10-10 20:44
@ztNFny 
Sorry for misusing this thread:
I just tried to contact you via mail using the mail address you used when initially contacting @moving-bits on our support mail. But this somehow looke like a one-time mail address.

If you did not receive my mail, could you contact support@cgeo.org again or via the my mail address as recorded in older git commits as your time permits.

**Comment by ztNFny** [comment] 2021-10-10 21:01
I think a survey would be good to get some big picture. In issues we'll get only negative voices, but we won't know whether that's only a small subset of users or a substantial amount that have some issues. As in the end we won't be able to make 100% happy that's an important number to know.

If we have some kind of survey we need to present all the Icons to the users, also less frequently used ones like CITO, CC, Maze, ... (there's a lot of new types that I added icons for that previously didn't have their own) to get proper quality feedback - maybe by linking to the appropiate page in help? Or maybe a survey with 1 vote (how do you like it 1-5) per icon?

**Comment by moving-bits** [comment] 2021-10-11 05:59
Just a short heads-up: Starting to prepare beta version now. Still needs some fine-tuning with the changelog, will continue tonight...

- [x] Forward branch `release` to `master`
- [x] Check/Insert correct version name
- [ ] Fine-tuning for changelog display
- [ ] Build release on CI server
- [ ] Perform smoke test with resulting cgeo-release.apk before continuing
- [ ] Upload and publish cgeo-release.apk to Google Play
- [ ] Tag the release on Github
- [ ] Publish the release on Github including upload of cgeo-release.apk to Github
- [ ] Publish release on F-Droid
- [ ] Trigger notification to status.cgeo.org
- [ ] Post release info to Facebook
- [ ] Post release info to Twitter

**Comment by moving-bits** [comment] 2021-10-11 20:49
🤣

**Comment by Lineflyer** [comment] 2021-10-11 20:57
> We always have to keep in mind that the visible feedback will be mostly the negative one, users who like it won't show up here.

I answered of course and requested more detailed (constructive) feedback to our support mail.

**Comment by Lineflyer** [comment] 2021-10-19 18:19
Regarding beta update:
Once we have the new icon improvements merged (PR submitted by @ztNFny) we should IMHO update the beta version. We do also have a fixed crash on `release`, thus it might be best to release a new version asap.

@moving-bits 
The changes between beta-1 and beta-2 will go into `changelog-bugfix.md` or `changelog-base.md` or nowhere as it is no official release. We can still mention it on Play change note and on social media. Or we try it this time to test the changelog file mechanism. What do you think?

**Comment by moving-bits** [comment] 2021-10-19 20:37
@Lineflyer 
Everything up to a feature release goes into `changelog_base.md` (and the version number to `BranchDetectionHelper.java`). 
Everything after a feature release (but still on branch `release`) goes into `changelog_bugfix.md`, including the version number on releasing a bugfix.
(For further details see the workflow documented in https://github.com/cgeo/cgeo/wiki/Changelog-handling)

**Comment by Lineflyer** [comment] 2021-10-20 19:49
Changed icon set has been merged.
Shall I prepare a second beta round or is anything open to be included?

**Comment by Lineflyer** [comment] 2021-10-20 21:05
> With the way the layer drawable is built that's not really feasible.

Fine with that.
Meanwhile users can select to hide visited waypoints anyway....that's kind of very transparent then :)

**Comment by ztNFny** [comment] 2021-10-20 21:06
100% transparency 🤣

**Comment by Lineflyer** [comment] 2021-10-20 21:09
Will do the next beta tomorrow then.

**Comment by ztNFny** [comment] 2021-10-21 06:36
We have still open the issues that waypoints don't have the marker background in some places (eg https://github.com/cgeo/cgeo/issues/11777). This is a must-have for final release imho, would be nice to have it in beta first, but it seems noone is working on that right now.

**Comment by ztNFny** [comment] 2021-10-31 13:29
How do we proceed regarding with the release? There's some bugfix/minor change PRs already committed to release, some more still open (#12016 #12006 #12024).
In terms of icons there's only 2 "hot" topics: multi-icon (waypoints vs 2-boxes - PR with ">" waypoint version coming up) and EC (blue vs. other color vs. the multi-color icon) - though I have the impression that the discussion has toned down after the "wifi" icon was replaced with the current "earth".

My suggestion would be: We push the survey out, then use the call in 2 weeks to discuss the results and make a decision, then release.

I'm not aware of anything that'd call for another beta till then (but maybe I missed something from the mapsforge side?)

**Comment by Lineflyer** [comment] 2021-10-31 20:08
I would suggest another beta update (to include thew renewed multi icon) and those other fixes.
Some days afterwards we can push the survey out for users of that version. 

I will be home from vacation on Tuesday...and follow up here by then regarding the update and how to do the survey.

**Comment by Lineflyer** [comment] 2021-11-02 12:28
The above mentioned PRs #12016 #12006 and #12024 are merged already.
However IMHO #12030 needs a fix before the next (and maybe final) beta round.

**Comment by Lineflyer** [comment] 2021-11-03 20:39
Seems all planned for next beta is fixed/implemented by now.
Ready for another beta round starting tomorrow?

**Comment by Lineflyer** [comment] 2021-11-04 13:27
OK, so the plan is:
- Release a new beta tonight
- Push a notification link after next weekend (to give all beta users time to update and to have them use the upcoming version for some days in the field)

Will report back here once smoke tested / published.

**Comment by Lineflyer** [comment] 2021-11-04 20:28
Beta version 2021.11.04-RC has been smoke tested and published to beta users.

**Comment by Lineflyer** [comment] 2021-11-15 22:07
As agreed in our call, we plan a last beta round after some days of nightlies (+ fetch incoming translations).

I "played around" with filtering today and could at least not find any obvious bug or crash, so I suggest to spread it to beta users (a broader test base) as soon as possible.
If no one objects and/or finds a serious regression I will start a new beta tomorrow.

**Comment by Lineflyer** [comment] 2021-11-16 17:33
Beta version 2021.11.16-RC has been pushed to our beta testers.
Last round until (I propose) after next weekend, then we go for a release if there are no new problems.

**Comment by Lineflyer** [comment] 2021-11-21 11:22
No user reports and nothing out of the ordinary on the crash reporting on Google Play as well.
I guess we can start rolling out the next release tonight?

**Comment by eddiemuc** [comment] 2021-11-21 11:26
What about https://github.com/cgeo/cgeo/issues/12145?

**Comment by fm-sys** [comment] 2021-11-21 11:29
> What about #12145?

Is it really a newly introduced issue starting with the current beta? Otherwise, it can go into a separate bugfix release afterwards...

**Comment by eddiemuc** [comment] 2021-11-21 11:33
> > What about #12145?
> 
> Is it really a newly introduced issue starting with the current beta? Otherwise, it can go into a separate bugfix release afterwards...

It is not new, but it is kind of huge...

**Comment by Lineflyer** [comment] 2021-11-21 12:27
Shouldn't we do this in a upcoming bugfix release?
You never know what might go wrong...and I would rather avoid any additional risk and let users digest the new icons in a tested to be stable build first.

**Comment by eddiemuc** [comment] 2021-11-21 12:38
> Shouldn't we do this in a upcoming bugfix release? You never know what might go wrong...and I would rather avoid any additional risk and let users digest the new icons in a tested to be stable build first.

Ok, then go ahead. But please do not merge master to release after production release

**Comment by Lineflyer** [comment] 2021-11-21 12:39
Will release later today/tonight.

**Comment by Lineflyer** [comment] 2021-11-21 16:42
- [ ] Check/Insert correct version name as plain text in ```/main/res/raw/version_release.txt``` (Format `YYYY-MM-DD`)
_Only relevant for combined legacy/normal releases: Be aware, that Github release tags always take the newest tagged commits as latest release, independently of its branch. So if you e.g. have to tag a release for legacy and normal release, make sure to change the changelog of the normal release as last step. If you only want to release a legacy version, you seem to have no solution to keep the normal release as "latest release" on Github_
- [ ] Build release on [CI server](https://ci.cgeo.org/view/Release_Nightly/job/cgeo%20release/) (Download available after build from [here](https://download.cgeo.org/cgeo-release.apk))
- [ ] Perform smoke test with resulting ```cgeo-release.apk``` before continuing
- [ ] Upload and publish ```cgeo-release.apk``` to Google Play (Account required for the c:geo team Google Play account)
- [ ] Tag the release on Github in format `market_yyyymmdd` (can be combined with next step if done on Github UI)
- [ ] Publish the release on Github including upload of ```cgeo-release.apk``` to Github (Select Draft a new release from [here](https://github.com/cgeo/cgeo/releases), enter tag name (see above), make sure to select branch `release`, C&P change log, attach APK file, release the version)
- [ ] Publish release on F-Droid by runnning [this job](https://ci.cgeo.org/view/FDroid/job/Publish%20FDroid%20-%20RELEASE/) This required, that the release APK has been uploaded to Github in previous step
- [ ] Trigger notification to status.cgeo.org via [CI server](https://ci.cgeo.org/view/Notification%20system/job/Create%20release%20notification/) once the release is available on Google Play
- [ ] Post release info to Facebook 
- [ ] Post release info to Twitter

**Comment by Lineflyer** [comment] 2021-11-21 22:06
Update 2021.11.21 is live now.
Thanks to all contributors and special thanks to @ztNFny for his icon work.

**Closed by Lineflyer** 2021-11-21 22:06 UTC
Labels: Feedback required
