### ISSUE TITLE
Mapsforge: map rotation

### ISSUE THREAD

**Issue by devemux86** [cgeo/cgeo#15743] opened 2024-05-25 13:07 UTC
### Tell us your idea!

I started working again on **map rotation** in Mapsforge.

The basics work, now various improvements are needed:
- https://github.com/mapsforge/mapsforge/issues/7

Another feature that could be examined is:
- https://github.com/mapsforge/mapsforge/issues/75

---

I thought to inform the c:geo team as you are working with Mapsforge and VTM map libraries.

Also because of some OpenGL problems and the new native libraries issue in the next Android:

- https://github.com/mapsforge/vtm/issues/1125

---

Sample of map rotation in Mapsforge:

<img src="https://github.com/cgeo/cgeo/assets/3484020/f512219e-362a-49d1-9ead-26edd877d845" width="50%"/>

**Comment by SammysHP** [comment] 2024-05-25 15:06
Great to see some love for good old Mapsforge. :relaxed: Although I already started to like the vector rendering of VTM.

Interesting to see that the labels stay aligned to the viewport. How are they drawn? Are the tiles redrawn on rotation? When the map rotation follows the device rotation it would mean permanent redraw.

**Comment by devemux86** [comment] 2024-05-25 15:21
We use the label layer that already exists in Mapsforge for many years (see [documentation](https://github.com/mapsforge/mapsforge/blob/master/docs/LabelLayer.md)).
Note: VTM (OpenGL) also has a separate label layer.

There are samples [LabelLayerUsingLabelCacheMapViewer](https://github.com/mapsforge/mapsforge/blob/master/mapsforge-samples-android/src/main/java/org/mapsforge/samples/android/LabelLayerUsingLabelCacheMapViewer.java) and [LabelLayerUsingMapDataStoreMapViewer](https://github.com/mapsforge/mapsforge/blob/master/mapsforge-samples-android/src/main/java/org/mapsforge/samples/android/LabelLayerUsingMapDataStoreMapViewer.java).

The tiles are cached as always, the labels and symbols are rendered separately on the top.

Label layer can certainly be improved more for better performance.

**Comment by devemux86** [comment] 2024-05-29 09:34
Update: I'm currently testing the Mapsforge rotation in Cruiser navigation:

<img src="https://github.com/cgeo/cgeo/assets/3484020/d36dfcb1-c8da-469c-883a-419333013f84" width="50%"/>

**Comment by devemux86** [comment] 2024-05-29 15:58
If anyone wants to try the rotation, you can use the RotationMapViewer sample in the [rotation branch](https://github.com/mapsforge/mapsforge/tree/rotation).

There are too many changes in the entire Mapsforge code and it is still under development.

Rotation currently works via the API, a rotation gesture has commented out code in MapView.
Also the label / symbol collision detection needs more work and probably some other things.

**Comment by devemux86** [comment] 2024-06-07 08:11
After map rotation, I also implemented **fractional zoom** in Mapsforge.

It works with API `setZoom(double)` and gestures where the zoom is fluid without levels.
(the map refreshes automatically when zoom levels are passed)

Zoom|Rotation + Zoom
-|-
<video src="https://github.com/cgeo/cgeo/assets/3484020/eac0c4d9-6891-44b4-a2b7-c30394f4f20f" width="50%"/>|<video src="https://github.com/cgeo/cgeo/assets/3484020/34e155ca-f5d6-4ea3-8ec5-51381a64afef" width="50%"/>

**Comment by fm-sys** [comment] 2024-06-07 09:05
Wow, really cool. Thank you so much for your effort! 

Are both features already considered mostly stable (in terms of APIs)? If yes, I would like to test these things inside cgeo hopefully this weekend if I find time...

@cgeo/team Should we replace VTM or implement Mapsforge to Unified Map in parallel for now?

**Comment by devemux86** [comment] 2024-06-07 09:41
@fm-sys

I am already testing the rotation inside Cruiser, so it is mostly finished.

For the zoom, I still optimize some things, it should be completed soon.

They are available in branches [rotation](https://github.com/mapsforge/mapsforge/tree/rotation), see RotationMapViewer sample
and [zoom](https://github.com/mapsforge/mapsforge/tree/zoom) (contains rotation), see DiagnosticsMapViewer sample.

Rotation is more complicated with many changes, especially if custom layers are used.

**Comment by devemux86** [comment] 2024-06-07 09:51
> Should we replace VTM

My motivation was because of https://github.com/mapsforge/vtm/issues/1125 and the future of native libs on Android.
And I wanted Mapsforge to have feature parity with VTM so there is no problem in the future.

OpenGL speed is important, but let's see how map rotation can work with the regular API.

---

I also recently rewrote the Mapsforge POI API to not use external native libraries:
- https://github.com/mapsforge/mapsforge/pull/1411

**Comment by ztNFny** [comment] 2024-06-07 17:49
> @cgeo/team Should we replace VTM or implement Mapsforge to Unified Map in parallel for now? 

I'd vote for MapsForge as the third map provider (in addition to vtm and Gmaps) I'm unified map. Would also make fixing unified map bugs easier as we can then identify whether the problem is in vtm or unified.

**Comment by eddiemuc** [comment] 2024-06-07 19:23
How should the user select for an OSM map (offline or online) whether it should be displayed using VTM or Mapsforge? Should we list each OSM entry two times in the list of map sources?

**Comment by ztNFny** [comment] 2024-06-07 19:27
Unified Map is experimental, so showing maps twice would be perfectly fine imho. Users can disable sources in preferences already. Good enough - not for final release but for test version which it is.

**Comment by moving-bits** [comment] 2024-06-07 20:34
> > @cgeo/team Should we replace VTM or implement Mapsforge to Unified Map in parallel for now?
> 
> I'd vote for MapsForge as the third map provider (in addition to vtm and Gmaps) I'm unified map.

I second this, but I would add a switch to UnifiedMap configuration whether to use OpenGL or Bitmap-based version (however we name this option) to avoid having each Mapsforge map twice in the list of selectable maps. (Having four active offline maps currently + "combined" option, this would make ten entries for me otherwise, plus the Google Maps variants - way too crowded.)

**Comment by moving-bits** [comment] 2024-06-07 20:36
> After map rotation, I also implemented **fractional zoom** in Mapsforge.

That's great news, thanks @devemux86 for your efforts and for continuously improving the map libraries!

**Comment by ztNFny** [comment] 2024-06-07 20:38
> I second this, but I would add a switch to UnifiedMap configuration whether to use OpenGL or Bitmap-based version (however we name this option) to avoid having each Mapsforge map twice in the list of selectable maps.

Or a checkbox like for Hillshading (currently only in WIP PR):
![Screenshot_2024-06-07-22-37-31-97_a916ceb0c8a82619faeb76fe6b8ae997.jpg](https://github.com/cgeo/cgeo/assets/1258173/45995506-96fb-48c1-a33c-f0d50f81038d)

**Comment by fm-sys** [comment] 2024-06-07 22:55
@devemux86 

There is no abstraction layer for VTM and mapsforge out of the box, right? So tile sources and all these things need their completely own implementation for both maps... 

Out of curiosity, and as Cruiser had used VTM and mapsforge in parallel as well for quite some time: How did you managed to overcome that issue?

**Comment by devemux86** [comment] 2024-06-08 07:08
@fm-sys 

Cruiser has multiple libraries for maps, overlays, routing, navigation, poi, favorites, etc.

There is a central and common map / overlay interface used in all Cruiser libraries.
And implementations of this interface for Mapsforge and VTM (Android / Desktop).

By the way, I'm wondering if it's worth it to make Cruiser open source: :slightly_smiling_face: 
- https://github.com/devemux86/cruiser/discussions/509

**Comment by eddiemuc** [comment] 2024-06-08 08:00
> > > @cgeo/team Should we replace VTM or implement Mapsforge to Unified Map in parallel for now?
> > 
> > 
> > I'd vote for MapsForge as the third map provider (in addition to vtm and Gmaps) I'm unified map.
> 
> I second this, but I would add a switch to UnifiedMap configuration whether to use OpenGL or Bitmap-based version (however we name this option) to avoid having each Mapsforge map twice in the list of selectable maps. (Having four active offline maps currently + "combined" option, this would make ten entries for me otherwise, plus the Google Maps variants - way too crowded.)

In case we decide to do this: there is already an implementation for unified item layer availlable for Mapsforge here: `cgeo.geocaching.unifiedmap.geoitemlayer.MapsforgeV6GeoItemLayer`. Haven't touched it in a long time since we didn't use mapsforge in unifiedmap yet, so it might not be completely up-to-date. But it could well serve as a starting point for a quick integration of mapsforge into unifiedmap.

We might want to discuss this topic in this sunday's dev call?

**Comment by fm-sys** [comment] 2024-06-10 07:08
Didn't had as much time as expected this weekend. That's what I have so far, but don't have the time to continue the work in the near future...

https://github.com/fm-sys/cgeo/tree/mapsforge-in-um

**Comment by devemux86** [comment] 2024-06-10 08:52
I included all the latest work in Cruiser testing, so the Mapsforge branches should be mostly finished.
(but improvements are always made)

Fractional zoom can be enabled in `Parameters`, as I am not sure how usable it is in its current state.
It scales everything in the fractional zooms (also overlays). Performance without GPU is complicated. :slightly_smiling_face: 

---

@MotoUKRider also transfers a new Mapsforge theme: **Motorider** (light and dark).
It is still work in progress and available in [theme](https://github.com/mapsforge/mapsforge/tree/theme) branch (contains rotation & zoom).

**Comment by devemux86** [comment] 2024-06-10 14:31
For your information:

Another thing we could optimize is the bitmap scaling effect when we change the zoom level of the map.
This can be annoying as we wait the new level to be rendered while seeing the old level zooming in / out.

It may work well when we change zoom level with UI, but when traveling we often want instant changes.

I added the `Parameters.MATRIX_SCALING` that when false, the old zoom level remains rendered
and the new zoom level replaces it instantly without the scaling effect that can take some time.

**Comment by devemux86** [comment] 2024-06-30 08:25
I merged the **map rotation** in Mapsforge, please see the [changelog](https://github.com/mapsforge/mapsforge/blob/master/docs/Changelog.md) for other API changes.

[RotationMapViewer](https://github.com/mapsforge/mapsforge/blob/master/mapsforge-samples-android/src/main/java/org/mapsforge/samples/android/RotationMapViewer.java) demonstrates the new rotation API.
[OverlayMapViewer](https://github.com/mapsforge/mapsforge/blob/master/mapsforge-samples-android/src/main/java/org/mapsforge/samples/android/OverlayMapViewer.java) works with rotated overlay events.

---

Rotation gesture is still experimental and needs improvements: https://github.com/mapsforge/mapsforge/issues/1495

**Comment by moving-bits** [comment] 2024-06-30 09:16
That's fantastic news, thanks @devemux86 for your work on this.

I'll reopen this issue as a reminder for our team that we need to implement it (at least for UnifiedMap), and that we need to find a viable solution to distinguish between VTM-based OSM and Mapsforge-based OSM within UnifiedMap (displaying and selecting map sources etc.).

**Comment by devemux86** [comment] 2024-07-30 08:32
I implemented a new Mapsforge feature:
- https://github.com/mapsforge/mapsforge/issues/1507

Pre-caching can be enabled for +-zoom levels or +tile margin.
Details in the issue. Works best with the persistent tile cache.

Examples of the new API are in [MapsforgeMapViewer](https://github.com/mapsforge/mapsforge/blob/master/mapsforge-samples-android/src/main/java/org/mapsforge/samples/android/MapsforgeMapViewer.java) sample.

**Comment by devemux86** [comment] 2024-08-05 08:55
If you are interested in trying the new Mapsforge engine, it is included in:

- https://github.com/devemux86/cruiser/discussions/610

Map rotation is available in follow location mode(long press on location button) and navigation.

**Comment by fm-sys** [comment] 2024-08-11 20:30
I've just rechecked my initial WIP implementation from some weeks ago. The implementation does compile and shows a white map with overlayed map items (user location, geocaches). Nothing else supported yet, and quite some code which exists but doesn't work correctly. Maybe it's worth to throw some of these parts away and start from scratch... 

Just rebased the [WIP branch](https://github.com/fm-sys/cgeo/tree/mapsforge-in-um) onto current master.

**Comment by moving-bits** [comment] 2024-09-01 20:29
FYI: A first draft is available with PR #15984 - generally working, but some things aren't (especially: loading caches in live mode, don't yet know why, though)

**Comment by moving-bits** [comment] 2024-09-08 19:35
PR has been merged to `master`, so let's close here

**Closed by moving-bits** 2024-09-08 19:35 UTC
Labels: Prio - Medium, Map: Unified

**Comment by devemux86** [comment] 2024-09-19 09:27
I also implemented the map rotation gesture in Mapsforge (not enabled by default).
Map rotation API and gesture are more useful with the label layer.

How to use these new features (they require larger cache):
- [RotationMapViewer](https://github.com/mapsforge/mapsforge/blob/master/mapsforge-samples-android/src/main/java/org/mapsforge/samples/android/RotationMapViewer.java) (map rotation API)

- [LabelLayerUsingLabelCacheMapViewer](https://github.com/mapsforge/mapsforge/blob/master/mapsforge-samples-android/src/main/java/org/mapsforge/samples/android/LabelLayerUsingLabelCacheMapViewer.java) (rotation gesture)

---

These are also available for testing in **Cruiser 5**:

- https://github.com/devemux86/cruiser/discussions/610

**Comment by devemux86** [comment] 2024-10-10 07:54
I published [**Mapsforge 0.22.0**](https://github.com/mapsforge/mapsforge/blob/master/docs/Changelog.md#version-0220-2024-10-10).

It is available on JitPack.

**Comment by devemux86** [comment] 2024-10-10 07:58
I published [**Mapsforge 0.22.0**](https://github.com/mapsforge/mapsforge/blob/master/docs/Changelog.md#version-0220-2024-10-10) with **map rotation**.

It is available on JitPack.

**Comment by devemux86** [comment] 2025-02-22 13:11
VTM has new native libraries to resolve https://github.com/mapsforge/vtm/issues/1125.
I published a new VTM version to Maven and JitPack.

You can continue using VTM with the new version `0.23.0`.

**Comment by moving-bits** [comment] 2025-02-22 17:01
Thanks for notifying, I've created #16678 for it

**Comment by devemux86** [comment] 2025-03-01 11:35
I created new Android native libraries to fix a tesselation problem:

- https://github.com/mapsforge/vtm/issues/1125#issuecomment-2690695627

Please use the VTM `snapshot` version.
