### ISSUE TITLE
Update only caches on screen (offline caches)

### ISSUE THREAD

**Issue by vav166** [cgeo/cgeo#5333] opened 2015-12-21 11:32 UTC
Feature which I "want":
Zoom in map to some place, and have a "button" to update all offline caches which are shown on screen.

Actually I can update whole offline list at all, only. But sometimes I need to update only few caches is some area when I'll be (but caches are part of few big lists - traditional/mystery/...).

**Comment by SammysHP** [comment] 2015-12-21 13:16
Duplicate of #5137.

**Closed by SammysHP** 2015-12-21 13:16 UTC
