### ISSUE TITLE
Please update FAQ: .cgeo directory fills up my internal sdcard: How to delete not needed data?

### ISSUE THREAD

**Issue by guettli** [cgeo/cgeo#5085] opened 2015-07-13 15:14 UTC
Please update the FAQ:

The .cgeo directory fills up my internal sdcard of my android phone.

How to delete not needed data?

Thank you very much.

**Comment by guettli** [comment] 2015-07-13 15:35
I helped me like this:

Install SSHelper. Start SSH-Server on android device.

Connect to the device:

```
ssh ...
cd /storage/sdcard0/.cgeo
find GC* -name '*.jpg*' | xargs rm
```

This freed a lot of space. 
But I guess there are easier and better solutions. 
I am curious, please leave a comment if you know a better solution.

Thank you.

**Comment by SammysHP** [comment] 2015-07-13 15:45
First at all, you don't need an SSH server. You can access the external storage with any file manager available for Android.

Second, usually every cache stores images, static maps etc in that directory. Once the cache is deleted from the device, the memory is freed three days later. There were some bugs in the past, but they are fixed. If you're unsure about it, there is a option in the preferences of c:geo that can be used to check the data directory.

This is not a bug, so I'm closing it. ("lot of space" isn't a good description, too.) If you think that there's an issue with your installation of c:geo, delete all caches, delete `.cgeo`, store some caches and check the content of the directory. It should contain one directory per cache (+ some other files and directories). Afterwards you can delete the caches and start c:geo 4 days later again. Then check the contents again.

PS: The issue tracker for the FAQ is https://github.com/cgeo/cgeo.github.io/issues.

**Closed by SammysHP** 2015-07-13 15:45 UTC
