### ISSUE TITLE
Crash when opening map (Mapsforge V3)

### ISSUE THREAD

**Issue by okainov** [cgeo/cgeo#7248] opened 2019-01-22 22:51 UTC
##### Detailed steps causing the problem:
- Build the app locally in AS
- Run on device (run from AS)
- Try to open live map
- Crash NPE, getActionBar() returned null

##### Version of c:geo used:
master

##### Is the problem reproducible for you?
Yes

##### Other comments and remarks:
![image](https://user-images.githubusercontent.com/918446/51570363-26bc0380-1e9f-11e9-8142-7df7a436ee37.png)

Since it was not reproducible with nightly build, I can guess that something went wrong with the AS build after TargetSDK change.

**Comment by rsudev** [comment] 2019-01-23 21:01
What was the target sdk of your emulator?

**Comment by rsudev** [comment] 2019-01-23 21:55
I cross-checked with an emulator on API 26 - no problem there...

**Comment by okainov** [comment] 2019-01-23 22:16
@rsudev it's on my physical phone, Android 8, nothing to do with emulator, I suppose..

--- System information ---
Device: SM-A320FL (a3y17ltexc, samsung)
Android version: 8.0.0
Android build: R16NW.A320FLXXU3CRH2
c:geo version: 2019.01.22-9de530a developer build
Google Play services: enabled - 14.7.99 (040306-223214910)
Low power mode: inactive
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: rotation vector
Hide own/found: false
Map strategy: auto
HW acceleration: enabled (default state)
System language: en_AU
System date format: d/M/yy
Debug mode active: yes
System internal c:geo dir: /data/user/0/cgeo.geocaching (1014.3 MB free) internal
User storage c:geo dir: /storage/emulated/0/cgeo (994.3 MB free) external non-removable
Geocache data: /storage/emulated/0/Android/data/cgeo.geocaching/files/GeocacheData (994.3 MB free) external non-removable
Database: /data/user/0/cgeo.geocaching/databases/data (176.0 KB) on system internal storage
Fine location permission: granted
Write external storage permission: granted
Geocaching sites enabled:
   geocaching.com: Logged in (Login OK) / BASIC
   Geocaching.su
Geocaching.com date format: d. M. yyyy
Installed c:geo plugins:  none
--- End of system information ---

**Comment by okainov** [comment] 2019-01-23 22:23
@rsudev I also tried removing all .idea folder and re-creating project after fetch, but it didn't help. I was wondering, maybe there is some setting which needs to be set additionally, because if I click F4 on main project from AS, I see one of the "minimum target something" as "Google APi 23", same in build.gradle.file... not sure if it's related though..

**Comment by ithink314** [comment] 2019-01-24 13:21
I also had this crash after updating to 2019.01.24-NB... from f-droid. Going back to 2019.01.22 made it work again, except I lost logins and signature, because f-droid would not "downgrade" without uninstall first.

--- System information ---
Device: Nexus 6 (shamu, google)
Android version: 8.1.0
Android build: lineage_shamu-userdebug 8.1.0 OPM7.181205.001 487e2d20fc dev-keys
c:geo version: 2019.01.22-NB-9c4ddb6
Google Play services: enabled - 0.2.6.13280
Low power mode: inactive
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: rotation vector
Hide own/found: false
Map strategy: auto
HW acceleration: enabled (default state)
System language: en_US
System date format: M/d/yy
Debug mode active: no
System internal c:geo dir: /data/user/0/cgeo.geocaching (4.5 GB free) internal
User storage c:geo dir: /storage/emulated/0/cgeo (4.5 GB free) external non-removable
Geocache data: /storage/emulated/0/Android/data/cgeo.geocaching/files/GeocacheData (4.5 GB free) external non-removable
Database: /data/user/0/cgeo.geocaching/databases/data (541.4 MB) on system internal storage
Fine location permission: granted
Write external storage permission: granted
Geocaching sites enabled:
   geocaching.com: Not logged in (No Login information stored)
Geocaching.com date format: MM/dd/yyyy
Installed c:geo plugins:  none
--- End of system information ---

**Comment by rsudev** [comment] 2019-01-24 16:17
Regarding the crash:
Which map source do you use?
Regarding the uninstall:
This is a limitation imposed by Android, as far as I can see. You cannot downgrade from an App with the new permission handling to a version without.

**Comment by rsudev** [comment] 2019-01-24 16:26
Ok, now we have it. You are using the 'old' (V3) mapsforge map. This crashes for me as well.

**Comment by ithink314** [comment] 2019-01-24 17:21
@rsudev Yes offline v3 mapsforge maps. Recently tried v4 and v5 for michigan, and got a popup error message when trying to select it in settings.

**Comment by rsudev** [comment] 2019-01-26 07:40
@ithink314 There is a difference in using a v3 map file (which is compatible even with newer mapsforge libraries) and using the v3 mapsforge library based map implementation.
Regarding the map files, there was a bug that v4 and higher version files were not correctly detected and therefore not usable (#7071).
The library version is selected with the respective option in the c:geo map settings. I guess you have that set to version v3 as well?

**Comment by ithink314** [comment] 2019-01-27 12:37
@rsudev The "old maps version" setting was "unchecked" a couple days ago with my reinstall, but from June 2018 it was "checked" as a workaround for not displaying all my waypoints. Lars suggested the workaround by email. That problem seems better now, after trying a v5 map just now, with 2019.01.22-NB-9c4ddb6.

**Comment by mirabilos** [comment] 2019-01-27 13:51
mirabilos commented Jan 27, 2019 in #7275
Detailed steps causing the problem:

    Update from 2018.12.13 to 2019.01.27 NB
    Start the new version
    Hit “Live Map”
    Watch it FC

Actual behavior after performing these steps:

    Watch it FC

Expected behavior after performing these steps:

    Show the map

Version of c:geo used:

NB 2019.01.27
Is the problem reproducible for you?

Yes
System information:

--- System information ---
Device: HTC Desire (htc_bravo, htc_wwe)
Android version: 4.4.4
Android build: liquid_bravo-userdebug 4.4.4 KTU84Q c5fea05051 test-keys
c:geo version: 2019.01.27-NB-4ff734d
Google Play services: unavailable
Low power mode: inactive
Compass capabilities: yes
Rotation vector sensor: absent
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: magnetometer & accelerometer
Hide own/found: true
Map strategy: auto
HW acceleration: enabled (default state)
System language: en_GB
System date format: yyyy/MM/dd
Debug mode active: no
System internal c:geo dir: /data/data/cgeo.geocaching (964.0 MB free) internal
User storage c:geo dir: /storage/sdcard0/cgeo (4.4 GB free) external
Geocache data: /storage/sdcard0/Android/data/cgeo.geocaching/files/GeocacheData (4.4 GB free) external
Database: /storage/sdcard0/Android/data/cgeo.geocaching/files/databases/data (26.0 MB) on user storage
Fine location permission: granted
Write external storage permission: granted
Geocaching sites enabled:
   geocaching.com: Logged in (Login OK) / PREMIUM
   opencaching.de: Logged in (Login OK)
Geocaching.com date format: yyyy-MM-dd
Installed c:geo plugins:  none
--- End of system information ---

Other comments and remarks:

Workaround is to disable the old v3 mapsforge API. This is a bad workaround though, the new one is much less usable on my device: much slower, and it loads caches first, map second, which is bad when I need the map quickly for orientating myself (it’s easy enough to remember the rough cache location than to navigate without map tiles, plus I usually use cgeo as normal navigation/map showing äpp as well).

**Comment by Lineflyer** [comment] 2019-01-27 20:50
>  it loads caches first, map second

You are speaking about online maps, are you?
Otherwise it would be strange, that the tiles need longer time to load than the caches.

**Comment by mirabilos** [comment] 2019-01-27 21:51
Lars dixit:

>>  it loads caches first, map second
>
>You are speaking about online maps, are you?

No, offline maps (Freizeitkarte).

>Otherwise it would be strange, that the tiles need longer time to load
>than the caches.

No, they need lots of time to be rendered at 1 GHz…

(Also, Mapsforge v3 is MUCH performanter than v4 for me.)

**Comment by ithink314** [comment] 2019-01-28 08:49
@rsudev I spoke/wrote too soon. North Carolina v3 and v5 maps show saved waypoints OK (so far), but Mississippi does not. I have a test case cache with 3 waypoints; As map is changed, one of 2 waypoints is displayed. It seems almost random which one.

**Comment by ithink314** [comment] 2019-02-03 13:43
Because "A Photo Manager" photo mapping cannot use v4 or v5 mapsforge offline maps, I've gone back to using only v3 maps, with "old mapsforge v3" checked in map settings. Still getting consistent crashes when mapping caches with c:geo version 2019.02.03-NB, except using "Google Maps" (which is not really Gmaps for me).

**Comment by rsudev** [comment] 2019-02-03 21:33
You can use old v3 maps even with the new mapsforge library, avoiding the crash.

**Comment by ithink314** [comment] 2019-02-03 21:42
@rsudev Thanks. With unchecked "old mapsforge v3" it does not crash, but waypoints are messed up sometimes. Shows waypoints from caches not being displayed (better than crashing!)

**Closed** 2019-02-03 21:52 UTC
Labels: Bug, high, sdk26-regression
