### ISSUE TITLE
Bug - Error message when retrieving TB

### ISSUE THREAD

**Issue by alan666notb** [cgeo/cgeo#5428] opened 2016-01-30 14:39 UTC
Since the last update I get an error message when I retrieve a TB from a cache.
I click on the TB in the cache listing, select "Retrieve", enter the tracking code from the TB and hit send.

I always get the message "it seems your log was not posted. Please check it on the originating website."

However, the operation DOES succeed - the TB ends up in my inventory.
A friend using cgeo gets exactly the same result, so it's not just me.

I'm running 2016.01.19
I get the same result on a Sony Xperia Z3 running 5.1.1 and a Nexus 7 running 4.1.2

**Comment by SammysHP** [comment] 2016-01-30 14:52
Duplicate of #5427.

**Closed by SammysHP** 2016-01-30 14:52 UTC
