### ISSUE TITLE
Hint button missing when maps live map enabled

### ISSUE THREAD

**Issue by bekuno** [cgeo/cgeo#7634] opened 2019-05-21 06:39 UTC
##### Detailed steps causing the problem:
- have a cache with hint saved
- open map view
- Set map option to live map disabled
- open the cache preview 
 -> hint button is visible
- Set map option to live map enabled
- open the cache preview 
 -> hint button is not visible

##### Expected behavior after performing these steps:
The hint button should be visible when a hint exist in both modes
(at least for saved caches)

##### Version of c:geo used:
2019.05.20

##### Is the problem reproducible for you?
Yes

##### System information:
Android 9

**Comment by Lineflyer** [comment] 2019-05-21 20:21
I experienced something like that but not reproducible with the steps mentioned above yet. Need to try again.

However I experienced cases where the hint button was not shown but should have been (cache was saved and has hint).

**Comment by moving-bits** [comment] 2019-05-21 21:28
I played around with this in c:geo a bit: It seems to be related to "automatic reloading" and synchronizing data while in live mode.

Example:
- While not in live mode: Cache says "saved before 10 months", shows hint button
- After enabling live mode: Cache says "saved a couple of minutes ago", no hint button show - but if you click on "details" the hint itself is shown.
- If you disable live mode again, cache switches back to the first state of "saved before 10 months" and hint button shown.

So it looks like the hint information is lost in memory (while still being available in the database).

**Comment by SammysHP** [comment] 2019-05-22 04:21
A long time ago we had some kind of lazy loading of caches to improve database performance. When loading a cache you could control whether the full cache should be loaded from the database or just some fields (e.g. for lists). Not sure if it is still done this way.

**Comment by bekuno** [comment] 2019-05-22 08:11
> While not in live mode: Cache says "saved before 10 months", shows hint button
> After enabling live mode: Cache says "saved a couple of minutes ago",

This is Issue #7593

**Comment by moving-bits** [comment] 2020-10-02 20:03
Fixed with #9120 as well.

**Closed by moving-bits** 2020-10-02 20:03 UTC
Labels: Bug
