### ISSUE TITLE
api.geokretymap.org replaced by api.geokrety.org

### ISSUE THREAD

**Issue by bekuno** [cgeo/cgeo#7638] opened 2019-05-24 20:42 UTC
From @kumy in #7615 & https://github.com/GeoKretyMap/gkm-api-php/issues/13
https://api.geokretymap.org will be deprecated and replaced by https://api.geokrety.org (Fusion of GKM and GK projects)

**Comment by kumy** [comment] 2019-05-24 20:44
Isn't it a duplicate of #7615 ?

**Comment by bekuno** [comment] 2019-05-24 20:47
No, this was only for the export-details.php script.

**Closed** 2019-06-06 22:19 UTC
Labels: Connector GK
