### ISSUE TITLE
Regular map crashes

### ISSUE THREAD

**Issue by mjarmstr** [cgeo/cgeo#16453] opened 2024-12-24 21:53 UTC
### Describe your problem!

The c:geo map crashes and closes regularly.  It also sometimes becomes unresponsive.  

### How to reproduce?

Haven't been able to precisely reproduce, but most often the crash happens when switching to another app and back into c:geo.

### Actual result after these steps?

Display map in c:geo, switch apps, switch back to c:geo and see the map start to come up only to have it close and go back to the main c:geo page, or back to my launcher.  

### Expected result after these steps?

Display map in c:geo, switch apps, switch back to c:geo and see same map display.  

### Reproducible

Yes

### c:geo Version

 2024.12.17-RC

### System information

```text
## System information

c:geo version: 2024.12.17-RC

Datetime: December 21 at 9:08 AM

Device:
-------
- Device type: SM-S906U1 (g0quew, samsung)
- Available processors: 8
- Android version: 14
- Android build: UP1A.231005.007.S906U1UEU7EXK6
- Screen resolution: 1080x2131px (384x758dp)
- Pixel density: 3.09375
- System font scale: 1.1 / used scale: 1.1
- Sailfish OS detected: false
- Google Play services: enabled - 24.47.38 (190400-705893532)
- Memory:  Available:2.1 GB, Total:7.1 GB, Threshold: 390.0 MB, low:false

Sensor and location:
-------
- Low power mode: inactive
- Compass capabilities: yes
- Rotation vector sensor: present
- Orientation sensor: present
- Magnetometer & Accelerometer sensor: present
- Direction sensor used: rotation vector

Program settings:
-------
- Settings: v9, Count:224
- Set language: en
- System date format: M/d/yy
- Time zone: CST
- Debug mode active: no
- Log Settings: debug=false, minLevel=WARN, minAddCallerInfo=NONE, addCallerInfoMaxDepth=8, throwOnError=false, transactionSizes=false
- Last manual backup: Oct 30, 2023, 7:58 AM
- Last auto backup: Dec 12, 2:18 PM
- Routing mode: Car (shortest.brf / trekking.brf / car-eco.brf / (none) / (none))
- Live map mode: true
- Use unified map: true
- OSM multi-threading: false / threads: 1
- Map: Combined (Offline)
  - Id: cgeo.geocaching.unifiedmap.tileproviders.MapsforgeMultiOfflineTileProvider:null
  - Attrs: Us-Midwest: / Map data (c) OpenStreetMap contributors /  / Us-South: / Map data (c) OpenStreetMap contributors /  / Us-West: / Map data (c) OpenStreetMap contributors
  - Theme: Elevate.zip:Elements.xml

Filters:
-------
- Hide waypoints: -
- LIVE: Hunting ({"name":"Hunting","advanced":true,"inconclusive":false,"tree":{"type":"AND","children":[{"type":"NOT","children":[{"type":"AND","children":[{"type":"stored_list","config":{"values":["17","12"]}}]}]},{"type":"status","config":{"values":["owned_no","found_no","has_offline_found_log_no","exclude_disabled","exclude_archived"]}}]}})
- OFFLINE: None ({"advanced":true,"inconclusive":false})
- Additional stored filters: 11

Services:
-------
- Geocaching sites enabled:
   - geocaching.com: Logged in (Login OK) / PREMIUM
   - Geocaching.com Adventure Lab
   - opencaching.us: Logged in (Login OK)
- Geocaching.com date format: MM/dd/yyyy
- Geocaching.com website language: en-US
- Last login error on geocaching.com: Communication error //  (2024-12-20 18-31)
- Last successful login on geocaching.com: 2024-12-21 09-06
- Routing: internal / BRouter installed: false

Permissions
-------
- ACCESS_COARSE_LOCATION: granted
- ACCESS_FINE_LOCATION: granted
- READ_CONTACTS: DENIED
- WRITE_EXTERNAL_STORAGE: DENIED
- POST_NOTIFICATIONS: granted

Wherigo
-------
- playing:false, debug:false, debugFC:false
- Name: - (unknown)
- Cache context: null
- Last Error: null
- Last Played: null / null
- Visible things: LOCATION:0, ITEM:0, INVENTORY:0, TASK:0, THING:0
- Cartridge File: null
- Load Slots: 

Paths
-------
- System internal c:geo dir: /data/user/0/cgeo.geocaching (38.0 GB free) v3 internal isDir(10 entries)
- Legacy User storage c:geo dir: /data/user/0/cgeo.geocaching (38.0 GB free) v3 internal isDir(10 entries)
- Geocache data: /storage/emulated/0/Android/data/cgeo.geocaching/files/GeocacheData (38.0 GB free) v3 external non-removable isDir(2963 entries)
- Internal theme sync (is turned ON): /data/user/0/cgeo.geocaching/MapThemeData (38.0 GB free) v3 internal isDir(3 entries)
- Map render theme path: Elevate.zip:Elements.xml
- Public Folders: #13
  - BASE: content://com.android.externalstorage.documents/tree/primary:cgeo/document/primary:cgeo (av:true, files:>=21, size:>=6.4 GB, free:>=38.0 GB)
  - OFFLINE_MAPS: content://com.android.externalstorage.documents/tree/primary:cgeo/document/primary:cgeo/maps (av:true, files:>=9, size:>=6.4 GB, free:>=38.0 GB)
  - OFFLINE_MAP_THEMES: content://com.android.externalstorage.documents/tree/primary:cgeo/document/primary:cgeo/maps/_themes (av:true, files:>=2, size:>=528.6 KB, free:>=38.0 GB)
  - OFFLINE_MAP_SHADING: content://com.android.externalstorage.documents/tree/primary:cgeo/document/primary:cgeo/maps/_hgt (av:true, files:>=0, size:>=0 B, free:>=38.0 GB)
  - LOGFILES: content://com.android.externalstorage.documents/tree/primary:cgeo/document/primary:cgeo/logfiles (av:true, files:>=3, size:>=721.3 KB, free:>=38.0 GB)
  - GPX: content://com.android.externalstorage.documents/tree/primary:cgeo/document/primary:cgeo/gpx (av:true, files:>=16, size:>=185.1 MB, free:>=38.0 GB)
  - BACKUP: content://com.android.externalstorage.documents/tree/primary:cgeo/document/primary:cgeo/backup (av:true, files:>=4, size:>=261.6 MB, free:>=38.0 GB)
  - FIELD_NOTES: content://com.android.externalstorage.documents/tree/primary:cgeo/document/primary:cgeo/field-notes (av:true, files:>=0, size:>=0 B, free:>=38.0 GB)
  - SPOILER_IMAGES: content://com.android.externalstorage.documents/tree/primary:cgeo/document/primary:cgeo/GeocachePhotos (av:true, files:>=0, size:>=0 B, free:>=38.0 GB)
  - ROUTING_BASE: content://com.android.externalstorage.documents/tree/primary:cgeo/document/primary:cgeo/routing (av:true, files:>=11, size:>=58.0 MB, free:>=38.0 GB)
  - ROUTING_TILES: content://com.android.externalstorage.documents/tree/primary:cgeo/document/primary:cgeo/routing/segments4 (av:true, files:>=2, size:>=57.9 MB, free:>=38.0 GB)
  - WHERIGO: content://com.android.externalstorage.documents/tree/primary:cgeo/document/primary:cgeo/wherigo (av:true, files:>=0, size:>=0 B, free:>=38.0 GB)
  - TEST_FOLDER: file:///data/user/0/cgeo.geocaching/files/unittest (av:true, files:>=0, size:>=0 B, free:>=38.0 GB)
- PersistedDocumentUris: #2
  - PROXIMITY_NOTIFICATION_FAR: null
  - PROXIMITY_NOTIFICATION_CLOSE: null
- Persisted Uri Permissions: #1
  - content://com.android.externalstorage.documents/tree/primary:cgeo (Apr 14, 2022, 11:32 AM):RW

Database
-------
- File: /data/user/0/cgeo.geocaching/databases/data (v103, Size:127.9 MB) on system internal storage
- Data: {cg_attributes=68708, cg_caches=11682, cg_caches_lists=14351, cg_categories=0, cg_extension=72, cg_filters=11, cg_lists=55, cg_logCount=9208, cg_logImages=9301, cg_logs=209476, cg_logs_offline=3, cg_logs_offline_images=0, cg_logs_offline_trackables=1, cg_route=1, cg_search_destination_history=0, cg_spoilers=2245, cg_trackables=219, cg_trail_history=702, cg_variables=303, cg_waypoints=4768}
- Extension Data: {DBEXTENSION_DOWNGRADEABLE_DBVERSION=1, DBEXTENSION_EMOJILRU=11, DBEXTENSION_FOUNDNUM=2, DBEXTENSION_LAST_TRACKABLE_ACTION=3, DBEXTENSION_ONE_TIME_DIALOGS=7, DBEXTENSION_PENDING_DOWNLOAD=1, DBEXTENSION_POCKETQUERY_HISTORY=47}

--- End of system information ---
 
```

**Comment by SammysHP** [comment] 2024-12-24 22:07
Duplicate of #16430.

**Closed by SammysHP** 2024-12-24 22:07 UTC
Labels: Bug, Unverified
