### ISSUE TITLE
Distance info flickering on map

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#14765] opened 2023-10-26 20:53 UTC
### Describe your problem!

Reported by several users on social media and support:

The distance info on map is flickering/flashing

One user reports further detail:
- distance info tends to not shop up while standing still (but not always), and flickering while moving slowly (walking)
- distance info is visible constantly while moving fast (car)

### How to reproduce?

TBD from support tickets

### Reproducible

Unclear

### c:geo Version

2023.10.25

### Additional Information

Ticket 717381 provides a video recording. Distance info is constantly switching on an off for reason unknown yet.
Further tickets: 972832, 179403

**Comment by moving-bits** [comment] 2023-10-27 18:58
As we have not yet been able to reproduce this issue in our test environment: 
Is some of the users affected by this issue able to test a manually installed version of c:geo to check whether that version fixes this issue?

Download is available from PR #14766 and can be downloaded here: https://ci.cgeo.org/job/cgeo-CI_PR-build/6361/artifact/main/build/outputs/apk/basic/debug/cgeo-debug.apk (or see the linked PR, check in "Show all checks" section, follow the "Details" link in "default" line and install the "cgeo-debug.apk" (which is the same link as above)).

**Comment by fm-sys** [comment] 2023-10-27 19:16
Cannot reproduce either. Maybe limited to a specific android version?

**Comment by GeoPineseeker** [comment] 2023-10-28 13:25
I can produce this on Pixel3 (CalyxOS AOSP 13 with latest updates) and Pixel6 (CalyxOS AOSP 13 with latest updates), sent a support ticket for Pixel6 with details, for which the id is 103602.

**Comment by GeoPineseeker** [comment] 2023-10-28 13:48
Debug version (https://ci.cgeo.org/job/cgeo-CI_PR-build/6361/artifact/main/build/outputs/apk/basic/debug/cgeo-debug.apk) does fix the issue on pixel 3 (CalyxOS AOSP 13 with the latest updates).

**Comment by GeoPineseeker** [comment] 2023-10-28 14:14
After some further testing, it seems that if I select from the gear icon routing mode as straight line (dog bone icon) then the distance is constantly on. But then it seems that I'm unable to click the distance to make it use larger font. Also with the debug version it was flashing "walking" and "straightline" icons constantly.

**Comment by moving-bits** [comment] 2023-10-28 14:22
Thanks for your testing efforts. Do you have "Show straight distance" enabled in settings => routing / navigation?

**Comment by GeoPineseeker** [comment] 2023-10-28 14:38
I cannot find a setting "Show straight distance" anywhere under settings -> routing / navigation.

**Comment by moving-bits** [comment] 2023-10-28 14:58
you may need to enable "extended settings" on the first settings page first

(But then I guess you probably don't have the "show straight distance" setting enabled. I'm wondering why it toggles between straight and walking distance for you.)

**Comment by GeoPineseeker** [comment] 2023-10-28 15:10
You are right, with "extended settings" enabled, under settings -> routing/navigation, setting for "show straight distance appears" and it was not selected. Funny things happen when I switch "show straight distance" on that. When gear->routing->walking is selected, then the straightline distance is shown with small font constantly and walking distance flashes on/off with large font. :) When straightline routing is selected, only small distance for straight line is on, unable to tap it larger.

I was able to screencap at the moment when both were on.
![Screenshot_20231028-180342](https://github.com/cgeo/cgeo/assets/149248512/e1addb7e-9162-4669-a48c-966af797bc24)

**Comment by GeoPineseeker** [comment] 2023-10-28 15:54
With the nightly 2023.10.28-NB-417b509 it is better.

With settings -> routing / navigation -> Show straight distance->off:
-When gear->routing->straight line is selected, all seems good. Can tap for larger font.
-When gear->routing->walking is selected, straightline and walking icons are flashing/flickering, but distance is shown constantly. Can tap for larger font. Same seems to be for "biking".
-When gear->routing->off is selected, distance is shown with straight line icon, except no line to cache is shown on map.

With settings -> routing / navigation -> Show straight distance->on:
-When gear->routing->straight line is selected, straight line distance is shown constantly, can tap for larger font.
-When gear->routing->walking is selected, straight line is shown constant, with walking flickering on/off. can tap for larger, but then the straight line is shown as larger.
-When gear-routing->off is selected, distance is shown with straight line icon, except no line to cache is shown on map.

These tests were done stationary at my desk, as some others were reporting, some of the flickering seems to be related when the distance is actually changing. But for the the problematic mainline build, I was able reproduce flickering at my desk as well.

**Comment by moving-bits** [comment] 2023-10-29 07:48
@GeoPineseeker 
I've created a new build that attempts to avoid the flickering. Do you have the chance to test this?
It's https://ci.cgeo.org/job/cgeo-CI_PR-build/6390/artifact/main/build/outputs/apk/basic/debug/cgeo-debug.apk from PR #14773.

**Comment by GeoPineseeker** [comment] 2023-10-29 14:07
I have tested this debug build, and there is still some flickering. I have a video about it (800MB). I sent the link to support@cgeo.org, please find it there, id 714515. Let me know if you got it downloaded, or if you need some specific scenario tested. On my computer, VLC was able to play the video.

It seems to be related to map provider somewhat (openstreetmap.org seems to be affected) and also moving, when rebooting the phone and then quickly starting cgeo, it flickers a lot. When gps location stabilises, flickering happens less often.

**Comment by GeoPineseeker** [comment] 2023-10-29 18:15
Noticed something else. flickering seems to be related to missing brouter route data. I don't have brouter or the brouter routing data installed. After turning on the settings->routing / navigation -> Automatic download, and then changing the "walk" profile to "trekking.brf" and switching once routing from walking to cycling and back, then cgeo suggests to download the routing data and after this the actual route is shown on the map and distances are not flickering anymore. Then if the show "straight distance" is on, both are shown, with different distances.

**Comment by moving-bits** [comment] 2023-10-29 22:23
@GeoPineseeker 
Thanks for providing the video. While I still cannot reproduce the issue, even after deleting already existing routing data files, I found something else that might be interesting: In the video you can see that the values for routed and straight distance are pretty close, but not always equal. We do have an equality check, so that one may fail, and if GPS is slightly "wandering around", equality check may fail or proceed. I've update the PR to check against small diffs instead of equality. Updated APK is available here: https://ci.cgeo.org/job/cgeo-CI_PR-build/6400/artifact/main/build/outputs/apk/basic/debug/cgeo-debug.apk

**Comment by GeoPineseeker** [comment] 2023-10-30 15:12
This debug build doesn't flicker. But it does always shows only straight distance, nothing else. Doesn't matter if settings->routing/navigation->show straight distance is on or off. Doesn't matter which routing is selected from the gear menu. Icon or distance doesn't change. Routing line on the map changes though. Tapping for larger font works.

**Comment by moving-bits** [comment] 2023-10-30 15:29
Thanks for cross-checking with the latest build. I suppose, this test was done with routing tile data being available? (As without such data, the routed distance will be 0 and therefore not shown.) If so, did you choose a target which is far away enough that routed distance and straight distance are different enough? I've set the minimum difference to 15m (IIRC) - for smaller distances only one distance value will be shown.

**Comment by moving-bits** [comment] 2023-10-30 20:44
Hm, it should work with and without routing data being installed, with and without "show straight distance" being set.

The only thing I can still imagine is some race condition, getting updates in parallel (and therefore updating the views in parallel), but even then some difference in data needs to be involved to create different viewing conditions. Strange.

I can give it a last shot with an "in update" marker, but if that doesn't help either, next step would be to revert the change.

I'll post here when a new build is available.

**Comment by moving-bits** [comment] 2023-10-30 21:50
@GeoPineseeker 
May I ask you for a (hopefully) last test with the new build (as time permits): https://ci.cgeo.org/job/cgeo-CI_PR-build/6424/artifact/main/build/outputs/apk/basic/debug/cgeo-debug.apk, ideally with both routing data available and not available. Thanks.

I've fixed a stupid logic error introduced in the last build, which prevented showing both straight and routed distance views at the same time if they had different values. If that build works for you in both settings, I would give it in the nightly versions, otherwise I could create a version with locking support.

**Comment by moving-bits** [comment] 2023-10-31 17:42
Thanks, @GeoPineseeker, for your extensive testing - very helpful especially in this case, where we were not able to reproduce the error in one of our environments. 

I've just merged the fix to `release` to get it into the nightly versions, and will prepare a bugfix release tomorrow evening (if there are no objections from the team).

> Out of the box (without routing data) only straight line distance is shown, changing routing from the gear icon does nothing (except "recalculating route in background" notfication briefly), still straight line route is shown, with straight line distance and icon.

This is expected behavior, as without routing data c:geo cannot calculate a routed distance (and returns straight distance instead). And if there's no difference between straight distance and routed distance, only one of the values will be shown.

> I think the default option of the automatic routing data download should be changed to on or adding a suggestion to turning it on manually after selecting some other routing mode than straight line. Other option would be to do the functionality of "Check for missing routing data" when other than straight line routing mode is selected. Otherwise bugreports will keep coming.

It's actually been like this for quite some time already, without bug reports poring in, but changing the default could be discussed anyway. It will only help with new installations, though, as existing users have a value for this setting stored already (which would not be overruled by a new default). And it will only help when using the built-in routing, not when using external BRouter app (which was the only option until not that long ago).

**Comment by fm-sys** [comment] 2023-10-31 18:25
> It will only help with new installations, though, as existing users have a value for this setting stored already (which would not be overruled by a new default). 

It would be for all users who never changed this setting, as it only gets stored after using it once.

**Comment by moving-bits** [comment] 2023-11-04 13:23
should be resolved with release 2023.11.01, otherwise feel free to reopen

**Closed by moving-bits** 2023-11-04 13:23 UTC
Labels: Bug, Unverified, Regression
