### ISSUE TITLE
Reload deletes coorected coords

### ISSUE THREAD

**Issue by nagisml** [cgeo/cgeo#5123] opened 2015-08-05 16:35 UTC
When I change the coordinates of a cache and choose to change it only locally a refresh of the cache erases that correction.
This is for me not expected as I had chosen to keep that change locally.
The waypoint itself which was created during that change is not removed and stays.

Simular issue:
If I import a cache with corrected coords from GSAK there is no additional wp created so after a refresh the corrected information is gone and not seen anymore within cgeo

**Comment by Lineflyer** [comment] 2015-08-09 21:25
Can you be more prcise about your expectation.
You selected to do those tasks only locally...afterwards you fetch data from remote...So it is by design, that remote (=server which made have newer information) will be the master for any data.

**Comment by nagisml** [comment] 2015-08-22 15:41
I would understand your argument (server wins over local changes) when I would change e.g. the description of a cache and after that do a reload. But if I add additional information, which is a wp and corrected coords from my point of view, I did not expect to lose that information when refreshing the cache.
Example case which happened during my holidays. I started a multi cache and corrected the coords to the next station. But was not able to finish the cache. During night I had internet connection again and refreshed my caches to download new caches and new logs. During that I lost the wp and corrected coords of the multi above.
So from my point of view wp’s and corrected coords are local changes done by the user which should persist a server refresh.

**Comment by Lineflyer** [comment] 2016-01-03 21:10
@nagisml Can you please reconfirm, that you did not only losse the modified final but that the whole personally created WP was lost while refreshing? That should not happen.

**Comment by pstorch** [comment] 2017-01-30 08:33
While working on the waypoints I also retested this one. I can reproduce the replacement of the locally changed header coords on refresh, but can't reproduce the loss of the waypoint. The issue owner hasn't confirmed it either.
Let's close this one as it is a duplicate of #5476.

**Closed by pstorch** 2017-01-30 08:33 UTC
Labels: Feedback
