### ISSUE TITLE
Map resets to GoogleMap after version upgrade

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#9465] opened 2020-11-30 11:01 UTC
From the last nightly update installations I have the impression, that after each upgrade the app comes up with Google Maps as active map although previously another map type was selected.

Need to explicitly test this though...but maybe someone can confirm already?

**Comment by MagpieFourtyTwo** [comment] 2020-11-30 14:33
There seem to be even  more problems with map display - but I was not able to get a deterministic scenario, yet.
What happens to me now and then:
- although ``Combined (offline)`` is chosen, GM is displayed (is GM a fallback for any case?)
- after opening live map (IIRC from c:geo's main page) no map is displayed at all
- after switching from GSat to ``Combined (offline)`` (via ``Map view`` button) GM will be shown
- now and then a crash while being in a map ... which I do not even count anymore. ;)

Anybody else ...?

**Comment by Lineflyer** [comment] 2020-11-30 14:40
> although Combined (offline) is chosen, GM is displayed (is GM a fallback for any case?)

Never happened to me during usage. Might be however the same scenario after upgrade?

> after opening live map (IIRC from c:geo's main page) no map is displayed at all

Never happened to me, maybe it was a debug build without GM key or your SD card (in case of offline map stored there) was not accessible

> after switching from GSat to Combined (offline) (via Map view button) GM will be shown

Also never happened to me. Maybe also due to unavailability of the offline maps?

> now and then a crash while being in a map ... which I do not even count anymore. ;)

Feel free to save logfiles after crash happened to see whether its a known error (there are some listed here) or something new.

**Comment by MagpieFourtyTwo** [comment] 2020-11-30 14:57
By accident I got a reproducible scenario for at least one of the described cases right now!   ;)

1. open map with ``Combined (offline)``
2. open any cache popup
3. display this cache on map (by clicking the compass rose)
4. switch map to Google Maps
5. use Android's Return button twice, to first go back to the cache popup, then to the Live Map (where we came from)
6. Caches are displayed, but no map at all.

In step 3 you may even change to ``Details`` first, makes no difference.

**Comment by MagpieFourtyTwo** [comment] 2020-11-30 14:59
Addition:
7. check selection in ``Map view`` list - it shows the map you've selected in step 4.

**Comment by eddiemuc** [comment] 2020-11-30 16:49
Multiple findings on this:
* I indeed introduced a bug in yesterdays nightly where pref_masource attribute is sometimes parsed wrongly (it is now a string instead of a number but got parsed as int at some place). Sorry for that, this is fixed with PR #9469 
* The sequence of steps written by @MagpieFourtyTwo indeed produce the described error. Alas, it is doing so also on my device where current release of c:geo is installed. It is a bug nevertheless of course.
* The initial issue (map resets to Google Map) is true, but it should be a one-time-reset only. This happens because I changed the format of storing mapsource from string-parsed hashcode ints to strings. I do not see an easy way to prevent this without carrying around lots of legacy code.

**Comment by MagpieFourtyTwo** [comment] 2020-11-30 21:10
Although a bug has been found, these are "bad news",
as I again have no deterministic scenario for my various map peculiarities ...  :/

;)

**Comment by moving-bits** [comment] 2020-12-06 12:36
> The initial issue (map resets to Google Map) is true, but it should be a one-time-reset only. This happens because I changed the format of storing mapsource from string-parsed hashcode ints to strings. I do not see an easy way to prevent this without carrying around lots of legacy code.

If that's a thing that will happen to all users using OSM maps - shouldn't we add a one time message for it (ideally limited to users of OSM)? Otherwise it might be pretty confusing for most users.

**Comment by eddiemuc** [comment] 2020-12-06 17:18
> If that's a thing that will happen to all users using OSM maps - shouldn't we add a one time message for it (ideally limited to users of OSM)? Otherwise it might be pretty confusing for most users.

Happens to all users not using the first entry of the MapSource list which is google standard map (this means this also happens for users of google satellite view).

I am undecided whether it's a good idea to warn users about this. Such a message would draw their attention to something they might not even notice otherwise.
For example the same thing should have occurred to all users already in last release and I only noticed one side notice from @Lineflyer about it. Or was there complaining towards support?

**Comment by MagpieFourtyTwo** [comment] 2020-12-06 17:20
IMO, if a program changes an expected value to some default, it should always inform the user,

First, to avoid confusion and second, to give a feeling of security. A user feels way better when he knows that the program has everything under control and that the behavior he just experienced was an expected one.

Thus, if c:geo defaults to GM on purpose, e. g. cause the previously stored or currently demanded value could not be found anmore, there should indeed be a message, perhaps s/th like "Due to changes in internal map management, map selection was set to Google Maps. This should occur just once." or alike ...?

**Comment by moving-bits** [comment] 2020-12-06 17:40
I agree with @MagpieFourtyTwo, at least for relevant settings (which the selected map type is, IMHO). Experienced users will be a bit irritated on that sudden map change, but change the type back and continue. Not so experienced users might not notice at first (but probably will be wondering about mobile traffic numbers), and/or might not know how to change it back. Additionally in both cases trust in c:geo will decrease a bit due to that surprising map type change.

**Comment by MagpieFourtyTwo** [comment] 2020-12-06 18:49
> trust in c:geo will decrease a bit 

And esp. this is a factor, one can not estimate high enough.
Although c:geo is in a pretty comfortable situation, as it's virtually unrivalled, IMHO. ;)

**Comment by Lineflyer** [comment] 2020-12-07 17:51
>For example the same thing should have occurred to all users already in last release and I only noticed one side notice from @Lineflyer about it. Or was there complaining towards support?

Only one complaint on support which made me aware of this topic after all and I created such issue.

I did not follow the whole discussion here (which also went a bit offtopic):
What is the "final" status? Was this a one time experience due to code change in current release and won't happen again in future version upgrades? In this case we can IMHO disregard this issue.  But If it is a permanent issue we should handle it / avoid it.

**Comment by moving-bits** [comment] 2020-12-07 20:20
Ok, if it's only a single response on support so far then we might go with a short notice in release notes instead of a one time message.

**Comment by moving-bits** [comment] 2020-12-08 19:53
note added / closing this issue

**Closed by moving-bits** 2020-12-08 19:53 UTC
Labels: Bug, Unverified

**Comment by MagpieFourtyTwo** [comment] 2020-12-09 00:12
Well phrased, BTW.
