### ISSUE TITLE
Missing Favorite Quote and Log-Counter

### ISSUE THREAD

**Issue by wolverine007** [cgeo/cgeo#12682] opened 2022-02-05 19:13 UTC
While flipping through some newly stored caches I recognized that the following is missing:

- Favorite Quote next to given favorites
- Log counter on top of the logbook page

For already stored caches the log counter is still stated but not updating when you do a refresh of the stored cache.
For newly saved caches it is completely missing:
![IMG_20220205_201146.jpg](https://user-images.githubusercontent.com/4508228/152655546-a24d23cb-6be6-4327-ad49-cc056335b421.jpg)

![IMG_20220205_201202.jpg](https://user-images.githubusercontent.com/4508228/152655548-c59ebdfc-1d0e-41e4-a789-1276f417ede3.jpg)

Maybe also related to the other website changes which are causing the log issue with an attached image?

Cheers
Wolv

**Comment by Lineflyer** [comment] 2022-02-05 19:58
Duplicate of #12667 and #12676

**Closed by Lineflyer** 2022-02-05 19:58 UTC
