### ISSUE TITLE
Routing menu vanishes on changing map file on new mapsforge map

### ISSUE THREAD

**Issue by rsudev** [cgeo/cgeo#7118] opened 2018-08-15 12:48 UTC
Opening the map (with the new mapsforge map being selected as default, on a list in this case), the routing menu is available (given the necessary preconditions).
After switching to a different map file, the menu is gone.

**Comment by Lineflyer** [comment] 2018-08-15 13:12
Duplicate of #6281 ?

**Comment by rsudev** [comment] 2018-08-26 07:58
@Lineflyer Very likely, but a different sequence of actions.

**Closed** 2018-08-27 05:05 UTC
