### ISSUE TITLE
Pretty-print exported GPX

### ISSUE THREAD

**Issue by baiti** [cgeo/cgeo#9233] opened 2020-10-20 11:56 UTC
**Describe the bug:**
Exported GPX files are completely unformated and thus they are virtually unreadable. Please format these files with proper XML syntax driven newlines and indentation

**To Reproduce:**
1. Load a geocache
2. In the top right "three dots pull down", select "Export", then "GX"
3. Download the file to a system and open the file with a text editor, then you will see the mess

**Actual behavior/state after performing these steps:**
I'd be looking at text that is unparseable for the human eye and brain

**Expected behavior/state after performing these steps:**
Properly formatted XML

**Version of c:geo used:**
2020.10.10

**Is the problem reproducible:**
Yes

**Comment by SammysHP** [comment] 2020-10-20 18:24
I see absolutely no reason to do this. As long as it's valid XML it would only introduce more complexity that is not required for proper parsing. If you want fancy eye candy, use a proper XML editor with XML visualization and navigation features.

> I'd be looking at text that is unparseable for the human eye and brain

Then stop looking at it without proper tools or use it as intended.

I'm closing this issue, but feel free to ask if you need help using XML files.

**Comment by baiti** [comment] 2020-10-20 19:04
After this very polite reasoning, I'm pretty sure I won't ever ask for anything that might lead to such an answer.

Thanks much for your time.

**Comment by SammysHP** [comment] 2020-10-20 19:28
Sorry if I sounded rude to you, that wasn't my intention. It's just that we have so many open issues that are actually visible to the user that it's not worth adding a feature that (almost) nobody will notice and that doesn't fix an issue.

XML is not meant to be read by humans in its raw format. Such eye candy is better applied at editor/tool level. For doing this in c:geo we would need another library, another dependency and it would still be only hardly readable without additional syntax highlighting. Not to mention the case of several hundred caches in one file.

That's why it makes no sense to implement it in c:geo. GPX/XML is a computer readable exchange format. Let's keep it simple.

**Comment by fm-sys** [comment] 2020-10-20 19:29
> it would only introduce more complexity that is not required for proper parsing

Of course this change would not make any feature of c:geo better for normal users, but it doesn't hurt either. Every xml parser should be able to read that files, even if there are whitespaces or new lines in it. And for proper XML syntax there are enough libraries we could use...

**Comment by SammysHP** [comment] 2020-10-20 19:34
> And for proper XML syntax there are enough libraries we could use...

But do we really want to add another dependency? Why at the provider (c:geo) and not the consumer (XML tool, IDE) that is responsible for formatting, syntax highlighting, rendering and editing by a human?

**Comment by SammysHP** [comment] 2020-10-20 19:44
Just another thought. What library do we use at the moment for generating XML? Maybe it has a flag for human friendly format or can be replaced by a different library without much work.

@baiti What issue do you want to solve with this? Why is it important for you how the GPX file is formatted? Most XML files I work with are not formatted nicely and it never bothered me.

**Comment by baiti** [comment] 2020-10-20 20:18
I wanted to programmatically process user notes attached to user created waypoints. I didn't know at that time that there is now a function in cgeo that dumps the information from user created waypoints into the personal cache note field.  So for the time being, I get to the information I need.

I am certainly ok with the closing of this issue. I also understand there is bigger fish to fry.  Coming from Node-JS it is an intrinsic capability of the JSON.stringify() to do "pretty printing". I had somehow assumed it would be as simple as that in Java too.

BTW: The tools I use all generate or export properly formatted XML in their GPX:

geocaching.com
GSAK
Locus Map
gpsbabel
XCtrails

AFAIR it was one of the design goals for XML that it is human readable. Otherwise we send bloated ASCII strings anyway?

**Comment by eddiemuc** [comment] 2020-10-20 20:59
I looked it up and it was a one-liner to enable pretty-printing on the xml export. So I just did it (PR #9238).
Strange XML-Export class we are using btw. Its name is `cgeo.org.kxml2.io.KXmlSerializer` and it seems to be some source file copied somewhere a long time ago?

**Comment by eddiemuc** [comment] 2020-10-20 21:00
> There are so many important issues like proper map attribution or tile caching (not long and c:geo will be blocked by OpenStreetMap). 

@baiti I was not aware of such critical issues pending for c:geo. Are there any issues for these things, can you give me a short pointer to them?

**Comment by baiti** [comment] 2020-10-20 21:11
> > There are so many important issues like proper map attribution or tile caching (not long and c:geo will be blocked by OpenStreetMap).
> 
> @baiti I was not aware of such critical issues pending for c:geo. Are there any issues for these things, can you give me a short pointer to them?

Hi Eddie ... that wasn't me you're quoting from. I am not aware of any critical issues pending.

**Comment by Lineflyer** [comment] 2020-10-20 21:21
The attribution issue is #6150

**Comment by Lineflyer** [comment] 2020-10-20 21:21
Reopening as there is a PR pending for this.

**Comment by bekuno** [comment] 2020-10-20 21:23
> Strange XML-Export class we are using btw. Its name is `cgeo.org.kxml2.io.KXmlSerializer` and it seems to be some source file copied somewhere a long time ago?

Here you are :-)
Cite: `Added XML serializer from andorid sources ` in https://github.com/cgeo/cgeo/commit/54636f563159512b6d6ad3f0e5b2997e8c01036d

**Comment by bekuno** [comment] 2020-10-20 22:00
By the way, this code is no more (or on another position?) in the android source.
The library is developed here:
https://github.com/stefanhaustein/kxml2

We should import direkt from there instead use a copy as thirdparty component.

**Comment by eddiemuc** [comment] 2020-10-21 05:42
> Hi Eddie ... that wasn't me you're quoting from. I am not aware of any critical issues pending.

Whoops, sorry, my mistake

**Closed** 2020-10-22 07:43 UTC
Labels: Feature Request
