### ISSUE TITLE
Waypoint type changes  if personal note is involved

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#9266] opened 2020-10-23 21:17 UTC
Just had this problem (not tested if reroducible or the dependencies):
2020.10.23-NB on Android 11

- Open GC236A2
- Swipe to waypoint tab
- Add wayppoint with coordinates and Save (Default type: Referencepoint)
- Swipe to cache details
- Select to copy waypoint to personal note
- Swipe to waypoint tab
- Click on waypoint created before to edit it

Result:
- Waypoint type changes to Parking

**Comment by MagpieFourtyTwo** [comment] 2020-10-23 22:53
> Swipe to cache details

I guess, you meant ``Description`` page? Or is there a possibility to save WPs to PN in ``Details`` page, too?
Anyway - using the PN button ``Add/update waypoints`` the scenario described above works correctly for me.

Only way to force the ``Reference Point`` to be changed to a ``Parking Area`` is to initially rename the ``Reference Point`` to "Reference Point (P)". After saving to PN we now get ...
```
{c:geo-start}
@Reference Point (P) (W) N50 06.692 E8 40.896
{c:geo-end}
```
... which will indeed change the waypoint type - but this is most probably not, what you did.  :)
Nevertheless, seems as if the parsing function should at least better look for the rightmost bracketed letter.
Or may use the well defined coord as starting point and take the stuff left of it ... or quote brackets when saving ...

**Comment by eddiemuc** [comment] 2020-10-24 06:46
There is some legacy logic in c:geo which tries to guess the waypoint type by checking words before the coordinate in PN. I left this legacy logic so we don't have regression. For example, when the word "parking" is close to the coordinate on left side (e.g. in waypoint name), type will be set to parking.

@Lineflyer can you give me the name of the waypoint and the complete pN after copying waypoints to it? (If necessary, x-out critical information)

**Comment by eddiemuc** [comment] 2020-10-24 06:50
> > Swipe to cache details
> 
> I guess, you meant ``Description`` page? Or is there a possibility to save WPs to PN in ``Details`` page, too?
> Anyway - using the PN button ``Add/update waypoints`` the scenario described above works correctly for me.
> 
> Only way to force the ``Reference Point`` to be changed to a ``Parking Area`` is to initially rename the ``Reference Point`` to "Reference Point (P)". After saving to PN we now get ...
> ```
> {c:geo-start}
> @Reference Point (P) (W) N50 06.692 E8 40.896
> {c:geo-end}
> ```
> ... which will indeed change the waypoint type - but this is most probably not, what you did.  :)
> Nevertheless, seems as if the parsing function should at least better look for the rightmost bracketed letter.
> Or may use the well defined coord as starting point and take the stuff left of it ... or quote brackets when saving ...

Never thought of users doing these kind of waypoint namings  :-) if this leads to "Parking" instead of "reference point" I would consider this a bug. As you said: only the bracket es waypoint type directly before coord should be considered

**Comment by geocachermgo** [comment] 2020-10-24 14:38
I could reproduce:
Create waypoint, cache coord, manually changed, store, double swipe right, symbol "marker with circle arrows", double swipe left, click on waypoint.
The waypoint in the note is
 `{c:geo-start}
@Referenzpunkt 1 (W) N50 06.700 E8 40.900
{c:geo-end}
`
In the Edit window "Parking" is shown

**Comment by geocachermgo** [comment] 2020-10-24 14:42
![IMG_20201024_164055](https://user-images.githubusercontent.com/43813636/97084493-b9ab4400-1617-11eb-8a23-dc50de92dae2.jpg)
When I store the wp it gets a green hook additionally.

**Comment by eddiemuc** [comment] 2020-10-24 17:34
Thanks for the good testing! Was a tough one. Confirmed and fixed with PR #9272. See there also if you want a more detailled explanation what happened here behind the scenes:
@geocachermgo the aspect with the green hookI could not reproduce. AFAIK this hook gets added to wp's marked as "visited". Did you maybe accidentally set that flag during your test?

**Comment by geocachermgo** [comment] 2020-10-25 08:14
> @geocachermgo the aspect with the green hookI could not reproduce. AFAIK this hook gets added to wp's marked as "visited". Did you maybe accidentally set that flag during your test?

Probably yes. I tried it once more: no green hook. Additionally: The "visited" point in the menu is right below "edit" and I have full grown thumbs.

**Closed** 2020-10-26 18:39 UTC
Labels: Bug, Regression

**Comment by geocachermgo** [comment] 2020-10-27 06:31
Tested ok with 2020.10.27-NB-dfe6fb8
