### ISSUE TITLE
"Clear offline logs" does not remove indicator bar

### ISSUE THREAD

**Issue by MagpieFourtyTwo** [cgeo/cgeo#9152] opened 2020-10-05 23:31 UTC
**Describe the bug:**
When being in a list, caches with offline logs have a colored indicator bar.
This bar should disappear as soon as the offline log is deleted - but when using Menu => ``Manage caches`` => ``Clear offline logs``, the bar will stay until you either open and close the listing or display the list on map and return to the list.

BTW: May be this happens in ``Select mode`` only (just got aware that I have not tested it without ``Select mode``).

**Version of c:geo used:**
2020.10.05-NB-c129c9e

**Is the problem reproducible:**
Yes

**Comment by fm-sys** [comment] 2020-10-07 16:38
I can verify this, the same also happens without `Select mode`

**Comment by murggel** [comment] 2020-11-03 23:35
Duplicate of #9222 ? Fixed with #9252 ?

**Comment by Lineflyer** [comment] 2020-11-04 07:57
Yes, very likely. Thanks @murggel

**Closed by Lineflyer** 2020-11-04 07:57 UTC
Labels: Bug
