### ISSUE TITLE
Unable to upload offline logs

### ISSUE THREAD

**Issue by wizard4u** [cgeo/cgeo#6569] opened 2017-05-18 08:43 UTC
##### Detailed steps causing the problem:
- cgeo unable to download the data to log
- ...

##### Actual behavior after performing these steps:
 not able to upload offline logs

##### Is the problem reproducible for you?
Yes/No

##### System information:
```
Attach system information here if available (see c:geo menu -> About c:geo -> Swipe right to System)
Keep the apostrophe at beginning and end to have it properly formatted
```

##### Other comments and remarks:
e.g. Reference to other issues, projects, sources, etc.

**Comment by SammysHP** [comment] 2017-05-18 08:48
Duplicate of #6519.

PS: For future bug reports please fill in the template.

**Closed by SammysHP** 2017-05-18 08:48 UTC
