### ISSUE TITLE
Speed up filtering lists for caches not yet found

### ISSUE THREAD

**Issue by MagpieFourtyTwo** [cgeo/cgeo#9015] opened 2020-09-18 13:04 UTC
**Is your feature request related to a problem?**
When being on the road I most of time would like to see only caches which are saved offline (for a good reason), but are not yet found (as I save found caches, too, to have them handy if s/one needs a TJ - and perhaps this saves online time, too ...?).

As the map still lacks the feature to filter in any way (see e. g. #7278 and #3346), I use list "All caches" and filter it for "Status" => "Not Found". This kind of works - at least most of the times (unless some crashes because of timeout), but it's annooooyingly slow ...

**Describe the solution you'd like**
Result of filter should appear in reasonable time (i. e. less than 1 sec., which is a [widely used quasi standard in GUI development](https://www.nngroup.com/articles/response-times-3-important-limits/)).

**Additional context**
An index á la ``CREATE INDEX in_caches_found ON cg_caches(geocode,found)`` may already solve the problem ...?

**Comment by eddiemuc** [comment] 2020-09-18 14:52
I see you begin to like the idea of INDEXES speeding up processing :-)
In this case, this might be not so easy though.  I checked the code, and unfortunately it seems to me that c:geo first loads all cache data for the whole list into memory and then applies filtering programmatically (someone please correct me if I misinterpret the code here...)

To further harden (or weaken) my assumption:
* Which part is the slow one? The loading of the "all" list or the filtering for "status" thereafter (or both)?
* Could you try to send me a logcat file with verbose settings on (like for the other issue using the log-properties.txt)? PLease do this after a fresh start of c:geo (so no caches are loaded from db to memory before). I write "try" because it might be that turning on this log level when loading the "all" list will create too many and long messages for logcat to handle.

**Comment by MagpieFourtyTwo** [comment] 2020-09-18 20:41
> I see you begin to like the idea of INDEXES speeding up processing :-)

Not really. Know about the advantages of indexes for nearly 30 years now ...  ;)
And when I first got in touch with them, they were even more important, as we had to cope with 33 M(!)Hz CPUs and 2 to 4 M(!)B of RAM. Although more would have been possible with i386, but was not really affordable. Moreover there were no such nice things like SQLite, but only plain Oracle (and a bit DB2) these days. Nevertheless, we managed storehouses with thousands of storage places and controlled dozens of pickers, packers and drivers, already using wireless mobile scanners to transfer and control progress of the orders given by our system ... and all this with hardware and cpu power, that is surpassed by any digital wrist watch nowadays. Yeah, these were the days ...! ;)

But, back to topic: 
- slow(er) part is most definitely the filtering, as showing "all" is done in about 3 secs, but applying the filter takes up to 8 to 9 secs. And even deleting the filter takes about 4 secs.
- logcat ... tried to, but most regretfully, we seem to have the same scenario as with the previous issue: the really interesting stuff seems to be missing. Thus I added even three logcats, as I have the impression, the [first one](https://github.com/cgeo/cgeo/files/5247907/logcat_2020-09-18_21-07.txt) seems to contain a bit more info than the [second](https://github.com/cgeo/cgeo/files/5247911/logcat_2020-09-18_21-12.txt) or the [third](https://github.com/cgeo/cgeo/files/5247913/logcat_2020-09-18_21-24.txt). Disadvantage of the first: This was just for testing the sequence and although I already had the same sequence as with the other two, I have not written it down as exact as with the third one. Same for the second, although this was following *nearly* the same time intervals as the third.

Ok, time schedule of third logcat:
- 21:23:00 c:geo start
- 21:23:15 tap "All caches" in previously opened list of lists (opened by longclick on [Stored] in main screen)
- 21:23:30 tap "Not found" of previously opened list of "Filter" => "Status"
- 21:23:45 tap trash bin in previously opened list of "Filters"
- 21:24:00 go back to "Settings" => "Save logfile" => [Extended]

And, as usual: Feel free to ask for more.  ;)

P.S.: Funfact: If the filter is already set to "Status" => "Not found", i. e. previously set it in a different list and you switch to "All caches" *afterwards*, the list will be shown after 6 secs, thus about 3 secs faster as if you first open the All caches list and *then* apply the filter.

PP.S.: If the filtering is really done in code, why does it take *that* long?!

**Comment by MagpieFourtyTwo** [comment] 2020-09-18 23:31
Hmm ... played a little bit more with this "\<All caches\> filtered by 'Not Found'" scenario ... and it seems, the longer you work with it, the more sluggish it gets. Sometimes even the ``c:geo isn't responding - close - wait`` message appears ... looks a little bit like a memory leak ... but when you put the phone aside for a few minutes, it suddenly works fluent again ... strange.

Right after that I thought it would possibly a good idea to just save the result of "\<All caches\> filtered by 'Not Found'" into a new list ... but in fact this seemed to make things even worse: Now on every single action I get the App Hang message.  :/

And after writing this sentence, it works fluent again ... what's going on there?!?

**Comment by MagpieFourtyTwo** [comment] 2020-09-18 23:36
Hmm, hmmm, hmmmm ... the bad performance of displaying the "\<All caches\> filtered by 'Not Found'" result is obviously *not* a problem of the filter, cause as written before, I have saved the result to a new list ... and now opening this list takes even longer than the filtering.  :/

Hard to believe, it's the sheer amount of caches, as displaying \<All caches\> is way faster ...

**Comment by eddiemuc** [comment] 2020-09-19 07:00
@MagpieFourtyTwo thanks for the testing work! There's something I don't understand about how the logcat "chooses" its entries. While it seems that for the current day (which is of most interest to me) the log is "cut away" and only a certain part (maybe last 200 lines) are displayed, it contains stuff "useless" for current investigation from 13.9. ("crash"). @moving-bits you seem to have worked on this in the past. Is there any way to instruct logcat simply to get the last e.g. half-an-hour-or-so of logs (c:geo plus system) regardless of the amount and put that into the logfile created by c:geo?

With regards to how this whole thing works, I have to be more precise than I was before:
When you select a list:
* A query is issued to get all geocodes in this list. It is something like `select geocode from cg_caches where geocode in (select geocode from cg_caches_lists where list_id = 5)` (5 being the real list id). This operation is currently not logged, but the query seems to have good indexes. @MagpieFourtyTwo  just to be sure: do you use "global cache type filtering" (the filter on the start screen)? Because in this case the query would slightly different `select geocode from cg_caches where type = <sometype> and geocode in (select geocode from cg_caches_lists where list_id = 5)`. 
* For each geocode returned by this list, the cache data is loaded. In this case those were 14754 caches, and the db load took 1789ms. Query is something like `select * from cg_caches c left outer join cg_logs_offline l on c.geocode = l.geocode where c.geocode in (<long list of geocodes from query before)`. I have not profiled this one, but the most obvious indexes (on geocode) are there in both tables and it would seem fair to me if loading of that much data takes some time

When you filter that list then it SEEMS to me that all the stuff is happening only in memory on the preloaded caches. I haven't dived into the cache caching deeply though, maybe at some points the cache overflows and single caches have to be reloaded on filtering or something like that...

@MagpieFourtyTwo I am currently not able to work too much on c:geo and also am in the middle of implementing #8897. If no one solved this issue in the meantime I promise you I will dig deeper into this (and yes, I may ask you again for testing and logging if I do :-)). I hope that's ok.

**Comment by eddiemuc** [comment] 2020-09-19 07:02
> > I see you begin to like the idea of INDEXES speeding up processing :-)
> 
> And when I first got in touch with them, they were even more important, as we had to cope with 33 M(!)Hz CPUs and 2 to 4 M(!)B of RAM. Although more would have been possible with i386, but was not really affordable. Moreover there were no such nice things like SQLite, but only plain Oracle (and a bit DB2) these days. Nevertheless, we managed storehouses with thousands of storage places and controlled dozens of pickers, packers and drivers, already using wireless mobile scanners to transfer and control progress of the orders given by our system ... and all this with hardware and cpu power, that is surpassed by any digital wrist watch nowadays. Yeah, these were the days ...! ;)

Ah, the i386 with 40MHz was my first real computer after C64. I was very proud of it. Until, that is, the i486 came out. And thus I was introduced in the cruel world of "fast hardware outdating"...

**Comment by moving-bits** [comment] 2020-09-19 10:33
> Is there any way to instruct logcat simply to get the last e.g. half-an-hour-or-so of logs (c:geo plus system) regardless of the amount and put that into the logfile created by c:geo?

Time restrictions can be applied on more recent Android versions, but is not supported on all platforms c:geo supports. But even then it only limits the data available.
Maximum length of Logcat is limited by system settings - at least that's how I interpret the setting "Logger-Puffergrößen" (German) in the developer settings. But haven't tested yet. It's set to 256.000 bytes on my physical mobile device, haven't checked in the emulator.

For special use cases we could switch to our own logging (in addition to system logcat), something like I'd prepared in #9005 for catching the login error. I'll extract the logWriter to a separate PR to make it available in the nightlies, and then we can prepare special logging commands (like for #8818) as PR built on top of this.

**Comment by okainov** [comment] 2020-09-20 12:01
>As the map still lacks the feature to filter in any way (see e. g. #7278 and #3346), I use list "All caches" and filter it for "Status" => "Not Found". This kind of works - at least most of the times (unless some crashes because of timeout), but it's annooooyingly slow

Maybe I don't understand something, but what's the issue with checking "Hide-> Own/found caches"? Isn't it exactly what you're looking for? Works perfectly for me, at least I didn't notice any slowdowns even when there are ~100s of caches on the screen.

**Comment by MagpieFourtyTwo** [comment] 2020-09-21 00:28
@eddiemuc 
> do you use "global cache type filtering" (the filter on the start screen)?

No global filtering applied.

> If no one solved this issue in the meantime I promise you I will dig deeper into this (and yes, I may ask you again for testing and logging if I do :-)). I hope that's ok.

Yes, of course. And no stress, this is not vitally important. :)

@okainov 
> what's the issue with checking "Hide-> Own/found caches"

Problem is not hiding already found caches under "normal" circumstances (these are hidden by the option you mentioned, anyway), but using the map with no caches other than offline saved ones, so to *not* see all the unsaved (thus currently not interesting) stuff.
This can currently just be achieved via "list \<All caches> => Filter for not found (as this list of course does not care for found or not found) => Show on map" - which is really slow.

At least my wish could of course be solved way better by a map filter á la "Show only saved stuff" (which does not exist yet), but as it seems to turn out, the currently implemented way of working with such a long list just seems to beg for a rework ... if it's really done in memory. ;)

**Comment by okainov** [comment] 2020-09-21 06:33
> using the map with no caches other than offline saved ones, so to not see all the unsaved (thus currently not interesting) stuff.

I still don't understand. "Disable live" does exactly this. Why would you need filters?

**Comment by MagpieFourtyTwo** [comment] 2020-09-21 11:04
> I still don't understand. "Disable live" does exactly* this. Why would you need filters?

Yes, kind of, but not really. When you open Live Map, "Live" is enabled by default, so as soon as you open it, the map gets "polluted". And no matter if you disable "Live" - which at first sight seems to even remove the unsaved caches - the unsaved stuff will be there again after next switch away from map or to another app and back to c:geo's map. And in "crowded" areas, this can really be disturbing and you in fact do not see (and probably even miss) the caches, you're aiming to for real.

Nevertheless, the hint to disable "Live" will be kept in the back of our heads, as this will at least help in less "crowded" areas.

**Comment by MagpieFourtyTwo** [comment] 2020-09-21 11:27
> Is there any way to instruct logcat simply to get the last e.g. half-an-hour-or-so of logs

Remark: The stuff "missing" was not at the beginning of the saved logcat nor at it's end  ... it's right in the middle ...

**Comment by okainov** [comment] 2020-09-21 14:55
> "Live" is enabled by default, so as soon as you open it

That's not true for sure. It remembers previous setting. So if you have disabled it, then it is still disabled when you open cgeo again.

> the unsaved stuff will be there again after next switch away from map or to another app and back to c:geo's map.

That's what I wrote in my `*`/p.s. :) Sometimes it happens and it's indeed quite annoying, but just closing and reopening cgeo helps in this case, I don't see a big problem in doing that (but agree that this part can be improved). However sometimes it just hides all the unsaved caches directly when I disable Live, I have no idea about this behavior.

**Comment by MagpieFourtyTwo** [comment] 2020-09-21 14:59
Ok, just observed that they seemed to came back every single time.
Will check next time "in the wild". :)

**Comment by eddiemuc** [comment] 2020-09-26 10:11
I might be able to tackle this issue next (provided where discussion is going on #8897 ...).
I would like to try a different approach this time: I will create myself a local c:geo-database with many (fake) caches and logs in it and see whether I can reproduce the performance issues locally. This should save @MagpieFourtyTwo some rounds of "testing and log sending" I hope :-)

**Comment by MagpieFourtyTwo** [comment] 2020-09-26 14:09
Thanks for your thoughtfulness, but please keep an eye on time invest in total, too - and if building up your local DB will take more time than we would save in the testing process (for e. g. writing forth and back), I would have no problem at all to stay with the previous procedure - just feel free to ask ... ;)

**Comment by eddiemuc** [comment] 2020-09-26 15:27
Hi @MagpieFourtyTwo it was a matter of maybe 10 minutes to make a script to create 50000 dummy caches with 30 dummy log entries each.
The effect is astonishing though: c:geos list/filter features become pretty much unusable with this setting: opening the `all caches` list takes about 30 seconds, scrolling in this list is a pain and filtering `with offline logs` takes more than 5 minutes (no typo!).
I believe what is happening here is that c:geo tries to load all caches into memory, but memory overspills so parts are garbage collected, and when accessing these caches later (e.g. for filtering and scrolling) this becomes a nightmare of memory movement and reload. I can see lots of messages from garbage collection and cursor memory overflows.at least...

Will continue later, have to bake pancakes with my daughter now :-)

**Comment by eddiemuc** [comment] 2020-09-26 22:51
Note to self:
big performance issue seems to lie in how lists are filtered when a filter reduces a very large list (e.g. 50000 caches) to a very short list (e.g. only 30 caches or so). Then a list with all Geocaches to remove is created first, and then this list is removed from the original list using List.removeAll.
However, this leads to N^2 complexity because in order to remove each list item, the original list has to be parsed and Geocaching objects have to be compared one-by-one. A HashMap approach could solve this.
![image](https://user-images.githubusercontent.com/6909759/94351657-982c5c00-005b-11eb-9090-09a2f034425b.png)

**Comment by eddiemuc** [comment] 2020-09-26 22:57
Also removing element from a (long) array list is an extreme ly expensive operation (remainder of array has to be moved in memory by one position). Either use LinkedList or create new list from scratch as target

**Comment by MagpieFourtyTwo** [comment] 2020-09-26 22:57
Like your priorities.  :)

As for the lists: Why not forget about the in-memory lists and use an appropriate SELECT instead ...?
And on really long ones, memory usage can even more be reduced by e. g. SELECT TOP() ...

**Comment by moving-bits** [comment] 2020-09-27 06:37
Currently we are able to filter on lists with in-memory caches only, eg. a search result from a "by address" search.

Maybe we need to distinguish between lists having all caches in our database and those having at least one in-memory-only cache. Searching in database would be way faster in many occasions, and would allow more types of searches.

_IF_ you want to dive into filtering system at a more global level, there are a couple of other filter-related open issues, eg.: 
#8716 Country filter should only offers countries contained in the list to be filtered
#8620 Filtering attributes for opencaching.de caches does not work
#8383 Search uses filter/hide settings from map
#8377 FIlter for favorited caches
#8343 [Nightly] c:geo crashes while filtering a list (Transaction too large)
#8273 Make filters be able to consider the current cache list's contents
#7540 Filtered list not updated on change
#6511 Add filter for gc friend that has found caches in your list
#5877 Use better filter selection
#5860 Run filter async
#5523 Filter (for Found in last 30 days) seems to trigger ANRs
#5317 "own and found" filter in search result list
#5222 Remove attribute filter options in lists of unsaved caches
#5056 Filter/search by text on cache name
#3683 option for filtering archived caches on the map
#3346 Quick access to filter from map view
#2508 Have negation filter
#995 Global type filter versus local filters in lists
#135 Revise Cache filter (make it checkbox based)
(May have missed some)

There are some patterns behind those issues. Mostly
- use one filtering system instead of three (global / list / map)
- re-define UI
- performance
- what data is accessible for the filters

**Comment by eddiemuc** [comment] 2020-09-27 08:40
@moving-bits , @MagpieFourtyTwo Thanks for the good insights. I did not think before about situations where filtering has to be done on transient lists (not stored in DB) like results from address searches. I 100% agree with @moving-bits that this should be tackled at a larger context ("rework of searching, displaying and filtering of cache lists"), and he describes the situation perfectly.
This is, however, a larger topic. I am interested in tackling this, but I won't be able to do this right now.

Hence my suggestion:
* I will create a PR speeding up in-memory filtering based on my findings yesterday, because this is simply not programmed in a performant way currently. This should already increase dramatically the current problems of @MagpieFourtyTwo described in this issue
* I will create a new issue, basically with the content of @moving-bits 's last comment, and I will put this issue on my pesonal "ToDo-list" :-) (meaning that if others are interested in tackling this they may step in too). I want to put some sort of "closure" behind the logging topics before I dive into something so big again.

Would that be ok?

**Comment by eddiemuc** [comment] 2020-09-27 10:01
For the in-memory-filtering I added PR #9080. @moving-bits : I added some other things too with regards to logging, please check in PR if this is ok

**Comment by MagpieFourtyTwo** [comment] 2020-09-27 10:15
As for me, of course. Better later than never. ;)
Additionally, it's not that big of an issue yet, as there seem to be no massive complaints, so it's no high prio anyway, but with increasing phone capabilities, bigger internal and SD-card memory and raising mobile plans, I guess people will load and keep even more data (and caches) on their phones, so one day it will become a critical theme, for sure.

@moving-bits with regard to differentiation between DB and in-memory lists: As RAM seems to be the mayor issue here, I thought of a solution, where *all* lists, which may tend to grow big (a map list for example may not count into this, as this is usually limited to 500 or, in case of several map moves and updates maybe even 2k caches, but for sure not 10+k, nevertheless I would handle it the same way, to stay clear with regard to software design) be temporarily saved to DB - maybe in a separate table, to not clutter cg_caches or with a "dirty flag", to indicate that these just contain the data needed for lists and will be disposed and purged as soon as the list context is left (or with a grace period) ...

This way sort and filtering can easily be done in resp. by the DB, without bothering RAM and hitting it's limits ...? And for stuff that really has to be done in RAM, the already mentioned hash tables can be used ...

**Comment by moving-bits** [comment] 2020-09-27 11:27
> Would that be ok?

Yes, for sure, more than ok. I would be happy if you would dive into this area.

Proposal: Let's open a new issue to discuss architectural questions (eg: UI? Filtering already on connector level or only in memory? ...). For tracking the individual issues I've created a new project and will move the items from my list above to it.

**Comment by moving-bits** [comment] 2020-09-27 11:27
> For the in-memory-filtering I added PR #9080. @moving-bits : I added some other things too with regards to logging, please check in PR if this is ok

LGTM, just merged it. Thanks for tackling that issue!

**Comment by eddiemuc** [comment] 2020-09-29 06:46
@MagpieFourtyTwo PR #9080 (merged two days ago) should at least make your performance problems a little better (loading of whole list of caches should still be same-slow, but filtering should now be noticeably-faster (not "acceptable"-fast but "better-than-before"-fast). Whenever you can, I would appreciate a short feedback whether this worked out as I hoped.

**Comment by MagpieFourtyTwo** [comment] 2020-09-29 20:54
Yep, as you have already announced: It's still laggy, but way faster than before. Would say about 50 % speed gain. Felt.
Ah, have posted times in my second post, and it still takes the same time to open the 15 k \<All caches> list (3-4 secs).
But filtering - which took about 8 to 9 secs - is now done in about 4, while deleting the filter is with 4 secs the same as before.

**Comment by eddiemuc** [comment] 2021-04-17 06:51
In combination with #9081 I plan to solve this issue as follows:
* Make filtering as well as sorting SQL-based for offline Lists (in addition to in-memory filtering, which is still needed for non-pesisted lists e.g. gc.com search results)
* Introduce an optional settings-configurable limit used when loading lists from database (which will also be user in sql of course), maybe default to 500. At list end, user shall have the option to load rest of list

I think this should solve the problem at Hand. Making filtering and sorting SQL-based should lead to the most relevant caches always on top of the list and limit should make performance good even for very large lists. Also this method is consistent wrt UX with handling of other non-offline-stored list types 

What do you say?

**Comment by eddiemuc** [comment] 2021-04-24 14:58
Will be fixed with PR #10147

**Closed** 2021-05-07 18:36 UTC
Labels: Feature Request, Unverified
