### ISSUE TITLE
F-Droid repo is unavailable

### ISSUE THREAD

**Issue by Ceremony64** [cgeo/cgeo#5219] opened 2015-10-03 09:34 UTC
https://fdroid.cgeo.org response with `403 Forbidden`. F-Droid reports `Error getting index file`.
Has it been shutdown, moved or is there maintenance being done?

**Comment by samueltardieu** [comment] 2015-10-03 09:48
Cc @mucek4 @kumy

**Comment by kumy** [comment] 2015-10-03 09:52
Repo is up. and up to date. Don't use your browser, but the fdroid app.

**Comment by Ceremony64** [comment] 2015-10-03 09:56
Its not just when visiting via browser, but also when trying to fetch within F-Droid:
`Error getting index file https://fdroid.cgeo.org`

**Comment by kumy** [comment] 2015-10-03 09:58
Strange. It works for me...
I m not at home, I cannot check the logs.

**Comment by Ceremony64** [comment] 2015-10-03 10:01
Strange... all other Repos (e.g. Antox and I2P repos) I have work flawlessly. Just cgeo repo runs into an error...

**Comment by kumy** [comment] 2015-10-03 10:19
I ll look deeper tomorow night

**Comment by mucek4** [comment] 2015-10-03 11:51
I only keep cname record in dns. Will take a look when I get to pc

**Comment by kumy** [comment] 2015-10-04 20:00
@Ceremony64 I can't see where the problem is.
Could you share your IP? contact at geokretymap dot org
Could you also test without SSL? http://fdroid.cgeo.org
Thanks

**Comment by Ceremony64** [comment] 2015-10-04 20:10
HTTP works! No errors whatsoever. HTTPS still results in the issue above. I also just sent you a mail with my current IPv4

**Comment by mucek4** [comment] 2015-10-04 20:25
Could it be issue with cert or some firewall mtu? Can you try on any other network?

**Comment by kumy** [comment] 2015-10-04 20:26
As said in my reply, I didn't found your Ip in the logs, And since 22h00 I just got 2 requests on IPV6.
May you share your device info, Model/Android version. Which fdroid app version do you use? (mine is fdroid 0.92 ; Android 5.1.1)

**Comment by kumy** [comment] 2015-10-04 20:29
Hum, maybe an SNI problem...

**Comment by Ceremony64** [comment] 2015-10-04 20:31
I am running a Custom Rom (Euphoria-OS) which is based on Android 5.1.1 as well. F-Droid is 0.97-alpha4

**Comment by kumy** [comment] 2015-10-04 20:34
With F-Droid 0.97 I get the same error as yours

**Comment by Ceremony64** [comment] 2015-10-04 20:40
Issue seems to be occuring starting with 0.97-alpha2. Fetching apks from the server still works, but updating the server index does not.

**Comment by kumy** [comment] 2015-10-04 20:48
There is an open issue: [SNI missing after upgrade to 0.97-alpha2 ](https://gitlab.com/fdroid/fdroidclient/issues/431)

**Comment by kumy** [comment] 2015-10-04 21:03
I think we may close this issue, as the problem seems on the fdroid side.

**Closed by kumy** 2015-10-04 21:03 UTC
Labels: Bug, Website

**Comment by Ceremony64** [comment] 2015-10-04 21:05
Yep. Guess I'll stick to the stable 0.96.x release for now. Thanks for helping me out!
