### ISSUE TITLE
Nullpointer on Maps when Google Maps/Satellite is selected

### ISSUE THREAD

**Issue by sosnet** [cgeo/cgeo#4851] opened 2015-04-07 14:17 UTC
On startup OSM was selected without any problem. Then I switched to Google Maps on the Map View and got the first FC. Reopened cgeo, opened LiveMap and got a FC again. Only when switching back to OSM in the settings will open the LiveMap again.

Log shows:
```
E/cgeo    ( 5486): [main] UncaughtException
E/cgeo    ( 5486): java.lang.RuntimeException: Unable to start activity ComponentInfo{cgeo.geocaching/cgeo.geocaching.maps.google.v1.GoogleMapActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'int cgeo.geocaching.maps.CachesOverlay.size()' on a null object reference
E/cgeo    ( 5486): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2325)
E/cgeo    ( 5486): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
E/cgeo    ( 5486): 	at android.app.ActivityThread.access$800(ActivityThread.java:151)
E/cgeo    ( 5486): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
E/cgeo    ( 5486): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/cgeo    ( 5486): 	at android.os.Looper.loop(Looper.java:135)
E/cgeo    ( 5486): 	at android.app.ActivityThread.main(ActivityThread.java:5254)
E/cgeo    ( 5486): 	at java.lang.reflect.Method.invoke(Native Method)
E/cgeo    ( 5486): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/cgeo    ( 5486): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
E/cgeo    ( 5486): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
E/cgeo    ( 5486): Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int cgeo.geocaching.maps.CachesOverlay.size()' on a null object reference
E/cgeo    ( 5486): 	at cgeo.geocaching.maps.google.v1.GoogleCacheOverlay.size(GoogleCacheOverlay.java:48)
E/cgeo    ( 5486): 	at com.google.android.maps.ItemizedOverlay.populate(ItemizedOverlay.java:298)
E/cgeo    ( 5486): 	at cgeo.geocaching.maps.google.v1.GoogleCacheOverlay.superPopulate(GoogleCacheOverlay.java:68)
E/cgeo    ( 5486): 	at cgeo.geocaching.maps.AbstractItemizedOverlay.populate(AbstractItemizedOverlay.java:27)
E/cgeo    ( 5486): 	at cgeo.geocaching.maps.CachesOverlay.<init>(CachesOverlay.java:55)
E/cgeo    ( 5486): 	at cgeo.geocaching.maps.google.v1.GoogleCacheOverlay.<init>(GoogleCacheOverlay.java:33)
E/cgeo    ( 5486): 	at cgeo.geocaching.maps.google.v1.GoogleMapView.createAddMapOverlay(GoogleMapView.java:124)
E/cgeo    ( 5486): 	at cgeo.geocaching.maps.CGeoMap.onCreate(CGeoMap.java:509)
E/cgeo    ( 5486): 	at cgeo.geocaching.maps.google.v1.GoogleMapActivity.onCreate(GoogleMapActivity.java:37)
E/cgeo    ( 5486): 	at android.app.Activity.performCreate(Activity.java:5990)
E/cgeo    ( 5486): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
E/cgeo    ( 5486): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2278)
E/cgeo    ( 5486): 	... 10 more
E/AndroidRuntime( 5486): FATAL EXCEPTION: main
E/AndroidRuntime( 5486): Process: cgeo.geocaching, PID: 5486
E/AndroidRuntime( 5486): java.lang.RuntimeException: Unable to start activity ComponentInfo{cgeo.geocaching/cgeo.geocaching.maps.google.v1.GoogleMapActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'int cgeo.geocaching.maps.CachesOverlay.size()' on a null object reference
E/AndroidRuntime( 5486): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2325)
E/AndroidRuntime( 5486): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
E/AndroidRuntime( 5486): 	at android.app.ActivityThread.access$800(ActivityThread.java:151)
E/AndroidRuntime( 5486): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
E/AndroidRuntime( 5486): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime( 5486): 	at android.os.Looper.loop(Looper.java:135)
E/AndroidRuntime( 5486): 	at android.app.ActivityThread.main(ActivityThread.java:5254)
E/AndroidRuntime( 5486): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 5486): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime( 5486): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
E/AndroidRuntime( 5486): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
E/AndroidRuntime( 5486): Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int cgeo.geocaching.maps.CachesOverlay.size()' on a null object reference
E/AndroidRuntime( 5486): 	at cgeo.geocaching.maps.google.v1.GoogleCacheOverlay.size(GoogleCacheOverlay.java:48)
E/AndroidRuntime( 5486): 	at com.google.android.maps.ItemizedOverlay.populate(ItemizedOverlay.java:298)
E/AndroidRuntime( 5486): 	at cgeo.geocaching.maps.google.v1.GoogleCacheOverlay.superPopulate(GoogleCacheOverlay.java:68)
E/AndroidRuntime( 5486): 	at cgeo.geocaching.maps.AbstractItemizedOverlay.populate(AbstractItemizedOverlay.java:27)
E/AndroidRuntime( 5486): 	at cgeo.geocaching.maps.CachesOverlay.<init>(CachesOverlay.java:55)
E/AndroidRuntime( 5486): 	at cgeo.geocaching.maps.google.v1.GoogleCacheOverlay.<init>(GoogleCacheOverlay.java:33)
E/AndroidRuntime( 5486): 	at cgeo.geocaching.maps.google.v1.GoogleMapView.createAddMapOverlay(GoogleMapView.java:124)
E/AndroidRuntime( 5486): 	at cgeo.geocaching.maps.CGeoMap.onCreate(CGeoMap.java:509)
E/AndroidRuntime( 5486): 	at cgeo.geocaching.maps.google.v1.GoogleMapActivity.onCreate(GoogleMapActivity.java:37)
E/AndroidRuntime( 5486): 	at android.app.Activity.performCreate(Activity.java:5990)
E/AndroidRuntime( 5486): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
E/AndroidRuntime( 5486): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2278)
E/AndroidRuntime( 5486): 	... 10 more
W/ActivityManager(  720):   Force finishing activity 1 cgeo.geocaching/.maps.google.v1.GoogleMapActivity
W/ActivityManager(  720):   Force finishing activity 2 cgeo.geocaching/.MainActivity
```

**Comment by sosnet** [comment] 2015-04-07 14:20
I have a Nexus 5, with Android 5.1 and cgeo-nightly 2015.04.07

**Comment by Bananeweizen** [comment] 2015-04-07 16:43
thanks for the report. duplicate of #4848 .

**Closed by Bananeweizen** 2015-04-07 16:43 UTC
