### ISSUE TITLE
Crash of c:geo [java.lang.ArrayIndexOutOfBoundsException]

### ISSUE THREAD

**Issue by DaTechniker** [cgeo/cgeo#11504] opened 2021-08-21 05:31 UTC
### Describe your problem!

For some reason, I am not sure of, c:geo version: 2021.08.15 crashes and restarted

In the logs I see an exception for this time

08-20 23:58:42.539 21345 21345 E AndroidRuntime: FATAL EXCEPTION: main
08-20 23:58:42.539 21345 21345 E AndroidRuntime: Process: cgeo.geocaching, PID: 21345
08-20 23:58:42.539 21345 21345 E AndroidRuntime: java.lang.ArrayIndexOutOfBoundsException: length=638; index=638
08-20 23:58:42.539 21345 21345 E AndroidRuntime: 	at java.util.concurrent.CopyOnWriteArrayList.get(CopyOnWriteArrayList.java:380)
08-20 23:58:42.539 21345 21345 E AndroidRuntime: 	at java.util.concurrent.CopyOnWriteArrayList.get(CopyOnWriteArrayList.java:393)
08-20 23:58:42.539 21345 21345 E AndroidRuntime: 	at org.mapsforge.map.layer.Layers.get(Layers.java:336)
08-20 23:58:42.539 21345 21345 E AndroidRuntime: 	at org.mapsforge.map.android.input.TouchGestureHandler.onSingleTapConfirmed(TouchGestureHandler.java:263)
08-20 23:58:42.539 21345 21345 E AndroidRuntime: 	at android.view.GestureDetector$GestureHandler.handleMessage(GestureDetector.java:354)
08-20 23:58:42.539 21345 21345 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
08-20 23:58:42.539 21345 21345 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:246)

### How to reproduce?

No idea at the moment

### Reproducible

No

### c:geo Version

2021.08.15

### System information

```text
## System information

c:geo version: 2021.08.15

Device:
-------
- Device type: SM-A705FN (a70qeea, samsung)
- Available processors: 8
- Android version: 11
- Android build: RP1A.200720.012.A705FNXXU5DUE2
- Screen resolution: 1080x2198px (411x837dp)
- Sailfish OS detected: false
- Google Play services: disabled - 21.26.21 (150400-387928701)
- HW acceleration: enabled (default state)

Sensor and location:
-------
- Low power mode: inactive
- Compass capabilities: yes
- Rotation vector sensor: present
- Orientation sensor: present
- Magnetometer & Accelerometer sensor: present
- Direction sensor used: orientation

Program settings:
-------
- Settings: v8, Count:202
- Set language: de_AT (system default)
- System date format: dd.MM.yy
- Time zone: GMT+02:00
- Debug mode active: no
- Last backup: 2. Apr., 18:50
- Routing mode: Walk
- Live map mode: false
- OSM multi-threading: false / threads: 1
- Map: Aut+ (FZK) (Offline)
  - Id: cgeo.geocaching.maps.mapsforge.MapsforgeMapProvider$OfflineMapSource:0000-0000:OfflineMaps/Aut+ (FZK).map
  - Atts: (c) Map: FZK project (free for private use); Map data: OpenStreetMap contributors; Contour data: U.S. Geological Survey and J. de Ferranti
  - Theme: freizeitkarte-v5.zip:freizeitkarte-v5/freizeitkarte-v5.xml

Filters:
-------
- Hide waypoints: original visited
- LIVE: Aktiv und Liste und Gespeichert und Typ eingeblendet* ([Aktiv und Liste und Gespeichert und Typ eingeblendet*:inconclusive=false:advanced=true]AND(type;stored_since:-:-;status:found_no:exclude_archived;stored_list))
- OFFLINE: Aktiv und Liste und Gespeichert und Typ eingeblendet* ([Aktiv und Liste und Gespeichert und Typ eingeblendet*:inconclusive=false:advanced=true]AND(type;stored_since:-:-;status;stored_list))

Services:
-------
- Geocaching sites enabled:
   geocaching.com: Logged in (Anmeldung OK) / PREMIUM
   Geocaching.com Adventure Lab
- Geocaching.com date format: dd.MM.yyyy
- Routing: external / BRouter installed: false
- Installed c:geo plugins:  none

Permissions & paths:
-------
- Fine location permission: granted
- Write external storage permission: granted
- System internal c:geo dir: /data/user/0/cgeo.geocaching (54,7 GB free) v2 internal isDir(12 entries)
- Legacy User storage c:geo dir: /storage/emulated/0/cgeo (54,6 GB free) v2 external non-removable isDir(7 entries)
- Geocache data: /storage/0000-0000/Android/data/cgeo.geocaching/files/GeocacheData (1,1 GB free) v2 external removable isDir(26484 entries)
- Internal theme sync (is turned ON): /data/user/0/cgeo.geocaching/MapThemeData (54,7 GB free) v2 internal isDir(16 entries)
- Public Folders: #11
  - BASE: /cgeo (User-Defined)[/cgeo[DOCUMENT#0:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo, Av:true, files:>=18, dirs:>=8, totalFileSize:>=592,4 MB, free space: 54,6 GB, files on device: 3645440)
  - OFFLINE_MAPS: SD-Karte/OfflineMaps (User-Defined)[SD-Karte/OfflineMaps[DOCUMENT#0:p-content://com.android.externalstorage.documents/tree/0000-0000%3AOfflineMaps::]] (Uri: content://com.android.externalstorage.documents/tree/0000-0000%3AOfflineMaps/document/0000-0000%3AOfflineMaps, Av:true, files:16, dirs:1, totalFileSize:4,3 GB, free space: 1,1 GB, files on device: 0)
  - OFFLINE_MAP_THEMES: SD-Karte/OfflineThemes (User-Defined)[SD-Karte/OfflineThemes[DOCUMENT#0:p-content://com.android.externalstorage.documents/tree/0000-0000%3AOfflineThemes::]] (Uri: content://com.android.externalstorage.documents/tree/0000-0000%3AOfflineThemes/document/0000-0000%3AOfflineThemes, Av:true, files:804, dirs:3, totalFileSize:4,8 MB, free space: 1,1 GB, files on device: 0)
  - LOGFILES: /cgeo/logfiles (Default)[/cgeo/logfiles[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/logfiles]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Flogfiles, Av:true, files:10, dirs:0, totalFileSize:6,2 MB, free space: 54,6 GB, files on device: 3645440)
  - GPX: SD-Karte/OfflineThemes (User-Defined)[SD-Karte/OfflineThemes[DOCUMENT#0:p-content://com.android.externalstorage.documents/tree/0000-0000%3AOfflineThemes::]] (Uri: content://com.android.externalstorage.documents/tree/0000-0000%3AOfflineThemes/document/0000-0000%3AOfflineThemes, Av:true, files:804, dirs:3, totalFileSize:4,8 MB, free space: 1,1 GB, files on device: 0)
  - BACKUP: /cgeo/backup (Default)[/cgeo/backup[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/backup]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Fbackup, Av:true, files:2, dirs:1, totalFileSize:585,6 MB, free space: 54,6 GB, files on device: 3645440)
  - FIELD_NOTES: /cgeo/field-notes (Default)[/cgeo/field-notes[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/field-notes]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Ffield-notes, Av:true, files:275, dirs:0, totalFileSize:203,4 KB, free space: 54,6 GB, files on device: 3645440)
  - SPOILER_IMAGES: /cgeo/GeocachePhotos (Default)[/cgeo/GeocachePhotos[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/GeocachePhotos]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2FGeocachePhotos, Av:true, files:0, dirs:0, totalFileSize:0 B, free space: 54,6 GB, files on device: 3645440)
  - ROUTING_BASE: /cgeo/routing (Default)[/cgeo/routing[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/routing]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Frouting, Av:true, files:7, dirs:1, totalFileSize:81,2 KB, free space: 54,6 GB, files on device: 3645440)
  - ROUTING_TILES: /cgeo/routing/segments4 (Default)[/cgeo/routing/segments4[PERSISTABLE_FOLDER(ROUTING_BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/routing/segments4]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Frouting%2Fsegments4, Av:true, files:0, dirs:0, totalFileSize:0 B, free space: 54,6 GB, files on device: 3645440)
  - TEST_FOLDER: [Legacy]/data/user/0/cgeo.geocaching/files/unittest (Default)[/data/user/0/cgeo.geocaching/files/unittest[FILE#1:p-file:///data/user/0/cgeo.geocaching/files::/unittest]] (Uri: file:///data/user/0/cgeo.geocaching/files/unittest, Av:true, files:0, dirs:0, totalFileSize:0 B, free space: 54,7 GB, files on device: -1)
- Map render theme path: freizeitkarte-v5.zip:freizeitkarte-v5/freizeitkarte-v5.xml
- PersistedDocumentUris: #1
- TRACK: null
- Persisted Uri Permissions: #3
  - content://com.android.externalstorage.documents/tree/0000-0000%3AOfflineThemes (31. März, 13:28):RW
  - content://com.android.externalstorage.documents/tree/0000-0000%3AOfflineMaps (31. März, 13:27):RW
  - content://com.android.externalstorage.documents/tree/primary%3Acgeo (31. März, 13:27):RW
- Database: /storage/emulated/0/Android/data/cgeo.geocaching/files/databases/data (v96, Size:848,2 MB) on user storage

--- End of system information ---
```

### Additional Information

[logcat-2021-08-20-23-59-25-2.txt](https://github.com/cgeo/cgeo/files/7024955/logcat-2021-08-20-23-59-25-2.txt)

**Comment by DaTechniker** [comment] 2021-08-21 05:31
I am not sure, I know how to reproduce.
I had crashes with this version before.
I was doing a lot of filtering and moving of caches between the lists maybe something to do with the database operations.
Maybe there is a connection to other issues with slow views.
I was moving from lists to main menue.

At the moment, I do not have an idea what may be.
I will try to set a limit to the load limit to about 7000 from unlimited.
We saw db performance raise with other issues.

I will try to see if this changes the behavior and stability

**Comment by eddiemuc** [comment] 2021-08-21 08:07
Seems to be same issue as in #10128 and #11185. As far as I remember the main problems in analyzing this were:
* The stack trace does not involve any Cgeo class (just mapsforge and JDK/Android) so its hard to search for the cause in Cgeo
* We didn't find a way yet to reproduce 

A request towards mapsforge was not successful as far as I remember. I fear there is something fishy in our code around how we put new objects on the map and remove them. Probably a synchronization problem. But I also fear it will be hard to find

**Comment by Lineflyer** [comment] 2021-08-21 21:47
Indeed, a clear duplicate of the mentioned. Lets continue in those issues.

**Closed by Lineflyer** 2021-08-21 21:47 UTC
Labels: Bug, Unverified
