### ISSUE TITLE
Some half empty cache icons after zooming in/out

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#11663] opened 2021-09-14 21:03 UTC
Just a marker for after my vacation, will add screenshots then.

Not reproducible (yet):
- Open live map
- Zoom out and in repeatedly

At some point I ended up with some of the cache icons only either showing the upper or the lower half of the content (meaning, the white circle is shown, but the cache type icon only half, rest is white).

Android 11
2021.09.14-NB
Samsung S20

**Comment by ztNFny** [comment] 2021-09-16 07:49
duplicate of https://github.com/cgeo/cgeo/issues/11545

**Comment by Lineflyer** [comment] 2021-09-16 08:00
Sorry....missed that as well due to vacation. Closing here.

**Closed** 2021-09-16 08:00 UTC
Labels: Bug, Unverified
