### ISSUE TITLE
Support GPX 1.0.1 for Geotours

### ISSUE THREAD

**Issue by Surfoo** [cgeo/cgeo#6377] opened 2017-03-01 23:28 UTC
##### Detailed steps causing the problem:
- Download the GPX file for this Geotour : https://www.geocaching.com/play/geotours/bion3
- Import the file into c:geo

##### Actual behavior after performing these steps:
![screenshot_20170302-001517](https://cloud.githubusercontent.com/assets/553659/23486065/beec2e56-fede-11e6-8f7e-745f73aa104d.png)

##### Expected behavior after performing these steps:
Gpx imported successfully

##### Version of c:geo used:
2017.02.28-RC

##### Is the problem reproducible for you?
Yes

##### Other comments and remarks:
Here the gpx tag from the file :
`<gpx xmlns:schemaLocation="http://www.topografix.com/GPX/1/0 http://www.topografix.com/GPX/1/0/gpx.xsd http://www.groundspeak.com/cache/1/0/1 http://www.groundspeak.com/cache/1/0/1/cache.xsd" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:groundspeak="groundspeak" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:creator="Groundspeak, Inc. All Rights Reserved. http://www.groundspeak.com" xmlns:version="1.0">`

**Comment by rsudev** [comment] 2017-03-02 07:33
I can reproduce the problem as well. The namespace declaration seems doubtful for me, but I cannot cross-check right away.

**Comment by pstorch** [comment] 2017-03-02 21:22
I could also reproduce. 

As @rsudev suspected there might be something fishy with the namespace declaration. Android Studio tells me that the "Namespace declaration is never used...".
```
<gpx 
  xmlns:schemaLocation="http://www.topografix.com/GPX/1/0 http://www.topografix.com/GPX/1/0/gpx.xsd http://www.groundspeak.com/cache/1/0/1 http://www.groundspeak.com/cache/1/0/1/cache.xsd" 
  xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
  xmlns:groundspeak="groundspeak" 
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
  xmlns:creator="Groundspeak, Inc. All Rights Reserved. http://www.groundspeak.com" 
  xmlns:version="1.0"
>
```

Here is a namespace declaration of a working GPX file:
```
<gpx 
  xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
  version="1.0" 
  creator="Groundspeak Pocket Query" 
  xsi:schemaLocation="http://www.topografix.com/GPX/1/0 http://www.topografix.com/GPX/1/0/gpx.xsd http://www.groundspeak.com/cache/1/0/1 http://www.groundspeak.com/cache/1/0/1/cache.xsd" 
  xmlns="http://www.topografix.com/GPX/1/0"
>
```

But regardless of problems with the xml file itself, I could import this GPX successfully in Locus and Flopp's Map. Maybe they don't validate the document.

**Comment by rsudev** [comment] 2017-03-02 21:46
I took another look this evening and IMO this gpx is non-conforming.
On the one hand, it doesn't declare the top-level namespace to make it a gpx in the first place (see xmlns="http://www.topografix.com/GPX/1/0" from the correct example), on the other hand it does not declare the correct namespace for the groundspeak cache extensions (xmlns:groundspeak="groundspeak" should read xmlns:groundspeak="http://www.groundspeak.com/cache/1/0/1" to make it really denote the gpx extensions for geocache data).
That other gpx importers blindly assume gpx as default namespace and groundspeak: as namespace-prefix for the geocache extension does only help to proliferate broken geo-data.

**Comment by Lineflyer** [comment] 2017-03-02 23:08
Does this file even work on GPS devices like Garmin?

**Comment by Bananeweizen** [comment] 2017-03-03 12:11
That error message is coming directly from the SAX parser. I would rather not like to try and fix anything by doing some text replacement or similar before parsing the XML. I suggest to close this as WONTFIX as we did for GPX files from other tools where the output did not validate.

**Comment by kumy** [comment] 2017-03-03 13:12
+1 won't fix.

Wouldn't it be useful to open an issue to the upstream site, so they provides well formed xml files?

**Comment by pstorch** [comment] 2017-04-08 06:50
Looks like they have a general problem with their Geotour GPX files:
https://www.geocaching.com/play/geotours/paderborner-land/gpx?geotourId=94 is broken, too.

**Comment by Bananeweizen** [comment] 2017-04-09 06:33
Let's see if they can fix it. https://forums.groundspeak.com/GC/index.php?showtopic=343763

**Closed by Bananeweizen** 2017-04-09 06:33 UTC
Labels: Won't Fix
