### ISSUE TITLE
Static map load forever

### ISSUE THREAD

**Issue by kumy** [cgeo/cgeo#5915] opened 2016-08-21 21:33 UTC
##### Detailed steps causing the problem:
- Open a cache
- Store it
- Slide to "Details" tab
- Scroll down until map
- Tap the map
- Select "Static Maps"
##### Actual behavior after performing these steps:

Activity change, and "Loading static maps..." message is displayed forever.
##### Expected behavior after performing these steps:

Message should disappear, and map shown. Or at least if there is something wrong don't hang like this.
##### Version of c:geo used:

current release (self build)
##### Is the problem reproducible for you?

Yes.
##### System information:

```
--- System information ---
Device: m8 (cm_m8, htc)
Android version: 6.0.1
Android build: cm_m8-userdebug 6.0.1 MOB30R 702ea7c7ee test-keys
Cgeo version: 2016.08.21-6de45ba developer build
Google Play services: enabled
Low power mode: inactive
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: rotation vector
Hide own/found: false
Map strategy: fast
HW acceleration: enabled (default state)
System language: en_US
Log date format: 8/21/16
Debug mode active: yes (cgeo forced to English)
Geocaching sites enabled:
geocaching.com: Logged in (Login OK) / PREMIUM
Installed cgeo plugins: none
--- End of system information ---
```
##### Other comments and remarks:

Why `Static Maps` entry is only visible when cache is stored?

```
08-21 23:24:09.333 2923-5219/cgeo.geocaching E/cgeo: [Thread-9895] UncaughtException
                                                     android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.
                                                         at android.view.ViewRootImpl.checkThread(ViewRootImpl.java:6566)
                                                         at android.view.ViewRootImpl.focusableViewAvailable(ViewRootImpl.java:3042)
                                                         at android.view.ViewGroup.focusableViewAvailable(ViewGroup.java:761)
                                                         at android.view.ViewGroup.focusableViewAvailable(ViewGroup.java:761)
                                                         at android.view.ViewGroup.focusableViewAvailable(ViewGroup.java:761)
                                                         at android.view.ViewGroup.focusableViewAvailable(ViewGroup.java:761)
                                                         at android.view.View.setFlags(View.java:10565)
                                                         at android.view.View.setFocusableInTouchMode(View.java:7508)
                                                         at android.widget.AdapterView.checkFocus(AdapterView.java:744)
                                                         at android.widget.AdapterView$AdapterDataSetObserver.onChanged(AdapterView.java:839)
                                                         at android.widget.AbsListView$AdapterDataSetObserver.onChanged(AbsListView.java:6203)
                                                         at android.database.DataSetObservable.notifyChanged(DataSetObservable.java:37)
                                                         at android.widget.BaseAdapter.notifyDataSetChanged(BaseAdapter.java:50)
                                                         at android.widget.ArrayAdapter.notifyDataSetChanged(ArrayAdapter.java:301)
                                                         at android.widget.ArrayAdapter.add(ArrayAdapter.java:197)
                                                         at cgeo.geocaching.staticmaps.StaticMapsActivity$LoadMapsThread.run(StaticMapsActivity.java:100)
```

**Comment by Lineflyer** [comment] 2016-08-27 21:39
@kumy Do you have static maps disabled by default? Because if I try this the static maps open instantly as they have been saved while saving the cache.

**Comment by kumy** [comment] 2016-08-27 22:54
"Static map" is enabled in settings. "Static map (WP)" isn't.

On August 27, 2016 11:39:41 PM GMT+02:00, Lars <notifications@github.com> wrote:
>@kumy Do you have static maps disabled by default? Because if I try
>this the static maps open instantly as they have been saved while
>saving the cache.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/cgeo/cgeo/issues/5915#issuecomment-242942359

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by kumy** [comment] 2016-08-29 19:43
It doesn't happens on **Nexus 10**
```
--- System information ---
Device: Nexus 10 (mantaray, google)
Android version: 5.1.1
Android build: LMY49H
Cgeo version: 2016.08.29-fc9b99c developer build
Google Play services: enabled
Low power mode: inactive
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: rotation vector
Hide own/found: false
Map strategy: auto
HW acceleration: enabled (default state)
System language: fr_FR
Log date format: 8/29/2016
Debug mode active: no (cgeo forced to English)
Geocaching sites enabled:
geocaching.com: Logged in (Login OK) / PREMIUM
Installed cgeo plugins: none
--- End of system information ---
```

**Comment by Pitel** [comment] 2016-10-21 10:48
It's happening to me. Static maps for both caches and waypoints are enabled in settings.

```
10-21 12:40:23.363 ? E/cgeo: [Thread-37] StaticMapsActivity.LoadMapsThread.run
                             android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.
                                 at android.view.ViewRootImpl.checkThread(ViewRootImpl.java:6891)
                                 at android.view.ViewRootImpl.requestLayout(ViewRootImpl.java:1048)
                                 at android.view.View.requestLayout(View.java:19781)
                                 at android.view.View.requestLayout(View.java:19781)
                                 at android.view.View.requestLayout(View.java:19781)
                                 at android.view.View.requestLayout(View.java:19781)
                                 at android.view.View.requestLayout(View.java:19781)
                                 at android.widget.AbsListView.requestLayout(AbsListView.java:1989)
                                 at android.widget.AdapterView$AdapterDataSetObserver.onChanged(AdapterView.java:840)
                                 at android.widget.AbsListView$AdapterDataSetObserver.onChanged(AbsListView.java:6357)
                                 at android.database.DataSetObservable.notifyChanged(DataSetObservable.java:37)
                                 at android.widget.BaseAdapter.notifyDataSetChanged(BaseAdapter.java:50)
                                 at android.widget.ArrayAdapter.notifyDataSetChanged(ArrayAdapter.java:310)
                                 at android.widget.ArrayAdapter.add(ArrayAdapter.java:200)
                                 at cgeo.geocaching.staticmaps.StaticMapsActivity$LoadMapsThread.run(StaticMapsActivity.java:100)
```

```
--- System information ---
Device: Nexus 5X (bullhead, google)
Android version: 7.1.1
Android build: NPF10C
Cgeo version: 2016.10.20-NB-2bc67ef
Google Play services: enabled
Low power mode: active
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: rotation vector
Hide own/found: true
Map strategy: auto
HW acceleration: enabled (default state)
System language: cs_CZ
Log date format: 21.10.16
Debug mode active: yes
Fine location permission: granted
Write external storage permission: granted
Geocaching sites enabled:
   geocaching.com: Logged in (Přihlášení bylo úspěšné) / PREMIUM
Installed cgeo plugins:  none
--- End of system information ---
```

**Comment by Lineflyer** [comment] 2016-11-12 12:10
@samueltardieu Isn't this what you solved meanwhile?

**Comment by samueltardieu** [comment] 2016-11-12 18:36
#6111 is a duplicate of this. Since it is referenced in the fix, I'll close this one as a duplicate.

Thanks @Lineflyer for the ntoe.

**Closed by samueltardieu** 2016-11-12 18:36 UTC
Labels: Bug
