### ISSUE TITLE
Scrolling broken after selection

### ISSUE THREAD

**Issue by Bananeweizen** [cgeo/cgeo#5490] opened 2016-02-28 15:52 UTC
Select some text of the description. Close selection mode. Try to scroll the view up and down. It jumps around.

**Comment by Lineflyer** [comment] 2016-02-28 20:18
Confirmed.
Happend to me today with 2016.02.27-RC while scrolling through the cache description even without previously opening the selection mode (or it happend unintentionally).

**Comment by kumy** [comment] 2016-03-01 13:17
Cannot reproduce on Android 6.0.1

**Comment by rsudev** [comment] 2016-03-01 13:24
For me it was also tied to the selection mode. After closing selection mode, after scrolling down and then starting to scroll up, it jumped always to the beginning. Without using selection mode before, srolling up and down worked as expected (Android 5.1.1)

**Comment by kumy** [comment] 2016-03-01 13:27
Tested on another phone Android 4.4.4 (CyanogenMod too), cannot reproduce...

**Comment by rsudev** [comment] 2016-03-01 13:45
My detailed test description:
* Have GC5VVVV saved on the device, open it
* swipe to description
* Long-press on the first paragraph, select some more text by extending the marker, select copy from the context action bar
* scroll down (takes around three screen full)
* after reaching the end, start to scroll up again a little - the description immediately jumps to the top

Cross check:
* Close the cache, re-open it
* Swipe to the description
* scroll down (again three screens)
* scroll up again (also three screens)

**Comment by rsudev** [comment] 2016-03-01 13:46
(Sony Xperia Z1 rooted stock ROM Android 5.1.1)

**Comment by kumy** [comment] 2016-03-01 13:48
Thanks @rsudev I hit the bug too (Android 6.0.1)

**Comment by rahu** [comment] 2016-03-01 20:15
After taking a deeper look into I found out this behavior is caused by the workaround from https://code.google.com/p/android/issues/detail?id=137509 which was added to `IndexOutOfBoundAvoidingTextview`. 

Remove 
```
    @Override
    protected void onSelectionChanged(final int selStart, final int selEnd) {
        if (selStart == -1 || selEnd == -1) {
            // @hack : https://code.google.com/p/android/issues/detail?id=137509
        /*    final CharSequence text = getText();
            if (text instanceof Spannable) {
                Selection.setSelection((Spannable) text, 0, 0);
            }*/
        } else {
            super.onSelectionChanged(selStart, selEnd);
        }
    }
```
from `IndexOutOfBoundAvoidingTextview` and there is no more jumping. But you can double click the text and make cgeo crash when you move a selector afterwards.

**Comment by Lineflyer** [comment] 2016-03-01 20:24
mmh..without knowing what is wrong here in detail due to lack of understanding of the code:
The problem happens after the selection mode has ended. GIven that, couldn't we just take care that the description view is refreshed/resetted after leaving the selection mode (same state as just after freshly opening it)?

**Comment by kumy** [comment] 2016-03-03 22:19
I propose to change the function to

```
	// https://code.google.com/p/android/issues/detail?id=137509
	@Override
	protected void onSelectionChanged(final int selStart, final int selEnd) {
		try{
			super.onSelectionChanged(selStart, selEnd);
		} catch (final IndexOutOfBoundsException ignored) {
			super.onSelectionChanged(0, 0);
		}
	}
```

**Comment by kumy** [comment] 2016-03-03 22:21
PR #5502 opened

**Comment by rahu** [comment] 2016-03-04 04:58
I just installed the pull request build for testing this new workaround.

On my phone c:geo crashes if I do these steps:
1)double-tap the description text (getting text selectors on the beginning of the text)
2) try to move one of them

This is the same behaviour as without the function.


Am 3. März 2016 23:19:06 MEZ, schrieb kumy <notifications@github.com>:
>I propose to change the function to
>
>```
>	// https://code.google.com/p/android/issues/detail?id=137509
>	@Override
>	protected void onSelectionChanged(final int selStart, final int
>selEnd) {
>		try{
>			super.onSelectionChanged(selStart, selEnd);
>		} catch (final IndexOutOfBoundsException ignored) {
>			super.onSelectionChanged(0, 0);
>		}
>	}
>```
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/cgeo/cgeo/issues/5490#issuecomment-191992076

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by kumy** [comment] 2016-03-04 08:09
@rahu as I cannot get the crash on my device, could you test something like this for me. Thanks
```
	// https://code.google.com/p/android/issues/detail?id=137509
	@Override
	protected void onSelectionChanged(final int selStart, final int selEnd) {
		try{
			super.onSelectionChanged(selStart, selEnd);
		} catch (final IndexOutOfBoundsException ignored) {
			final CharSequence text = getText();
			if (text instanceof Spannable) {
				Selection.setSelection((Spannable) text, 0, 0);
			} else {
				super.onSelectionChanged(0, 0);
			}
		}
	}
```

**Comment by rsudev** [comment] 2016-03-04 08:31
To me this looks like being back to the same implementation as before, more or less. Unless ```onSelectionChanged``` does not fail on ```-1``` any more

**Comment by kumy** [comment] 2016-03-04 09:08
Right, bug may still happend for device like rahu one :/

On March 4, 2016 9:31:48 AM GMT+01:00, rsudev <notifications@github.com> wrote:
>To me this looks like being back to the same implementation as before,
>more or less. Unless ```onSelectionChanged``` does not fail on ```-1```
>any more
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/cgeo/cgeo/issues/5490#issuecomment-192183230

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by rahu** [comment] 2016-03-04 19:22
```
Process: cgeo.geocaching, PID: 3811
java.lang.IndexOutOfBoundsException: setSpan (-1 ... -1) starts before 0
    at android.text.SpannableStringBuilder.checkRange(SpannableStringBuilder.java:1041)
    at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:626)
    at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:622)
    at android.text.Selection.setSelection(Selection.java:76)
    at android.widget.Editor$SelectionEndHandleView.updateSelection(Editor.java:3838)
    at android.widget.Editor$HandleView.positionAtCursorOffset(Editor.java:3454)
    at android.widget.Editor$SelectionEndHandleView.updatePosition(Editor.java:3858)
    at android.widget.Editor$HandleView.onTouchEvent(Editor.java:3585)
    at android.view.View.dispatchTouchEvent(View.java:8593)
    at android.view.View.dispatchPointerEvent(View.java:8799)
    at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4662)
    at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4520)
    at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4034)
    at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4087)
    at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4053)
    at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4190)
    at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4061)
    at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4247)
    at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4034)
    at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4087)
    at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4053)
    at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4061)
    at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4034)
    at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6463)
    at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6437)
    at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6390)
    at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6622)
    at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
    at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
    at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:176)
    at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:6581)
    at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:6648)
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:800)
    at android.view.Choreographer.doCallbacks(Choreographer.java:603)
    at android.view.Choreographer.doFrame(Choreographer.java:570)
    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:786)
    at android.os.Handler.handleCallback(Handler.java:815)
    at android.os.Handler.dispatchMessage(Handler.java:104)
    at android.os.Looper.loop(Looper.java:194)
    at android.app.ActivityThread.main(ActivityThread.java:5637)
    at java.lang.reflect.Method.invoke(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:372)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:960)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
```

this is the exception with the changes from you PR.  It's the same as without the fix from https://code.google.com/p/android/issues/detail?id=137509 .

**Comment by rahu** [comment] 2016-03-04 21:55
After adding the solution from http://stackoverflow.com/questions/15836306/can-a-textview-be-selectable-and-contain-links to `AnchorAwareLinkMovementMethod` I'm able to double tap the description and get the double taped word selected. From my side there is no need to have the workaround in `onSelectionChanged` any longer.

**Comment by kumy** [comment] 2016-03-04 22:04
@rahu nice, may you provide a Pull Request?

**Comment by rahu** [comment] 2016-03-04 22:09
git is pushing right now. 

Next to the double-tape select it's possible to scroll with a active selection now. Was this possible before?

**Comment by kumy** [comment] 2016-03-05 10:40
@rahu behavior with selection is really much better with your patch. Thanks
Just tested also without the old workaround. It's still ok for me. From my point of view, it could be removed.

However it seems you PR is based on the master branch, as this issue is a fix for the release branch, it would be better if you could propose the PR from this branch. See https://github.com/cgeo/cgeo/wiki/How-to-get-a-bug-fix-into-the-release#how-to-do-a-fix-right

**Comment by rahu** [comment] 2016-03-05 16:45
I removed the old workaround and opened a new pullrequest based on release branch.

**Comment by kumy** [comment] 2016-03-06 10:43
As stated in PR #5506 `release` branch contain only a fix, and `master` contains also a method cleanup.

@rahu Thanks for your contribution
@Lineflyer assigned for testing

**Comment by Lineflyer** [comment] 2016-03-06 20:01
Compared the older RC-version with a freshly compiled RC version from today. 
Scrolling works flawless, also selection mode works normal. 
Only occasionally when starting the selection mode the text position jumps initially, I could not find our why exactly this is happening but I don't consider it critical, as afterwards everything is smooth.
Tested with: GCZC6E

**Closed by Lineflyer** 2016-03-06 20:01 UTC
Labels: Assigned-non-collab, Bug, Field test, Regression

**Comment by rahu** [comment] 2016-03-07 18:51
I tested the nightly with GCZC6E on a Xperia Z1 (android 5.1.1) and selection and scrolling works perfect. 
On a dooge X5 (android 5.1) the inital selection is a bit strange. It starts at the selected word and ends at the end of the table-cell. This could be reproduced for other caches where tables are used to format the listing. Is this the same behavior you observed? If not, the position jump is maybe a artefeact from the old workarround? Can you cross-check against nightly in this case? On a cache without tables (e.g. GC67B56) only the selected word is selected.

**Comment by kumy** [comment] 2016-03-09 00:04
FTR, The method to cleanup was recently added by 5449a1d
