### ISSUE TITLE
UI handling problem with bottom sheet navigation menu

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#15623] opened 2024-04-16 13:29 UTC
### Describe your problem!

A user contacted us with a minor but strange problem.
When trying to use the navigation options from the bottom sheet on the map, he has the problem that the menu is stuck if he slides his finger after having tapped on the navigation item.

### How to reproduce?

Video of the issue provided by the user (publication on Github OK for the user):

https://github.com/cgeo/cgeo/assets/949669/78895f8e-83c2-4ea8-be35-525315bc14cf

### Actual result after these steps?

If the user wants to go back from navigation, he has to press the back key several times
If the user wants to select a navigation method, the map seemingly crashes and restarts

### Expected result after these steps?

Normal usability

### Reproducible

Yes

### c:geo Version

2024.04.05

### Additional Information

Support ticket 309646

**Comment by MagpieFourtyTwo** [comment] 2024-04-19 07:28
WFM - can't reproduce

**Comment by moving-bits** [comment] 2024-04-19 20:45
Reproducible for me in an emulator as well as on a physical device:
- tap and hold the "navigation arrow" button
- and slide your finger away from that button, still holding it

Navigation selection popup will open multiple times, which leads to having to tap the back button the same amount of times.

Not sure if we can do anything about it, looks like a bug in the framework to me.

**Comment by MagpieFourtyTwo** [comment] 2024-04-19 23:59
Yes, you're right, had to press the nav button even way longer.

**Comment by moving-bits** [comment] 2024-09-22 10:13
Duplicate of #15937 and fixed with #15981, therefore closing here

**Closed by moving-bits** 2024-09-22 10:13 UTC
Labels: Bug
