### ISSUE TITLE
Option to upload more images

### ISSUE THREAD

**Issue by hakuchi** [cgeo/cgeo#7119] opened 2018-08-18 19:16 UTC
I would upload today some Pictures to a log, but I saw that I can only upload one in the settings of c:geo.

There should be a option to select how many images I will upload.

**Comment by Lineflyer** [comment] 2018-08-18 19:49
Duplicate of #2734

**Closed by Lineflyer** 2018-08-18 19:50 UTC

**Comment by hakuchi** [comment] 2018-08-18 19:51
oh...searched but not found this old request.
