### ISSUE TITLE
Update or retire legacy version (API 16-20)

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#9285] opened 2020-10-25 21:37 UTC
Play Store is enforcing new policies regarding background access to location:
![image](https://user-images.githubusercontent.com/3754370/97119716-4cc8a480-1712-11eb-9814-7505681551cf.png)

see https://developer.android.com/distribute/play-policies

Although we're not using background access to location (AFAIK), Play Console still marks our app as violating the policies:
![image](https://user-images.githubusercontent.com/3754370/97119666-02dfbe80-1712-11eb-9b03-4314b5637e91.png)

TODO: Check if there is any action to be taken by us (applying for something, doing a code change or whatever)

@Lineflyer @mucek4

**Comment by mucek4** [comment] 2020-10-27 11:32
The only reason for c:geo that needs background permission is "talk to navigate". That's something that does not work at all on Huawei as when display is off app is paused. 
I am not sure if we change cgeo tu run in background (Icon in task bar) if location permission needs to be permanent or that counts as running.

**Comment by Lineflyer** [comment] 2020-10-27 12:22
I am wondering about this "background location permission" in general, as when I first time start c:geo the permission dialog offers:
- Allow during usage of the app
- Do not allow
- Do not allow and don't ask again

The first item sound like "foreground permission" and I have also seen other apps where one more option "Always allow" is shown on the permission dialog. 
Maybe its only a configuration issue (knowing that Talking compass will anyhow not work in background as also @mucek4 described, but thats a different story).

**Comment by Lineflyer** [comment] 2020-10-27 12:32
@moving-bits 
Can you provide a link of where you found the information shown on your second screenshot?

**Comment by Lineflyer** [comment] 2020-10-27 12:50
According to https://developer.android.com/training/location/permissions we do not explicitly request background location permission and we also target SDK29.
I guess the "problem" why we are shown as violating is, that we also have the legacy version targeting a lower SDK.
So IMHO we can just take the questionaire and confirm, that we do not intentionally use background location for that APK.

**Comment by Lineflyer** [comment] 2020-10-27 12:51
Addition:
Or simply drop legacy support before March 2021.

**Comment by Lineflyer** [comment] 2020-10-27 12:53
Offtopic (just on the way of renewing the age allowance check on Google Play):

I am unsure about "Yes" or "No" at this point  :) ...just kidding

![grafik](https://user-images.githubusercontent.com/949669/97304198-af798780-185b-11eb-8961-d44b54a2d019.png)

**Comment by Lineflyer** [comment] 2020-10-27 12:58
> @moving-bits
Can you provide a link of where you found the information shown on your second screenshot?

Nevermind, I found it meanwhile.
When starting this process I get a list of APK violating the terms and it is indeed our legacy version only listed here.

![grafik](https://user-images.githubusercontent.com/949669/97304653-51996f80-185c-11eb-92cd-625d410f90b7.png)

**Comment by Lineflyer** [comment] 2020-10-27 21:17
Addition:
We can no longer push updates to the legacy app starting in a few days anyway unless we would raise targetSDK to 29 for it. Therefore I am afraid, that the lifetime of the legacy version is rather limited.

**Comment by bekuno** [comment] 2020-10-27 21:38
> 
> 
> Addition:
> We can no longer push updates to the legacy app starting in a few days anyway unless we would raise targetSDK to 29 for it.

Currently we have on the legacy version:
~~~
        minSdkVersion 16
	maxSdkVersion 20
        targetSdkVersion 28
~~~
We do not change minSdkVersion/maxSdkVersion when changing the targetSdkVersion .
So the change of targetSdk is possible.
But at first we have to check if there are regressions when changing targetSdkVersion .

**Comment by Lineflyer** [comment] 2020-10-27 21:51
> So the change of targetSdk is possible.
But at first we have to check if there are regressions when changing targetSdkVersion .

Yes, but possibly to much effort for it, don't you think?

**Comment by bekuno** [comment] 2020-10-27 21:53
As we have currently no hurry with change to the SAF we do not have to change our code, I would say.
@moving-bits ?

**Comment by moving-bits** [comment] 2020-10-27 21:58
> As we have currently no hurry with change to the SAF we do not have to change our code, I would say.
> @moving-bits ?

You are referring to the legacy version?
There's only the TB website change we should publish, and if we do so before the new policy gets set active, we can stay with current targetSDK for legacy version for now. But, to be honest, I've no idea whether we will be able to adjust legacy version to the new targetSDK at all.

The original reason for this issue, though, was about Play Store stating some of our apps are violating their policies, and requesting us to update a questionnaire (?) to comment why we are requesting those permissions.

**Comment by mucek4** [comment] 2020-10-29 07:10
So they will only remove Legacy version for older phones. And TBs already does not work in Legacy?

**Comment by Lineflyer** [comment] 2020-10-29 08:59
> So they will only remove Legacy version for older phones.

Yes, or we just fill in the form stating that we do not use any active background location, but would like to keep this version for older Android version as legacy, so they might give us a permission.

> And TBs already does not work in Legacy?

Will be fixed before November, 1st for legacy...thats the plan.

**Comment by Lineflyer** [comment] 2020-12-28 23:20
I changed the title on this issue to the real topic as of now:
As Google enforces the removal of background permission (which is equal to enforcing targetSDK 29 AFAICS) we need to decide in beforehand whether we should take the effort to evolve legacy to targetSDK=29 or not.

My vote is clearly to drop support of API<=20 (Android 4.x and below) and retire the current legacy version latest March 2021.

**Comment by eddiemuc** [comment] 2020-12-29 10:32
> My vote is clearly to drop support of API<=20 (Android 4.x and below) and retire the current legacy version latest March 2021.

Same here. Also a very clear vote :-)

**Comment by moving-bits** [comment] 2020-12-29 15:57
> > My vote is clearly to drop support of API<=20 (Android 4.x and below) and retire the current legacy version latest March 2021.
> 
> Same here. Also a very clear vote :-)

Agreed 👍

**Comment by bekuno** [comment] 2020-12-29 18:00
> As Google enforces the removal of background permission (which is equal to enforcing targetSDK 29 AFAICS) we need to decide in beforehand whether we should take the effort to evolve legacy to targetSDK=29 or not.
> 
> My vote is clearly to drop support of API<=20 (Android 4.x and below) and retire the current legacy version latest March 2021.

If we **now** want to change something at the legacy version, we have to change to targetSDK=29.
So either we have already stopped supporting the legacy version or we can do it when targetSDK=30 is enforced.
Or - we will only release updates on F-Droid.

If I correct remember we can easily switch to targetSDK=29. Only a change on AndroidManifest.xml is necessary. Isn´t it?

@Lineflyer Can you update https://github.com/cgeo/cgeo/wiki/Playstore-statistics to have a actual situation?
In May we had ~2,5% users of the legacy Android version (4.x).
Do we have such statistic for the F-Droid installations?

I vote for dropping the support now if the installation count below 1%.

**Comment by Lineflyer** [comment] 2020-12-29 22:26
FYI the installed active device (c:geo installed and online within last 30 days) distribution based on Google Play Statistics as of today:

Version | API | User | Percentage
-- | -- | -- | --
Android 11 | 30 | 50.018 | 5,9%
Android 10 | 29 | 427.688 | 50,2%
Android 9 | 28 | 154.199 | 18,1%
Android 8.1 | 27 | 26.196 | 3,1%
Android 8.0 | 26 | 80.062 | 9,4%
Android 7.1 | 25 | 17.432 | 2,0%
Android 7 | 24 | 41.215 | 4,8%
Android 6 | 23 | 27.614 | 3,2%
Android 5.1 | 22 | 8.384 | 1,0%
Android 5 | 21 | 6.461 | 0,8%
Android 4.4 | 19 | 8.520 | 1,0%
Android 4.3 | 18 | 870 | 0,1%
Android 4.2 | 17 | 1.679 | 0,2%
Android 4.1 | 16 | 1.493 | 0,2%
Android 4.0.3-4.0.4 | 15 | 99 | 0,0%
older |   | 208 | 0,0%

This means retiring legacy affects 1,5% of users.

Statistics also added to https://github.com/cgeo/cgeo/wiki/Playstore-statistics

**Comment by rsudev** [comment] 2020-12-30 10:02
Totalling the figures we get ~ 13k users affected (one of them I know personally). Tricky question. Besides looking at the effort of supporting these versions it would also be interesting to understand what this support in the end can offer (IIRC there are serious connection problems due to no longer supported tls protocol versions and ciphers)

**Comment by Lineflyer** [comment] 2021-04-01 22:42
Update of active user installations API 16-20 (c:geo installed and device online within last 30 days) as of 30.03.21:

Users | Version
-- | --
6426 | Android 4.4
1320 | Android 4.2
1119 | Android 4.1
651 | Android 4.3
60 | Android 4.0.3/4.0.4
-- | -- 
9576 | Total

Total figure (c:geo installed and device online within last 30 days): 716.048
Accordingly API16-20 is around 1,3% of users.

**Comment by Lineflyer** [comment] 2021-04-18 19:15
I am going to remove the legacy version from Google Play. 
While releasing 2021.04.15 it was remarked, that the release contains an app violating the standards (the legacy version (see above for reasoning).

**Comment by moving-bits** [comment] 2021-04-18 19:59
Shall we add some note in manual or FAQ why we cannot support the legacy version any longer?

**Comment by Lineflyer** [comment] 2021-04-18 20:07
I will adapt the relevant FAQ entry if it needs update (did not check yet).

**Comment by bekuno** [comment] 2021-04-28 04:54
Would it make sense to port the fixes for the last geocaching.com changes to the legacy version (to publish on F-Droid)?

**Comment by Lineflyer** [comment] 2021-04-28 06:55
Would be possible using our CI mechanisms.

**Comment by Lineflyer** [comment] 2021-05-04 13:19
There are indeed now some users asking us regarding their 4.x devices.

Is somone able to cherry-pick the website changes to `cgeo-legacy`.
I would then push a version to F-Droid and link them in our FAQ to download from our website.

**Comment by Lineflyer** [comment] 2021-08-01 11:05
Lets close this topic. IMHO its not worth the effort and there have been even more website changes since then.

**Closed by Lineflyer** 2021-08-01 11:05 UTC
Labels: Feedback required, Google Play or Beta feedback
