### ISSUE TITLE
Including proximity warning signal

### ISSUE THREAD

**Issue by wizard4u** [cgeo/cgeo#5730] opened 2016-05-10 15:17 UTC
##### Detailed steps causing the problem:
- Step 1
- Step 2
- ...

##### Expected behavior after performing these steps:
additional feature: add proximity signal to c:geo nearing / closing in a geocache (distance might be variable / settable

##### Is the problem reproducible for you?
Yes/No

##### System information:
```
Attach system information here if available (see c:geo menu -> About c:geo -> System)
```

**Comment by SammysHP** [comment] 2016-05-10 16:45
Duplicate of #417.

**Closed by SammysHP** 2016-05-10 16:45 UTC
