### ISSUE TITLE
Have more prominent links to APK downloads on c:geo Homepage

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#2060] opened 2012-09-20 19:54 UTC
Over the last months I got quite a lot of questions dealing with:
1. Where to download the APK outside of the PlayStore
2. Where to find the nightly builds

On the starting page of www.cgeo.org you will only find them after scrolling all the way down at the bottom left.
Maybe we could link it from above as well (next to the PlayStore link)  to avoid such questions.

**Comment by Lineflyer** [comment] 2015-01-01 22:58
@mucek4 Can you link the APK download on the homepage to https://github.com/cgeo/cgeo/releases/latest please.
Doing so the most urgent topic for people looking for the official version would be solved.

**Comment by Lineflyer** [comment] 2015-02-08 10:44
Work has been started for cgeo.github.io.
So hopefully no more need to do this on the "old page".

Issue will be closed once the website is live.

**Comment by SammysHP** [comment] 2015-02-08 11:18
Let's close it now as the website is in development, the issue is "fixed" and I'll open another one once @mucek4 has to change the DNS configuration of cgeo.org.

**Closed by SammysHP** 2015-02-08 11:18 UTC
Labels: Website
