### ISSUE TITLE
[unified vtm] fail to render if viewport is too large

### ISSUE THREAD

**Issue by fm-sys** [cgeo/cgeo#14948] opened 2023-12-02 22:13 UTC
Steps to reproduce:

- create a list with a cache in USA and Australia
- show map as list

=> map stays grey and can't be moved zoomed

![Screenshot_20231202_231014_cgeo geocaching](https://github.com/cgeo/cgeo/assets/64581222/00e67766-6d08-4173-a8dd-b5b0f984db36)

**Comment by moving-bits** [comment] 2023-12-02 22:21
it may be that the zoom level calculated by `UnifiedMapActivity` for showing all caches in the same view is not supported by current map. Can you compare its value against `getZoomMin()` / `getZoomMax`?

**Comment by moving-bits** [comment] 2023-12-04 18:43
> it may be that the zoom level calculated by `UnifiedMapActivity` for showing all caches in the same view is not supported by current map. Can you compare its value against `getZoomMin()` / `getZoomMax`?

Forget this part - UnifiedMap currently ignores the values for min/max 🤷‍♂️, and during my tests I've seen pure nonsense in the map files being reported for supported min/max values (so ignoring those limits may actually be a useful mitigation). 🤔

**Comment by moving-bits** [comment] 2023-12-04 20:19
Just tried to find a small code example for reproducing this bug, therefore modified the original VTM example `MapsforgeActivity` by adding the following code snippet around line 244 (before the `catch` block):

```
Bitmap bitmapPoi = new AndroidBitmap(BitmapFactory.decodeResource(getResources(), R.drawable.marker_poi));
MarkerSymbol symbol = new MarkerSymbol(bitmapPoi, MarkerSymbol.HotspotPlace.CENTER, false);
ItemizedLayer mMarkerLayer = new ItemizedLayer(mMap, symbol);
mMap.layers().add(mMarkerLayer);
List<GeoPoint> pts = new ArrayList<>();
pts.add(new GeoPoint(51.487, 7.0425));
pts.add(new GeoPoint(47.649, -122.348));
pts.add(new GeoPoint(-33.858, 151.215));

List<MarkerInterface> markers = new ArrayList<>();
for (GeoPoint gp : pts) {
    markers.add(new MarkerItem(gp.toString(), "", gp));
}
mMarkerLayer.addItems(markers);
mMap.animator().animateTo(new BoundingBox(pts));
```

This draws a small dot in Seattle, Sidney and Essen (home of the GC7G1GA event).
When starting the activity and selecting Mapsforge's world.map, it scales to a 2000km unit, and only the dot in Europe is being displayed in portrait mode - but it does work. When rotating the device to landscape mode, all three dots are visible, no rendering issues.

In contrast to this, c:geo fails to display the map when mapping a list with the three caches with above's coordinates. It shows a white window, scaled to 2000 km, with "(c)" and zoom controls, but no map content. I can zoom to 10000 km using the mouse (but can no longer zoom back), and I can rotate using the mouse. But in neither state the selected map "world.map" is being displayed in this case.

The very same map displays fine when opening the map directly, not displaying contents of a specific list. Zooming out to 10000 km is possible in this case, with the map getting displayed.

|map opened manually|displaying list content|
|---|---|
|![image](https://github.com/cgeo/cgeo/assets/3754370/5a579946-f2a3-43c5-bdd0-42ab98faeca9)|![image](https://github.com/cgeo/cgeo/assets/3754370/38f0d11b-cf2c-4e21-9f4c-54ee60297173)|

BTW: When displaying a list, the number of caches in this list should be displayed (3, in this case), not the number of (temporarily) stored caches in the area being displayed (193 out of 195, as the one in Seattle and the one in Sidney where not visible compared to the other screenshot, due to different zoom levels).

**Comment by fm-sys** [comment] 2023-12-04 23:03
Yes, that's pretty much the same I was experiencing. Well described!

I also tried to debug this a bit yesterday, but unfortunately without any progress.

**Comment by moving-bits** [comment] 2023-12-08 23:15
Another observation:

If you change the zoom command in `zoomToBounds` by adding a animation duration of eg 10 seconds, you can see that the map gets actually zoomed and displayed, but then vanishes shortly before the end of the animation. (Default timespan is 1000 ms)

But the viewport is way too large, changing the zoom level does not seem to work. Maybe we need to adjust `zoomToBounds` to set a target zoom level manually first, then do the animation?

**Comment by eddiemuc** [comment] 2023-12-14 23:34
I debugged this issue (could easily and reliable reproduce it) down to the following method of class `org.oscim.map.Animator`. This is the method called in the end to perform the actual work.

```
public synchronized void animateTo(long duration, BoundingBox bbox, Easing.Type easingType, int state) {
        ThreadUtils.assertMainThread();

        mMap.getMapPosition(mStartPos);
        /* TODO for large distance first scale out, then in
         * calculate the maximum scale at which the BoundingBox
         * is completely visible */
        double dx = Math.abs(longitudeToX(bbox.getMaxLongitude())
                - longitudeToX(bbox.getMinLongitude()));

        double dy = Math.abs(latitudeToY(bbox.getMinLatitude())
                - latitudeToY(bbox.getMaxLatitude()));

        log.debug("anim bbox " + bbox);

        double zx = mMap.getWidth() / (dx * Tile.SIZE);      //mMap.getWidth() returns 0 (zero)
        double zy = mMap.getHeight() / (dy * Tile.SIZE);    //mMap.getHeight() returns 0 (zero)
        double newScale = Math.min(zx, zy);              //newScale is 0 (zero) and thus smaller than smallest allowed scale (which is 4)

        GeoPoint p = bbox.getCenterPoint();

        mDeltaPos.set(longitudeToX(p.getLongitude()) - mStartPos.x,
                latitudeToY(p.getLatitude()) - mStartPos.y,
                newScale - mStartPos.scale,
                -mStartPos.bearing,
                -mStartPos.tilt);

        animStart(duration, state, easingType);
    }
```

I found out that at the point we're calling this method, both mMap.getWidth(9 and mMap.getHeight() return 0. This leads to newScale being 0. This in turn is lower than the lowest allowed scale which is 4 (according to `org.oscim.map.Viewport.mMinScale`)

I believe that trying to set a scale of 0 leads to the observed "gray" tiles. When using other "animateTo" methods (especially the ones taking a GeoPoint and a scale as parameter), there is even code making sure that scale is never below 4.

I also believe that the root problem is that mMap does not return width or height at this point in code. I don't know what we ccan do about this. I assume that at the point of calling the map is not yet layouted/rendered and thus has not yet a width/height.

@devemux86 do you have any hint what we can do to solve this?

**Comment by eddiemuc** [comment] 2023-12-15 00:01
PR #15026 mitigates the problem by putting another map animation BEFORE the real bounds animation and post the bounds animation later in the GUI thread. This seems to be enough for the map to have width/height available, and thus the zoom-to-bounds seems to work. 

However, the fix is not too clean...

**Comment by devemux86** [comment] 2023-12-15 07:46
Do you call actions on the map before the map is initialized?

Can also try animateTo(MapPosition) with MapPosition.setByBoundingBox(BoundingBox, viewWidth, viewHeight).
In any case the map view must first have dimensions in order for map view size calculations to be able to work.

In app could also delay the animation call for some milliseconds if it is done before the map is initialized?

**Comment by eddiemuc** [comment] 2023-12-15 08:19
> Do you call actions on the map before the map is initialized?

Probably not at this point in code... but haven't investigated this further.

> Can also try animateTo(MapPosition) with MapPosition.setByBoundingBox(BoundingBox, viewWidth, viewHeight). In any case the map view must first have dimensions in order for map view size calculations to be able to work.

Thanks for this hint! MapPosition looks like a promising abstraction. For current problem it won't help much because (as you said) this method also needs to know map width and height.

> In app could also delay the animation call for some milliseconds if it is done before the map is initialized?

I found out that a simple "post" of the call towards UI thread apparently solves the problem. So apparently at point of calling some map actions (leading to calculation of map width/height) are already queued. if this proves to solve the problem for good, I think it is a valid solution. See PR #15026

Thanks a lot for your helpful pointers!

**Comment by devemux86** [comment] 2023-12-15 08:46
@eddiemuc 

> I found out that a simple "post" of the call towards UI thread apparently solves the problem.

This internally calls MapView.post(Runnable) so it could also work.
There is also Map.postDelayed in case you ever need it.

**Comment by moving-bits** [comment] 2023-12-17 21:40
Cannot reproduce it any longer since the fix made by @eddiemuc, thus I propose to close it as fixed.

**Closed** 2023-12-17 23:02 UTC
Labels: Map: Unified
