### ISSUE TITLE
Allow County specification in Location

### ISSUE THREAD

**Issue by B2Pi** [cgeo/cgeo#11502] opened 2021-08-19 17:10 UTC
### Tell us your idea!

Currently, the Location field of the cache details page shows "State Country" (or simply Country in cases where there are no states). There are often times when one might wish to see County (or whatever the next level down from State might be called)

### What solution would you suggest?

1.) There should be a new configuration option - Settings - Cache Details - Display 3rd Location Level
2.) Having the above set would enable Location to be displayed as "County State Country" (or County Country where countie's exist, but states do not)

### Is there an alternative?

Right now, I do a manual reverse geocode of the cache coordinates

**Comment by Lineflyer** [comment] 2021-08-19 17:19
Duplicate of #4457

**Closed** 2021-08-19 17:19 UTC
Labels: Feature Request, Unverified
