### ISSUE TITLE
[new Filter] Remove Map Viewer Filter from Map-Quick-Settings

### ISSUE THREAD

**Issue by eddiemuc** [cgeo/cgeo#10659] opened 2021-05-17 11:59 UTC
> I would definitely prefer to have the new filter in the map (overflow) menu

Yep, like the overflow menu idea, too - and in fact this was the second place where I tried to find it.

> [Indicator for a "Filter active" in Map View]
> You could simply reuse the existing "filter active" hint which is shown on map currently if a global cache type filter is active

Thx for the link! I knew I had seen it somewhere, but could remember where.  ;)
Is there a special reason why this has not been used for the "classic" filters so far?

_Originally posted by @MagpieFourtyTwo in https://github.com/cgeo/cgeo/issues/10575#issuecomment-842247169_

**Comment by eddiemuc** [comment] 2021-05-17 12:00
@Lineflyer,  @MagpieFourtyTwo: one remaining question: at what position in the overview menu would you like to have the filter entry placed?

![image](https://user-images.githubusercontent.com/6909759/118485078-3ae33900-b718-11eb-9f10-7d1a145cb88d.png)

**Comment by Lineflyer** [comment] 2021-05-17 12:23
Good question:
BTW: The screenshot you posted is a rather special one for a map of a single cache.

Anyway:
I would place it rather prominent so that is has chances (on devices with larger screen or higher density) to be shown as icon. I would suggest behind "Enable/Disable live" with the option "Show if room"!?

**Comment by Lineflyer** [comment] 2021-05-17 12:23
Addition:
But it makes no sense if the map is opened for a single cache. Shouldn't the filtering be hidden in that case (unless live mode is enabled in addition)?

**Comment by eddiemuc** [comment] 2021-05-17 12:35
> Addition:
> But it makes no sense if the map is opened for a single cache. Shouldn't the filtering be hidden in that case (unless live mode is enabled in addition)?

Well yes. Although I am personally not a friend of such ever-changing menues.

But if this is so important: shouldn't then also the filtering options in the quick settings vanish on single-cache-view?

**Comment by Lineflyer** [comment] 2021-05-17 12:42
> But if this is so important: shouldn't then also the filtering options in the quick settings vanish on single-cache-view?

You are right...these also only make limited sense.
But then for the sake of simplicity: Lets not do any hiding of the menu entries just because they will probably not be useful. Just forget my addition :)

**Comment by fm-sys** [comment] 2021-05-17 15:26
I would place it directly after the map source selector or even before that...

**Comment by Lineflyer** [comment] 2021-05-17 15:29
> I would place it directly after the map source selector or even before that...

Maybe better behind..quite some users changing their maps frequently (Google Maps overview, OSM deep dive for small paths).

**Comment by MagpieFourtyTwo** [comment] 2021-05-17 20:12
BTW: While looking for a daily this afternoon I most surprisingly saw no caches at all in the map, just Parking and Stage waypoints - although I was pretty sure to have disabled my test filter ... switched back to list view to cross-check, and there was none, for real. Took a while until I realized that the map seems to have it's own filter, which is completely independent from the filter defined in the list view!

I of course like the versatility of being able to set different filters for lists and map, but does this really make sense?
And, even more important, will Joe Average be able to handle this?

Another strange scenario: Set up a map filter ``Name Contains huhu``, then go to a list and filter for ``Status = [Only Not Found]``, then click the map icon - the caches which have been shown after filtering the list will be displayed (expectedly) - nevertheless, the map filter still says ``Name:huhu`` ...?

**Comment by Lineflyer** [comment] 2021-05-17 20:22
@MagpieFourtyTwo Please feel free to open up new issues for new findings. I transferred your last paragraph into a new issue.

**Comment by Lineflyer** [comment] 2021-05-17 20:26
> I of course like the versatility of being able to set different filters for lists and map, but does this really make sense?
And, even more important, will Joe Average be able to handle this?

That was the reason I opened  #10661 (that issue now also contains unrelated stuff...we really need to separate topics more cleanly to keep the overview ..my fault in that issue).

**Comment by eddiemuc** [comment] 2021-05-19 06:00
I did add the filter to the overflow menu, but did not remove it from the `MapSettingsUtils`. So I keep this issue open for the removal part.

Strange, I was almost sure there were also voices wanting it to keep it there but I am unable to find them. Must be a false memory.

**Comment by MagpieFourtyTwo** [comment] 2021-05-19 22:50
> Strange, I was almost sure there were also voices wanting it to keep it there but I am unable to find them. Must be a false memory.

I guess, this was me - I like(d) to see the filter and it's definition in the popup, cause
a) it is in fact a quick setting, thus would make perfect sense over there, esp. as ``Show archived [_]`` etc. are just filters, too,
b) it is/was good to see the filter definition in short (which is now kind of outdated, as it is displayed in the map itself)
c) I have plenty of screen space anyway ...  ;)

However, I would be fine with the overflow menu, too.
Although ... wasn't it said that it should go to the overflow with the "if not enough room" option?
Cause over here there would be plenty of room in the header row, so I would in fact like to see the filter symbol there, like in lists.

**Comment by eddiemuc** [comment] 2021-05-20 05:51
@MagpieFourtyTwo I am almost certain I used the ifRoom option, and I dimly remember that filter moves to bar when I turn my phone. But I agree, in upright mode the bar seems to be unable to show more than 2 icons.

(I also removed the "with text" flag for map layer selection)

**Comment by fm-sys** [comment] 2021-05-20 06:04
This might be helpful:
https://stackoverflow.com/questions/15917973/showasaction-ifroom-doesnt-show-the-item-even-when-there-is-plenty-of-room

**Comment by MagpieFourtyTwo** [comment] 2021-05-20 09:06
> (I also removed the "with text" flag for map layer selection)

This might do the trick - cause with text it's indeed too wide to fit into the portrait header bar.

BTW (already apologizing, as this is in fact kind of off topic, but it's most probably just a quick question):
Had a somewhat surprising effect the day before yesterday day, I can not reproduce anymore:
1. in Live Map defined a filter ``Description:ladder``
2. open the listing of a "normal" cache (i. e. with no "ladder" in the description)
3. "Show Cache in Map" (by clicking the wind rose)
4. ``Enable live`` => the cache I came from vanished from map
5. ``Disable live`` => the cache I came from shows up again

I of course understand the logic which led to this behavior, but it seems to work now - or am I wrong?
Have you changed s/th w/ regard to this scenario?
If so, I most probably missed s/th which may be worth testing, I guess ...

**Closed** 2021-05-22 17:59 UTC

**Comment by MagpieFourtyTwo** [comment] 2021-05-22 22:03
Just upgraded to 2021.05.22-NB1-179e29d - and with this version I expected the text ``Filter (experimental`` to be removed from the live map's filter icon, as well as the icon itself should appear in the live map's header (if there's enough room, like on my screen, I guess) - or do I get s/th wrong? Cause the text is still there and the icon does not appear in the header row, neither.

**Comment by eddiemuc** [comment] 2021-05-23 07:47
@MagpieFourtyTwo I suppose you mean this?
![image](https://user-images.githubusercontent.com/6909759/119252275-8fb90080-bbab-11eb-812c-5d6c5825effe.png)

Apologies, completely forgot about that. I will remove the text as part of the fix/PR for "lost advanced setting on rotation". 

Also I can try a first hack for keeping it in header row even when Android itself thinks there is not enough room. (@fm-sys's link contains an interesting idea of calculating the remaining room ourself). Can't promise there won't be side effects though!

**Comment by eddiemuc** [comment] 2021-05-23 09:16
fixed with PR #10723.
Note that the wish to force-add filter icon to action bar against the "will" of android is somehow hacky. I now implemented that the filter icon is force-added to action bar if map is either in live-mode or shows things from db (in other words: not just a single cache) and the screen is wider than 390dp (this is a gut-guess currently!)

There might be new problems coming up because of this. Please open new issues for those.

**Comment by fm-sys** [comment] 2021-05-28 19:31
> Note that the wish to force-add filter icon to action bar against the "will" of android is somehow hacky. I now implemented that the filter icon is force-added to action bar if map is either in live-mode or shows things from db (in other words: not just a single cache) and the screen is wider than 390dp (this is a gut-guess currently!)

Is it already implemented?

Ok, I just calculated - my device has a screen wide of 360dp 😥 Could you lower this "magic border" as I can tell you that on my device there is still way more than enough space left...
