### ISSUE TITLE
Crash in CacheDetailActivity.onCreateContextMenu

### ISSUE THREAD

**Issue by rhubert** [cgeo/cgeo#5429] opened 2016-01-30 20:40 UTC
To reproduce:
1) open gc4vchp
2) go to waypoints
3) long click on (D-A-E-C) 

There is no crash if any other action is done. For example open another waypoint, close it and do long click on (D-A-E-C) -> you'll get the menu.

I tested this with the latest nightly 2016.01.30-NB3 and with some older development build.

```
01-30 21:33:33.772 8859-8859/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                 Process: cgeo.geocaching, PID: 8859
                                                 java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String cgeo.geocaching.models.Waypoint.getName()' on a null object reference
                                                     at cgeo.geocaching.CacheDetailActivity.onCreateContextMenu(CacheDetailActivity.java:435)
                                                     at android.view.View.createContextMenu(View.java:9216)
                                                     at android.view.View.createContextMenu(View.java:9224)
                                                     at com.android.internal.view.menu.ContextMenuBuilder.show(ContextMenuBuilder.java:81)
                                                     at com.android.internal.policy.impl.PhoneWindow$DecorView.showContextMenuForChild(PhoneWindow.java:2671)
                                                     at android.view.ViewGroup.showContextMenuForChild(ViewGroup.java:694)
                                                     at android.view.ViewGroup.showContextMenuForChild(ViewGroup.java:694)
                                                     at android.view.ViewGroup.showContextMenuForChild(ViewGroup.java:694)
                                                     at android.view.ViewGroup.showContextMenuForChild(ViewGroup.java:694)
                                                     at android.view.ViewGroup.showContextMenuForChild(ViewGroup.java:694)
                                                     at android.widget.AbsListView.showContextMenuForChild(AbsListView.java:3173)
                                                     at android.view.ViewGroup.showContextMenuForChild(ViewGroup.java:694)
                                                     at android.view.View.showContextMenu(View.java:4929)
                                                     at android.view.View.performLongClick(View.java:4898)
                                                     at android.widget.TextView.performLongClick(TextView.java:8731)
                                                     at android.view.View$CheckForLongPress.run(View.java:19930)
                                                     at android.os.Handler.handleCallback(Handler.java:739)
                                                     at android.os.Handler.dispatchMessage(Handler.java:95)
                                                     at android.os.Looper.loop(Looper.java:211)
                                                     at android.app.ActivityThread.main(ActivityThread.java:5389)
                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                     at java.lang.reflect.Method.invoke(Method.java:372)
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1020)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:815)
```

**Comment by rsudev** [comment] 2016-01-30 21:49
sounds like the lazy-loading of waypoints doesn't work correctly...

**Comment by Bananeweizen** [comment] 2016-01-31 13:26
nope, our handling of context menus is bad. we try to remember the waypoint selection in listeners of the list, then delegate to the activity context menu handling, and use the remembered waypoint there. this needs to be cut into different pieces

**Comment by rsudev** [comment] 2016-01-31 13:35
This is likely an ingredient.
I also made some interesting observations:
* You cannot invoke the context menu by long-pressing on the descriptions of the waypoints in view initially. This works only for those scrolled into visibility
* If you invoke the context menu through a long press on the waypoint name, it even works for those scrolled into view

This is kind of weird...

**Comment by Lineflyer** [comment] 2016-03-17 22:21
I wanted to take a closer look on this, however for GC4VCHP I do not see anything like (D-A-E-C) within the waypoints. Am I missing somehting?

**Comment by rahu** [comment] 2016-03-18 04:56
Description text of waypoint "tafel"

![screenshot_2016-03-18-05-50-29](https://cloud.githubusercontent.com/assets/937126/13868894/035df30e-ecce-11e5-9d78-b009c006a5c7.png)

**Comment by Lineflyer** [comment] 2016-03-18 12:05
Thanks. Can reproduce.

**Comment by Lineflyer** [comment] 2017-08-28 15:49
Still reproducibel with 2017.08.26-NB

**Comment by fm-sys** [comment] 2021-01-05 09:51
Cannot reproduce the issue anymore. Therefore closing it...

**Closed by fm-sys** 2021-01-05 09:51 UTC
Labels: Bug
