### ISSUE TITLE
Lenovo map problem

### ISSUE THREAD

**Issue by gmw1971** [cgeo/cgeo#4812] opened 2015-03-31 12:07 UTC
Using cgeo on both the Lenovo A8-50 and Yoga 10 tablets is not possible. Get a line of cache icons and a messed up map. Seems to be a continuation of a previously flagged problem. Any idea how to fix it (either at user end or software update)?
Thanks

**Comment by SammysHP** [comment] 2015-03-31 13:27
Duplicate of  #4097. You can use the nightly build with disabled JIT compiler.

http://ci.cgeo.org/job/c-geo-nightly-nojit/ws/main/bin/cgeo-release.apk

**Closed by SammysHP** 2015-03-31 13:27 UTC
