### ISSUE TITLE
Strings mixed up in Settings-System menu

### ISSUE THREAD

**Issue by andrixnet** [cgeo/cgeo#5592] opened 2016-03-28 07:30 UTC
Settings -> System. 
Section : Low power mode.
The description string shows:

> "Please note that this feature will backup/restore a database containing caches and waypoints, but not your settings. Your login data and passwords will never leave this application."

**Comment by andrixnet** [comment] 2016-03-28 07:31
Settings -> Ssystem.
Section: orientation sensor
The description string shows: 

> You may store the databsae of c:geo on your external storage medium. Doing so will save internal memory, but you may lose a bit of performance and c:geo will not work if your SD card isn't available.

**Comment by andrixnet** [comment] 2016-03-28 07:32
Settings -> System
Section : Hardware accelerated rendering
Description shows: 

> c:geo store images, log images and other files related to a cache in a separate directory. In some cases (like importing/exporting the databse) this directory may contain outdated files, which can be deleted)

**Comment by andrixnet** [comment] 2016-03-28 07:33
Settings - System
Section Backup
Description shows:

> On devices with Google Play Services, c:geo can automatically use a better geolocation provider. However this prevents the use of an externa BlueTooth GPS receiver

**Comment by andrixnet** [comment] 2016-03-28 07:35
Settings -> System
Section : Geolocation
Description shows:

> Please note that this feature will backup/restore a database containing caches and waypoints, but not your settings. Your login data and passwords will never leave this application.
> 
> There is no file with a backup

**Comment by andrixnet** [comment] 2016-03-28 07:44
Even more wierd, as I am writing information for this issue, I am viewing (without changing) the Settings -> System page and scrolling up and down, it seems that the description field for various sections change. After scrolling a bit, the Low Power mode section now reads the description which properly belongs to Geolocation section. (previously it showed the description for Backup section)

**Comment by andrixnet** [comment] 2016-03-28 07:44
Only System ppage seems to be affected.

**Comment by samueltardieu** [comment] 2016-03-28 09:15
Which version?

**Comment by andrixnet** [comment] 2016-03-28 09:20
2016.03.06. Installed on freshly reset Android 4.2.1 phone on saturday.

**Comment by Lineflyer** [comment] 2016-03-29 14:06
@andrixnet 
Did you maybe force c:geo to english without force closing/restarting it afterwards?
Is this still reproducible also after restart?

**Comment by andrixnet** [comment] 2016-03-30 08:49
English not forced. (unchecked, never touched it). 
Same problem after restart, including phone reboot.

**Comment by SammysHP** [comment] 2016-03-30 10:09
Have you tried the no-jit build?

**Comment by andrixnet** [comment] 2016-10-26 14:50
I am using the official release via Google Play.

**Comment by andrixnet** [comment] 2016-10-26 14:51
Screenshots showing the issue described.

![screenshot_2016-10-26-15-11-38](https://cloud.githubusercontent.com/assets/3382777/19731019/bb49f8c0-9ba4-11e6-8a27-7380ead684e7.png)

![screenshot_2016-10-26-15-11-54](https://cloud.githubusercontent.com/assets/3382777/19731020/bb4c18f8-9ba4-11e6-805c-97e375b446b4.png)

**Comment by Lineflyer** [comment] 2016-10-26 17:01
Please try disabling HW acceleration in cgeo settings....just guessing.

**Comment by andrixnet** [comment] 2016-10-26 17:37
HW accel is disabled

**Comment by Lineflyer** [comment] 2016-10-26 18:52
And I guess if you enable it, it does not make a change either?!

**Comment by SammysHP** [comment] 2016-10-26 19:07
Half a year later and still the same problem?! Seems like you're the only one. Strange.

**Comment by andrixnet** [comment] 2016-10-27 06:06
@Lineflyer : you are guessing correctly.
@SammysHP : or maybe the only one to notice it and report it. 

It doesn't seem to happen in any other category under Settings, only System.
I haven't seen anything like that with any other app on the same device.

**Comment by Lineflyer** [comment] 2017-01-09 20:07
@andrixnet You could now also try the release version like NOJIT build and report back:
http://www.cgeo.org/faq.html#osm-mediatek-problem

**Comment by Lineflyer** [comment] 2017-02-21 22:07
Closing due to lack of feedback.
Feel free to comment and reopen.

**Comment by andrixnet** [comment] 2017-02-24 08:28
Sorry, missed it. 
Request reopen. See screenshots with non-JIT build:
![screenshot_2017-02-24-09-00-22](https://cloud.githubusercontent.com/assets/3382777/23296025/f4ad6a62-fa7b-11e6-924b-c8103f4be1c4.png)
![screenshot_2017-02-24-09-00-31](https://cloud.githubusercontent.com/assets/3382777/23296033/fdb1b19a-fa7b-11e6-8387-194487ce2fd5.png)

**Comment by andrixnet** [comment] 2017-03-04 21:46
Question: I installed the non-JIT nightly build to test this. Afterwards I wanted to revert back to the release build (restore from backup using Titanium Backup). c:geo crashes on start.

How to I revert from nightly to release without an uninstall (I want to keep all my settings and authorizations)?

**Comment by SammysHP** [comment] 2017-03-04 22:25
Usually it is not possible to downgrade from a nightly to a release version due to database and configuration changes. That's why we provide also a no-jit version that is based on release.

Your backup should include the database except for the case that you selected to store the database on the external storage.

**Comment by andrixnet** [comment] 2017-03-05 20:23
Yes, it is on external storage. 
Will it be possible to return to release channel with the next release version? (as it being a later build then currently installed nightly)

**Comment by pstorch** [comment] 2017-03-05 20:27
That might be possible, if it is the next feature release.

To be on the safe side: backup when on release, then test nightly. When going back to release restore the backup. Changes made during nightly test are gone then of course.

**Comment by pstorch** [comment] 2017-03-21 21:48
@andrixnet can you test again with next nightly? I've done some changes on the SettingsActivity during another issue. Maybe this affects this as well.

**Comment by andrixnet** [comment] 2017-03-22 09:20
Just tested with 2017.03.22-NB-470aeae (no-JIT)
Problem persists.

**Comment by pstorch** [comment] 2017-03-22 09:53
Ok, thanks for testing.

**Comment by Lineflyer** [comment] 2017-05-11 11:07
@andrixnet 
Not, that I would have any news for this, but can you post the system information (from "About c:geo") for the device where this happens into this issue. Do I could possibly try to find a similar device or have some more clues in case other users with this problem come along.

**Comment by andrixnet** [comment] 2017-05-11 12:07
--- System information ---
Device: Q800 (XOLO, XOLO)
Android version: 4.2.1
Android build: Q800
Cgeo version: 2017.03.29
Google Play services: enabled - 10.2.98 (034-146496160)
Low power mode: inactive
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: rotation vector
Hide own/found: false
Map strategy: auto
HW acceleration: disabled (default state)
System language: en_US
System date format: E, MMM d, yyyy
Debug mode active: no
Fine location permission: granted
Write external storage permission: granted
Geocaching sites enabled:
geocaching.com: Logged in (Login OK) / BASIC
opencaching.ro: Logged in (Login OK)
Geocaching.com date format: yyyy-MM-dd
Installed cgeo plugins: none
--- End of system information ---

**Comment by andrixnet** [comment] 2017-05-11 12:08
MTK based CPU. 
See: http://allview.ro/p5-quad.html
http://www.gsmarena.com/allview_p5_quad-6029.php

**Comment by andrixnet** [comment] 2017-05-11 12:09
Initial ROM was 4.1.2. 
Official upgrade and also XOLO Q800 (same device, different brand) ROM at Android 4.2.1.
Regardless of ROM used, I see the same issue in c:geo.

**Comment by SammysHP** [comment] 2017-05-11 12:30
As the resources are correct, the code has not many possibilities for failures and it works for most users, I'd like to close this as "won't fix". There is nothing we can do. I assume that there is something wrong with caching of the views or resources in that ROM (or optimization of the code) that is just broken.

**Comment by andrixnet** [comment] 2017-05-11 20:14
I understand. Fortunately it is the only part affected by this and otherwise it does not impair functionality.
I will monitor other devices for this issue and request reopen should it surface on other devices.

Thank you.

**Comment by Lineflyer** [comment] 2018-02-26 14:41
We have a user on support mail with the same problem:
```
--- System information ---
Device: F5121 (F5121, Sony)
Android version: 8.0.0
Android build: 34.4.A.0.364
c:geo version: 2018.02.05
Google Play services: disabled - 11.9.75 (448-182402865)
Low power mode: inactive
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: rotation vector
Hide own/found: false
Map strategy: auto
HW acceleration: enabled (default state)
System language: de_DE
System date format: dd.MM.yy
Debug mode active: no
System internal c:geo dir: /data/user/0/cgeo.geocaching (10,8 GB free) internal
User storage c:geo dir: /storage/emulated/0/cgeo (10,8 GB free) external non-removable
Geocache data: /storage/emulated/0/Android/data/cgeo.geocaching/files/GeocacheData (10,8 GB free) external non-removable
Database: /data/user/0/cgeo.geocaching/databases/data (311,7 MB) on system internal storage
Fine location permission: granted
Write external storage permission: granted
Geocaching sites enabled:
geocaching.com: Logged in (Anmeldung OK) / PREMIUM
Geocaching.com date format: yyyy-MM-dd
Installed c:geo plugins: none
--- End of system information ---
```
![screenshot_20180226-124319](https://user-images.githubusercontent.com/949669/36676276-8677d1c0-1b0b-11e8-9071-6e58c5278da5.png)

**Comment by andrixnet** [comment] 2018-02-26 17:52
According to https://www.gsmarena.com/sony_xperia_x-7948.php the device has non-MTK processor.

**Comment by Lineflyer** [comment] 2018-02-27 10:13
I asked the user to provide screenshots of the whole settings/system menu.

Here is what it looks like:
The problem somehow starts in the positioning menu.
![screenshot_20180226-214241](https://user-images.githubusercontent.com/949669/36722904-1bef84e8-1baf-11e8-98e4-e3ffdcf7796f.png)
![screenshot_20180226-214317](https://user-images.githubusercontent.com/949669/36722905-1c070924-1baf-11e8-8158-fb6eef299500.png)
![screenshot_20180226-214333](https://user-images.githubusercontent.com/949669/36722902-1bb9a8fa-1baf-11e8-9d7d-abc82df065c3.png)
![screenshot_20180226-214355](https://user-images.githubusercontent.com/949669/36722903-1bd4d85a-1baf-11e8-8c5a-5f4033c32191.png)

**Comment by Lineflyer** [comment] 2018-02-27 10:16
Afterwards the user changed the font size setting of his devices and tried again, now with a different result.

![screenshot_20180226-214617](https://user-images.githubusercontent.com/949669/36723057-7cbb7b74-1baf-11e8-8c9f-5a883a77379a.png)
![screenshot_20180226-214631](https://user-images.githubusercontent.com/949669/36723058-7cd33048-1baf-11e8-9e19-543b89b765e4.png)
![screenshot_20180226-214644](https://user-images.githubusercontent.com/949669/36723052-7c6f1f7c-1baf-11e8-940a-9ec30c884745.png)
![screenshot_20180226-214655](https://user-images.githubusercontent.com/949669/36723055-7c898a42-1baf-11e8-8244-8c7b0e8528ff.png)
![screenshot_20180226-214703](https://user-images.githubusercontent.com/949669/36723056-7ca06988-1baf-11e8-87b1-2d9e2e14a9ae.png)

**Comment by Lineflyer** [comment] 2018-02-27 10:19
The user owns a second device of same model/type running with Android 7.1 and same c:geo versions,
The problem is only existing on the Android 8.0 device, the Android 7.1 device has normal menus.

**Comment by Bananeweizen** [comment] 2018-03-07 17:56
If I get it right, these errors always occur only for summaries of options, right? Those _are_ set by us dynamically when preferences change, so there is still a chance we are doing something wrong, even though I can't find any error.

**Comment by Lineflyer** [comment] 2018-03-12 15:01
Addon:
> The user owns a second device of same model/type running with Android 7.1 and same c:geo versions,
> The problem is only existing on the Android 8.0 device, the Android 7.1 device has normal menus.

Now the user updated this second device to Android 8.0 and it has now the same problem.

**Comment by Lineflyer** [comment] 2018-03-12 15:02
> If I get it right, these errors always occur only for summaries of options, right?

Correct.

**Comment by okainov** [comment] 2018-08-05 14:06
Copied screenshot and system info from #7095 

![image](https://user-images.githubusercontent.com/918446/43686633-81790d2e-98c9-11e8-8d29-f26d12b42189.png)

Version of c:geo used:
2018.08.05-NB-4a08c8a

System information:
--- System information ---
Device: SM-A320FL (a3y17ltexc, samsung)
Android version: 8.0.0
Android build: R16NW.A320FLXXU2CRE3
c:geo version: 2018.08.05-NB-4a08c8a
Google Play services: enabled - 12.8.74 (040306-204998136)
Low power mode: inactive
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: rotation vector
Hide own/found: true
Map strategy: auto
HW acceleration: enabled (default state)
System language: en (c:geo forced to English)
System date format: M/d/yy
Debug mode active: no
System internal c:geo dir: /data/user/0/cgeo.geocaching (745.8 MB free) internal
User storage c:geo dir: /storage/emulated/0/cgeo (725.8 MB free) external non-removable
Geocache data: /storage/3133-3335/Android/data/cgeo.geocaching/files/GeocacheData (6.7 GB free) external removable
Database: /data/user/0/cgeo.geocaching/databases/data (124.0 MB) on system internal storage
Fine location permission: granted
Write external storage permission: granted
Geocaching sites enabled:
geocaching.com: Logged in (Login OK) / BASIC
Geocaching.su
Geocaching.com date format: d. M. yyyy
Installed c:geo plugins: none
--- End of system information ---

**Comment by okainov** [comment] 2018-08-05 14:08
The same behavior is without forcing to English with normal English or Russian UI

**Comment by samueltardieu** [comment] 2018-08-05 16:03
When adding the closeout message for Android 4.1, I removed a string and added another (with a different id). Could it be that the CI does not properly clean (or have dependencies) its environment and mixed files?

**Comment by Lineflyer** [comment] 2018-08-05 16:05
It is happening (on some device) since a longer time, than your recent change.

**Comment by ajcampos** [comment] 2018-12-13 13:45
I have the same problem, but don't know when it started.

Using now OnePlus 6 with Android 9.

**Comment by Lineflyer** [comment] 2019-02-19 12:38
This issue was now reported by more users, who are using our current RC-version 2019.02.17-RC or later.
With the recent change this seems now to affect more/all users.

I can also now reproduce this error in 2019.02.18-NB

**Comment by ajcampos** [comment] 2019-02-19 16:12
I have now 2019.02.18-RC and the problem is still there.

**Comment by bekuno** [comment] 2019-02-25 22:19
It is ok for me on a Android 7.0 device, but not on Android 8.0.0.
The first wrong text is at "GEOLOCATION".

**Closed** 2019-03-17 10:01 UTC
Labels: Bug, Frontend Design, medium, sdk26-regression
