### ISSUE TITLE
IndexOutOfBoundsException in SimpleDialog

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#13578] opened 2022-10-30 09:56 UTC
Reported in Play Store for current release 2022.10.17:

```
Exception java.lang.IndexOutOfBoundsException: Index: 2, Size: 1
  at java.util.ArrayList.get (ArrayList.java:437)
  at cgeo.geocaching.ui.dialog.SimpleDialog.lambda$selectSingleGrouped$1 (SimpleDialog.java:340)
  at cgeo.geocaching.ui.dialog.SimpleDialog.lambda$selectSingleGrouped$1$SimpleDialog
  at cgeo.geocaching.ui.dialog.-$$Lambda$SimpleDialog$_BEHauIquqxXzy2ZLeBXkgZWqss.onClick
  at androidx.appcompat.app.AlertController$AlertParams$3.onItemClick (AlertController.java:1068)
  at android.widget.AdapterView.performItemClick (AdapterView.java:374)
  at android.widget.AbsListView.performItemClick (AbsListView.java:1736)
  at android.widget.AbsListView$PerformClick.run (AbsListView.java:4207)
  at android.widget.AbsListView$7.run (AbsListView.java:6692)
  at android.os.Handler.handleCallback (Handler.java:883)
  at android.os.Handler.dispatchMessage (Handler.java:100)
  at android.os.Looper.loop (Looper.java:237)
  at android.app.ActivityThread.main (ActivityThread.java:8167)
  at java.lang.reflect.Method.invoke
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:496)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1100)
```

More than 150 events since releasing the version (< 2 weeks).

**Comment by eddiemuc** [comment] 2022-10-30 11:36
Always hard to tell from those context-free exceptions what the cause actually is. I tried my best in PR #13580 to guess and solve the error.

Any context-related support messages on this? E.g. "when I clicked in a dialog, c:geo crashed"?

**Comment by moving-bits** [comment] 2022-10-30 12:22
Not that I can remember of.

From checking the first 60 reports in Play Console, `Index` is mostly 2, but never higher than 6. `Size` is up to 5.

One idea for a possible source, would explain the high number of occurrences (but not checked): We have log options for caches, with some default values per connector. The list of available options get updated in the background. So the entries in the selection list may still refer to the values set as default, but might be applied to the updated list (which may have less entries).

**Comment by eddiemuc** [comment] 2022-10-30 12:27
> One idea for a possible source, would explain the high number of occurrences (but not checked): We have log options for caches, with some default values per connector. The list of available options get updated in the background. So the entries in the selection list may still refer to the values set as default, but might be applied to the updated list (which may have less entries).

That's actually a very likely cause if the list of items is updated outside of the main thread (in the background) or while the "old" list is currently opened by the user.

**Comment by eddiemuc** [comment] 2022-10-30 13:06
Update: I could reproduce the scenario, will provide a fix

**Comment by eddiemuc** [comment] 2022-10-30 13:15
PR #13580 will now fix this issue

**Comment by fm-sys** [comment] 2022-11-01 07:26
Auto-closing didn't work as `fix #xxx` was placed in the PR description (instead of commit message) while targeting a branch != master. Therefore closing manually...

**Closed by fm-sys** 2022-11-01 07:26 UTC
Labels: Google Play or Beta feedback

**Comment by fm-sys** [comment] 2022-11-01 07:34
Woops. `fix #xxx` was actually part of the commit message. However, `release` wasn't merged back to `master`. 

Please always do this directly after merging a PR to release, so we can test fixes the nightlys.

Another hint: If you don't feel comfortable with merging via command line or you don't have a PC at hand, you can do this via the Github webUI as well. Just execute our self-created workflow:

https://github.com/cgeo/cgeo/actions/workflows/branch-merge.yml
