### ISSUE TITLE
list limit - change max value in settings

### ISSUE THREAD

**Issue by bekuno** [cgeo/cgeo#11191] opened 2021-07-12 10:22 UTC
The list limit has currently the maximum amount of 5000.
This should be a higher value, I would suggest to set it at least to 10000.

**Comment by moving-bits** [comment] 2021-07-12 18:28
Thinking of lists like "history" or "all" we should set the limit even higher...

**Comment by MagpieFourtyTwo** [comment] 2021-07-12 22:29
Over here "Unlimited" is working perfectly fine since the change to SQL-based filtering:
Not even a single crash (at least not reproducibly "long list related" ;) ) and stunningly fast (4 secs to display/filter "All").
And as I have about 20k caches stored offline, I would consider at least 20k (if not even more) as save ...
Thus a max value of even way more than 20k (50k?) would make sense, IMO
(e. g. to be able to test for the limits, if "Unlimited" gives problems somewhere).

**Comment by eddiemuc** [comment] 2021-07-13 06:00
@MagpieFourtyTwo I am glad it works so well. I am also a bit surprised because the change to SQL-based filtering did of course not reduce the amount of caches loaded into memory or the number of SQLs executed in background for it (and I always assumed this was the source of the slowness...). So I wonder where the slowness came from :-) Maybe from in-memory-sorting, but that is very far-fetched.

To the initial issue: the max value for "max limit" should not be measured against the max. list sizes our users use but against **the max. size of items on a list which the user would really read manually** (without adding an additional filter or sort because it is too much for him to read through). The whole feature should limit loading too much into memory and sparing the DB many unnecessary SQL statements. 

I think 10K would be ok, maybe even 20K, but for higher values the feature does not make sense any more anyway. If users really want to deal with unlimited 20K+ lists and load them into memory at a single tap, then they are allowed to do so (by deactivating max limit).

**Comment by fm-sys** [comment] 2021-07-13 07:17
> Maybe from in-memory-sorting, but that is very far-fetched.

Could likely be. Sorting is a quite expensive task. Depending on the sorting algorithm we use the sorting time can be much faster if the list is already presorted...

**Comment by eddiemuc** [comment] 2021-07-13 07:24
> > Maybe from in-memory-sorting, but that is very far-fetched.
> 
> Could likely be. Sorting is a quite expensive task. Depending on the sorting algorithm we use the sorting time can be much faster if the list is already presorted... 

Yes, but we're talking about 10+ seconds for lists of maybe 50K items... This is too much to be explained by sorting Algo imho. I believe Java SDK uses an adapted version of mergesort

**Comment by MagpieFourtyTwo** [comment] 2021-07-17 22:35
@eddiemuc
I suggested 50k to be able to test out the sweet spot, i. e. finding the critical quantity.
To be able to do so, 10k is way too low, cause this can easily be handled by the current implementation.
And the step from 10k to Unlimited is too big, IMO - thus I would again suggest 50k as mx value, to be able to test.

As for sorting: AFAIK, Java's "normal" sort function does not use mergesort by default - to really get it, you must call it explicitly (while timsort would perhaps be even faster ;) ). BUT, although mergesort is way faster (O(n log n) vs. O(n²)) it most regretfully has a really bad space complexity of O(n) (vs. O(1) resp. O(log n)) - and WRT the heavily limited resources of a mobile phone ...

TMALSS: I would agree with @fm-sys that sorting was the main issue over here.

**Comment by eddiemuc** [comment] 2021-07-18 05:19
Out of interest I looked it up, Java does indeed use TimSort by default: https://docs.oracle.com/javase/7/docs/api/java/util/Collections.html#sort(java.util.List)

For some reason however, in SDK8 the search Algo used is no longer specified in the java doc. Don't know if this means they have changed it.

**Comment by fm-sys** [comment] 2021-07-18 07:27
> I suggested 50k to be able to test out the sweet spot, i. e. finding the critical quantity.
> To be able to do so, 10k is way too low, cause this can easily be handled by the current implementation.
> And the step from 10k to Unlimited is too big, IMO - thus I would again suggest 50k as max value, to be able to test (on low and mid range hardware).

And can we please use 100s steps for the slider? Cause nobody will ever set their limit to e.g. 2627 and I know quite some people (me included ;)) who will be really triggered by the fact that the limit is set to such a strange number 😅

**Comment by eddiemuc** [comment] 2021-07-18 08:10
> And can we please use 100s steps for the slider?

IIRC the slider used in settings is self-written. I am not sure if it supports steps

**Comment by eddiemuc** [comment] 2021-07-18 08:21
@murggel this is not directly filter-related, but should be something easy to fix (the max. value)

**Comment by fm-sys** [comment] 2021-07-18 08:33
> I am not sure if it supports steps

Probably not yet. But can be added for sure ;-)

**Comment by eddiemuc** [comment] 2021-07-18 09:19
> > I am not sure if it supports steps
> 
> Probably not yet. But can be added for sure ;-)

I wouldn't invest too muc here since we want to replace Settings anyway. But if you really want to tackle this, I would recommend replacing this with a material.io slider.

**Comment by murggel** [comment] 2021-07-18 20:45
@eddiemuc, @MagpieFourtyTwo did I understand you correct with changing the max to 50k?

**Comment by murggel** [comment] 2021-07-18 20:46
I would leave supporting steps / changing to material.io slider because settings will hopefully changed soon via #10579

**Comment by MagpieFourtyTwo** [comment] 2021-07-18 21:06
> @eddiemuc, @MagpieFourtyTwo did I understand you correct with changing the max to 50k?

As far as I'm concerned, yes. I suggested the 50k to be able to test out the working max, just in case it doesn't work in some special (hardware) environments resp. with *really* many offline saved caches.

As for steps: since it is also possible to enter the exact number by hand (after clicking on the number itself), I wouldn't invest in implementing steps anyway.

**Comment by murggel** [comment] 2021-08-01 10:22
@MagpieFourtyTwo  when you are done with testing and found / agreed to a value for the max list size, let me know, I will adapt the setting then.

**Comment by MagpieFourtyTwo** [comment] 2021-08-01 16:40
@murggel 
>  when you are done with testing and found / agreed to a value for the max list size, let me know, I will adapt the setting then.

Sorry, but I'm out here, at least for the moment being, as I have stored "just" 20 k offline ... and with 20 k it's working like a charm, at least on my hardware. IOW: To check out the limit. we need testers with either way more caches stored or "weaker" hardware.

In fact, I had in mind to a) set the default for the limit to "Unlimited", but b) leave the slider as it is, as a tool for @Lineflyer, so he can ask these people who might eventually contact support after they ran into trouble because of the "Unlimited", to ask these guys to test out the maximum working number ...

**Comment by murggel** [comment] 2021-08-01 18:47
@Lineflyer shall I close then this issue and you reopen it or create a new one, if we need a different max value?

**Comment by bekuno** [comment] 2021-08-01 19:23
I have ~8s for ~20.000 caches on my Samsung Note 8.
Therefore I propose to let the list_load_limit_max at 50.000 and set the list_load_limit_default to 10.000 .

**Comment by Lineflyer** [comment] 2021-08-01 19:59
@murggel I took the amount out of the issue title. 
The consensus at the end defines the solution :)

BTW: No opinion form my side. I usually have max of 4k caches on all lists in total.

**Comment by MagpieFourtyTwo** [comment] 2021-08-01 20:16
> I have ~8s for ~20.000 caches on my Samsung Note 8.

Wow - would not have expected such a difference ... over here just a little more than 3 secs for 20k caches on Huawei P30 Pro ...

**Comment by murggel** [comment] 2021-08-01 20:18
> I have ~8s for ~20.000 caches on my Samsung Note 8.
> Therefore I propose to let the list_load_limit_max at 50.000 and set the list_load_limit_default to 10.000 .
> 

I would leave the default to unlimited and user can set it to a lower value if he has problems, see discussion in #11132.
Probably we should add then an entry in FAQ

**Comment by murggel** [comment] 2021-08-01 20:19
> @murggel I took the amount out of the issue title

Ok


> The consensus at the end defines the solution :)
> 
> BTW: No opinion form my side. I usually have max of 4k caches on all lists in total.

@Lineflyer I mentioned you in cases for user feedback

**Comment by murggel** [comment] 2022-06-05 21:16
@Lineflyer can we close this issue?

**Comment by Lineflyer** [comment] 2022-06-05 23:03
Yes, no issues reported, so unlimited seems to be fine for most users.

**Closed** 2022-06-05 23:03 UTC
Labels: Feature Request
