### ISSUE TITLE
Distance Circles Missing after map type switch

### ISSUE THREAD

**Issue by wolverine007** [cgeo/cgeo#9618] opened 2020-12-28 22:42 UTC
With 2020.12.22-RC or even longer I am facing the following issue:

during a map type switch from offline OSM to Goggle Maps, the 161m circles circles are completely not shown.
 
I have to unselect this option inside the quick settings menu and leave the menu. Reopen the menu and enable them again, so they are shown on the map again. 

Please check if something in the load routine must be adjusted, cause for the switch between Google maps and offline OSM it is working every time without any issue.

Thanks,
wolv

**Comment by moving-bits** [comment] 2020-12-28 22:49
Duplicate of #9108?

**Comment by wolverine007** [comment] 2020-12-28 23:00
> Duplicate of #9108?

It seems that you are right, missed to find this one related to the used abbreviation GM instead of Google Maps o.O

**Closed** 2020-12-28 23:02 UTC
Labels: Bug, Unverified
