### ISSUE TITLE
Log with attached image returns upload failure although successful

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#12673] opened 2022-02-04 21:06 UTC
### Describe your problem!

On support we have two new tickets stating, that on logging with an attached picture c:geo returns an error, even on several retries. But when they check online with their browser, the log got sent.

Both tickets are about logs with attached images, don't know yet whether the error message also occurs if no image is attached (but I sort of doubt it, otherwise we would have tons of support tickets).

Logcat does not show any related errors for them.

I tried to reproduce this from within the emulator, and I'm not able to send a log at all, I always get an "unknown error". Logcat lists this:
```
2022-02-04 21:45:15.791 17728-17975/cgeo.geocaching E/cgeo: [AsyncTask #2] Error posting log
    java.lang.RuntimeException: java.io.IOException: request was not successful: Response{protocol=http/1.1, code=400, message=Bad Request, url=https://www.geocaching.com/api/proxy/web/v1/geocache/gc12345/GeocacheLog}
        at io.reactivex.rxjava3.internal.util.ExceptionHelper.wrapOrThrow(ExceptionHelper.java:46)
        at io.reactivex.rxjava3.internal.observers.BlockingMultiObserver.blockingGet(BlockingMultiObserver.java:94)
        at io.reactivex.rxjava3.core.Single.blockingGet(Single.java:3645)
        at cgeo.geocaching.connector.gc.GCWebAPI.postLog(GCWebAPI.java:926)
        at cgeo.geocaching.connector.gc.GCLoggingManager.postLog(GCLoggingManager.java:137)
        at cgeo.geocaching.log.LogCacheActivity$Poster.doInBackgroundInternal(LogCacheActivity.java:687)
        at cgeo.geocaching.log.LogCacheActivity$Poster.doInBackgroundInternal(LogCacheActivity.java:671)
        at cgeo.geocaching.utils.AbstractAsyncTaskWithProgress.doInBackground(AbstractAsyncTaskWithProgress.java:134)
        at android.os.AsyncTask$3.call(AsyncTask.java:378)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
     Caused by: java.io.IOException: request was not successful: Response{protocol=http/1.1, code=400, message=Bad Request, url=https://www.geocaching.com/api/proxy/web/v1/geocache/gc12345/GeocacheLog}
        at cgeo.geocaching.network.Network.lambda$static$6(Network.java:654)
        at cgeo.geocaching.network.-$$Lambda$Network$HJwZsCLFMmiISrdxtajFdFJJscU.apply(Unknown Source:2)
        at io.reactivex.rxjava3.internal.operators.single.SingleFlatMap$SingleFlatMapCallback.onSuccess(SingleFlatMap.java:77)
        at io.reactivex.rxjava3.internal.operators.single.SingleCreate$Emitter.onSuccess(SingleCreate.java:68)
        at cgeo.geocaching.utils.RxOkHttpUtils$1.onResponse(RxOkHttpUtils.java:48)
        at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:919) 
```

(Not sure if those two errors are related, or if the cause for the failing call in the emulator is something emulator-specific.)

### How to reproduce?

- open c:geo
- open a cache
- send log, with or without attached image

### Actual result after these steps?

- in my emulator test:
  - a popup opens with "unknown error, see FAQ" (etc.)
  - log did not get sent
- for the users on support
  - some error is being displayed
  - but the log got sent

### Expected result after these steps?

- generally: post log successfully
- show error message only when an actual error has occurred

### Reproducible

Yes

### c:geo Version

2021.12.24

### Additional Information

Tickets 876615 and 417247

**Comment by Lineflyer** [comment] 2022-02-04 23:57
I can reproduce this issue on my real device for posting a log with image (unscaled in this case....could make a difference).
Log send reports failed but log is posted OK with image.

**Comment by moving-bits** [comment] 2022-02-05 00:01
Additional info from the two users:
- only happens when attaching an image
- happens since about one week
- log is being posted successfully, despite the error message

**Comment by john-magnus** [comment] 2022-02-05 01:32
I can confirm this as well. 

Furthermore, if there's several images attached to the log, only the first is uploaded. Also, the image title is missing.

**Comment by eddiemuc** [comment] 2022-02-05 08:11
Happens also in normal production (not just beta).

On which branch should it be fixed?

**Comment by eddiemuc** [comment] 2022-02-05 09:56
Forget what I wrote about production, I have beta on my device as well.

Trying to reproduce this on my developer machine, In noticed that there I am unable to send any log. Diving deeper In have the impression that the Json generated for the post message body is empty. Don't know why.

@moving-bits In saw that you worked in this area in October last year (specifically the Json wrapper class "GeocacheLog" inside GCWebAPI. It seems to be the only class using Json field mapping without Json annotations (compare e.g. with AttachLogImageRequest). Could the reason for the problem lie in a new version of fasterjson with maybe other defaults on how to do Json bind/unbind?

Sorry, this code area is quite new to me.

**Comment by eddiemuc** [comment] 2022-02-05 10:40
Update: got the general log sending problem fixed on my emulator by adding explicit "JsonProperty" annotations to "GeocacheLog" and "Geocache". 

Continuing with the log image problem: sending the log image message returns HTTP500 ("Internal server error"), and as can be seen by observation this obviously means that the image is transferred but not related information (e.g. image title).

Will continue investigation

**Comment by eddiemuc** [comment] 2022-02-05 10:48
Full error message returned by gc.com:

```
{"statusCode":500,"statusMessage":"InternalServerError","errorMessage":"The given header was not found.","errors":[{"message":"The given header was not found.","detail":"   at System.Net.Http.Headers.HttpHeaders.GetValues(String name)\r\n   at Geocaching.WebService.Attributes.ValidateXhrAntiforgeryTokenAttribute.<ExecuteAuthorizationFilterAsync>d__5.MoveNext() in E:\\TeamCity\\work\\1db2aea98762ed70\\Geocaching.WebService\\Attributes\\ValidateXhrAntiforgeryTokenAttribute.cs:line 51\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__1.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__1.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Groundspeak.Owin.Middleware.NonSuccessResponseRewritingHandler.<SendAsync>d__0.MoveNext()"}]}
```

**Comment by eddiemuc** [comment] 2022-02-05 10:51
Apparently we need to set some (new) header which we don't set currently. in the stack trace I find "Geocaching.WebService.Attributes.ValidateXhrAntiforgeryTokenAttribute", might be related to this.

**Comment by eddiemuc** [comment] 2022-02-05 11:59
Ok, I am at a loss at this point. I tried to reconstruct which requests are actually send for image upload by the website, but strangely enough they seem not to use the Proxy WebAPI (or I am too dumb to find those requests in Google Network.)

From googling XhrAntiforgery I assume that we do not forward some cookie value the right way, but I cant really tell where the problem lies as of now. Anyone with more experience in this area can jump in?

**Comment by Lineflyer** [comment] 2022-02-05 12:07
@pstorch 
Back in the days you implemented the usage of the new logging page (using that WebAPI). Perhaps you can give some insights to the problems/questions above if your time permits. That would be great!

**Comment by ztNFny** [comment] 2022-02-05 12:33
@Lineflyer we have 3 Website changes now.  While each of them on their own not that critical maybe we should still do a stable release with all 3 fixed?

**Comment by Lineflyer** [comment] 2022-02-05 12:42
@ztNFny Yes, maybe. Lets take this alignment to #12451

**Comment by eddiemuc** [comment] 2022-02-06 10:06
Follow-up on this:
* I tried on the website both the new log editor (where you can post images together with the log) and the "old way" (where you have to upload images via a separate method later). To the best of my "Chrome network" reading abilities, both methods do  not (any more?) use the Web Api calls we use in our code
* It must be noted that we still use the Proxy WebAPI v1 whereas gc.com has switched to a "v2" version of this API. However, in this "v2" the problematic call above seems not to be available any more

I fear that we experience a side effect of gc.com changing their internal services while of course not testing any more their "outdated" v1 functions.

It must be noted that we CAN change the code to allow for multi-image-attach again, but we are not able to set title and description on it as of now.

@pstorch : as documented in code by you back in 2017, posting a log image consists of three calls:
* first one to actually upload the image as "log draft image" -> works
* second one to "patch" this image to the log -> works
* third one to post info about image e.g. title and description -> this one fails
Any insights from you back from your work back then would be highly appreciated.

Otherwise I have a strange idea: maybe asking gc for help?

Meanwhile, as time permits, I will try a few ideas. But I am really stabbing around in the dark here

**Comment by ztNFny** [comment] 2022-02-06 10:08
Why not change our code to use the v2 webapi?

**Comment by eddiemuc** [comment] 2022-02-06 10:15
> Why not change our code to use the v2 webapi?

As written above, just changing v1 to v2 in the URLs doesn't work. And since these APIs are undocumented of course (they are meant for gc.com internal usage only) and the website does not seem to use it itself I am at a lost how to find out how to use it (or if it even has methods for image upload)

**Comment by ztNFny** [comment] 2022-02-06 10:18
Misunderstood your previous comment to mean they are using v2 now. What I meant was to adjust our code to whatever the website is currently doing. Should be a simple matter of capturing those calls.

**Comment by eddiemuc** [comment] 2022-02-06 10:39
> Misunderstood your previous comment to mean they are using v2 now. What I meant was to adjust our code to whatever the website is currently doing. Should be a simple matter of capturing those calls.

Be my guest :-) Looks to me as if they are using aspx for image upload. Again, I might have failed to find the right requests in Chrome's Network output

**Comment by pstorch** [comment] 2022-02-06 10:53
> Otherwise I have a strange idea: maybe asking gc for help?

To be honest: 
Don't expect help on their webapi, this is gc internal. GC.com won't support c:geo as long as c:geo doesn't use the official 3rd party client API, which is documented. 
Breaking webapi changes will happen over and over again until c:geo will switch to the official API. 

To the current problem:
> third one to post info about image e.g. title and description -> this one fails
> Any insights from you back from your work back then would be highly appreciated.

I might be able to spend a few minutes on this. But I don't promise anything.

**Comment by ztNFny** [comment] 2022-02-06 10:56
1. Upload image:
```
curl 'https://www.geocaching.com/api/proxy/web/v1/LogDrafts/images' \
  -H 'Content-Type: multipart/form-data; boundary=----WebKitFormBoundaryfAfrrIQXmUrmKn4e' \
  -H 'Accept: application/json' \
  --data-raw $'------WebKitFormBoundaryfAfrrIQXmUrmKn4e\r\nContent-Disposition: form-data; name="guid"\r\n\r\nacfdf728-baea-4be8-ba73-012a1625874f\r\n------WebKitFormBoundaryfAfrrIQXmUrmKn4e\r\nContent-Disposition: form-data; name="qqfilename"\r\n\r\ntest.png\r\n------WebKitFormBoundaryfAfrrIQXmUrmKn4e\r\nContent-Disposition: form-data; name="qqtotalfilesize"\r\n\r\n425\r\n------WebKitFormBoundaryfAfrrIQXmUrmKn4e\r\nContent-Disposition: form-data; name="qqfile"; filename="test.png"\r\nContent-Type: image/png\r\n\r\n\r\n------WebKitFormBoundaryfAfrrIQXmUrmKn4e--\r\n' \
  --compressed
```
Returns:
```
  {"guid":"<guid>","url":"https://img.geocaching.com/<guid>.png","thumbnailUrl":"https://img.geocaching.com/large/<guid>.png","success":true}
```

2. On submitting the log attach the image to the log:
```
  curl 'https://www.geocaching.com/api/proxy/web/v1/LogDrafts/images/<guid>?geocacheLogReferenceCode=GL<logcode>' \
    -X 'PATCH' \
    -H 'Accept: */*' \
    --compressed
```

3. Set image description
```
curl 'https://www.geocaching.com/api/proxy/web/v1/geocaches/logs/GL<logcode>/images/<guid>' \
  -H 'X-Verification-Token: <TOKEN>' \
  -H 'Content-Type: application/json' \
  --data-raw '{"name":"","uuid":"","guid":"<guid>","thumbnailUrl":"https://img.geocaching.com/large/<guid>.png","dateTaken":"2022-02-06","description":"my description text","qqButtonId":"5eff9b5b-e544-45a8-b6ef-3d5be1b2e6b9","qqThumbnailId":0,"id":0,"filename":"test.png","lastModified":1644144486172,"lastModifiedDate":"2022-02-06T10:48:06.172Z","webkitRelativePath":"","size":425,"type":"image/png"}' \
  --compressed
```

**Comment by ztNFny** [comment] 2022-02-06 10:58
> Looks to me as if they are using aspx for image upload.

aspx is used in the old log form only

**Comment by ztNFny** [comment] 2022-02-06 11:04
After taking a (very short) look at the code I'd say that "3) attach image to log" is missing "X-Verification-Token"

**Comment by ztNFny** [comment] 2022-02-06 11:10
The value of X-Verification-Token header is the value of the form field __RequestVerificationToken

**Comment by pstorch** [comment] 2022-02-06 11:20
@ztNFny that sounds like the issue, yes.

**Comment by eddiemuc** [comment] 2022-02-06 11:40
@ztNFny thanks for diving into this! Out of interest (and for the future): where / how would I have been able to capture this sequence of requests (I used the website new log form, attached images to it but could not find these requests in the Chrome recorded Network history. And using "Upload image" afterwards always brings be to the old form)

**Comment by ztNFny** [comment] 2022-02-06 11:48
> where / how would I have been able to capture this sequence of requests

Chrome dev console. The first request happens when you attach the image to the log, the other 2 when sending the log

![image](https://user-images.githubusercontent.com/1258173/152679397-222b17f4-6dda-47d1-9eb8-396f5c3c69f1.png)

**Comment by eddiemuc** [comment] 2022-02-06 13:06
> also "preserve" needs to be checked to retain logs on navigating pages

Thanks a lot! The "preserve log" checkbox did the trick

**Comment by eddiemuc** [comment] 2022-02-06 13:34
I have a working fix, need to clean it up and will provide PR

Very sad thing is that now we have to fetch the website's HTML in order to get the __RequestVerificationToken. So it is not a "pure" WepAPI interface any more

**Closed** 2022-02-07 19:44 UTC
Labels: Bug, Prio - High
