### ISSUE TITLE
C:Geo does not work with Maps.me 6.3.6

### ISSUE THREAD

**Issue by dcj99b** [cgeo/cgeo#5918] opened 2016-08-23 08:20 UTC
##### Detailed steps causing the problem:
- Upgrade Maps.me to 6.3.6

##### Actual behavior after performing these steps:
Selecting "Show on a map" in C:Geo, and chosing Maps.me
The map appears, but no caches come across
Their cursor is stuck in the search box.

##### Expected behavior after performing these steps:

Full display of caches onto the map

##### Version of c:geo used:

2016.06.16

##### Is the problem reproducible for you?
Yes, on two different Android machines

##### System information:
Android 5.0.2
Attach system information here if available (see c:geo menu -> About c:geo -> System)
```


##### Other comments and remarks:

Deleting Maps.me and loading version 6.2.5-Web  using their downloadable .apk file restores full functionality.

PLEASE

**Comment by SammysHP** [comment] 2016-08-23 08:21
Duplicate of #5916.

**Closed by SammysHP** 2016-08-23 08:21 UTC
