### ISSUE TITLE
Log type changes during posting

### ISSUE THREAD

**Issue by andrixnet** [cgeo/cgeo#6694] opened 2017-08-18 06:37 UTC
Recently I've been at an event and I marked all my finds with "one click offline log".
Now that I am home, I am reopening each cache and posting a log with c:geo.

I open the cache from the map. Go to logs page. Click on my offline log. (it's a found log)
I write my log and submit it. 
Note: I have about 30 trackables and 9 geokrety with visiting set.
During the submission process, while processing the geokrety "visited" posts, I get a notification bubble in the lower part of the screen: "log type changed". 
After the submission ended, I see my online "found" log and the "saved offline log" as "didn't find".
Checking the cache webpage shows only my "found" there, which is correct. 

This is the cache https://coord.info/GC6QBB0

![screenshot_20170818-093536](https://user-images.githubusercontent.com/3382777/29447106-d5090c64-83f8-11e7-918b-c7b825493f23.png)

It may be related to https://github.com/cgeo/cgeo/issues/6644 and/or https://github.com/cgeo/cgeo/issues/6693

**Comment by Lineflyer** [comment] 2017-08-18 11:16
I think this issue as well as your issue #6693 are caused by the fact that either some communication problem occured or you turned the phone to landscape while the log was being posted. 
Therre exists an issue which describes this fault already. I need to look it up.

**Comment by Lineflyer** [comment] 2017-08-28 14:12
We have quite some support mail like that after version change to 2017.08.23.

The reason is quite obvious for me:
- With the previous c:geo version the log posting had a problem (reported error but went through)
- As a consequence the cache was not marked as found in c:geo
- When the user tries again to post his log and the logging page is loaded the log type "Found" becomes unavailable (only one found log per cache allowed as to new rule of gc.com). This seems to automatically change the log type to "Did not find" in c:geo.

If we ignore the cause of the current problems, still one problem remains, which is easy to reproduce:
- Save a unfound geocache in c:geo
- Log a "Find" for this cache using other means than c:geo (e.g. directly on the website)
- Open this cache in c:geo and start logging it
- On the log page the log type changs from "Found" to "Did not find" after the log page is loaded

@Bananeweizen 
AFAIR you implemented the "one find per cache" adaption within c:geo according to the new gc.com regulations. I thought it was implemented that we fall back to "Write note" in such cases, am I wrong?

**Comment by pstorch** [comment] 2017-08-28 16:23
I think we should prevent the user from choosing the log type as long as the log page is still being loaded in the background.

**Comment by Lineflyer** [comment] 2017-08-28 19:09
> I think we should prevent the user from choosing the log type as long as the log page is still being loaded in the background.

This problem is not about the user selecting something but about the default log type "Found" we set, which makes much sense in normal cases.
I think this is similar to another issue we had some time ago (which resulted in Need archived logs in some scenarios), where the list of available log types results in inconsistence after parsing the logging page:
Lets say in c:geo it is:
"Found"= Logtype#1
"DNF" = Logtype#2
"Note" = Logtype#3

When starting the logging activity Logtype#1 is preselected.

Now the logging page is parsed and returns:
"DNF" = Logtype#1
"Note" = Logtype#2
"Needs maintenance" = Logtype#3

This results in the preselected logtype#1 being changed from "Found" to "DNF" in such cases.
You get my point?

**Comment by Lineflyer** [comment] 2017-08-28 19:11
This probably means the easiest solution could be to change our log type order from:


- Found
- DNF
- Note
- Needs maintenance
- Needs archived

to:
- Found
- Note
- DNF
- Needs maintenance
- Needs archived

**Comment by pstorch** [comment] 2017-08-28 19:38
But isn't any preselection a problem if we change the options after parsing the log page?

**Comment by Lineflyer** [comment] 2017-08-28 20:05
Might be. But what could be a better solution.
If you have the "offline log" case you will anyhow use a preselection which later gets merged if you decide to compose online.

But if you can confirm it works the way I assume, then my proposal would avoid the most disturbing case at least.

**Comment by pstorch** [comment] 2017-08-28 20:18
Checking the current implementation:
https://github.com/cgeo/cgeo/blob/master/main/src/cgeo/geocaching/log/LogCacheActivity.java#L150-L157

After loading the log page c:geo checks if the LogType is still available. If not it selects the first option and shows a Toast that the LogType has changed. Maybe users simply overlook the Toast?

**Comment by SammysHP** [comment] 2017-08-29 06:14
If the selected log type is not available it should be unset.

**Comment by Lineflyer** [comment] 2017-08-29 09:13
> If the selected log type is not available it should be unset.

Sounds even more reasonable!

**Comment by andrixnet** [comment] 2017-12-31 17:24
Problem still affecting c:geo 2017.12.17 with many trackables to log as visited. After first submission fails, a login error is shown, subsequent manual retry either encounters a rejection from GC (because multiple find logs not allowed) or other cause, but logtype changed (without warning) to DNF, and then submitted again.

**Comment by Lineflyer** [comment] 2021-04-26 12:56
Was no longer able to reproduce this. Closing for now.
@andrixnet Feel free to reopen if you have the chance to try it again as described in your initial posting.

**Closed by Lineflyer** 2021-04-26 12:56 UTC
Labels: Bug
