### ISSUE TITLE
Feature  request  show  potential FTF's 

### ISSUE THREAD

**Issue by simrebel** [cgeo/cgeo#6735] opened 2017-09-20 16:20 UTC
I like  the new feature in cachly  where if it shows a cache  on the live map that has no found  logs
it will add a little FTF flag to the icon,   so you know it's  a potential of being a FTF

**Comment by SammysHP** [comment] 2017-09-20 16:35
Duplicate of #2802. Sadly this is not possible because we don't have the necessary information on the map.

**Closed by SammysHP** 2017-09-20 16:35 UTC
