### ISSUE TITLE
During browsing OSM map skips thousands kilometres 

### ISSUE THREAD

**Issue by vohary** [cgeo/cgeo#4630] opened 2015-01-23 21:24 UTC
Hello,
 when I use OSM maps (online or offline) then very often skips the map to the North (typically from Prag to Svalbard; from America to north Canada).  The skip happens when I move by map. Sometime the skip happens, when I put off my finger from display. Google maps in c:geo are OK without this problem. 
I have smartphone ZTE Z5mini, Androiid 4.2.2, c:geo 2015.01.20 and some older version. For more information contact me, please. 
Best Regards
Vohary
PS: edit 24.1.2015

**Comment by Lineflyer** [comment] 2015-01-25 19:42
Can you please post more details:
- What map from what source (URL, link, name) are you using?
- Does only the map position change or does your own position jump together with the map?
- On which zoom level does this happen / Is it depending on the zoom level?

**Comment by vohary** [comment] 2015-01-26 12:38
______________________________________________________________
> Od: Lars <notifications@github.com>
> Komu: "cgeo/cgeo" <cgeo@noreply.github.com>
> Datum: 25.01.2015 20:42
> Předmět: Re: [cgeo] During browsing skips OSM maps thousands kilometres (#4630)
>
Can you please post more details:
What map from what source (URL, link, name) are you using?- It makes OSM maps. I have default online maps: OSM Mapnik and OSM Cyclemap -- both skip. And I have offline map of Czech republic from year 2013, and it skips too. Maps from Goggole (Maps and Saletile) are OK -- without this issue.
Does only the map position change or does your own position jump together with the map?- Only the map position change.  The blue arrow (my position on map) is not show after the skip. When I press "my position" (GPS symbol), then the map moves to my position.
On which zoom level does this happen / Is it depending on the zoom level?- It is NOT depending on the zoom level.

**Comment by vohary** [comment] 2015-01-27 11:25
Hello,
 
I tried next two test. 
1.    I rotated my phone to horizontal position (landscape) – map still skips to the North.
2.    I tried this issue on my old phone (ZTE Blade – 1x CPU 600MHz) and this issue is not there – but  the phone is to slow to use OSM maps.
 
Best Regards
 
Vojtech @ Vohary
______________________________________________________________
> Od: <vohary@centrum.cz>
> Komu: "cgeo/cgeo" <reply@reply.github.com>
> Datum: 26.01.2015 13:38
> Předmět: Re: [cgeo] During browsing skips OSM maps thousands kilometres (#4630)
>
 
______________________________________________________________
> Od: Lars <notifications@github.com>
> Komu: "cgeo/cgeo" <cgeo@noreply.github.com>
> Datum: 25.01.2015 20:42
> Předmět: Re: [cgeo] During browsing skips OSM maps thousands kilometres (#4630)
>
Can you please post more details:
What map from what source (URL, link, name) are you using?- It makes OSM maps. I have default online maps: OSM Mapnik and OSM Cyclemap -- both skip. And I have offline map of Czech republic from year 2013, and it skips too. Maps from Goggole (Maps and Saletile) are OK -- without this issue.
Does only the map position change or does your own position jump together with the map?- Only the map position change.  The blue arrow (my position on map) is not show after the skip. When I press "my position" (GPS symbol), then the map moves to my position.
On which zoom level does this happen / Is it depending on the zoom level?- It is NOT depending on the zoom level.

**Comment by Lineflyer** [comment] 2015-02-05 08:31
I tested this on quite some devices now and can not reproduce it.
It looks to me like a problem of your specific device or the model (which I don't have available for testing). 
Not sure how we can help, as I cant find any possible reason why the map should move by itself (as you said it is not your position which is jumping, but only the map).

**Comment by Lineflyer** [comment] 2015-04-13 20:47
@vohary I will close this. Feel free to reopen if you have any clues, that this is not caused by your device.

**Closed by Lineflyer** 2015-04-13 20:47 UTC
Labels: Unverified

**Comment by SammysHP** [comment] 2015-04-14 04:48
Btw: Guess which CPU the ZTE Z5 Mini has? Correct, MediaTek. ;)

**Comment by alexxsanchezm** [comment] 2015-05-04 22:03
Hi @Lineflyer i have been facing this issue for a while, its similar as @vohary case, but in my case the map and the current position is moved for an instant then it's moved back to my current real position.

I have some clues that may help, 
1. Maybe due to a change on the accuracy.
2. Maybe a change on the location provider (GPS, Network)

Any help will be appreciated
thanks

**Comment by SammysHP** [comment] 2015-05-05 17:40
Please try this version: http://download.cgeo.org/cgeo-nightly-nojit.apk
