### ISSUE TITLE
Send2cgeo no longer working.

### ISSUE THREAD

**Issue by alan666notb** [cgeo/cgeo#6617] opened 2017-06-26 07:54 UTC
The Send2c:geo script updated yesterday and it no longer appears on firefox, is that something dealt with here?

Send 2 c:geo is now version 0:38

**Comment by alan666notb** [comment] 2017-06-26 07:55
I don't see the Send2cgeo option on the maps or on cache pages.

**Comment by SammysHP** [comment] 2017-06-26 08:08
Wrong repository and duplicate of cgeo/send2cgeo#36.

**Closed by SammysHP** 2017-06-26 08:08 UTC
