### ISSUE TITLE
Show DNFs and NM

### ISSUE THREAD

**Issue by Technical-13** [cgeo/cgeo#6879] opened 2017-12-10 21:54 UTC
It's great that c:geo shows smiles on completed caches, but I wish it would also show if I logged a DNF or a NM as well.

**Comment by pstorch** [comment] 2017-12-10 22:19
Partly duplicate of #3206 (the case for DNFs).

**Comment by Technical-13** [comment] 2017-12-11 14:24
Also would be great if it could show FTFs like Cachely (which I didn't find out about until this morning)
![image](https://user-images.githubusercontent.com/4294498/33835624-0ef92754-de55-11e7-9b86-e3b1581c085f.png)

**Comment by UniQP** [comment] 2017-12-11 14:41
@Technical-13 Sorry, I don't get it. Does it show your FTFs (then I would expect a smiley) or caches without any found log?

**Comment by pstorch** [comment] 2017-12-11 16:50
I think this is about showing FTF opportunities, like caches which are not found by anyone yet.

**Comment by pstorch** [comment] 2017-12-11 17:05
If my assumption is right, then we already have an issue for that which was closed as "Won't fix": #2802

**Comment by Lineflyer** [comment] 2017-12-11 18:06
Flagging FTF is for sure not possible with reasonable effort as we simply do not have this information (except for locally stored caches, and even then it could be outdated information) on the map.

Regarding DNFs:
This seems meanwhile possible as the map as well as the cache details contain this information very prominent (map= Sad smiley, Cache detail = Found/DNF status on top right). Anyway for DNF it is a duplicate of #3206

**Comment by Technical-13** [comment] 2017-12-13 01:45
Apparently, the icon indicator shows based on the contents of a stored `FTF` list.  So, the list is user maintained.  The other option is to do it like https://project-gc.com/Profile/FTFList

**Comment by pstorch** [comment] 2017-12-13 09:39
If you want to put your own FTFs on a list and want to mark them on the map, then this might be similar as requested here #5798

**Comment by Lineflyer** [comment] 2017-12-23 21:31
So, I think the two requests here are covered by the mentioned issues: DNF #3206   Marked lists: #5798

Please reopen if you disagree.

**Closed** 2017-12-23 21:31 UTC

**Comment by Technical-13** [comment] 2017-12-24 04:46
#3206 covers DNFs, #5798 doesn't really cover FTFs and neither cover NMs.
