### ISSUE TITLE
Automatically sort by name

### ISSUE THREAD

**Issue by Bananeweizen** [cgeo/cgeo#5067] opened 2015-06-29 20:19 UTC
We already sort lists by date if they contain only event caches. We could sort by name automatically if we recognise a common prefix in all caches of a list.

**Comment by Lineflyer** [comment] 2015-06-29 20:22
Title corrected :) That was a good one ;)

**Comment by kumy** [comment] 2015-06-29 21:46
This remind me something...
Isn't it a duplicate of #4707 ;) ?

**Comment by Lineflyer** [comment] 2015-06-30 06:26
Yup, it is.

**Closed by Lineflyer** 2015-06-30 06:26 UTC
Labels: Feature Request
