### ISSUE TITLE
Show if you did not find a cache

### ISSUE THREAD

**Issue by Savvasun** [cgeo/cgeo#9448] opened 2020-11-26 01:42 UTC
### Problem
The app shows you when you have found a cache with a smiley face and by highlighting it in the "radar" view (as I call it, I'm dumb.) This is good, but unlike the official app, it **doesn't show if you have submitted a DNF request**. It is really frustrating for me to see caches that look unexplored but were actually not found by me.

### Solution
Add code to check if you have submitted a **DNF request** in a way similar to how it currently checks for **"found" logs**. Then, **display it** in blue or another color, similar to how it does in the official geocaching app. This is very useful for generally seeing what caches you have visited, whether you have found them or not.

#### Additional
If this wasn't added to encourage people to look for the same cache again, even if they already tried looking for it, make it a toggleable setting. Also, it would be nice if there was an option to show a large sad face similar to how the large smiley face currently can look on already found caches.

**Comment by SammysHP** [comment] 2020-11-26 05:07
Duplicate of #3206 and #6614.

**Closed by SammysHP** 2020-11-26 05:07 UTC
Labels: Feature Request, Unverified
