### ISSUE TITLE
feature request: refresh for caches not refreshed for a selectable time

### ISSUE THREAD

**Issue by juergbeck** [cgeo/cgeo#7135] opened 2018-09-04 19:57 UTC
##### Detailed steps causing the problem:
- refreshing of caches: manage caches -> refresh all

##### Actual behavior after performing these steps:
- all caches in the list are refreshed, independent of the age of the latest refresh

##### Expected behavior after performing these steps:
It should be possible to define a maximum age of the latest refresh, so that only those caches are refreshed that have older data. This would dramatically reduce time and network traffic for a refresh.

##### Version of c:geo used:
Latest version: 2018.08.14

##### Is the problem reproducible for you?
Yes

##### System information:
```
Attach system information here if available (see c:geo menu -> About c:geo -> Swipe right to System)
Keep the apostrophe at beginning and end to have it properly formatted
```

##### Other comments and remarks:
After presenting this request in a german facebook group for c:geo I received a lot of positive feedback. Introducing this possibility would be widely appreciated.

**Comment by SammysHP** [comment] 2018-09-04 21:30
Duplicate of #2590.

**Closed by SammysHP** 2018-09-04 21:30 UTC
