### ISSUE TITLE
Bug :  Smiley of founded geocaches

### ISSUE THREAD

**Issue by RF-TEC** [cgeo/cgeo#10726] opened 2021-05-23 13:51 UTC
Hello

Thank you for your software and its updates.

For a few months, there has been a bug in the display of smileys which indicate the geocaches found, these smileys are not displayed, or partially, or randomly.

It's annoying, we no longer know which geocaches have been found.

Despite the last 5 updates, the problem persists.

Thank you

**Comment by bekuno** [comment] 2021-05-23 19:13
Please provide screenshot(s) to see what you mean.

**Comment by Lineflyer** [comment] 2021-05-23 20:29
And your system information would be helpful as well.

**Comment by RF-TEC** [comment] 2021-05-24 07:18
Thanks for you support

I use Android 9 with core 4.4.146 of 2019 on simple Wiko smartphone.

The display worked normally from August 2020 to January 2021, since the last 5 updates, only a few 'found' smileys are displayed. On the screenshot, all geocaches have been found, but only 2 smileys are displayed.

Do you recommend changing Android version, or hardware?

Thank you so much

Tosh75 on Geocaching.com
Fred, South of France

![Capture d'écrans_20210524-090206](https://user-images.githubusercontent.com/76113728/119311047-e0def800-bc70-11eb-80de-8e9c7cc1b86b.png)

**Comment by Lineflyer** [comment] 2021-05-24 08:29
Please kindly send us the c:geo system information, so that we can take a closer look into your problem.
You will find the c:geo system information in: c:geo Menu -> About c:geo -> Swipe to "System".

**Comment by RF-TEC** [comment] 2021-05-24 10:18
`--- System information ---
c:geo version: 2021.05.20

Device:
-------
- Device type: W-K510-EEA (W-K510-EEA, WIKO)
- Available processors: 4
- Android version: 9
- Android build: PPR1.181008.011 release-keys
- Sailfish OS detected: false
- Google Play services: disabled - 21.12.13 (110304-367530751)
- HW acceleration: enabled (default state)

Sensor and location:
-------
- Low power mode: inactive
- Compass capabilities: yes
- Rotation vector sensor: absent
- Orientation sensor: present
- Magnetometer & Accelerometer sensor: present
- Direction sensor used: magnetometer & accelerometer

Program settings:
-------
- Hide caches: -
- Hide waypoints: original 
- Set language: fr_FR (system default)
- System date format: dd/MM/y
- Debug mode active: no
- Live map mode: true
- OSM multi-threading: false / threads: 1
- Global filter: display all caches
- Last backup: 12 janv. à 23:25
- Routing mode: Walk
 -Settings: v5, Count:130
- Map: Google Maps : satellite
  - Id: cgeo.geocaching.maps.google.v2.GoogleMapProvider$GoogleSatelliteSource
  - Atts: none
  - Theme: none

Services:
-------
- Geocaching sites enabled:
   geocaching.com: Not logged in ()
   Geocaching.com Adventure Lab
- Geocaching.com date format: dd/MM/yyyy
- Routing: external / BRouter installed: false
- Installed c:geo plugins:  none

Permissions & paths:
-------
- Fine location permission: granted
- Write external storage permission: granted
- System internal c:geo dir: /data/user/0/cgeo.geocaching (8,6 GB free) v2 internal isDir(7 entries)
- Legacy User storage c:geo dir: /storage/emulated/0/cgeo (8,6 GB free) v2 external non-removable isDir(6 entries)
- Geocache data: /storage/emulated/0/Android/data/cgeo.geocaching/files/GeocacheData (8,6 GB free) v2 external non-removable isDir(451 entries)
- Internal theme sync (is turned off): /data/user/0/cgeo.geocaching/MapThemeData (8,6 GB free) v2 internal isDir(0 entries)
- Public Folders: #11
  - BASE: /cgeo (User-Defined)[/cgeo[DOCUMENT#0:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo, Av:true, files:>=5, dirs:>=8, totalFileSize:>=34,8 MB, free space: 8,6 GB, files on device: 3077632)
  - OFFLINE_MAPS: /GEO-Cartes-hors-ligne (User-Defined)[/GEO-Cartes-hors-ligne[DOCUMENT#0:p-content://com.android.externalstorage.documents/tree/primary%3AGEO-Cartes-hors-ligne::]] (Uri: content://com.android.externalstorage.documents/tree/primary%3AGEO-Cartes-hors-ligne/document/primary%3AGEO-Cartes-hors-ligne, Av:true, files:1, dirs:1, totalFileSize:163,6 MB, free space: 8,6 GB, files on device: 3077632)
  - OFFLINE_MAP_THEMES: /GEO-Cartes-hors-ligne/_themes (Default)[/GEO-Cartes-hors-ligne/_themes[PERSISTABLE_FOLDER(OFFLINE_MAPS)#1:p-content://com.android.externalstorage.documents/tree/primary%3AGEO-Cartes-hors-ligne::/_themes]] (Uri: content://com.android.externalstorage.documents/tree/primary%3AGEO-Cartes-hors-ligne/document/primary%3AGEO-Cartes-hors-ligne%2F_themes, Av:true, files:0, dirs:0, totalFileSize:0 B, free space: 8,6 GB, files on device: 3077632)
  - LOGFILES: /cgeo/logfiles (Default)[/cgeo/logfiles[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/logfiles]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Flogfiles, Av:true, files:2, dirs:0, totalFileSize:24,9 MB, free space: 8,6 GB, files on device: 3077632)
  - GPX: /cgeo/gpx (Default)[/cgeo/gpx[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/gpx]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Fgpx, Av:true, files:0, dirs:0, totalFileSize:0 B, free space: 8,6 GB, files on device: 3077632)
  - BACKUP: /cgeo/backup (Default)[/cgeo/backup[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/backup]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Fbackup, Av:true, files:3, dirs:2, totalFileSize:9,9 MB, free space: 8,6 GB, files on device: 3077632)
  - FIELD_NOTES: /cgeo/field-notes (Default)[/cgeo/field-notes[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/field-notes]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Ffield-notes, Av:true, files:0, dirs:0, totalFileSize:0 B, free space: 8,6 GB, files on device: 3077632)
  - SPOILER_IMAGES: /cgeo/GeocachePhotos (Default)[/cgeo/GeocachePhotos[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/GeocachePhotos]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2FGeocachePhotos, Av:true, files:0, dirs:0, totalFileSize:0 B, free space: 8,6 GB, files on device: 3077632)
  - ROUTING_BASE: /cgeo/routing (Default)[/cgeo/routing[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/routing]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Frouting, Av:true, files:7, dirs:1, totalFileSize:81,2 KB, free space: 8,6 GB, files on device: 3077632)
  - ROUTING_TILES: /cgeo/routing/segments4 (Default)[/cgeo/routing/segments4[PERSISTABLE_FOLDER(ROUTING_BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/routing/segments4]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Frouting%2Fsegments4, Av:true, files:0, dirs:0, totalFileSize:0 B, free space: 8,6 GB, files on device: 3077632)
  - TEST_FOLDER: [Legacy]/data/user/0/cgeo.geocaching/files/unittest (Default)[/data/user/0/cgeo.geocaching/files/unittest[FILE#1:p-file:///data/user/0/cgeo.geocaching/files::/unittest]] (Uri: file:///data/user/0/cgeo.geocaching/files/unittest, Av:true, files:0, dirs:0, totalFileSize:0 B, free space: 8,6 GB, files on device: -1)
- Map render theme path: 
- PersistedDocumentUris: #1
- TRACK: null
- Persisted Uri Permissions: #2
  - content://com.android.externalstorage.documents/tree/primary%3AGEO-Cartes-hors-ligne (5 mai à 10:17):RW
  - content://com.android.externalstorage.documents/tree/primary%3Acgeo (5 mai à 10:17):RW
- Database: /data/user/0/cgeo.geocaching/databases/data (v94, Size:6,9 MB) on system internal storage
--- End of system information ---`

**Comment by bekuno** [comment] 2021-05-24 10:46
@RF-TEC 
You are not logged in to geocaching.com.
Then you see only your offline log state. And you will miss logged caches without offline logs.
Please login and check the state afterwards.

**Comment by Lineflyer** [comment] 2021-05-24 10:50
Additionally to what @bekuno you seem to have stored the caches on your screen for offline use (as can be seen by the disc icon). You might need to refresh those caches to reflect the found state as you might have stored them before finding them or while not being logged in (correctly).

**Comment by RF-TEC** [comment] 2021-05-24 12:15
Before January 2021, when i connected to géocaching.com with CGEO, automatically, CGEO updated the geocaches found and the smileys remained memorized after deconection, which was very useful, now, some disappear, others remain, sometimes it is. is random.

Yes indeed, I store the caches offline before going to fetch them, it works very well and this is the only reason i use CGEO.

I will try to update the caches found (Only 115) but i am not sure that this fixes the problem.

Thank you

**Comment by fm-sys** [comment] 2021-05-24 14:44
It's right that a found state should be taken over to DB if gathered via the live map...

**Comment by fm-sys** [comment] 2021-07-14 15:29
Duplicate of  #7600

**Closed by fm-sys** 2021-07-14 15:29 UTC
Labels: Bug, Unverified
