### ISSUE TITLE
UI frozen while loading trackables on log page

### ISSUE THREAD

**Issue by andrixnet** [cgeo/cgeo#7513] opened 2019-04-16 09:43 UTC
- Have trackables in your inventory. I am talking tavelbugs & geocoins. I have 30+.
- Have geokrety service also. I have 10+ krety in my inventory.
- Go to a cache, open the log page (online logging)

Apparently the log page opens pretty quickly.
The geokrety list loads fast. (not noticable on my device)

I start typing my log entry. While typing, the c:geo UI freezes completely for several seconds (1-3 seconds most often, once happened for about 12s). Nothing responds, not the soft keyboard, nothing from c:geo. Only system home button responds. 

Then the travelbugs/geocoins list loads (or not) and c:geo starts responding again with no further problems. 

I would expect c:geo not to freeze like this and loading such data, which is clearly collateral, to take place in a background thread.

This issue looks similar to https://github.com/cgeo/cgeo/issues/7003 but to me it happens only related to loading of travelbug list. The actual log page loads fine, I don't have a problem with loading spinner.

Geokrety site might respond faster and I don't see problems from it (?) 
Geocaching.com might respond slower for the trackables list -> this issue.
I think error loading the trackables list is silent. After waiting >10s the app responds again and I see only geokrety trackables.

c:geo 2019.04.04

Device is Samsung Galaxy S9+ (so device performance should not be a problem)
Internet access GSM 4G during all instances of encountering this issue.

**Comment by alan666notb** [comment] 2019-04-16 12:54
I've seen this behaviour as well, I don't think it's connected to trackable inventory and I don't have a geokrety connection.

c:geo sometimes freezes completely while I'm typing out my log. When it starts responding again, the first thing that happens is the the 'Add to favourite' checkbox appears.

I've noticed that if I ignore it and continue typing (on the unresponsive keyboard), the words I've 'typed' do appear in the log entry once it wakes up again.

I'm using a Galaxy S9 on 4G as well.

**Comment by Lineflyer** [comment] 2019-04-16 14:37
> This issue looks similar to #7003 but to me it happens only related to loading of travelbug list. The actual log page loads fine, I don't have a problem with loading spinner.

I am pretty sure, this is actually the same according to your description. At least reading your issue it totally reflects what I tried to describe in #7003.
At the moment you cannot see a spinner as the spinner is generally broken at the moment (there is also an issue for that).

Duplicate of #7003.

**Closed by Lineflyer** 2019-04-16 14:37 UTC
