### ISSUE TITLE
Download from map is dismissed by rotate

### ISSUE THREAD

**Issue by triakcz** [cgeo/cgeo#2424] opened 2013-01-22 21:36 UTC
Hi,

In current market version I found bug ... when you download caches from mapview, and then you rotate device ... download progress is dismissed (I don't know whether it just dismissed progress or stopped downloading), but it is not working as user should expect.

Shoud I try to fix it or is there someone who knows ?

**Comment by Hauwertlhaufn** [comment] 2015-07-29 21:08
With 2015.07.29-NB-76b4276 the progess window still vanishes, and the download still continues, but c:geo doesn't crash anymore.

**Comment by Lineflyer** [comment] 2018-03-12 16:32
Duplicate of #5814

**Closed by Lineflyer** 2018-03-12 16:32 UTC
Labels: Bug, medium
