### ISSUE TITLE
Log can be sent but doesn't appear on geocaching.com

### ISSUE THREAD

**Issue by sternli** [cgeo/cgeo#5258] opened 2015-10-29 20:56 UTC
I can send a "found"-log, but this log doesn't appear on geoacaching.com
same problem for a friend on another device.
Maybe groundspeak made a change on the API?
(PS: on www.geocaching.com it works...)

**Comment by SammysHP** [comment] 2015-10-29 22:27
Please provide following information:

- System information from "about c:geo" (in the menu of the start screen)
- Exact steps to reproduce ("press xyz, input asdf, press foo")
- GC-code of the cache

**Comment by sternli** [comment] 2015-10-29 22:33
2015.09.28
show live map
select a cache e.g. GC5J851 or others
menu on the right top corner - select "Besuch loggen" and "Found" or "Write Note"
write "test" and push on the send-arrow
see the logs => ok
click on actualize => log disappears

**Comment by Lineflyer** [comment] 2015-10-29 22:35
Ohoh...Confirmed with current NB.

I can not take logs right now, but I can see:
- Login seems to work
- I can load cache
- I can compose a log and c:geo reports succesful posting

However the log is not online afterwards.
Can someone trace?

**Comment by Lineflyer** [comment] 2015-10-29 22:37
If someone can also confirm, please set a warning via status.cgeo.org

**Comment by Cappa-d** [comment] 2015-10-29 22:39
Can confirm this behaviour of the app with the Current build 2015.09.28 on my phone... just thought I am stupid as it worked last night

**Comment by Lineflyer** [comment] 2015-10-29 22:41
Managed to get a log..its inconclusive:

```
23:39:42.940 Debug cgeo 16045  [AsyncTask #4] POST http://www.geocaching.com/seek/log.aspx?ID=2511222
23:39:42.951 Debug cgeo 16045  [AsyncTask #4] 200 (2166 ms) POST http://www.geocaching.com/seek/log.aspx?ID=2511222
23:39:42.962 Info cgeo 16045  [AsyncTask #4] Log successfully posted to cache #2511222
23:39:42.964 Debug cgeo 16045  [AsyncTask #4] Saving GC352Y3 Die alte Schule (12) to DB
```

**Comment by Lineflyer** [comment] 2015-10-29 22:51
Notification posted :(

**Comment by Lineflyer** [comment] 2015-10-29 22:55
Facebook posted

**Comment by Lineflyer** [comment] 2015-10-29 23:12
```
[00:12] <Lineflyer> Info to all: Release branch is tested and ready to release anytime (beside a fix of this problem of course)```

**Comment by Cappa-d** [comment] 2015-10-30 14:16
Changes to TB do work. I grabbed a TB and this was successful... just loging a Cache does not

**Comment by beejjorgensen** [comment] 2015-10-30 16:58
Another confirmation. Nexus 5. Logged caches yesterday with issue, but logged caches today don't register on GC. Tried on 7 caches. Here's one of them: GC2FP24

**Comment by beejjorgensen** [comment] 2015-10-30 17:11
I just noticed that I did, however, successfully add a cache to my watchlist from c:geo, so that worked.

**Comment by samueltardieu** [comment] 2015-10-30 18:38
If a cursory glance of the release just built, the nightly (-NB1) or a build from master looks fine, please release. ChangeLog is up-to-date. Assigning to @Lineflyer.

**Comment by Lineflyer** [comment] 2015-10-30 20:00
Tested and working. With 2015.10.30 logging caches and TBs works normal. Search functions, image loading and live map also ok.

We published a new release some minutes ago.

Smoke test on Android 2.3 also ok.

**Closed by Lineflyer** 2015-10-30 20:00 UTC
Labels: Bug, GC, high, Regression

**Comment by rsudev** [comment] 2015-10-30 21:02
Thank you so much!

**Comment by sternli** [comment] 2015-10-30 21:15
Thank you, I'm waiting to receive the update on google play store...
Another question: Why C:Geo doesn't appear here? https://www.geocaching.com/mobile/partners/
Maybe groundspeak will inform only their partners?

**Comment by SammysHP** [comment] 2015-10-30 22:10
Because we are not official partners and do not use their API.
