### ISSUE TITLE
Use the new Google Maps API with vector maps

### ISSUE THREAD

**Issue by samueltardieu** [cgeo/cgeo#2222] opened 2012-12-03 23:15 UTC
We should use the new Google Maps API which features vector maps, rotation, etc.

See https://developers.google.com/maps/documentation/android/

**Comment by Lineflyer** [comment] 2015-04-07 14:09
I found this information on https://developers.google.com/maps-engine/ :

```
Note: The Google Maps Engine API is deprecated. Support for the Google Maps Engine (GME) product ends on January 29th, 2016. You can use your existing GME project as well as the GME API until that date. After January 29th, 2016, GME will be deactivated and the API will therefore no longer be available. 
```

Is this our current implementation?

**Comment by Lineflyer** [comment] 2015-10-13 20:04
To bring is up again... does my above link really mean, that we might be affected by this depraction as of January 29th, 2016 or is this again something else?

**Comment by rsudev** [comment] 2015-10-13 20:16
I rather think this is what applies to us: https://developers.google.com/maps/documentation/android-api/v1/

**Comment by Mainah** [comment] 2015-10-13 20:22
c:geo uses the Google Maps Android API, not the Google Maps Engine API. 
@rsudev posted the correct link. It has not been announced when/if the Maps Android API v1 will cease to function.

**Comment by Lineflyer** [comment] 2015-10-13 20:39
Thanks for clarification. I am just a little nervous, that it will stop working some day without us beeing able to tackle it on short term.

**Comment by Mainah** [comment] 2015-10-13 20:44
I do however think c:geo is long overdue for a Google Maps Android API upgrade. There are a lot of features that can be taken advantage of in the latest API.

**Comment by Lineflyer** [comment] 2015-10-13 20:56
We are well aware of that. But it needs time and work :(

**Comment by samueltardieu** [comment] 2015-10-13 21:56
And we need to switch to Gradle first if we want to make the move more easy.

**Comment by MrYaz** [comment] 2016-01-17 21:39
I personally believe that this is one of the most important features to implement since I notice more and more users are turning towards other geocaching apps using the latest Google Maps API.

Now when the switch to Gradle is soon completed this should get the full focus, IMHO.

**Comment by Lineflyer** [comment] 2016-01-17 22:10
@MrYaz I agree, but for sure this requires quite some work, where hopefully one of the devs here will find time for it.

**Comment by jeremyflathead** [comment] 2016-04-08 23:06
When someone gets the time to look at this will this also support OSMaps? As another open source project this would be awesome.  I'm a supporter of OSM and living on the fringe of a city have been able to contribute by submitting routes and correcting/updating street names, it's good to contribute.  Unfortunately, I have no idea on what's needed to do something to help with this otherwise I'd volunteer, the rest of the c:geo interface, ease of use is intuitive I don't need the offline maps but it would mean I didn't need to carry my GPS as well.

Hope you find time.

Cheers, JF

**Comment by Mainah** [comment] 2016-04-08 23:21
@jeremyflathead c:geo already has OSM support.

**Comment by Pixelfahnder** [comment] 2016-09-10 08:36
I had a look at this. So the latest SDK version supported seems to be 9 meaning there definitely is no 1.6 support any more in this. Is there still a userbase on that version?

**Comment by SammysHP** [comment] 2016-09-10 08:36
No, min version is 2.3.

**Comment by Pixelfahnder** [comment] 2016-09-10 08:38
Also this is a requirement for #5947 and further steps. I guess it is worth it.

**Comment by Pixelfahnder** [comment] 2016-09-10 08:40
@SammysHP API level 9 is Android 2.3; sorry I was unclear: I meant that the latest vesion c:geo supports is API level 9

**Comment by rsudev** [comment] 2016-09-10 09:55
Interesting way to phrase it :)
I would have said, that the minimum API level c:geo supports is 9, the maximum we checked is 23 (not sure if someone already tried N).
So from that perspective, we in the meantime aligned with the requirements for GoogleMaps v2, technically.

**Comment by Lineflyer** [comment] 2019-03-31 20:38
As one result of our "virtual team meeting" today we agreed, that due to several technical dependencies it makes most sense to focus on "Google Maps V2" integration over several other topics (like new connector to GC.com, etc.) because with using GMaps V1 we are approaching a dead end now as we are unable to raise `targetSDK` and/or `compile SDK` while it is being used.

Besides the general preference to target higher versions also Google enforces this now to be able to publish your app on Google Play. Refer also to #7354 and #7321 for more details about this.

Several points have been discussed/agreed:
1. Generate a dedicated branch in the cgeo repository as base for working on GMaps V2 implementation (will be done by @UniQP or @moving-bits ). 
2. Use the existing PR #5973 as basis for this new branch (mainly due to the fact that resources to start from scratch with a "New map" style implementation are not there) 
@rsudev Feel free to object if you think another approach would still be more meaningful for whatever reason
3. Obtain an official GMaps V2 key to be used on our CI and later in production asap. This is mainly helpful to be able to use the `debug.apk` compiled by our CI as kind of a "shadow-nightly" to test the GMaps V2 implementation
I will open dedicated issues for obtaining GMaps V2 key and configuring the CI accordingly to also build PR from the new dedicated branch

@bekuno @moving-bits @UniQP Feel free to add here, if I forget something essential.

**Comment by Lineflyer** [comment] 2019-03-31 20:46
Addon:
Created the new label `New Map Google` for issues dedicated to this topic.

**Comment by Lineflyer** [comment] 2019-04-15 13:05
Question on this:
In the (very) old comments on this thread, I read something about minimum requirements like Android 2.3 for GMaps v2. Is this still the case or do we need to raise the minSDK in order to implement it?

**Comment by Lineflyer** [comment] 2019-04-15 21:29
For your attention:

It would be nice if anyone creating issues related to Google Maps V2 could follow this:
- Assign label "New Map Google"
- Add to project "Google Maps V2" (This also applies for any PRs related)

The project function on Github provides a IMHO nice overview about the status with its Kanban table, which is automated on issue and PR status:
https://github.com/cgeo/cgeo/projects/8

**Comment by Lineflyer** [comment] 2019-07-28 20:18
Taken from #7665:

What about GMapsV2?
As stated earlier the implementation currently on branch `GoogleMapsV2` works for me with some regressions (already [documented in issues here](https://github.com/cgeo/cgeo/issues?q=is%3Aopen+is%3Aissue+label%3A%22New+Map+Google%22) ). So if someone dares to migrate it to master and would also be available for bugfixing we could do that.
Alternatively we could work on the branch by bringing it closer to `master` and fixing some regressions  on the branch. As we have [nightlies for that branch](https://download.cgeo.org/cgeo-nightly-GM.apk) its relatively easy to try it out.

**Comment by Lineflyer** [comment] 2019-09-11 09:11
I am happy to finally close this one as GMapsV2 was just implemented on `master` and already present and working in our nightlies. Big step forward!

They are some regressions though as well as possible new features, which can be found [here](https://github.com/cgeo/cgeo/issues?q=is%3Aopen+sort%3Aupdated-desc+label%3A%22New+Map+Google%22). At least those regressions should be fixed before we can release it.

**Closed** 2019-09-11 09:13 UTC
Labels: Hacktoberfest, New Map Google, Prio - High, Refactoring
