### ISSUE TITLE
Next bugfix/feature release

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#5179] opened 2015-09-03 20:56 UTC
As we do have some need to release some version soon (due to #5175 and #5177 and maybe due to #4921) let me just give some opinion from my side:

The `release` branch contains only minimal changes with respect to the shutdown of opencaching.com and the geocoding things, whereas the `master` branch has a lot of new stuff.
While I think that `master` is rather stable, I did not have any sufficient time and will not have until beginning of October to test it in deep (e.g. compass related).
So although the gap between `master` and `release` is quite big and will get bigger until beginning of October I would still prefer a release from `release` as far as I am concerned for testing it.

There could be one alternative if needed:
If we could strip the compass related changed from `master`, the remaining changes on `master` could be made ready for release without too much effort IMO. 
What I want to say is, that the compass changes need to be carefully checked, as it is a core function but I would still like to see the bundle of other changes on `master`to be out there rather soon.

Happy to get your opinion on that...

**Comment by samueltardieu** [comment] 2015-09-03 21:21
Did we get complaints from nightly users about the compass? @kumy hasn't confirmed his tests. Note that no algorithm has been changed, only the *default* sensor used and the unreliable low-power mode removed.

**Comment by Lineflyer** [comment] 2015-09-04 08:18
No reports from nightly users so far.
But AFAIK we had less complaints in general and a better PlayStore feedback since we introduced the general concept of GooglePlayServices and the sensor work as is. Therefore I do see some risk in changing the default sensor...
Maybe we should stay with the orientation and offer rotation as an option in settings (so reverse the current priority)? Could be less dangerous but still a help for users having problems (to be explained in the FAQ then).

**Comment by samueltardieu** [comment] 2015-09-04 09:09
Note that Google Play Services have nothing to do with the compass.

I'm not convinced that staying with the deprecated sensor as the default is wise, as was shown on all the Xperia series phones. But if you want to revert the default or remove the change, feel free to do it, but I'd rather not release if you don't have the time to test the changes correctly or find people to do it.

**Comment by Lineflyer** [comment] 2015-09-04 10:33
Currently discussing the sensor things in #4921 with @kumy let`s wait for the learnings from that before deciding about the best default.

**Comment by Lineflyer** [comment] 2015-09-04 12:17
I wrote a "call for translation" on Crowdin to complete the translations as we have a bunch of new strings since the last feature release.
So independently if we go for `release` or `master` branch we are prepared.

**Comment by rsudev** [comment] 2015-09-04 19:54
> Note that Google Play Services have nothing to do with the compass.
This might be true Api-wise, but is not true functionality-wise. On my phone, the usage of GMS for location (in c:geo) obviously kills the orientation sensor until the next reboot.

**Comment by rsudev** [comment] 2015-09-04 20:03
@Lineflyer I think we still have some languages without proofreaders. Should we discuss this on IRC? Or should I just try to nudge some of the recent/frequent contributors in those languages by assigning them the role?

**Comment by Lineflyer** [comment] 2015-09-07 18:41
@rsudev I usually look into the log on Crowdin and contact the person with most translations contributed asking if they are natural speaker and would like to proofread. So feel free to do it alike.

**Comment by Lineflyer** [comment] 2015-09-07 18:43
So shall we go for a RC version from master?

**Comment by rsudev** [comment] 2015-09-07 18:59
+1

**Comment by Lineflyer** [comment] 2015-09-07 19:10
On IRC we agreed that at least some icons are still missing (to be added by @kumy shortly). Afterwards we could merge `master` into `release`.

FYI:
My vacation is one and a half week from now. So I could assist with testing a RC, finetune and release but probably be away after release (nearly unable to take care for support and Play reports).

**Comment by kumy** [comment] 2015-09-07 22:20
Do you agree with new icon set at https://github.com/cgeo/cgeo/issues/5156#issuecomment-138384167?

**Comment by samueltardieu** [comment] 2015-09-08 12:42
`master` has been merged into `release` and changelogs updated. I've also moved every closed issue (and #5156) to  the `Release branch` milestone.

**Comment by samueltardieu** [comment] 2015-09-08 21:16
@Lineflyer Time to do a RC1?

**Comment by Lineflyer** [comment] 2015-09-09 17:20
will build later today

**Comment by Lineflyer** [comment] 2015-09-09 20:16
RC built. Testing now and eventually publish it on FB tomorrow if everything is OK.

**Comment by Lineflyer** [comment] 2015-09-10 20:48
RC seems good for FB, will schedule a posting for tomorrow morning CEST.

**Comment by Lineflyer** [comment] 2015-09-10 21:28
Published in german c:geo FB fan group. Posting scheduled for 08:30 tomorrow on FB main c:geo channel.

**Comment by Lineflyer** [comment] 2015-09-14 20:48
Feedback looks good on social networks and support mail.
Right now last issues I found while testing are fixed. I will test the new RC version and suggest to release tomorrow staged by 20% on first day.

**Comment by rsudev** [comment] 2015-09-14 22:19
Thanks for keeping the release rolling. I agree with your proposal and will keep an eye on the play console.

**Comment by Lineflyer** [comment] 2015-09-15 07:27
@samueltardieu Will built the release now, make a smoke test and upload and publish to 20%.
Will be on IRC today if someone wants to stop me :-)

**Comment by Lineflyer** [comment] 2015-09-15 07:31
>  I've also moved every closed issue (and #5156) to the Release branch milestone.

That would not have been necessary.
In the Wiki I described an easier option:
> Locate the milestone matching the branch used for this build, e.g. either the "master branch" or "release branch" milestone. Rename it to "YYYY-MM-DD" to indicate the release date (see closed milestones for some examples). Create a new "master branch" or "release branch" milestone with a target date some time in the future. Move all open issues from the renamed milestone to the new milestone. Github will automatically show the renamed milestone as closed now, because it contains no open issues anymore.

**Comment by Lineflyer** [comment] 2015-09-15 09:23
Release 2015.09.15 has been pushed on Google Play to 20% of users.

Remaining tasks:
- [ ] Check Google Play reports
- [ ] Push to 100%
- [ ] Create tag on Github 
-[ ] Upload APK to Github

**Comment by rsudev** [comment] 2015-09-16 17:16
Play console still has no crash reports at all for the new version (which is nice).
But I would suggest to fix the marker issue nevertheless before going 100%, what do you think?

**Comment by Lineflyer** [comment] 2015-09-16 17:39
Sounds good. Please note I am not available for testing...but it should not require extensive tests.

**Comment by samueltardieu** [comment] 2015-09-20 12:26
@rsudev What marker issue are you referring to?

**Comment by samueltardieu** [comment] 2015-09-20 12:28
That would be #5195, editing the TODO list.

**Comment by samueltardieu** [comment] 2015-09-20 12:39
Google Play reports show nothing unusual (except a crash due to send2cgeo returning an empty string once, and a strange error only occurring on MI 2 (aries) running Android 5.0 which seems to be a JIT error).

**Closed** 2015-09-24 12:04 UTC
Labels: Feedback

**Comment by kumy** [comment] 2015-09-25 21:37
I ve launched the CI job for updating fdroid repo.
