### ISSUE TITLE
Visual indication of list menu for "Stored Caches" Icon

### ISSUE THREAD

**Issue by geocrasher** [cgeo/cgeo#788] opened 2011-11-14 17:50 UTC
This is an UI improvement request.

Having not tracked the development for some time I only noticed by chance that the stored caches icon now has a context menu that opens when the user long taps on the icon. This is unexpected as the user has no visual clue of this added functionality. For instance, Google apps add visual clues when there are additional functions associated with action bars and icons; usually a down-pointing triangle.

I would suggest to add a small down-pointing arrow to the top-right hand edge of the icon, as this is the usual position, at least in left-to-right locales. For this to work, the number of stored caches needs to be shifted to the top-left hand edge of the symbol.

**Comment by kumy** [comment] 2015-08-18 23:39
(Didn't know about this feature too)

Is this the idea?

In the two first screenshots, the triangle is an image (sorry I'm not a designer :p)
In the third, I've added a textview that display character U+25BC (▼)

![screenshot_2015-08-19-00-43-56](https://cloud.githubusercontent.com/assets/176794/9345547/75df6f42-4612-11e5-8a73-11794b7a8a65.png)
![screenshot_2015-08-19-00-46-02](https://cloud.githubusercontent.com/assets/176794/9345548/76005ae0-4612-11e5-8533-9af15cb62018.png)
![screenshot_2015-08-19-01-18-25](https://cloud.githubusercontent.com/assets/176794/9345549/760606fc-4612-11e5-8370-30b697794ebf.png)

**Comment by Lineflyer** [comment] 2015-08-19 13:06
This is the idea....but maybe more like a turning sheet of paper in the upper left (so rotate your triangle counter clockwise by 90°).

**Comment by kumy** [comment] 2015-08-19 18:04
A page fold effect would be easier if we update the original icon. Do you agree to update the icon? Do we have original resource as vectorial?

**Comment by SammysHP** [comment] 2015-08-19 18:09
Without reading the issue I don't know what that triangle means. I don't think that there's a good way to visualize the long press action. Maybe we should just close this issue and "fix" it with the new design (navigation drawer etc.).

**Comment by kumy** [comment] 2015-08-19 18:29
Gimp is my friend... What about?
![test](https://cloud.githubusercontent.com/assets/176794/9365174/69fceb48-46b0-11e5-81a2-8132290d4dad.png)
![screenshot_2015-08-19-20-26-40](https://cloud.githubusercontent.com/assets/176794/9365234/c57e69f6-46b0-11e5-8ba0-551b26c0b5c5.png)

**Comment by SammysHP** [comment] 2015-08-19 20:07
Don't forget the filter button. ;)

**Comment by Lineflyer** [comment] 2015-08-19 20:28
Sure...its still not that intuitive but the best we can do with minimum effort in the current UI to give at least a hint on the secondary function.

And yes: The filter button has also a long press option which could be indicated alike,

@kumy:
The new proposal is perfect IMHO. Don't invest too much time, this is good.

**Comment by kumy** [comment] 2015-08-19 20:29
![main_filter_default2](https://cloud.githubusercontent.com/assets/176794/9368033/63ef505e-46c1-11e5-9765-db43ba79eb32.png)
![screenshot_2015-08-19-22-28-24](https://cloud.githubusercontent.com/assets/176794/9368113/c38c52fa-46c1-11e5-88f7-ea5f7cc076dd.png)

**Comment by kumy** [comment] 2015-08-19 20:30
Let me know if I commit both.

**Closed** 2015-08-20 10:15 UTC
Labels: Frontend Design

**Comment by SammysHP** [comment] 2015-08-20 16:03
The problem is that the user does not know

a) that it means "long press"
b) what will happen.

**Comment by kumy** [comment] 2015-08-21 19:52
A discussion on UX Stack Exchange on the subject: http://ux.stackexchange.com/questions/1257/indicate-long-click-option-to-user-on-android
