### ISSUE TITLE
[VTM] GeoItemLayer markers only get drawn on map move

### ISSUE THREAD

**Issue by fm-sys** [cgeo/cgeo#14787] opened 2023-11-03 10:34 UTC
### Describe your problem!

On unified map VTM, markers are not rendered directly.

@eddiemuc could you take a look?

### How to reproduce?

Suggestion for GeoItemTestLayer: 

Implement a marker which will change its appearance (two different icons) every second. 

### Actual result after these steps?

The icon will only change if map gets moved.

### Expected result after these steps?

The icon should change instantly.

### Reproducible

Yes

### c:geo Version

master

### Additional Information

See https://github.com/cgeo/cgeo/pull/14663#issuecomment-1773883489
See https://github.com/cgeo/cgeo/pull/14779#issuecomment-1792160860

**Comment by eddiemuc** [comment] 2023-11-04 11:44
PR #14791 adds a series of markers to the test layer which are constantly changing their icon. (I also used this chance to easify a bit the creation of bitmaps for markers through ImageParam). 

I am not able to consistently reproduce the error with this. However I noticed that sometimes after a while the "screen updating" seems to get "stucked" and is only continued when I move the map. Don't know why yet. It seems to be happen more consistently when I abandon my emulator for some time (e.g. while writing GitHub comments :-)) and then return to it

**Comment by eddiemuc** [comment] 2023-11-04 12:38
It is "zum kotzen"! Now that I build in some logging, I can't reproduce any more

**Comment by moving-bits** [comment] 2023-11-04 12:49
I can reproduce it reliably in the emulator by using the new elevation chart in `UnifiedMap`: If I tap on the elevation chart, a circle (marker) should appear on the map at the corresponding place along the route, but does only so after moving the map or zooming in/out. If then tapping at a different place, the circle should move accordingly, but also does so only after moving an/or zooming in/out.
I've just merged the PR for this, maybe this could help with debugging?

Besides that, if you say at what places to put logging into, I can give it a try here as well.

**Comment by eddiemuc** [comment] 2023-11-04 14:20
What can I say? Works on my emulator.... (Pixel XL API31).

I have however found a potential source of problems. It seems to me that "map.updateMap()" has to be called regularly on VTM map to do the actual drawing. This is happening in my emulator somehow automatically in the background (don't kknow what triggers it), but if this it missing it would explain the observed behaviour. I have thus extended PR #14791 with some code so this method is called regularly when map data is updated. I think it is a valid shot that might solve the problem.

**Comment by eddiemuc** [comment] 2023-11-04 14:20
BTW: the elevation chart is very cool!

**Comment by eddiemuc** [comment] 2023-11-04 14:49
[untitled3.webm](https://github.com/cgeo/cgeo/assets/6909759/9289956a-77e2-4bd5-9ec1-eb7543b75345)

**Comment by fm-sys** [comment] 2023-11-04 15:20
I can confirm that PR https://github.com/cgeo/cgeo/pull/14791 fixes the problem. The problem did suddenly appear and after that was 100% reproducible in my emulator before, and now it seems to work properly again. Thank you so much for the debugging effort!

**Comment by eddiemuc** [comment] 2023-11-04 15:54
Very good. I will merge for further testing

**Comment by moving-bits** [comment] 2023-11-04 18:32
Works like a charm now in the same emulator 🚀, thanks for being persistent in debugging this issue!

**Comment by eddiemuc** [comment] 2023-11-04 18:45
Glad to hear :-)

I will close here for now. If issue appears again, feel free to reopen

**Closed by eddiemuc** 2023-11-04 18:45 UTC
Labels: Bug, Unverified
