### ISSUE TITLE
Index offline/unsubmitted logs

### ISSUE THREAD

**Issue by Technical-13** [cgeo/cgeo#6881] opened 2017-12-10 22:00 UTC
My signature includes the [number] parameter which is great most of the time.  It's a hassle when I'm caching someplace with no service as all of those logs become the same number.  Please have the number of offline finds added in.

**Comment by pstorch** [comment] 2017-12-10 22:16
Duplicate of #987

**Closed by pstorch** 2017-12-10 22:16 UTC
