### ISSUE TITLE
Image gallery crashing on "open with c:geo"

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#13622] opened 2022-11-07 22:11 UTC
### Describe your problem!

Reported by user on support:
c:geo crashes on selecting "open with c:geo" in (old) image viewer. Happens for all caches.
(Happens only, if new experimental gallery is NOT active.)

### How to reproduce?

1. open a (stored?) cache
2. swipe to the images page
3. tap any image
4. select open with cgeo

### Actual result after these steps?

c:geo crashes and your are back in cache list (or wherever you started cache details from)

### Expected result after these steps?

display image in zoomable image viewer

### Reproducible

Yes

### c:geo Version

2022.11.05-RC

### System information

```text
System info is in the related ticket, but it's reproducible in emulator as well. Just make sure that the experimental new gallery is DISABLED.
```

### Additional Information

ticket 605011

```
 java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
        at java.util.ArrayList.get(ArrayList.java:437)
        at cgeo.geocaching.ImageViewActivity$ImageAdapter.instantiateItem(ImageViewActivity.java:120)
        at androidx.viewpager.widget.ViewPager.addNewItem(ViewPager.java:1010)
        at androidx.viewpager.widget.ViewPager.populate(ViewPager.java:1158)
        at androidx.viewpager.widget.ViewPager.populate(ViewPager.java:1092)
        at androidx.viewpager.widget.ViewPager.onMeasure(ViewPager.java:1622)
        at android.view.View.measure(View.java:26358)
        at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:735)
        at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:481)
        at android.view.View.measure(View.java:26358)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6981)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
        at androidx.appcompat.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:145)
        at android.view.View.measure(View.java:26358)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6981)
        at androidx.appcompat.widget.ActionBarOverlayLayout.onMeasure(ActionBarOverlayLayout.java:496)
        at android.view.View.measure(View.java:26358)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6981)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
        at android.view.View.measure(View.java:26358)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6981)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
        at android.view.View.measure(View.java:26358)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6981)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
        at com.android.internal.policy.DecorView.onMeasure(DecorView.java:758)
        at android.view.View.measure(View.java:26358)
        at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:3838)
        at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:2570)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2834)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2286)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8948)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1231)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1239)
        at android.view.Choreographer.doCallbacks(Choreographer.java:899)
        at android.view.Choreographer.doFrame(Choreographer.java:832)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1214)
        at android.os.Handler.handleCallback(Handler.java:942)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7898)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
```

**Comment by eddiemuc** [comment] 2022-11-08 06:03
It looks like the old image gallery tries to open the image in the new image viewer. This should not be possible (and is not currently supported, at least not to my knowledge or doing). 

Where did you find this strange option "open in c:geo"? I tried to reproduce on my current installed beta (2022.11.05-RC) and did not see it (as I would expect)

**Comment by bekuno** [comment] 2022-11-08 06:34
in Android 9
- menu point "open as file"
- system selector "open with" -> select cgeo "image"

**Comment by eddiemuc** [comment] 2022-11-08 08:13
Oh damn, the activity is marked as exported=true. This is wrong

**Comment by moving-bits** [comment] 2022-11-08 10:22
My test-case was a bit different:
- add the "new gallery feature flag" in preferences manually and set it to `false` (*)
- open a cache
- swipe to images tab
- tap on an image
- a selector opens at the bottom with two options, one of which says "open with c:geo"
  (can't say what the other was, as I'm not at my dev PC currently)

BTW: I'm not sure why step one was necessary. It was a freshly installed VM with the "new gallery feature flag" not yet set at all, still it presented the new gallery. Did we make it to default meanwhile? (And if so: Then we might want to remove the "*" indicator in bottom navigation.)

**Comment by fm-sys** [comment] 2022-11-08 10:32
> Oh damn, the activity is marked as exported=true. This is wrong

This explains the behavior. c:geo registers itself as additional image gallery app. Probably we should remove the intent filter (if any?) from the activity and mark it as exported=false

**Closed** 2022-11-10 21:59 UTC
Labels: Bug, Regression
