### ISSUE TITLE
GPX track import produces error message, tracks are imported without problem individually

### ISSUE THREAD

**Issue by dcjkfgdjhd** [cgeo/cgeo#14571] opened 2023-09-01 14:41 UTC
### Describe your problem!

I have a GPX file that contains a few caches, three tracks, one waypoint. When I try to import the tracks into cgeo, this fails with an (not very meaningful) error message.

If I export the three tracks individually, they all individually import correctly. So it appears to be an issue with the GPX file as a "collection". If you give me an email adress or some other contact info, I can provide the GPX file.

### How to reproduce?

Import the GPX file.

### Reproducible

Yes

### c:geo Version

2023.08.24

**Comment by moving-bits** [comment] 2023-09-01 15:28
Please contact us at our support address (support@cgeo.org), then we can debug into it. Thanks.

**Comment by moving-bits** [comment] 2023-09-03 08:25
Thanks for providing the GPX file. If I open the map, and select this file for "import track/route", it loads fine with current release version. It draws as sort of a "T shape standing on its head". 

Are you sure you experienced this error with 2023.08.24 and not with 2023.08.16?
I'm asking because we had fixed some GPX track import issues for files containing more than one track with the recent 2023.08.24 update (it was partly broken in 2023.08.16).

To retest this please remove the track if it's still listed in the tracks/route menu, and reload it.

**Comment by dcjkfgdjhd** [comment] 2023-09-03 12:21
![Screenshot_20230903-140611](https://github.com/cgeo/cgeo/assets/54892606/2c32a269-c168-4850-baab-7dc583552daf)
![Screenshot_20230903-140611](https://github.com/cgeo/cgeo/assets/54892606/2ae414e2-bb8c-46d6-9196-c36cdcf8cbe8)

See error toast in screenshot.

**Comment by dcjkfgdjhd** [comment] 2023-09-03 12:22
![Screenshot_20230903-140626](https://github.com/cgeo/cgeo/assets/54892606/4650b759-711e-44b8-8625-9dd7611a2c8d)

Definitely version .24

**Comment by moving-bits** [comment] 2023-09-03 12:45
My bad, sorry. I thought the fix was already part of 2023.08.24, which it is NOT, it got merged later (PR #14545).
I'll close here as the issue is fixed in the nightly versions already, and will be part of next release of c:geo.

**Closed by moving-bits** 2023-09-03 12:45 UTC
Labels: Bug, Unverified
