### ISSUE TITLE
Heading of submenus of cache list's three dot menu is illegible

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#6674] opened 2017-08-02 20:22 UTC
##### Detailed steps causing the problem:
- open list of caches
- open "sort" popup menu (which is a submemu of the three dot menu)

##### Actual behavior after performing these steps:
The popup menu's heading ("Sortierung" for me) is dark grey on medium grey and thus nearly illegible. Menu entries are in white and thus fine.

##### Expected behavior after performing these steps:
Menu heading should be another color with good contrast.

##### Version of c:geo used:
2017.07.24

##### Is the problem reproducible for you?
Yes

##### System information:
- Default dark theme in c:geo, Android 7 on Samsung phone
- same behaviour is observed for the other submemus of the three dot menu in cache list

**Comment by SammysHP** [comment] 2017-08-02 21:16
Cannot reproduce on Lineage OS (Android 7.1.3).


![](http://i.imgur.com/nqSDNzm.png)

**Comment by moving-bits** [comment] 2017-08-03 06:28
![2017-08-03 cgeo](https://user-images.githubusercontent.com/3754370/28908759-92fa7576-7825-11e7-9410-86706cdf0063.png)
Screenshot taken on Samsung A5 (2016) running Android 7.

**Comment by Lineflyer** [comment] 2017-08-03 09:13
Duplicate of #6389

**Closed by Lineflyer** 2017-08-03 09:13 UTC
