### ISSUE TITLE
Android lock screen

### ISSUE THREAD

**Issue by kia71** [cgeo/cgeo#5668] opened 2016-04-13 08:51 UTC
This is a feature request.

It would be great if the running c:geo could appear above the android lock screen. In this way, you could reach the already running c:geo without unlocking the device. I saw similar feature in Locus and Cachebox. This feature can be switched on/off in these apps.

Thanks.

**Comment by SammysHP** [comment] 2016-04-13 09:12
Duplicate of #4216.

**Closed by SammysHP** 2016-04-13 09:12 UTC

**Comment by kia71** [comment] 2016-04-13 12:02
I think my request is not the same as the request #4216.

I do not want this functioning: "to lock you click the option and to unlock you have to drag the bar to the central position"

I would like this feature: pressing the power button to activate the phone and seeing immediately c:geo without unlocking the phone.
