### ISSUE TITLE
Personal Note. Upload Button is missing

### ISSUE THREAD

**Issue by geocachermgo** [cgeo/cgeo#9379] opened 2020-11-14 15:00 UTC
**Describe the bug:**
I added a note (in this case just a time stamp), but the upload button was missing.

**To Reproduce:**
Open cache ( in my case GC8VF39). Add some text in the note.
I added a waypoint (w/o copying to the notes) and the button appeared. If I deleted the WP, the upload button stayed.

**Actual behavior/state after performing these steps:**
Upload button is missing

**Expected behavior/state after performing these steps:**
As long as the field is not empty the upload button should be visible.

**Version of c:geo used:**
2020.11.13-NB-d3efa71

**Is the problem reproducible:**
Not with other caches.

**Screenshots:**
![IMG_20201114_153936](https://user-images.githubusercontent.com/43813636/99149818-ad535d80-2690-11eb-8a11-2859bc455af0.jpg)

The cache was reloaded with this version but was stored with an earlier version.

**Comment by Lineflyer** [comment] 2020-11-14 17:45
Maybe not (yet) logged in or no longer logged in (e..g bad network or c:geo just started)?
As this is a PM feature it might only appear with valid login (which identifies you as PM).

**Comment by geocachermgo** [comment] 2020-11-14 20:40
At that moment I checked it on the main page and it was ok. But its not reset if connection is lost.
I just now closed cgeo, switched of connection, reopened, message "Not logged in ..." on the main screen. But still the stored caches have the upload button.
Since its a premium cache at the time of download I must have been logged in.
Strange. But since I cannot reproduce it.I'll close it if nobody can derive an improvment out of this report.

**Comment by MagpieFourtyTwo** [comment] 2020-11-14 21:50
This problem exists for years now, happens from time to time, but was not reproducible so far.
Most of the times it indeed happens when network coverage is bad, but OTOH it does not automatically happen when there is no network at all ...
Workaround: Usually it helps to close c:geo, remove it from memory, and start over.

**Comment by Lineflyer** [comment] 2020-11-22 11:03
Duplicate of #7850

**Closed by Lineflyer** 2020-11-22 11:03 UTC
Labels: Bug, Unverified
