### ISSUE TITLE
 FTF Badge in Map Icons

### ISSUE THREAD

**Issue by Fabio-A-Sa** [cgeo/cgeo#16269] opened 2024-10-26 19:21 UTC
### Tell us your idea!

It would be nice if caches that haven't been found for the first time (FTF) yet were highlighted on the map in some way. The concept seems feasible since there are already features that support the necessary mechanisms:

- Currently, there is a status icon bar showing recent log types (published, found, etc.) when we click on a cache on the map or view its details.
- There is also a mechanism to add a “badge” to the upper left corner of a cache icon on the map based on its state [found online - yellow, found offline - orange, didn’t find - blue, etc.].

### What solution would you suggest?

<img src="https://github.com/user-attachments/assets/e5769a9f-d0ba-4244-96c4-57bf6ccdbfcd" width="400">

<br> <br>

Two possible design suggestions:

Create a new badge with a distinct color/shape to be added to the upper left corner of the respective icon.
Highlight these caches by changing the icon color itself.
A cache is considered a potential FTF if it has no "found" logs online after its publication date by a reviewer. Simply put, a potential FTF is a cache without a yellow icon following the green icon, as shown in the attached screenshot. This distinction avoids confusion with beta tests that may have been logged earlier (whose “found” date is almost always earlier). These edge cases would not be considered in the algorithm, as they are impossible to manage automatically.

Two scenarios can occur:

- The cache is not saved for offline use: Here, navigation occurs through the online map, using the same get() mechanism to create badges but with this additional check.
- The cache is saved offline on the device: In this case, the cache retains the state it had when saved until the next refresh.

### Additional Information

This feature request is related to [issue #13906](https://github.com/cgeo/cgeo/issues/13906), though it does not require generating Pocket Queries.

**Comment by SammysHP** [comment] 2024-10-26 20:44
Duplicate of #2802 and #6735.

> The cache is not saved for offline use

In that case we don't know whether the cache has any logs. Caches shown on the live map have only very little information available.

> The cache is saved offline on the device

In that case we don't know if the state has already changed again until the data is (manually) updated.

Another problem is that there's simply not enough space for another indicator. There are already many more indications than visible in your screenshot. Also it will be difficult to find possible candidates by looking at the map (too much information).

**But** you can use filters to show only caches with zero found logs. Open the (advanced) filter menu and select "amount of logs → type: found it → value 0-0". This will make it much easier to identify FTF candidates (as long as they are stored offline or recently opened within the last three days). This method does not check if the logs were before or after the beta test. I think it is a very rare situation and not worth to handle explicitly.

**Closed by SammysHP** 2024-10-26 20:44 UTC
Labels: Feature Request, Unverified

**Comment by ztNFny** [comment] 2024-10-27 09:02
Just set up a pocket query for "has no found logs" and run it as needed from within cgeo
