### ISSUE TITLE
New top bar too large and too bright

### ISSUE THREAD

**Issue by mirabilos** [cgeo/cgeo#7274] opened 2019-01-27 13:36 UTC
In the old design, the top bar was (at least visually, if not in actual dimensions) smaller. It also was white on black, not with a bright grey background, which helped with OLED battery usage.

Please add an option to get the old design back.

**Comment by SammysHP** [comment] 2019-01-27 15:35
There is no new design, but we were forced to raise the target API version which caused some theme issues. You can find related issues with [this filter](https://github.com/cgeo/cgeo/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3Asdk26-regression+).

This issue seems to be a duplicate of #7246 and #7260.

**Closed by SammysHP** 2019-01-27 15:35 UTC

**Comment by mirabilos** [comment] 2019-01-27 15:44
Hm, no, it’s not, it’s about the generic height of the in-äpp bar (not the one above with the signal strength and clock)… I’ll upload a screenshot if I figure out how.

**Comment by mirabilos** [comment] 2019-01-27 15:50
In the normal äpp view, it takes up quite some space, but more importantly, it’s not got a black background any more. (If needed I can downgrade the APK (if that keeps the DB intact!) and make a screenshot of the old one.)

![screenshot_2019-01-27-16-45-10](https://user-images.githubusercontent.com/861078/51803259-5f6b2c80-2253-11e9-8120-42e0b0f74145.png)

In the map view the size is probably okay given the extra information, but the info below is redundant… (but this could be a mapsforge issue, I normally use the v3 one).

![screenshot_2019-01-27-16-45-32](https://user-images.githubusercontent.com/861078/51803260-5f6b2c80-2253-11e9-84a5-f9ea05ad1096.png)
