### ISSUE TITLE
First CachePopup showing causes map refresh

### ISSUE THREAD

**Issue by okainov** [cgeo/cgeo#7187] opened 2018-11-11 15:24 UTC
##### Detailed steps causing the problem:
- Make sure "New map" is used, no "Use old Mapsforge" checkbox is set in Settings
- Open Live map with OSM:Mapnik map
- Scroll to somewhere where there are some caches
- Wait for map loading (no "loading" sign should be seen)
- Click on any cache
- Check the background of popup

##### Actual behavior after performing these steps:
It's visible that map was some kind of "force reloaded" and interrupted in between. Half of tiles are missing.

##### Expected behavior after performing these steps:
Popup should not trigger map reload.

##### Version of c:geo used:
master, nightly as well

##### Is the problem reproducible for you?
Yes

##### System information:
--- System information ---
Device: SM-A320FL (a3y17ltexc, samsung)
Android version: 8.0.0
Android build: R16NW.A320FLXXU3CRH2
c:geo version: 2018.11.11-NB-4b150d4
Google Play services: enabled - 14.3.66 (040306-213742215)
Low power mode: inactive
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: rotation vector
Hide own/found: false
Map strategy: auto
HW acceleration: enabled (default state)
System language: en_AU
System date format: d/M/yy
Debug mode active: no
System internal c:geo dir: /data/user/0/cgeo.geocaching (834.6 MB free) internal
User storage c:geo dir: /storage/emulated/0/cgeo (814.6 MB free) external non-removable
Geocache data: /storage/emulated/0/Android/data/cgeo.geocaching/files/GeocacheData (814.6 MB free) external non-removable
Database: /data/user/0/cgeo.geocaching/databases/data (148.0 KB) on system internal storage
Fine location permission: granted
Write external storage permission: granted
Geocaching sites enabled:
   geocaching.com: Not logged in (No Login information stored)
Geocaching.com date format: MM/dd/yyyy
Installed c:geo plugins:  none
--- End of system information ---

--- System information ---
Device: SM-A320FL (a3y17ltexc, samsung)
Android version: 8.0.0
Android build: R16NW.A320FLXXU3CRH2
c:geo version: 2018.11.11-882f095 developer build
Google Play services: enabled - 14.3.66 (040306-213742215)
Low power mode: inactive
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: rotation vector
Hide own/found: false
Map strategy: auto
HW acceleration: enabled (default state)
System language: en_AU
System date format: d/M/yy
Debug mode active: no
System internal c:geo dir: /data/user/0/cgeo.geocaching (827.7 MB free) internal
User storage c:geo dir: /storage/emulated/0/cgeo (807.7 MB free) external non-removable
Geocache data: /storage/emulated/0/Android/data/cgeo.geocaching/files/GeocacheData (807.7 MB free) external non-removable
Database: /data/user/0/cgeo.geocaching/databases/data (400.0 KB) on system internal storage
Fine location permission: granted
Write external storage permission: granted
Geocaching sites enabled:
   geocaching.com: Not logged in (No Login information stored)
   Geocaching.su
Geocaching.com date format: MM/dd/yyyy
Installed c:geo plugins:  none
--- End of system information --

##### Other comments and remarks:
This happens only on first cache click after map load. If one cancels first popup and then clicks on another cache (without map move!), popup will be opened fine.
Each map movement triggers this weird behavior.

This does not happen with Google map, but with OSM map and offline maps.

Also a few friends of mine and I observed several times some crash during clicks on caches. I will try to investigate this more, but it could be related to this maybe....

Actual | Expected
------ | -----
<img src="https://user-images.githubusercontent.com/918446/48314723-b014a700-e5cd-11e8-8659-d2b30b0dcfc2.png" width="250"> | <img src="https://user-images.githubusercontent.com/918446/48314726-b571f180-e5cd-11e8-8219-5a557981a942.jpg" width="250">

**Comment by SammysHP** [comment] 2018-11-11 16:04
> **Version of c:geo used:**
> master

Not really…

>  c:geo version: 2018.11.11-882f095 developer build
https://github.com/cgeo/cgeo/commit/882f095

Does it also happen with master for you? Because I cannot reproduce it.

**Comment by okainov** [comment] 2018-11-11 16:11
@SammysHP checked even with nighly. Yes it happens.

```
--- System information ---
Device: SM-A320FL (a3y17ltexc, samsung)
Android version: 8.0.0
Android build: R16NW.A320FLXXU3CRH2
c:geo version: 2018.11.11-NB-4b150d4
Google Play services: enabled - 14.3.66 (040306-213742215)
Low power mode: inactive
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: rotation vector
Hide own/found: false
Map strategy: auto
HW acceleration: enabled (default state)
System language: en_AU
System date format: d/M/yy
Debug mode active: no
System internal c:geo dir: /data/user/0/cgeo.geocaching (834.6 MB free) internal
User storage c:geo dir: /storage/emulated/0/cgeo (814.6 MB free) external non-removable
Geocache data: /storage/emulated/0/Android/data/cgeo.geocaching/files/GeocacheData (814.6 MB free) external non-removable
Database: /data/user/0/cgeo.geocaching/databases/data (148.0 KB) on system internal storage
Fine location permission: granted
Write external storage permission: granted
Geocaching sites enabled:
   geocaching.com: Not logged in (No Login information stored)
Geocaching.com date format: MM/dd/yyyy
Installed c:geo plugins:  none
--- End of system information ---
```

But not with Google Map layer, there it seem to be ok. But in OSM and offline maps.

**Comment by SammysHP** [comment] 2018-11-11 16:15
Do you use the new or old implementation of Mapsforge?

**Comment by okainov** [comment] 2018-11-11 16:18
>Do you use the new or old implementation of Mapsforge?

All default settings, new.

With old is not reproducible.

**Comment by okainov** [comment] 2018-11-11 16:39
>Also a few friends of mine and I observed several times some crash during clicks on caches. I will try to investigate this more, but it could be related to this maybe....

Was able to get this more or less reproducible with official nightly (OSM layer + new mapsforge). Move the map around, click on caches, move again, click again - and after a few tries you will eventually get empty map and hanging c:geo. So I think it makes this issue more then just "ui lags"

**Comment by Lineflyer** [comment] 2018-12-13 14:12
This behaviour should be fixed meanwhile. Refer to https://github.com/cgeo/cgeo/issues/7200

**Closed by Lineflyer** 2018-12-13 14:12 UTC
Labels: Bug, New Map, Unverified
