### ISSUE TITLE
Map jumps to current position

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#12768] opened 2022-02-17 20:46 UTC
### Describe your problem!

Received three individual support mails describing the problem, that with 2022.02.13 the map jumps to the current position when changin the map source.
This reminds me of an older (fixed) issue and I cannot reproduce it.

### How to reproduce?

- Open GoogleSat map
- Scroll to a random position
- Change map source to OSM

### Actual result after these steps?

Map changes to OSM but jumps back to current device position

### Expected result after these steps?

Map changes to OSM but centered to same position as before

### Reproducible

No

### c:geo Version

2022.02.13

**Comment by Lineflyer** [comment] 2022-02-19 13:11
I can reproduce it on `release` and `master`

**Comment by fm-sys** [comment] 2022-02-19 13:26
Duplicate of  #12054 and  #10308

But the fact that we have three issues open for this problem shows us that we should really work on it ;-)

**Comment by Lineflyer** [comment] 2022-02-20 10:57
Ups...I did not see these issues before..so lets the older as I already referenced this one in the "Next bugfix release".
To anyone working on this: The above mentioned issues contain even more sequences to reproduce.

**Comment by ztNFny** [comment] 2022-02-20 11:12
Reproducable with slightly different steps:
1. Open Live Map
2. Switch to a OSM map
3. Enable location lock
4. Switch to Google maps
5. Scroll the map
6. Switch to a OSM map

_Originally posted by @ztNFny in https://github.com/cgeo/cgeo/issues/12054#issuecomment-962493259_

**Comment by eddiemuc** [comment] 2022-02-20 14:41
PR #12786 seems to fix this

**Closed** 2022-02-21 21:18 UTC
Labels: Bug, Google Play or Beta feedback, Regression
