### ISSUE TITLE
[Nightly] Syc'ing themes folder to internal storage does not work

### ISSUE THREAD

**Issue by MagpieFourtyTwo** [cgeo/cgeo#10070] opened 2021-02-24 17:30 UTC
**Describe the bug:**
After upgrading to the latest nightly this morning I got the wizard for changing the ``_themes`` folder from Legacy to SAF.
Did so, everything seemed to run smooth, the wizard sync'ed the folder to internal storage (as he reported in the popup),
but after opening the OSM live map, I do not see any themes at all anymore. And there should be plenty of ...
(about 16 or so, cause currently I experiment with different sizes for texts and symbols and stuff).

**To Reproduce:**
1. let the wizard switch your themes folder to SAF notation
2. open live map (default theme is shown)
3. try to switch to a differnet theme ...

**Actual behavior/state after performing these steps:**
Apart from ``default`` there are no themes at all.

**Expected behavior/state after performing these steps:**
My themes should be there as usual.

**Version of c:geo used:**
2021.02.24-NB-8f387a6

**Is the problem reproducible:**
Yes

**System information:**
```
--- System information ---
c:geo version: 2021.02.24-NB-8f387a6

Device:
-------
- Device type: VOG-L29 (VOG-L29EEA, HUAWEI)
- Android version: 10
- Android build: VOG-L29 10.1.0.150(C431E19R2P5)
- Sailfish OS detected: false
- Google Play services: disabled - 21.02.14 (120400-352619232)
- HW acceleration: enabled (default state)

Sensor and location:
-------
- Low power mode: inactive
- Compass capabilities: yes
- Rotation vector sensor: present
- Orientation sensor: present
- Magnetometer & Accelerometer sensor: present
- Direction sensor used: rotation vector

Program settings:
-------
- Hide caches: own/found archived
- Hide waypoints: -
- Set language: en_DE (system default)
- System date format: dd/MM/y
- Debug mode active: no
- Live map mode: true
- Global filter: display all caches
- Last backup: 23 Feb, 22:49
- Routing mode: Car

Services:
-------
- Geocaching sites enabled:
   geocaching.com: Logged in (Login OK) / PREMIUM
   extremcaching.com: Logged in (Login OK)
- Geocaching.com date format: dd MMM yy
- BRouter connection available: true
- Installed c:geo plugins: contacts

Permissions & paths:
-------
- Fine location permission: granted
- Write external storage permission: granted
- System internal c:geo dir: /data/user/0/cgeo.geocaching (64,9 GB free) v1 internal isDir(6 entries)
- Legacy User storage c:geo dir: /storage/emulated/0/cgeo (64,9 GB free) v1 external non-removable isDir(7 entries)
- Geocache data: /storage/emulated/0/Android/data/cgeo.geocaching/files/GeocacheData (64,9 GB free) v1 external non-removable isDir(238 entries)
- Public Folders: #9
- BASE: /cgeo (User-defined)[/cgeo[DOCUMENT#0:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::], default: /storage/emulated/0/cgeo[FILE#0:p-file:///storage/emulated/0/cgeo::]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo, Available:true, Files: 56, subdirs:13, free space: 64,9 GB, files on device: 13278715)
- OFFLINE_MAPS: ‎‏‎‎‎‎‎‏‎‏‏‏‎‎‎‎‎‎‏‎‎‏‎‎‎‎‏‏‏‏‏‏‎‏‎‏‏‎‏‏‎‎‎‏‏‏‏‎‏‏‎‎‎‎‎‏‎‎‏‏‎‎‎‎‏‏‏‏‎‏‎‎‎‏‏‏‎‎‏‏‏‎‏‎‏‎‎‏‎‎‏‏‎‎‏‎SD card‎‏‎‎‏‎/Locus/mapsVector (User-defined)[‎‏‎‎‎‎‎‏‎‏‏‏‎‎‎‎‎‎‏‎‎‏‎‎‎‎‏‏‏‏‏‏‎‏‎‏‏‎‏‏‎‎‎‏‏‏‏‎‏‏‎‎‎‎‎‏‎‎‏‏‎‎‎‎‏‏‏‏‎‏‎‎‎‏‏‏‎‎‏‏‏‎‏‎‏‎‎‏‎‎‏‏‎‎‏‎SD card‎‏‎‎‏‎/Locus/mapsVector[DOCUMENT#0:p-content://com.android.externalstorage.documents/tree/0123-4567%3ALocus%2FmapsVector::], default: /cgeo/maps[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/maps]] (Uri: content://com.android.externalstorage.documents/tree/0123-4567%3ALocus%2FmapsVector/document/0123-4567%3ALocus%2FmapsVector, Available:true, Files: 1234, subdirs:9, free space: 156,2 GB, files on device: 0)
- OFFLINE_MAP_THEMES: ‎‏‎‎‎‎‎‏‎‏‏‏‎‎‎‎‎‎‏‎‎‏‎‎‎‎‏‏‏‏‏‏‎‏‎‏‏‎‏‏‎‎‎‏‏‏‏‎‏‏‎‎‎‎‎‏‎‎‏‏‎‎‎‎‏‏‏‏‎‏‎‎‎‏‏‏‎‎‏‏‏‎‏‎‏‎‎‏‎‎‏‏‎‎‏‎SD card‎‏‎‎‏‎/Locus/mapsVector/_themes (User-defined)[‎‏‎‎‎‎‎‏‎‏‏‏‎‎‎‎‎‎‏‎‎‏‎‎‎‎‏‏‏‏‏‏‎‏‎‏‏‎‏‏‎‎‎‏‏‏‏‎‏‏‎‎‎‎‎‏‎‎‏‏‎‎‎‎‏‏‏‏‎‏‎‎‎‏‏‏‎‎‏‏‏‎‏‎‏‎‎‏‎‎‏‏‎‎‏‎SD card‎‏‎‎‏‎/Locus/mapsVector/_themes[DOCUMENT#0:p-content://com.android.externalstorage.documents/tree/0123-4567%3ALocus%2FmapsVector%2F_themes::], default: /cgeo/themes[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/themes]] (Uri: content://com.android.externalstorage.documents/tree/0123-4567%3ALocus%2FmapsVector%2F_themes/document/0123-4567%3ALocus%2FmapsVector%2F_themes, Available:true, Files: 1215, subdirs:8, free space: 156,2 GB, files on device: 0)
- LOGFILES: /cgeo/logfiles (Default)[/cgeo/logfiles[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/logfiles], default: (same)] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Flogfiles, Available:true, Files: 1, subdirs:0, free space: 64,9 GB, files on device: 13278715)
- GPX: /Download (User-defined)[/Download[DOCUMENT#0:p-content://com.android.externalstorage.documents/tree/primary%3ADownload::], default: /cgeo/gpx[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/gpx]] (Uri: content://com.android.externalstorage.documents/tree/primary%3ADownload/document/primary%3ADownload, Available:true, Files: 88, subdirs:10, free space: 64,9 GB, files on device: 13278715)
- BACKUP: /cgeo/backup (Default)[/cgeo/backup[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/backup], default: (same)] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Fbackup, Available:true, Files: 25, subdirs:8, free space: 64,9 GB, files on device: 13278715)
- FIELD_NOTES: /cgeo/field-notes (Default)[/cgeo/field-notes[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/field-notes], default: (same)] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Ffield-notes, Available:true, Files: 28, subdirs:0, free space: 64,9 GB, files on device: 13278715)
- SPOILER_IMAGES: /cgeo/GeocachePhotos (Default)[/cgeo/GeocachePhotos[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/GeocachePhotos], default: (same)] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2FGeocachePhotos, Available:true, Files: 0, subdirs:0, free space: 64,9 GB, files on device: 13278715)
- TEST_FOLDER: [Legacy]/data/user/0/cgeo.geocaching/files/unittest (Default)[/data/user/0/cgeo.geocaching/files/unittest[FILE#1:p-file:///data/user/0/cgeo.geocaching/files::/unittest], default: (same)] (Uri: file:///data/user/0/cgeo.geocaching/files/unittest, Available:true, Files: 0, subdirs:0, free space: 64,9 GB, files on device: -1)
- Map render theme path: 
- PersistedDocumentUris: #1
- TRACK: null
- Persisted Uri Permissions: #4
- content://com.android.externalstorage.documents/tree/0123-4567%3ALocus%2FmapsVector%2F_themes (24 Feb, 16:29):RW
- content://com.android.externalstorage.documents/tree/primary%3ADownload (7 Feb, 14:47):RW
- content://com.android.externalstorage.documents/tree/primary%3Acgeo (7 Feb, 14:44):RW
- content://com.android.externalstorage.documents/tree/0123-4567%3ALocus%2FmapsVector (7 Feb, 14:46):RW
- Database: /data/user/0/cgeo.geocaching/databases/data (v94, Size:322,6 MB) on system internal storage
 -Settings: v5, Count:225
--- End of system information ---
```

**Additional context:**
Tried with different themes folders (like e. g. ``...\_themes``, ``...\_themes\Elevate`` and ``...\_themes\Elevate\Elevate4``), but to no avail.

**Comment by eddiemuc** [comment] 2021-02-24 19:56
Not good, will.check. apologize in advance.

16 Themes? That's a lot! I was not aware that people have so many of them.

**Comment by MagpieFourtyTwo** [comment] 2021-02-24 20:03
Just did the same procedure with another phone with less themes (just Elevate 4 with Elements and Elevate plus 1 variant per theme, thus 4 themes), but the very same result: After migration there is ``default`` only.

**Comment by MagpieFourtyTwo** [comment] 2021-02-24 20:04
BTW: The old settings variable for the theme folder seems to be gone - what was it's name?

**Comment by Lineflyer** [comment] 2021-02-24 20:16
I just also upgraded to the latest nightly to test it:
I have 24 themes installed in my previous folder.

These are my findings:
- SAF dialog was opened in the correct starting folder
- After accepting and returning to the wizard, there was some unresponsiveness when trying to select "Fertig" in the wizard
- Initial copy took about 15 seconds (2066 files)
- The sync on startup is faster and takes only 2-3 seconds, still disturbing to have this on each startup
- Finally I have the same problem as reported by @MagpieFourtyTwo : Only default theme available

**Comment by Lineflyer** [comment] 2021-02-24 20:22
While checking, that the data is really synced I found it complete and seemingly correct below `shared/MapThemeData` but in my internal storage, while I have selected in c:geo Settings - Offline Data to use the external SD.

Could that be the reason?
@eddiemuc Did you take into account the different settings whether internal or SD is used for our app internal storage?

**Comment by Lineflyer** [comment] 2021-02-24 20:27
What confuses me even more is, that the application storage in my internal storage also contains pretty recent data for additional geocache data, which I would have expected to be stored on SD (as I have set it that way in our settings).

Just to be precise:
I am talking about items <2> and <5> on that page: https://github.com/cgeo/cgeo/wiki/Disk-usage-structure
I have selected to store the data in <5> but mapthemes and geocachedata appear in <2>

Remark:
My file browser does for some reason not allow to access `/Android/data/cgeo.geocaching` on my SD, so I cannot doublecheck whats stored there. Maybe a new obstacle with Android 11.

**Comment by MagpieFourtyTwo** [comment] 2021-02-24 21:15
> BTW: The old settings variable for the theme folder seems to be gone - what was it's name?

Found it: ``renderthemepath``.
But resetting it (i. e. removing ``unused::`` and deleting ``persistablefolder_offlinemapthemes``) did not work:
Although after next restart I told the wizard ``Not now`` the themes are still gone ...
And looking at the settings, the values are the same as before the above mentioned changes ... \*wonder\*

[next restart few minutes later]

Now the deleted setting is gone for true, ``renderthemepath`` is set to the old value, and even in ``Setting`` => ``Map`` there is the old Legacy folder ... nevertheless, there are not other themes than ``default`` ... currently things seem to be messed up completeley.  :/

I'll revert to yesterday's backup, to get a clean base again.

**Comment by MagpieFourtyTwo** [comment] 2021-02-24 21:18
BTW: It does not really make me happy to know that somewhere in my precious internal storage (were I do not have access to)
are about one and a half thousand file zombies loitering around ...

**Comment by Lineflyer** [comment] 2021-02-24 21:23
You are testing development versions...so expect such things :)

BTW: You can probably locate the file with a file manager.

**Comment by MagpieFourtyTwo** [comment] 2021-02-24 21:23
Yes, I know - and that's why I do backups on a daily basis.  ;)

**Comment by eddiemuc** [comment] 2021-02-24 21:27
Sorry for this. Those are really major changes and it is not easy to predict possible errors upfront.

@Lineflyer : with 2066 files I don't wonder that sync takes 2-3 seconds. This is merely the time needed by SAF to scan the folders. As I said multiple times: SAF is dead slow. 
Only thing coming to my mind is to do the sync completely in background without touching GUI at all. Need to think about this.

Wrt general error when folder is a SAF folder: have to investigate this, will (as always) most likely not be able to do this until weekend. 

Wrt storage space: I used same dir path that is used for all GeocacheData (a subfolder of it). If this points to another folder (SD vs Non-SD) than where the other GeocacheData is stored then something went terribly wrong...

**Comment by MagpieFourtyTwo** [comment] 2021-02-24 21:30
> while I have selected in c:geo Settings - Offline Data to use the external SD.
> Could that be the reason?

Don't think so, as over here it's set to internal storage (default), but nevertheless does not work.

**Comment by Lineflyer** [comment] 2021-02-24 21:31
> Wrt general error when folder is a SAF folder: have to investigate this, will (as always) most likely not be able to do this until weekend.

No hurry...take your time.

> Wrt storage space: I used same dir path that is used for all GeocacheData (a subfolder of it). If this points to another folder (SD vs Non-SD) than where the other GeocacheData is stored then something went terribly wrong... I did not touch GeocacheData mechanism to find it's place (at least not knowingly)

Then it could be some misinterpretation of what I am seeing in my file manager. I do see my Geocachedata in the internal folder in my file manager...but maybe its some kind of mounting mechanism behind as my file manager shows an empty or inaccesible `/Android/data/` folder on my SD.
I will investigate.

**Comment by MagpieFourtyTwo** [comment] 2021-02-24 21:43
Perhaps you want to give ``Cx File Explorer`` a try - he gives me access to ``/Android/data``, at least on my "Main storage" (which is in fact internal SD card)) and on the external SD card.

> BTW: You can probably locate the file with a file manager.

Don't think so, as it's living in internal storage over here - you have set to use external memory, and I suppose that's why you were able to access it in file manager.

**Comment by eddiemuc** [comment] 2021-02-25 06:58
First analysis: can't reproduce on emulator (means: works there for both a . This means I need your help investigation this further. Might be related in some twisted way to the "internal vs SD card" issue, because if Themes are looked up in one folder but stored into another this for sure would explain your observation.

@Lineflyer : this is the code line I introduced into "LocalStorage" to get the internal dir to store map theme files (I use this method both as target for the sync and as source for getting available themes of course):

![image](https://user-images.githubusercontent.com/6909759/109115052-c9aa7000-773e-11eb-8910-4b0b34eaec5b.png)

As you can see it uses already existing method "getGeocacheDataDirectory()" - and I currently trust completely the handling of c:geo wrt this directories content for all possible "SD-NonSD-internal" situations. I also trust in that this directory points to the same place at all times from c:geo startup onwards except when user explicitely changes "SD-NonSD-internal" settings. I additionally trust that in this case the content of this directory is transferred to the new place
Is this trust valid? If not, this could be the source of the problem.

Additionally:
* would it be possible for you to send me a screenshot of the (public) theme folder and the files in it? I assume that there are a lot of XML Theme files and some subdirectories like ele_res or similar, right?
* I might have to introduce some logging statements to get to the bottom of this, and I might you to rerun the situation with these logs enabled

**Comment by eddiemuc** [comment] 2021-02-25 07:00
Also I would like your opinion if we have to support use cases where users have such a big amount of theme files. Is this just a poweruser-tester-thing or does this really happen out there in the wild?

**Comment by Lineflyer** [comment] 2021-02-25 07:59
>  this is the code line I introduced into "LocalStorage" to get the internal dir to store map theme files (I use this method both as target for the sync and as source for getting available themes of course):

@pstorch As you probably introduced/refactored the LocalStorage back then, can you take a look? Looks correct to me.

**Comment by Lineflyer** [comment] 2021-02-25 10:30
@MagpieFourtyTwo 

> Don't think so, as it's living in internal storage over here - you have set to use external memory, and I suppose that's why you were able to access it in file manager.

As you wrote, that you can access the /Android/data/ folders with your CX File Explorer, please have a look into `/Android/data/cgeo.geocaching/files/GeocacheData/shared/MapThemeData/`.  This should AFAICS be the "mirror" where your themes should have been copied.

**Comment by MagpieFourtyTwo** [comment] 2021-02-25 10:47
> please have a look into ``/Android/data/cgeo.geocaching/files/GeocacheData/shared/MapThemeData/``. This should AFAICS be the "mirror" where your themes should have been copied.

In my ``(Internal SD)/Android/data/cgeo.geocaching/files/GeocacheData\shared`` there is no ``MapThemeData`` directory.
But that doesn't really surprise me, as I have configured c:geo to store it's data in internal memory,
which I can't access, as the device is not rooted.

**Comment by MagpieFourtyTwo** [comment] 2021-02-25 11:21
> screenshot of the (public) theme folder

![themes_1](https://user-images.githubusercontent.com/9889015/109145389-ba3d1e00-7762-11eb-8cab-98a6555525f4.jpg)

The csv and bat files are used to adapt sizes of texts, symbols, contour lines and stuff, but did not do any harm till now, and they do not make a difference with regard to the current problem.

![themes_2](https://user-images.githubusercontent.com/9889015/109145418-c1642c00-7762-11eb-8341-d2077349c405.jpg)

``Elevate4`` in fact contains 14 .xml, as well as one pdf and a txt file ...

![themes_3](https://user-images.githubusercontent.com/9889015/109145439-c628e000-7762-11eb-8127-5bbb33b6076d.jpg) 

... and ``ele_res`` has of course a lot more svg files, but this is most probably of no importance anyway, I guess.

![themes_4](https://user-images.githubusercontent.com/9889015/109145449-c88b3a00-7762-11eb-87e3-c1ec22ba06a1.jpg)

If you need more info, feel free to ask.  As usual. ;)

**Comment by Lineflyer** [comment] 2021-02-25 11:41
> In my (Internal SD)/Android/data/cgeo.geocaching/files/GeocacheData\shared there is no MapThemeData directory.
But that doesn't really surprise me, as I have configured c:geo to store it's data in internal memory,
which I can't access, as the device is not rooted.

Can you check which folders are shown to you in c:geo setttings - Offline data - Geocache data directory (currently active and choices you have)?

**Comment by eddiemuc** [comment] 2021-02-25 12:51
@MagpieFourtyTwo this is very helpful. seeing your screenshots and assuming that _themes is the chosen theme folder I think I know where the Problem lies:

I only scan the root theme folder for xml and zip files, not the subfolders. 

To confirm: can you try to place on theme xml file in the root _themes folder, then restart c:geo (to trigger sync) and see if this is then shown as theme in map viewer?

If this is confirmed to be the problem I will provide a fix. I was really not aware that you maintain such complex theme folder structures.

**Comment by Lineflyer** [comment] 2021-02-25 14:51
> I only scan the root theme folder for xml and zip files, not the subfolders.

That might be the cause:
My folder looks similar. It contains several subfolders only which then either contain the *.xml or even have another level of subfolders which finally contain the *.xml

**Comment by eddiemuc** [comment] 2021-02-25 14:59
Question so I fix this regression correctly: how would you expect an xml in a subfolder to be displayed in the c:geo theme selection list?

E.g. should a theme "elements.xml" in a subfolder "openandromaps" be displayed as: `openandromaps/elements.xml`? Or any other format?

**Comment by Lineflyer** [comment] 2021-02-25 15:03
IMHO just the file name without extension (as it was before).

**Comment by eddiemuc** [comment] 2021-02-25 16:12
> IMHO just the file name without extension (as it was before).

so exclusing the xml suffix but including the subfolder-name? E.g. taking @MagpieFourtyTwo s screenshot as an example (hope this is ok...) like this?

```
Elevate4/Elements F140 S120 S110
Elevate4/Elements F150 S130 S120
...

```


Then I have an additional questions: how to display themes within zip files (maybe also within subfolders)? For example let's assume that within subfolder "elevate4" in above structure there would be a ZIP file "Elevate.zip" which contains two themes "Elevate.xml" and "Elements.xml" (this is not too far-fetched since this is the structure of openandromaps-theme-zips):

![image](https://user-images.githubusercontent.com/6909759/109181678-7ced8600-778c-11eb-86a3-d2e0f2294d93.png)

How should we in this case display the two themes within this zip file into the file list. Maybe like this?:

```
Elevate4/Elevate.zip:Elevate
Elevate4/Elevate.zip:Elements
```

**Comment by eddiemuc** [comment] 2021-02-25 16:20
Or, to talk about an even more complex case: what if there is a theme zip file in a subfolder of the themes folder, and this theme zip file itself contains a theme xml within a subfolder inside the zip file (yes, this is possible too). Should this then be displayed like this?

E.g. in the following example (a Zip file "mythemes.zip" in subfolder "Elevate4" of the _themes folder, with zip-internal subfolders mythemes\Elevate where within lie two XML theme files):

![image](https://user-images.githubusercontent.com/6909759/109182674-7ca1ba80-778d-11eb-9fa1-10737ef65455.png)

Should this be displayed in the theme selection list like this?

```
Elevate4/mythemes.zip:mythemes/Elevate/Elevate
Elevate4/mythemes.zip:mythemes/Elevate/Elements
```

Or how else?

**Comment by MagpieFourtyTwo** [comment] 2021-02-25 16:21
> I only scan the root theme folder for xml and zip files, not the subfolders.

Even if this may possibly not be the only one, this is an issue for sure, as e. g. the Elevate theme comes with two subdirs by default. For more info have a look at [Elevate-Theme](https://www.openandromaps.org/en/legend/elevate-mountain-hike-theme).

> Question so I fix this regression correctly: how would you expect an xml in a subfolder to be displayed in the c:geo theme selection list?

This is a pure luxury problem, isn't it?  ;)

Behavior till yesterday:
- *all* .xml files are presented in one list (with their basename, thus no extension, no folder name)
- no matter, how deep they are "hidden" in the folder structure
- sorted in an order I was not really able to figure out ...

BUT - if you have a look at my themes list, you can probably imagine that I would be really happy to see some kind of separation or sorting ... which is the reason why I originally had put my Elevate and Elements themes (which both come with Element4) resp. their selfmade variantes separated in two extra subfolders below Elements - this way they were at least sorted by "Elements" and "Elevate" themes, which makes selection way more easy, of course.

Thus it would be great to at least get them sorted by name ... 

Extra subfolders would make no sense, as well as displaying the folder names, IMHO, as most of the users just have two of them anyway - and too long names will give display problems ...

Thus the plain file name without path or extension would be fine.

**Comment by eddiemuc** [comment] 2021-02-25 17:39
> Thus the plain file name without path or extension would be fine.

Will do. But this might result in duplicate entries if user does keep e.g. different versions of openandromaothemes in differently named zip files

**Comment by eddiemuc** [comment] 2021-02-25 18:38
@Lineflyer, @MagpieFourtyTwo 
I just created PR #10073 as a quick fix for this. This PR will now also search subfolders of Themes folder and offer them as a selection.

Several aspects are NOT yet fixed with this PR:
* naming is wrong (have xml suffixes and contain subdirectory path)
* synchronization still happens with blocking GUI at c:geo startup

I will fix those aspects in the next days. My hope however is that #10073 will keep you going for now.

**Comment by MagpieFourtyTwo** [comment] 2021-02-25 18:43
> To confirm: can you try to place on theme xml file in the root _themes folder, then restart c:geo (to trigger sync) and see if this is then shown as theme in map viewer?

Just checked with the second device (which still has yesterday's nightly): Moving the xml files and the ele_res folder to _themes works.

**Comment by MagpieFourtyTwo** [comment] 2021-02-25 18:46
[theme in selection list; just plain basename]
> Will do. But this might result in duplicate entries if user does keep e.g. different versions of openandromaothemes in differently named zip files

Sounds pretty unlikely to me. The majority will just have one of each - and would just suffer from the (probably too) long names.

**Comment by MagpieFourtyTwo** [comment] 2021-02-25 18:48
> My hope however is that #10073 will keep you going for now.

Sounds good to me. Thanks a lot!

BTW: Weekend came way faster than expected, this week ...  ;)

**Comment by eddiemuc** [comment] 2021-02-25 19:38
> > My hope however is that #10073 will keep you going for now.
> 
> Sounds good to me. Thanks a lot!
> 
> BTW: Weekend came way faster than expected, this week ...  ;)

Yeah, squeezed it in somehow, seemed to be important to you :-) But as I said, it's only half the way

**Comment by MagpieFourtyTwo** [comment] 2021-02-25 19:59
Really appreciate it!

BTW, WRT "half way": It's in fact a little bit more than that, cause seemingly the .xml extension was shown before, too.
Would have bet that it wasn't ... nevertheless it would be better without, I would say.  ;)

**Comment by MagpieFourtyTwo** [comment] 2021-02-25 22:15
@Lineflyer 
> Can you check which folders are shown to you in c:geo setttings - Offline data - Geocache data directory (currently active and choices you have)?

My current data folder is ``/storage/emulated/0/Android/data/cgeo.geocaching/files``.
If I try to go there via system file tree, thus for real trying to start with ``/storage/emulated/0``, even ``emulated`` already gets an ``Access denied``. Going there via ``(Main storage)/Android/data/cgeo.geocaching/files`` I see ``GeocacheData`` with the cached files for various caches. plus a ``shared`` folder (which contains just files, but no more folders).

If I tap the setting to change the folder, I get
- ``/storage/emulated/0/ ... (64,4 GB free) [X]``
- ``/storage/0123-4567/ ... (156,1 GB free) [_]``

BTW: I made the same observation WRT the folders with cached data of recently refreshed caches, which suddenly showed up in internal storage (saw them after switching the setting for ``Database location`` to ``On user storage [X]``) as you reported [here](https://github.com/cgeo/cgeo/issues/10070#issuecomment-785352957). Usually these are stored in ``/storage/emulated/0/Android/data/cgeo.geocaching/files`` - and I would really dislike if these would go to system storage in the future, cause these directories are a real memory eater and I would really like to keep full control of them.

**Comment by Lineflyer** [comment] 2021-02-25 22:39
@MagpieFourtyTwo 
Thats all real strange. because:
If you had previously already selected `/storage/emulated/0/...` as location I would have expected, that the MapThemesData should show up there under `/shared/`

Please be aware that switching the database location is totally unrelated to what we are talking about here.
Pleas carefully read the Wiki article to help understanding the difference: https://github.com/cgeo/cgeo/wiki/Disk-usage-structure

It might be, that we screwed up something totally here, but I have no clue at this moment.
I will test on a pre-Android 11 rooted device to be able to access all the locations and see its contents to check whether it matches expectation.

**Comment by MagpieFourtyTwo** [comment] 2021-02-25 23:29
I'm aware of the difference between database folder and storage of internal data - but you asked for this directory ... or have I perhaps misunderstood your question?

**Comment by Lineflyer** [comment] 2021-02-25 23:51
I meant, that "Database location" setting is a different thing than "GeocacheData location".

**Comment by MagpieFourtyTwo** [comment] 2021-02-26 01:16
> But as I said, it's only half the way

Just checked with this night's nightly - and themes work again. Even with nested folders for Elevate and Elements. Great.

And, with regard to the "long names vs. basename" question: 

![Selection - fullname](https://user-images.githubusercontent.com/9889015/109239986-e1353780-77d6-11eb-994c-be435df026cf.jpg)  ![Selection - basename](https://user-images.githubusercontent.com/9889015/109239992-e3979180-77d6-11eb-8893-6017d7acdb03.jpg)

With long names it looks a little bit overcrowded and confusing ... IMO. Like the short one way better.

@Lineflyer With the new nightly I indeed see all the sync'ed themes stuff in ``/storage/0/Android/data/cgeo.geocaching/files/GeocacheData/shared/MapThemeData`` now. So everything fine, at least half way, as @eddiemuc would say. ;)

Plus, BTW, one file per folder named ``_cgeoFolderSyncInfo.txt``, which I better leave untouched, I guess.  ;)

**Comment by eddiemuc** [comment] 2021-02-26 06:22
> Plus, BTW, one file per folder named _cgeoFolderSyncInfo.txt, which I better leave untouched, I guess. ;)

Yes please :-) It contains file metadata (length and size) for the source folder to check what needs to be synced again and what not. Necessary to prevent unneeded copying.

But we can rename this file if you like?

**Comment by eddiemuc** [comment] 2021-02-26 06:24
> @Lineflyer With the new nightly I indeed see all the sync'ed themes stuff in /storage/0/Android/data/cgeo.geocaching/files/GeocacheData/shared/MapThemeData now.

Am I understanding you correctly that my last change resulted on the themes being synced to a different target folder? That would be very strange because I did not change anything in that area...

**Comment by eddiemuc** [comment] 2021-02-26 06:30
> With long names it looks a little bit overcrowded and confusing ... IMO. Like the short one way better.

My current plan:
* Remove suffix xml and subfolders
* Also for themes in zip: remove zip file folder, zip file.name, zip-inside subfolder and suffix (just plain name)
* Order result alphabetically

But: in corner cases, this can result in duplicate names (pointing to different files) being displayed

**Comment by MagpieFourtyTwo** [comment] 2021-02-26 14:08
> But we can rename this file if you like?

For me it's perfectly fine, do in fact not care at all.  ;)
Any special reason why you use length/size instead of an IMO more reliable checksum?
Cause in a very common scenario over here it's just about changing digits in the .xml (i. e. increase sizes),
which may possibly result in being missed by the sync-comparison ....?

> Am I understanding you correctly that my last change resulted on the themes being synced to a different target folder? That would be very strange because I did not change anything in that area..

Nop - it was not *another* folder but *one at all,* eventually. With the previous version I was not even able to find the sync'ed stuff. Most probably it did not even happen at all ... or I am having some more zombies now, living somewhere in the unrevealed depths of my system memory ...  ;)

[...Plan...]
Sounds very good to me. Esp. the [s|sh]ort part(s) thrill(s) me.  ;)
But ... while thinking about it:  Given the cases where a theme .xml lives in an archive, it may possibly be a good idea to nevertheless add the zip file's name, cause otherwise it may be hard for the user to deal with it (update/remove/...), cause it's location may not be too obvious for the user ...?

**Comment by eddiemuc** [comment] 2021-02-26 14:55
> Any special reason why you use length/size instead of an IMO more reliable checksum?
> Cause in a very common scenario over here it's just about changing digits in the .xml (i. e. increase sizes),
> which may possibly result in being missed by the sync-comparison ....?

I mistyped above, I use "last modified" and "size". The reason I do not use checksum is simple: it would be far too slow to calculate all the checksums in the source folder on "check if something changed", because I had to read all files. The whole sync process is only necessary because SAF is so dead slow, so I have to carefully avoid any avoidable file operation.

> [...Plan...]
> Sounds very good to me. Esp. the [s|sh]ort part(s) thrill(s) me. ;)
> But ... while thinking about it: Given the cases where a theme .xml lives in an archive, it may possibly be a good idea to nevertheless add the zip file's name, cause otherwise it may be hard for the user to deal with it (update/remove/...), cause it's location may not be too obvious for the user ...?

sure, no problem. In case someone downloads the themes from OpenandroMaps this could then result in two entries like e.g. "Elevate.zip:Elevate" and "Elevate.zip:Elements" ("Elevate.zip" being the zip file name and "Elevate.xml"/"Elements.xml" being the xml themes inside)

**Comment by MagpieFourtyTwo** [comment] 2021-02-26 15:42
> In case someone downloads the themes from OpenandroMaps this could then result in two entries like e.g. "Elevate.zip:Elevate" and "Elevate.zip:Elements" ("Elevate.zip" being the zip file name and "Elevate.xml"/"Elements.xml" being the xml themes inside)

Yep. this is the way it's intended to be, I would say.
BTW: I was not even aware of the possibility to leave the theme stuff in a (zip) archive.
Does this really make sense?
Or, to be more precise: Is the handling of archive contents really that performant that c:geo should "allow" to use it this way?

**Comment by eddiemuc** [comment] 2021-02-26 18:16
> BTW: I was not even aware of the possibility to leave the theme stuff in a (zip) archive.
> Does this really make sense?
> Or, to be more precise: Is the handling of archive contents really that performant that c:geo should "allow" to use it this way?

Actually I Implemented this recently inside mapsforge project. Reason was that SAF has an outrageously bad performance when dealing with many (small) files, even when reading them. See e.g. #10075. At the time I wanted to solve this issue by only allowing zipped themes in the future (because then SAF has to open just one file and is in summary way faster). But seeing that this was not enough to speed things adequately and also would desupport existing structures, I added the syncing (because now after sync theme files can be accessed via good old fast File interface)

I fear this will not be the last slowness we see with SAF.

**Comment by eddiemuc** [comment] 2021-02-27 07:27
@bekuno I have a question wrt mapsforge version used in c:geo.

I think it was you helping to integrate an intermediate version of mapsforge library for now se we could use the new ZipMapThemes-features.

In the meantime I realized that I need an additional method in this class on mapsforge side. I already provided the PR to mapsforge and it was merged. NowI want to use this method in c:geo of course. This means I would have to "upgrade" the version of mapsforge which we pull into c:geo.

In following screenshot you see the three most recent commits on mapsforge master branch. The third one is the state we are currently using, the first one is the one I want to be used:
![image](https://user-images.githubusercontent.com/6909759/109378767-6d2d8900-78d5-11eb-981f-839987bc8976.png)

Question: what do I need to do so the first version is used?

I found in build.gradle the following line:

![image](https://user-images.githubusercontent.com/6909759/109378785-89312a80-78d5-11eb-82c5-43c1177a03ed.png)

Would I just need to change the value of "mapsforgeVersion" to the new commit hash?

**Comment by eddiemuc** [comment] 2021-02-27 07:29
@bekuno followup question: I see that the "mapsforgeVersion" in our build.gradle contains the first 10 digits of the commit hash. Is this the right way to referfence a commit here (take first 10 digits of the 40-digits-long full hash)?

**Comment by bekuno** [comment] 2021-02-27 08:32
To be fast:
see the description in PR #9923
The short hash form is wide used in Git for references. I think that is used because the chance of a collision is small enouth for a single repo. Its not my invention.

**Comment by eddiemuc** [comment] 2021-02-27 08:45
@MagpieFourtyTwo , @Lineflyer 
wioth regards to the "user friendly map theme display", please reference to PR #10078 for an implementation. I described there in detail what I implemented and how this will look like in a result. I followed approach discussed here, in case you have amending wishes please let me know in the PR.

**Comment by eddiemuc** [comment] 2021-02-27 08:47
> To be fast:
> see the description in PR #9923
> The short hash form is wide used in Git for references. I think that is used because the chance of a collision is small enouth for a single repo. Its not my invention.

Thanks for quick help!

**Closed** 2021-02-27 15:58 UTC
Labels: Bug, Regression SDK30/SAF
