### ISSUE TITLE
"Side entry" scenario

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#10247] opened 2021-03-23 21:09 UTC
Cannot test at this moment, but reading support tickets and survey feedback the following came to my mind:

The first start after upgrade to SAF might not be, that c:geo is normally started, but also by clicking a cache link from mail, etc.
How does this scenario behave?

**Comment by eddiemuc** [comment] 2021-03-24 06:39
Good question.

Can't test either. My guess would be that Wizard is not started in this case, so c:geo behaves as if the user clicked "Not Now" in it (and folders are not migrated).

But maybe this is even the wanted behaviour?

**Comment by fm-sys** [comment] 2021-03-24 06:58
> But maybe this is even the wanted behaviour?

Tested it via resetting the base folder to legacy and everything seems to work normal (including live map, etc) without wizard. IMHO this is totally Ok and the "polite" way if users don't have much time and just want to take a short look at a cache...

**Comment by Lineflyer** [comment] 2021-03-24 11:16
@fm-sys  Thanks for giving it a try. I would agree, that this is OK.

**Comment by bekuno** [comment] 2021-03-25 21:51
I did some tests two day before on this area, open caches from mail and using the quick launches.
The messages are in the same way as if the user clicked "Not Now".
The splash is relative short.
A possible problem could be that some users use the quick launch buttons by default and therefore do not understand why c:geo does not work as before.

![Screenshot_20210324-113040_cgeo1](https://user-images.githubusercontent.com/32555742/112371874-654be380-8cdf-11eb-9765-1f4922ba979c.jpg)
![Screenshot_20210324-112937_cgeo1](https://user-images.githubusercontent.com/32555742/112371951-7a287700-8cdf-11eb-85d8-db36c831ed19.jpg)

**Comment by Lineflyer** [comment] 2021-03-25 21:54
Why does it say in your screenshot, that the folders are not accesible... The legacy should still work, shouldn't it?

**Comment by bekuno** [comment] 2021-03-25 21:57
> 
> 
> Why does it say in your screenshot, that the folders are not accesible... The legacy should still work, shouldn't it?

Good question - @eddiemuc @moving-bits ?

**Comment by eddiemuc** [comment] 2021-03-26 06:54
> > 
> > 
> > Why does it say in your screenshot, that the folders are not accesible... The legacy should still work, shouldn't it?
> 
> Good question - @eddiemuc @moving-bits ?

This should indeed work, provided the folder does indeed exist. 

@bekuno :
* Does the folder indeed exist?
* Anything helpful in the logs?
* If you go into map viewer, can you use the offline maps in the named folder? 

I remember a problem in the past where it seemed that SD card folders are not accessible directly after app start but only a few seconds later. It was in reaction to this problem that I removed auto-set-to-default on startup when folders are not accessible. @Lineflyer may remember this. If this turns out to be the case I can somehow remove the warning (I wonder why it shows up for map folder on cache details opening anyway)

**Comment by fm-sys** [comment] 2021-03-26 06:57
@bekuno did you tested it on a android 11 emulator? A few months ago, we found that legacy folder access is possible with a normal Android 11 device but not with the emulator...(Probably that developers are reminded that they need to rework the app?)

However, I suppose this will work on normal devices. @Lineflyer Can you verify this with your android 11 device? (You can set the folder to legacy via `Settings > System > base folder > default`)

**Comment by eddiemuc** [comment] 2021-03-26 07:10
@fm-sys good catch, now that you say it I remember this too. This could indeed be the reason. I remember that I concluded back in the days that Google enforces stricter rules in the emulators than on real devices

**Comment by Lineflyer** [comment] 2021-03-26 10:20
>  @Lineflyer Can you verify this with your android 11 device? (You can set the folder to legacy via Settings > System > base folder > default)

I have tested this in the beginning already (meaning to skip the wizard and use c::geo with legacy setup. Was working normal on my Android 11 devices).

> remember a problem in the past where it seemed that SD card folders are not accessible directly after app start but only a few seconds later. It was in reaction to this problem that I removed auto-set-to-default on startup when folders are not accessible. @Lineflyer may remember this. I

Yes. That was due to the fact, that my SD is encrypted and Android needs some seconds up to a minute to mount the encrypted card after booting the system. The problem showed up when I started c:geo in that time frame.
But it was more a problem with SAF folders, as those were invalidated at that point and I needed to set them up again . That was fixed by @eddiemuc. Using legacy folders I never had such problem.

**Comment by bekuno** [comment] 2021-03-26 13:29
It was my physicle device.
--- System information ---
c:geo version: 2021.03.22-RC

Device:
-------
- Device type: SM-N950F (greatltexx, samsung)
- Android version: 9
- Android build: PPR1.180610.011.N950FXXSEDTL1
- Sailfish OS detected: false
- Google Play services: disabled - 21.09.15 (100400-361652764)
- HW acceleration: enabled (default state)

Sensor and location:
-------
- Low power mode: inactive
- Compass capabilities: yes
- Rotation vector sensor: present
- Orientation sensor: present
- Magnetometer & Accelerometer sensor: present
- Direction sensor used: orientation

Program settings:
-------
- Hide caches: -
- Hide waypoints: -
- Set language: de_DE (system default)
- System date format: dd.MM.yy
- Debug mode active: no
- Live map mode: true
- Global filter: display all caches
- Last backup: 24. Jan., 05:57
- Routing mode: Gehen
- Map: Kombiniert (Offline)
  - Id: cgeo.geocaching.maps.mapsforge.MapsforgeMapProvider$OfflineMultiMapSource
  - Atts: <p><b>CanaryIslands_ML.map</b>:<br>Maps: (c)Christian Kernbeis, Themes: (c)Tobias Kuehn, www.openandromaps.org 2012-2018</p><p><b>Czech_Republic.map</b>:<br>Maps: (c)Christian Kernbeis, Themes: (c)Tobias Kuehn, www.openandromaps.org 2012-2016</p><p><b>Germany_Mid.map</b>:<br>Maps: (c)Christian Kernbeis, Themes: (c)Tobias Kuehn, www.openandromaps.org 2012-2019</p><p><b>Germany_North.map</b>:<br>Maps: (c)Christian Kernbeis, Themes: (c)Tobias Kuehn, www.openandromaps.org 2012-2019</p><p><b>Germany_South.map</b>:<br>Maps: (c)Christian Kernbeis, Themes: (c)Tobias Kuehn, www.openandromaps.org 2012-2019</p>
  - Theme: Elements.xml

Services:
-------
- Geocaching sites enabled:
   geocaching.com: Logged in (Anmeldung OK) / PREMIUM
   extremcaching.com: Logged in (Anmeldung OK)
   opencaching.de: Logged in (Anmeldung OK)
   Geocaching.su: Logged in (Anmeldung OK)
- Geocaching.com date format: dd.MM.yy
- BRouter installed: true / connection available: true
- Installed c:geo plugins: contacts

Permissions & paths:
-------
- Fine location permission: granted
- Write external storage permission: granted
- System internal c:geo dir: /data/user/0/cgeo.geocaching (9,5 GB free) v2 internal isDir(10 entries)
- Legacy User storage c:geo dir: /storage/emulated/0/cgeo (9,4 GB free) v2 external non-removable isDir(5 entries)
- Geocache data: /storage/6363-3661/Android/data/cgeo.geocaching/files/GeocacheData (87,6 GB free) v2 external removable isDir(3495 entries)
- Internal theme sync (is turned off): /data/user/0/cgeo.geocaching/MapThemeData (9,5 GB free) v2 internal isDir(0 entries)
- Public Folders: #9
- BASE: /cgeo (Benutzerdefiniert)[/cgeo[DOCUMENT#0:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::], default: /storage/emulated/0/cgeo[FILE#0:p-file:///storage/emulated/0/cgeo::]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo, Av:true, Files:184, dirs:12, totalFileSize:1,9 GB, free space: 9,4 GB, files on device: 1761280)
- OFFLINE_MAPS: SD-Karte/Android/maps/vector (Benutzerdefiniert)[SD-Karte/Android/maps/vector[DOCUMENT#0:p-content://com.android.externalstorage.documents/tree/6363-3661%3AAndroid%2Fmaps%2Fvector::], default: /cgeo/maps[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/maps]] (Uri: content://com.android.externalstorage.documents/tree/6363-3661%3AAndroid%2Fmaps%2Fvector/document/6363-3661%3AAndroid%2Fmaps%2Fvector, Av:true, Files:8, dirs:0, totalFileSize:5,3 GB, free space: 87,6 GB, files on device: 0)
- OFFLINE_MAP_THEMES: SD-Karte/Android/maps/themes (Benutzerdefiniert)[SD-Karte/Android/maps/themes[DOCUMENT#0:p-content://com.android.externalstorage.documents/tree/6363-3661%3AAndroid%2Fmaps%2Fthemes::], default: SD-Karte/Android/maps/vector/_themes[PERSISTABLE_FOLDER(OFFLINE_MAPS)#1:p-content://com.android.externalstorage.documents/tree/6363-3661%3AAndroid%2Fmaps%2Fvector::/_themes]] (Uri: content://com.android.externalstorage.documents/tree/6363-3661%3AAndroid%2Fmaps%2Fthemes/document/6363-3661%3AAndroid%2Fmaps%2Fthemes, Av:true, Files:397, dirs:1, totalFileSize:1,7 MB, free space: 87,6 GB, files on device: 0)
- LOGFILES: /cgeo/logfiles (Standard)[/cgeo/logfiles[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/logfiles], default: (same)] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Flogfiles, Av:true, Files:10, dirs:0, totalFileSize:4,9 MB, free space: 9,4 GB, files on device: 1761280)
- GPX: /cgeo/gpx (Standard)[/cgeo/gpx[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/gpx], default: (same)] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Fgpx, Av:true, Files:1, dirs:0, totalFileSize:48,1 KB, free space: 9,4 GB, files on device: 1761280)
- BACKUP: /cgeo/backup (Standard)[/cgeo/backup[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/backup], default: (same)] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Fbackup, Av:true, Files:8, dirs:4, totalFileSize:1,9 GB, free space: 9,4 GB, files on device: 1761280)
- FIELD_NOTES: /cgeo/field-notes (Standard)[/cgeo/field-notes[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/field-notes], default: (same)] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Ffield-notes, Av:true, Files:165, dirs:0, totalFileSize:346,1 KB, free space: 9,4 GB, files on device: 1761280)
- SPOILER_IMAGES: /cgeo/GeocachePhotos (Standard)[/cgeo/GeocachePhotos[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/GeocachePhotos], default: (same)] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2FGeocachePhotos, Av:true, Files:0, dirs:3, totalFileSize:0 B, free space: 9,4 GB, files on device: 1761280)
- TEST_FOLDER: [Veraltet]/data/user/0/cgeo.geocaching/files/unittest (Standard)[/data/user/0/cgeo.geocaching/files/unittest[FILE#1:p-file:///data/user/0/cgeo.geocaching/files::/unittest], default: (same)] (Uri: file:///data/user/0/cgeo.geocaching/files/unittest, Av:true, Files:0, dirs:0, totalFileSize:0 B, free space: 9,5 GB, files on device: -1)
- Map render theme path: Elements.xml
- PersistedDocumentUris: #1
- TRACK: null
- Persisted Uri Permissions: #3
- content://com.android.externalstorage.documents/tree/6363-3661%3AAndroid%2Fmaps%2Fthemes (24. März, 17:15):RW
- content://com.android.externalstorage.documents/tree/6363-3661%3AAndroid%2Fmaps%2Fvector (24. März, 17:15):RW
- content://com.android.externalstorage.documents/tree/primary%3Acgeo (24. März, 07:57):RW
- Database: /storage/emulated/0/Android/data/cgeo.geocaching/files/databases/data (v94, Size:499,6 MB) on user storage
 -Settings: v5, Count:207
--- End of system information ---

**Comment by eddiemuc** [comment] 2021-03-26 14:16
@bekuno from your sys info I can see that you already set the maps folder (and all other folders) to SAF. Do you get the above error message nevertheless? Because I can't find the path in the message in your settings.

Maybe the folder paths are not set correctly to the values in settings when entering c:geo "from the side".

**Comment by bekuno** [comment] 2021-03-26 14:51
@eddiemuc I had after the tests startet the SAF migration. So the system information is the current state, not for the test situation.

**Comment by bekuno** [comment] 2021-03-26 14:55
On migration I did accept the presented folders, as they where the current and correct one. So I would say that there was no need to ask for them from my side.

**Comment by bekuno** [comment] 2021-03-26 14:57
One reason to start the migration was that only online maps could used.

**Comment by eddiemuc** [comment] 2021-03-26 16:04
@bekuno and did the error message on "side entry" disappear after migration?

**Comment by bekuno** [comment] 2021-03-26 16:09
no such messages after migration, I have the full (offline) map list

**Comment by eddiemuc** [comment] 2021-03-26 19:23
Can't reproduce the error message. Tried resetting device to legacy folder on an android 30 emulator, could access the folder. 
Dont know what heppened here, maybe this only fails sporadically. I would advise to close this issue

**Comment by bekuno** [comment] 2021-03-26 21:42
The device is at android 9 = api 28. But it could of course be one of the strange samsung behaviours.

**Comment by eddiemuc** [comment] 2021-03-28 07:06
Is there anything left to do or can this be closed?

**Comment by bekuno** [comment] 2021-03-28 18:06
Please let it open. I will try to reproduce the situation befor SAF migration.

**Comment by fm-sys** [comment] 2021-05-07 14:31
> 
> 
> Please let it open. I will try to reproduce the situation befor SAF migration.

@bekuno anything left, or can we close this issue?

**Closed** 2021-05-07 14:34 UTC
Labels: Unverified
