### ISSUE TITLE
Empty log screen shown while posting log

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#7055] opened 2018-06-11 21:03 UTC
This occured to me only after bebe0e89f4fbe6da36a497bc78fe8f298a93a6d5 was merged.
@pstorch 

##### Detailed steps causing the problem:
- Compose a "found" log for a gc.com  cache
- Send the log online

##### Actual behavior after performing these steps:
The normal logging progress status is shown. The log is posted.
Just after the progress is done and the log is posted, the logging page is shown again with type "Note" and empty log text.
After 1-2 seconds the logging screen is closed and the result is normal.

##### Expected behavior after performing these steps:
If possible it should be avoided, that this "interim" logging screen is shown just after the log has been posted

##### Version of c:geo used:
2018.06.08-NB

##### Is the problem reproducible for you?
Yes

**Comment by pstorch** [comment] 2018-06-12 11:03
Yes, due to my change the screen is first resetted and then closed, because when closing the screen there is this automatic save logic when there are changes. This Activity is a bit cumbersome. I tried to consolidate a bit last time, but unfortunately caused this side effect. I haven't experienced this delay while testing, but will have another look at it.

**Comment by pstorch** [comment] 2018-06-12 20:54
Is it really up to 2 seconds? I tried to reproduce it and log success message and the closing of the dialog is nearly immediately. And my device is not the fastest, it is already a few years old.

**Comment by Lineflyer** [comment] 2018-06-12 21:08
Yes, up to..but usually less. It seems to be longer depending on log length or some other dependency.

Anyway I considered it as "low", just asking if the process flow can be optimized to avoid it.
If this is not possible with reasonable effort, then lets close it.

**Closed** 2018-06-20 19:46 UTC
Labels: Bug, Frontend Design, low
