### ISSUE TITLE
Offline find counter [NUMBER] is inaccurate and getting worse

### ISSUE THREAD

**Issue by Zamlet** [cgeo/cgeo#10007] opened 2021-02-14 07:36 UTC
The count of my finds that is shown offline and filled in on my signature through [NUMBER] is way off and getting even worse.  The count is considerably higher than my actual find count.  I can find no way to reset it.

1. Add the [NUMBER] placeholder to a custom signature (Settings -> Logging -> Signature).
2. Log several finds offline.

The offline count was accurate at first but has grown increasingly inaccurate over time.  c:geo appears to be adding ghost caches to the count, or logging some finds twice, or somehow adding more than the actual count.  It has never dipped below the actual count; it has gotten steadily higher.  I cannot find any pattern to it.

I expected that the count would remain accurate, or that there would at least be some way to sync it with the actual count when online.  If there's any way to reset this without losing other data, I can't find it either in the User Guide or in the FAQ.

I am currently using version 2021.01.16, but this problem has been going on for several months now.

Problem is reproducible, at least in that I cannot correct the erroneous count by any known, documented means.

```
--- System information ---
Device: P01M (WW_P01M, asus)
Android version: 5.0
Android build: LRX21V.WW_P01M-V4.7.1-20160419
c:geo version: 2021.01.16
Google Play services: disabled - 21.02.14 (020700-352619232)
Low power mode: inactive
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: orientation
Hide caches: archived
Hide waypoints: -
HW acceleration: enabled (default state)
System language: en_US / user-defined language: 
System date format: M/d/y
Debug mode active: no
System internal c:geo dir: /data/data/cgeo.geocaching (4.6 GB free) internal
User storage c:geo dir: /storage/emulated/0/cgeo (4.6 GB free) external non-removable
Geocache data: /storage/emulated/0/Android/data/cgeo.geocaching/files/GeocacheData (4.6 GB free) external non-removable
Database: /storage/emulated/0/Android/data/cgeo.geocaching/files/databases/data (60.6 MB) on user storage
Last backup: Dec 14, 2020, 11:14
GPX import path: /storage/emulated/0/cgeo/gpx
GPX export path: /storage/emulated/0/cgeo/gpx
Offline maps path: /storage/emulated/0/Download
Map render theme path: 
Live map mode: true
Global filter: display all caches
Sailfish OS detected: false
Fine location permission: granted
Write external storage permission: granted
Geocaching sites enabled:
geocaching.com: Logged in (Login OK) / PREMIUM
Geocaching.com date format: dd MMM yy
Installed c:geo plugins:  none
BRouter connection available: true
--- End of system information ---
```

Just in case it matters, I log most if not all of my finds using c:geo's offline log capability, then Export Field Notes to send the information to my geocaching.com account's Drafts section, and then I do the actual posting online.  I don't know if any of this matters, but thought I should include the info anyway.  Disclaimer: I am not an Android guru, so if there's more information you need, you may have to tell me how to get it for you.

**Comment by fm-sys** [comment] 2021-02-14 08:43
Thanks for contacting us!


As You wrote, you are not logging the caches directly from within c:geo, so the problem is probably that c:geo has stored offline logs for caches which are already logged online. 


To easily find remaining offline logs, go to the list "History" and filter for "With personal data" > "With offline log". Then you can delete the "ghost offlinelogs" for these caches. 

However, a question that is not directly related to the issue: Should we offer an option "☑ delete offline logs" while exporting field notes?

**Comment by fm-sys** [comment] 2021-02-25 20:38
Closing since no future feedback occurred. BTW, you could also try to use the [ONLINENUM] template instead, which will ignore all cgeo offline logs...

**Closed by fm-sys** 2021-02-25 20:38 UTC
Labels: Bug, Unverified
