### ISSUE TITLE
Importing .loc file has wrong progress dialog

### ISSUE THREAD

**Issue by triakcz** [cgeo/cgeo#3413] opened 2013-11-03 21:29 UTC
I discovered that when I import .loc file I see whole time progress dialog for reading of file (process of importing caches is working, but progress is still showing 100% of reading a file, nothing about downloading caches from websites).

http://i.imgur.com/Dbru1Bc.png

This problem is present on android 4.0, ASUS FonePad. I don't know if elsewhere.

If you can try I would like to know if I'm alone facing this issue or not.

**Comment by samueltardieu** [comment] 2015-01-02 14:46
Duplicate of #3126.

**Closed by samueltardieu** 2015-01-02 14:46 UTC
