### ISSUE TITLE
Owned OC caches sometimes not recognized as owned

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#10877] opened 2021-06-06 16:46 UTC
## Bug description 

I noticed by myself and was made aware by other users on support, that (under certain yet unknown conditions) owned OC-caches are not recognized as owned cache.

### Steps to reproduce the problem

Not sure yet. 
Plainly opening it works fine..Might be related to live map loading or some other special circumstance.

## c:geo version 

Nightlies

## Reproducible 

No

## System information 

```
Paste your system information here
```

**Comment by eddiemuc** [comment] 2024-02-11 20:26
Teammeeting 11.2.24: no reaction since 2021, thus closing for now. Feel free to reopen if reproducible/still an issue

**Closed by eddiemuc** 2024-02-11 20:26 UTC
Labels: Bug, Unverified, Connector OC
