### ISSUE TITLE
DBExtentions - c:geo crashes

### ISSUE THREAD

**Issue by fm-sys** [cgeo/cgeo#8717] opened 2020-07-31 18:15 UTC
**Describe the bug:**
When trying to use the new DBExtentions c:geo crashes on my device.
At first I thought the error was in my implementation of the offlinenum variable, but the error also occurs at PendingDownload (OSM offline map files downloader #8707). To test the map files downloader i used 2020.07.31-NB-146e5f4

**To Reproduce:**
1. Go to Live Map
2. Click on 'download offline map'
3. Start a download...
--> crash! from the second time even if you only click on 'download offline map' in live map

**Expected behavior/state after performing these steps:**
Everything shoud work fine

**Is the problem reproducible:**
Yes - at least on my device

**System information:**
```
--- System information ---
Device: Telekom Puls (Telekom_Puls, T-Mobile)
Android version: 5.0.1
Android build: LRX21M.vC29-0 release-keys
c:geo version: 2020.07.31-NB-146e5f4
Google Play services: enabled - 20.24.14 (020300-319035315)
Low power mode: inactive
Compass capabilities: no
Rotation vector sensor: absent
Orientation sensor: absent
Magnetometer & Accelerometer sensor: absent
Direction sensor used: magnetometer & accelerometer
Hide caches: -
Hide waypoints: -
HW acceleration: enabled (default state)
System language: de_DE
System date format: dd.MM.yyyy
Debug mode active: no
System internal c:geo dir: /data/data/cgeo.geocaching (9,3 GB free) internal
User storage c:geo dir: /storage/sdcard0/cgeo (9,2 GB free) external non-removable
Geocache data: /storage/sdcard0/Android/data/cgeo.geocaching/files/GeocacheData (9,2 GB free) external non-removable
Database: /data/data/cgeo.geocaching/databases/data (156,0 KB) on system internal storage
Fine location permission: granted
Write external storage permission: granted
Geocaching sites enabled: None
Installed c:geo plugins:  none
--- End of system information ---
```

**Additional context:**
that are the errors/warnings I get in Android Studio. In the debug log from NB i found nothing special - but maby i just overlooked it
```
W/Java7Support: Unable to load JDK7 types (annotations, java.nio.file.Path): no Java7 support added
```
```
E/SQLiteLog: (1) no such table: cg_table_extension
W/cgeo: [RxCachedThreadScheduler-1] DataStore.clean
    android.database.sqlite.SQLiteException: no such table: cg_table_extension (code 1): , while compiling: DELETE FROM cg_table_extension WHERE _key NOT IN (0,1,2)
        at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
        at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:898)
        at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:509)
        at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
        at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:58)
        at android.database.sqlite.SQLiteStatement.<init>(SQLiteStatement.java:31)
        at android.database.sqlite.SQLiteDatabase.delete(SQLiteDatabase.java:1526)
        at cgeo.geocaching.storage.DataStore.deleteOrphanedRecords(DataStore.java:3043)
        at cgeo.geocaching.storage.DataStore.lambda$cleanIfNeeded$9(DataStore.java:2988)
        at cgeo.geocaching.storage.-$$Lambda$DataStore$8FeSmNTmqSUkISabhEebrLdvpUw.run(lambda)
        at io.reactivex.rxjava3.core.Scheduler$DisposeTask.run(Scheduler.java:614)
        at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:65)
        at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:56)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
        at java.lang.Thread.run(Thread.java:818)
```
```
E/SQLiteLog: (1) no such table: cg_table_extension
D/AndroidRuntime: Shutting down VM
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: cgeo.geocaching, PID: 3778
    android.database.sqlite.SQLiteException: no such table: cg_table_extension (code 1): , while compiling: DELETE FROM cg_table_extension WHERE _type = ? AND _key LIKE ?
        at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
        at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:898)
        at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:509)
        at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
        at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:58)
        at android.database.sqlite.SQLiteStatement.<init>(SQLiteStatement.java:31)
        at android.database.sqlite.SQLiteDatabase.delete(SQLiteDatabase.java:1526)
        at cgeo.geocaching.storage.DataStore$DBExtension.removeAll(DataStore.java:508)
        at cgeo.geocaching.storage.extension.FoundNumCounter.updateFoundNum(FoundNumCounter.java:27)
        at cgeo.geocaching.MainActivity$UpdateUserInfoHandler$1.fillView(MainActivity.java:153)
        at cgeo.geocaching.MainActivity$UpdateUserInfoHandler$1.getView(MainActivity.java:142)
        at android.widget.AbsListView.obtainView(AbsListView.java:2464)
        at android.widget.ListView.measureHeightOfChildren(ListView.java:1286)
        at android.widget.ListView.onMeasure(ListView.java:1194)
        at android.view.View.measure(View.java:17769)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5625)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1692)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:760)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:629)
        at android.view.View.measure(View.java:17769)
        at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:846)
        at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:512)
        at android.view.View.measure(View.java:17769)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5625)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:459)
        at androidx.appcompat.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:143)
        at android.view.View.measure(View.java:17769)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5625)
        at androidx.appcompat.widget.ActionBarOverlayLayout.onMeasure(ActionBarOverlayLayout.java:403)
        at android.view.View.measure(View.java:17769)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5625)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:459)
        at android.view.View.measure(View.java:17769)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5625)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1692)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:760)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:629)
        at android.view.View.measure(View.java:17769)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5625)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:459)
        at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2646)
        at android.view.View.measure(View.java:17769)
        at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2354)
        at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1378)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1602)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1256)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6443)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:800)
        at android.view.Choreographer.doCallbacks(Choreographer.java:603)
        at android.view.Choreographer.doFrame(Choreographer.java:572)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:786)
        at android.os.Handler.handleCallback(Handler.java:815)
        at android.os.Handler.dispatchMessage(Handler.java:104)
        at android.os.Looper.loop(Looper.java:194)
        at android.app.ActivityThread.main(ActivityThread.java:5576)
    	at java.l
```
@moving-bits maybe you could take a look...

**Comment by moving-bits** [comment] 2020-07-31 19:16
This is strange. Looks like table `cg_table_extension` hasn't been created on your device. - But this is part of the database update routine. I have no idea how this could have been skipped or reverted.

Will test with a fresh install.

**Comment by moving-bits** [comment] 2020-07-31 19:37
Still cannot reproduce. Have tried with backup / restore of an old database, both on API 29 and API 21 (Android 5) - works fine. (Table gets created, map downloader works, map file gets downloaded and received by c:geo)

Do you remember any specific steps you did between upgrading you c:geo version and the crashes? I'm looking for something to reproduce the error condition you've described.

**Comment by fm-sys** [comment] 2020-07-31 21:00
maybe this is also related to the failing tests #8706

I tested this multible times without any specific steps. Just a fresh install and directly navigating to offline map. Same happens when I restore a backup.

So probably this is a device specific problem

**Comment by fm-sys** [comment] 2020-07-31 21:08
on another device (also android 5.1.1 but emulated) everything runs without problems... Very strange!

**Comment by fm-sys** [comment] 2020-07-31 21:37
> 
> 
> on another device (also android 5.1.1 but emulated) everything runs without problems... Very strange!

I have to correct me: I've uninstalled and reinstalled the NB and now it's not working any more. Same crashes as on the first device :-(
So it looks like upgrading works but restoring an old database or just whith a fresh install won't... So it looks like it is **not** device specific

@moving-bits Could you send me a backup containing the `cg_table_extension` from a fresh install. Let's see if this is working, so i could continue my work for the offlineNum counter until this bug is hopefully fixed?

**Comment by Lineflyer** [comment] 2020-07-31 21:54
CI emulators run Android 6, yours Android 5.
Mine and others I have read around this topic are all newer.

@moving-bits 
Are you sure there is not any SQL function you use, which is on a later API?

**Comment by moving-bits** [comment] 2020-07-31 22:03
Not that I know of. `CREATE` statement is pretty standard:

```
    private static final String dbCreateExtension
            = "CREATE TABLE " + dbTableExtension + " ("
            + "_id INTEGER PRIMARY KEY AUTOINCREMENT, "
            + "_type INTEGER DEFAULT " + DBEXTENSION_INVALID.id + ", "
            + "_key VARCHAR(50), "
            + "long1 LONG DEFAULT 0, "
            + "long2 LONG DEFAULT 0, "
            + "string1 TEXT, "
            + "string2 TEXT"
            + "); ";
```

and within the db upgrade routine we have

```
    // add extension table
    if (oldVersion < 82) {
        try {
            db.execSQL(dbCreateExtension);
            Log.i("Added table " + dbTableExtension + ".");
        } catch (final Exception e) {
            Log.e("Failed to upgrade to ver. 82", e);
        }
    }
```
which is practically the same as for the last db update.

Also I had tested again today with restoring an old backup from within c:geo on Android 5 + Android 10 (both emulated). Haven't tested a complete fresh install yet, though.

**Comment by moving-bits** [comment] 2020-07-31 23:08
> Haven't tested a complete fresh install yet, though.

\*blush\*
AGAIN I forgot to add the create statement to `onCreate()`, I only added it to `onUpgrade()` - so upgrading did work, but a fresh install did not. => I'll create a fix for this.

**Comment by moving-bits** [comment] 2020-08-01 09:26
> @moving-bits Could you send me a backup containing the `cg_table_extension` from a fresh install. Let's see if this is working, so i could continue my work for the offlineNum counter until this bug is hopefully fixed?

The attached file is an (nearly) empty c:geo db at version 82 - which is the current state on master branch:

[cgeo82.zip](https://github.com/cgeo/cgeo/files/5010125/cgeo82.zip)

Extract the file and put cgeo.sqlite into your backup directory, then start c:geo and do a db restore.

**Comment by fm-sys** [comment] 2020-08-01 12:35
> The attached file is an (nearly) empty c:geo db at version 82 - which is the current state on master branch:
> [cgeo82.zip](https://github.com/cgeo/cgeo/files/5010125/cgeo82.zip)
> Extract the file and put cgeo.sqlite into your backup directory, then start c:geo and do a db restore.

Thank you! Now I have no crashes anymore... :-)

**Closed** 2020-08-01 15:16 UTC
Labels: Bug
