### ISSUE TITLE
Out of memory error in trail feature

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#7598] opened 2019-05-04 20:54 UTC
Google play console report for current beta version 2019.04.29-RC (new problem with this version):

ˋˋˋ
java.lang.OutOfMemoryError: 

at java.lang.Thread.nativeCreate (Native Method)

at java.lang.Thread.start (Thread.java:1063)

at java.util.concurrent.ThreadPoolExecutor.addWorker (ThreadPoolExecutor.java:921)

at java.util.concurrent.ThreadPoolExecutor.ensurePrestart (ThreadPoolExecutor.java:1556)

at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute (ScheduledThreadPoolExecutor.java:310)

at java.util.concurrent.ScheduledThreadPoolExecutor.schedule (ScheduledThreadPoolExecutor.java:543)

at java.util.concurrent.ScheduledThreadPoolExecutor.submit (ScheduledThreadPoolExecutor.java:642)

at io.reactivex.internal.schedulers.NewThreadWorker.scheduleActual (NewThreadWorker.java:145)

at io.reactivex.internal.schedulers.IoScheduler$EventLoopWorker.schedule (IoScheduler.java:239)

at io.reactivex.Scheduler$Worker.schedule (Scheduler.java:371)

at cgeo.geocaching.utils.AndroidRxUtils.andThenOnUi (AndroidRxUtils.java:76)

at cgeo.geocaching.maps.PositionHistory.saveToStorage (PositionHistory.java:36)

at cgeo.geocaching.maps.PositionHistory.rememberTrailPosition (PositionHistory.java:86)

at cgeo.geocaching.maps.mapsforge.v6.layers.HistoryLayer.draw (HistoryLayer.java:60)

at org.mapsforge.map.layer.LayerManager.doWork (LayerManager.java:94)

at org.mapsforge.map.util.PausableThread.run (PausableThread.java:147)

ˋˋˋ

**Comment by Lineflyer** [comment] 2019-05-05 20:01
@moving-bits Have you seen this issue? Does the trail data accumulate in memory....be aware, that feature was originally probably not designed to show a real long trail as it was resetted after leaving the map.

**Comment by moving-bits** [comment] 2019-05-05 20:29
Trail is limited in memory (and has been - haven't changed this) as well as in the database.

Error message to me looks like the device was not able to fork a new thread for saving. Currently I'm using `AndroidRxUtils.andThenOnUi ` - @rsudev @UniQP : I do not really need the `OnUi` part - is there a less memory intensive way for saving a trailpoint in background?

**Comment by moving-bits** [comment] 2019-05-11 16:32
I created a PR which switches the functions for saving the trail to database / clearing it from `AndroidRxUtils.andThenOnUi` to `AsyncTask`, since the `andThenOnUi` part is not needed. Not sure whether this helps with this issue, but at least it's cleaner code.

**Comment by moving-bits** [comment] 2019-05-11 16:33
BTW: trail length ist limited to 700 positions - in memory as well as in database, which should not be more than a couple of kb.

**Comment by Bananeweizen** [comment] 2019-05-12 14:31
From the stack trace in the report I don't think there is any memory issue in our code related to the storage of the trail coordinates. The OOM happens within the native part of a thread creation. That probably means we exhausted system resources for threads. That in turn might happen if we try to create many threads or thread pools all the time.

I'm not sure anymore, but I think I read another issue comment somewhere saying that the trail is stored like 10 to 15 times per second (someone noticed during debugging?), and that symptome would fit to this OOM in thread creation. Anyone else remembering that comment?

**Comment by moving-bits** [comment] 2019-05-12 14:43
Yes :-)
Source code not at hand right now, but IIRC the thread for saving a trailpoint only gets created if positions are at least 10m apart, so it should not be called in this case.

**Comment by moving-bits** [comment] 2019-05-12 19:08
here is the source fragment:

```
    public void rememberTrailPosition(final Location coordinates) {
        if (coordinates.getAccuracy() >= 50f) {
            return;
        }
        if (coordinates.getLatitude() == 0.0 && coordinates.getLongitude() == 0.0) {
            return;
        }
        if (history.isEmpty()) {
            saveToStorage(coordinates);
            history.add(coordinates);
            return;
        }

        final Location historyRecent = history.get(history.size() - 1);
        if (historyRecent.distanceTo(coordinates) <= MINIMUM_DISTANCE_METERS) {
            return;
        }

        saveToStorage(coordinates);
        history.add(coordinates);

        // avoid running out of memory
        final int itemsToRemove = getHistory().size() - MAX_POSITIONS;
        if (itemsToRemove > 0) {
            for (int i = 0; i < itemsToRemove; i++) {
                getHistory().remove(0);
            }
        }
    }
```

`saveToStorage()` gets called after the distance check, so even if the history implementation calles `rememberTrailPosition()` ten times a second it should not reach `saveToStorage()` as long as the position does not change too much.

Only race condition I could imagine here is the the order of the two commands `saveToStorage()` and `history.add()`. Those two could be swapped to make sure the coordinates are available as early as possible for the two checks (`history.isEmpty()` and distance check).

I'll close this issue for now. @Lineflyer  Feel free to reopen if issue persists.

**Comment by Lineflyer** [comment] 2019-05-12 20:58
> I'll close this issue for now. @Lineflyer Feel free to reopen if issue persists.

The above stacktrace was retrieved from Google Play for the beta version.
Did I oversee something here? Why should it not exist / no longer exist?

**Comment by Lineflyer** [comment] 2019-05-13 19:49
Reopening for clarification of my comment above.

**Comment by moving-bits** [comment] 2019-05-14 21:28
> The above stacktrace was retrieved from Google Play for the beta version.
> Did I oversee something here? Why should it not exist / no longer exist?

There's been an error message, for sure. We only did not find any obvious cause for it, even after looking into the code, and nothing related to the trail feature (except it being somewhere in the stack trace). So for now everything points to a general OOM error, which can have many different possible causes (not necessarily related to c:geo at all).

Did we get more of that error, or has it been a single instance?

**Comment by rsudev** [comment] 2019-05-15 19:54
28 instances of this issue for 13 different users according to Google Play

**Comment by moving-bits** [comment] 2019-05-16 07:06
Hm. I see three options:

a) disable the call to `saveToStorage()` (but do not change the rest) - to get a feeling whether this call is the cause for the above error. Also we would be able to release then. The rest of this implementation (`clear trail` and limiting the trail length in db) is no blocker to this, IMHO.

b) add loggin to the call to see whether `rememberTrailPosition()` gets called too frequently and/or there is some non-linearity which leads to thread stacking

c) revert the trail saving feature completely

Personally I would vote for b) or a), depending on how much time we have.

**Comment by moving-bits** [comment] 2019-05-16 07:07
> 28 instances of this issue for 13 different users according to Google Play

Thanks for the stats. Any things in common, like Android version, mobile model or else which could point to the cause?

**Comment by moving-bits** [comment] 2019-05-18 19:20
@Lineflyer For the upcoming release: Shall I implement any of the above options or leave everything as is?

**Comment by Lineflyer** [comment] 2019-05-19 10:07
I suggest to leave it unchanged for now and closely monitor the appearance of the problem after release

**Comment by Lineflyer** [comment] 2019-06-10 18:47
New statistics after release:
178 reports from 115 users

Not a very common problem (or only some users having the trail active).

**Comment by jakedot** [comment] 2019-06-10 18:56
maybe the latter. they might have noticed it has problems and turned it off, I know I did when the trail started lagging behind current position and going back into opposite direction of travel...

**Comment by moving-bits** [comment] 2021-05-16 07:21
I haven't seen any of this in the last months, so let's close here for now.

**Closed by moving-bits** 2021-05-16 07:21 UTC
Labels: Bug, Google Play or Beta feedback, Unverified
