### ISSUE TITLE
samma problem här / das geiche Problem hier

### ISSUE THREAD

**Issue by alces7** [cgeo/cgeo#15635] opened 2024-04-18 05:43 UTC
![Screenshot_20240418-065716_cgeo](https://github.com/cgeo/cgeo/assets/167400294/cd5aeceb-eb5a-4c85-b308-01c1dca870e3)

**Comment by eddiemuc** [comment] 2024-04-18 05:59
Duplicate of #15633

**Closed** 2024-04-18 05:59 UTC
