### ISSUE TITLE
User defined cache cannot be removed

### ISSUE THREAD

**Issue by HankChow** [cgeo/cgeo#13352] opened 2022-08-25 09:48 UTC
### Describe your problem!

Click on the user defined cache on the map and click the "trashbin icon", the toast prompts that the user defined cache has been removed from the stored list. But the user defined cache hexagon icon is still on the map. The hexagon icon still exists even after restarting the app and rebooting the phone.

### How to reproduce?

1. Long tap on the map and create a user defined cache
2. Delete the cache with the trashbin icon
3. The cache icon still exists on the map

### Reproducible

Yes

### c:geo Version

2022.08.21

**Comment by Lineflyer** [comment] 2022-08-25 15:35
This is intended behavior to allow restoring an accidentally deleted cache. Its removed from the list but still on map. Same applies for "normal" caches, but you might not notice as the live map anyway displays those.



It will vanish after a grace period of 72 hours.
You can enforce deletion by using c:geo Start - Menu - Offline Data - Delete orphaned data.

**Comment by fm-sys** [comment] 2022-08-25 16:06
This might indeed be a regression of  #13225. In the past we had explicitly implemented that UDC's will be deleted directly after closing and reopening cgeo. For other cache types the 72 hours period is intended...

**Comment by HankChow** [comment] 2022-08-26 02:22
Thanks for the reply. I regarded this as a problem before because UDC will be cleaned up after it being deleted and restarting the app in ver. 2022.07.31 (or older). I think it's not a problem now but it does make some users confused probably. I suggest that the period of keeping orphan data should be able to be set in settings by user in the future version.

**Comment by fm-sys** [comment] 2022-08-26 11:05
Introducing yet another setting won't be an option for us, cause internal operations should "just work" without users even being aware of it. Our settings are already today way too crowded.

However, I would like to discuss whether to exclude UDC's from this period.

**Comment by Lineflyer** [comment] 2022-08-26 11:05
I think the period of keeping orphaned data is fine, there just seems to be the regression, that UDC are not handled as before. This needs to be fixed.

**Comment by moving-bits** [comment] 2022-08-26 20:35
Are you sure we actually implemented an instant-deletion of UDC? I remember that we have discussed it some time ago, but I cannot remember us having actually implemented this.
As for the PR mentioned above I did not find any UDC-specific code (but I may have missed it), so the 72h grace period should apply for UDC as well. The only difference that PR introduced was that the cleanup function gets called once a day at max.

**Comment by fm-sys** [comment] 2022-08-26 21:29
> Are you sure we actually implemented an instant-deletion of UDC?

No. I was searching for it but haven't found the related code part either. But I'm almost sure it was working like this from user perspective... 

Just had an idea (haven't checked):
The "last details update" flag will always be 0 for UDC's cause they cannot be refreshed. Therefore our cleaning routine had always considered UDC's as obsolete so they where deleted directly. Could this explain the previous behavior?

**Comment by moving-bits** [comment] 2022-08-27 18:55
This might very well be. I see two options for fixing this:

In `DataStore.cleanIfNeeded()` add a section at the beginning (before the `dbNeedsCleanup()` check), where orphaned UDC get deleted. This would then be executed on every `MainActivity.init()`.

A more elegant solution would be to check for orphaned UDC every time the last list gets removed from an UDC.

**Comment by fm-sys** [comment] 2022-09-01 05:29
@HankChow it seems the issue isn't solved yet, so I would like to reopen the issue...

Could you please explain what has changed since you opened the issue?

**Comment by HankChow** [comment] 2022-09-01 08:08
@fm-sys I thought it was a bug because it's a little confusing before your explanation and discussion above on disposing UDC. But it's no more confusing for me, so I closed this issue. 
If cgeo team plan to make anything optimation about it in the future release, it's also OK to keep this issue open.

**Comment by dvdq8** [comment] 2022-09-07 12:39
Hi, I am a user of c:geo and in my opinion it would be really useful to add a button for immediate deletion of the single user defined waypoint. It would be nice to have the command directly in the list of items that appear by pressing the three vertical dots once entered in the cache.  With user defined caches you can very quickly manage customized paths, you can see where to hide a cache (with the display of the occupied area), record specific coordinates and much more.  To facilitate all this, however, we need the possibility of eliminating them as easily as their creation was.  Waiting 72 hours or going every time to delete orphaned offline data makes it too cumbersome and useless.
Thanks.

**Closed** 2022-09-19 17:02 UTC
Labels: Bug, Unverified
