### ISSUE TITLE
Wrong satellites count on Nexus 5X

### ISSUE THREAD

**Issue by Kuitsi** [cgeo/cgeo#6218] opened 2016-12-31 11:54 UTC
##### Detailed steps causing the problem:
- check that Android's settings -> Location mode is set to "Device only" or "High accuracy", both of them uses the GPS

##### Actual behavior after performing these steps:
- Main screen of c:geo shows "GPS disabled"
- Compass view of a cache shows "Sat: 0/0"
- accuracy +- is still updated in real time in both views and navigation works ok

##### Expected behavior after performing these steps:
- Real satellites count should be shown

##### Version of c:geo used:
2016.12.28
happened a long time before this version too

##### Is the problem reproducible for you?
Yes

##### System information:
```
--- System information ---
Device: Nexus 5X (bullhead, google)
Android version: 7.1.1
Android build: NMF26F
Cgeo version: 2016.12.28
Google Play services: enabled
Low power mode: inactive
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: rotation vector
Hide own/found: true
Map strategy: auto
HW acceleration: enabled (default state)
System language: en_FI
Log date format: 31/12/2016
Debug mode active: no
Fine location permission: granted
Write external storage permission: granted
Geocaching sites enabled:
   geocaching.com: Logged in (Sisäänkirjautuminen onnistui) / PREMIUM
Geocaching.com date format: yyyy-MM-dd
Installed cgeo plugins:  none
--- End of system information ---
```

I think this was happening on the same device when it had Android 6 too

**Comment by Lineflyer** [comment] 2016-12-31 13:21
Which version of GooglePlayServicrs is installed on your device?

**Comment by Kuitsi** [comment] 2016-12-31 14:53
Google Play Services 10.0.84 (440-137749526)

**Comment by Lineflyer** [comment] 2017-01-09 19:51
This is the same version that I am using (on another device).
So this cannot be the cause alone.

Is the count working if you disable Google Play Services usage in c:geo Menu -> System?
Does the count reappear if you just wait for some seconds/minutes while on the main screen or if you later on while using c:geo return to the main screen?

**Comment by Kuitsi** [comment] 2017-01-09 22:22
Disabling Google Play Services from c:geo's settings works

**Comment by samueltardieu** [comment] 2017-01-09 22:38
Google Play Services has its way of locating you without using the GPS all the time, and turns it on for very small period of times. That may explain the discrepancy with the GPS information we get from Android.

**Comment by Lineflyer** [comment] 2017-02-21 21:52
I had this case today,
Indeed Google Play services did not activate GPS right away as it probably had my location already. During this phase c:geo seems to show Sat: 0/0

Let me close this for now, as there is no functional drawback behind this.

**Closed by Lineflyer** 2017-02-21 21:52 UTC
Labels: Bug, low, Unverified
