### ISSUE TITLE
Waypoint Calculator: Support for float results

### ISSUE THREAD

**Issue by Matze2** [cgeo/cgeo#6891] opened 2017-12-19 00:17 UTC
See formuia in GC7ENZJ.

North 48° ((B * D) +((D+E+A+B+C+F+G+H) * C)) *A
East 011° (E+D) * A * B

Result of both formulas is something like 23456. There is no possibility to "float-divide" by 1000 to get 23.456.

The only way to achieve the desired result is to repeat both formulas once with "/ 1000" and once with "% 1000", e.g. in plain mode:

N 48° (((B\*D) + ((D+E+A+B+C+F+G+H)\*C)) * A **/ 1000**).(((B*D) + ((D+E+A+B+C+F+G+H)*C)) * A **% 1000**)
E 011° ((E+D) * A * B / 1000).((E+D) * A * B % 1000)

Needless to say that this is cumbersome.

**Comment by pstorch** [comment] 2017-12-19 06:52
Duplicate of #6699

**Closed** 2017-12-19 06:52 UTC

**Comment by Matze2** [comment] 2017-12-19 06:55
Sorry, should have seen that. *Insert pstorch's emoji from 6890 here*
