### ISSUE TITLE
Cache log photos internally and scale/compress before sending only

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#9806] opened 2021-01-16 21:19 UTC
Two users contacted us on support mail with this problem. Did not have time/opportunity to test it:
- Have picture stored in galery
- Post a log and add the picture with the legacy function (Menu - Add picture)
- Select "No scaling"
- Send log 
- Post again a log and add the same picture via quick button instead of the old function
- Send log

Result:
The first picture has a higher resolution than the second one. The second one seems to get scaled to 1024px on longer side.

Is this a bug or known limitation?
The examples posted by a user proofs that such limitation can results in pretty unusable pictures (in that users case he took a photo of a signpost with a lot of text, it was not possible to read it anymore).

**Comment by eddiemuc** [comment] 2021-01-17 08:44
The described way is how it was intentionally coded by me. The idea behind it was that the quick way is like e.g. WhatsApp: add stuff quickly, do everything being the scenes (including scaling to a sensible value). If the user wants more control he can use the old advanced dialog via menu.

Back in the days, you may remember I proposed a third icon to access the advanced dialog also directly from the main screen. But it was not considered meaningful. I initially planned even to add a scaling and a name prefix field into the main screen but it was not received well back in the days.

Now the big question: (how) do you want to change this behaviour?

**Comment by eddiemuc** [comment] 2021-01-17 09:02
By the way: please nobody work on this before #9734 is merged!

**Comment by Lineflyer** [comment] 2021-01-17 12:50
Yes, I remembered there was some discussion back when you implemented it. Thats why I phrased the issue as a question. :)

> The idea behind it was that the quick way is like e.g. WhatsApp: add stuff quickly, do everything being the scenes 

That is still a good idea IMHO.
I am not sure, what is happening here:
- The user send screenshots showing that the original picture has 2736x3648px with a size of 483kB according to the c:go screenshot (added via advanced dialog). Strangely already a rather small size given the dimension, isn't it?
- The user send another screenshot showing the picture added over the quick selection: 768x1024px with 72kB
- Now look at the picture attached to this log: https://www.geocaching.com/seek/log.aspx?LUID=ff3b10db-6eec-4b01-9fba-b259a36df726 The user told it was the second one (added via quick selection). On the website it shows with 384x512px. Why is that?

**Comment by Lineflyer** [comment] 2021-01-17 13:02
> Now the big question: (how) do you want to change this behaviour?

Up to now I seemingly had a wrong understanding how it works:
I though you can add a picture using the quick button and can (before finally sending the log) just click the picture, which opens the full (old) dialog to adjust title and also scaling according to your needs. But for me the dialog opens with "No scaling" although the picture is already scaled down after initially selecting it.

Wouldn't it be possible to do it like that:
- Copy the original picture when the user selects it and still keep the scaling preset to 1024px but not yet execute it
- If the user clicks on the picture he should see "1024px" scaling and can select another value (e.g. "no scaling" or even more scaling)
- Finally scale the picture only as soon as the user sends the log
-

**Comment by Lineflyer** [comment] 2021-01-17 13:14
Changed the issue title and labels.

**Comment by eddiemuc** [comment] 2021-01-17 15:21
Let me try to summarize how things are implemented today, then let's discuss how and what to change:

Although there are different ways of adding images to the log, they all have in common the following preprocessing when the selection is saved (for quick-select immediately, for advanced select on clicking "ok"):
* a copy of the selected image is made
* This copy is preprocessed: EXIF-information is deleted and it is converted to a JPG with compression quality 75%
* The image is scaled as followsd: 
   * for "advanced dialog" it is scaled to the setting chosen in the dialog. It is not scaled when "no scaling" is selected there.
   * for the "quick settings" the last setting chosen in advanced dialog is used. If this last setting is "no scaling", then 1024 is used

@Lineflyer : this explains already some of the things observed by the user:

> - The user send screenshots showing that the original picture has 2736x3648px with a size of 483kB according to the c:go screenshot (added via advanced dialog). Strangely already a rather small size given the dimension, isn't it?

This is expected because of the preprocessing above (removing EXIF-data and compressing to JPG with 75% quality)

> - The user send another screenshot showing the picture added over the quick selection: 768x1024px with 72kB

This is expected due to the default scaling to 1024 in case "no scaling" is last selection in advanced dialog

> - Now look at the picture attached to this log: https://www.geocaching.com/seek/log.aspx?LUID=ff3b10db-6eec-4b01-9fba-b259a36df726 The user told it was the second one (added via quick selection). On the website it shows with 384x512px. Why is that?

This is NOT expected and might be a bug. The image should still be scaled to 768x1024px. I could unfortunately not reproduce this case 


> Wouldn't it be possible to do it like that:
> - Copy the original picture when the user selects it and still keep the scaling preset to 1024px but not yet execute it. Still of course the user should see the theoretical dimensions a scaling would produce in the picture list.
> - If the user clicks on the picture he should see "1024px" scaling and can select another value (e.g. "no scaling" or even more scaling). The dimensions in the picture list are afterwards updated accordingly.
> - Finally scale the picture only as soon as the user sends the log

This is of course possible. imho this would mean the following:
* No preprocessing of images on offline log save or before sending the log to the server. This would interestingly enough mean that we do no longer need a c:geo folder for "offline log images" (I would argue that in this case we can store images made via camera from inside c:geo in the standard android image folder). 
* Note that if the user deleted on his device an image used in an  offline log before sending it to the server, this would be lost. Of course we have the same situation today, but since we use a dedicated c:geo image folder with copies of the original images this might be less likely (or at least more understandable to the user)
* Adding a column "scale" to the Offline Log Image database table - so we know what to scale the image to if he finally sends the log to server
* All image processing is then done "on send" only
* Note that we cannot preview efficiently the size of the image then - because we would have to do the preprocessing and scaling "behind the scenes" into some temporary file to get that value. We can however "predict" the scale size of the image of course.

If this is what is wanted, it would make a fine feature request imho.

**Comment by eddiemuc** [comment] 2021-01-17 15:24
Additional note: I would argue that if we do NOT want to modify the offline log image before sending it to the server, then it does not make sense to make a copy of it too. It would just use up lots of user device space unnecessarily, because this copy would not be modified in any way before the image is send to server, and it would be deleted afterwards anyway.

**Comment by eddiemuc** [comment] 2021-01-17 15:42
@Lineflyer : wrt to the possible bug (image scaled to 1024 is shown at gc.com scaled to 512): I tried now to reproduce with different images, added both via advanced or quick dialog and changing scaling values to different settings inbetween. I was unable to reproduce. It would be good to know if this specific case is reproducible and how. Especially I would be interested in the last value of "scaling" set via "advanced dialog", and also the "raw" setting of "logImageScale" (as seen in the "view settings" list in Settings -> System)

**Comment by eddiemuc** [comment] 2021-01-21 06:25
It hit me last night that I made a thinking mistake above. Although we would not modify selected images until they are sent together with the offline log, we still need to make a copy of them. Reason is that we will not have permission to access them across app/device restarts otherwise due to scoped storage (very embarrassed that I did not think about this in the first place...). Unfortunately this also means that they take much space on the users device while offline log is stored there.

But we could store these copies e.g. in c:geo private storage because there is no more need for them to be publically available to the user (he has the originals for that). Would ease up a few things and prevent some possible error scenarios (like user deleting the image, changing the base/image dir or c:geo loosing public folder read permission).

**Comment by fm-sys** [comment] 2021-01-21 08:31
IIRC the images currently gets compressed and downscaled. What is we compress them before copying into private storage and do only the downscaling while upload? That will already save a lot of storage space...

**Comment by Lineflyer** [comment] 2021-01-21 18:51
I think we should just copy (to a private dir).
Why after all do we compress it instead of just scaling...or is it something where one thing does not work without the other (have no idea about graphic processing)

**Comment by moving-bits** [comment] 2021-01-21 19:06
I would postpone compressing up to the same point where we scale, to avoid loosing image quality.
And how many offline log images would you have at the same time? Shouldn't make that much difference in terms of used space.

**Comment by fm-sys** [comment] 2021-01-21 19:26
> I would postpone compressing up to the same point where we scale, to avoid loosing image quality.
> And how many offline log images would you have at the same time? Shouldn't make that much difference in terms of used space.

Also ok for me. To be honest, storage space isn't a real problem anymore. (Thousands of pictures on my phone 🙈) 

Still compression is very important. For me, c:geo currently shrinks the image size from 8 MB to a few hundred kilobytes without any visible loss of quality. This is due to the fact that the manufacturers (huawei at least) store countless metadata in the images, which allows extensive post-processing incl. changes in depth of field and other fancy things.

But since we do the compression anyway, there is actually no difference whether it will be done a little sooner or later. 

Example:
20 log images * 10 MB  = 200 MB
20 log images * 500 kB = 10 MB

And even if most devices have enough memory, 190 MB can also be used elsewhere (for example offline maps 😁)

**Comment by moving-bits** [comment] 2021-01-21 19:32
> But since we do the compression anyway, there is actually no difference whether it will be done a little sooner or later.

But AFAIK there will be a loss of image quality on each storing, even if no additional compression is applied - at least for .jpg files, due to the nature of jpeg file format. That's why I suggested to do compression and scaling in one step and only then store the result.

Things would be different for lossless formats. Or if we only strip the metadata in step 1, without any compression or scaling. (Not sure if that's possible for jpegs.)

**Comment by eddiemuc** [comment] 2021-01-21 19:36
I am with @Lineflyer and @moving-bits on this.

> Things would be different for lossless formats. Or if we only strip the metadata in step 1, without any compression or scaling. (Not sure if that's possible for jpegs.)

No idea. I guess this can be explored via the many image processing options of the Android framework.

**Comment by eddiemuc** [comment] 2021-01-31 12:22
Please be aware that I consider #9609 to be blocked until this issue is either rejected or implemented (if the later then maybe in conjunction with #9609)

**Comment by Lineflyer** [comment] 2021-01-31 12:31
Let me try to summarize my opinion on this:
- IMHO picture processing should be done right when (before) sending the log.
- This means, we should just copy the selected image (the taken photo) into some internal folder once selected (no need for this folder to be user accessible IMHO, maybe even better if not otherwise we need to handle missing files if the user deletes it while the image is still used for a pending log)
- In this state (image added, log not yet sent or even stored offlline) the user should be able to click on it to open the (legacy) dialog and select the desired scaling)
- Once the log is sent we should delete the cached images

Regarding compression:
If it is possible we should only change the dimension not involving any further compression.
The original scaling thing wents back to a time, where most connections were rather slow and data quota was limited. I guess this will more and more becoming irrelevant.

**Comment by fm-sys** [comment] 2021-01-31 12:57
> Regarding compression:
If it is possible we should only change the dimension not involving any further compression.
The original scaling thing wents back to a time, where most connections were rather slow and data quota was limited. I guess this will more and more becoming irrelevant.

Here I totally disagree. Compression is very important and the biggest advantage of using JPG instead of PNG. For c:geo, it provides faster submitting and downloading and saves much data volume without a noticeable quality loss.

[Here is a blog post about web image optimization](https://www.abetterlemonadestand.com/optimizing-images-for-web/) 

BTW: We are already compressing images since many years, and it has never been negatively noticed. That is why I do not understand why we should change this now. Never change a running system ;-)

Everything else of you're summary is totally correct and also my point of view 👍

**Comment by moving-bits** [comment] 2021-01-31 15:14
I agree with @fm-sys on the compression issue. We should compress before uploading to save transmission time. Too many times you'll have a bad network connection (not to speak of data rate limitations).

**Comment by Lineflyer** [comment] 2021-01-31 16:08
> Here I totally disagree. Compression is very important and the biggest advantage of using JPG instead of PNG. 

Maybe you are right, I was looking at my phone where the camera produces pictures with 3-4MB JPG 4096xsomething and after scaling down to 1600xsomething its only 0,5-1MB, which is already rather small.

But OK, then lets stay with what we have in terms of compression.

**Comment by eddiemuc** [comment] 2021-02-06 17:30
OK, I will tackle this one in combination with #9609

**Comment by eddiemuc** [comment] 2021-02-07 09:01
Copied from https://github.com/cgeo/cgeo/issues/9966#issuecomment-774633458:

Ok. Let's keep things simple: I will create a new subfolder in GeocachData for the log images. That way the existing functionality for changing this folder (including an implicit move of the content) will be reused for log images too.

@Lineflyer log images are today not deleted after log was send. Check folder "Pictures/cgeo" and you should find all log images you ever send. I noticed this when Initially working on the multiple-images-per-log-thing many months ago and tried to discuss deleting them but to no avail. Anyway, I would indeed delete them once images are in internal storage.

Wrt the case of a removed SD card: imho we should draw a line here. If the user insists on storing his data on an external card but removes this card, then it is ok that the images are no longer there.

**Comment by Lineflyer** [comment] 2021-02-07 10:42
Thanks @eddiemuc for taking over the comment.

Regarding the deletion: 
I assume we are always talking about the deletion of our "cached" image. Correct? These should indeed be deleted if the log was sent succesful or the user deletes his offline log.

Asking because when I select an existing photo from my gallery to be attached to the log, it should (of course) not be deleted from the source.

I used the opportunity to rename the issue to better match the ToDo.

**Comment by eddiemuc** [comment] 2021-02-07 11:25
> Regarding the deletion:
> I assume we are always talking about the deletion of our "cached" image. Correct? These should indeed be deleted if the log was sent succesful or the user deletes his offline log.

Yes I am talking solely about copies made for c:geo. Today those copies are stored in Pictures/cgeo (in case of selecting from storage/gallery, those are scaled-down copies from original image, in case of making camerat-shot from within c:geo there are two images there, the original one and a scaled-down version). Those copies are never deleted. Before I tackled the image stuff few months ago it was even worse: every time you edited an existing image on your offline log (e.g. replacing it, changing it's title or whatever), there was a new copy of the same image created and the old one was not deleted.

While tackling this issue I will also introduce deletion of copy images when log is uploaded. Original images (also when taking via camera from within c:geo) shall not be deleted of course, only the c:geo-internal copies

**Comment by eddiemuc** [comment] 2021-02-07 17:22
@Lineflyer or anyone else with experience in translations:
As part of this issue I have to change the number and meaning of parameters for an already translated and productive string:
`<string name="log_image_info">%1$d x %2$d px, %3$d kB, %4$s</string>`
will be changed to something like:
`<string name="log_image_info">%1$d x %2$d px, %3$d kB\nScaled: %4$d x %5$d px</string>`

So both the number and also the meaning of the parameters will change (e.g. %4 was a filename before of type string, now it will be the expected width after scaling of type integer (and filename will no longer be part of the message at all))

Question: with such a huge change, would you rather prefer that I create a new value (e.g. `log_image_display_info`) or should I just change the existing value? I don't know how this is then best handled in Crowdin for the translations.

**Comment by bekuno** [comment] 2021-02-07 17:44
I would stay here with the current keyword. It is only a specification change in its text. This should be recognisable by the translators.
You can additional upload an image and tag it with the keyword. So the translators can see the context.
The place is at https://crowdin.com/project/cgeo/settings#screenshots

**Comment by Lineflyer** [comment] 2021-02-07 18:16
If the content changes, translations are reset. So also from this perspective there is no need to change the keyword.

**Comment by eddiemuc** [comment] 2021-02-07 18:24
> The place is at https://crowdin.com/project/cgeo/settings#screenshots
> 

Seems like a special permission is needed to access this page. I get a http 403 after login.

**Comment by bekuno** [comment] 2021-02-07 20:36
> 
> 
> > The place is at https://crowdin.com/project/cgeo/settings#screenshots
> 
> Seems like a special permission is needed to access this page. I get a http 403 after login.

is changed.

**Closed** 2021-02-13 21:19 UTC
Labels: Feature Request
