### ISSUE TITLE
Ghost waypoints on map

### ISSUE THREAD

**Issue by lassidadi** [cgeo/cgeo#9596] opened 2020-12-27 00:39 UTC
When I edit waypoints location which was created earlier, the old waypoint is left on the map. Ghost waypoints disappear when app is closed and reopened.

--- System information ---
Device: SM-A705FN (a70qeea, samsung)
Android version: 10
Android build: QP1A.190711.020.A705FNXXU5CTK4
c:geo version: 2020.12.03
Google Play services: enabled - 20.47.13 (120400-344095733)
Low power mode: inactive
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: rotation vector
Hide caches: -
Hide waypoints: -
HW acceleration: enabled (default state)
System language: en_GB
System date format: dd/MM/y
Debug mode active: no
System internal c:geo dir: /data/user/0/cgeo.geocaching (71.0 GB free) internal
User storage c:geo dir: /storage/emulated/0/cgeo (71.0 GB free) external non-removable
Geocache data: /storage/emulated/0/Android/data/cgeo.geocaching/files/GeocacheData (71.0 GB free) external non-removable
Database: /data/user/0/cgeo.geocaching/databases/data (764.0 KB) on system internal storage
GPX import path: /storage/emulated/0/cgeo/gpx
GPX export path: /storage/emulated/0/cgeo/gpx
Offline maps path: /storage/emulated/0/Maastokartta
Map render theme path: 
Live map mode: false
Global filter: display all caches
Fine location permission: granted
Write external storage permission: granted
Geocaching sites enabled:
   geocaching.com: Logged in (Login OK) / PREMIUM
Geocaching.com date format: d.MM.yyyy
Installed c:geo plugins:  none
BRouter connection available: false
--- End of system information ---

**Comment by geocachermgo** [comment] 2020-12-27 05:17
Duplicate of #8237 ?

**Comment by lassidadi** [comment] 2020-12-27 13:17
Yes

**Comment by moving-bits** [comment] 2020-12-27 13:20
Then let's close here as duplicate

**Closed by moving-bits** 2020-12-27 13:20 UTC
Labels: Duplicate
