### ISSUE TITLE
Filter hint and filter behavior when changing between list and map

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#10673] opened 2021-05-17 20:23 UTC
Another strange scenario: Set up a map filter ``Name Contains huhu``, then go to a list and filter for ``Status = [Only Not Found]``, then click the map icon - the caches which have been shown after filtering the list will be displayed (expectedly) - nevertheless, the map filter still says ``Name:huhu`` ...?

_Originally posted by @MagpieFourtyTwo in https://github.com/cgeo/cgeo/issues/10659#issuecomment-842599625_

**Comment by eddiemuc** [comment] 2021-05-18 06:05
As you already saw, this behaviour results because I currently store two filter-sets: one for "map viewer", one for "map as list".

Changing it to one filter can have some other strange effects though. Keep in mind that "map as list" simply transfers the currently visible caches (according to map viewer filter settings + quick settings) to a list. Not more, not less.

Before I try to explain it all here, I will change it back to one filter and then you can see for yourself :-)

**Comment by MagpieFourtyTwo** [comment] 2021-05-18 09:19
For me it is (or at least seems to be ;) ) pretty clear, but I'm afraid it's quite likely, Jo:sephine Average might not get it.

Just to check, I presented the two different filters to my "personal standard user" yesterday evening, and she promptly asked, why list and map have different filters at all, cause when she is looking for caches, she said, she will first set up a filter, and then look in the map and/or in the lists ... and her search context will not switch just because of the place where she is looking ... i. e. in a list or into (live) map. And to be honest, unfortunately, I had to agree with her. ;)

Although this could even be achieved with a global filter, without the need to set one in list and map at all ... but nevertheless there would then even be three places to screw things up ... ahem, sorry, to enable a filter ... which of course might get better, once the filter is displayed in the map view, too, but I still guess, these are too many places for an average user.

BTW: If multiple different filter definitions will be implemented anyway, I would really like to have one ring to rule ... ahem, one button to disable them all in one go.

**Comment by eddiemuc** [comment] 2021-05-18 09:36
I will change it.

But when there is one filter for "map viewer" and "map as list", consider the following scenario:
* In map viewer, I select a filter "Type=traditional". -> only tradis will be shown in map viewer
* I click "Map as List" -> List view will open with active filter "Type=traditional", and only tradis are shown

So far so good. But let's continue:

* Still in list view, I change the filter to "Type=traditional OR multi" -> STILL only tradis will be shown
* I close the list view and go back to the map viewer -> there now tradis AND multis will be shown

This behaviour happens because "Map as list" does not transfer a search/filter criteria but it transfers simply the list of caches visible on the map at the time the "map as list" is clicked (with all filters etc applied).

**Comment by MagpieFourtyTwo** [comment] 2021-05-18 09:49
Had to think about it for a second, but I guess this can safely be called an "expected behavior" (if I got it right).

IOW: When coming from a map, where only tradis are shown, and the user then looks at these caches in list form, he then can of course extend the filter, but will most probably not expect to see *more* caches afterwards, cause one will usually filter *in this subset* of caches, anyway. At least IMHO.

So it might be slightly disturbing for someone (there always is at least one ;) ), but in fact it's easy to explain (even autodidactic).

**Comment by fm-sys** [comment] 2021-05-18 09:58
> This behaviour happens because "Map as list" does not transfer a search/filter criteria but it transfers simply the list of caches visible on the map at the time the "map as list" is clicked (with all filters etc applied).

This should IMHO not be the case. If the filter gets changed, the search should be reexecuted (as for "search by filter")

**Comment by MagpieFourtyTwo** [comment] 2021-05-18 10:06
Au contraire.

Scenario: If you are in a list of saved caches, which just contains Tradis, do you really expect to see a Multi, when you set your filter to Multis in this Tradi list?

IMHO the ``Show (mapped caches) as list`` is comparable to this saved list.

Moreover: If the list content should be re-evaluated, the list must additionally know, which map region has been shown ...

**Comment by MagpieFourtyTwo** [comment] 2021-05-18 10:11
IMHO the ``Show (mapped caches) as list`` is a list of a subset of caches, and filtering a subset should never extend the subset.
This would BTW even contradict the elsewhere discussed ``AND`` principle.

**Comment by eddiemuc** [comment] 2021-05-18 10:39
I agree with @MagpieFourtyTwo on this.
Plus, the function "show list on map" (the "map" icon at the top of a list) works the same way: it shows the (filtered) list of caches on the map. I feel that "show map on list" and "show list on map" should behave the same mutually

And I know that this is not a valid argument, but implementing it another way would add some non-trivial complexity to both implementation and also "logic". @MagpieFourtyTwo already mentioned that the "map as list" then somehow has to "maintain" the "map region" to search for on re-issuing requests. Also, on an implementation level, the whole map-specific search logic has to be transferred to CacheListActivity (map viewer is the only place where there are mixed search requests issued to both database and connectors).

**Comment by fm-sys** [comment] 2021-05-18 13:05
> 
> 
> > This behaviour happens because "Map as list" does not transfer a search/filter criteria but it transfers simply the list of caches visible on the map at the time the "map as list" is clicked (with all filters etc applied).
> 
> This should IMHO not be the case. If the filter gets changed, the search should be reexecuted (as for "search by filter")



Sorry, my first post was just a quick post out of the field. Anyway, I have the strong opinion that this is the correct way to go.

I have to add, that I see this issue in a way larger context. To have the full picture, please read my comment in that issue as well: https://github.com/cgeo/cgeo/issues/4597#issuecomment-842486880

There, I have suggested implementing a Bottom navigation component:

![grafik](https://user-images.githubusercontent.com/64581222/118651953-5c125b00-b7e6-11eb-8f6f-0168f837111d.png)
_(material.io example of a bottom navigation)_

As soon as we use it, **lists and map need to be at the same hierarchic level.**

But even if we never switch to a bottom navigation, really aren't you annoyed by situations, where you have to press 4 or 5 times the back button, to come back to the main activity?

Please, tell me: is there any larger app which uses such complex and confusing activity hierarchies? E.g. Youtube, all Google apps, WhatsApp, Signal, Spotify, FDroid, even the official Geocaching App. In none of these apps, there are situations where you have to press the back button more than two times...

For sure, this would be a larger change in how it behaves (compared with currently). But we have said so many times: "Oh, our UX is bad." Design might be imported as well, but the most imported thing is, how user workflows are structured. And this is currently IMHO very bad...

![grafik](https://user-images.githubusercontent.com/64581222/118653708-18b8ec00-b7e8-11eb-859c-0fadf6182a4d.png)


I hope my "large plans" are understandable to you and I can convince you. ;-)
Otherwise, please explain to be why we should continue using such complex structures...

**Comment by eddiemuc** [comment] 2021-05-18 14:58
@fm-sys I understand, I like and I support your "large plan" :-) I would love to see c:geo with a design as you proposed.

But it seems to be a bit off-topic for the issue at hand. I guess we have to iterate towards such a solution step by step.

**Comment by fm-sys** [comment] 2021-05-18 15:16
> I guess we have to iterate towards such a solution step by step.

If "stacked" vs. "shared" can easily be changed later on, I'm totally fine with that 👍

I agree, that it makes more sense to change this known behavior together with a larger refactoring, so that users are only confused once ;-)

**Closed** 2021-05-18 15:46 UTC
Labels: Bug, Unverified

**Comment by eddiemuc** [comment] 2021-05-19 05:59
Small update: with yesterday's work, the filter is already no longer "stashed" (same filter for map and list view)
