### ISSUE TITLE
Modify coordinates for all Cache types 

### ISSUE THREAD

**Issue by speedy-1702** [cgeo/cgeo#6056] opened 2016-10-23 07:17 UTC
Feature request 

Since GC has changed  to let all Cache types modify  their coordinates, I would like to use it  in c:geo

**Comment by Lineflyer** [comment] 2016-10-23 09:03
Duplicate of #6043, but thanks anyway!

**Closed** 2016-10-23 09:03 UTC
Labels: Duplicate

**Comment by speedy-1702** [comment] 2016-10-23 10:13
Ok. Thank you. 
I was searching with keywords coordinates and modify and not finding.
