### ISSUE TITLE
Unified map: tiles not placed correctly in VTM

### ISSUE THREAD

**Issue by fm-sys** [cgeo/cgeo#13593] opened 2022-11-01 21:40 UTC
tiles not placed correctly in VTM

Cgeo version: 2022.11.01

![Screenshot_20221101_222635_cgeo geocaching](https://user-images.githubusercontent.com/64581222/199346749-97465c6e-ba66-4c53-9664-d6936d01d6fa.jpg)

**Comment by fm-sys** [comment] 2022-11-02 00:20
Reproducible for me when closing and reopening unified map.

**Comment by moving-bits** [comment] 2022-11-02 20:20
This is strange, never have seen this before. How do you open/close the map? Quick icon to open map, then home icon in bottom navigation?

**Comment by fm-sys** [comment] 2022-11-03 07:05
> Quick icon to open map, 

Yes
> then home icon in bottom navigation?

For example. However, happens as well when using back-key or the actionbar back arrow

100% reproducible on my device. Always happen on >=second map launch.

```
# System information

c:geo version: 2022.11.02-NB-314b9e4

# Device:
- Device type: SNE-LX1 (SNE-LX1, HUAWEI)
- Available processors: 8
- Android version: 10
- Android build: SNE-LX1 10.0.0.245(C432E10R1P1)
- Screen resolution: 1080x2250px (360x750dp)
- Pixel density: 3.0
- System font scale: 1.0 / used scale: 1.0

**Comment by moving-bits** [comment] 2022-11-03 20:16
Can you cross-check the VTM example programs whether they run fine? (See https://github.com/mapsforge/vtm/tree/master/vtm-android-example/src/org/oscim/android/test)

If not, you should open an issue for VTM, otherwise we would need to look for differences in implementation of `UnifiedMap` (VTM)

Thanks.

**Comment by devemux86** [comment] 2022-11-04 13:13
This looks like a change (in code) of tile size (?).

**Comment by moving-bits** [comment] 2022-11-04 15:34
> This looks like a change (in code) of tile size (?).

If so this would have been by accident. In my tests so far I haven't seen this so far, neither in AS emulator nor in my (single) physical testing device. What method calls (or map parameters etc.) could be triggering such a change?

**Comment by devemux86** [comment] 2022-11-04 15:48
`Tile.SIZE` is calculated automatically in `MapView` creation and cannot be changed in real time,
without creating everything again.

See the [GettingStarted](https://github.com/mapsforge/vtm/blob/master/vtm-android-example/src/org/oscim/android/test/GettingStarted.java) example for the life cycle of the library.
The sample also keeps the map view in orientation changes (see [manifest](https://github.com/mapsforge/vtm/blob/master/vtm-android-example/AndroidManifest.xml#L47))).

**Comment by moving-bits** [comment] 2022-11-04 18:53
Hm, we're nowhere even referencing `Tile.SIZE`.
Lifecycle handling for mapView is implemented as given in the example, will cross-check for theme handling.

**Comment by moving-bits** [comment] 2022-11-22 14:40
This looks more like a "tile not completely drawn" issue to me rather than a "wrong placement of tiles". Have a look at the orange line crossing "Kirchhundem" (lower third of the map) - the tile is not displaced, but there is something missing, the orange lines would not connect if the currently drawn parts of the tile would be completely adjacent.

**Comment by fm-sys** [comment] 2022-11-23 22:08
> This is strange, never have seen this before. How do you open/close the map? Quick icon to open map, then home icon in bottom navigation?

Just noticed: This does only happen when using the elevate/elevate theme. Neither have seen this with the elevate/elements theme, the default theme or any other custom one.

[Elevate.zip](https://github.com/cgeo/cgeo/files/10079386/Elevate.zip)

**Comment by moving-bits** [comment] 2022-11-26 11:22
I have not yet been able to reproduce it. Tested it against OAM NRW map with latest (Nov 6) Elevate/Elevate theme as well as with the theme file you provided. 🤔

**Comment by moving-bits** [comment] 2023-06-18 19:39
@fm-sys 
Still happening after all those changes lately?

**Comment by fm-sys** [comment] 2023-06-18 19:48
Still happening unfortunately :(

I'll assign myself for debugging as I seem to be the only one who can reproduce this issue...

**Comment by fm-sys** [comment] 2023-06-18 21:56
Found the reason why it was not reproducible for you, I had map scaling enabled which seem to cause problems on VTM:

![img](https://github.com/cgeo/cgeo/assets/64581222/1faf907b-4e80-4d85-b1eb-6695744d830b)

**Comment by moving-bits** [comment] 2023-06-24 14:36
> Found the reason why it was not reproducible for you, I had map scaling enabled which seem to cause problems on VTM:

May be (although I still cannot reproduce it over here, neither in the emulator nor on a physical device). Can you open an issue for it with @mapsforge/vtm?

**Comment by devemux86** [comment] 2023-06-24 14:54
Changing the symbol or text scale of the map elements just needs to reload the vector map.

User scale changes everything, tiles, map scale, etc. and requires to restart the map engine.
On the desktop Cruiser requires a restart of the app.

Usually there is no need for user scale. Symbol and text scale should be fine for most uses.
The vector tile size is automatically calculated on Android in both Mapsforge + VTM libraries,
based on the device screen dpi.

**Comment by fm-sys** [comment] 2023-12-04 22:38
We should try to set the scale settings before initializing the map fragment. If this doesn't help either, I would vote to make the map scaling options global and initialize these values once on application startup (`CgeoApplication`). I already could verify that this would work without problems.

**Comment by moving-bits** [comment] 2024-02-03 17:57
@fm-sys 
Do we really need a user scale for VTM?

If not: With user scale options having been removed, the error described here should be prevented, so we could close this issue.

Otherwise we should move user scale options out of theme options into "map behavior" settings, which would automatically mean a map restart (and we could even force an app restart, if required for this setting).

**Comment by fm-sys** [comment] 2024-02-03 19:40
IMHO they are not necessary, but it was an explicit feature request for old mapsforge. So we can either drop them or make them global. No preference from my side...

**Comment by moving-bits** [comment] 2024-02-04 14:45
I'd vote for "drop" for now (as it is implemented currently for VTM), and see if there are any claims for getting this feature back for VTM when we finally have released it.

**Comment by moving-bits** [comment] 2024-02-18 21:26
No objections coming in yet, thus let's close as "won't fix" for now (actually: the original issue got "fixed" by the mentioned mitigation, and the feature that got removed by the mitigation is a "won't fix" for now)

**Closed by moving-bits** 2024-02-18 21:26 UTC
Labels: Bug, Map: Unified
