### ISSUE TITLE
wrong LogID and LogType in exported GPX

### ISSUE THREAD

**Issue by andrixnet** [cgeo/cgeo#5750] opened 2016-05-23 08:56 UTC
##### Detailed steps causing the problem:
- Take any cache. My research was done on http://coord.info/GC65F6R
- export that cache as GPX (premium account only) from geocaching.com
- import and refresh that cache in GSAK, then export it again to another file, for comparison
- import and refresh that cache in c:geo, then export it again to another file, for comparison
- load the c:geo refreshed and exported file back into GSAK
##### Actual behavior after performing these steps:

GSAK now shows duplicate logs.

In my example research, take the FOUND log by user "vomhoger".

Log in GPX export from geocaching.com or GSAK

```
        <groundspeak:log id="601469664">
          <groundspeak:date>2016-05-17T11:00:44Z</groundspeak:date>
          <groundspeak:type>Found it</groundspeak:type>
          <groundspeak:finder id="1800425">vomhoger</groundspeak:finder>
          <groundspeak:text encoded="False">Found during our holidays in Bucharest. 
Greetings from Switzerland
TFTC</groundspeak:text>
        </groundspeak:log>
```

Notice the ID=601469664
Notice the TYPE=Found it (first letter uppercase)

Log exported by c:geo

```
<groundspeak:log id="268840"><groundspeak:date>2016-05-17T11:00:43Z</groundspeak:date><groundspeak:type>found it</groundspeak:type><groundspeak:finder id="">vomhoger</groundspeak:finder><groundspeak:text encoded="False">Found during our holidays in Bucharest. 
Greetings from Switzerland
TFTC</groundspeak:text></groundspeak:log>
```

Notice the different log ID
Notice the different letter case in TYPE

**Also, GPX exported by c:geo has not source code formating.**

Upon investigating the geocaching.com webpage, I found JSON data : 
`{"LogID":601469664,`

I was however unable to find `268840` anywhere in the page source (the log ID exported by c:geo)

The result is that exporting data from c:geo and importing it into GSAK results in duplicate logs.
Log counts are skewed.
Also, any custom SQL queries saved in GSAK need to be updated to handle both uppercase and lowercase letters. 
##### Expected behavior after performing these steps:
- c:geo to export correct Log ID
- c:geo to export Log TYPE using the same upper and lower case conventions as the GPX from geocaching.com
- c:geo to export GPX files with proper source code formatting as the GPX from geocaching.com
##### Version of c:geo used:

2016.05.09
##### Is the problem reproducible for you?

Yes
##### System information:

```
Android 4.2.1
```

**Comment by Lineflyer** [comment] 2016-05-23 09:03
To help me understand your problem: Why is it important to have the same LogID?

**Comment by SammysHP** [comment] 2016-05-23 13:46
LogID is a duplicate of #4023.

**Comment by andrixnet** [comment] 2016-05-26 08:38
If I exchange data with GSAK both ways (import into c:geo from GSAK, then export from c:geo to GSAK), I get duplicate logs, same as #4023, just different app.

Using c:geo gave the opportunity to go around nr. of logs limitation in GSAK (and the manual complexity and limitations of pocket queries), but doesn't help actually because of this duplication.

**Comment by Lineflyer** [comment] 2021-12-12 11:01
@andrixnet 
Looking at #4023 the logID problem seems solved.
Can you check if this issue is still existing/relevant?

**Comment by fm-sys** [comment] 2022-06-05 21:31
No feedback arrived, so let's close as stale...

**Closed by fm-sys** 2022-06-05 21:31 UTC
