### ISSUE TITLE
Introduce map zoom factor for devices with xhdpi displays

### ISSUE THREAD

**Issue by ChrisEt** [cgeo/cgeo#4480] opened 2014-11-09 09:09 UTC
**Problem:**
Some Android devices have a very high pixel density. For example my Xperia Z has 443ppi. 
Mapnik-rendered maps have a constant pixel height for all labels. For example a street name is ~6pixels in height.
As a result, labels are often so small they are not readable any more. For example a street name on my Xperia Z is smaller than 0.4mm

**Proposal:**
Introduce a customizable zoom factor. In _Preferenes/Maps_ below _Map Source_ I propose a slider with the title "Map Zoom" and the description "Magnify map images on devices with very high pixel density".

**Comment by Lineflyer** [comment] 2018-03-12 16:16
Closed as outdated / not updated.
Meanwhile we are about to implement mapsforge v0.9.

Please open a new issue / reopen this issue with updated information if the problem is still existing.

**Closed by Lineflyer** 2018-03-12 16:16 UTC
Labels: Frontend Design, Live Map
