### ISSUE TITLE
language settings are getting changed by c:geo

### ISSUE THREAD

**Issue by Grizzly70** [cgeo/cgeo#4973] opened 2015-05-25 20:12 UTC
Good evening
As geocaching.com let us know, it's the c:geo app, that seems to have an error/bug as it sets back the language settings on geocaching.com to english all the time. Sorry, but only part on this planet speeks english. Would be great if you could fix this.
Thanks in advance
Best Regards
Grizzly70

**Comment by rsudev** [comment] 2015-05-25 20:16
Hi Grizzly70 - this is not a bug, but by design. As c:geo parses the website it can only do that in English and sets the website therefore to English on login. See also http://faq.cgeo.org/#1_39
Closing.

**Closed by rsudev** 2015-05-25 20:16 UTC

**Comment by OschauLars** [comment] 2016-01-21 10:52
Dear rsudev,
then this is a bad design. If you have  to switch to English, you should remember the prior language and switch back to it.
I find it annoying to do this manually. Therefore I will stop using c:geo although it was in general a very helpful app.

**Comment by rsudev** [comment] 2016-01-21 11:20
@OschauLars We always welcome constructive feedback. If you have a suggestion for a better design, please step in. Unfortunately is practically impossible (IMO) to define when to switch back.
As we are open source you are welcome to study the flow in our implementation and make suggestions to remedy that.
