### ISSUE TITLE
Hide all Caches [Livemap] 

### ISSUE THREAD

**Issue by fm-sys** [cgeo/cgeo#8629] opened 2020-07-13 22:05 UTC
When searching for a specific location on the live map, it is often annoying when the map is crowded by caches.

Currently there is the function Switch off update. 
But of course this only helps if the caches are not loaded yet. If so, you have to close and restart c:geo at the moment.

So I would like to have a function for temporarily hiding all caches on Livemap...

**Comment by fm-sys** [comment] 2020-07-14 04:55
I found #7667 and think, that would be a good way to implement.

A cache filter in the livemap menu with the options:
- show all 
- show saved 
- show unsaved 
- hide all

**Comment by Lineflyer** [comment] 2020-07-14 10:59
Duplicate of #5599

**Comment by Lineflyer** [comment] 2020-07-14 11:00
Please follow up your ideas in the referenced issue.

**Closed by Lineflyer** 2020-07-14 10:59 UTC
Labels: Feature Request, Unverified
