### ISSUE TITLE
add support for amazfit bip u pro

### ISSUE THREAD

**Issue by hartunic** [cgeo/cgeo#12946] opened 2022-04-30 20:01 UTC
### Tell us your idea!

Make cgeo work with amazfit bip u pro and display details like distance  in feet and miles

### What solution would you suggest?

Should show the distance

**Comment by Lineflyer** [comment] 2022-04-30 20:35
What is "amazfit bip u pro"? Any links to technical details and programming interface appreciated.

**Comment by hartunic** [comment] 2022-04-30 20:50
> What is "amazfit bip u pro"? Any links to technical details and programming interface appreciated.

Is a smart watch

**Comment by moving-bits** [comment] 2022-05-01 11:07
Duplicate of #12920, therefore closing here

**Closed by moving-bits** 2022-05-01 11:07 UTC
Labels: Feature Request, Duplicate

**Comment by moving-bits** [comment] 2022-05-01 11:08
If you want to provide any additional info on interfacing with this specific smart watch, please do so in the already existing issue (#12920)

**Comment by SammysHP** [comment] 2022-05-01 11:27
Not sure if it's a duplicate because the Amazfit is not a Wear device and uses its own SDK (although I don't know if it's already accessible for everyone).
