### ISSUE TITLE
Map crashes on Android 10

### ISSUE THREAD

**Issue by lazydays79** [cgeo/cgeo#7824] opened 2019-09-08 09:36 UTC
**Describe the bug:**
I have a Google Pixel 3 xl running on Android 10. When I switch the map to Gmaps, cgeo crashes with a NoClassDefFound for Apaches Http Client class. 
I will try to analyze and fix this this evening, but I think it's a good idea to open the issue now. 

**To Reproduce:**
On Android 10 use Gmaps as map provider. 

**Actual behavior/state after performing these steps:**
FC caused by a NoClassDefFound exception. 

**Expected behavior/state after performing these steps:**
The map showing gmaps. :-)

**Version of c:geo used:**
2019.08.18

**Is the problem reproducible:**
Yes 

**System information:**
```
Device: Pixel 3 XL (crosshatch, google)
Android version: 10
Android build: QP1A.190711.020
c:geo version: 2019.08.18
Google Play services: enabled - 19.0.56 (120400-262933554)
Low power mode: inactive
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: rotation vector
Hide own/found: false
HW acceleration: enabled (default state)
System language: de_DE
System date format: dd.MM.yy
Debug mode active: no
System internal c:geo dir: /data/user/0/cgeo.geocaching (12,3 GB free) internal
User storage c:geo dir: /storage/emulated/0/cgeo (12,3 GB free) external non-removable
Geocache data: /storage/emulated/0/Android/data/cgeo.geocaching/files/GeocacheData (12,3 GB free) external non-removable
Database: /data/user/0/cgeo.geocaching/databases/data (17,7 MB) on system internal storage
Fine location permission: granted
Write external storage permission: granted
Geocaching sites enabled:
   geocaching.com: Logged in (Anmeldung OK) / PREMIUM
Geocaching.com date format: dd MMM yy
Installed c:geo plugins:  none```

**Comment by Lineflyer** [comment] 2019-09-08 10:35
Duplicate of #7369

**Closed by Lineflyer** 2019-09-08 10:35 UTC
Labels: Bug, Unverified

**Comment by Lineflyer** [comment] 2019-09-08 10:37
We have plans to change to GMapsv2 which should implicitly solve the issue.
A branch with a working version is already here, however any help is appreciated.

If we could get gmapv1 running on Android 10 again until gmapv2 is ready, that would be even better.

**Comment by Lineflyer** [comment] 2019-09-08 10:42
Please kindly continue conversation in #7369

**Comment by lazydays79** [comment] 2019-09-08 10:59
I'll do 👍
