### ISSUE TITLE
UnsupportedOperationException

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#6429] opened 2017-03-22 11:46 UTC
From Google Play.
Occurence started with November 2016 release.

Is this connected to the recent issues with methods not available in API14-19 ?

```
java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$3.done(AsyncTask.java:309)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
	at java.lang.Thread.run(Thread.java:818)
Caused by: java.lang.UnsupportedOperationException
	at java.util.Collections$SingletonSet$1.remove(Collections.java:260)
	at java.util.AbstractCollection.remove(AbstractCollection.java:229)
	at cgeo.geocaching.storage.DataStore.moveToList(DataStore.java:2939)
	at cgeo.geocaching.command.MoveToListCommand.doCommand(MoveToListCommand.java:47)
	at cgeo.geocaching.CacheListActivity$14.doCommand(CacheListActivity.java:965)
	at cgeo.geocaching.command.AbstractCommand$ActionAsyncTask.doInBackgroundInternal(AbstractCommand.java:110)
	at cgeo.geocaching.command.AbstractCommand$ActionAsyncTask.doInBackgroundInternal(AbstractCommand.java:103)
	at cgeo.geocaching.utils.AsyncTaskWithProgress.doInBackground(AsyncTaskWithProgress.java:104)
	at android.os.AsyncTask$2.call(AsyncTask.java:295)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	... 4 more
```

**Comment by samueltardieu** [comment] 2017-03-22 11:48
This is likely a duplicate of #6419 which has been fixed yesterday. The fix will be in the next release.

**Closed by samueltardieu** 2017-03-22 11:48 UTC
Labels: Bug, Google Play related
