### ISSUE TITLE
Wrong fontsizes after switching mapsforge render theme

### ISSUE THREAD

**Issue by helmo2004** [cgeo/cgeo#6738] opened 2017-09-24 20:38 UTC
##### Detailed steps causing the problem:
- Use a mapsforge offline map in live map
- Change rendering theme

##### Actual behavior after performing these steps:
Map shows wrong fontsizes. E.g. for contour line descriptions or street names. (See attached pictures)

##### Expected behavior after performing these steps:
Map shows correct fontsizes directly after switching map theme.

##### Workaround #####
Reload complete map by re-entering live map.

##### Version of c:geo used:
2017.08.23

##### Is the problem reproducible for you?
Yes.

##### System information:
```
--- System information ---
Device: SM-G930F (heroltexx, samsung)
Android version: 7.0
Android build: NRD90M.G930FXXS1DQHW.Helios.7.22.0
c:geo version: 2017.08.23
Google Play services: enabled - 11.5.09 (448-164803921)
Low power mode: inactive
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: rotation vector
Hide own/found: true
Map strategy: detailed
HW acceleration: enabled (default state)
System language: de_DE
System date format: dd.MM.yy
Debug mode active: no
System internal c:geo dir: /data/user/0/cgeo.geocaching (18,2 GB free) internal
User storage c:geo dir: /storage/emulated/0/cgeo (18,2 GB free) external non-removable
Geocache data: /storage/emulated/0/Android/data/cgeo.geocaching/files/GeocacheData (18,2 GB free) external non-removable
Database: /storage/emulated/0/Android/data/cgeo.geocaching/files/databases/data (984,0 KB) on user storage
Fine location permission: granted
Write external storage permission: granted
Geocaching sites enabled:
   geocaching.com: Logged in (Anmeldung OK) / PREMIUM
Geocaching.com date format: MM/dd/yyyy
Installed c:geo plugins:  none
--- End of system information ---
```

##### Other comments and remarks:
[wrong_font_sizes_after_switching_theme](https://user-images.githubusercontent.com/6477497/30786506-4de42df8-a177-11e7-9a82-b69d4a5ce529.png)

[right_font_sizes_after_reentering_live_map](https://user-images.githubusercontent.com/6477497/30786507-4de749ac-a177-11e7-98ee-abce54e50e61.png)

**Comment by Lineflyer** [comment] 2017-09-24 21:03
Thanks for reporting.

AFAIR a duplicate of an issue created by myself some time ago.

**Comment by helmo2004** [comment] 2017-09-24 21:20
Seems to be solved using mapsforge beta feature:


![beta switch](https://cloud.githubusercontent.com/assets/780005/17383435/43249324-59d6-11e6-9b19-bce846cc8ed6.png)

**Comment by Lineflyer** [comment] 2017-10-09 19:13
Duplicate of #4398

**Closed by Lineflyer** 2017-10-09 19:13 UTC
