### ISSUE TITLE
Search UI rendered with smaller controls after changing screen orientation

### ISSUE THREAD

**Issue by rainerbossert** [cgeo/cgeo#5216] opened 2015-10-02 18:44 UTC
1. open search menu, large controls 
![1](https://cloud.githubusercontent.com/assets/14945026/10254723/ceeb357a-6945-11e5-8750-84714c4677e8.png)
2. open live map
![2](https://cloud.githubusercontent.com/assets/14945026/10254748/eef87918-6945-11e5-9c66-f6685fa138b8.png)
3. switch orientation by turning the device
![3](https://cloud.githubusercontent.com/assets/14945026/10254779/1a42c696-6946-11e5-9876-f2cca3503f57.png)
4. go back to search menu, small controls
![4](https://cloud.githubusercontent.com/assets/14945026/10254787/27a37e52-6946-11e5-962d-0f2e1028f441.png)

c:geo: 2015.09.28
Device: Samsung SM-G800F (Galaxy S5 Mini)
OS: 4.4.2 (B800FXXU1AOC8)

**Comment by samueltardieu** [comment] 2015-10-03 15:32
I cannot reproduce this on Nexus 5.

**Comment by Lineflyer** [comment] 2015-10-05 15:30
Me neither on Samsung S4.

**Comment by Lineflyer** [comment] 2016-02-15 11:30
Closing as not clearly reproducible on other devices and not a functional problem. It is unlikely that we can change anything here without being able to test it and without knowing possible issues a possible change would cause on other devices (which are working normal right now).

**Closed by Lineflyer** 2016-02-15 11:30 UTC
Labels: Bug, Frontend Design, Unverified
