### ISSUE TITLE
Zooming in is bumpy on mapsforge 0.11

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#7523] opened 2019-04-19 18:46 UTC
I noticed since some days (nightlies), that when pinching or zooming on an offline map the rerendering is not really smooth all the time.

Sometimes it workd normal but sometimes tiles need lot of time to show up in new zoomlevel and cache icons remain too large (on zoomout) until they are new rendered.
I have  never seen this so frequently befor and on my Samsung S10 I would not think its a device performance problem.

From the commit history I suspect the upgrade to mapsforge 0.11 or the trail function (but it happens also if the trail is switched off....so probably not related).

**Comment by moving-bits** [comment] 2019-04-20 20:22
Lastly I have rendering problems (tile loading problems) as well. In LogCat I can see a couple of error messages, which seem related to host name resolving:

`Unable to resolve host "c.tile.openstreetmap.org": No address associated with hostname java.net.UnknownHostException: Unable to resolve host "c.tile.openstreetmap.org": No address associated with hostname
        at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:95)
        at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:74)
        at java.net.InetAddress.getAllByName(InetAddress.java:752)
        at com.android.okhttp.internal.Network$1.resolveInetAddresses(Network.java:29)
        at com.android.okhttp.internal.http.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:187)
        at com.android.okhttp.internal.http.RouteSelector.nextProxy(RouteSelector.java:156)
        at com.android.okhttp.internal.http.RouteSelector.next(RouteSelector.java:98)
        at com.android.okhttp.internal.http.HttpEngine.createNextConnection(HttpEngine.java:345)
        at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:328)
        at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:246)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:457)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:405)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getHeaders(HttpURLConnectionImpl.java:162)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getHeaderField(HttpURLConnectionImpl.java:206)
        at java.net.URLConnection.getContentEncoding(URLConnection.java:522)
        at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getContentEncoding(DelegatingHttpsURLConnection.java:142)
        at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getContentEncoding(HttpsURLConnectionImpl.java)
        at org.mapsforge.map.layer.download.TileDownloader.getInputStream(TileDownloader.java:34)
        at org.mapsforge.map.layer.download.TileDownloader.downloadImage(TileDownloader.java:71)
        at org.mapsforge.map.layer.download.TileDownloadThread.downloadTile(TileDownloadThread.java:81)
        at org.mapsforge.map.layer.download.TileDownloadThread.doWork(TileDownloadThread.java:60)
        at org.mapsforge.map.util.PausableThread.run(PausableThread.java:149)
` (with different host names "a", "b" and "c")

Not sure if this is related, and if it's caused by a weak WLAN on my side or server problems.
(this is on API 24 emulator)

**Comment by Lineflyer** [comment] 2019-04-20 21:36
In my case it was an offline map, so a different case I assume.

**Comment by Lineflyer** [comment] 2019-04-23 19:06
By testing a bit more I have following observations:
- Only happens in portrait mode (landscape works much smoother)
- Only happens on zoom in (but not on zoom out) 
- Only happening on some zoom level (cannot tell which level as the new map is missing the debug info in the title...separate issue). Roughly speaking: Zooming in until 500m/unit seems mostly OK, the more zoomed in below 500m/unit it gets worse)
- Both map tiles and overlays are zoomed but not rerendered in correct size for a few seconds

Thats a typical zoom in look which hangs for some seconds before being rendered correctly:

![Screenshot_20190419-133108_cgeo](https://user-images.githubusercontent.com/949669/56608342-daea3900-660a-11e9-8dd7-d73d33ee33f2.jpg)

**Comment by rsudev** [comment] 2019-04-25 09:50
Today I did a direct comparison with current master either using mapsforge 0.11.0 or 0.9.1.
I couldn't see any difference in rendering performance, even when looking specially at zooming in like you descibed the scenario.

**Comment by Lineflyer** [comment] 2019-04-25 10:09
I will give it a try as well with release version on same device.

This means the problem is or is not existing for you in both versions?

**Comment by Lineflyer** [comment] 2019-04-25 10:25
For me the release version is much faster on zooming in than todays nightly.

As I only compared to the release version, there are of course other changes in as well.

@moving-bits 
There is also the new trail saving to database between those two versions. Is there any part of the new code involved even if the trail feature is switched off completely?

**Comment by Lineflyer** [comment] 2019-04-25 12:30
@moving-bits 
I tried to follow and understand the code for positionHistory and positionDrawer and might it be, that the position is recorded all the time but the "Show trail" switch only enables the drawing overlay?
In that case I would assume, that it was no performance problem before as the history was recorded to memory but now its recorded to the database, which is more time consuming?
But even then, I am wondering why positionhistory should be triggered by zooming the map without changing my current position.

At the end I have no more clues, please help, but at least tried to read some code :)

**Comment by rsudev** [comment] 2019-04-25 14:33
@Lineflyer Compared to earlier it might be a bit more 'laggy' than previously, but it is not prominent enough compared to my memories to be sure.
I will try to do a similar comparison based on the release version (but it's a bit tricky due to the db-schema change).

**Comment by moving-bits** [comment] 2019-04-25 16:09
@rsudev 
While debugging a different issue a couple of days ago I've stumbled upon that the trail gets redrawn on every location signal, whether the position has been changed or not. In my emulator this was ten times per second! (But I'm not sure how much performance this actually costs. And also it's not related to zooming directly.)

I tried a quick fix by comparing the last drawn position with the current one, but this led to the line not being drawn at all, as the emulator always starts at the same position... Is there any specific marker by which I can identify whether the trail has been drawn already at least once?

**Comment by Lineflyer** [comment] 2019-04-25 16:30
@moving-bits 
What about my initial question:
> There is also the new trail saving to database between those two versions. Is there any part of the new code involved even if the trail feature is switched off completely?

**Comment by moving-bits** [comment] 2019-04-25 16:51
> What about my initial question:
> > There is also the new trail saving to database between those two versions. Is there any part of the new code involved even if the trail feature is switched off completely?

It's integrated in the existing trail history functions - I'll need to look it up whether they get called independently of the feature setting.

**Comment by moving-bits** [comment] 2019-04-27 07:23
I've dived into the code: `rememberTrailPosition` is the place where the trailpoint gets stored (to memory and to database). This function gets called for every trailpoint.
The setting "show track" only relates to painting the trail and has no influence on whether the trail gets stored or not.
But it should not cause delays on zooming as saving a trailpoint not only is fast but done in the background.

**Comment by Lineflyer** [comment] 2019-04-27 11:06
I have made two videos with a comparison.
Same device, same map and theme files

Current nightly:
https://files.droescher.eu/public/mapsforge_11.mp4

Release version:
https://files.droescher.eu/public/mapsforge_9.mp4

**Comment by Lineflyer** [comment] 2019-04-27 11:49
After testing with the debug.apk derived from #7562 I can say, that with mf 0.9.1 the problem is gone.
So it seems related to the mapsforge library version and not to other changes we had (e.g. trail).

Maybe this gives some clues:
- If I perform the scenario as shown in the video of current nightly, zoom out again and zoom in again the problem does no longer occur. This looks a bit like the first loading of the new (zoomed) tiles from the offline map file takes longer time than later on (when they are probably cached?!). 

- Additionally the laziness gets worse if I jump in over several zoom steps, a bit like all different zoom steps are still be done in the background.

**Comment by rsudev** [comment] 2019-04-29 14:26
The findings reported here will be traced and handled in #7494

**Closed by rsudev** 2019-04-29 14:26 UTC
Labels: Bug, New Map OSM, Performance, Unverified

**Comment by jonas-koeritz** [comment] 2019-07-27 17:19
I did some profiling today and found that rendering tiles got slower in the last few releases. This might have been due to some quality improvements in mapsforge.
Fortunately mapsforge offers an option to use a faster rendering method. I tried it and can't see any noticable quality decrease on my phone.
I will update my Mapsforge 0.11.0 pull request to include the fast rendering method.
