### ISSUE TITLE
keep timestamp at reload

### ISSUE THREAD

**Issue by geocachermgo** [cgeo/cgeo#14775] opened 2023-10-29 10:40 UTC
### Tell us your idea!

It something between a bug and a feature request. The time of a log shown in the history (Verlauf) and used for sorting is reset to 0:00 if the cache is updated from geocaching.com.
So if you are e.g. editing a log on the website and updating the cache from geocaching.com in c:geo the timestamp is lost.

### What solution would you suggest?

If the date of the log retrieved from geocaching.com is the same as in c:geo, the time should be left unaltered.

### Additional Information

It's related to https://github.com/cgeo/cgeo/issues/14122 but the other way round. There is a timestamp in c:geo if you write your log in c:gei but not at geocaching.com.
I was taking the behavoiur it as it is, but since yesterday a fellow cacher complained I am requesting it as a feature. (at least 2 cacher think, that it can be done better)

**Comment by moving-bits** [comment] 2024-02-02 21:31
duplicate of #9653

**Closed by moving-bits** 2024-02-02 21:31 UTC
Labels: Feature Request, Unverified, Duplicate
