### ISSUE TITLE
Map popup - offline logging is not in fieldnotes export

### ISSUE THREAD

**Issue by Mac-Gyver** [cgeo/cgeo#5840] opened 2016-07-18 12:01 UTC
In LiveMap-Popup is the posibility to "One Click offline log" - "Found it".... if I do so, this offline log is not in the History an not in Fieldnotes export. It only appers, when u open the Listing....

##### Is the problem reproducible for you?
Yes

##### System information:
```
Attach system information here if available (see c:geo menu -> About c:geo -> System)
```

**Comment by SammysHP** [comment] 2016-07-18 12:43
Duplicate of #4086.

**Closed by SammysHP** 2016-07-18 12:43 UTC
