### ISSUE TITLE
Empty Logbook 

### ISSUE THREAD

**Issue by shrinknose** [cgeo/cgeo#6276] opened 2017-01-22 15:02 UTC
##### Detailed steps causing the problem:
- Step 1 search and save a Cache from geocaching.com or even a refresh a stored Cache 

##### Actual behavior after performing these steps:
now The Logbook is Empty 
- ...

##### Version of c:geo used:
Latest beta :

Hi

Problems 

-- System information ---
Device: SM-G930F (heroltexx, samsung)
Android version: 6.0.1
Android build: MMB29K.G930FXXU1BPLB
Cgeo version: 2017.01.15
Google Play services: disabled - 10.0.84 (440-137749526)
Low power mode: inactive
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: rotation vector
Hide own/found: true
Map strategy: auto
HW acceleration: enabled (default state)
System language: de_DE
Log date format: 22.01.17
Debug mode active: no
Fine location permission: granted
Write external storage permission: granted
Geocaching sites enabled:
   geocaching.com: Logged in (Anmeldung OK) / PREMIUM
Geocaching.com date format: MM/dd/yyyy
Installed cgeo plugins: calendar, contacts
--- End of system information ---

##### Is the problem reproducible for you?
Yes/No

##### System information:
```
Attach system information here if available (see c:geo menu -> About c:geo -> System)
Keep the apostrophe at beginning and end to have it properly formatted
```

##### Other comments and remarks:
e.g. Reference to other issues, projects, sources, etc.

**Comment by samueltardieu** [comment] 2017-01-22 15:34
Not reproducible on `master`.

**Comment by pstorch** [comment] 2017-01-22 16:46
Had a user on Facebook reporting this, too. After Phone restart the logbook got loaded again.

**Comment by shrinknose** [comment] 2017-01-22 17:15
Reboot of the Smartphone fixed The bug.


Am 22. Januar 2017 16:34:10 MEZ schrieb Samuel Tardieu <notifications@github.com>:
>Not reproducible on `master`.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/cgeo/cgeo/issues/6276#issuecomment-274337849

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by shrinknose** [comment] 2017-01-22 17:16
Bingo! 

Reboot of the Smartphone fixed The bug

Am 22. Januar 2017 17:46:28 MEZ schrieb Peter Storch <notifications@github.com>:
>Had a user on Facebook reporting this, too. After Phone restart the
>logbook got loaded again. 
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/cgeo/cgeo/issues/6276#issuecomment-274342273

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by samueltardieu** [comment] 2017-01-22 17:28
Rebooting the smartphone is too close to black magic for my taste. Killing the application from the recent applications list should have been enough :-)

**Comment by pstorch** [comment] 2017-01-22 17:32
I'm wandering what is happening here. Yes, I'll suggest killing the app first, to see if it is only c:geo which is having the problem.

**Comment by Lineflyer** [comment] 2017-01-22 23:47
My guess:Maybe the issue creator has used the website and cgeo in parallel and switched the website to another language than english?


Von meinem Smartphone gesendet.
-------- Ursprüngliche Nachricht --------Von: Peter Storch <notifications@github.com> Datum: 22.01.17  12:32  (GMT-05:00) An: cgeo/cgeo <cgeo@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Betreff: Re: [cgeo/cgeo] Empty Logbook (#6276) 
I'm wandering what is happening here. Yes, I'll suggest killing the app first, to see if it is only c:geo which is having the problem.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/cgeo/cgeo","title":"cgeo/cgeo","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/cgeo/cgeo"}},"updates":{"snippets":[{"icon":"PERSON","message":"@pstorch in #6276: I'm wandering what is happening here. Yes, I'll suggest killing the app first, to see if it is only c:geo which is having the problem. "}],"action":{"name":"View Issue","url":"https://github.com/cgeo/cgeo/issues/6276#issuecomment-274345157"}}}

**Comment by shrinknose** [comment] 2017-01-23 06:12
Hi 
Possible that I had geocaching.com open in a Browser in the background. The fact was each and every Logbook I refreshed was Empty afterwards. Also Caches I loaded New Into cgeo showed an Empty log book. But in case this is a know issue and not possible to fix it is worth to be mentioned in the FAQs 

Thanks for taking care and developing such a great app 

Gerald 

Am 23. Januar 2017 00:47:59 MEZ schrieb Lars <notifications@github.com>:
>My guess:Maybe the issue creator has used the website and cgeo in
>parallel and switched the website to another language than english?
>
>
>Von meinem Smartphone gesendet.
>-------- Ursprüngliche Nachricht --------Von: Peter Storch
><notifications@github.com> Datum: 22.01.17  12:32  (GMT-05:00) An:
>cgeo/cgeo <cgeo@noreply.github.com> Cc: Subscribed
><subscribed@noreply.github.com> Betreff: Re: [cgeo/cgeo] Empty Logbook
>(#6276) 
>I'm wandering what is happening here. Yes, I'll suggest killing the app
>first, to see if it is only c:geo which is having the problem.
>
>—
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly, view it on GitHub, or mute the thread.
>
>
>  
>  
>
>
>
>
>{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/cgeo/cgeo","title":"cgeo/cgeo","subtitle":"GitHub
>repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open
>in
>GitHub","url":"https://github.com/cgeo/cgeo"}},"updates":{"snippets":[{"icon":"PERSON","message":"@pstorch
>in #6276: I'm wandering what is happening here. Yes, I'll suggest
>killing the app first, to see if it is only c:geo which is having the
>problem. "}],"action":{"name":"View
>Issue","url":"https://github.com/cgeo/cgeo/issues/6276#issuecomment-274345157"}}}
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/cgeo/cgeo/issues/6276#issuecomment-274370505

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by pstorch** [comment] 2017-01-23 08:09
Tried to reproduce this, by opening the desktop browser in parallel and changing language to other than english. It still loaded the logbook correctly.
Maybe it's something else.

**Comment by shrinknose** [comment] 2017-01-23 09:26
(un) fortunatly I can also no longer reproduce. If it appears again I`ll inform you 
Greetings from Fürth 
Gerald 

Am 23. Januar 2017 09:09:44 MEZ schrieb Peter Storch <notifications@github.com>:
>Tried to reproduce this, by opening the desktop browser in parallel and
>changing language to other than english. It still loaded the logbook
>correctly.
>Maybe it's something else.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/cgeo/cgeo/issues/6276#issuecomment-274423332

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by Lineflyer** [comment] 2017-02-06 20:15
Closing as no longer reproducible and no other reports like that.

**Comment by pstorch** [comment] 2017-02-15 08:31
After a new Report on FB this morning, I looked again into this issue.
If for some reason the loading of the logs fail (e.g. Network problem) then we delete all previous logs and save an empty list.
- `GCParser.getLogs()` returns `Observable.empty()` in case of any Exception. Can be network, can be parsing problem.
- `DataStore.saveLogsWithoutTransaction()` first deletes all previous logs and stores the empty list from above.

We should keep the logs we have in case of an error. And inform the user (via Toast) that the logs couldn't be loaded for whatever reason.

**Comment by pstorch** [comment] 2017-02-17 08:50
Another hint from a user. After changing the date format it worked again. It seems that c:geo sometimes doesn't get the date format correct.

**Comment by pstorch** [comment] 2017-02-17 13:49
Accidentally closed. This is only partly fixed. 
An error message is missing to indicate to the user that loading the logs failed for some reason.

**Comment by Lineflyer** [comment] 2017-02-21 21:50
@pstorch With the partial fix I dont see this as a "high" "bug" right now. I suggest to open a follow up issue instead with the remaining ToDo.
Feel free to reopen if you disagree

**Closed by Lineflyer** 2017-02-21 21:50 UTC
Labels: Bug, high, Regression, Unverified

**Comment by pstorch** [comment] 2017-02-21 22:04
@Lineflyer yes, definitely not high anymore. I saw one user on FB who again had an empty logbook because of wrong date format. Let's open a new one if this happens again.
