### ISSUE TITLE
NoClassDefFoundError 'drop' cache from list from long press action

### ISSUE THREAD

**Issue by kumy** [cgeo/cgeo#4966] opened 2015-05-23 01:01 UTC
From master 1b4ff80d0c

* open a saved list
* long press on a cache
* select 'Drop'

```
java.lang.NoClassDefFoundError: cgeo.geocaching.command.AbstractCommand$ActionAsyncTask
            at cgeo.geocaching.command.AbstractCommand.execute(AbstractCommand.java:96)
            at cgeo.geocaching.command.DeleteCachesCommand.execute(DeleteCachesCommand.java:17)
            at cgeo.geocaching.CacheListActivity.deleteCachesInternal(CacheListActivity.java:1196)
            at cgeo.geocaching.CacheListActivity.onContextItemSelected(CacheListActivity.java:919)
            at android.app.Activity.onMenuItemSelected(Activity.java:2905)
            at android.support.v4.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:373)
            at android.support.v7.app.ActionBarActivity.superOnMenuItemSelected(ActionBarActivity.java:245)
            at android.support.v7.app.ActionBarActivityDelegateICS.onMenuItemSelected(ActionBarActivityDelegateICS.java:164)
            at android.support.v7.app.ActionBarActivity.onMenuItemSelected(ActionBarActivity.java:131)
            at android.support.v7.app.ActionBarActivityDelegateICS$WindowCallbackWrapper.onMenuItemSelected(ActionBarActivityDelegateICS.java:308)
            at com.android.internal.policy.impl.PhoneWindow$DialogMenuCallback.onMenuItemSelected(PhoneWindow.java:4960)
            at com.android.internal.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:761)
            at com.android.internal.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:152)
            at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:904)
            at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:894)
            at com.android.internal.view.menu.MenuDialogHelper.onClick(MenuDialogHelper.java:167)
            at com.android.internal.app.AlertController$AlertParams$3.onItemClick(AlertController.java:1082)
            at android.widget.AdapterView.performItemClick(AdapterView.java:305)
            at android.widget.AbsListView.performItemClick(AbsListView.java:1148)
            at android.widget.AbsListView$PerformClick.run(AbsListView.java:3059)
            at android.widget.AbsListView.onTouchUp(AbsListView.java:3878)
            at android.widget.AbsListView.onTouchEvent(AbsListView.java:3643)
            at android.view.View.dispatchTouchEvent(View.java:8472)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2400)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2093)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2406)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2107)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2406)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2107)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2406)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2107)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2406)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2107)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2406)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2107)
            at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2625)
            at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1770)
            at android.app.Dialog.dispatchTouchEvent(Dialog.java:765)
            at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2586)
            at android.view.View.dispatchPointerEvent(View.java:8667)
            at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4129)
            at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:3995)
            at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3550)
            at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3603)
            at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3569)
            at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3686)
            at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3577)
            at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3743)
            at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3550)
```

**Comment by Bananeweizen** [comment] 2015-05-23 06:15
Duplicate of #4967, even if it refers to another class.

**Closed by Bananeweizen** 2015-05-23 06:15 UTC
Labels: Bug
