### ISSUE TITLE
Duplicate between projected WP and personal note WP not detected

### ISSUE THREAD

**Issue by MagpieFourtyTwo** [cgeo/cgeo#7429] opened 2019-03-27 22:35 UTC
##### Detailed steps causing the problem:
- add a new Waypoint (WP), with any coordinates
- perform projection of this WP (i. e. enter bearing & distance) and save it
- copy coordinates and store them in the Personal Note (PN)

##### Actual behavior after performing these steps:
- a new WP "Personal Note x" will be extracted from the PN although there already exists the previously projected WP with the seemingly identical coordinates
- this WP "Personal Note x" can not be deleted
   (unless you copy it's coordinates and paste them into the projected WP;
   after having performed this probably "cutting off of invisible digits",
   the WP "Personal Note x" can be deleted)

##### Expected behavior after performing these steps:
- there should not be two WPs with the seemingly identical coordinates
- thus either projected WP should contain not more digits (i. e. pseudo precision) than visible
- or extraction of WPs out of PN should roud/cut off pseudo precision digits before comparing to already existing WPs

##### Version of c:geo used:
- 2019.03.27-NB-b5e943a

##### Is the problem reproducible for you?
- Yes

##### System information:
--- System information ---
Device: E6853 (E6853, Sony)
Android version: 7.1.1
Android build: 32.4.A.1.54
c:geo version: 2019.03.27-NB-b5e943a
Google Play services: disabled - 15.0.90 (040408-231259764)
Low power mode: active
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: rotation vector
Hide own/found: true
Map strategy: detailed
HW acceleration: enabled (default state)
System language: de_DE
System date format: dd.MM.yy
Debug mode active: no
System internal c:geo dir: /data/user/0/cgeo.geocaching (7,0 GB free) internal
User storage c:geo dir: /storage/emulated/0/cgeo (7,0 GB free) external non-removable
Geocache data: /storage/emulated/0/Android/data/cgeo.geocaching/files/GeocacheData (7,0 GB free) external non-removable
Database: /data/user/0/cgeo.geocaching/databases/data (235,1 MB) on system internal storage
Fine location permission: granted
Write external storage permission: granted
Geocaching sites enabled:
   geocaching.com: Logged in (Anmeldung OK) / PREMIUM
   extremcaching.com: Logged in (Anmeldung OK)
Geocaching.com date format: dd MMM yy
Installed c:geo plugins: contacts
--- End of system information ---

##### Other comments and remarks:
I'm not really a friend of the automatic WP extraction and would love to see an option to disable it completely.  :)

**Comment by Lineflyer** [comment] 2019-03-28 11:07
AFAIK there is no duplicate check imnplemented, meaning if coordinates are found in the personal note, a waypoint will be created using them.
The described use case is a rare case in which a duplicate appears logically. 

I will label this as a feature request for such a duplicate check, however IMHO the appearance of such duplicates is rare (i.e. why should a user add a personal note of a waypoint also exisiting, he could just delete one of those).

**Comment by moving-bits** [comment] 2019-03-28 11:51
I have a different use case (but can live with it, so it's just for documentation):

I use the personal note field frequently for documentation on how to solve a certain mystery cache. Sometimes I add the resulting final coordinates as well. When such a cache is read by c:geo it adds a couple of waypoints: "original location", "final location" and a waypoint generated from the address in the personal note, which has the same coordinates as the "final location" waypoint.

**Comment by Lineflyer** [comment] 2019-03-28 11:59
Also: A handling for duplicates needs to be implicitly implemented when implementing #5688

**Comment by MagpieFourtyTwo** [comment] 2019-03-30 15:10
> AFAIK there is no duplicate check implemented, meaning if coordinates are found in the personal note, a waypoint will be created using them.

Au contraire ... ;) There *must* be some kind of duplicate check, as I for example can happily delete a "Personal Note" waypoint, if the coordinates already are in another waypoint, whereas a "Personal Note" waypoint reappears after deletion, when it is in the Personal Note, but there is no waypoint with these coordinates in the list yet.

> The described use case is a rare case in which a duplicate appears logically.

Not really. In fact it's really hard sometimes to find the "real" waypoints in the now and then endless list of dupes and even completely senseless waypoints, where c:geo has interpreted some numbers as coordinates, which in fact are nothing else then the solution steps of a mystery or multi ... thus I would *love* to have a setting to disable this "coordinate guessing" completely, as it really goes wild sometimes.

**Comment by Lineflyer** [comment] 2019-04-01 13:39
> Au contraire ... ;) There must be some kind of duplicate check.

I tested it now and have to admit, that you are right. I forgot about that.

It seems this issues is indeed caused by the projected waypoint not to be detected to be a duplicate of the personal note, unless you open it and save it again. Afterwards the duplicate check matches and one is able to remove the personal note.
So it could really be some inconsistency when storing the projected waypoint or indeed we use more precision/more digits in the background causing the non-match.

**Comment by geocachermgo** [comment] 2020-09-30 22:18
Note: Its possible to shift the position of a waypoint finer then 1/1000 minute. Eg 49 9 2m N und 1m S results in longitude being 49.000008 displayed as 49 0.000 and 49 0 0.029.
![Screenshot_2020-10-01-00-08-35-158_cgeo geocaching](https://user-images.githubusercontent.com/43813636/94745223-94117e80-037a-11eb-9bab-16ee7298a6fb.jpg)

But the edit menu shows 49 00 00.000
![Screenshot_2020-10-01-00-08-58-052_cgeo geocaching](https://user-images.githubusercontent.com/43813636/94745246-9b388c80-037a-11eb-9aa4-588397ece0ff.jpg)
Inputs in that input field seem to be transfered to d mm.mmm and back.
If you put in  49 00 00.035 you will get 49 0.001 and if you edit again the presetting will be 49 00 00.061
![Screenshot_2020-10-01-00-15-54-294_cgeo geocaching](https://user-images.githubusercontent.com/43813636/94745748-96280d00-037b-11eb-83c5-67f80810c99e.jpg)

**Comment by fm-sys** [comment] 2021-07-13 11:43
I can't reproduce the issue anymore. Therefore closing...

**Closed by fm-sys** 2021-07-13 11:43 UTC
Labels: Bug, Prio - Low
