### ISSUE TITLE
Problem if waypoint description contains a "<"

### ISSUE THREAD

**Issue by Matze2** [cgeo/cgeo#6791] opened 2017-10-23 06:00 UTC
##### Detailed steps causing the problem:
Scenario 1 on imported waypoint note:
- Import GC768Y3
- Note for waypoint "Stage 14" is truncated at the "less than" (<) sign

Scenario 2 on waypoint user note:
- Add a waypoint user note containing a "less than" (<) sign
- Only the text before the "less than" (<) sign is saved

##### Actual behavior after performing these steps:
See steps above

##### Expected behavior after performing these steps:
Full waypoint description is imported / saved

##### Version of c:geo used:
2017.10.18-NB-30e87fb

##### Is the problem reproducible for you?
Yes

##### System information:
```
On demand (should not matter)
```

**Comment by Matze2** [comment] 2017-10-23 06:03
Waypoint calculator note seems not affected.

**Comment by Lineflyer** [comment] 2017-10-23 08:56
Confirmed using GC768Y3 also in official release 2017.10.23

**Comment by pstorch** [comment] 2017-10-31 21:52
The description (note) of Stage 14 is recognized as HTML in

https://github.com/cgeo/cgeo/blob/2f1a321510ed2906e7619dc36c19d5c50bca0554/main/src/cgeo/geocaching/utils/TextUtils.java#L163-L173

and then later parsed by `Html.fromHtml()`:
https://github.com/cgeo/cgeo/blob/2f1a321510ed2906e7619dc36c19d5c50bca0554/main/src/cgeo/geocaching/CacheDetailActivity.java#L1871

finally the `<10` is recognized as a tag with name `_10` and forwarded to the `UnknownTagsHandler` with the rest stripped, because the end `>` of the opening tag is not found.

If there is a blank before the number like `< 10` then it is not recognized as a tag and it works.

We would have to find all `<` which are not starting a tag and replace them with `&lt;` before calling `Html.fromHtml()`. 
Any other idea?

**Comment by Matze2** [comment] 2017-11-01 08:17
Makes sense to me. Browsers probably use the same logic.

**Comment by pstorch** [comment] 2017-11-01 20:48
My problem is how to recognize correctly a `<` which is not part of a start tag.
Because a tag name can consist of alphanumeric characters:
https://www.w3.org/TR/html51/syntax.html#tag-name
So in our example the `<10` is a valid start of a start tag. 
Then how to recognize the corresponding `>` is missing? Just looking for `>` without another `<` in between is not good enough. There could be attributes in the tag which could have a `<` in the attribute value, so you have to count single and double quotes, too...
Parsing HTML with regex is awkward. I think it would be better if the `<` would be properly encoded in the first place or the Android `Html.fromHtml()` would ignore these invalid start tags.

**Comment by kumy** [comment] 2017-11-01 20:52
Did you tried with Jsoup parser?

On November 1, 2017 9:48:57 PM GMT+01:00, Peter Storch <notifications@github.com> wrote:
>My problem is how to recognize correctly a `<` which is not part of a
>start tag.
>Because a tag name can consist of alphanumeric characters:
>https://www.w3.org/TR/html51/syntax.html#tag-name
>So in our example the `<10` is a valid start of a start tag. 
>Then how to recognize the corresponding `>` is missing? Just looking
>for `>` without another `<` in between is not good enough. There could
>be attributes in the tag which could have a `<` in the attribute value,
>so you have to count single and double quotes, too...
>Parsing HTML with regex is awkward. I think it would be better if the
>`<` would be properly encoded in the first place or the Android
>`Html.fromHtml()` would ignore these invalid start tags.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/cgeo/cgeo/issues/6791#issuecomment-341237768

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by Lineflyer** [comment] 2017-11-01 21:33
@pstorch Maybe it has some synergy to also look at #4124 which could be(?) related?

**Comment by pstorch** [comment] 2017-11-01 21:43
@kumy yes, we could "clean" the HTML with Jsoup.

I tried the following:
```
final Document document = Jsoup.parse(wpt.getNote());
final String cleanedNote = document.outerHtml();
```
This is an extra parsing to DOM and serializing as String back for all waypoint notes. To avoid this extra work on every display of the waypoints, we could only put it into the GCParser when parsing the waypoint note from the website.

@Lineflyer the other issue is a little bit different. It's there is no support for html in the popup, but that can easily be fixed. I'll have a look.

**Comment by Matze2** [comment] 2017-11-05 18:43
Sorry for verifying this so late, but it is not completely solved.
The waypoint is now imported correctly but as soon as you open it and save it again the truncation is still there.
Same if you enter a waypoint user note with an "<".

**Comment by pstorch** [comment] 2017-11-05 18:59
You are right, saving destroys it. Even if the field is not editable.

**Comment by pstorch** [comment] 2017-11-05 20:36
I think we have a bigger problem here. We accept HTML code in the note fields. And it is displayed in the waypoint list correctly. But when we edit it again the valid html gets removed. And the non-valid html, like the `<10`, causes the note to be truncated.

We could escape all `<` with `&lt;`. This would solve this issue but would also remove HTML completely from the notes. To be more precise after this escaping all HTML tags would be shown like in source code. But as HTML doesn't work currently only halfway anyway, I think it could be fine to "disable" it.

**Comment by Lineflyer** [comment] 2017-11-06 15:03
@pstorch The original fix for this issue was done on `release`. Do we need to revert it or add another fix or can it stay like that and the remaining problem solved later on. 
I did not completely understand the problem now, but if it can lead to a bigger problem than before we should maybe revert the change on `release`.

BTW: Things like this were the reason, why I orginally asked not to put any more changes unrelated to finalization of new features onto the `release` branch ;)

**Comment by pstorch** [comment] 2017-11-06 20:20
@Lineflyer I don't think we need to revert it. It is better than before. It just not solving the problem with the "<" in all situations and revealed another issue with how we deal with HTML code in waypoint descriptions when we edit them. That was present all the time.
But of course I understand your concerns about too many changes in the release branch before the publish.

**Comment by Matze2** [comment] 2017-11-07 23:44
Some of HTML tags can be directly converted to text. I am particularly thinking of <br> which can be replaced by "\n". Then we keep at least the line formatting to some extent. See GC768Y3.

**Comment by Matze2** [comment] 2017-11-19 01:29
This is now also fixed with the above PR and can be closed. Thanks!

**Closed** 2017-11-19 07:51 UTC
Labels: Bug
