### ISSUE TITLE
filter "saved since" to '-' does not work

### ISSUE THREAD

**Issue by bekuno** [cgeo/cgeo#11196] opened 2021-07-12 13:10 UTC
## Bug description 
The Filter "saved since" with value "-" has no result.

### Steps to reproduce the problem
- Ensure in map that there are unsaved caches manually or by filter "Status" - "saved"
- open filter "saved since"
- set left and right value to '-"
- result: no caches in map are shown

### Expected result after these steps 
as the hint says 'not saved' I expect to see not saved caches from the map

## c:geo version 
2021.07.10-RC

## Reproducible 
Yes

**Comment by eddiemuc** [comment] 2021-07-12 14:06
Confirmed if user selects "just" the "-" value in slider.
Works as soon as user selects a range including the "-", e.g. "-" - "0".

Will be fixed

**Comment by eddiemuc** [comment] 2021-07-19 18:57
PR #11265 will fix this

This PR will also fix the strange  "a few minutes ago" message on cache detail popup for caches stored much longer time before. I discovered that it makes more sense to use the "detailsupdated" field rather than the "updated" field - because the later is set to current system time in Geocache-merge-method (don't know why).

**Closed** 2021-07-21 06:50 UTC
Labels: Bug
