### ISSUE TITLE
Date parsing not correct

### ISSUE THREAD

**Issue by pietmarcus** [cgeo/cgeo#7059] opened 2018-06-16 15:23 UTC
My GC account is set on European date format (so day-month-year). Today, June 16th, I posted a log with GSAK. On the site the date is correct. When I refresh the cache in c:geo the date reads 6-4-2019. It looks like c:geo takes the 16th month of 2018, which is April 2019, and the 6th day of that month.

**Comment by pstorch** [comment] 2018-06-16 16:09
Can you please upload your system information here? About - > System

There we can check what date format c:geo has recognized.

**Comment by pietmarcus** [comment] 2018-06-16 16:59
My wife, who has a different phone, but on the same GC account, has the same problem, with different caches.

Here is my system info:
--- System information ---
Device: Nexus 5X (bullhead, google)
Android version: 8.1.0
Android build: OPM6.171019.030.B1
c:geo version: 2018.02.05
Google Play services: enabled - 12.6.85 (040400-197041431)
Low power mode: inactive
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: rotation vector
Hide own/found: false
Map strategy: auto
HW acceleration: enabled (default state)
System language: nl_NL
System date format: dd-MM-yy
Debug mode active: no
System internal c:geo dir: /data/user/0/cgeo.geocaching (1,2 GB free) internal
User storage c:geo dir: /storage/emulated/0/cgeo (1,2 GB free) external non-removable
Geocache data: /storage/emulated/0/Android/data/cgeo.geocaching/files/GeocacheData (1,2 GB free) external non-removable
Database: /data/user/0/cgeo.geocaching/databases/data (12,7 MB) on system internal storage
Fine location permission: granted
Write external storage permission: granted
Geocaching sites enabled:
   geocaching.com: Logged in (Ingelogd) / PREMIUM
Geocaching.com date format: dd/MM/yyyy
Installed c:geo plugins:  none
--- End of system information ---

**Comment by pstorch** [comment] 2018-06-16 17:15
OK the recognized format is `Geocaching.com date format: dd/MM/yyyy`

And what is the date format setting on your Geocaching.com profile?

**Comment by pietmarcus** [comment] 2018-06-16 17:37
I refreshed the caches again, and suddenly the dates are back to normal... Very weird...

**Comment by pstorch** [comment] 2018-06-16 18:28
Sometimes a login fails and c:geo can't recognize the date format correctly. So it falls back to a standard one which is often different from the one that the user has defined.
This is later corrected with the next successfull login. But then you need to refresh again.
Unfortunately this happens from time to time.

**Comment by Lineflyer** [comment] 2018-06-17 19:14
I agree to @pstorch, that this was most likely a case of not being logged in, which could be e.g. caused by connection problems or problems on the geocaching server.

Therefore closing, feel free to reopen in case you suspect a c:geo problem instead.

**Closed by Lineflyer** 2018-06-17 19:14 UTC
