### ISSUE TITLE
GPX export doesn't contain "unlocated" waypoints

### ISSUE THREAD

**Issue by steve8x8** [cgeo/cgeo#5100] opened 2015-07-17 11:18 UTC
Additional Waypoints besides their coordinates carry some more information ("Note:" text, waypoint type). Wpts with lat=lon=0 should not be excluded when exporting GPX.
(c:geo 2015-07-16 nightly)

**Comment by rsudev** [comment] 2015-07-17 11:22
Just a remark: Waypoints without coordinates are, besides their frequent occurrence in the geocaching context, in violation of the specification.
Regarding your request: Do you really mean lat=0/lon=0 or lat/lon empty?

**Comment by steve8x8** [comment] 2015-07-17 17:39
I saw this - with 07-16 nightly - for cache GC3TWEM, which has a Start (S1, with coordinates) and a Final (Z1, no coords as this is a multi-cache) waypoint when loaded from gc.com.
Exporting this cache results in a file GC3TWEM.gpx http://steve8x8.faehrwiese.selfhost.me/cgeo/issue5100/GC3TEWM.gpx which contains S1 but not Z1.
In this case, Z1 doesn't carry any extra information though - but if it did, that would be part of the cache data, right?

I agree that lat/lon empty violates the protocol, but lat="0.000000" lon="0.000000" seem to be possible (even geo-html2gpx did that 5 years ago, and probably still does). What's the canonical way to GPX import waypoints that only come with three question marks in a cache listing?

**Comment by steve8x8** [comment] 2015-07-31 13:53
I found that this is a duplicate of issue #2490 - and while wpt elements without lat and lon indeed violate the standard, c:geo happily imports them (which I consider a Good Thing), preserving notes attached to them. Absolutely essential for paperless geocaching.
Speaking of cgeo extensions to the GPX format, is there a canonical path to the corresponding xsd file? The one suggested by the file in git doesn't work.

Thanks, S

**Comment by Lineflyer** [comment] 2016-11-20 11:11
As this is mentioned above to be a duplicate of #2490 and this issue is fixed, I am also closing this one. Feel free to reopen if this is not correct.

**Closed by Lineflyer** 2016-11-20 11:11 UTC
Labels: Bug, Feedback, Unverified
