### ISSUE TITLE
Caches from EC shown as saved once opened

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#5630] opened 2016-04-03 21:24 UTC
##### Detailed steps causing the problem:
- Enable extremcaching.com
- Search nearby caches
- From the result list open a EC cache
- Go back to the search results
##### Actual behavior after performing these steps:

The cache which was just opened and closed is shown as saved (icon overlay) in the search result list. Entering the details again it is shown to be saved to the default list, but it can not be found there and it should not be saved at all.
##### Expected behavior after performing these steps:

Don't show it as saved.
##### Version of c:geo used:

2016.04.03-NB
##### Is the problem reproducible for you?

Yes
##### Other comments and remarks:

Does not happen for GC or OC as far as I could test but I am not sure.

**Comment by Bananeweizen** [comment] 2016-04-04 16:37
just as a note: the above commit referring to this issue was a typo of mine in the issue number, so please ignore it.

**Comment by Bananeweizen** [comment] 2016-04-04 18:46
Okay, I have a rough idea, but I don't know what the intended design is. Geocache.isOffline() is now implemented as !lists.isEmpty(). The caches from EC are put on the temporary list during parsing, therefore their lists is not empty. That is the cause for the above symptome.

However, now I'm not sure, if the caches should never have the temporary list in their persisted lists (that is, we need to filter away the temporary list in Geocache.setLists()) OR if it is totally okay to store the temporary list there and we need to ignore it on the fly in the isOffline method (lists.isNotEmpty and (lists.size() >1 or lists.get(0) != TEMPORARY_LIST).

**Comment by pstorch** [comment] 2016-04-04 19:25
I stumbled upon this `Geocache.isOffline()` when implementing the multi lists feature.
The old implementation was `return listId >= StoredList.STANDARD_LIST_ID;`

Filter on `setLists()` would not be easily possible. Someone can just call `getLists().add(...)`. So I guess filtering in `isOffline()` is better.

**Comment by Bananeweizen** [comment] 2016-04-04 19:32
We can always enforce developers to use the setSomeCollection() methods by returning Collections.unmodifiableList/Set/Map/... from the respective getSomeCollection() method. Would you still recommend filtering in isOffline then?

**Comment by pstorch** [comment] 2016-04-04 19:44
Would be cleaner to filter when adding a ListId to the Set, but it would be slightly more work. Need some helper / delegation methods to implement add(), addAll(), remove() and clear() on the lists Set.

**Comment by Bananeweizen** [comment] 2016-04-05 16:29
I have only tested this with single caches from the search by geocode. For me, nearby search didn't work. Please retest once this is merged.

**Comment by Bananeweizen** [comment] 2016-04-05 16:29
fixed with 0b83bb0d2708ff5d66bd0c96930dbd8526aa89b4

**Comment by Lineflyer** [comment] 2016-11-29 20:29
This seems to appear again with current master... so reopening!

Detailed test will follow if no one has a clue on this.

**Comment by Bananeweizen** [comment] 2016-12-01 18:16
I could not completely reproduce your results. However, the temporary opened cache showed the standard list in its details and that was surely wrong. This has been fixed and I assume that fixes your symptomes too.

**Closed** 2016-12-01 18:15 UTC
Labels: Bug, EC
