### ISSUE TITLE
MapMarkerUtils: exception " Invalid drawable added to LayerDrawable! Drawable already belongs to another owner but does not expose a constant state"

### ISSUE THREAD

**Issue by eddiemuc** [cgeo/cgeo#15169] opened 2024-01-05 11:22 UTC
I found the following exception in a log file (which I analyzed for a different issue). It indicates some non-correct behaviour when dealing with Map Markers. I don't know the concrete effects of this to the user.

```
01-05 11:30:20.671 15881 15881 W LayerDrawable: Invalid drawable added to LayerDrawable! Drawable already belongs to another owner but does not expose a constant state.
01-05 11:30:20.671 15881 15881 W LayerDrawable: java.lang.RuntimeException
01-05 11:30:20.671 15881 15881 W LayerDrawable: 	at android.graphics.drawable.LayerDrawable$ChildDrawable.<init>(LayerDrawable.java:1857)
01-05 11:30:20.671 15881 15881 W LayerDrawable: 	at android.graphics.drawable.LayerDrawable$LayerState.<init>(LayerDrawable.java:1977)
01-05 11:30:20.671 15881 15881 W LayerDrawable: 	at android.graphics.drawable.LayerDrawable.createConstantState(LayerDrawable.java:173)
01-05 11:30:20.671 15881 15881 W LayerDrawable: 	at android.graphics.drawable.LayerDrawable.mutate(LayerDrawable.java:1782)
01-05 11:30:20.671 15881 15881 W LayerDrawable: 	at cgeo.geocaching.utils.MapMarkerUtils.createWaypointMarker(MapMarkerUtils.java:333)
01-05 11:30:20.671 15881 15881 W LayerDrawable: 	at cgeo.geocaching.utils.MapMarkerUtils.getWaypointMarker(MapMarkerUtils.java:263)
01-05 11:30:20.671 15881 15881 W LayerDrawable: 	at cgeo.geocaching.CacheDetailActivity$WaypointsViewCreator.fillViewHolder(CacheDetailActivity.java:2253)
01-05 11:30:20.671 15881 15881 W LayerDrawable: 	at cgeo.geocaching.CacheDetailActivity$WaypointsViewCreator$1.getView(CacheDetailActivity.java:2132)
01-05 11:30:20.671 15881 15881 W LayerDrawable: 	at android.widget.HeaderViewListAdapter.getView(HeaderViewListAdapter.java:224)
01-05 11:30:20.671 15881 15881 W LayerDrawable: 	at android.widget.AbsListView.obtainView(AbsListView.java:2662)
01-05 11:30:20.671 15881 15881 W LayerDrawable: 	at android.widget.HwAbsListView.obtainView(HwAbsListView.java:1309)
01-05 11:30:20.671 15881 15881 W LayerDrawable: 	at android.widget.ListView.makeAndAddView(ListView.java:2174)
01-05 11:30:20.671 15881 15881 W LayerDrawable: 	at android.widget.ListView.fillDown(ListView.java:874)
01-05 11:30:20.671 15881 15881 W LayerDrawable: 	at android.widget.ListView.fillFromTop(ListView.java:943)
01-05 11:30:20.671 15881 15881 W LayerDrawable: 	at android.widget.ListView.layoutChildren(ListView.java:1926)
01-05 11:30:20.671 15881 15881 W LayerDrawable: 	at android.widget.AbsListView.onLayout(AbsListView.java:2448)
01-05 11:30:20.671 15881 15881 W LayerDrawable: 	at android.widget.HwAbsListView.onLayout(HwAbsListView.java:466)
01-05 11:30:20.671 15881 15881 W LayerDrawable: 	at android.view.View.layout(View.java:22496)
01-05 11:30:20.671 15881 15881 W LayerDrawable: 	at android.view.ViewGroup.layout(ViewGroup.java:6528)
01-05 11:30:20.671 15881 15881 W LayerDrawable: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:334)
01-05 11:30:20.671 15881 15881 W LayerDrawable: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
01-05 11:30:20.671 15881 15881 W LayerDrawable: 	at android.view.View.layout(View.java:22496)
01-05 11:30:20.671 15881 15881 W LayerDrawable: 	at android.view.ViewGroup.layout(ViewGroup.java:6528)
01-05 11:30:20.671 15881 15881 W LayerDrawable: 	at androidx.recyclerview.widget.RecyclerView$LayoutManager.layoutDecoratedWithMargins(RecyclerView.java:10407)
01-05 11:30:20.671 15881 15881 W LayerDrawable: 	at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1720)
01-05 11:30:20.671 15881 15881 W LayerDrawable: 	at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1622)
01-05 11:30:20.671 15881 15881 W LayerDrawable: 	at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:697)
01-05 11:30:20.671 15881 15881 W LayerDrawable: 	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4645)
01-05 11:30:20.671 15881 15881 W LayerDrawable: 	at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:4348)
01-05 11:30:20.671 15881 15881 W LayerDrawable: 	at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4919)
01-05 11:30:20.671 15881 15881 W LayerDrawable: 	at android.view.View.layout(View.java:22496)
01-05 11:30:20.671 15881 15881 W LayerDrawable: 	at android.view.ViewGroup.layout(ViewGroup.java:6528)
01-05 11:30:20.671 15881 15881 W LayerDrawable: 	at androidx.viewpager2.widget.ViewPager2.onLayout(ViewPager2.java:535)
01-05 11:30:20.671 15881 15881 W LayerDrawable: 	at android.view.View.layout(View.java:22496)
01-05 11:30:20.671 15881 15881 W LayerDrawable: 	at android.view.ViewGroup.layout(ViewGroup.java:6528)
01-05 11:30:20.671 15881 15881 W LayerDrawable: 	at androidx.swiperefreshlayout.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:625)
01-05 11:30:20.671 15881 15881 W LayerDrawable: 	at android.view.View.layout(View.java:22496)
01-05 11:30:20.671 15881 15881 W LayerDrawable: 	at android.view.ViewGroup.layout(ViewGroup.java:6528)
01-05 11:30:20.671 15881 15881 W LayerDrawable: 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1857)
01-05 11:30:20.671 15881 15881 W LayerDrawable: 	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1701)
01-05 11:30:20.671 15881 15881 W LayerDrawable: 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1610)
01-05 11:30:20.671 15881 15881 W LayerDrawable: 	at android.view.View.layout(View.java:22496)
01-05 11:30:20.671 15881 15881 W LayerDrawable: 	at android.view.ViewGroup.layout(ViewGroup.java:6528)
01-05 11:30:20.671 15881 15881 W LayerDrawable: 	at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1103)
01-05 11:30:20.671 15881 15881 W LayerDrawable: 	at android.view.View.layout(View.java:22496)
01-05 11:30:20.671 15881 15881 W LayerDrawable: 	at android.view.ViewGroup.layout(ViewGroup.java:6528)
01-05 11:30:20.671 15881 15881 W LayerDrawable: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:334)
01-05 11:30:20.671 15881 15881 W LayerDrawable: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
01-05 11:30:20.671 15881 15881 W LayerDrawable: 	at android.view.View.layout(View.java:22496)
01-05 11:30:20.671 15881 15881 W LayerDrawable: 	at android.view.ViewGroup.layout(ViewGroup.java:6528)
01-05 11:30:20.671 15881 15881 W LayerDrawable: 	at androidx.appcompat.widget.ActionBarOverlayLayout.onLayout(ActionBarOverlayLayout.java:536)
01-05 11:30:20.671 15881 15881 W LayerDrawable: 	at android.view.View.layout(View.java:22496)
01-05 11:30:20.671 15881 15881 W LayerDrawable: 	at android.view.ViewGroup.layout(ViewGroup.java:6528)
01-05 11:30:20.671 15881 15881 W LayerDrawable: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:334)
01-05 11:30:20.671 15881 15881 W LayerDrawable: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
01-05 11:30:20.671 15881 15881 W LayerDrawable: 	at android.view.View.layout(View.java:22496)
01-05 11:30:20.671 15881 15881 W LayerDrawable: 	at android.view.ViewGroup.layout(ViewGroup.java:6528)
01-05 11:30:20.671 15881 15881 W LayerDrawable: 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1857)
01-05 11:30:20.671 15881 15881 W LayerDrawable: 	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1701)
01-05 11:30:20.671 15881 15881 W LayerDrawable: 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1610)
01-05 11:30:20.671 15881 15881 W LayerDrawable: 	at android.view.View.layout(View.java:22496)
01-05 11:30:20.671 15881 15881 W LayerDrawable: 	at android.view.ViewGroup.layout(ViewGroup.java:6528)
01-05 11:30:20.671 15881 15881 W LayerDrawable: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:334)
01-05 11:30:20.671 15881 15881 W LayerDrawable: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
01-05 11:30:20.671 15881 15881 W LayerDrawable: 	at com.android.internal.policy.DecorView.onLayout(DecorView.java:1146)
01-05 11:30:20.671 15881 15881 W LayerDrawable: 	at android.view.View.layout(View.java:22496)
01-05 11:30:20.671 15881 15881 W LayerDrawable: 	at android.view.ViewGroup.layout(ViewGroup.java:6528)
01-05 11:30:20.671 15881 15881 W LayerDrawable: 	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:3743)
01-05 11:30:20.671 15881 15881 W LayerDrawable: 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3207)
01-05 11:30:20.671 15881 15881 W LayerDrawable: 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2166)
01-05 11:30:20.671 15881 15881 W LayerDrawable: 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8887)
01-05 11:30:20.671 15881 15881 W LayerDrawable: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1280)
01-05 11:30:20.671 15881 15881 W LayerDrawable: 	at android.view.Choreographer.doCallbacks(Choreographer.java:1019)
01-05 11:30:20.671 15881 15881 W LayerDrawable: 	at android.view.Choreographer.doFrame(Choreographer.java:911)
01-05 11:30:20.671 15881 15881 W LayerDrawable: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1248)
01-05 11:30:20.671 15881 15881 W LayerDrawable: 	at android.os.Handler.handleCallback(Handler.java:900)
01-05 11:30:20.671 15881 15881 W LayerDrawable: 	at android.os.Handler.dispatchMessage(Handler.java:103)
01-05 11:30:20.671 15881 15881 W LayerDrawable: 	at android.os.Looper.loop(Looper.java:219)
01-05 11:30:20.671 15881 15881 W LayerDrawable: 	at android.app.ActivityThread.main(ActivityThread.java:8668)
01-05 11:30:20.671 15881 15881 W LayerDrawable: 	at java.lang.reflect.Method.invoke(Native Method)
01-05 11:30:20.671 15881 15881 W LayerDrawable: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
01-05 11:30:20.671 15881 15881 W LayerDrawable: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109)
01-05 11:30:20.672 15881 15881 W LayerDrawable: Invalid drawable added to LayerDrawable! Drawable already belongs to another owner but does not expose a constant state.
01-05 11:30:20.672 15881 15881 W LayerDrawable: java.lang.RuntimeException
01-05 11:30:20.672 15881 15881 W LayerDrawable: 	at android.graphics.drawable.LayerDrawable$ChildDrawable.<init>(LayerDrawable.java:1857)
01-05 11:30:20.672 15881 15881 W LayerDrawable: 	at android.graphics.drawable.LayerDrawable$LayerState.<init>(LayerDrawable.java:1977)
01-05 11:30:20.672 15881 15881 W LayerDrawable: 	at android.graphics.drawable.LayerDrawable.createConstantState(LayerDrawable.java:173)
01-05 11:30:20.672 15881 15881 W LayerDrawable: 	at android.graphics.drawable.LayerDrawable.mutate(LayerDrawable.java:1782)
01-05 11:30:20.672 15881 15881 W LayerDrawable: 	at cgeo.geocaching.utils.MapMarkerUtils.createWaypointMarker(MapMarkerUtils.java:333)
01-05 11:30:20.672 15881 15881 W LayerDrawable: 	at cgeo.geocaching.utils.MapMarkerUtils.getWaypointMarker(MapMarkerUtils.java:263)
01-05 11:30:20.672 15881 15881 W LayerDrawable: 	at cgeo.geocaching.CacheDetailActivity$WaypointsViewCreator.fillViewHolder(CacheDetailActivity.java:2253)
01-05 11:30:20.672 15881 15881 W LayerDrawable: 	at cgeo.geocaching.CacheDetailActivity$WaypointsViewCreator$1.getView(CacheDetailActivity.java:2132)
01-05 11:30:20.672 15881 15881 W LayerDrawable: 	at android.widget.HeaderViewListAdapter.getView(HeaderViewListAdapter.java:224)
01-05 11:30:20.672 15881 15881 W LayerDrawable: 	at android.widget.AbsListView.obtainView(AbsListView.java:2662)
01-05 11:30:20.672 15881 15881 W LayerDrawable: 	at android.widget.HwAbsListView.obtainView(HwAbsListView.java:1309)
01-05 11:30:20.672 15881 15881 W LayerDrawable: 	at android.widget.ListView.makeAndAddView(ListView.java:2174)
01-05 11:30:20.672 15881 15881 W LayerDrawable: 	at android.widget.ListView.fillDown(ListView.java:874)
01-05 11:30:20.672 15881 15881 W LayerDrawable: 	at android.widget.ListView.fillFromTop(ListView.java:943)
01-05 11:30:20.672 15881 15881 W LayerDrawable: 	at android.widget.ListView.layoutChildren(ListView.java:1926)
01-05 11:30:20.672 15881 15881 W LayerDrawable: 	at android.widget.AbsListView.onLayout(AbsListView.java:2448)
01-05 11:30:20.672 15881 15881 W LayerDrawable: 	at android.widget.HwAbsListView.onLayout(HwAbsListView.java:466)
01-05 11:30:20.672 15881 15881 W LayerDrawable: 	at android.view.View.layout(View.java:22496)
01-05 11:30:20.672 15881 15881 W LayerDrawable: 	at android.view.ViewGroup.layout(ViewGroup.java:6528)
01-05 11:30:20.672 15881 15881 W LayerDrawable: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:334)
01-05 11:30:20.672 15881 15881 W LayerDrawable: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
01-05 11:30:20.672 15881 15881 W LayerDrawable: 	at android.view.View.layout(View.java:22496)
01-05 11:30:20.672 15881 15881 W LayerDrawable: 	at android.view.ViewGroup.layout(ViewGroup.java:6528)
01-05 11:30:20.672 15881 15881 W LayerDrawable: 	at androidx.recyclerview.widget.RecyclerView$LayoutManager.layoutDecoratedWithMargins(RecyclerView.java:10407)
01-05 11:30:20.672 15881 15881 W LayerDrawable: 	at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1720)
01-05 11:30:20.672 15881 15881 W LayerDrawable: 	at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1622)
01-05 11:30:20.672 15881 15881 W LayerDrawable: 	at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:697)
01-05 11:30:20.672 15881 15881 W LayerDrawable: 	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4645)
01-05 11:30:20.672 15881 15881 W LayerDrawable: 	at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:4348)
01-05 11:30:20.672 15881 15881 W LayerDrawable: 	at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4919)
01-05 11:30:20.672 15881 15881 W LayerDrawable: 	at android.view.View.layout(View.java:22496)
01-05 11:30:20.672 15881 15881 W LayerDrawable: 	at android.view.ViewGroup.layout(ViewGroup.java:6528)
01-05 11:30:20.672 15881 15881 W LayerDrawable: 	at androidx.viewpager2.widget.ViewPager2.onLayout(ViewPager2.java:535)
01-05 11:30:20.672 15881 15881 W LayerDrawable: 	at android.view.View.layout(View.java:22496)
01-05 11:30:20.672 15881 15881 W LayerDrawable: 	at android.view.ViewGroup.layout(ViewGroup.java:6528)
01-05 11:30:20.672 15881 15881 W LayerDrawable: 	at androidx.swiperefreshlayout.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:625)
01-05 11:30:20.672 15881 15881 W LayerDrawable: 	at android.view.View.layout(View.java:22496)
01-05 11:30:20.672 15881 15881 W LayerDrawable: 	at android.view.ViewGroup.layout(ViewGroup.java:6528)
01-05 11:30:20.672 15881 15881 W LayerDrawable: 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1857)
01-05 11:30:20.672 15881 15881 W LayerDrawable: 	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1701)
01-05 11:30:20.672 15881 15881 W LayerDrawable: 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1610)
01-05 11:30:20.672 15881 15881 W LayerDrawable: 	at android.view.View.layout(View.java:22496)
01-05 11:30:20.672 15881 15881 W LayerDrawable: 	at android.view.ViewGroup.layout(ViewGroup.java:6528)
01-05 11:30:20.672 15881 15881 W LayerDrawable: 	at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1103)
01-05 11:30:20.672 15881 15881 W LayerDrawable: 	at android.view.View.layout(View.java:22496)
01-05 11:30:20.672 15881 15881 W LayerDrawable: 	at android.view.ViewGroup.layout(ViewGroup.java:6528)
01-05 11:30:20.672 15881 15881 W LayerDrawable: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:334)
01-05 11:30:20.672 15881 15881 W LayerDrawable: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
01-05 11:30:20.672 15881 15881 W LayerDrawable: 	at android.view.View.layout(View.java:22496)
01-05 11:30:20.672 15881 15881 W LayerDrawable: 	at android.view.ViewGroup.layout(ViewGroup.java:6528)
01-05 11:30:20.672 15881 15881 W LayerDrawable: 	at androidx.appcompat.widget.ActionBarOverlayLayout.onLayout(ActionBarOverlayLayout.java:536)
01-05 11:30:20.672 15881 15881 W LayerDrawable: 	at android.view.View.layout(View.java:22496)
01-05 11:30:20.672 15881 15881 W LayerDrawable: 	at android.view.ViewGroup.layout(ViewGroup.java:6528)
01-05 11:30:20.672 15881 15881 W LayerDrawable: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:334)
01-05 11:30:20.672 15881 15881 W LayerDrawable: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
01-05 11:30:20.672 15881 15881 W LayerDrawable: 	at android.view.View.layout(View.java:22496)
01-05 11:30:20.672 15881 15881 W LayerDrawable: 	at android.view.ViewGroup.layout(ViewGroup.java:6528)
01-05 11:30:20.672 15881 15881 W LayerDrawable: 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1857)
01-05 11:30:20.672 15881 15881 W LayerDrawable: 	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1701)
01-05 11:30:20.672 15881 15881 W LayerDrawable: 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1610)
01-05 11:30:20.672 15881 15881 W LayerDrawable: 	at android.view.View.layout(View.java:22496)
01-05 11:30:20.672 15881 15881 W LayerDrawable: 	at android.view.ViewGroup.layout(ViewGroup.java:6528)
01-05 11:30:20.672 15881 15881 W LayerDrawable: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:334)
01-05 11:30:20.672 15881 15881 W LayerDrawable: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
01-05 11:30:20.672 15881 15881 W LayerDrawable: 	at com.android.internal.policy.DecorView.onLayout(DecorView.java:1146)
01-05 11:30:20.672 15881 15881 W LayerDrawable: 	at android.view.View.layout(View.java:22496)
01-05 11:30:20.672 15881 15881 W LayerDrawable: 	at android.view.ViewGroup.layout(ViewGroup.java:6528)
01-05 11:30:20.672 15881 15881 W LayerDrawable: 	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:3743)
01-05 11:30:20.672 15881 15881 W LayerDrawable: 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3207)
01-05 11:30:20.672 15881 15881 W LayerDrawable: 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2166)
01-05 11:30:20.672 15881 15881 W LayerDrawable: 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8887)
01-05 11:30:20.672 15881 15881 W LayerDrawable: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1280)
01-05 11:30:20.672 15881 15881 W LayerDrawable: 	at android.view.Choreographer.doCallbacks(Choreographer.java:1019)
01-05 11:30:20.672 15881 15881 W LayerDrawable: 	at android.view.Choreographer.doFrame(Choreographer.java:911)
01-05 11:30:20.672 15881 15881 W LayerDrawable: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1248)
01-05 11:30:20.672 15881 15881 W LayerDrawable: 	at android.os.Handler.handleCallback(Handler.java:900)
01-05 11:30:20.672 15881 15881 W LayerDrawable: 	at android.os.Handler.dispatchMessage(Handler.java:103)
01-05 11:30:20.672 15881 15881 W LayerDrawable: 	at android.os.Looper.loop(Looper.java:219)
01-05 11:30:20.672 15881 15881 W LayerDrawable: 	at android.app.ActivityThread.main(ActivityThread.java:8668)
01-05 11:30:20.672 15881 15881 W LayerDrawable: 	at java.lang.reflect.Method.invoke(Native Method)
01-05 11:30:20.672 15881 15881 W LayerDrawable: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
01-05 11:30:20.672 15881 15881 W LayerDrawable: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109)

```

**Comment by moving-bits** [comment] 2024-01-05 11:34
Duplicate of #15024 (part 1), but as that one has two different issues (the other one being fixed), I'll close #15024.

**Closed** 2024-01-10 05:57 UTC
Labels: Bug
