### ISSUE TITLE
"file <imageurl> could not be read" for each image

### ISSUE THREAD

**Issue by ztNFny** [cgeo/cgeo#14000] opened 2023-02-19 23:10 UTC
With today's nightly loading any listing with image i get fit each image a toast "file imageurl could not be read"
Happens for both OC and GC.
the images are displayed though.

**Comment by ztNFny** [comment] 2023-02-20 21:26
String is contentstorage_err_read_failed

**Comment by ztNFny** [comment] 2023-02-20 21:27
possibly related to a8a829503a665f3b323ce82fc526673afa361cc8

**Comment by ztNFny** [comment] 2023-02-20 21:50
The exception is this, happens for ANY listing or log photo afaict:

`02-20 22:48:49.649 25116 25116 W cgeo    : [main] ContentStorage: File 'https://s3.amazonaws.com/gs-geo-images/XXXXXXXXXXXXXXXX.jpg' could not be read
02-20 22:48:49.649 25116 25116 W cgeo    : java.io.FileNotFoundException: No content provider: https://s3.amazonaws.com/gs-geo-images/b47a297a-0c99-4753-af8f-de3327b5fe45.jpg
02-20 22:48:49.649 25116 25116 W cgeo    :      at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:2031)
02-20 22:48:49.649 25116 25116 W cgeo    :      at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1860)
02-20 22:48:49.649 25116 25116 W cgeo    :      at android.content.ContentResolver.openInputStream(ContentResolver.java:1536)
02-20 22:48:49.649 25116 25116 W cgeo    :      at cgeo.geocaching.storage.ContentStorage.openForRead(ContentStorage.java:427)
02-20 22:48:49.649 25116 25116 W cgeo    :      at cgeo.geocaching.storage.ContentStorage.openForRead(ContentStorage.java:413)
02-20 22:48:49.649 25116 25116 W cgeo    :      at cgeo.geocaching.utils.ImageUtils.openImageStream(ImageUtils.java:661)
02-20 22:48:49.649 25116 25116 W cgeo    :      at cgeo.geocaching.utils.ImageUtils.getImageOrientation(ImageUtils.java:355)
02-20 22:48:49.649 25116 25116 W cgeo    :      at cgeo.geocaching.utils.ImageUtils.getImageRotationDegrees(ImageUtils.java:344)
02-20 22:48:49.649 25116 25116 W cgeo    :      at cgeo.geocaching.ui.ImageGalleryView.lambda$fillView$0(ImageGalleryView.java:220)
02-20 22:48:49.649 25116 25116 W cgeo    :      at cgeo.geocaching.ui.ImageGalleryView.$r8$lambda$YMEWtwD2VSI0nmKC1s7xESNAucQ(ImageGalleryView.java:0)
02-20 22:48:49.649 25116 25116 W cgeo    :      at cgeo.geocaching.ui.ImageGalleryView$$ExternalSyntheticLambda10.call(R8$$SyntheticClass:0)
02-20 22:48:49.649 25116 25116 W cgeo    :      at cgeo.geocaching.utils.ImageDataMemoryCache.lambda$loadImage$0(ImageDataMemoryCache.java:75)
02-20 22:48:49.649 25116 25116 W cgeo    :      at cgeo.geocaching.utils.ImageDataMemoryCache.$r8$lambda$Owv2eXGo9H7aU9Mu5szADWSEux4(ImageDataMemoryCache.java:0)
02-20 22:48:49.649 25116 25116 W cgeo    :      at cgeo.geocaching.utils.ImageDataMemoryCache$$ExternalSyntheticLambda0.accept(R8$$SyntheticClass:0)
02-20 22:48:49.649 25116 25116 W cgeo    :      at io.reactivex.rxjava3.internal.observers.LambdaObserver.onNext(LambdaObserver.java:63)
02-20 22:48:49.649 25116 25116 W cgeo    :      at io.reactivex.rxjava3.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal(ObservableObserveOn.java:202)
02-20 22:48:49.649 25116 25116 W cgeo    :      at io.reactivex.rxjava3.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:256)
02-20 22:48:49.649 25116 25116 W cgeo    :      at io.reactivex.rxjava3.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:123)
02-20 22:48:49.649 25116 25116 W cgeo    :      at android.os.Handler.handleCallback(Handler.java:938)
02-20 22:48:49.649 25116 25116 W cgeo    :      at android.os.Handler.dispatchMessage(Handler.java:99)
02-20 22:48:49.649 25116 25116 W cgeo    :      at android.os.Looper.loopOnce(Looper.java:233)
02-20 22:48:49.649 25116 25116 W cgeo    :      at android.os.Looper.loop(Looper.java:344)
02-20 22:48:49.649 25116 25116 W cgeo    :      at android.app.ActivityThread.main(ActivityThread.java:8212)
02-20 22:48:49.649 25116 25116 W cgeo    :      at java.lang.reflect.Method.invoke(Native Method)
02-20 22:48:49.649 25116 25116 W cgeo    :      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
02-20 22:48:49.649 25116 25116 W cgeo    :      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)
`

**Comment by eddiemuc** [comment] 2023-02-21 07:10
Hi @ztNFny thanks a lot for diving into this issue caused by my commit! With your work it was very easy for me to find the root cause of it.

I provided an alternative fix PR #14009 which tries to solve the problem at its root. Also it is targeted against release (the error manifests there too). I would kindly ask you to consider using this PR instead of yours.

**Comment by Lineflyer** [comment] 2023-02-21 21:59
> Also it is targeted against release (the error manifests there too)

But the problem does not show up on `release` as the https://github.com/cgeo/cgeo/commit/aa85c0551cb190a8675d370982a1c6a556e348ab commit only came on afterwards. But the root cause is on `release`. Correct?
I am asking just to determine whether we need a urgent bugfix release, which I doubt as no user reported that obvious problem yet.

**Comment by eddiemuc** [comment] 2023-02-22 05:34
> > Also it is targeted against release (the error manifests there too)
> 
> But the problem does not show up on `release` as the https://github.com/cgeo/cgeo/commit/aa85c0551cb190a8675d370982a1c6a556e348ab commit only came on afterwards. But the root cause is on `release`. Correct?
> I am asking just to determine whether we need a urgent bugfix release, which I doubt as no user reported that obvious problem yet.
> 

I introduced the bug on release branch but after we released last beta. So for now beta users are not affected, but if we would release a new beta right now (without merging my PR) then the new beta would contain the problem.

**Comment by eddiemuc** [comment] 2023-02-22 05:44
... and my errorness commit on release then was merged to master through our regular processes, and this is where it was then found in the nightlies e.g. by @ztNFny 

So imho this needs to be fixed/merged urgently to release (to prevent a problem in next beta) and then merged to master from there.

**Closed** 2023-02-22 10:01 UTC
Labels: Bug, Regression
