### ISSUE TITLE
Quick menu access (entering + leaving)

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#9617] opened 2020-12-28 22:38 UTC
Feedback to quick settings keeps coming in.

Some users like it, quite some suggested to place it in the normal menu flow (top bar) instead somewhere else.
Also quite some users (with smaller screens) keep having problems to leave the menu.

One example:

A new setup menu would perhaps be ok, but WHY down there. It doesn't fit there. There is still plenty of room at the top next to the other menu icons.
![grafik](https://user-images.githubusercontent.com/949669/103246968-8366a980-4965-11eb-952d-c25bfb6a220e.png)

My phone doesn't have a back-button since I chose to configure it so that the full screen real estate is useable for applications. Over all the way to leave the different menus in c:geo is a bit annoying and inconsistent. Several menus have a left-arrow at the top, many don't. Clicking outside of the menu does not do anything!

**Comment by moving-bits** [comment] 2020-12-28 22:46
I do understand the problems, but do not have an easy solution for it:

> A new setup menu would perhaps be ok, but WHY down there. It doesn't fit there. There is still plenty of room at the top next to the other menu icons.

It looks like this, indeed, but actually Android does not place any additional buttons there automatically. We have configured more buttons as "show on ActionBar ifRoom", but Android will do so only in landscape mode.
So only alternative here would be to force those icons (follow me, map selection, quick map settings), which will reduce the space available for cache/map title even more.

> My phone doesn't have a back-button

Isn't that one being displayed on up-swipe? That would be regular Android-behavior.

> Clicking outside of the menu does not do anything!

There seems to be some "reserved area" around the popup which is not regarded as clicking on the map. If the popup is filling up most of the screen, this "reserved area" may cover the whole rest of the map.

Maybe we actually do have to place a "Close" button somewhere on the dialog.

**Comment by Lineflyer** [comment] 2020-12-28 22:58
> It looks like this, indeed, but actually Android does not place any additional buttons there automatically. We have configured more buttons as "show on ActionBar ifRoom", but Android will do so only in landscape mode.
So only alternative here would be to force those icons (follow me, map selection, quick map settings), which will reduce the space available for cache/map title even more.

I know this meachanism...however for the live map the title consumes no so much space (of course depending on device).
The user is somehow right, that it is inconsistent to the normal menu flow....that also made me post it here to discuss it.
What if we really use our normal overflow menu in second place (after follow me) and set follow me, quick settings and map selection to "Always show"? Maybe this would really be the better choice (and no more need to explain the change as user might easily see it there)..... 

> > My phone doesn't have a back-button

> Isn't that one being displayed on up-swipe? That would be regular Android-behavior.

I also think, that a back button is still an Android must have,..maybe just the user does not know how to trigger it.
But indeed there is no other place in c:geo I can remember where we enforce to use it....maybe only if the screen resolution is so low, that you need to close the map cache popup with back button.

> Maybe we actually do have to place a "Close" button somewhere on the dialog.

Or as a custom back arrow on top left?

**Comment by MagpieFourtyTwo** [comment] 2020-12-28 23:26
> What if we really use our normal overflow menu 

I would consider this a really bad solution:
1. the room in the head line is in fact very limited, esp. in single cache scenario.
2. main reason for the Quick Settings popup was to create a possibility to change the routing style as fast as possible;
    with the Quick Settings button the the headline, you first have to go to the top, then down to the routing style ...
    advantage against the old fashioned routing menu will be lost
3. when holding the phone with one hand, it's pretty hard to reach the headline ... esp. with modern phones;
    the Quick Settings button at the bottom can be used easily with the thumb - which makes it a really quick action

> My phone doesn't have a back-button

I can configure my Android 10 to use 
1. 3 button line (back, home, recent apps)
2. gestures (back: swipe from left or right edge to center; home: lower edge to center; recent: lower edge and stop at center)
3. Navi dot: (back: tap dot; home: tap and hold: recent: tap and move dot to left or right)

but there is absolutely no way, to do it without any back function ... and I doubt that it would make any sense at all w/o back button.

> Ok button to close

To be at least kind of consistent it probably has to go to the left of the title (like e. g. left of ``Live map``). But this would again spoil the "Quick-ness" and the usability with one hand (thumb navigation), thus I would place it rightmost of the routing styles.
But I would nevertheless keep the possibility to just tap outside of the popup (with changes being saved, of course).

**Comment by moving-bits** [comment] 2020-12-29 08:56
> I also think, that a back button is still an Android must have,..maybe just the user does not know how to trigger it. But indeed there is no other place in c:geo I can remember where we enforce to use it....

Just for the record: We have other places, at least
- map cache / waypoint popup (if you don't press the "more details" button, which implicitly closes the popup)
- settings (second level screens)
- some action popups (eg. export notifications) don't have a "cancel" button

(and maybe more)

**Comment by moving-bits** [comment] 2020-12-29 08:58
A different approach to this issue would be to reduce the content in the map settings popup, as discussed in #9540.

**Comment by moving-bits** [comment] 2020-12-29 21:20
I'm currently pursuing three ways to get an "back" button being displayed in the dialog title.

Dialogs do not provide this feature natively, so I started with the other options first, trying to use an activity instead of a dialog.

It's no problem for a full-screen Activity:

![image](https://user-images.githubusercontent.com/3754370/103314349-22051000-4a23-11eb-9cba-4c02a1c67344.png)

But for some reason it does not work for dialog-themed activities:

![image](https://user-images.githubusercontent.com/3754370/103314531-b2435500-4a23-11eb-9563-17bc8af2ee46.png)

Next I will try to stay with a dialog and somehow "inject" the back button...

**Comment by Lineflyer** [comment] 2020-12-29 21:44
> Next I will try to stay with a dialog and somehow "inject" the back button...

Or really convert it into activity and go for the top bar menu?

**Comment by moving-bits** [comment] 2020-12-29 21:52
> > Next I will try to stay with a dialog and somehow "inject" the back button...
> 
> Or really convert it into activity and go for the top bar menu?

If I use an activity it could look like the first screenshot. I would stay with the back button then.

But (at least on larger screens) not using a full-screen activity has the advantage of the map still being visible in the background, giving the illusion / impression of a settings popup (which it actually is currently).

**Comment by Lineflyer** [comment] 2020-12-29 21:56
> giving the illusion / impression of a settings popup (which it actually is currently).

On the pro side for an activity:
Room for future use, still all in one place.

**Comment by MagpieFourtyTwo** [comment] 2020-12-29 22:36
... but still not as "Quick" as a dialog, which can be confirmed with just a click in the map ...

**Comment by MagpieFourtyTwo** [comment] 2020-12-29 22:37
Wouldn't it be easier, to explain Android's back button to the user in question?
He will need it for other apps, anyway ... ;)

**Comment by moving-bits** [comment] 2020-12-29 23:11
Finally, found a way (using a custom layout):

![image](https://user-images.githubusercontent.com/3754370/103319823-6bf5f200-4a33-11eb-8d5e-b386e93d3d99.png)

Tapping on the arrow in the dialog title will close the dialog, applying all changes.
The other ways of closing this dialog (tapping on the map, tapping the back button) still work.

**Comment by MagpieFourtyTwo** [comment] 2020-12-29 23:30
Perfect! Great work - as usual.  ;)  Thx a lot!
Just one cosmetic point: Is the arrow a bitmap/icon?
If so, I would make the horizontal line a bit shorter and it's lines a bit thinner in general,
to make it look like the others in e. g. Live map or cache lists.

**Comment by moving-bits** [comment] 2020-12-29 23:39
Currently it's a bitmap. I would prefer to use the original vector resource Android itself is using for the activities, but I haven't found the resource's name yet :-( Still searching, though...

**Comment by MagpieFourtyTwo** [comment] 2020-12-29 23:45
Already tried ``?attr/homeAsUpIndicator``?

**Comment by moving-bits** [comment] 2020-12-30 09:45
> Already tried `?attr/homeAsUpIndicator`?

Good hint, tried it today, but it's always set to 0, both directly in layout definition and at runtime.

**Closed** 2020-12-30 17:47 UTC
Labels: Google Play or Beta feedback
