### ISSUE TITLE
Own position not shown on devices without compass

### ISSUE THREAD

**Issue by TeamJonas4** [cgeo/cgeo#4548] opened 2014-12-19 23:42 UTC
App still worked on Saturday after last update, but on Monday the blue arrow of the own Position is missing and neither the map nor the compass adjusts to the current position.
I am not sure but I suppose it was the display rotation I activated on Monday.
Since then I have this issue.
I think These issues are already reported: #4533 and #4540

**Comment by Lineflyer** [comment] 2015-01-05 14:47
@TeamJonas4 @dunkiper @HoBeHagen 
Can you please install and retest with http://www.cgeo.org/cgeo-RC.apk ?

Please leave this version installed if possible as you will be automatically alerted about further updates/fixes to this release candidate (for testing again in case this version did not help).

Please kindly report back here, if the problem of "no arrow on the map" is solved with that version.

**Comment by dunkiper** [comment] 2015-01-05 15:36
Just downloaded and installed right now and it works!! Arrow and surrounding circle are again present and showing the current position. I'll test it again later outdoors with GPS signal, but it seems to be ok.

Arrow is always pointing to the top of the phone, but this absolutely normal behaviour on a device with no magnetic compass at all. So many thanks for correcting the bug!!

**Comment by TeamJonas4** [comment] 2015-01-06 18:07
As dunkiper already reported. The blue arrow and its circle are back again on the map.
In the compass view, the distance will be updated if I move.
Only the compass itself is frozen. It points to one "random" direction without any movement.
This is not as critical, but it worked before.
Maybe you can fix this, too.
So far, great job.
Thx

**Comment by Lineflyer** [comment] 2015-01-06 19:59
@TeamJonas4
Thanks for your feedback.
Its strange that the compass is not working in your case, because the Monterra should for sure have a magnetic compass.
Please doublecheck if "Active Sensors" are "GPS and Compass" in the compass menu.

I will close this issue, as the main point is confirmed to be fixed from several sources.
Nevertheless please reply here and we may reopen or open a new dedicated issue.

**Closed by Lineflyer** 2015-01-06 19:59 UTC
Labels: Bug, Regression
