### ISSUE TITLE
Map View, Quick Settings -> "Show direction"

### ISSUE THREAD

**Issue by baiti** [cgeo/cgeo#9868] opened 2021-01-26 19:24 UTC
Find a better wording for that function as "Show direction" is potentially misleading. See here: https://github.com/cgeo/cgeo/commit/b424f1b21f598887903d2877c564750a0e890701#commitcomment-46373202 and the following comments.

We have agreed to call it: 

"Show routing line"

Although it is a rather trivial change in Strings.xml I am opening an issue here such that I can reference it in the process of creating a pull request. I will use this as an excercise to learn / refresh how the process is working.

**Comment by Lineflyer** [comment] 2021-01-26 19:50
Sound good: "Show direction line" or "Show routing line".
Fully agree.

**Comment by moving-bits** [comment] 2021-01-26 19:56
Or maybe integrate it in the routing buttons?
Off - Straight - Walk - Bike - Car?

**Comment by Lineflyer** [comment] 2021-01-26 20:00
Yes, one without the other makes no sense.
But I am afraid if another icon will fit in that line. How about renaming the icon section from "Routing" to "Routing line" and set the checkbox in front of the three icons.

**Comment by moving-bits** [comment] 2021-01-26 20:06
Hm, on my mobile the four routing icons together take up less than half the screen's width, even with the popup not using the whole width there would be room for another two of those square icons.

**Comment by baiti** [comment] 2021-01-26 21:03
> Yes, one without the other makes no sense.
> But I am afraid if another icon will fit in that line. How about renaming the icon section from "Routing" to "Routing line" and set the checkbox in front of the three icons.

I think this would work nicely. There is enough space on that line for the checkbox on the left and there would be no need for any text string.

If I understand that Quick Settings correctly the bottome line called "Routing", only makes a difference if "Show direction" is enabled?

**Comment by fm-sys** [comment] 2021-01-26 21:15
Please do not add a checkbox without text label. Either a labeled checkbox or an icon button would be the way to go

**Comment by moving-bits** [comment] 2021-01-26 21:22
A labelled checkbox is what we have now, but users do not associate it with the routing functions in its current place. 
So if we want to use a labelled checkbox, we should move it to the line between "Routing" and the routing buttons, and label it accordingly.

(Still I would like to try an "off" button in front of the four other states first - seems more logical to me.)

**Comment by baiti** [comment] 2021-01-26 21:52
> Please do not add a checkbox without text label. Either a labeled checkbox or an icon button would be the way to go

I wouldn't make **any** change without seeking prior consent, as I am not a UX professional

**Comment by baiti** [comment] 2021-01-26 22:01
> A labelled checkbox is what we have now, but users do not associate it with the routing functions in its current place.
> So if we want to use a labelled checkbox, we should move it to the line between "Routing" and the routing buttons, and label it accordingly.

Exactly that is what confused me too. Ideally, and I am not even sure something like this can be done with the Android UI framework, if that checkbox that is currently labeled "Show direction" is not checked, the "Routing" line and everything below, should not even be visible as it has zero effect on what is shown on the map.

**Comment by fm-sys** [comment] 2021-01-27 11:20
> Ideally, and I am not even sure something like this can be done with the Android UI framework, if that checkbox that is currently labeled "Show direction" is not checked, the "Routing" line and everything below, should not even be visible as it has zero effect on what is shown on the map.

That is definitely possible. However, routing was for a long time a hidden function that almost no one knew although it is very useful. Therefore, we show a playstore link to the brouter app if it is not installed. Hiding the buttons would mean that this  prominent advertisement is missing. A 4th button in this row would be both logical and vertically space-saving...

**Comment by baiti** [comment] 2021-01-27 21:07
@fm-sys I fully agree with what you're saying. The routing function deserves every highlithing it can possibly get. I use it all the time.

How would it look like, in your view then? Where exactly would that 4th button be?

**Comment by moving-bits** [comment] 2021-01-27 21:21
Actually it would be a fifth button. It could look like this:

![image](https://user-images.githubusercontent.com/3754370/106055433-a5cb1e80-60ed-11eb-82b1-f5fa730ba0c1.png)

Checkbox for "Show direction line" is no longer needed and removed.

The buttons beneath the "Routing" headline would be "Off" - "Straight" - "Walk" - "Bike" - "Car".
One could even add a short info text beside the heading, e. g. "Routing: Off" as headline etc.

(Reminder to myself: Before maybe implementing this need to check for possible side-effects of removing the "show direction line" setting.)

**Comment by baiti** [comment] 2021-01-27 21:48
Boah ... seems like you have already implemented it.

What does "Set as target automatically" do if selected and what happens if it is not selected?

**Comment by moving-bits** [comment] 2021-01-27 22:00
> Boah ... seems like you have already implemented it.

No, only the icon ;-)

> What does "Set as target automatically" do if selected and what happens if it is not selected?

If you have created an individual route and activate that setting, the first point of your route will be set as target automatically. If you remove the first point from the route, the next point will be used as target etc. - This is meant for use while being on tour, following along your individual route.

If that option is unset or no individual route is defined, nothing will happen.

**Comment by baiti** [comment] 2021-01-27 22:22
Now it is much more than "just" a simple modification to "Strings.xml". I will do my best, most likely seeking help on the way. Of course, assuming we all agree to the design point.

**Comment by moving-bits** [comment] 2021-01-29 19:09
@baiti 
If you want to tackle that issue I can provide you with what I've prepared for it so far, meaning: icon and integration into the map quick settings menu.

TODO would be to check for side-effects of adding `OFF` as state for `RoutingMode` (need to check all occurrences of RoutingMode and adapt conditions when necessary), and add a soft migration of the `UseDirectionLine` setting into checking `RoutingMode.OFF`.

Just give me a sign if you'd like to continue or whether I should complete it.

**Comment by baiti** [comment] 2021-01-29 21:51
I would give it a try. However, I have to setup the envrionment from scratch. I have never managed to create my own cheet sheet. for the whole process, end to end and including keeping my local copy of the code base synchronized with master.  I guess, what I am saying is yes, but it will take time. Much more time than it would take if you completed it. So it really depends on how fast the PR is needed.

P.S. Did we all agree on the "five button solution" you outlined?

**Comment by baiti** [comment] 2021-01-29 22:09
I am in the Wiki under "Working on c:geo for git beginners", completed all steps up to:

>Create alias upstream for the c:geo main repository:
>If you want to use ssh: git remote add upstream git@github.com:cgeo/cgeo.git
>If you want to use https: git remote add upstream https://github.com/cgeo/cgeo.git

Both variants fail in the same way:

`baiti@dog:~/cgeo$ git remote add upstream https://github.com/cgeo/cgeo.git`
`fatal: not a git repository (or any of the parent directories): .git`
`baiti@dog:~/cgeo$`

**Comment by moving-bits** [comment] 2021-01-29 22:13
Thanks @baiti for diving into this!
I've created PR #9901 for the preparations done so far. Will be merged to `master` branch.

You can continue by searching the source for places where `RoutingMode` is used currently, and check whether some additional comparisons against `RoutingMode.OFF` are needed.

Then have a look at `Settings.java`:

```
    /**
     * whether to show a direction line on the map
     */
    public static boolean isMapDirection() {
        return getBoolean(R.string.pref_map_direction, true);
    }

    public static void setMapDirection(final boolean showDirection) {
        putBoolean(R.string.pref_map_direction, showDirection);
    }
```

needs to be adapted to check against `getRoutingMode()` first. Instead of returning `WALK` as default, `getRoutingMode()` probably should check the value returned by `isMapDirection()` and either return `WALK` or `OFF` in that case.

One could also think of removing the `set map direction` setting from Settings => Map as it's completely covered by the map quick settings menu, but that's probably a different case.

**Comment by baiti** [comment] 2021-01-29 22:16
> I am in the Wiki under "Working on c:geo for git beginners", completed all steps up to:
> 
> > Create alias upstream for the c:geo main repository:
> > If you want to use ssh: git remote add upstream [git@github.com](mailto:git@github.com):cgeo/cgeo.git
> > If you want to use https: git remote add upstream https://github.com/cgeo/cgeo.git
> 
> Both variants fail in the same way:
> 
> `baiti@dog:~/cgeo$ git remote add upstream https://github.com/cgeo/cgeo.git`
> `fatal: not a git repository (or any of the parent directories): .git`
> `baiti@dog:~/cgeo$`

I figured it out. Reason it failed was that the preceeding git clone command created a direcctory called cgeo under my cgeo
Once I straightened this out it woked. I am now following the recipe further ...

**Comment by baiti** [comment] 2021-01-29 22:31
> > I am in the Wiki under "Working on c:geo for git beginners", completed all steps up to:
> > > Create alias upstream for the c:geo main repository:
> > > If you want to use ssh: git remote add upstream [git@github.com](mailto:git@github.com):cgeo/cgeo.git
> > > If you want to use https: git remote add upstream https://github.com/cgeo/cgeo.git
> > 
> > 
> > Both variants fail in the same way:
> > `baiti@dog:~/cgeo$ git remote add upstream https://github.com/cgeo/cgeo.git`
> > `fatal: not a git repository (or any of the parent directories): .git`
> > `baiti@dog:~/cgeo$`
> 
> I figured it out. Reason it failed was that the preceeding git clone command created a direcctory called cgeo under my cgeo
> Once I straightened this out it woked. I am now following the recipe further ...

Seems I am now back in business ;) The "Working on c:geo for git beginners" section is good stuff. Thanks much.

**Comment by baiti** [comment] 2021-01-30 08:45
Stuck again. I now have successfully built my local clone from my fork from 1/29. Wanted to run it on the emulator. Pixel3, Android 10. It detected my nightly, asked me to uninstall it. I said yes, then the new version installed and asked me for various permissions, all good so far. I came to the point where I was able to login to gc.com. Then I ended up in cgeo's own dialog "Grant access for Data Storage". Whatever I do from there, ends in cgeo terminating and when I restart it, I end up in the same dialog with the same results. Endlessly. Only if I press "Cancel" in that dialog, I end up, I guess, with cgeo using legacy directory setup. It is most likely ok as long as I am on Android 10 so I just continue from here with legacy folder structure, however, there is something wrong in the current master repo.

**Comment by moving-bits** [comment] 2021-01-30 09:08
Strange. Does work here on a fresh install. In the "grant" dialog I chose "do nothing" and selected my old "cgeo" dir in the next step. Then I was able to restore my database backup, and c:geo restarted. (Or actually, it terminated after a message stating to need a restart, and after a manual restart everything was fine.)

Anything in the logfile for what you've experienced?
(You should be able to see the logfile from within Android Studio by now, as you have been able to connect AS and the emulator. There is a tab called "LogCat", see bottom left in AS window.)

**Comment by baiti** [comment] 2021-01-30 09:24
In the grant dialog, if I select "do nothing", then press "Select Folder", I end up in a view of a file manager, showing the Download directory. At the bottom it says in blue background (so I believe this comes "from the system") "ALLOW ACCESS TO DOWNLOADS".  If I click that, the cgeo crashes, logcat shows a red dump. Each and every time I do this, a new "file_<date>.dat" file with zero bytes length is created in ~/Downloads (on the emulator).

And logcat ..yes, **a lot**. If I cancel the directory thing, go into map view, to test the direction thing, it loops like this:

`2021-01-30 10:22:22.153 12279-12657/cgeo.geocaching W/cgeo: [LayerManager] cannot parse brouter output of length 29
    org.apache.harmony.xml.ExpatParser$ParseException: At line 1, column 0: syntax error
        at org.apache.harmony.xml.ExpatParser.parseFragment(ExpatParser.java:509)
        at org.apache.harmony.xml.ExpatParser.parseDocument(ExpatParser.java:494)
        at org.apache.harmony.xml.ExpatReader.parse(ExpatReader.java:315)
        at org.apache.harmony.xml.ExpatReader.parse(ExpatReader.java:273)
        at android.util.Xml.parse(Xml.java:57)
        at cgeo.geocaching.maps.routing.Routing.parseGpxTrack(Routing.java:217)
        at cgeo.geocaching.maps.routing.Routing.calculateRouting(Routing.java:210)
        at cgeo.geocaching.maps.routing.Routing.getTrack(Routing.java:148)
        at cgeo.geocaching.maps.mapsforge.v6.layers.NavigationLayer.draw(NavigationLayer.java:62)
        at org.mapsforge.map.layer.LayerManager.doWork(LayerManager.java:95)
        at org.mapsforge.map.util.PausableThread.run(PausableThread.java:149)
`

I have BRouter installed and the required map tiles loaded.

Also, the PR you mentioned above, with your initial changes, has not been merged into master yet, so I am looking at the original quick settings view.

**Comment by baiti** [comment] 2021-01-30 09:27
For completeness, here is the FATAL ABORT for the Grant, do nothin scenario
`2021-01-30 10:25:05.079 12279-12279/cgeo.geocaching D/AndroidRuntime: Shutting down VM
2021-01-30 10:25:05.080 12279-12279/cgeo.geocaching E/AndroidRuntime: FATAL EXCEPTION: main
    Process: cgeo.geocaching, PID: 12279
    java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=59372, result=-1, data=Intent { dat=content://com.android.providers.downloads.documents/tree/downloads flg=0xc3 }} to activity {cgeo.geocaching/cgeo.geocaching.MainActivity}: java.lang.IllegalArgumentException: mimeType can't be null
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4845)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:4886)
        at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
     Caused by: java.lang.IllegalArgumentException: mimeType can't be null
        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:170)
        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:140)
        at android.content.ContentProviderProxy.call(ContentProviderNative.java:658)
        at android.content.ContentResolver.call(ContentResolver.java:2042)
        at android.provider.DocumentsContract.createDocument(DocumentsContract.java:1327)
        at cgeo.geocaching.storage.DocumentContentAccessor.createInternal(DocumentContentAccessor.java:111)
        at cgeo.geocaching.storage.DocumentContentAccessor.create(DocumentContentAccessor.java:98)
        at cgeo.geocaching.storage.ContentStorage.create(ContentStorage.java:169)
        at cgeo.geocaching.storage.ContentStorage.tryTestReadWriteToFolder(ContentStorage.java:426)
        at cgeo.geocaching.storage.ContentStorage.ensureFolder(ContentStorage.java:133)
        at cgeo.geocaching.storage.ContentStorageActivityHelper.handleResultPersistableFolderSelection(ContentStorageActivityHelper.java:338)
        at cgeo.geocaching.storage.ContentStorageActivityHelper.onActivityResult(ContentStorageActivityHelper.java:210)
        at cgeo.geocaching.activity.AbstractActivity.onActivityResult(AbstractActivity.java:300)
        at cgeo.geocaching.MainActivity.onActivityResult(MainActivity.java:571)
        at android.app.Activity.dispatchActivityResult(Activity.java:8110)
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4838)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:4886) 
        at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7356) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930) 
`

**Comment by moving-bits** [comment] 2021-01-30 09:34
Ok, I can reproduce the crash on selecting `Downloads` folder in the grant dialog. I'll open a separate issue for it.

Only that it starts with "Allow access to cgeo" for me, even though I have uninstalled c:geo and renamed the c:geo folder. It recreates a `cgeo` folder in the main storage's root for me.

**Comment by moving-bits** [comment] 2021-01-30 09:38
To unstuck: Can you create a `cgeo` folder using your filemanager (if that folder does not already exists), and then chose that folder in the grant dialog?

**Comment by baiti** [comment] 2021-01-30 09:52
> To unstuck: Can you create a `cgeo` folder using your filemanager (if that folder does not already exists), and then chose that folder in the grant dialog?

That worked...

Two problems at this time

1. Master doesn't have your changes to the router changes you did
2. Currently struggling with git, in the path where the wiki discusses "Refreshing your local environment". Everything I pulled, worked, but when I try to do a push, git seems to use wrong credentials. I will google myself  through that now ..

**Comment by moving-bits** [comment] 2021-01-30 10:05
> 1. Master doesn't have your changes to the router changes you did

I've merged it now. Do a local refresh and you should be ready to go.

> 2. Currently struggling with git, in the path where the wiki discusses "Refreshing your local environment". Everything I pulled, worked, but when I try to do a push, git seems to use wrong credentials. I will google myself  through that now ..

Are you pushing against the `cgeo` repo (won't work, as you don't have credentials for that) or against your fork (that should work)?

**Comment by Lineflyer** [comment] 2021-01-30 10:27
> 2. Currently struggling with git, in the path where the wiki discusses "Refreshing your local environment". Everything I pulled, worked, but when I try to do a push, git seems to use wrong credentials. I will google myself through that now ..

Didnt look into our guide, but normally you should clone your fork as `origin` and the cgeo repo as e.g. `upstream`. So you can push to `origin` and pull from `upstream`.
Check it with `git remote -v`.

**Comment by baiti** [comment] 2021-01-30 10:38
> > 1. Currently struggling with git, in the path where the wiki discusses "Refreshing your local environment". Everything I pulled, worked, but when I try to do a push, git seems to use wrong credentials. I will google myself through that now ..
> 
> Didnt look into our guide, but normally you should clone your fork as `origin` and the cgeo repo as e.g. `upstream`. So you can push to `origin` and pull from `upstream`.
> Check it with `git remote -v`.

Of course I followed the guide literally point by point. The problem seems to be that I am using  the same machine for development  of multiple projects and I had already uploaded the ssh-keys to github, however for a different username. I now have created an additional pair of ssh keys, uploaded the newly created keys to github under the correct name "baiti". and have updated my ~./ssh/config to use the correct keys for domain github.com.

The only problem: How to I manage to use the other key for the other project. Seems I have to modify my ~/.ssh/config for github.com each time but this is not cgeo's problem of course.

**Comment by baiti** [comment] 2021-01-30 10:47
> > 1. Master doesn't have your changes to the router changes you did
> 
> I've merged it now. Do a local refresh and you should be ready to go.
> 

Pulled it and have it working on the emulator, however, experiencing the same looping failure, which has nothing to do with your latest merge as it was there before I pulled the changes. I'd assume this needs to be resolved before I even think about making any code changes:

`2021-01-30 11:46:14.276 14379-14485/cgeo.geocaching W/cgeo: [LayerManager] cannot parse brouter output of length 50
    org.apache.harmony.xml.ExpatParser$ParseException: At line 1, column 0: syntax error
        at org.apache.harmony.xml.ExpatParser.parseFragment(ExpatParser.java:509)
        at org.apache.harmony.xml.ExpatParser.parseDocument(ExpatParser.java:494)
        at org.apache.harmony.xml.ExpatReader.parse(ExpatReader.java:315)
        at org.apache.harmony.xml.ExpatReader.parse(ExpatReader.java:273)
        at android.util.Xml.parse(Xml.java:57)
        at cgeo.geocaching.maps.routing.Routing.parseGpxTrack(Routing.java:217)
        at cgeo.geocaching.maps.routing.Routing.calculateRouting(Routing.java:210)
        at cgeo.geocaching.maps.routing.Routing.getTrack(Routing.java:148)
        at cgeo.geocaching.maps.mapsforge.v6.layers.NavigationLayer.draw(NavigationLayer.java:62)
        at org.mapsforge.map.layer.LayerManager.doWork(LayerManager.java:95)
        at org.mapsforge.map.util.PausableThread.run(PausableThread.java:149)
`

**Comment by baiti** [comment] 2021-01-30 11:05
Where do I report the following potential problem with "Working on c:geo for git beginners" (Wiki)

If the **https** method is used for the following:

>Clone your forked repository:
If you want to use ssh: git clone git@github.com:bruno/cgeo.git
If you want to use https: git clone https://github.com/bruno/cgeo.git
(the last step automatically created the standard alias origin for this remote repository)
Create alias upstream for the c:geo main repository:
If you want to use ssh: git remote add upstream git@github.com:cgeo/cgeo.git
If you want to use https: git remote add upstream https://github.com/cgeo/cgeo.git

Then a subsequent "git push" further down the road, asks for github username and password and if those are specified, you'll receive an email with a deprecation notice from github:

>You recently used a password to access the repository at baiti/cgeo with git using git/2.25.1.
>
>Basic authentication using a password to Git is deprecated and will soon no longer work. Visit https://github.blog/2020-12-15-token-authentication-requirements-for-git-operations/ for more information around suggested workarounds and removal dates. 

Using the ssh method right from the top where the git clone is done, avoids this problem later.

**Comment by Lineflyer** [comment] 2021-01-30 11:20
Maybe you should hop onto our IRC chat (see readme.md) and chat with one of the team to sort this out. Might be more efficient and does not clutter this issue to much. Not sure if someone is around on the IRC at this moment, but normally someone will reply after a while or after reading my post here ;)

**Comment by baiti** [comment] 2021-01-30 13:56
I hopped in. There were 17 folks around, however, the channel was entirely quiet. I said "Hi" but no reaction whatsoever so after a while I left.

In order to limit the spam on this channel, I won't report anything that isn't directly related to the issue at hand. So I'd say we can forget my comments wrt the Wiki and also wrt to git handling https vs ssh requests.

So back to the issue: I believe it makes no sense if I started to investigate the source could while I have not accomplished to run a clean build on the emulator that doesn't go into exception loops and memory leaks without me even touching the points that are subject of this issue. I would assume that a lot is going on in master's HEAD and that I have just cloned / pulled it at the wrong time. I think I will give it some time to settle and clone / pull  a completely fresh copy tomorrow and see if it goes any better. At least at the UI I can see the changes you made wrt to routing.

**Comment by eddiemuc** [comment] 2021-01-30 14:11
> Maybe you should hop onto our IRC chat (see readme.md) and chat with one of the team to sort this out. Might be more efficient and does not clutter this issue to much. Not sure if someone is around on the IRC at this moment, but normally someone will reply after a while or after reading my post here ;)

This is sure the wrong place to discuss this, but I can't really use the IRC channel because it is completely cluttered with all the cgeo-ci messages. I find it very hard to find the messages from "real people" into all this

**Comment by moving-bits** [comment] 2021-01-30 14:57
> Pulled it and have it working on the emulator, however, experiencing the same looping failure, which has nothing to do with your latest merge as it was there before I pulled the changes. I'd assume this needs to be resolved before I even think about making any code changes:
> 
> `2021-01-30 11:46:14.276 14379-14485/cgeo.geocaching W/cgeo: [LayerManager] cannot parse brouter output of length 50

Strange, cannot reproduce here. Can you open file `maps/routing/Routing.java`, go to about line 240 and change it from 
`Log.w("cannot parse brouter output of length " + gpx.length(), e);` to 
`Log.w("cannot parse brouter output of length " + gpx.length() + ", gpx=" + gpx, e);`,
then run again, create a logfile and post the result here? (In contrast to the logfile above it should additionally print the string returned by the brouter call.) Thanks.

**Comment by eddiemuc** [comment] 2021-01-30 16:07
My guess would be that brother returns some sort of error Message instead of valid xml

**Comment by baiti** [comment] 2021-01-30 18:17
W/cgeo: [LayerManager] cannot parse brouter output of length 50, gpx=no brouter service config found for mode off_short

**Comment by moving-bits** [comment] 2021-01-30 18:50
Thanks for looking that up. Yes, this is an artifact of me adding "OFF" to `RoutingMode`. That value should never be sent to brouter, so that's part of the cleanup work that needs to be done to avoid any unwanted side-effects.

To get out of the dead-end you can change the routing setting manually be entering Settings => System => View settings => search for "map_routing" (should be "off"), enter edit mode, change value to e. g. "bicycle".

**Comment by baiti** [comment] 2021-01-31 10:50
With the improved Log.i() statement  mentioned earlier in this thread, I stumbled over:

>W/cgeo: [LayerManager] cannot parse brouter output of length 29, gpx=datafile E5_N45.rd5 not found

I think we need to handle this somehow in a tolerant way and not running into the syntax error exception thrown by the XML parser. I could look into that, however, 1st things 1st ;)

**Comment by baiti** [comment] 2021-01-31 11:20
With the above change, the logic actually worked nicely on the emulator, however, the "Settings -> Map -> Show Direction" settings is now not relevant anymore. Need to look at how this can be removed.

**Comment by baiti** [comment] 2021-01-31 11:45
> With the above change, the logic actually worked nicely on the emulator, however, the "Settings -> Map -> Show Direction" settings is now not relevant anymore. Need to look at how this can be removed.
> 
> I have not yet found where that dialog is and how to modify it. If I try to open any layout file I am getting a: "Design editor is unavavailable until after a successful project sync". I googled that message and tried everything that was recommended to others having the same problem but nothing worked so far.

Found it! I had to install SDK 28. Didn't know that there is such a dependency. I only had 29 and 30 until now.

**Comment by fm-sys** [comment] 2021-01-31 11:52
> however, the "Settings -> Map -> Show Direction" settings is now not relevant anymore. Need to look at how this can be removed.
> 
> I have not yet found where that dialog is and how to modify it.

Search for the file `preferences.xml`. All settings are defined there...

**Comment by moving-bits** [comment] 2021-01-31 14:57
> With the improved Log.i() statement mentioned earlier in this thread, I stumbled over:
> 
> > W/cgeo: [LayerManager] cannot parse brouter output of length 29, gpx=datafile E5_N45.rd5 not found
> 
> I think we need to handle this somehow in a tolerant way and not running into the syntax error exception thrown by the XML parser. I could look into that, however, 1st things 1st ;)

See #9914 for BRouter routing data downloading. My idea is to integrate this in our MapDownloader routines. But we need permission from the author of BRouter first.

**Closed** 2021-02-01 20:01 UTC
Labels: Assigned-non-collab, Bug, Frontend Design
