### ISSUE TITLE
Adapt new logging rules at GC

### ISSUE THREAD

**Issue by SammysHP** [cgeo/cgeo#6465] opened 2017-03-30 21:34 UTC
According to http://gsak.net/board/index.php?showtopic=32259 there will be two changes to the available log types for the API as well as the website:

1. A user can log a cache only once as found. c:geo should handle this in two ways: Handle the message returned by the website in case of an error; show a warning and disallow another found log if the cache is known as already found.
2. The owner of a cache cannot log found and maintenance logs. This should be reflected in the available log types in c:geo.

**Comment by Lineflyer** [comment] 2017-03-31 11:21
AFAIK this will be implictly implemented as soon as gc.com limits the log types possible also on the website as we populate the available log types while parsing the logging page from the website.

Or do you think we should implement this independently to reflect the API behaviour also while the website is (possibly) still allowing this?

**Comment by SammysHP** [comment] 2017-03-31 11:41
The list is populated automatically only if there is an Internet connection. Otherwise we have a default set.

We should provide what is possible via the website.

**Comment by Bananeweizen** [comment] 2017-04-08 11:07
That change covers almost all of the rule changes (except for not allowing a second WILL_ATTEND). Be aware that trying to test this change is not possible right now, since the logging activity will override this reduced list by what is (still) available on the website.

@Lineflyer Please come back to testing this only after the website change.

**Comment by UniQP** [comment] 2017-04-08 11:35
@Bananeweizen As mentioned by @SammysHP [above](https://github.com/cgeo/cgeo/issues/6465#issuecomment-290690437), this already affects the possible options when the device is offline.

I also noticed that when trying to log an own cache offline (= online after the website change), the preselected option is "found it", which wouldn't be a valid option anymore.

**Comment by Bananeweizen** [comment] 2017-04-09 06:01
I can't test for own caches, since I don't own any. Testing an already found cache in airplane mode, the behavior is as expected ("Found" not available anymore).

I found only one possible way to come to an invalid state: If an additional offline found log exists for an already found cache, then this offline log will be loaded and the selected type will be "found", even though it should not be available anymore. That has been fixed with the commit above. If you can still reproduce the bad pre-selection on your owned cache, then it might be worth debugging into it on your side.

**Comment by SammysHP** [comment] 2017-04-09 06:06
@Lineflyer Can you add a FAQ entry why some log types are not available?

**Comment by Lineflyer** [comment] 2017-04-09 21:00
Can someone update me on this?
Is this already live on gc.com (via website not via API)?

**Comment by UniQP** [comment] 2017-04-09 21:03
No, it is not live yet.

**Comment by Lineflyer** [comment] 2017-04-10 07:39
Then I do not understand this:
> @Lineflyer Can you add a FAQ entry why some log types are not available?

At the moment the only change will be the behaviour of the nightly version, correct?
In this case I could create a reminder issue for the website repo to add this to the FAQ as soon as we know how the whole feature behaves after the website change.

Furthermore I am not even sure, if Groundspeak has any plans to bring this change to the website at all as it was only announced for the API AFAICS.

**Comment by SammysHP** [comment] 2017-04-10 08:20
From the thread I linked previously:

> In our online reviewer meeting yesterday, we were told the website would get these changes sometime in "early to mid-April." They're giving API partners a bit longer to adapt.

**Comment by Lineflyer** [comment] 2017-04-12 07:42
Setting to fieldtest

**Comment by Lineflyer** [comment] 2017-05-09 20:05
Note:
The change is live on the website now (but according to Groundspeak release note) not yet for the API.
However my tests shows the recent change is matching between offline and online case.

So before parsing the log page we already avoid showing non available log types, and after parsing it, it is correct anyway.

**Closed by Lineflyer** 2017-05-09 20:05 UTC
Labels: Field test
