### ISSUE TITLE
Excessive "Remove list" dialog

### ISSUE THREAD

**Issue by andrixnet** [cgeo/cgeo#8421] opened 2020-06-08 09:02 UTC
**Describe the bug:**
Under certain conditions the "remove list" dialog appears repeatedly, though the first time I answered it "Cancel".

**To Reproduce:**
1. have a list of caches
2. remove all caches from the list. you will be asked if you also want to remove the now empty list.
answer "Cancel"
3. do any of the following actions:
- switch to another app, then back to c:geo (using window manager)
- go to home screen, you could start another app or do smth, go to c:geo icon and click on it
- within c:geo, open the menu, vizit various sections but do not initiate any action and return to the empty list
4. do the following action: 
- select another list from the lists menu, then select your empty list again. 

**Actual behavior/state after performing these steps:**
every variant at 3. results in the "Remove list" dialog being displayed again and again at each action variant. I press "Cancel" every time.

in case of 4. the dialog no longer appears then or further actions from 3.

**Expected behavior/state after performing these steps:**
once I answer the dialog I expect it not to appear again.

**Version of c:geo used:**
version 2020.04.25

**Is the problem reproducible:**
Yes

**System information:**
```
--- System information ---
Device: SM-G965F (star2ltexx, samsung)
Android version: 9
Android build: PPR1.180610.011.G965FXXS7CSK4
c:geo version: 2020.04.25
Google Play services: enabled - 20.18.17 (100400-311416286)
Low power mode: inactive
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: rotation vector
Hide caches: own/found
Hide waypoints: -
HW acceleration: enabled (default state)
System language: en_GB
System date format: dd/MM/y
Debug mode active: no
System internal c:geo dir: /data/user/0/cgeo.geocaching (193.5 GB free) internal
User storage c:geo dir: /storage/emulated/0/cgeo (193.5 GB free) external non-removable
Geocache data: /storage/emulated/0/Android/data/cgeo.geocaching/files/GeocacheData (193.5 GB free) external non-removable
Database: /storage/emulated/0/Android/data/cgeo.geocaching/files/databases/data (6.7 MB) on user storage
Fine location permission: granted
Write external storage permission: granted
Geocaching sites enabled:
geocaching.com: Logged in (Login OK) / BASIC
Geocaching.com date format: yyyy-MM-dd
Installed c:geo plugins: none
--- End of system information ---

```

**Additional context:**
My intentions that led to the discovery of this issue were the following:
- remove caches from a list to clean it up and load a new gpx into it
- i removed the caches before copying the gpx into the device, thus immediately after removing, I switch to file manager to get the gpx, then I return to c:geo to import.

**Comment by Lineflyer** [comment] 2020-06-13 14:48
Confirmed also with 2020.06.13-NB using the variant, that I just leave c:geo (to device home screen) after deleting the caches and return to c:geo.

**Comment by moving-bits** [comment] 2021-11-20 21:54
Since a few versions you can choose "never ask me again for this list" in the mentioned dialog - this should resolve the issue, therefore closing here.

**Closed by moving-bits** 2021-11-20 21:54 UTC
Labels: Bug
