### ISSUE TITLE
Next release after 2023.02.12

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#14024] opened 2023-02-24 09:20 UTC
I closed the old issue and opened this new one.
In a first step I simply took over what was listed as still open in the old issue:
- [ ] #5599
- [ ] #10428
- [x] #13999
- [ ] #13675
- [x] #13759
- [ ] #11725
- [ ] #13698 

Edit:
Adding:
- [ ] #12225
- [ ] #14001 
- [ ] #13097 (workaround available with #14056)
- [x] #13993 
- [x] #14032
- [x] #13983
- [x] #14028

**Comment by fm-sys** [comment] 2023-02-25 17:06
We have a new regression (#14028) in our newest release, which however needs to be fixed at master. Luckily, not too many users will probably ever notice that bug.

However, as there were quite some minor changes at master in the last weeks, I would propose to start a new beta rather soon.

**Comment by moving-bits** [comment] 2023-02-25 17:11
As we also have quite a few small bugfixes ready on `release`, I propose to release a bugfix release first, then prepare a new beta from `master`.

I'll start working on it tonight, if noone objects.

**Comment by alan666notb** [comment] 2023-02-25 17:15
A minor issue, possibly related, is that if you delete the route, it remains on the map until you close the map and re-open it.

**Comment by fm-sys** [comment] 2023-02-25 17:30
> I'll start working on it tonight, if noone objects. 

Sounds good 👍

As we have the fix for #14028 on `release` as well, there is no pressure to release a new beta quickly...

**Comment by moving-bits** [comment] 2023-02-25 18:09
> > I'll start working on it tonight, if noone objects.
> 
> Sounds good 👍
> 
> As we have the fix for #14028 on `release` as well, there is no pressure to release a new beta quickly...

Ok, you guys are pretty fast! 👍 I'll prepare just a bugfix release then.

**Comment by moving-bits** [comment] 2023-02-25 21:44
Will start working on bugfix release now:

- [ ] Check/insert correct version name in `/main/res/raw/changelog_bugfix.md`
- [ ] Wait for a Crowdin cycle or trigger sync manually
- [ ] Merge the related Crowdin translation pull requests for branch `release`
- [ ] Build release on CI server
- [ ] Perform smoke test with resulting ```cgeo-release.apk``` before continuing
- [ ] Upload and publish ```cgeo-release.apk``` to Google Play
- [ ] Tag the release on Github in format `market_yyyymmdd`
- [ ] Publish the release on Github including upload of ```cgeo-release.apk``` to Github
- [ ] Publish release on F-Droid
- [ ] Trigger notification to status.cgeo.org via CI server
- [ ] Post release info to Facebook 
- [ ] Post release info to Twitter

**Comment by fm-sys** [comment] 2023-03-08 01:26
More and more issues coming in mentioning "burned in" behavior on GMap for all kind of lines 
https://github.com/cgeo/cgeo/issues/14032 https://github.com/cgeo/cgeo/issues/13993 #14068

**Comment by eddiemuc** [comment] 2023-03-08 06:01
> More and more issues coming in mentioning "burned in" behavior on GMap for all kind of lines 
> https://github.com/cgeo/cgeo/issues/14032 https://github.com/cgeo/cgeo/issues/13993 #14068
> 

We can try to replace the route/track layer of GM with the new unified GeoItemLayer. This approach would not be without risks though since the implementation is pretty fresh and untested. Original plan was to test it for a longer time as part of unified map first.

**Comment by moving-bits** [comment] 2023-03-08 06:47
Before we try this we should probably analyze what has changed in our codebase for GMv2 in the Februar release(s), since those errors seem to have entered the scene with one of those versions.

**Comment by eddiemuc** [comment] 2023-03-08 07:45
> Before we try this we should probably analyze what has changed in our codebase for GMv2 in the Februar release(s), since those errors seem to have entered the scene with one of those versions.

One thing I changed for sure is the introduction of GeoJson support. Works fine on mapsforge. But back then I noticed that the underlying Google Maps integration is designed in a faulty way and inherently sometimes "forgets" to remove objects on the map. A solution to this is complex and provided by new GeoItemLayer. Introduction of GeoJson might have shifted a "smelling code at balance" into a "bad" direction unwillingly. Hard to tell without a longer analyzation session.

**Comment by fm-sys** [comment] 2023-03-08 09:51
> We can try to replace the route/track layer of GM with the new unified GeoItemLayer. 

If you think this is feasible with a reasonable amount of time I would say go ahead. Otherwise we should probably try to patch the current layer with some ugly hotfix code for now

**Comment by fm-sys** [comment] 2023-03-15 12:27
The ghost line problem seems to be solved. Worth a new bugfix release?

**Comment by Lineflyer** [comment] 2023-03-15 21:33
Yes, its worth a new bugfix release IMHO, also as we have the fix or not showing OSM waypoints in addition.

Anyone working on https://github.com/cgeo/cgeo/issues/13759 ?
Is there a big problem to fix it or just no one took the point? Its a website regression.

**Comment by moving-bits** [comment] 2023-03-25 13:37
If no one objects I'll create a new bugfix release this evening, using current state of `release` branch.

**Comment by moving-bits** [comment] 2023-03-25 18:52
Will start working on bugfix release now:

- [ ] Check/insert correct version name in `BranchDetectionHelper.java`
- [ ] Wait for a Crowdin cycle or trigger sync manually
- [ ] Merge the related Crowdin translation pull requests for branch `release`
- [ ] Build release on CI server
- [ ] Perform smoke test with resulting ```cgeo-release.apk``` before continuing
- [ ] Upload and publish ```cgeo-release.apk``` to Google Play
- [ ] Tag the release on Github in format `market_yyyymmdd`
- [ ] Publish the release on Github including upload of ```cgeo-release.apk``` to Github
- [ ] Publish release on F-Droid
- [ ] Trigger notification to status.cgeo.org via CI server
- [ ] Post release info to Facebook 
- [ ] Post release info to Twitter

**Comment by ztNFny** [comment] 2023-03-26 14:40
seems I'm too late to the party with the fix for https://github.com/cgeo/cgeo/issues/13759 :-(

**Comment by moving-bits** [comment] 2023-04-07 17:23
We've got a couple of tickets on support regarding bookmark lists recently. As we have a fix for this already on `release` I propose to create another bugfix release rather soon. If no one objects I'll prepare one tomorrow evening.

**Comment by Lineflyer** [comment] 2023-04-07 20:02
See also my new issue regarding bookmark list download.

**Comment by Lineflyer** [comment] 2023-04-07 20:03
BTW: Better wait with any release until after easter holidays to avoid frustration in case we have some unseen regression.

**Comment by ztNFny** [comment] 2023-04-08 15:08
both bookmark issues are fixed on master now (well, they'll be after the merge) so I suggest to release soon

**Comment by moving-bits** [comment] 2023-04-08 18:22
> both bookmark issues are fixed on master now (well, they'll be after the merge) so I suggest to release soon

Thanks for diving into this (and for taking into account both parts). 

> BTW: Better wait with any release until after easter holidays to avoid frustration in case we have some unseen regression.

Shall I prepare the new release on Tuesday evening then?

**Comment by Lineflyer** [comment] 2023-04-10 19:58
> Shall I prepare the new release on Tuesday evening then?

Sounds good.. I assume you mean a bugfix release from `release`?
I will be on business trip, so I would appreciate if you take care of it.

**Comment by moving-bits** [comment] 2023-04-10 20:10
Yes, bugfix release from `release`. I'll take care of it.

(Although we could additionally think of preparing a new beta. Or discuss this in next week's meeting.)

**Comment by moving-bits** [comment] 2023-04-11 14:11
Will start working on bugfix release now:

- [ ] Check/insert correct version name in `BranchDetectionHelper.java`
- [ ] Wait for a Crowdin cycle or trigger sync manually
- [ ] Merge the related Crowdin translation pull requests for branch `release`
- [ ] Build release on CI server
- [ ] Perform smoke test with resulting ```cgeo-release.apk``` before continuing
- [ ] Upload and publish ```cgeo-release.apk``` to Google Play
- [ ] Tag the release on Github in format `market_yyyymmdd`
- [ ] Publish the release on Github including upload of ```cgeo-release.apk``` to Github
- [ ] Publish release on F-Droid
- [ ] Trigger notification to status.cgeo.org via CI server
- [ ] Post release info to Facebook 
- [ ] Post release info to Twitter

**Comment by moving-bits** [comment] 2023-04-26 08:59
I propose to start a new beta cycle in the next few days. We have accumulated quite a few new things in the nightlies, and last full version is from mid of February. If no one objects I would start working on it on Friday.

**Comment by moving-bits** [comment] 2023-04-30 17:07
Will start working on preparing a new beta now:

- [ ] empty `changelog_bugfix.md` on branch `master`
- [ ] Wait for a Crowdin cycle or trigger sync manually
- [ ] Merge the related Crowdin translation pull requests for branch `release`
- [ ] fast forward `release` branch to HEAD of `master`
- [ ] Check/insert correct version name in `BranchDetectionHelper.java`
- [ ] Build release on CI server
- [ ] Perform smoke test with resulting ```cgeo-RC.apk``` before continuing
- [ ] Upload and publish ```cgeo-RC.apk``` to Google Play on beta channel
- [ ] Trigger notification to status.cgeo.org via CI server
- [ ] Post release info to Facebook 
- [ ] Post release info to Twitter

**Comment by moving-bits** [comment] 2023-05-01 19:41
Let's collect items in current beta that should be fixed before releasing a new feature release:

Reported by Play Store for current beta 2023.04.30-RC:
- [ ] #14212

**Comment by moving-bits** [comment] 2023-05-07 09:29
Current beta is running smooth so far, no relevant error occurrences except the one we have a fix for in the nightlies.

Thus I propose to test the other fixes which are already in the nightlies (#14249, #14253) or in the queue (#14255) throughout this week, and if no problems occur, release the next feature release on next weekend.

**Comment by moving-bits** [comment] 2023-05-15 20:00
Starting to prepare a new release now:

- [ ] Check/insert correct version name in `BranchDetectionHelper.java`
- [ ] Wait for a Crowdin cycle or trigger sync manually
- [ ] Merge the related Crowdin translation pull requests for branch `release`
- [ ] Build release on CI server
- [ ] Perform smoke test with resulting ```cgeo-release.apk``` before continuing
- [ ] Upload and publish ```cgeo-release.apk``` to Google Play
- [ ] Tag the release on Github in format `market_yyyymmdd`
- [ ] Publish the release on Github including upload of ```cgeo-release.apk``` to Github
- [ ] Publish release on F-Droid
- [ ] Trigger notification to status.cgeo.org via CI server
- [ ] Post release info to Facebook 
- [ ] Post release info to Twitter

**Comment by moving-bits** [comment] 2023-05-19 16:15
Version is out in the wild since a couple of days, so let's close this issue.

Thanks to all contributors of this version, highly appreciated!

**Closed by moving-bits** 2023-05-19 16:15 UTC
Labels: Feedback required
