### ISSUE TITLE
Loading log images is done multiple times

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#4578] opened 2015-01-01 21:47 UTC
While working on #4563 it was discovered that something is wrong with the mechanism of downloading log pictures:

1. When refreshing caches multiple times it could be seen that all (or some?) pictures are downloaded again although they should already be stored offline (setting "Save log images" active). 

2. When opening single caches of this refreshed list and accessing the gallery tab even more network requests are sent although the pictures have been loaded recently (<1 day). In this case at least the request returns a 304 but there shouldn't be a request at all if the pictures is younger than 24 hours.

**Comment by samueltardieu** [comment] 2015-01-02 11:23
I cannot reproduce this. The only instances I see are 404 images (which cannot be cached indeed) and images from new log entries since the last refresh.

Do you have a way to reproduce it, or a copy of the logcat?

**Comment by Lineflyer** [comment] 2015-01-03 12:49
It is indeed different than I first thought. I have just seen that on repeated refresh of the same list of caches still some pictures are loaded, which made me think they are loaded multiple times.

I retested it today and from what I can see, the first refresh loads quite a lot of images and on the sedond refresh also images are loaded (but these have not been contained in the first refresh as far as I checked). Why is that?

Both refreshes have been done a few minutes apart.
Here are the logs:

First refresh:
https://www.dropbox.com/s/joo7hp9byiy2nnw/firstrefresh_89caches_issues4578.txt?dl=0

Seond refresh:
https://www.dropbox.com/s/bmugewj5ynwn39j/secondrefresh_89caches_issues4578.txt?dl=0

Please kindly have a look.

**Comment by samueltardieu** [comment] 2015-01-06 10:47
Caused by #4570. Closing.

**Closed by samueltardieu** 2015-01-06 10:47 UTC
Labels: Bug, Unverified

**Comment by Lineflyer** [comment] 2015-01-07 21:32
I can confirm that the faulty behavior is gone in 2015.01.07-RC
