### ISSUE TITLE
Loading filters is wonky

### ISSUE THREAD

**Issue by ztNFny** [cgeo/cgeo#12073] opened 2021-11-08 21:12 UTC
### Describe your problem!

Loading a stored filter (in advanced mode) is unreliable, "randomly" only some elements of the filter are loaded.

The below video shows repeatedly loading 2 filters which were both created with the filter criteria "Cache Type" and "Status" visible. Filter settings are:
- "Found": in Status Found=Yes
- "Offline log": In Status Has Offline Log=Yes

Loading the filters none to all filter elements are loaded in a seemingly random pattern.

https://user-images.githubusercontent.com/1258173/140818406-ea04e17a-3cbb-42f5-b463-24e0e4067f27.mp4

 

### How to reproduce?

Create 2 filters with different settings
Load them

### Reproducible

Yes

### c:geo Version

2021.11.07-NB

**Comment by eddiemuc** [comment] 2021-11-09 12:47
Can confirm one part of the error: when saved filters are loaded but they contain non-filtering filters (e.g. a cache type filter with all items selected), then those are removed from view (if they are also part of the simple filter). 

This does not explain yet the situation in video above where NO filter can be seen for "Offline Log" though

**Comment by ztNFny** [comment] 2021-11-09 12:49
> when saved filters are loaded but they contain non-filtering filters (e.g. a cache type filter with all items selected), then those are removed from view (if they are also part of the simple filter).

That doesn't happen always though, see 0:07 and 0:16 when the non-filtering filter stays (as I would expect)

**Comment by eddiemuc** [comment] 2021-11-09 13:02
@ztNFny question: wehn you originally created the filters, did you place the type filter visually ABOVE or BELOW the status filter? (this is just for me to reproduce the error correctly)

Seems that these errors are in the logic on how the filter is "converted" into the view. Which is good news, since at least it should filter as expected (although it is not visualized/editable as expected)

**Comment by ztNFny** [comment] 2021-11-09 13:42
> wehn you originally created the filters, did you place the type filter visually ABOVE or BELOW the status filter?

Types was above Status. Whether I inserted it in the correct order or drag & dropped it into it I can't remember.

I recreated the filters and now when loading them it toggles between Types (not) visible but status doesn't disappear anymore.

**Comment by eddiemuc** [comment] 2021-11-09 13:43
@ztNFny I created PR #12074 to include stored filter information into system information (since I realize I need this info to analyze related prolems accordingly). It would be great if you can send me this info after the PR is merged.

Meanwhile (as time permits) I will try to analyze and fix as good as possible.

**Comment by ztNFny** [comment] 2021-11-09 18:49
Cherry-picked the logging:
Filters:
-------
- Hide waypoints: parking visited
- LIVE: None ([:inconclusive=false:advanced=false]AND(type;difficulty_terrain:d=-:d=-:t=-:t=-;status))
- OFFLINE: None ([:inconclusive=false:advanced=true]AND(type;status))

Stored Filters (#5):
- Archived: [Archived:inconclusive=false:advanced=false]AND(status:exclude_active:exclude_disabled;type;difficulty:-:-;terrain:-:-))
- Found: [Found:inconclusive=false:advanced=false]AND(status:found_yes;type;difficulty:-:-;terrain:-:-))
- New Found: [New Found:inconclusive=false:advanced=false]AND(type;status:found_yes))
- New Offline: [New Offline:inconclusive=false:advanced=false]AND(type;status:has_offline_log_yes))
- Offline Log: [Offline Log:inconclusive=false:advanced=false]AND(status:has_offline_log_yes))


I'm seeing 2 bugs here:
- All filters show the behaviour originally described in this issue -> Loading them sections randomly show up or not (it's most prominent for "Types" section but happens for all)
- Filters Archived, Found, Offline Log -> They are advanced=false,  loading them in advanced mode stays in advanced mod and the "Status" filter doesn't show up as it's the simple modes

Do you want a new issue for the second?

**Comment by eddiemuc** [comment] 2021-11-09 20:14
> Do you want a new issue for the second?

No, I try to fix it in one go anyway. Thanks for the details!

**Comment by eddiemuc** [comment] 2021-11-11 13:21
Happens on release too, so I will fix there

**Comment by eddiemuc** [comment] 2021-11-11 14:35
Found the bug(s) and are in the middle of fixing.

However, a question bresents itself.

Part of the error lies in the logic of switching from basic to advanced mode: currently this logic removes all filters which are currently not filtering. This is because in basic mode there are 4 pre-defined filters, all of them are removed when switching to advanced. (the bug is that this is also applied when loading a stored filter -> here this is clearly wrong).

Question is: should I also remove the removal of existing non-filtering filters when switching from basic to advanced in general? I would vote "yes".

**Comment by fm-sys** [comment] 2021-11-11 15:49
> Question is: should I also remove the removal of existing non-filtering filters when switching from basic to advanced in general? I would vote "yes".

I would strongly vote for "no", because:

a) it was explicitly requested in #11378 (by myself)
b) no one has criticized this idea before it got implemented (this issue was open for approx. one month)
c) no one has claimed about this behavior in the last months

**Comment by eddiemuc** [comment] 2021-11-11 15:50
I leave as is for now (when switching from basic to adv via switch, then non-fitering filters are removed).
The bug(s) should be fixed with PR #12079, targeted to release

**Comment by eddiemuc** [comment] 2021-11-11 16:51
> I would strongly vote for "no"

Then it is a good thing I kept it as is :-)

**Closed** 2021-11-13 15:05 UTC
Labels: Bug
