### ISSUE TITLE
Text does't load

### ISSUE THREAD

**Issue by Legowim** [cgeo/cgeo#7087] opened 2018-07-22 21:01 UTC
When picking a random geocache the description is empty and the hint is wrong or isn't the full word/line

**Comment by Lineflyer** [comment] 2018-07-22 21:22
Are you sure, you are logged in?

Please post your system info as listed in Menu - About c:geo - Swipe to "System"

**Comment by SammysHP** [comment] 2018-07-23 04:12
Even if not logged in this should be detected and the cache parsed without description.

**Comment by Legowim** [comment] 2018-07-23 07:12
I am logged in i see that on the homepage of the app

**Comment by mucek4** [comment] 2018-07-23 07:49
I'll ask for the second time: Please post your system info as listed in Menu - About c:geo - Swipe to "System"

**Comment by Legowim** [comment] 2018-07-23 09:09
--- System information ---
Device: ALE-L21 (ALE-L21, Huawei)
Android version: 6.0
Android build: ALE-L21C432B633
c:geo version: 2018.06.26
Google Play services: enabled - 12.8.72 (040406-202717283)
Low power mode: inactive
Compass capabilities: yes
Rotation vector sensor: absent
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: magnetometer & accelerometer
Hide own/found: false
Map strategy: auto
HW acceleration: enabled (default state)
System language: nl_NL
System date format: dd-MM-yy
Debug mode active: no
System internal c:geo dir: /data/user/0/cgeo.geocaching (860,0 MB free) internal
User storage c:geo dir: /storage/emulated/0/cgeo (840,0 MB free) external non-removable
Geocache data: /storage/emulated/0/Android/data/cgeo.geocaching/files/GeocacheData (840,0 MB free) external non-removable
Database: /storage/emulated/0/Android/data/cgeo.geocaching/files/databases/data (5,0 MB) on user storage
Fine location permission: granted
Write external storage permission: granted
Geocaching sites enabled:
   geocaching.com: Logged in (Ingelogd) / BASIC
Geocaching.com date format: dd/MM/yyyy
Installed c:geo plugins: contacts
--- End of system information ---

**Comment by rsudev** [comment] 2018-07-23 11:16
Some follow-up questions (as the system info doesn't reveal any obvious issues):
* When you access geocaching.com on your PC, is the language English?
* Can you give us a sample cache code where you obeserve this (even though it might look like all are affected for you, they could share a common property that makes it fail. an example gives a chance to reproduce the problem)?

**Comment by Lineflyer** [comment] 2018-08-06 21:25
Closing due to lack of repsonse

**Closed by Lineflyer** 2018-08-06 21:25 UTC
Labels: Bug, Unverified
