### ISSUE TITLE
Prevent waypoint list from resetting on change of visited state

### ISSUE THREAD

**Issue by jakedot** [cgeo/cgeo#8110] opened 2020-01-30 06:12 UTC
**Describe the bug:**
When setting a waypoint to **visited**, the waypoint list view resets and scrolls to the top, which is annoying when sorting out waypoints from a cache like [GC892W0](https://coord.info/GC892W0) with many, but not all required, waypoints.

**To Reproduce:**
1. Go to 'Waypoints'
2. Scroll down to 'somewhere out of the initial viewport'
3. Click on 'Visited'

**Actual behavior/state after performing these steps:**
The list view resets and jumps to the top of the list.

**Expected behavior/state after performing these steps:**
The list view should not move the viewport so the user can continue editing at the same position.

**Version of c:geo used:**
2020.01.26-RC

**Is the problem reproducible:**
Yes, always.

**Screenshots:**

![Screenshot_20200129-071748_cgeo](https://user-images.githubusercontent.com/12250212/73424663-cd977300-432f-11ea-8efc-98557d05d2e9.jpg)
![Screenshot_20200129-071752_cgeo](https://user-images.githubusercontent.com/12250212/73424664-cd977300-432f-11ea-9b4a-fd31666e4092.jpg)
![Screenshot_20200129-071756_cgeo](https://user-images.githubusercontent.com/12250212/73424665-ce300980-432f-11ea-96a8-f376f6aa93a3.jpg)

**System information:**
```
--- System information ---
Device: SM-J415FN (j4primeltecis, samsung)
Android version: 9
Android build: PPR1.180610.011.J415FNXXU5BSL2
c:geo version: 2020.01.26-RC
Google Play services: enabled - 19.8.31 (100300-284611645)
Low power mode: inactive
Compass capabilities: no
Rotation vector sensor: absent
Orientation sensor: absent
Magnetometer & Accelerometer sensor: absent
Direction sensor used: magnetometer & accelerometer
Hide own/found: false
HW acceleration: enabled (default state)
System language: de_AT
System date format: dd.MM.yy
Debug mode active: no
System internal c:geo dir: /data/user/0/cgeo.geocaching (14,6 GB free) internal
User storage c:geo dir: /storage/emulated/0/cgeo (14,6 GB free) external non-removable
Geocache data: /storage/emulated/0/Android/data/cgeo.geocaching/files/GeocacheData (14,6 GB free) external non-removable
Database: /data/user/0/cgeo.geocaching/databases/data (13,9 MB) on system internal storage
Fine location permission: granted
Write external storage permission: granted
Geocaching sites enabled:
   geocaching.com: Logged in (Anmeldung OK) / PREMIUM
Geocaching.com date format: dd/MM/yyyy
Installed c:geo plugins: contacts
--- End of system information ---

```

**Additional context:**
May become more relevant with PR #8101 as users will then be able to do more useful stuff (hiding) with visited waypoints.

**Comment by Lineflyer** [comment] 2021-12-26 13:45
Closing this as a duplicate of #1905 as the root cause is IMHO the same (= page content is altered, which makes it reset/jump to top).

**Closed by Lineflyer** 2021-12-26 13:45 UTC
Labels: Bug, Unverified
