### ISSUE TITLE
Downloading offline maps - stops sporadically, after completion there is no map

### ISSUE THREAD

**Issue by as24dev** [cgeo/cgeo#8940] opened 2020-09-03 14:07 UTC
With the new beta I tried to download the offline map europe/alps and europe/belgium
First the download starts but after a few minutes it disappears. Then suddenly the download is working again.
Once the download completes, there is no map on the phone.

**To Reproduce:**
1. Go to CGEO
2. Start "Live Karte"
3. Tap on the map icon on top
4. select <Offlinekarte herunterladen>
5. search Europe/
6 start the download 

The download starts as described above
The download stops and restarts and ends without any map downloaded - at least I don't find any

**Version of c:geo used: 2020.09.02-RC**

**Is the problem reproducible:**
Yes 

**System information:**
Huawei CLT-L29
Build: 10.0.0.171(C432E3R1P3)
EMUI: 10.0.0.
Android 10
July 1st, 2020
Kernel: 4.12.116

```
--------- beginning of system
09-03 15:40:25.915  1698  1698 D ActivityThread: Remove activity client record, r= ActivityRecord{c13bf44 token=android.os.BinderProxy@f54f79e {cgeo.geocaching/cgeo.geocaching.maps.mapsforge.v6.NewMap}} token= android.os.BinderProxy@f54f79e
09-03 15:40:29.306  1698  1698 D ActivityThread: Remove activity client record, r= ActivityRecord{24dd5af token=android.os.BinderProxy@72aebcd {cgeo.geocaching/cgeo.geocaching.MainActivity}} token= android.os.BinderProxy@72aebcd
09-03 15:47:52.735  1698  1698 V ActivityThread: callActivityOnCreate
09-03 15:47:52.775  1698  1698 D ActivityThread: add activity client record, r= ActivityRecord{158be8b token=android.os.BinderProxy@c01ddea {cgeo.geocaching/cgeo.geocaching.MainActivity}} token= android.os.BinderProxy@c01ddea
09-03 15:47:56.674  1698  1698 V ActivityThread: callActivityOnCreate
09-03 15:47:56.735  1698  1698 D ActivityThread: add activity client record, r= ActivityRecord{1d26b43 token=android.os.BinderProxy@6f5e2ed {cgeo.geocaching/cgeo.geocaching.settings.SettingsActivity}} token= android.os.BinderProxy@6f5e2ed
09-03 15:48:07.744  1698  1698 V ActivityThread: callActivityOnCreate
09-03 15:48:07.776  1698  1698 D ActivityThread: add activity client record, r= ActivityRecord{1932459 token=android.os.BinderProxy@fe8d5ba {cgeo.geocaching/cgeo.geocaching.SelectMapfileActivity}} token= android.os.BinderProxy@fe8d5ba
09-03 15:48:17.140  1698  1698 D ActivityThread: Remove activity client record, r= ActivityRecord{1932459 token=android.os.BinderProxy@fe8d5ba {cgeo.geocaching/cgeo.geocaching.SelectMapfileActivity}} token= android.os.BinderProxy@fe8d5ba
09-03 15:48:20.063  1698  1698 D ActivityThread: Remove activity client record, r= ActivityRecord{1d26b43 token=android.os.BinderProxy@6f5e2ed {cgeo.geocaching/cgeo.geocaching.settings.SettingsActivity}} token= android.os.BinderProxy@6f5e2ed
09-03 15:48:21.193  1698  1698 D ActivityThread: Remove activity client record, r= ActivityRecord{158be8b token=android.os.BinderProxy@c01ddea {cgeo.geocaching/cgeo.geocaching.MainActivity}} token= android.os.BinderProxy@c01ddea
09-03 15:51:54.712  1698  1698 V ActivityThread: callActivityOnCreate
09-03 15:51:54.755  1698  1698 D ActivityThread: add activity client record, r= ActivityRecord{def0095 token=android.os.BinderProxy@fd4bd63 {cgeo.geocaching/cgeo.geocaching.MainActivity}} token= android.os.BinderProxy@fd4bd63
09-03 15:51:55.942  1698  1698 D ActivityThread: Remove activity client record, r= ActivityRecord{def0095 token=android.os.BinderProxy@fd4bd63 {cgeo.geocaching/cgeo.geocaching.MainActivity}} token= android.os.BinderProxy@fd4bd63
09-03 15:56:08.370  1698  1698 V ActivityThread: callActivityOnCreate
09-03 15:56:08.403  1698  1698 D ActivityThread: add activity client record, r= ActivityRecord{f945415 token=android.os.BinderProxy@e21a49d {cgeo.geocaching/cgeo.geocaching.MainActivity}} token= android.os.BinderProxy@e21a49d
09-03 15:56:17.469  1698  1698 V ActivityThread: callActivityOnCreate
09-03 15:56:17.507  1698  1698 D ActivityThread: add activity client record, r= ActivityRecord{3496784 token=android.os.BinderProxy@3d5a0cf {cgeo.geocaching/cgeo.geocaching.SearchActivity}} token= android.os.BinderProxy@3d5a0cf
09-03 15:56:17.772  1698  1698 V ActivityThread: callActivityOnCreate
09-03 15:56:17.804  1698  1698 D ActivityThread: add activity client record, r= ActivityRecord{4eb5a6b token=android.os.BinderProxy@df6f7e4 {cgeo.geocaching/cgeo.geocaching.maps.mapsforge.v6.NewMap}} token= android.os.BinderProxy@df6f7e4
09-03 15:56:19.438  1698  1698 D ActivityThread: Remove activity client record, r= ActivityRecord{4eb5a6b token=android.os.BinderProxy@df6f7e4 {cgeo.geocaching/cgeo.geocaching.maps.mapsforge.v6.NewMap}} token= android.os.BinderProxy@df6f7e4
09-03 15:56:19.831  1698  1698 D ActivityThread: Remove activity client record, r= ActivityRecord{3496784 token=android.os.BinderProxy@3d5a0cf {cgeo.geocaching/cgeo.geocaching.SearchActivity}} token= android.os.BinderProxy@3d5a0cf
09-03 15:56:20.334  1698  1698 V ActivityThread: callActivityOnCreate
09-03 15:56:20.363  1698  1698 D ActivityThread: add activity client record, r= ActivityRecord{f12b68b token=android.os.BinderProxy@c5b976d {cgeo.geocaching/cgeo.geocaching.maps.mapsforge.v6.NewMap}} token= android.os.BinderProxy@c5b976d
09-03 15:56:55.336  1698  1698 D ActivityThread: Remove activity client record, r= ActivityRecord{f12b68b token=android.os.BinderProxy@c5b976d {cgeo.geocaching/cgeo.geocaching.maps.mapsforge.v6.NewMap}} token= android.os.BinderProxy@c5b976d
09-03 15:56:57.318  1698  1698 V ActivityThread: callActivityOnCreate
09-03 15:56:57.372  1698  1698 D ActivityThread: add activity client record, r= ActivityRecord{902ea1c token=android.os.BinderProxy@a1a21e {cgeo.geocaching/cgeo.geocaching.settings.SettingsActivity}} token= android.os.BinderProxy@a1a21e
09-03 15:57:04.198 28926 28926 D ActivityThread: Attach thread to application
09-03 15:57:04.295 28926 28926 V ActivityThread: callActivityOnCreate
09-03 15:57:04.385 28958 28958 D ActivityThread: Attach thread to application
09-03 15:57:04.482 28958 28958 V ActivityThread: callActivityOnCreate
09-03 15:57:04.598 28958 28958 D ActivityThread: add activity client record, r= ActivityRecord{ead5c87 token=android.os.BinderProxy@4d08507 {cgeo.geocaching/cgeo.geocaching.MainActivity}} token= android.os.BinderProxy@4d08507
09-03 15:57:10.002 28958 28958 D ActivityThread: Remove activity client record, r= ActivityRecord{ead5c87 token=android.os.BinderProxy@4d08507 {cgeo.geocaching/cgeo.geocaching.MainActivity}} token= android.os.BinderProxy@4d08507
09-03 15:57:13.942 29107 29107 D ActivityThread: Attach thread to application
09-03 15:57:14.030 29107 29107 V ActivityThread: callActivityOnCreate
09-03 15:57:14.115 29107 29107 D ActivityThread: add activity client record, r= ActivityRecord{b5e8d95 token=android.os.BinderProxy@4d08507 {cgeo.geocaching/cgeo.geocaching.MainActivity}} token= android.os.BinderProxy@4d08507
09-03 15:57:17.583 29107 29107 V ActivityThread: callActivityOnCreate
09-03 15:57:17.718 29107 29107 D ActivityThread: add activity client record, r= ActivityRecord{77de1be token=android.os.BinderProxy@2394a9a {cgeo.geocaching/cgeo.geocaching.settings.SettingsActivity}} token= android.os.BinderProxy@2394a9a
09-03 15:57:32.786 29307 29307 D ActivityThread: Attach thread to application
09-03 15:57:32.852 29307 29307 V ActivityThread: callActivityOnCreate
09-03 15:57:32.924 29337 29337 D ActivityThread: Attach thread to application
09-03 15:57:32.990 29337 29337 V ActivityThread: callActivityOnCreate
09-03 15:57:33.055 29337 29337 D ActivityThread: add activity client record, r= ActivityRecord{b5e8d95 token=android.os.BinderProxy@4d08507 {cgeo.geocaching/cgeo.geocaching.MainActivity}} token= android.os.BinderProxy@4d08507
09-03 15:57:36.991 29337 29337 V ActivityThread: callActivityOnCreate
09-03 15:57:37.032 29337 29337 D ActivityThread: add activity client record, r= ActivityRecord{e99dff1 token=android.os.BinderProxy@b26ada7 {cgeo.geocaching/cgeo.geocaching.maps.mapsforge.v6.NewMap}} token= android.os.BinderProxy@b26ada7
09-03 15:58:13.680 29337 29337 V ActivityThread: callActivityOnCreate
09-03 15:58:13.720 29337 29337 D ActivityThread: add activity client record, r= ActivityRecord{ffcfba1 token=android.os.BinderProxy@61fe2 {cgeo.geocaching/cgeo.geocaching.settings.MapDownloadSelectorActivity}} token= android.os.BinderProxy@61fe2
09-03 16:00:04.536 29337 29337 D ActivityThread: Remove activity client record, r= ActivityRecord{ffcfba1 token=android.os.BinderProxy@61fe2 {cgeo.geocaching/cgeo.geocaching.settings.MapDownloadSelectorActivity}} token= android.os.BinderProxy@61fe2
09-03 16:00:05.705 29337 29337 D ActivityThread: Remove activity client record, r= ActivityRecord{e99dff1 token=android.os.BinderProxy@b26ada7 {cgeo.geocaching/cgeo.geocaching.maps.mapsforge.v6.NewMap}} token= android.os.BinderProxy@b26ada7
09-03 16:00:06.972 29337 29337 V ActivityThread: callActivityOnCreate
09-03 16:00:06.987 29337 29337 D ActivityThread: add activity client record, r= ActivityRecord{9253fa3 token=android.os.BinderProxy@c31b91f {cgeo.geocaching/cgeo.geocaching.AboutActivity}} token= android.os.BinderProxy@c31b91f
--------- beginning of main
09-03 16:00:41.169 29337 29380 D mali_winsys: EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
09-03 16:00:41.185 29337 29337 I HwViewRootImpl: removeInvalidNode all the node in jank list is out of time
09-03 16:00:41.502 29337 29380 W libEGL  : EGLNativeWindowType 0x77211b5650 disconnect failed
09-03 16:00:41.509 29337 29337 D ActivityThread: Remove activity client record, r= ActivityRecord{9253fa3 token=android.os.BinderProxy@c31b91f {cgeo.geocaching/cgeo.geocaching.AboutActivity}} token= android.os.BinderProxy@c31b91f
09-03 16:00:44.634 29337 29380 W libEGL  : EGLNativeWindowType 0x77211b9390 disconnect failed
09-03 16:00:44.642 29337 29337 D ActivityThread: Remove activity client record, r= ActivityRecord{b5e8d95 token=android.os.BinderProxy@4d08507 {cgeo.geocaching/cgeo.geocaching.MainActivity}} token= android.os.BinderProxy@4d08507
09-03 16:00:45.214 29337 29365 D ZrHung.AppEyeUiProbe: not watching, wait.
09-03 16:03:08.415 29337 29337 W ActivityThread: handleWindowVisibility: no activity for token android.os.BinderProxy@bec8daf
09-03 16:03:08.419 29337 29365 D ZrHung.AppEyeUiProbe: restart watching
09-03 16:03:08.430 29337 29337 V ActivityThread: callActivityOnCreate
09-03 16:03:08.437 29337 29337 I ToolbarWidgetWrapper: Progress display unsupported
09-03 16:03:08.458 29337 29337 D ActivityThread: add activity client record, r= ActivityRecord{d55a77b token=android.os.BinderProxy@bec8daf {cgeo.geocaching/cgeo.geocaching.MainActivity}} token= android.os.BinderProxy@bec8daf
09-03 16:03:08.478 29337 30011 D HiTouch_PressGestureDetector: onAttached, package=cgeo.geocaching, windowType=1, mHiTouchRestricted=false
09-03 16:03:08.486 29337 29380 D mali_winsys: EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
09-03 16:03:08.508 29337 29337 I HwViewRootImpl: removeInvalidNode all the node in jank list is out of time
09-03 16:03:09.535 29337 29337 W Settings: Setting device_provisioned has moved from android.provider.Settings.Secure to android.provider.Settings.Global.
09-03 16:03:09.536 29337 29337 V HiTouch_HiTouchSensor: User setup is finished.
09-03 16:03:09.544 29337 29337 V AudioManager: querySoundEffectsEnabled...
09-03 16:03:09.568 29337 29380 D mali_winsys: EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
09-03 16:03:10.323 29337 29337 V AudioManager: querySoundEffectsEnabled...
09-03 16:03:10.369 29337 29337 W ActivityThread: handleWindowVisibility: no activity for token android.os.BinderProxy@c74305d
09-03 16:03:10.373 29337 29337 V ActivityThread: callActivityOnCreate
09-03 16:03:10.380 29337 29337 I ToolbarWidgetWrapper: Progress display unsupported
09-03 16:03:10.387 29337 29337 D ActivityThread: add activity client record, r= ActivityRecord{9c3aca6 token=android.os.BinderProxy@c74305d {cgeo.geocaching/cgeo.geocaching.AboutActivity}} token= android.os.BinderProxy@c74305d
09-03 16:03:10.402 29337 30031 D HiTouch_PressGestureDetector: onAttached, package=cgeo.geocaching, windowType=1, mHiTouchRestricted=false
09-03 16:03:10.457 29337 29337 W cgeo.geocaching: type=1400 audit(0.0:1558038): avc: granted { getattr } for pid=29337 name="/" dev="sdcardfs" ino=5 scontext=u:r:untrusted_app:s0:c162,c256,c512,c768 tcontext=u:object_r:sdcardfs:s0 tclass=filesystem
09-03 16:03:10.484 29337 29380 D mali_winsys: EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
09-03 16:03:10.667 29337 29380 W libEGL  : EGLNativeWindowType 0x7796c58650 disconnect failed
09-03 16:03:10.667 29337 29380 D OpenGLRenderer: endAllActiveAnimators on 0x76f5d8da00 (MenuPopupWindow$MenuDropDownListView) with handle 0x77213fc4e0
09-03 16:03:10.843 29337 29380 W libEGL  : EGLNativeWindowType 0x77315f3010 disconnect failed
09-03 16:03:11.823 29337 29337 W Settings: Setting device_provisioned has moved from android.provider.Settings.Secure to android.provider.Settings.Global.
09-03 16:03:11.823 29337 29337 V HiTouch_HiTouchSensor: User setup is finished.
09-03 16:03:11.869 29337 29337 W HiTouch_PressGestureDetector: Touch pointer move a lot. The moving distance of X is:77.5, limit is:60The moving distance of Y is:2.5, limit is:60
09-03 16:03:12.505 29337 29337 W HiTouch_PressGestureDetector: Touch pointer move a lot. The moving distance of X is:85.7088, limit is:60The moving distance of Y is:3.2852783, limit is:60
09-03 16:03:13.910 29337 29337 W HiTouch_PressGestureDetector: Touch pointer move a lot. The moving distance of X is:67.9397, limit is:60The moving distance of Y is:14.855469, limit is:60
09-03 16:03:14.597 29337 29337 W cgeo.geocaching: type=1400 audit(0.0:1558042): avc: granted { getattr } for pid=29337 name="/" dev="sdcardfs" ino=5 scontext=u:r:untrusted_app:s0:c162,c256,c512,c768 tcontext=u:object_r:sdcardfs:s0 tclass=filesystem
09-03 16:03:14.601 29337 29337 W cgeo.geocaching: type=1400 audit(0.0:1558043): avc: granted { getattr } for pid=29337 name="/" dev="sdcardfs" ino=5 scontext=u:r:untrusted_app:s0:c162,c256,c512,c768 tcontext=u:object_r:sdcardfs:s0 tclass=filesystem
09-03 16:03:15.315 29337 29337 W HiTouch_PressGestureDetector: Touch pointer move a lot. The moving distance of X is:82.41174, limit is:60The moving distance of Y is:6.470581, limit is:60
09-03 16:03:20.969 29337 29337 W HiTouch_PressGestureDetector: Touch pointer move a lot. The moving distance of X is:14.186279, limit is:60The moving distance of Y is:88.977905, limit is:60
09-03 16:03:21.839 29337 29337 W HiTouch_PressGestureDetector: Touch pointer move a lot. The moving distance of X is:4.6016235, limit is:60The moving distance of Y is:67.04846, limit is:60
09-03 16:03:21.908 29337 29337 D OverScrollerOptimization: fling time is flingTime = 2.9829663767203614 velocity = -9693
09-03 16:03:21.908 29337 29337 D OverScrollerOptimization: fling time is flingTime = 2.9829663767203614 velocity = -9693
09-03 16:03:22.525 29337 29337 W HiTouch_PressGestureDetector: Touch pointer move a lot. The moving distance of X is:6.161865, limit is:60The moving distance of Y is:98.198, limit is:60
09-03 16:03:24.318 29337 29337 V AudioManager: querySoundEffectsEnabled...
09-03 16:03:24.379 29337 30044 D HiTouch_PressGestureDetector: onAttached, package=cgeo.geocaching, windowType=2, mHiTouchRestricted=false
09-03 16:03:24.404 29337 29380 D mali_winsys: EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
09-03 16:03:24.422 29337 29337 I HwViewRootImpl: removeInvalidNode all the node in jank list is out of time
09-03 16:03:27.430 29337 29337 W Settings: Setting device_provisioned has moved from android.provider.Settings.Secure to android.provider.Settings.Global.
09-03 16:03:27.431 29337 29337 V HiTouch_HiTouchSensor: User setup is finished.
09-03 16:03:27.497 29337 29337 V AudioManager: querySoundEffectsEnabled...
09-03 16:03:27.533 30047 30047 W logcat  : type=1400 audit(0.0:1558046): avc: granted { read } for pid=30047 name="logfiles" dev="sdcardfs" ino=51887 scontext=u:r:untrusted_app:s0:c162,c256,c512,c768 tcontext=u:object_r:sdcardfs:s0 tclass=dir
09-03 16:03:27.533 30047 30047 W logcat  : type=1400 audit(0.0:1558047): avc: granted { read open } for pid=30047 path="/storage/emulated/0/cgeo/logfiles" dev="sdcardfs" ino=51887 scontext=u:r:untrusted_app:s0:c162,c256,c512,c768 tcontext=u:object_r:sdcardfs:s0 tclass=dir
09-03 16:03:27.533 30047 30047 W logcat  : type=1400 audit(0.0:1558048): avc: granted { write } for pid=30047 name="logfiles" dev="sdcardfs" ino=51887 scontext=u:r:untrusted_app:s0:c162,c256,c512,c768 tcontext=u:object_r:sdcardfs:s0 tclass=dir
09-03 16:03:27.533 30047 30047 W logcat  : type=1400 audit(0.0:1558049): avc: granted { add_name } for pid=30047 name="logcat_2020-09-03_16-03.txt" scontext=u:r:untrusted_app:s0:c162,c256,c512,c768 tcontext=u:object_r:sdcardfs:s0 tclass=dir
09-03 16:03:27.537 30047 30047 W logcat  : type=1400 audit(0.0:1558050): avc: granted { create } for pid=30047 name="logcat_2020-09-03_16-03.txt" scontext=u:r:untrusted_app:s0:c162,c256,c512,c768 tcontext=u:object_r:sdcardfs:s0:c162,c256,c512,c768 tclass=file
09-03 16:03:27.537 30047 30047 W logcat  : type=1400 audit(0.0:1558051): avc: granted { append open } for pid=30047 path="/storage/emulated/0/cgeo/logfiles/logcat_2020-09-03_16-03.txt" dev="sdcardfs" ino=208050 scontext=u:r:untrusted_app:s0:c162,c256,c512,c768 tcontext=u:object_r:sdcardfs:s0 tclass=file
09-03 16:03:27.548 29337 29380 W libEGL  : EGLNativeWindowType 0x77314457d0 disconnect failed
09-03 16:03:27.548 29337 29380 D OpenGLRenderer: endAllActiveAnimators on 0x77020d9d00 (RippleDrawable) with handle 0x7796ce6420
```

**Comment by Lineflyer** [comment] 2020-09-04 19:21
Can you pleae provide your system information from About c:geo - system to see your storage config.

**Comment by bfankd** [comment] 2020-09-05 13:00
--- System information ---
Device: CLT-L29 (CLT-L29, HUAWEI)
Android version: 10
Android build: CLT-L29 10.0.0.171(C432E3R1P3)
c:geo version: 2020.09.02-RC
Google Play services: enabled - 20.30.19 (120408-326531024)
Low power mode: inactive
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: rotation vector
Hide caches: own/found 
Hide waypoints: original 
HW acceleration: enabled (default state)
System language: de_CH
System date format: dd.MM.yy
Debug mode active: no
System internal c:geo dir: /data/user/0/cgeo.geocaching (68.9 GB free) internal
User storage c:geo dir: /storage/emulated/0/cgeo (68.9 GB free) external non-removable
Geocache data: /storage/emulated/0/Android/data/cgeo.geocaching/files/GeocacheData (68.9 GB free) external non-removable
Database: /storage/emulated/0/Android/data/cgeo.geocaching/files/databases/data (41.2 MB) on user storage
Fine location permission: granted
Write external storage permission: granted
Geocaching sites enabled:
geocaching.com: Logged in (Anmeldung OK) / PREMIUM
Geocaching.com date format: dd MMM yy
Installed c:geo plugins: none
BRouter connection available: true
--- End of system information ---

**Comment by moving-bits** [comment] 2020-09-06 20:24
I can't find any reason why the download seems to fail. :-(

But at least for the "cannot find the file" problem there is an solution since #8952, which will be included in the upcoming release version (and is already available in the nightlies). The map file being downloaded will be visible in the public "Download" directory.

**Comment by bfankd** [comment] 2020-09-07 04:58
Hmm- I also can't find any hidden file.

Within my setup CGEO uses a custom path for offline maps:
/storage/emulated/0/Geocaching/Maps
/storage/emulated/0/Geocaching/Themes

A target "maps" as shown in https://github.com/cgeo/cgeo/pull/8952 does not exist in "/storage/emulated/0/cgeo". Should it?

**Comment by moving-bits** [comment] 2020-09-07 09:14
> Hmm- I also can't find any hidden file.

It's not actually hidden, but stored in an system-internal directory (internal cache directory) - don't know, if this is visible to the end-user at all.

This is before #8952 - the  nightly versions since then use the public "Download" dir.

> Within my setup CGEO uses a custom path for offline maps:
> /storage/emulated/0/Geocaching/Maps
> /storage/emulated/0/Geocaching/Themes
> 
> A target "maps" as shown in #8952 does not exist in "/storage/emulated/0/cgeo". Should it?

No need for it, "maps" was just an example. The map downloader uses the map dir you have configured, "Maps" in your case.

**Comment by bfankd** [comment] 2020-09-08 07:49
Update:
Today there is no problem at all downloading maps. Fast and reliable.
Starting the download through "Einstellungen/Karte/Offflinekarte herunterladen":
- Disclaimer about download in the background
- select map
- download ...
- creating/copying map
- done - success message

Starting the download through Live-Karte Map Icon/<Offlinekarte herunterladen>
- select map
- download ...
- creating/copying map
- done
- success - no message

To me the problem is gone. Mapserver problem? Who knows...

**Comment by moving-bits** [comment] 2020-09-11 20:04
@Lineflyer 
Anything else like this on support, or can we close this issue?

**Comment by bfankd** [comment] 2020-09-13 16:11
I couldn't reproduce the issue on 2.4GHz Wifi but on 5 GHz.
So it's probably a problem within my network. Grmpf.
Thanks for your time

**Closed** 2020-09-13 16:18 UTC
Labels: Bug, Unverified
