### ISSUE TITLE
Proximity alarms: Make them work with display off

### ISSUE THREAD

**Issue by MagpieFourtyTwo** [cgeo/cgeo#15708] opened 2024-05-07 23:28 UTC
### Tell us your idea!

When caching by bike, you also have to struggle with the phone's battery, obviously.
And as display is *the* main battery eater, best bet is to switch if off as soon (and long) as possible.
But with display off, it's kind of hard to not miss the next cache.  Or stage.
Being the smart kid that I am, thought, just activate proximity notifications and you're on the safe side.
Big miss.  No signal at all.  Of course missed the next one and had to head back to get it.  :(  ;)

### What solution would you suggest?

Keep track of GPS position even if display is off (others do so anyway, thus energy needs should be negligible) and let alarms ring, even with display off,

Moreover I would suggest to play ``Specific waypoint proximity notification``, too, if you approach current routing target resp. next routing point (like navigation devices do for decades ;) ).

**Comment by moving-bits** [comment] 2024-05-10 20:26
Duplicate of #15193, therefore closing here (have copied your comment to the other issue)

**Closed by moving-bits** 2024-05-10 20:26 UTC
Labels: Feature Request, Duplicate
