### ISSUE TITLE
Downloading caches gets the wrong images associated with a cache.

### ISSUE THREAD

**Issue by dcj99b** [cgeo/cgeo#4598] opened 2015-01-08 11:17 UTC
Hi :  Android 4.1.1 c:gep 2014.12.22
I did a refresh of 200 caches two days ago and when out in the field, found the wrong images at several caches. I came home, cleared all caches and files from sdcard/.cgeo.
Then reloaded ti 200 caches, and still wrong pictures.  I deleted as much as possible and cleared as much caching as I could and loaded one cache and it loaded the images from another nearby cache.
Then I deleted all again and this time it loaded one correct image.
So, it could be local caching troubles, but if anyone else see it, please report it.

**Comment by Lineflyer** [comment] 2015-01-08 11:20
Duplicate of #4570 

Will be solved in the next release of c:geo.
Thanks for your report anyway.

**Closed by Lineflyer** 2015-01-08 11:20 UTC
