### ISSUE TITLE
ForegroundServiceStartNotAllowedException

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#13666] opened 2022-11-14 20:01 UTC
### Describe your problem!

From Google Play for last 2022.11.05-RC RC and current release 2022.11.13 
(According to Google Play it did not happen with earlier versions).

59 users affected, 108 reports

### How to reproduce?

Unclear

### Actual result after these steps?

```
Exception java.lang.RuntimeException:
  at android.app.ActivityThread.handleReceiver (ActivityThread.java:4770)
  at android.app.ActivityThread.access$1800 (ActivityThread.java:310)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:2292)
  at android.os.Handler.dispatchMessage (Handler.java:106)
  at android.os.Looper.loopOnce (Looper.java:226)
  at android.os.Looper.loop (Looper.java:313)
  at android.app.ActivityThread.main (ActivityThread.java:8669)
  at java.lang.reflect.Method.invoke
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:571)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1135)
Caused by android.app.ForegroundServiceStartNotAllowedException:
  at android.app.ForegroundServiceStartNotAllowedException$1.createFromParcel (ForegroundServiceStartNotAllowedException.java:54)
  at android.app.ForegroundServiceStartNotAllowedException$1.createFromParcel (ForegroundServiceStartNotAllowedException.java:50)
  at android.os.Parcel.readParcelable (Parcel.java:3346)
  at android.os.Parcel.createExceptionOrNull (Parcel.java:2433)
  at android.os.Parcel.createException (Parcel.java:2422)
  at android.os.Parcel.readException (Parcel.java:2405)
  at android.os.Parcel.readException (Parcel.java:2347)
  at android.app.IActivityManager$Stub$Proxy.startService (IActivityManager.java:6968)
  at android.app.ContextImpl.startServiceCommon (ContextImpl.java:1927)
  at android.app.ContextImpl.startForegroundService (ContextImpl.java:1893)
  at android.content.ContextWrapper.startForegroundService (ContextWrapper.java:798)
  at android.content.ContextWrapper.startForegroundService (ContextWrapper.java:798)
  at androidx.core.content.ContextCompat$Api26Impl.startForegroundService (ContextCompat.java:931)
  at androidx.core.content.ContextCompat.startForegroundService (ContextCompat.java:703)
  at cgeo.geocaching.downloader.DownloaderUtils.startReceive (DownloaderUtils.java:426)
  at cgeo.geocaching.downloader.DownloadNotificationReceiver.onReceive (DownloadNotificationReceiver.java:34)
  at android.app.ActivityThread.handleReceiver (ActivityThread.java:4761)
Caused by android.os.RemoteException: Remote stack trace:
  at com.android.server.am.ActiveServices.startServiceLocked (ActiveServices.java:771)
  at com.android.server.am.ActiveServices.startServiceLocked (ActiveServices.java:679)
  at com.android.server.am.ActivityManagerService.startService (ActivityManagerService.java:14099)
  at android.app.IActivityManager$Stub.onTransact (IActivityManager.java:2960)
  at com.android.server.am.ActivityManagerService.onTransact (ActivityManagerService.java:3036)
```

### Expected result after these steps?

No exception

### Reproducible

Unclear

### c:geo Version

2022.11.13

**Comment by moving-bits** [comment] 2022-11-22 14:26
More than 500 occurrences for current release 2022.11.13 meanwhile, in less than ten days. Happens in `DownloaderUtils.startReceive()`

@fm-sys: Concluding from the amount of occurrences I guess this method is also involved for downloading caches? (Cannot check in code currently.) Then it might be related to / the cause for #13408. Can you have a look at it (as time permits)?

**Comment by fm-sys** [comment] 2022-11-23 11:02
I will have a look at it this evening...

**Comment by fm-sys** [comment] 2022-11-23 19:50
Unfortunately I wont be able to work on this, as I'm not familiar enough with the map downloader codebase and this looks like a larger task. I'm on a quite limited time budget currently :-/

Implementation note:
Probably everything that today happens inside `DownloadNotificationReceiver`, needs to be moved to `onHandleIntent()` of `ReceiveDownloadService`. However, I was not able to get it working on a quick try.

**Comment by moving-bits** [comment] 2022-11-25 21:58
I'm not convinced that we are using notification trampolines here: To my understanding, a "notification trampoline" is a notification, which starts a new activity when you tap on it. AFAIK our notifications are "read-only", so nothing happens if you tap on them

Also, from the description in https://developer.android.com/about/versions/12/behavior-changes-12#notification-trampolines, the error message should be something like "Indirect notification activity start (trampoline) from PACKAGE_NAME, \
this should be avoided for performance reasons.", which is not the case here.

I'll try to investigate further...

**Comment by moving-bits** [comment] 2022-11-25 22:09
Found a way to reproduce the error:
- start downloading a map
- put c:geo in the background
- wait until download finishes

c:geo won't open the "receiving xxx" notification, but prints an error like this in LogCat:
```
java.lang.RuntimeException: Unable to start receiver cgeo.geocaching.downloader.DownloadNotificationReceiver: android.app.ForegroundServiceStartNotAllowedException: startForegroundService() not allowed due to mAllowStartForeground false: service cgeo.geocaching/.downloader.ReceiveDownloadService
	at android.app.ActivityThread.handleReceiver(ActivityThread.java:4317)
	at android.app.ActivityThread.access$1600(ActivityThread.java:247)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2064)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7839)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
Caused by: android.app.ForegroundServiceStartNotAllowedException: startForegroundService() not allowed due to mAllowStartForeground false: service cgeo.geocaching/.downloader.ReceiveDownloadService
	at android.app.ForegroundServiceStartNotAllowedException$1.createFromParcel(ForegroundServiceStartNotAllowedException.java:54)
	at android.app.ForegroundServiceStartNotAllowedException$1.createFromParcel(ForegroundServiceStartNotAllowedException.java:50)
	at android.os.Parcel.readParcelable(Parcel.java:3333)
	at android.os.Parcel.createExceptionOrNull(Parcel.java:2420)
	at android.os.Parcel.createException(Parcel.java:2409)
	at android.os.Parcel.readException(Parcel.java:2392)
	at android.os.Parcel.readException(Parcel.java:2334)
	at android.app.IActivityManager$Stub$Proxy.startService(IActivityManager.java:5971)
	at java.lang.reflect.Method.invoke(Native Method)
	at leakcanary.ServiceWatcher$install$4$2.invoke(ServiceWatcher.kt:93)
	at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
	at $Proxy3.startService(Unknown Source)
	at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1847)
	at android.app.ContextImpl.startForegroundService(ContextImpl.java:1823)
	at android.content.ContextWrapper.startForegroundService(ContextWrapper.java:779)
	at android.content.ContextWrapper.startForegroundService(ContextWrapper.java:779)
	at androidx.core.content.ContextCompat$Api26Impl.startForegroundService(ContextCompat.java:931)
	at androidx.core.content.ContextCompat.startForegroundService(ContextCompat.java:703)
	at cgeo.geocaching.downloader.DownloaderUtils.startReceive(DownloaderUtils.java:426)
	at cgeo.geocaching.downloader.DownloadNotificationReceiver.onReceive(DownloadNotificationReceiver.java:34)
	at android.app.ActivityThread.handleReceiver(ActivityThread.java:4308)
	at android.app.ActivityThread.access$1600(ActivityThread.java:247) 
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2064) 
	at android.os.Handler.dispatchMessage(Handler.java:106) 
	at android.os.Looper.loopOnce(Looper.java:201) 
	at android.os.Looper.loop(Looper.java:288) 
	at android.app.ActivityThread.main(ActivityThread.java:7839) 
	at java.lang.reflect.Method.invoke(Native Method) 
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548) 
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003) 
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.am.ActiveServices.startServiceLocked(ActiveServices.java:691)
	at com.android.server.am.ActiveServices.startServiceLocked(ActiveServices.java:616)
	at com.android.server.am.ActivityManagerService.startService(ActivityManagerService.java:11839)
	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:2519)
	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2498)
```

**Comment by moving-bits** [comment] 2022-11-26 00:07
I trying to replace using `ForegroundService` by `WorkManager` and `OneTimeWorkRequest`. The problem described in #13606 is getting worse, and is especially nasty if you start working with components you haven't worked with so far:
- no class of package `androidx.work` is detected (all marked in red),
- no auto expansion of any of those classes or its members,
- no help
- no jump to source,
- I even have to enter all import statements for those classes manually.

It basically reduces Android Studio to something only slightly more comfortable than Notepad (for those classes).

What I've tried so far:
- resync Gradle
- invalidate caches
- re-import project
- restart of IDE
- a complete cycle of  uninstall + remove `.gradle`, `.m2`, `JetBrains`, `Android` + clean reinstall
- "Repair IDE" (which also invalidates caches in several levels of escalation)
- even removed my local clone of c:geo and re-cloned from the server

But to no avail. I'll call it a day for now... 😠

**Comment by moving-bits** [comment] 2022-11-26 17:16
@fm-sys 
I created an implementation for using `Worker` instead of `ForegroundService` for receiving downloaded files. I did quick tests with both API 25 and API 33, but it would be nice if you could do a review, see PR #13733.

**Comment by eddiemuc** [comment] 2023-01-29 14:48
SInce the mentioned PR #13733 is merged: can this issue be closed?

**Comment by Lineflyer** [comment] 2023-01-31 09:20
I will monitor appearance of this issue with our new RC 2023.01.30-RC next days.

**Comment by Lineflyer** [comment] 2023-01-31 12:17
Trying to paste a permalink to the crash report filtered for 2023.01.30-RC (for those having access) to crosscheck:
https://play.google.com/console/u/0/developers/7945466068179931672/app/4975240647192321833/vitals/crashes/346e34fa3a467194a2c77a7b3bf83a2f/details?installedFrom=PLAY_STORE&days=28&versionCode=20230129

**Comment by moving-bits** [comment] 2023-02-04 19:49
No occurrences so far for current beta, let's keep fingers crossed...

**Comment by moving-bits** [comment] 2023-02-11 11:06
No new occurrences for both release candidates, so let's close here.

**Closed** 2023-02-11 11:08 UTC
Labels: Bug, Google Play or Beta feedback
