### ISSUE TITLE
Feature request: Auto Download caches and auto send all offline logs

### ISSUE THREAD

**Issue by alex9099** [cgeo/cgeo#5842] opened 2016-07-19 14:20 UTC
Dont know how to add tags but... this is a feature request:

Add an option to download X caches on Y location (it can be current location or any other).
Instead of being opening 20 by 20 caches have an automated process to do that and store offline then.

Other feature request would be send all offline logs instead of one by one, some guy from support@cgeo.com sayed that this already exists on issue tracker, but i didnt find it

**Comment by GodfatherThe** [comment] 2016-07-25 10:32
Send all offline logs is must have feature for me!  Cause I'm travelling now and don't have internet often, but I log in dozens of caches.

**Comment by rsudev** [comment] 2016-08-02 21:05
@GodfatherThe What platform do you use? Uploading field-notes is no option for you?

**Comment by rsudev** [comment] 2016-08-02 21:15
For the uploading of offline logs see: #1786.

**Comment by alex9099** [comment] 2016-08-02 22:08
Yup is exactly that, so this issue is duplicated

**Comment by Lineflyer** [comment] 2021-12-12 11:31
Duplicate of #1786

**Closed by Lineflyer** 2021-12-12 11:31 UTC
Labels: Feature Request
