### ISSUE TITLE
'Star' characters are displayed with odd colours/backgrounds

### ISSUE THREAD

**Issue by alan666notb** [cgeo/cgeo#7306] opened 2019-02-18 14:56 UTC
I see some strange font issues with the latest beta release....

##### Detailed steps causing the problem:
- load GC6YWFT  [Church Micro 10381...Sanderstead - URC]
- scroll to bottom of cache page and observe the 'star' characters above and below the "For full information ....." text.

##### Actual behavior after performing these steps:
'Stars' are shown as red font on black background above the text and blue font on black background below the text.

##### Expected behavior after performing these steps:
On the previous release (and on website), all of the stars were red font on white background.

##### Version of c:geo used:
2019.02.17-RC

##### Is the problem reproducible for you?
Yes

**Comment by alan666notb** [comment] 2019-02-18 14:59
Screen shots ....

Old
![screenshot_old](https://user-images.githubusercontent.com/7459480/52959089-53274a80-338d-11e9-92cf-e18ea4d1d7d5.png)

New
![screenshot_new](https://user-images.githubusercontent.com/7459480/52958968-1d826180-338d-11e9-855d-77590d20f5c5.jpg)

**Comment by Lineflyer** [comment] 2019-02-18 15:06
This is IMHO caused by the new feature for contrast optimization to improve bad colored text on our black background.

I fear the implementation was not yet really tested with white background.

**Comment by SammysHP** [comment] 2019-02-18 17:07
It behaves exactly as intended. Fully saturated blue and red are "hard to read on white background", thus they get a dark background. I already mentioned these problems back then.

**Comment by githubber2222** [comment] 2019-02-18 17:33
How would the new look be easier to read? Maybe my eyes are different but the old one is clearly better.
Also, the text above the 'blue stars' is blue as well but no black background.

Lastly, the listing has the bottom row of stars in red, not blue.

@SammysHP your response looks like a lame excuse here, sorry. You intended that red turns blue? And visually same shade of blue above has NO black background?

**Comment by SammysHP** [comment] 2019-02-18 18:03
Oh, I haven't noticed that originally both rows had the same color.

Different parsing for visually the same color is possible because not all ways of changing the color are handled.

**Comment by okainov** [comment] 2019-02-22 15:56
Seems interesting (changing the foreground color), thia should not happen. may be some issue in  source cache formatting... I can try to take a look and debug a bit when I'm back from my trip

Upd: tried to open the cache, but it's premium-only, so I don't have access and cannot check it. If you find any other cache with such issue, please report.

**Comment by alan666notb** [comment] 2019-02-22 16:03
Here's a non-premium church-micro that shows the same problem: GC660KN

Could the whole 'contrast optimisation' thing not be turned off when using the light scheme?

**Comment by okainov** [comment] 2019-02-22 16:08
Thanks for the other cache, will take a look in March.

About disabling for white scheme - it's not a problem from technical point of view, when I was implementing better contrast detection, I was keeping the same behavior as before (which was applicable for both themes). If @rsudev @Lineflyer and others are ok with removing this logic for white theme at all, we can disable it. However, I believe, it's a different request, the main issue here is unexpected change of foreground color which we need to investigate anyway

**Comment by okainov** [comment] 2019-03-01 19:09
Just took a bit more detailed look, it seems very confusing, so far no ideas.

Source description string:

    <font color="blue">See also the Church Micro <a href="http://www.15ddv.me.uk/geo/cm/cm.html">Statistics</a> and <a href="http://www.15ddv.me.uk/geo/cm/index.html">Home</a> pages for further information about the series.<br /> <font color="red">****************** *******************</font></font>

It's definitely bad practice to make tags like this, but seems valid anyway, shouldn't be an issue.

Let's convert it to Spannable and then back:
`Html.toHtml(Html.fromHtml(descriptionString, new HtmlImage(cache.getGeocode(), true, false, descriptionView, false), unknownTagsHandler)).toString()`

    <span style="color:#0000FF;">See also the Church Micro </span><a href="http://www.15ddv.me.uk/geo/cm/cm.html"><span style="color:#0000FF;">Statistics</span></a><span style="color:#0000FF;"> and </span><a href="http://www.15ddv.me.uk/geo/cm/index.html"><span style="color:#0000FF;">Home</span></a><span style="color:#0000FF;"> pages for further information about the series.</span><br>
<span style="color:#FF0000;"><span style="color:#0000FF;">****************** *******************</span></span>

So the inner `red` span switched the place and became outer span, so stars are "blue" now.

**Comment by alan666notb** [comment] 2019-04-14 15:56
Is there any movement on this issue?
It makes some caches pages look very odd when viewed using the white scheme.

E.g. GC8675T - why are Red & Green given a black background while Purple and Blue are not?

Please at least just disable it on the white scheme, or give us the option to do so.

**Comment by Lineflyer** [comment] 2019-04-15 11:04
Reading again through this issue and thinking about the original reason for implementing the contrast optimization in the past, it was IMHO mainly to get the content optimized to our black scheme.

While applying such kind of thing to our white scheme might make sense to gain better readability, it might be going a step too far here.
As most owners optimize or style their listing to already fit on the default white background, I tend to agree, that we should just disable our feature on white scheme.

One thing however comes to my mind, where this can still be a problem:
If an owner applied an own background color/picture and modified the colors to make it readable. When e.g. an owner explicitly give the listing a black background and therefore uses white color, disabling our feature would lead to white on white, wouldn't it?

**Comment by bekuno** [comment] 2020-11-06 12:48
In both situations (here and in #9353) we have nested font tags.

Eg. 
~~~
    <font color="black">
      Von der 
      <font color="green">1.Bonusinfo</font> 
      ....
    </font>
~~~
or
~~~
<font color="blue">See also the Church Micro 
  ....
  pages for further information about the series.<br>
  <font color="red">****************** *******************</font>
</font>
~~~

**Comment by okainov** [comment] 2020-11-07 18:11
@bekuno yeah, which cannot be parsed properly by `Html.fromHtml` as noted above :(

**Comment by alan666notb** [comment] 2021-07-26 16:51
Hi there,

I see that this issue seems to have been fixed now.
I'm running 2021.07.17-RC2, but I don't know when it was fixed, only just noticed.

Is that deliberate, or the result of another change.

**Comment by moving-bits** [comment] 2021-07-26 17:44
I guess there has been no specific work on this lately, but our ongoing major rework on UI and its technical foundation may have positiv side-effects on this as well. Those changes are released in our betas currently, but not yet in production release version.

**Comment by fm-sys** [comment] 2021-07-26 19:40
I can confirm, that it is fixed. So let's close here...

**Closed by fm-sys** 2021-07-26 19:40 UTC
Labels: Feedback required, Frontend Design
