### ISSUE TITLE
Suggestion: DNF smiley on the map

### ISSUE THREAD

**Issue by jelleruben** [cgeo/cgeo#7140] opened 2018-09-18 13:44 UTC
Hello, 

c:geo is realy great app. But I have some suggestion.

On the map can you see if you found a cache. But is it possible to add the DNF smiley too, so I can see on the map which I didn't found.

**Comment by SammysHP** [comment] 2018-09-18 18:11
Duplicate of #6614.

**Closed by SammysHP** 2018-09-18 18:11 UTC
