### ISSUE TITLE
Unsaved solved mysteries do not show final flag

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#9875] opened 2021-01-26 20:59 UTC
Report on support mail (confirmed by screenshots, but not yet retested by myself):

When using the live map (Google) the solved mysteries are shown are their real final coordinates (as also before) but since 2021.01.16 the final icon (red flag) is no longer shown:

cgeo:
![grafik](https://user-images.githubusercontent.com/949669/105904534-88308300-6021-11eb-9f13-d352f7c65d6a.png)

Geocaching app:
![grafik](https://user-images.githubusercontent.com/949669/105904583-9c748000-6021-11eb-99be-9f12e394d019.png)

**Comment by MagpieFourtyTwo** [comment] 2021-01-28 23:30
Can confirm for OSM: Stumbled upon some unsaved mysteries today whose map icon did not show any indicator at all - until I opened their popup. To be honest, I do not really remember if I opened all of these listings completely, but afterwards, the ``Changed Coords`` and ``Has PN`` indicators were suddenly there.

But did not really think about it, cause I thought, it has always been this way, anyway ...

**Comment by Lineflyer** [comment] 2021-01-29 11:58
More users of the beta version with this problem and the problem, that found caches are showing not found (happens for unsaved caches).
It seems we miss some information when loading from the live map API or the live map on gc.com has a problem.

**Comment by MagpieFourtyTwo** [comment] 2021-01-29 16:16
Life map?  c:geo really loads caches around a coordinate via gc.com's Life map ...?
Ok, it may be unrelated, but ... on opening gc.com's Life map I observed significantly higher CPU load and longer load times,
way higher and longer than a few weeks ago.  So the missing stuff may perhaps be related to time outs ...?

**Comment by Lineflyer** [comment] 2021-01-30 12:41
Confirmed with 2021.01.30-NB

I have seen a unsaved mystery on my live map. It was shown at the modified final coords but the final flag overlay not being shown until I loaded it.

**Comment by Lineflyer** [comment] 2021-01-30 12:42
> Live map? c:geo really loads caches around a coordinate via gc.com's Live map ...?

Not as you might think. Lets say we use the same data source as the live map internally uses. But loading the whole framework of tiles and other stuff is not involved...should not be slow.

**Comment by Lineflyer** [comment] 2021-01-30 18:55
@fm-sys 
I was finally able to (almost) reproduce this issue and it might be related to your changes on popup...or not. Not sure.

- Open map with found solved mysteries (not saved on device)
- Initially all looks good (found smiley shown, final flag shown)
- Open the popup for such a cache
- The icon in popup also shows smiley and final flag (new feature implemented by @fm-sys )
- After closing the popup however the final flag vanishes

Sadly it does not happen each time but usually after moving the map around a bit and then trying the same again.

**Comment by fm-sys** [comment] 2021-01-30 21:16
Indeed, something seams to be very buggy. While testing, not only the final flag, but also list markers and whole caches where vanishing and reappearing. However, I don't see a real relation why this should be caused by displaying the cache marker in the popup. But I might be wrong.
 
@moving-bits how does the icon caching works and do you have any idea, what could cause this behavior?

**Comment by MagpieFourtyTwo** [comment] 2021-01-30 21:17
> After closing the popup however the final flag vanishes also on the live map

In my case it was different: we were just driving along, with map locked to current position, when the mystery icons moved in. They had no PN or Final flag from the moment they appeared, until I opened them via popup. After closing the popup, the flags were there and remained, until the Mystery icon moved out again, although I opened popups for other caches, too.

**Comment by MagpieFourtyTwo** [comment] 2021-01-30 21:20
> whole caches where vanishing and reappearing

This is something we observed several times, too: After opening the popup of a cache (mainly Tradis), the cache icon disappeared - until we opened the popup for another cache. After closing the popup of the second cache, his icon vanished, too, but in the very same moment the icon of the first appeared again. Same happened to him, when openeing the popup of a third cache ...

**Comment by Lineflyer** [comment] 2021-01-30 21:24
@MagpieFourtyTwo What version?

**Comment by moving-bits** [comment] 2021-01-30 21:31
> @moving-bits how does the icon caching works and do you have any idea, what could cause this behavior?

Have a look at `MapMarkerUtils.getCacheMarker()` (and `getWaypointMarker()`). There we create a hashcode from the different cache attributes.

As we recently added some more attributes: Maybe we have some sort of overflow or hash collisions? If so, we could combine some of the binary attributes into a single multi-bit attribute?

**Comment by MagpieFourtyTwo** [comment] 2021-01-31 00:32
> @MagpieFourtyTwo What version?

Hmm, good question. Don't know.
IIRC this phenomenon exists for about half a year or so ...
We already had an issue dealing with this, but can't remember. 
However - last time I noticed it was last weekend, IIRC ...

**Comment by Lineflyer** [comment] 2021-01-31 09:06
> Hmm, good question. Don't know.

Just asking, because some parts of the problems you desctibed should be solved meanwhile.

**Comment by moving-bits** [comment] 2021-02-02 20:33
I've debugged a bit into it, displaying the cache specific data.

Displaying the flag depends on either `cache.hasUserModifiedCoords()` or `cache.hasFinalDefined()` having a true value. I tested it with some caches not stored offline, which have modified coords stored on gc.com

At first, everything is fine. Caches have the `hasUserModifiedCoords` flag set, which is fine. After much moving around the `hasUserModifiedCoords` flags gets lost, for reasons yet unknown. So it's not the marker being wrong (or its caching), the problems happens at a different stage, probably some sync problem with gc.com live map?

**Comment by Lineflyer** [comment] 2021-02-02 20:58
That matches my experience of vanishing final flags or found state....maybe our cachecache?

**Comment by MagpieFourtyTwo** [comment] 2021-02-03 22:15
> Just asking, because some parts of the problems you desctibed should be solved meanwhile.

Had it again today:
1. Two saved caches on display in map view
2. opened and closed popup of first one - first cache vanishes
3. opened and closed popup of second cache - first appears again and second cache vanishes
4. moved map around a bit (most probably until map update is triggered): second cache appears again ...

**Comment by Lineflyer** [comment] 2021-08-01 11:06
@MagpieFourtyTwo 
Any idea whether this is still happening?

**Comment by MagpieFourtyTwo** [comment] 2021-08-01 16:52
Haven't seen it in a while ... or at least haven't noticed it .... but, to be honest, haven't tested it explicitly anymore.
Will have an eye on it again. But, a longer tour will happen next weekend the earliest ...

**Comment by MagpieFourtyTwo** [comment] 2021-08-20 11:08
Have had a bunch of mysteries the last two weeks, which showed the "Changed Coordinates" overlay in the map without being stored offline. And from the cross-checked ones without indicator, there was not a single one which turned out to have changed coords after opening the listing. IOW: No falsely displayed stuff so far.

I of course have not checked every single mystery without the "Changed Coordinates" indicator, nevertheless it seems to work perfectly fine over here.

**Comment by fm-sys** [comment] 2021-08-20 20:16
Then let's close for now...

**Closed by fm-sys** 2021-08-20 20:16 UTC
Labels: Bug, Google Play or Beta feedback, Regression
