### ISSUE TITLE
Spurious logging of DNF records.

### ISSUE THREAD

**Issue by alan666notb** [cgeo/cgeo#6757] opened 2017-10-12 10:27 UTC
##### Detailed steps causing the problem:
- Create a 'Found' log and attempt to send it with a weak mobile phone signal
- The send fails and you select 'save offline' ( I _**think**_  the log has actually been sent but cgeo hasn't received a confirmation)
- When you have a data connection, open the log and re-send it.
- cgeo replies with 'log successfully submitted'

##### Actual behavior after performing these steps:
The original 'Found' log appears on the cache page followed by a 'Not found' log with the same text.

##### Expected behavior after performing these steps:
The second attempt to log the find should be rejected.

##### Version of c:geo used:
2017.10.10

##### Is the problem reproducible for you?
It's difficult to reproduce as you have to lose the data connection at just the right time.

##### System information:
```
--- System information ---
Device: E6683 (E6683, Sony)
Android version: 7.1.1
Android build: 32.4.A.0.160
c:geo version: 2017.10.10
Google Play services: enabled - 11.5.18 (448-170253583)
Low power mode: inactive
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: rotation vector
Hide own/found: false
Map strategy: auto
HW acceleration: enabled (default state)
System language: en_GB
System date format: dd/MM/y
Debug mode active: no
System internal c:geo dir: /data/user/0/cgeo.geocaching (11.5 GB free) internal
User storage c:geo dir: /storage/emulated/0/cgeo (11.5 GB free) external non-removable
Geocache data: /storage/emulated/0/Android/data/cgeo.geocaching/files/GeocacheData (11.5 GB free) external non-removable
Database: /storage/emulated/0/Android/data/cgeo.geocaching/files/databases/data (14.0 MB) on user storage
Fine location permission: granted
Write external storage permission: granted
Geocaching sites enabled:
   geocaching.com: Logged in (Login OK) / PREMIUM
Geocaching.com date format: dd MMM yy
Installed c:geo plugins:  none
--- End of system information ---
```

##### Other comments and remarks:
I guess this is related to the recent change to prevent duplicate 'Found' logs.

**Comment by Lineflyer** [comment] 2017-10-12 10:35
I can somehow confirm this issue (but not reproducible).
Besides the case described above, I do also have the following experience:
- Post found log
- Switch off screen while log is being posted
- Switch screen on again

Result:
- Found is being posted online 
- Another offline log with either "found" or "DNF" was stored for the cache

I remember @Bananeweizen changed the behaviour some months ago to follow the new limitation by gc.com to allow only one "Found" log per user. So we changed it in a way, that c:geo changes the default log type automatically in case the cache is already found by the user.

I suspect, that there are some timing and/or resume issues due to which it may happen that this change of default log type is done while the log posting action is still in progress.
Can we decouple or delay the "has user found" from posting the log?

**Comment by alan666notb** [comment] 2017-10-12 10:47
I haven't tried this but I think you could reproduce it by ...
- loading a cache into cgeo and refreshing it.
- without closing cgeo, log a find on a different device / web browser
- then try logging a find on the original device.

**Comment by pstorch** [comment] 2017-10-12 18:14
Isn't it a duplicate of #6694 ?

**Comment by Lineflyer** [comment] 2017-10-16 10:05
@pstorch I think so.
@alan666notb If you think this is not a duplicate of #6694 feel free to reopen, else please continue there.

**Closed by Lineflyer** 2017-10-16 10:05 UTC
Labels: Bug
