### ISSUE TITLE
Cgeo edit log after post

### ISSUE THREAD

**Issue by Bielzebub** [cgeo/cgeo#7157] opened 2018-10-15 10:32 UTC
is unable to edit an EXISTING log posted from cgeo without going to same cache log via website.  Its insistent on making a new log, this is bad when trying to edit a WILL ATTEND as cgeo makes a new log and changes it to ATTENDED

**Comment by SammysHP** [comment] 2018-10-15 13:59
Duplicate of #5170

**Closed by SammysHP** 2018-10-15 13:59 UTC
