### ISSUE TITLE
GPX import does not set coords of Owner defined WPs, even if user has set coords

### ISSUE THREAD

**Issue by MagpieFourtyTwo** [cgeo/cgeo#9849] opened 2021-01-23 23:47 UTC
**Describe the bug:**
Had a Multi this weekend, which has several WPs predefined by the CO.
These WPs have no coords by default - but I had filled some of them.
As we wanted to finish the Multi together, I exported to GPX and shared it with my buddies,
but with import of this GPX, they did not get the coords I had set in the predefined WPs.

**Actual behavior/state after performing these steps:**
Imported WPs did not get the coords, I have set before exporting the cache.

**Expected behavior/state after performing these steps:**
Even predefined WPs should get changed coord.

**Version of c:geo used:**
2021.01.24-NB-f03a863

**Is the problem reproducible:**
Yes

**Comment by murggel** [comment] 2021-01-24 11:22
I will have a look into it, probably related to fix of #9141 (#8409)

**Comment by MagpieFourtyTwo** [comment] 2021-01-24 18:48
If these issues get solved, the strategy can probably be used for ``Save WPs to PN``, too,
as over there, predefined WPs are not saved, neither.

**Comment by murggel** [comment] 2021-01-24 19:14
Do you mean #9084?
I could imagine, that for the gpx-import it is more clear, which data will win on merging the imported data with an already existing waypoint. Probably this will be more difficult for merging from PN, because the data is more obvious in the PN.
But if it follows the same logic as for importing from gpx ...

**Comment by MagpieFourtyTwo** [comment] 2021-01-24 20:33
> Do you mean #9084?

Yep, thx for searching the issue.

**Comment by Lineflyer** [comment] 2021-01-27 09:54
A user of 2021.01.24-RC reported:
>  I have created some WP's in Go to menu and when i try to export them as a gpx file the file created does not contain them. 

Could this be the same root cause?

**Comment by murggel** [comment] 2021-01-27 11:56
> A user of 2021.01.24-RC reported:
> >  I have created some WP's in Go to menu and when i try to export them as a gpx file the file created does not contain them. 
> 
> Could this be the same root cause?

I will check. 
But I guess it is a slightly different case, because it is not contained in the gpx, where as the problem of this issue here is the import.

So probably we should change the description. 
But just let me check, if this is really the case. 

@MagpieFourtyTwo can you please check your gpx-file, if the waypoint / coordinates are contained correctly

**Comment by MagpieFourtyTwo** [comment] 2021-01-27 14:04
> where as the problem of this issue here is the import

You are right - and while reading this I realized that the issue title is misleading, anyway:
Had described the problem correctly as "with import of this GPX, they did not get the coords", but used "export" in the title,
which is in fact wrong, cause the coords have been properly exported to the GPX like ...

```
  <wpt lat="49.xxyzzz" lon="9.abccde">
    <name>027W6MT</name>
    <cmt>&lt;html&gt;
 &lt;head&gt;&lt;/head&gt;
 &lt;body&gt;
  Jahreszahl über dem Tor=Zahl 2
  &lt;br&gt;Zahl 2 - 1000 + 156= ???
  &lt;br&gt;N49°13.795 E009°09.???
 &lt;/body&gt;
&lt;/html&gt;</cmt>
    <desc>Stage 2</desc>
    <sym>Virtual Stage</sym>
    <type>Waypoint|Virtual Stage</type>
    <gsak:wptExtension>
      <gsak:Parent>GC7W6MT</gsak:Parent>
    </gsak:wptExtension>
    <cgeo:originalCoordsEmpty>true</cgeo:originalCoordsEmpty>
  </wpt>
```

... so I changed the issue title accordingly. (BTW: Coords in the example are masked, of course).

BTW: If someone wants to dive deeper in this case, I still have the GPX in question and can send it via mail (don't want to post it here, cause it contains solutions of a multi).

**Comment by murggel** [comment] 2021-01-27 14:32
> BTW: If someone wants to dive deeper in this case, I still have the GPX in question and can send it via mail (don't want to post it here, cause it contains solutions of a multi).

I already did and pushed a PR for that.

**Comment by murggel** [comment] 2021-01-27 14:34
> 
> 
> > A user of 2021.01.24-RC reported:
> > > I have created some WP's in Go to menu and when i try to export them as a gpx file the file created does not contain them.
> > 
> > 
> > Could this be the same root cause?
> 
> I will check.
> But I guess it is a slightly different case, because it is not contained in the gpx, where as the problem of this issue here is the import.

Checked it and it is a different case.
**Caches** without coordinates will not be exported, **waypoints** with empty coordinates will be exported :-o 
For waypoints there is an extension to store additional information, I don't know if there is such an extension for caches

**Comment by MagpieFourtyTwo** [comment] 2021-01-27 14:40
> Caches without coordinates will not be exported

Is this a realistic case?  As locationless caches are not allowed anyway ... even GC8NEAT, the recently announced and at least  locationless called one (by GC HQ), has coords.

> For waypoints there is an extension to store additional information, I don't know if there is such an extension for caches

If you're thinking of e. g. Personal Notes, yes. PNs do get ex- and properly imported via GPX.

**Comment by MagpieFourtyTwo** [comment] 2021-01-27 14:41
> PNs do get ex- and properly imported via GPX.

Which is in fact the workaround we used to transfer the coords from one device to another ... (via ``Save WPs to PN``)

**Comment by murggel** [comment] 2021-01-27 14:44
> 
> 
> > PNs do get ex- and properly imported via GPX.
> 
> Which is in fact the workaround we used to transfer the coords from one device to another ... (via `Save WPs to PN`)

But waypoints do get exported in gpx and imported from another device...

I guess it was more for storing the information in the personal note of geocaching.com (because you can't create user waypoints at geocaching.com) and having there a kind of "backup"

**Comment by MagpieFourtyTwo** [comment] 2021-01-27 14:45
> waypoints with empty coordinates will be exported :-o

Which is perfectly fine, IMO, as WPs w/o coords are a valid element.
Even c:geo users can create WPs without coords, what may be used by some guys to store infos or prepare a multi with the stages to do, putting mnemonic names, stage info etc. into the WPs, while the coords will be added during walking the multi iRL (cause coords may depend on questions and stuff)

**Comment by MagpieFourtyTwo** [comment] 2021-01-27 14:48
> But waypoints do get exported in gpx and imported from another device...

Generally, yes.  But in this special case they did not:
- cache owner pre-defined WPs without coords (cause the cacher has to calculate them on the road)
- I had already started this cache the other day, so some of the pre-defined(!) WPs got coords
- to bring the others up to my level I exported my state to GPX (which contained all the info, even the coords)
- the others imported the GPX, but their WPs did not get updated with the coords I had set the other day

**Comment by murggel** [comment] 2021-01-27 14:50
> > waypoints with empty coordinates will be exported :-o
> 
> Which is perfectly fine, IMO, as WPs w/o coords are a valid element.
> Even c:geo users can create WPs without coords, what may be used by some guys to store infos or prepare a multi with the stages to do, putting mnemonic names, stage info etc. into the WPs, while the coords will be added during walking the multi iRL (cause coords may depend on questions and stuff)

Yes, you are right, but unfortunately the gpx-schema does not allow empty coords for waypoint. 
So there was a workaround (which is also used from GSAK) to use 0/0 as indicator for empty coordinates

**Comment by murggel** [comment] 2021-01-27 14:52
> > But waypoints do get exported in gpx and imported from another device...
> 
> Generally, yes. But in this special case they did not, at least not properly:
> 

Yes, that is a bug which was introduced with  fixing  #9141 and will be fixed with the PR

**Comment by MagpieFourtyTwo** [comment] 2021-01-27 15:19
> So there was a workaround (which is also used from GSAK) to use 0/0 as indicator for empty coordinates

Yes, have seen such WPs already.  And now I even know, why they got 0/0 - fine! Thx for enlightenment!  ;)

**Closed** 2021-01-29 21:13 UTC
Labels: Bug

**Comment by murggel** [comment] 2021-01-31 16:40
Is this something for release or is it automatically contained in the next bugfix / release / beta?

**Comment by moving-bits** [comment] 2021-01-31 21:09
> Is this something for release or is it automatically contained in the next bugfix / release / beta?

It's been merged to `master` branch, so it's included in developer versions and in current nightlies.
Currently we are already in a beta phase, potentially shortly before releasing a new version, so this feature will be included in the release after that.
