### ISSUE TITLE
Adding event to calendar not possible for a specific event

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#4462] opened 2014-11-03 14:36 UTC
From support mail (and confirmed with 2014.11.03-NB):

http://coord.info/GC5F9EN
If I select "Add to calendar" nothing happens. For other caches it is working normal.

**Comment by samueltardieu** [comment] 2016-07-13 18:10
Fixed by b532dd925f543f98b27c68d04262fcd6f75891e5 (duplicate of #5820).

**Closed by samueltardieu** 2016-07-13 18:10 UTC
Labels: Bug
