### ISSUE TITLE
Waypoint description added automatically

### ISSUE THREAD

**Issue by SammysHP** [cgeo/cgeo#5366] opened 2016-01-09 21:49 UTC
Create a new waypoint (e.g. stage of a multicache) with a description. Create another waypoint without a description (description field is empty). After the waypoint was stored, it has the description of the first waypoint. Edit the description of the second waypoint.  Create a third waypoint without a description. It will get the description of the first waypoint as well. Create another waypoint with a description. It will keep its description.

Master from today morning.

**Comment by Lineflyer** [comment] 2016-01-09 22:55
Sound similar to #5276 (which I was unable to reproduce). Right?

**Comment by SammysHP** [comment] 2016-01-10 09:33
Yep, that sounds really similar. But in my case a waypoint with an initial description kept its description.

**Comment by SammysHP** [comment] 2016-01-10 09:46
Here is a video showing the issue: https://youtu.be/ZrCPnEwMzK4

**Comment by Lineflyer** [comment] 2016-01-11 21:15
Seems this was introcuded with the laast release, as we started to get reports like this only them. Closing #5276 as this issue has more information.

**Comment by rsudev** [comment] 2016-01-17 18:43
Could reproduce it.

**Comment by rahu** [comment] 2016-01-21 19:42
Hi,
I debugged into this issue. It' broken in Waypoint::mergeWayPoints. Since UserDefinedWayPoints all have the same prefix the newPrefixes map contains only one of them. (The first one added). And now we are in trouble:

```
  if (newPrefixes.containsKey(prefix)) {
                newPrefixes.get(prefix).merge(oldWaypoint);
```

I'm not sure how to fix this since I see at least two different solutions having different effort: 
1) increment the prefix on each OWN-waypoint added. But how to find out the next (unused) number? Just use count(waypoints)+1? 
2) calculate a hash over all Waypoint data and use this for merging.

**Comment by rsudev** [comment] 2016-01-21 22:05
The main purpose of this Routine is to merge in the waypoints from a newly downloaded or imported cache. In this situation the prefix is the only key we have to identify and match the waypoints from both sets, so 2) is no viable solution.
I think this needs to be solved already at the time the new waypoint is created (in the EditWaypointActivity) such that a new and (for the cache) unique 'own' prefix is generated.

**Closed** 2016-02-02 20:22 UTC
Labels: Bug, high
