### ISSUE TITLE
[Nightly] Enable Live needs an add. map refresh

### ISSUE THREAD

**Issue by MagpieFourtyTwo** [cgeo/cgeo#11316] opened 2021-07-25 10:11 UTC
### Describe your problem!

When being in map in a single cache context, enabling Live will not show the "rest" of the caches.

### How to reproduce?

- open any cache
- view cache on map
- menu => ``Enable live`` ...

### Actual result after these steps?

Some WPs pop up, but no (more) caches.

In order to force an update you may e. g. enter and leave filter definition (while it's not even necessary to save resp. ``Apply`` the filter).

### Expected result after these steps?

All caches should show up (regarding the Live filter definition, of course ;) ).

### Reproducible

Yes

### c:geo Version

2021.07.25-NB-db64367

### System information

```shell
c:geo version: 2021.07.25-NB-db64367

Device:
-------
- Device type: VOG-L29 (VOG-L29EEA, HUAWEI)
- Available processors: 8
- Android version: 10
- Android build: VOG-L29 10.1.0.150(C431E19R2P5)
- Screen resolution: 1080x2147px (423x841dp)
- Sailfish OS detected: false
- Google Play services: disabled - 21.24.18 (120400-383468479)
- HW acceleration: enabled (default state)

Sensor and location:
-------
- Low power mode: inactive
- Compass capabilities: yes
- Rotation vector sensor: present
- Orientation sensor: present
- Magnetometer & Accelerometer sensor: present
- Direction sensor used: rotation vector

Program settings:
-------
- Filters: 
    LIVE: Live Default (no Found, no Archived) ([Live Default \(no Found, no Archived\):inconclusive=false:advanced=true]AND(status:owned_no:found_no:exclude_archived))
    OFFLINE: None ([:inconclusive=false:advanced=true])
- Hide waypoints: -
- Set language: en_DE (system default)
- System date format: dd/MM/y
- Debug mode active: no
- Live map mode: true
- OSM multi-threading: true / threads: 4
- Last backup: 23 Jul, 01:20
- Routing mode: Walk
- Settings: v7, Count:272
- Map: _  DE BaWü Vosges (Offline)
  - Id: cgeo.geocaching.maps.mapsforge.MapsforgeMapProvider$OfflineMapSource:0123-4567:Locus/mapsVector/_  DE BaWü Vosges.map
  - Atts: Maps: (c)Christian Kernbeis, Themes: (c)Tobias Kuehn, www.openandromaps.org 2012-2021
  - Theme: Elevate F140 L120 S110 EB.xml

Services:
-------
- Geocaching sites enabled:
   geocaching.com: Logged in (Login OK) / PREMIUM
   extremcaching.com: Not logged in (Logging in…)
- Geocaching.com date format: dd MMM yy
- Routing: external / BRouter installed: true
- Installed c:geo plugins: contacts

Permissions & paths:
-------
- Fine location permission: granted
- Write external storage permission: granted
- System internal c:geo dir: /data/user/0/cgeo.geocaching (56,2 GB free) v2 internal isDir(7 entries)
- Legacy User storage c:geo dir: /storage/emulated/0/cgeo (56,2 GB free) v2 external non-removable isDir(7 entries)
- Geocache data: /storage/emulated/0/Android/data/cgeo.geocaching/files/GeocacheData (56,2 GB free) v2 external non-removable isDir(308 entries)
- Internal theme sync (is turned ON): /data/user/0/cgeo.geocaching/MapThemeData (56,2 GB free) v2 internal isDir(8 entries)
- Public Folders: #11
  - BASE: /cgeo (User-Defined)[/cgeo[DOCUMENT#0:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo, Av:true, files:>=10, dirs:>=13, totalFileSize:>=1,3 GB, free space: 56,2 GB, files on device: 13278715)
  - OFFLINE_MAPS: ‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‎SD card‌‌‌‌‌‎/Locus/mapsVector (User-Defined)[‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‎SD card‌‌‌‌‌‎/Locus/mapsVector[DOCUMENT#0:p-content://com.android.externalstorage.documents/tree/0123-4567%3ALocus%2FmapsVector::]] (Uri: content://com.android.externalstorage.documents/tree/0123-4567%3ALocus%2FmapsVector/document/0123-4567%3ALocus%2FmapsVector, Av:true, files:449, dirs:4, totalFileSize:20,7 GB, free space: 154,3 GB, files on device: 0)
  - OFFLINE_MAP_THEMES: ‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‎SD card‌‌‌‌‌‎/Locus/mapsVector/_themes/Elevate4 (User-Defined)[‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‎SD card‌‌‌‌‌‎/Locus/mapsVector/_themes/Elevate4[DOCUMENT#0:p-content://com.android.externalstorage.documents/tree/0123-4567%3ALocus%2FmapsVector%2F_themes%2FElevate4::]] (Uri: content://com.android.externalstorage.documents/tree/0123-4567%3ALocus%2FmapsVector%2F_themes%2FElevate4/document/0123-4567%3ALocus%2FmapsVector%2F_themes%2FElevate4, Av:true, files:418, dirs:1, totalFileSize:3,4 MB, free space: 154,3 GB, files on device: 0)
- LOGFILES: /cgeo/logfiles (Default)[/cgeo/logfiles[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/logfiles]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Flogfiles, Av:true, files:1, dirs:0, totalFileSize:119 B, free space: 56,2 GB, files on device: 13278715)
  - GPX: /Download/GPX (User-Defined)[/Download/GPX[DOCUMENT#0:p-content://com.android.externalstorage.documents/tree/primary%3ADownload%2FGPX::]] (Uri: content://com.android.externalstorage.documents/tree/primary%3ADownload%2FGPX/document/primary%3ADownload%2FGPX, Av:true, files:12, dirs:0, totalFileSize:1,1 MB, free space: 56,2 GB, files on device: 13278715)
  - BACKUP: /cgeo/backup (Default)[/cgeo/backup[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/backup]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Fbackup, Av:true, files:>=15, dirs:>=6, totalFileSize:>=2,2 GB, free space: 56,2 GB, files on device: 13278715)
  - FIELD_NOTES: /cgeo/field-notes (Default)[/cgeo/field-notes[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/field-notes]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Ffield-notes, Av:true, files:36, dirs:0, totalFileSize:118,9 KB, free space: 56,2 GB, files on device: 13278715)
  - SPOILER_IMAGES: /cgeo/GeocachePhotos (Default)[/cgeo/GeocachePhotos[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/GeocachePhotos]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2FGeocachePhotos, Av:true, files:0, dirs:0, totalFileSize:0 B, free space: 56,2 GB, files on device: 13278715)
  - ROUTING_BASE: /cgeo/routing (Default)[/cgeo/routing[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/routing]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Frouting, Av:true, files:15, dirs:1, totalFileSize:582,3 MB, free space: 56,2 GB, files on device: 13278715)
  - ROUTING_TILES: /cgeo/routing/segments4 (Default)[/cgeo/routing/segments4[PERSISTABLE_FOLDER(ROUTING_BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/routing/segments4]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Frouting%2Fsegments4, Av:true, files:5, dirs:0, totalFileSize:582,2 MB, free space: 56,2 GB, files on device: 13278715)
  - TEST_FOLDER: [Legacy]/data/user/0/cgeo.geocaching/files/unittest (Default)[/data/user/0/cgeo.geocaching/files/unittest[FILE#1:p-file:///data/user/0/cgeo.geocaching/files::/unittest]] (Uri: file:///data/user/0/cgeo.geocaching/files/unittest, Av:true, files:0, dirs:0, totalFileSize:0 B, free space: 56,2 GB, files on device: -1)
- Map render theme path: Elevate F140 L120 S110 EB.xml
- PersistedDocumentUris: #1
- TRACK: null
- Persisted Uri Permissions: #4
  - content://com.android.externalstorage.documents/tree/primary%3ADownload%2FGPX (24 May, 00:17):RW
  - content://com.android.externalstorage.documents/tree/0123-4567%3ALocus%2FmapsVector%2F_themes%2FElevate4 (20 May, 23:38):RW
  - content://com.android.externalstorage.documents/tree/primary%3Acgeo (20 May, 23:37):RW
  - content://com.android.externalstorage.documents/tree/0123-4567%3ALocus%2FmapsVector (20 May, 23:37):RW
- Database: /data/user/0/cgeo.geocaching/databases/data (v95, Size:431,3 MB) on system internal storage

--- End of system information ---
```

### Additional Information

I usually have a Live filter active like ``Found=No, Own=No, Archived=No``, which was active in the scenario described above, but even without the behavior was the same. BTW: With yesterday's nightly things were even more strange, cause although the filter was active and although the filter string in the header showed the filter text, the filter definition (opened by tapping on the filter string) was completely empty. But when entering the filter dialog using the filter icon, the filter definition was shown ... but this seems to be gone with today's nightly ... have there been some changes recently or did I just do s/th different ...? If nothing changed, I most probably would have to investigate again ...

**Comment by eddiemuc** [comment] 2021-07-25 13:11
Confirmed, but this bug seems **NOT** to occur on Google Maps (I could reproduce on Offline Map)

**Comment by eddiemuc** [comment] 2021-07-25 13:12
@MagpieFourtyTwo 
> BTW: With yesterday's nightly things were even more strange, cause although the filter was active and although the filter string in the header showed the filter text, the filter definition (opened by tapping on the filter string) was completely empty. But when entering the filter dialog using the filter icon, the filter definition was shown ... but this seems to be gone with today's nightly ... have there been some changes recently or did I just do s/th different ...? If nothing changed, I most probably would have to investigate again ...

There was a bug indeed leading to this behaviour, but I fixed it recently. The fix must have come to the nightlies only today.

**Comment by eddiemuc** [comment] 2021-07-25 13:39
Fixed with PR #11318. Actual cause of observed behaviour was an underlying (but catched) NullPointerException, which in turn was caused by an unset filter context.

**Closed** 2021-07-25 15:35 UTC
Labels: Bug, Unverified

**Comment by MagpieFourtyTwo** [comment] 2021-07-25 21:05
Works like a charm right now - great!

It's just a bit irritating if the cache, you were currently looking at on the map (with most probably even a route to it),
surprisingly disappears as soon as you activate Live mode (even more if his route now ends in nowhere land  ;) ).
Although it's of course pretty obvious (to us) why this may happen (e. g. when the cache in question was a found one,
but Live filter contains ``Found=No``), but, this behavior may nevertheless be irritating to the users ...
Probably even more, if he used ``Show list on map`` and then activates Live with a filter, which hides just parts of this list.  ;)

So let me fantasize a bit (and don't hesitate to say "No, absolute rubbish, will not do this!" if you feel it ;) ): Would it make any sense to you, to add the content of the previous context (like e. g. the "root cache" or even the content of the list, which has been displayed) to the filtered content, when Live mode gets activated ...? \*innocentlooking* ;)

**Comment by fm-sys** [comment] 2021-07-25 21:46
> and don't hesitate to say "No, absolute rubbish, will not do this!" if you feel it ;)

Not completely rubbish, but wouldn't this make things even more complex? Especially when thinking about the bottom navigation, there would be no way to get the "root cache" or list content hidden again as there will be just one top-level map viewer. 

So I would vote for leaving it as it is for now and wait for beta feedback fist...

**Comment by MagpieFourtyTwo** [comment] 2021-07-25 22:22
> there would be no way to get the "root cache" or list content hidden again 

Really? I of course may be wrong, cause I don't know the implementation details, but in my imagination there ...
1. is the current context displayed on offline map (with either a "root cache" or a list)
2. then Live mode gets enabled ...
3. filter function will be called to perform a select with the filter as where clause
4. and finally filter function returns a list of objects which then will be displayed on map.

Given that the context, in which the "root cache" or "root list content" has initially been displayed, knows very well that the mode changed from Offline to Live - and in this special situation it could take the content of the current context and pass it to the filter function, which will merge this content into the list it will return ... et voilà: Even the "root" stuff will be seen on map.

Getting rid of it will still be possible, as on next call of the filter function there will of course be no switch from Offline to Live, thus just an empty "root context list" will be passed ... and the result will be the pure filter result, and the "root" will be gone.

This may sound a bit weird on first sight, but IMO it's way more traceable for the user, as it happens no "implicit vanish" - and in the latter case, i. e. when opening the filter dialog, he actively changed the definition, thus it appears to be way more comprehensible why his "root cache" now disappears ...

And, no, my heart is not in this solution, I could just imagine that the switch to Live mode becomes a bit easier to understand for the normal user.

**Comment by eddiemuc** [comment] 2021-07-26 05:42
First of all: we would definitely need a new issue for this. If you want to proceed with this, please open one :-)

Second, In checked in current production how this is handled in injunction with global "exclude found" filter. To my surprise the behavior is different in OSM and Google Maps:
* In OSM the behavior is as @MagpieFourtyTwo describes it: when entering the map with an already found cache (although "hide found" is enabled), then switching to "live" then the initial "found" cache stays nevertheless
* In Google maps, the cache vanishes

So at least we have inconsistent behavior in current production.

Third: of course this can be implemented technically, why not? Obviously it already isnfor OSM, it may get complex for Google, I don't know the layering concept there (@MagpieFourtyTwo you should know that unfortunately we have more or less two different "map logics" programmed for the two maps, always complex and error-prone to keep them in sync)

Fourth is the question whether this makes sense for the user. I personally would disagree. Because while at first this seems to be logic, what should then happen if the user e.g. further changes the (now live) filter? Should those changes still not apply to the initial caches? So the user has absolutely no way to get rid of these "initial caches" in any way (except for going all the way back to start screen and opening live map from there)?

**Comment by eddiemuc** [comment] 2021-07-26 05:49
> Getting rid of it will still be possible, as on next call of the filter function there will of course be no switch from Offline to Live, thus just an empty "root context list" will be passed ... and the result will be the pure filter result, and the "root" will be gone.

This now gets too complicated for my taste. So initially the user would see the root caches, but if he goes into the filter and changes something completely unrelated to the "root caches" (or even nothing) they would suddenly disappear? What about other actions e.g. opening the map quick settings (which contains filtering too), or the map source selection? Which actions shall trigger the "filter execution" for root caches and which not? This seems very complicated to get sorted out, and I feel it gets at some point very hard for users to understand the logic behind it.

**Comment by MagpieFourtyTwo** [comment] 2021-07-26 22:05
> (...) the question (is) whether this makes sense for the user. I personally would disagree.

Okay - this is what I wanted to know first: a second opinion. Cause it was just a quick idea of mine, while working with the modes.
That's why I did not open an issue right from the start - thx for dealing with it.
And thx to @fm-sys, too, for reading and giving a statement

Nevertheless, still your question remains why it is different between GM and OSM (which I have not even realized yet, to be honest) ... and in which direction it should be changed to be consistent again (while the one I would prefer, is possibly clear ... ;) ).
