### ISSUE TITLE
Calculator crash on a waypoint with calculated coordinates

### ISSUE THREAD

**Issue by Matze2** [cgeo/cgeo#6783] opened 2017-10-18 20:38 UTC
##### Detailed steps causing the problem:
- Open a special waypoint which contains calculator data

##### Actual behavior after performing these steps:
c:geo crashes

##### Expected behavior after performing these steps:
No crash :)

##### Version of c:geo used:
2017.10.17-NB-30e87fb

##### Is the problem reproducible for you?
Yes, but only with one waypoint.

##### System information:
```
TODO
```

##### Other comments and remarks:
Maybe introduced with tri-state button change. If an older nightly is still available I can check how the calculator is configured in this waypoint.

**Comment by Matze2** [comment] 2017-10-18 20:43
Same for 2017.10.18-NB-30e87fb.

**Comment by S-Bartfast** [comment] 2017-10-19 05:53
Arr, I actually had this same problem but thought it was something wacky I had done to my own system.  Looks like it's not just me after all though.

To fix it I just uninstalled then re-installed c:geo.  For me this happened when I was testing the tri-state buttons as well so there must be something incompatible in there but at the time I couldn't work out what it was and given the reinstall fixed it I just moved on.

As this still hasn't gone out to uses yet we don't necessarily need to support upgrading from the 'two-state' buttons but I'll take a deeper look to see if I can clean it up just to be kind to those running the nightly builds ;)

**Comment by Matze2** [comment] 2017-10-19 08:19
For me this is not important. I have used the "button mode" only since one week. I can remove the problematic waypoint and create it from scratch.
So if you are sure that this is only a problem between different nightly builds we can ignore it and spend energy in more interesting areas. :)
Of course I can only speak for myself.

**Comment by S-Bartfast** [comment] 2017-10-19 09:12
Well, until I workout what the problem is I can't be confident that it's only between nightly builds, all I know is that I had the same problem and re-installing (which completely clears the calculators stored state) fixed it.

There is a small issue in that buttons that were saved as "Custom Values" (that is the long-press 'steel' coloured values) will show up as "Blank" buttons rather than "Custom" buttons when transitioning from dual-state to tri-state builds, but this shouldn't cause the program to crash.

Any way, try as I might I am now unable to get the "crashing issue" to show itself.  In my brief investigation from when I actually had the problem myself I worked out it was an issue to do with the JSON formatted data that the calculator's state is stored in and resolved it by un-installing and re-installing c:geo again.  Now though I am completely unable to find a way to infect the data and cause a crash.  Best I can achieve is to have "Custom" buttons appear as "Blank", which while annoying isn't too bad considering it's a nightly build.

Could I get you to install the older (working) version again while you still have the 'infected waypoint' and show us what data was entered into the calculator?

Thanks.

**Comment by S-Bartfast** [comment] 2017-10-19 09:49
Still can't workout what's causing it but it's possible the issue arose from implementing the "Save" icon, implemented on the 4th of October.  In this modification I also removed the 100's button from the latitude coordinates (as it was redundant) making one fewer button than before.  I can't see exactly how this would cause the problem but waypoints created before this change have calculator state for more buttons than there actually are after the change.  If you do have a waypoint from back then you'll notice that all the buttons have "slipped down one" and that the last no longer exists.

**Comment by S-Bartfast** [comment] 2017-10-19 10:19
Okay, after discovering that blanking out all the buttons in a section leads to a crash (see #6781) is it possible that you had all "Custom" buttons in a section.

Something like:
>`[W][1][2][2]°[0][5].[Z][Y][X]`

(Where 'X', 'Y' and 'Z' are all long-pressed values)

While this is different to the crash I was experiencing it would cause a crash when transitioning from a duel-state to a tri-state button build.  This crash though would occur later than the one I was experiencing.  in particular it would occur when the calculator is first shown where as the crash I was experiencing was occurring as soon as you opened the cache itself (ie. when the description of the cache is shown).

**Comment by Matze2** [comment] 2017-10-19 10:38
> Could I get you to install the older (working) version again while you still have the 'infected waypoint' and show us what data was entered into the calculator?

Unfortunately I don't have the old APKs anymore. Is there a way to get old nightlys from the download area or Jenkins?

**Comment by Matze2** [comment] 2017-10-19 10:40
> BTW, the crash I was experiencing (which I am now thinking was an anomaly again) was occurring as soon as you opened the cache itself (ie. when the description of the cache is shown) rather than when you attempted to open the calculator.

Yes in my case the c:geo crashes when I press "Calculate coordinates".

**Comment by Matze2** [comment] 2017-10-19 10:57
Maybe fixing #6781 will also fix this issue.

**Comment by S-Bartfast** [comment] 2017-10-19 11:42
>Maybe fixing #6781 will also fix this issue.

Yeah, I suspect it will.
A Pull Request for a fix has been submitted so hopefully it won't be far off.

Assuming that does fix the crash your buttons will appear blank but simply re-entering their original values should restore what you had before.  Note the previously entered expressions should still be in the "variable bank" so, even though you can't see them, they should re-appear once their associated 'names' are reentered (assuming you haven't saved over the state with 'empty' expressions in the meantime).

**Comment by Matze2** [comment] 2017-10-19 14:08
Let's see. Will try as soon as I have an apk.

**Comment by kumy** [comment] 2017-10-19 15:37
>  Is there a way to get old nightlys from the download area or Jenkins?

You can get them from the fdroid repo (maybe from yhe archive one)

On October 19, 2017 12:38:49 PM GMT+02:00, Matthias <notifications@github.com> wrote:
>> Could I get you to install the older (working) version again while
>you still have the 'infected waypoint' and show us what data was
>entered into the calculator?
>
>Unfortunately I don't have the old APKs anymore. Is there a way to get
>old nightlys from the download area or Jenkins?
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/cgeo/cgeo/issues/6783#issuecomment-337869466

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by kumy** [comment] 2017-10-19 15:40
Use https://fdroid.cgeo.org/nightly/archive/ for the repo url

**Comment by Matze2** [comment] 2017-10-19 18:51
No access, unfortunately

> 403 Forbidden

**Comment by Matze2** [comment] 2017-10-19 19:34
It seems a downgrade to an older version does not work: 
"Installation wegen unbekannten Fehler fehlgeschlagen" / "Installation failed due to unknown error"
Do i need to uninstall my current nightly? What happens with my cache data then?

**Comment by kumy** [comment] 2017-10-19 21:24
You have to use f-droid client to access the repo. See Fdroid.org

On October 19, 2017 9:34:01 PM GMT+02:00, Matthias <notifications@github.com> wrote:
>It seems a downgrade to an older version does not work: 
>"Installation wegen unbekannten Fehler fehlgeschlagen" / "Installation
>failed due to unknown error"
>Do i need to uninstall my current nightly? What happens with my cache
>data then?
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/cgeo/cgeo/issues/6783#issuecomment-338013451

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by Matze2** [comment] 2017-10-19 22:41
Did that. And I have the APKs on my mobile. But they don's install with unknown error.
Never mind. I will first try the fix for #6781. Maybe this solves the issue already.

**Comment by Lineflyer** [comment] 2017-10-23 16:13
> Did that. And I have the APKs on my mobile. But they don's install with unknown error.

Downgrading is not allowed in that case.
If you want to do the test you have to uninstall and reinstall, but you have to make a manual backup of the cache databse (Menu - Settings - System - Backup) before and restore afterwards.
Note: If the database scheme/version has changed between the two nightlies a restore will not be possible.

**Comment by Matze2** [comment] 2017-10-23 21:39
As far as I know I will lose my settings. Not sure about additional data like log photos, etc.
Frankly, I don't want to do this on my "production" c:geo (usually I am willing to do any kind of test).

I'll try to use another device and move the c:geo backup there.

**Comment by Matze2** [comment] 2017-10-23 22:29
So - I tried it on an Fire HD 8. c:geo reports Android version 5.1.1 - same as my mobile phone.
Nightlies up to 2017.10.16 could not open the cache with the problematic waypoint at all.
Starting from 2017.10.17 I have the same behavior as with the phone. I can open the cache but not the problematic waypoint.
In other words: with no nightly it is possible to open the waypoint to check the settings.

If there is interest i can provide a cgeo backup containing only this cache.

**Comment by Matze2** [comment] 2017-10-26 16:15
Ok. With the latest nightly 2017.10.26 the waypoint can be opened again. Here is how it was configured:
![screenshot_2017-10-26-18-03-44](https://user-images.githubusercontent.com/12542802/32063968-de548c88-ba78-11e7-885d-20cd309aea21.png)
As @S-Bartfast predicted this issue and #6781 had the same root cause (it is open how I ever could save this configuration). 
Therefore this issue is resolved from my side and can be closed.

**Comment by pstorch** [comment] 2017-10-26 16:22
@Matze2 thanks for testing and the feedback

**Closed by pstorch** 2017-10-26 16:22 UTC
Labels: Bug, Requires submitter feedback, WP Calc

**Comment by S-Bartfast** [comment] 2017-10-27 00:14
Cool, glad to have fixed it :)

>... (it is open how I ever could save this configuration).
Did you miss-type something there?

Once you were able to open it and re-entered the "custom values" did their associated "equations" automatically populate for you?

**Comment by S-Bartfast** [comment] 2017-10-27 00:14
Cool, glad to have fixed it :)

>... (it is open how I ever could save this configuration).
Did you miss-type something there?

Once you were able to open it and re-entered the "custom values" did
their associated "equations" automatically populate for you?

**Comment by Matze2** [comment] 2017-10-27 06:27
> (it is open how I ever could save this configuration)

This should have been "how I every **could have saved** the configuration".

Before this fix c:geo crashed as soon as all digits from a group are "blanked". I just wondered how I was able to setup a configuration like this and save it. That's all.

**Comment by S-Bartfast** [comment] 2017-10-27 07:07
Well, as I tried to explain above (though admittedly it was a bit of a 'wordy' explanation):
>There is a small issue in that buttons that were saved as "Custom Values" (that is the long-press 'steel' coloured values) will show up as "Blank" buttons rather than "Custom" buttons when transitioning from dual-state to tri-state builds...

Essentially what this is saying is that buttons assigned a 'custom' value (that is the long-pressed buttons) do not display properly between the two builds.  Specifically, if a custom value were assigned using a build before the 'tri-state' feature was introduced that button would not be displayed properly if opened by a build after the 'tri-state' buttons were introduced.  As it is, rather then being displayed as a 'custom' button (like it should) that button is in fact shown as being 'blank'.  While this is mildly annoying it would not lead to the crash you were experiencing.

The actual cause of the crash was that there were 3 'custom' buttons in a section (which is normally fine) however, when these three buttons were open in the 'tri-state' build those three buttons appeared as 'blank' buttons (rather than 'custom' buttons) , which is what lead to the crash as described in #6785.

So the blank-section was never saved.  They would have originally been three 'custom' value buttons to begin with but when open by the later build were _shown_ as being 'blank'.

**Comment by S-Bartfast** [comment] 2017-10-27 07:13
Arrr:
>(it is open how I ever could save this configuration)

Is that a regular expression in German is it?  Kind of how we would say "it is still an open question"
(as in "Goldbach's Conjecture is still an open question in mathermatics").

I like it :)

**Comment by Matze2** [comment] 2017-10-27 09:10
Um - sorry. It was in the sense "this is still a mystery but uninteresting".
Now I also got your explanation and it is not even a mystery anymore :)
