### ISSUE TITLE
Flashlight

### ISSUE THREAD

**Issue by andrixnet** [cgeo/cgeo#5425] opened 2016-01-26 20:52 UTC
While geocaching with cgeo, and only using the smartphone as tool, I found it significant to be able to promptly switch on and off the flashlight (the flash/torch white LED besides the camera).
Many smartphones have such hardware today.
Itcan be activated either by a special application (usually one needs to download such app) or by a funxtion through the notification and settings panrl (the few lucky ones whre the android was configured as such from factory).

I would like to request a functionality in cgeo  wherr one can easily turn on or off the flashlight from most screens of the app (like mains creen, map, navigation-compass, cache lists and cache pages , description and logs.)

Ideally it would be a single step button, but it could also be a two step as in menu, flashlight.

It is difficult ans cumbersome to focus on both map/compass/cache page and search for a cache in thw dark. 
And now being winter, when darkbess prevails, even more so.

I believe this fuction woukd add value to cgeo.

Thank you.

**Comment by samueltardieu** [comment] 2016-01-26 20:54
What version of Android are you using? Recent versions either include a flashlight toggle tile in the "quick tiles" that appear when you slide the status bar down or can be configured to do so.

**Comment by SammysHP** [comment] 2016-01-26 20:58
Duplicate of #3834.

**Closed by SammysHP** 2016-01-26 20:58 UTC
Labels: Feature Request

**Comment by Bananeweizen** [comment] 2016-01-27 06:37
Use an app like overlays: https://play.google.com/store/apps/details?id=com.applay.overlay&hl=de and configure your favorite flashlight widget to appear as overlay. Works with _every_ app, no changes in cgeo needed.
