### ISSUE TITLE
Text options menu when editing signature is broken (dark theme)

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#11582] opened 2021-08-29 09:34 UTC
### Describe your problem!

From support mail:
When editing my signature and selecting some text the shown menu is somehow blocking out (overlaying) the text.

### How to reproduce?

- Open Settings - Logging 
- Edit signature
- Long tap to mark some text

### Actual result after these steps?

![image](https://user-images.githubusercontent.com/949669/131245725-bdd5e370-af9e-4f47-880e-3b341b2d37eb.png)

### Reproducible

Yes

### c:geo Version

2021.08.28

### System information

```text
c:geo version: 2021.08.28

Device:
-------
- Device type: SM-N960U (crownqltesq, samsung)
- Available processors: 8
- Android version: 10
- Android build: QP1A.190711.020.N960USQS9FUG2
- Screen resolution: 1080x2085px (384x717dp)
- Sailfish OS detected: false
- Google Play services: disabled - 21.26.21 (120400-387928701)
- HW acceleration: enabled (default state)

Sensor and location:
-------
- Low power mode: inactive
- Compass capabilities: yes
- Rotation vector sensor: present
- Orientation sensor: present
- Magnetometer & Accelerometer sensor: present
- Direction sensor used: rotation vector

Program settings:
-------
- Settings: v8, Count:152
- Set language: en_US (system default)
- System date format: M/d/yy
- Time zone: CDT
- Debug mode active: no
- Last backup: Feb 23, 2019, 1:44 PM
- Routing mode: Walk
- Live map mode: true
- OSM multi-threading: false / threads: 1
- Map: CyclOSM
  - Id: cgeo.geocaching.maps.mapsforge.MapsforgeMapProvider$CyclosmMapSource
  - Atts: CyclOSM, map data OpenStreetMap contributors
  - Theme: none

Filters:
-------
- Hide waypoints: -
- LIVE: Status:Found=No ([:inconclusive=false:advanced=false]AND(type;difficulty_terrain:d=-:d=-:t=-:t=-;status:found_no))
- OFFLINE: None ([:inconclusive=false:advanced=false])

Services:
-------
- Geocaching sites enabled:
   geocaching.com: Logged in (Login OK) / PREMIUM
   Geocaching.com Adventure Lab
- Geocaching.com date format: MM/dd/yyyy
- Routing: external / BRouter installed: false
- Installed c:geo plugins:  none

Permissions & paths:
-------
- Fine location permission: granted
- Write external storage permission: granted
- System internal c:geo dir: /data/user/0/cgeo.geocaching (50.4 GB free) v2 internal isDir(8 entries)
- Legacy User storage c:geo dir: /storage/emulated/0/cgeo (50.3 GB free) v2 external non-removable isDir(8 entries)
- Geocache data: /storage/emulated/0/Android/data/cgeo.geocaching/files/GeocacheData (50.3 GB free) v2 external non-removable isDir(1953 entries)
- Internal theme sync (is turned off): /data/user/0/cgeo.geocaching/MapThemeData (50.4 GB free) v2 internal isDir(0 entries)
- Public Folders: #11
  - BASE: /cgeo (User-Defined)[/cgeo[DOCUMENT#0:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo, Av:true, files:>=15, dirs:>=10, totalFileSize:>=2.3 GB, free space: 50.3 GB, files on device: 3670016)
  - OFFLINE_MAPS: /cgeo/maps-offline (User-Defined)[/cgeo/maps-offline[DOCUMENT#0:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo%2Fmaps-offline::]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo%2Fmaps-offline/document/primary%3Acgeo%2Fmaps-offline, Av:true, files:5, dirs:1, totalFileSize:2.3 GB, free space: 50.3 GB, files on device: 3670016)
  - OFFLINE_MAP_THEMES: /cgeo/maps-offline/_themes (Default)[/cgeo/maps-offline/_themes[PERSISTABLE_FOLDER(OFFLINE_MAPS)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo%2Fmaps-offline::/_themes]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo%2Fmaps-offline/document/primary%3Acgeo%2Fmaps-offline%2F_themes, Av:true, files:0, dirs:0, totalFileSize:0 B, free space: 50.3 GB, files on device: 3670016)
  - LOGFILES: /cgeo/logfiles (Default)[/cgeo/logfiles[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/logfiles]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Flogfiles, Av:true, files:1, dirs:0, totalFileSize:229.8 KB, free space: 50.3 GB, files on device: 3670016)
  - GPX: /cgeo/gpx (User-Defined)[/cgeo/gpx[DOCUMENT#0:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo%2Fgpx::]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo%2Fgpx/document/primary%3Acgeo%2Fgpx, Av:true, files:9, dirs:0, totalFileSize:8.9 MB, free space: 50.3 GB, files on device: 3670016)
  - BACKUP: /cgeo/backup (Default)[/cgeo/backup[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/backup]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Fbackup, Av:true, files:1, dirs:1, totalFileSize:27.0 MB, free space: 50.3 GB, files on device: 3670016)
  - FIELD_NOTES: /cgeo/field-notes (Default)[/cgeo/field-notes[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/field-notes]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Ffield-notes, Av:true, files:0, dirs:0, totalFileSize:0 B, free space: 50.3 GB, files on device: 3670016)
  - SPOILER_IMAGES: /cgeo/GeocachePhotos (Default)[/cgeo/GeocachePhotos[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/GeocachePhotos]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2FGeocachePhotos, Av:true, files:0, dirs:0, totalFileSize:0 B, free space: 50.3 GB, files on device: 3670016)
  - ROUTING_BASE: /cgeo/routing (Default)[/cgeo/routing[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/routing]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Frouting, Av:true, files:7, dirs:1, totalFileSize:81.2 KB, free space: 50.3 GB, files on device: 3670016)
  - ROUTING_TILES: /cgeo/routing/segments4 (Default)[/cgeo/routing/segments4[PERSISTABLE_FOLDER(ROUTING_BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/routing/segments4]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Frouting%2Fsegments4, Av:true, files:0, dirs:0, totalFileSize:0 B, free space: 50.3 GB, files on device: 3670016)
  - TEST_FOLDER: [Legacy]/data/user/0/cgeo.geocaching/files/unittest (Default)[/data/user/0/cgeo.geocaching/files/unittest[FILE#1:p-file:///data/user/0/cgeo.geocaching/files::/unittest]] (Uri: file:///data/user/0/cgeo.geocaching/files/unittest, Av:true, files:0, dirs:0, totalFileSize:0 B, free space: 50.4 GB, files on device: -1)
- Map render theme path:
- PersistedDocumentUris: #1
- TRACK: null
- Persisted Uri Permissions: #3
  - content://com.android.externalstorage.documents/tree/primary%3Acgeo (Apr 18, 10:14 PM):RW
  - content://com.android.externalstorage.documents/tree/primary%3Acgeo%2Fgpx (Apr 18, 10:15 PM):RW
  - content://com.android.externalstorage.documents/tree/primary%3Acgeo%2Fmaps-offline (Apr 18, 10:14 PM):RW
- Database: /data/user/0/cgeo.geocaching/databases/data (v96, Size:68.4 MB) on system internal storage

--- End of system information ---
```

### Additional Information

Seems this complete dialog is not yet converted to the styling we use (e.g. when composing a log)

**Comment by fm-sys** [comment] 2021-08-29 16:47
Looks very much like #11024. There was a fix, but seems like it does not work anymore/for all devices...

**Comment by MagpieFourtyTwo** [comment] 2021-08-30 00:15
> There was a fix, but seems like it does not work anymore/for all devices...

Not really ... first: issue #11024 is indeed the very same, but in fact has not really been fixed.
@moving-bits merely reversed a few changes that were suspected to have been the cause.
But unfortunately that was not enough ... 

Perhaps #11024 should be re-opened, as the description is a bit more detailed over there?

**Comment by moving-bits** [comment] 2021-09-19 07:24
I'm not sure whether we can really fix this until our settings are refactored to AndroidX preferences (work on this is ongoing). 

We are currently using an unsupported mix of old and new technologies (old preferences technology, long deprecated, mixed with some home-brewn extensions, AndroidX and material design), and it's more or less "by pure chance", that our settings still do work at all... The error described in #10984 is another artifact of this (and a couple of other open issues).

As work on refactoring settings is already ongoing, I would propose to not invest too much time are for inventing another crude workaround (except someone finds the magic one-liner fixing it), but wait for settings being refactored.

**Comment by moving-bits** [comment] 2021-12-05 09:55
No longer reproducible with #12244, so probably fixed with migration of our preferences.
I'll keep this issue open for a while, though, so that one of the affected users can retest this with our upcoming nightly.

![image](https://user-images.githubusercontent.com/3754370/144741834-912e0d74-1076-4468-a0dd-d4e8fcbd141f.png)

**Comment by MagpieFourtyTwo** [comment] 2021-12-05 10:39
Already stumbled upon the changes concerning the problems reported with #11024 yesterday evening - seems to work now. Therefore I would agree that the issue over here, which was in fact just a subset of #11024, can safely be closed.

Thanks for the efforts!

**Comment by moving-bits** [comment] 2021-12-05 10:43
Thanks for the feedback, but let's wait until #12244 is in the nightlies to cross-check whether this has any side-effects. 
(Although I guess that the original cause has been tackled with migration to AndroidX preferences already.)

**Comment by fm-sys** [comment] 2021-12-10 07:12
I guess we can close here, can we?

**Closed by fm-sys** 2021-12-10 07:12 UTC
Labels: Bug, Frontend Design
