### ISSUE TITLE
Potential Feature Request: Use same zoom level for maps of lists and live map

### ISSUE THREAD

**Issue by haarspalter** [cgeo/cgeo#5681] opened 2016-04-20 12:43 UTC
##### Detailed steps causing the problem:
Not sure if this might be possible already now: I am mainly using c:geo "offline", and quite frequently I want to check what caches are near to my current location. To do so, I select a list of saved caches, and open that map. 

##### Actual behavior after performing these steps:
Currently, the map's zoom level seems to be set to show all caches in the list. 

##### Expected behavior after performing these steps:
What I would prefer for this specific use case: have GPS enabled by default to show my current location, and use a zoom level like in the live map to see near caches
Of course this could be based on a configuration option

##### Version of c:geo used:
2016.04.20-NB-3790b0a

##### Is the problem reproducible for you?
Yes

##### System information:
--- System information ---
Device: D6503 (D6503, Sony)
Android version: 5.1.1
Android build: 23.4.A.1.264
Cgeo version: 2016.04.20-NB-3790b0a
Google Play services: enabled
Low power mode: active
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present Direction sensor used: orientation Hide own/found: true Map strategy: auto HW acceleration: enabled (default state) System language: de_DE Debug mode active: no Geocaching sites enabled:
   geocaching.com: Logged in (Login OK) / PREMIUM Installed cgeo plugins: calendar
--- End of system information ---

**Comment by SammysHP** [comment] 2016-04-20 12:56
Duplicate of #5087, #3738, #3078.

**Closed by SammysHP** 2016-04-20 12:56 UTC
