### ISSUE TITLE
Copy parts of cache description e.g. coords to waypoint

### ISSUE THREAD

**Issue by fritzfan** [cgeo/cgeo#5066] opened 2015-06-29 19:23 UTC
the description of a multicache contains a list of waypoints (e.g. http://coord.info/GCY803)
I can't find a way to copy coords of a station to waypoint - longpressing text select the whole text for copying to clipboard or for translating. finally I solved my problem using an external file to select described coords and copy to waypoint - this last part then worked great for me.
Samsung Note3 Android 5.0, c:geo version 2015.06.19

**Comment by Lineflyer** [comment] 2015-06-30 06:30
Duplicate of #3819

**Closed by Lineflyer** 2015-06-30 06:30 UTC
