### ISSUE TITLE
Avoid duplicate cache positions

### ISSUE THREAD

**Issue by bekuno** [cgeo/cgeo#8641] opened 2020-07-14 21:26 UTC
It is possible to have caches at (almost) the same position, especially if more than one geocaching connector is used. (e.g. in a situation as described in #2349)

A way to not have 2 cache symbols on the same map position could be to use a pin and move the symbols a few points away from each other. But then we need a general collision detection and movement for all caches within a defined distance to their neighbours.

**Comment by Lineflyer** [comment] 2020-07-14 21:31
As also mentioned in that other issue we do alread have a solution for the map (implemented for OSM). All we need to do is to apply this to Gmaps as well.

**Comment by moving-bits** [comment] 2020-07-16 19:10
> As also mentioned in that other issue we do alread have a solution for the map (implemented for OSM). All we need to do is to apply this to Gmaps as well.

This would be #7511 then. Marking this issue as duplicate and closing it.

**Comment by bekuno** [comment] 2020-07-16 19:55
My idea pointed to another problem. If both caches are on the same position then only the random top most is visible. if we move both a little bin away from each other then you see that there  are more than one.

**Comment by moving-bits** [comment] 2020-07-16 20:06
Ah, then I misunderstood you. Personally I'm not too fond of moving caches around, displaying them at a different position, but I'll reopen this issue anyway for further discussion.

**Comment by Lineflyer** [comment] 2020-07-16 20:17
I would not move icons for this but maybe define an icon representing multiple icons on same position. e.g. a circle with the amount.

**Comment by jonas-koeritz** [comment] 2020-08-03 07:40
So we need a marker clustering algorithm and representation...maybe implementing the maps as fragments and doing a partial rewrite is worth the effort in the future.

**Comment by jonas-koeritz** [comment] 2020-08-03 07:41
Or even my proposed solution that involved moving to GMapsv3 and embedding OSM is worthwhile. I understand the concern but this would remove loads of duplicate code and add additional features to the map view.

**Comment by rsudev** [comment] 2020-08-03 07:56
For the code-duplication issue I'd rather drop GMaps in favour of OSM than requiring GMaps as prerequisite for c:geo.
Another solution is to again to implement the map functionalities in an abstract fashion as it was in the gmapsv1/mapsforgev3 version (but better).
My intention with the maspforgev6 version was to enable that, but unfortunately did the gmapsv2 implementation ignore all of that.

**Comment by jonas-koeritz** [comment] 2020-08-03 14:34
Currently there is no official way to show a Google map outside of a Google Maps MapView. But there is a way to show OSM Maps inside that View as well.
That's why I've proposed that solution.

I definitely understand the concern that this leads to a Google library being included in c:geo but I think for the "average user" the solution might be the better one (rotatable maps, unified user interface, familiar gestures etc.).

Maybe having a Google-less build variant would be an option? Users that don't want anything by Google on their Android based phone (apart from the OS...) won't be using the play store as well, so distribution on alternative channels is a must for them as well.

This is definitely just my opinion and I really don't want to force that on somebody but I don't think it will be easy to maintain two map implementations forever. Maybe there is a third option I'm not aware of yet?
Could somebody do some "market research" to see what kind of capable map views there are?

**Comment by moving-bits** [comment] 2020-08-03 16:00
> Or even my proposed solution that involved moving to GMapsv3 and embedding OSM is worthwhile. I understand the concern but this would remove loads of duplicate code and add additional features to the map view.

On a quick glance I really liked the implementation you had shwon us then, because of it's simplicity in maintenance, ease of use etc. - But then I also share the concerns about being dependant on a google maps lib. Not only because it's google, but because they may change their business model any time (and have done so for other components in the past).

From an implementation perspective I do see the extra work this is imposing on us, having to maintain two different libs. Sometimes a feature or bug fix is easier to implement on the google maps side, sometimes it's easier on the OSM side, no clear winner in this regard. I try to avoid code duplication in this map context wherever it's possible, but in some regards the two implementations are too different, so that things have to be implemented twice. Maybe @rsudev's proposal of integrating both via a common abstraction layer, like we had for GMv1 and old Mapsforge, can help here a bit, but that still leaves the extra work due to slightly different concepts.

In the end, if we decide to no longer support two different implementations, I would vote for OSM, with c:geo being a FOSS product.

OTOH there is so much that could be done anyway in terms of unifying the user interface, cleaning up old code etc., some really nice things you had shown us early previews for, looking very promising!

IMHO it would be really worth a try to implement those things, ideally streamlining/unifying the underlying map related code along the way.

To ease this a bit, I would also vote for dropping the old Mapsforge v3 implementation, to reduce the work, and to be able to make use of the many new features (and easier handling) the more recent Mapsforge libs provide us with. (If someone still needs the MFv3 maps or implementation for one reason or the other, then there's our legacy version.)

**Comment by jonas-koeritz** [comment] 2020-08-03 16:03
One of my concerns is that the Mapsforge MapView isn't very capable (e.g.
no rotation), Mapsforge rendering is nice but the MapView is very limited
IMO.

moving-bits <notifications@github.com> schrieb am Mo., 3. Aug. 2020, 18:00:

**Comment by moving-bits** [comment] 2020-08-03 16:05
> I definitely understand the concern that this leads to a Google library being included in c:geo but I think for the "average user" the solution might be the better one (rotatable maps, unified user interface, familiar gestures etc.).

Though I understand (but not necessarily share in all aspects) the described user perspective, IMHO there's more to it we have to take into consideration (eg. volatile usage policies etc.)

> Maybe having a Google-less build variant would be an option? Users that don't want anything by Google on their Android based phone (apart from the OS...) won't be using the play store as well, so distribution on alternative channels is a must for them as well.

But that would still leave us with having to implement / maintain two map implementations, in this case even divided into two apps. A support's and coding nightmare, I fear.

> This is definitely just my opinion and I really don't want to force that on somebody 

This discussion is very welcomed, thanks for bringing it up. IMHO it helps us to find a common focus on where to put our efforts into.

**Comment by moving-bits** [comment] 2020-08-03 16:08
> One of my concerns is that the Mapsforge MapView isn't very capable (e.g. no rotation), Mapsforge rendering is nice but the MapView is very limited IMO. 

Recent Mapsforge versions do support a lot more than what we use in c:geo today. Some things (eg.: multi map rendering, multilingual support etc.) have been added by us recently, others (eg.: POI search) not yet. There's even a rotation capable variant available, but I haven't compared the version we use with that. Sadly, documentation for Mapsforge is more of a "read the source" type :-)

**Comment by Lineflyer** [comment] 2021-04-26 14:19
Duplicate of #7511

**Closed by Lineflyer** 2021-04-26 14:19 UTC
Labels: Feature Request
