### ISSUE TITLE
CI fails constantly for Geocoder test (GRPC failed)

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#7729] opened 2019-07-17 20:20 UTC
As you might have already seen for my PR tests on CI we almost constantly have the problem of the failing geocoder test.

```
java.lang.RuntimeException: java.io.IOException: grpc failed
at io.reactivex.internal.util.ExceptionHelper.wrapOrThrow(ExceptionHelper.java:46)
at io.reactivex.internal.observers.BlockingMultiObserver.blockingGet(BlockingMultiObserver.java:93)
at io.reactivex.Single.blockingGet(Single.java:2835)
at cgeo.geocaching.address.GeocoderTest.testGeocoder(GeocoderTest.java:58)
at cgeo.geocaching.address.GeocoderTest.testAndroidGeocoder(GeocoderTest.java:35)
at java.lang.reflect.Method.invoke(Native Method)
at junit.framework.TestCase.runTest(TestCase.java:168)
at junit.framework.TestCase.runBare(TestCase.java:134)
at junit.framework.TestResult$1.protect(TestResult.java:115)
at android.support.test.internal.runner.junit3.AndroidTestResult.runProtected(AndroidTestResult.java:77)
at junit.framework.TestResult.run(TestResult.java:118)
at android.support.test.internal.runner.junit3.AndroidTestResult.run(AndroidTestResult.java:55)
at junit.framework.TestCase.run(TestCase.java:124)
at android.support.test.internal.runner.junit3.NonLeakyTestSuite$NonLeakyTest.run(NonLeakyTestSuite.java:63)
at junit.framework.TestSuite.runTest(TestSuite.java:243)
at junit.framework.TestSuite.run(TestSuite.java:238)
at android.support.test.internal.runner.junit3.DelegatingTestSuite.run(DelegatingTestSuite.java:103)
at android.support.test.internal.runner.junit3.AndroidTestSuite.run(AndroidTestSuite.java:69)
at android.support.test.internal.runner.junit3.JUnit38ClassRunner.run(JUnit38ClassRunner.java:103)
at org.junit.runners.Suite.runChild(Suite.java:128)
at org.junit.runners.Suite.runChild(Suite.java:27)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
at android.support.test.internal.runner.TestExecutor.execute(TestExecutor.java:59)
at android.support.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:262)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1879)
Caused by: java.io.IOException: grpc failed
at android.location.Geocoder.getFromLocationName(Geocoder.java:178)
at cgeo.geocaching.address.AndroidGeocoder$1.call(AndroidGeocoder.java:46)
at cgeo.geocaching.address.AndroidGeocoder$1.call(AndroidGeocoder.java:42)
at io.reactivex.internal.operators.observable.ObservableDefer.subscribeActual(ObservableDefer.java:33)
at io.reactivex.Observable.subscribe(Observable.java:12267)
at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:38)
at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:26)
at java.util.concurrent.FutureTask.run(FutureTask.java:237)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
at java.lang.Thread.run(Thread.java:818)
```

We used to discuss this already in #6692 ( @kumy) 

Searching the internet for it I have learned, that this often is an issue of SDK of the emulator and/or configuration of the emulated device.

My personal impression is, that this occurs much more often since we changed away from the hosted slaves via @kumy back to the slaves at @mucek4 machine.

I would highly appreciate if someone can try to tackle this. Meaningful CI results would be very helpful ;(

**Comment by bekuno** [comment] 2019-09-08 20:39
at cgeo.geocaching.address.GeocoderTest.testGeocoder(GeocoderTest.java:58)
calls
at cgeo.geocaching.address.AndroidGeocoder$1.call(AndroidGeocoder.java:42)
at cgeo.geocaching.address.AndroidGeocoder$1.call(AndroidGeocoder.java:46)
at android.location.Geocoder.getFromLocationName(Geocoder.java:178)
then we have the
java.io.IOException: grpc failed

The documentation for Geocoder.getFromLocationName is
https://developer.android.com/reference/android/location/Geocoder.html#getFromLocationName(java.lang.String,%20int)

**Comment by eddiemuc** [comment] 2020-07-16 11:14
Since this bug is already quite old, I assume you already gathered info about it. It looks like the related bug might not be closed by Google yet. Have you already onsidered using the Geocoding API Webservice instead?
https://github.com/googlemaps/google-maps-services-java 

Gradle e.g.
`api 'com.google.maps:google-maps-services:0.10.2'`
Code e.g.
`val geoApiCtx = GeoApiContext.Builder()
            .apiKey(Util.readGoogleApiKey(ctx))
            .build()

        val addresses = GeocodingApi.reverseGeocode(geoApiCtx, loc).await()`

INfo comes from this helpful stackover thread:
[https://stackoverflow.com/questions/47331480/geocoder-getfromlocation-grpc-failed-on-android-real-device?rq=1]

Android bug reports:
* https://issuetracker.google.com/issues/64418751?pli=1 
* https://issuetracker.google.com/issues/64247769

**Comment by bekuno** [comment] 2020-07-16 12:07
The google mals services is no solution:
~~~
The Java Client for Google Maps Services is designed for use in server applications. This library is not intended for use inside of an Android app, due to the potential for loss of API keys.
~~~

**Comment by eddiemuc** [comment] 2020-07-16 13:14
In that case I would consider accepting the failing test case as "ok" until the issue is solved on Google side (after all, same test also accepts if in executing environment the Geocoder service is simply not available)

**Comment by eddiemuc** [comment] 2020-07-16 18:35
Added PR #8645 to fix

**Comment by Lineflyer** [comment] 2020-07-16 18:49
Thanks @eddiemuc for addressing this inconvenient issue on our CI.

**Comment by eddiemuc** [comment] 2020-07-17 05:35
You're very welcome, I hope it helps

**Comment by moving-bits** [comment] 2020-07-18 10:34
Workaround seems to work fine, therefore closing this issue.

**Closed by moving-bits** 2020-07-18 10:34 UTC
Labels: CI server / Build tools, Prio - High
