### ISSUE TITLE
Option to update caches - already saved - based on map selection

### ISSUE THREAD

**Issue by Cappa-d** [cgeo/cgeo#6529] opened 2017-04-27 10:00 UTC
Right now you have the option to save caches shown on the live map to a list and have them available offline. That feature is good, but like a second step  / option is missing imho. 

If you have the live map open and you have caches in the area already saved but maybe a longer time ago you want to update just these caches you see. Right now this means go into every cache and update it as the whole list they are stored on is maybe too much.

Wouldn't it be possible to have an menu option to update the caches seen in the live map like you are able to save them? Like offline update or so.

**Comment by SammysHP** [comment] 2017-04-27 10:17
Duplicate of #5136 and #5137.

**Closed by SammysHP** 2017-04-27 10:17 UTC
