### ISSUE TITLE
Inconsistent routing behaviour depending on map source

### ISSUE THREAD

**Issue by andrixnet** [cgeo/cgeo#9654] opened 2021-01-03 13:54 UTC
**Describe the bug:**
There are several inconsistent behaviours using the routing function (having brouter installed) in c:geo depending on the map source (Google vs OSM/online/offline). 
It may have to do with the map display library, since rendering Google maps has different +/- zoom buttons. 

First of all, using OSM online/offline one has 2 buttons in the cache popup: 
**button-1:**
![btn-1](https://user-images.githubusercontent.com/3382777/103479575-4f610d80-4dd7-11eb-8cb3-5790f8997623.png)
**button-2:**
![btn-2](https://user-images.githubusercontent.com/3382777/103479580-54be5800-4dd7-11eb-8ebb-9e48737fe630.png)

Using Google maps there is only one button in the cache popup:
**button-1:**
![btn-1](https://user-images.githubusercontent.com/3382777/103479575-4f610d80-4dd7-11eb-8cb3-5790f8997623.png)

Perhaps this UI logic remained unchanged since an earlier version that perhaps did not fully support routing. 

Anyway ...

### To Reproduce:

All scenarios: have brouter app installed, with maps for your region of interest; have c:geo map->routing set to "car". 

**Scenario 1:**
1. open map
2. set map layer to OSM family, either online or offline
3. click on a cache to see cache popup window
4. press button-2 (route to cache). a route is calculated and shown
5. change between map layers only of OSM type, either online or offline. **The route is correctly shown each time.**
6. **INCONSISTENCY:** change to Google map. **The route dissapears.** Changing back to OSM map doesn't restore it. One has to perform steps 3-4 again.

**Scenario 2:**
1. open map
2. set map layer to Google family
3. click on a cache to see cache popup window
4. press button-1 (navigate to cache cache). a route is calculated and shown (not straight line) and map scale changes.
5. change between map layers (any OSM layer). **The route is correctly shown each time.**
6. problem described in scenario 1 does not happen.

**INCONSISTENCY 1:** 
- after step 5, press back. You arrive at cache popup screen you started at. Press back again (or outside the popup). You are returned to the map.
- press layers button. Despite the fact that Google map is the one shown, the dropdown shows the checkmark according to your last selection at step 5 above. If you press back to go to main menu and then map, the map will show the layer according to the last selection at step 5 above.

This only happens when starting Scenario 2 on the Google map layer. If you start scenario 2 on OSM layer and perform the same steps, the inconsistency does not happen. 

If you start scenario 2 on OSM layer and perform step 5 to Google map, the following will happen: 
**INCONSISTENCY 2:** 
- after step 5, press back. You arrive at cache popup screen you started at. The map is empty. Press back again (or outside the popup). You are returned to the map. The map is still empty.
- press layers button. Google map is shown as selected. Switching to any Google source will result in empty map. You will also note that the zoom buttons are those corresponding to the OSM maps. 
- there are 2 ways of returning to normal behaviour:
a. go back to main screen then press on map
b. switch to an OSM layer, then switch back to Google layer 

-------

button-1 cascades the click flow such that one can return to the initiating state: the open cache popup window (using back). Also, when using it, no other caches are shown.

button-2 shows route on the map without changes in the flow. All visible caches are shown. pressing back goes to main screen.

**_Regarding scenario 1:_**
It seems fairly obvious that showing a route (not straight line) works on both map libraries. (at least from user perspective).
So I see no reason why the route button should be missing on Google layer (unless some explicit requirements by Google - are there any?). 

If the route button-2 is enabled on Google layer, calculated route should be maintained (or recalculated) when switching to that layer. 

**_Regarding scenario 2:_**
Layer switching while going through the open/close(back) click flow should remain consistent. (and working)

**Version of c:geo used:**
2020.12.03

**Is the problem reproducible:**
Yes - always

**System information:**
```
--- System information ---
Device: SM-G965F (star2ltexx, samsung)
Android version: 9
Android build: PPR1.180610.011.G965FXXS7CSK4
c:geo version: 2020.12.03
Google Play services: enabled - 20.47.13 (100400-344095733)
Low power mode: inactive
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: rotation vector
Hide caches: own/found disabled archived
Hide waypoints: -
HW acceleration: enabled (default state)
System language: en_GB
System date format: dd/MM/y
Debug mode active: no
System internal c:geo dir: /data/user/0/cgeo.geocaching (189.8 GB free) internal
User storage c:geo dir: /storage/emulated/0/cgeo (189.7 GB free) external non-removable
Geocache data: /storage/emulated/0/Android/data/cgeo.geocaching/files/GeocacheData (189.7 GB free) external non-removable
Database: /storage/emulated/0/Android/data/cgeo.geocaching/files/databases/data (6.4 MB) on user storage
GPX import path: /storage/emulated/0/gpx
GPX export path: /storage/emulated/0/gpx
Offline maps path: /storage/emulated/0/maps/mapsforge
Map render theme path:
Live map mode: true
Global filter: display all caches
Fine location permission: granted
Write external storage permission: granted
Geocaching sites enabled:
geocaching.com: Logged in (Login OK) / BASIC
Geocaching.com date format: yyyy-MM-dd
Installed c:geo plugins: none
BRouter connection available: true
--- End of system information ---
```

**Comment by moving-bits** [comment] 2021-01-04 09:43
> First of all, using OSM online/offline one has 2 buttons in the cache popup:
> 
> Using Google maps there is only one button in the cache popup:
> 
> Perhaps this UI logic remained unchanged since an earlier version that perhaps did not fully support routing.

This is a somewhat older difference between OSM supporting "set as target" from cache/waypoint popup and Google Maps not supporting it, see #7969. This will be obsolete with the upcoming release since the implementation of #9492.

**Comment by Lineflyer** [comment] 2021-01-04 10:41
> press button-1 (navigate to cache cache). a route is calculated and shown (not straight line) and map scale changes.

In order to understand scenario 2:
The action behind this button depends on the default tool which you assigned for your preferred navigation. It seems you changed it away from the default in c:geo Settings - Navigation.
What are your assignments there for the two preferred navigation methods?

**Comment by andrixnet** [comment] 2021-01-06 21:16
I found through experience that compass navigation method is mostly useless in anything but empty fields or dense forests (featureless map areas) and distances >30m. Consequently indeed, the first thing I did after installing c:geo was to change default navigation method.

My settings: 
Default navigation = Map
Secondary navigation = compass.

**Comment by fm-sys** [comment] 2021-08-31 07:28
I can't reproduce szenario 2 (anymore?) and szenario 1 is no longer valid. I would vote for closing this issue...

**Closed by fm-sys** 2021-08-31 07:28 UTC
Labels: Bug, Unverified
