### ISSUE TITLE
Description of GCHK9B is truncated

### ISSUE THREAD

**Issue by SundialServices** [cgeo/cgeo#7322] opened 2019-02-22 17:04 UTC
The description of GCHK9B, "The Legend of MonkeyBrad," consists of two paragraphs, several blank lines, and then several paragraphs of additional text.  C:Geo does not display this additional content.

**Comment by Lineflyer** [comment] 2019-02-22 17:40
What version of c:geo are you using?

**Comment by Cornell73** [comment] 2019-02-22 20:31
Hello ... I have the same problems ... c:geo Version 2018-10-13 ... Can you help? ... Thanks in advanced

**Comment by Lomanic** [comment] 2019-02-23 00:26
I don't reproduce in beta (2019.02.22-RC), seems to be a duplicate of  #7291 or even #7305 .

**Comment by Lineflyer** [comment] 2019-02-23 10:29
Yes, pretty sure.

**Closed by Lineflyer** 2019-02-23 10:29 UTC

**Comment by Cornell73** [comment] 2019-02-23 10:45
Ok, thats meens nothing can help?

**Comment by Lineflyer** [comment] 2019-02-23 11:46
No, it means its already solved and should work when you upgrade to the version released today.

**Comment by Cornell73** [comment] 2019-02-23 12:36
Aaaaaaah, ok ... Later i will check for update und than i wll see if it works ... Thanks for your help and have a nice weekend ... Greets Christian

**Comment by Cornell73** [comment] 2019-02-23 13:43
Update of c:geo well done ... Everything works fine ... Cachedetails have to update and then de discription can be read ... THANK YOU! ... Great work and many thanks to the team!
