### ISSUE TITLE
language problems

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#5430] opened 2016-02-01 09:29 UTC
Some people on FB report again problems of cache count not loading and some cache information missing. After manual login on the website and switch to english it was solved.
People already using 2016.01.19

**Comment by samueltardieu** [comment] 2016-02-01 09:30
Would that mean that the switch to English does not work?

**Comment by rsudev** [comment] 2016-02-01 09:34
Confirmed. retrieveing log count works on master due to changes by @Bananeweizen , but switch to english does not (for me)

**Comment by rsudev** [comment] 2016-02-01 09:51
They again changed the id of the target control for switching to english. So we should rather extract that from the page instead of hard-coding it.

**Comment by Lineflyer** [comment] 2016-02-01 12:08
Anyway we should wait until tomorrow as a major website change is upcoming anyway (logbook changes). Greetings from Malaysia....so unavaiable for testing anything.

**Comment by Bananeweizen** [comment] 2016-02-01 17:50
At least for me that change seems to be the only necessary modification. My local release branch works fine with that. Or did I miss something else?

**Comment by rsudev** [comment] 2016-02-01 20:48
If I read it correctly, it requires english to stay the first available option (as it should match with all options, according to my limited understanding of regex). This sounds like a reasonable assumption to me, so it should be fine.

**Comment by rsudev** [comment] 2016-02-03 21:57
Already fixed by a8742e1

**Closed by rsudev** 2016-02-03 21:57 UTC
Labels: Bug
