### ISSUE TITLE
C:geo crashed after clicked wear button

### ISSUE THREAD

**Issue by eezau** [cgeo/cgeo#5001] opened 2015-06-01 13:53 UTC
I have Sony smartwatch 3. Android version 5.1.1 and wear 1.1.1.1929530.
my phone is Motorola Moto G (2nd gen.). Android 5.0.2. Newest c:geo.
I downloaded c:geo wear. Phone c:geo crashed everytime when I clicked wear button in c:geo.

**Comment by rsudev** [comment] 2015-06-01 13:56
Duplicate of #4829.

**Closed** 2015-06-01 13:57 UTC
