### ISSUE TITLE
Message Center link

### ISSUE THREAD

**Issue by AlphaDeltaIndigo** [cgeo/cgeo#6418] opened 2017-03-21 11:52 UTC
##### Detailed steps causing the problem:
- Open details page of cache 
- Click on cache owner name
- Click on "Send Message"

OR

- Open logbook page of cache 
- Click on username
- Click on "Send Message"

##### Actual behavior after performing these steps:
- Webpage opens on google chrome, link = "Send Email to (Username)"

##### Expected behavior after performing these steps:
- Webpage opens on google chrome, link = "New Message to (Username)" on Message Center

##### Version of c:geo used:
2017-03-19

##### Is the problem reproducible for you?
Yes

##### System information:
```
Attach system information here if available (see c:geo menu -> About c:geo -> Swipe right to System)
Keep the apostrophe at beginning and end to have it properly formatted
```

##### Other comments and remarks:
e.g. Reference to other issues, projects, sources, etc.

**Comment by SammysHP** [comment] 2017-03-21 12:11
Duplicate of #5352.

**Closed by SammysHP** 2017-03-21 12:11 UTC
