### ISSUE TITLE
Date picker returns wrong date for logging

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#11411] opened 2021-08-04 12:37 UTC
### Describe your problem!

Two users independently reported the following bug for version 2021.07.30-RC:

When I select a logdate which is not today but some days in the past, after closing the date picker the shown date is one day earlier than selected.
It does seemingly never happen if the date is today but for all dates in the past.

---

I myself cannot reproduce it.
Maybe an issue depending on locale and/or timezones?

### How to reproduce?

- Start logging a cache
- Tap on the date to open the date picker
- Set it e.g. to 15th of July 2021
- Select OK to close the date picker

### Actual result after these steps?

Log date field in logging activity shows 14th of July 2021

### Expected result after these steps?

Log date field in logging activity shows 15th of July 2021

### Reproducible

Unclear

### c:geo Version

2021.07.30-RC

### System information

```shell
Example for one user:

## System information

c:geo version: 2021.07.30-RC

Device:
-------
- Device type: SM-G991U (o1qsqw, samsung)
- Available processors: 8
- Android version: 11
- Android build: RP1A.200720.012.G991USQS4AUFD
- Screen resolution: 1080x2176px (360x725dp)
- Sailfish OS detected: false
- Google Play services: enabled - 21.26.20 (150408-387585197)
- HW acceleration: enabled (default state)

Sensor and location:
-------
- Low power mode: inactive
- Compass capabilities: yes
- Rotation vector sensor: present
- Orientation sensor: present
- Magnetometer & Accelerometer sensor: present
- Direction sensor used: rotation vector

Program settings:
-------
- Filters:
    LIVE: Status:Exclude Archived ([:inconclusive=false:advanced=false]status:exclude_archived)
    OFFLINE: None ([:inconclusive=false:advanced=false])
- Hide waypoints: original
- Set language: en_US (system default)
- System date format: M/d/yy
- Debug mode active: no
- Live map mode: false
- OSM multi-threading: true / threads: 4
- Last backup: Aug 2, 4:14 PM
- Routing mode: Walk
- Settings: v8, Count:132
- Map: Google: Satellite
  - Id: cgeo.geocaching.maps.google.v2.GoogleMapProvider$GoogleSatelliteSource
  - Atts: none
  - Theme: none

Services:
-------
- Geocaching sites enabled:
   geocaching.com: Logged in (Login OK) / PREMIUM
   Geocaching.com Adventure Lab
- Geocaching.com date format: MM/dd/yyyy
- Routing: internal / BRouter installed: false
- Installed c:geo plugins:  none

Permissions & paths:
-------
- Fine location permission: granted
- Write external storage permission: granted
- System internal c:geo dir: /data/user/0/cgeo.geocaching (38.2 GB free) v2 internal isDir(6 entries)
- Legacy User storage c:geo dir: /storage/emulated/0/cgeo (38.2 GB free) v2 external non-removable isDir(8 entries)
- Geocache data: /storage/emulated/0/Android/data/cgeo.geocaching/files/GeocacheData (38.2 GB free) v2 external non-removable isDir(2289 entries)
- Internal theme sync (is turned off): /data/user/0/cgeo.geocaching/MapThemeData (38.2 GB free) v2 internal isDir(0 entries)
- Public Folders: #11
  - BASE: /cgeo (User-Defined)[/cgeo[DOCUMENT#0:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo, Av:true, files:>=6, dirs:>=26, totalFileSize:>=115.2 MB, free space: 38.2 GB, files on device: 13511677)
  - OFFLINE_MAPS: /cgeo/maps (Default)[/cgeo/maps[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/maps]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Fmaps, Av:true, files:0, dirs:1, totalFileSize:0 B, free space: 38.2 GB, files on device: 13511677)
  - OFFLINE_MAP_THEMES: /cgeo/maps/_themes (Default)[/cgeo/maps/_themes[PERSISTABLE_FOLDER(OFFLINE_MAPS)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/maps/_themes]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Fmaps%2F_themes, Av:true, files:0, dirs:0, totalFileSize:0 B, free space: 38.2 GB, files on device: 13511677)
  - LOGFILES: /cgeo/logfiles (Default)[/cgeo/logfiles[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/logfiles]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Flogfiles, Av:true, files:2, dirs:0, totalFileSize:2.1 MB, free space: 38.2 GB, files on device: 13511677)
  - GPX: /cgeo/gpx (Default)[/cgeo/gpx[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/gpx]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Fgpx, Av:true, files:0, dirs:0, totalFileSize:0 B, free space: 38.2 GB, files on device: 13511677)
  - BACKUP: /cgeo/backup (Default)[/cgeo/backup[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/backup]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Fbackup, Av:true, files:>=6, dirs:>=19, totalFileSize:>=113.4 MB, free space: 38.2 GB, files on device: 13511677)
  - FIELD_NOTES: /cgeo/field-notes (Default)[/cgeo/field-notes[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/field-notes]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Ffield-notes, Av:true, files:0, dirs:0, totalFileSize:0 B, free space: 38.2 GB, files on device: 13511677)
  - SPOILER_IMAGES: /cgeo/GeocachePhotos (Default)[/cgeo/GeocachePhotos[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/GeocachePhotos]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2FGeocachePhotos, Av:true, files:0, dirs:0, totalFileSize:0 B, free space: 38.2 GB, files on device: 13511677)
  - ROUTING_BASE: /cgeo/routing (Default)[/cgeo/routing[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/routing]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Frouting, Av:true, files:7, dirs:1, totalFileSize:81.2 KB, free space: 38.2 GB, files on device: 13511677)
  - ROUTING_TILES: /cgeo/routing/segments4 (Default)[/cgeo/routing/segments4[PERSISTABLE_FOLDER(ROUTING_BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/routing/segments4]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Frouting%2Fsegments4, Av:true, files:0, dirs:0, totalFileSize:0 B, free space: 38.2 GB, files on device: 13511677)
  - TEST_FOLDER: [Legacy]/data/user/0/cgeo.geocaching/files/unittest (Default)[/data/user/0/cgeo.geocaching/files/unittest[FILE#1:p-file:///data/user/0/cgeo.geocaching/files::/unittest]] (Uri: file:///data/user/0/cgeo.geocaching/files/unittest, Av:true, files:0, dirs:0, totalFileSize:0 B, free space: 38.2 GB, files on device: -1)
- Map render theme path:
- PersistedDocumentUris: #1
- TRACK: null
- Persisted Uri Permissions: #1
  - content://com.android.externalstorage.documents/tree/primary%3Acgeo (Apr 7, 6:54 AM):RW
- Database: /data/user/0/cgeo.geocaching/databases/data (v96, Size:113.4 MB) on system internal storage

--- End of system information ---
```

**Comment by fm-sys** [comment] 2021-08-04 15:09
As I've touched the code recently, I have an idea what the problem could be:

When closing the date picker, the previous time will be added to the entered date. This is done due to the fact, that e.g. GeoKrety supports entering of time additional to the date. I wonder why the problem shows up in the  current beta, as the behavior was the same in previous versions. 

So a workaround could be to reset the time to 0:00 if the date is changed.

However, could you ask for their time zone so we can try to reproduce and find a better solution?

**Comment by eddiemuc** [comment] 2021-08-04 15:11
Related idea: we might want to add the timezone of the user to the system information

**Comment by fm-sys** [comment] 2021-08-04 15:38
> Related idea: we might want to add the timezone of the user to the system information


Already had the same idea ;-)

I added it to my private cgeo-ToDo-list, be feel free to open up an issue if you like...



> However, could you ask for their time zone so we can try to reproduce and find a better solution?

Oh and another thing: Please ask for the approximate time when the user had tried to create the log as well.

Reason: If you log a cache at 23:00 and change the date to yesterday, the stored time stamp is "yesterday 23:00". Together with potential unwanted time zone overlays this might result in a date roll-over...

**Comment by Lineflyer** [comment] 2021-08-04 16:44
Just now we received two more of the same user reports with wrong log date.
I wonder why they are only reported right now for 2021.07.30-RC.

Either something indeed changed codewise only with latest RC or its just a coincidence as e.g. some users discussed that topic and some of those contacted us in parallel.

**Comment by Lineflyer** [comment] 2021-08-04 16:48
I just passed around a video file regarding this issue (to cgeo-dev@...).

**Comment by Lineflyer** [comment] 2021-08-04 19:41
User 1:
I am in the Eastern time zone.  I first noticed this around 23:00 last night.  I was able to replicate this right now (13:00).  I have not tried in the morning yet.

**Comment by Lineflyer** [comment] 2021-08-04 19:41
User 2:
the phone is set to central daylight time. I noticed the date problem only once before which was yesterday evening. Not sure when it started or know of any other times it's done this.

**Comment by Lineflyer** [comment] 2021-08-04 19:55
I can reproduce it on Android 10 emulator by setting the time zone to some US time zone (I tested UTC-10 (Hawaii) and UTC-4 (New York)).  Both show this problem reproducibly.
If I set it to Germany (UTC+2) it looks normal.

Time of test device was 1:31PM UTC+2

**Comment by fm-sys** [comment] 2021-08-04 20:00
Ok, just made the same experience. The issue seems reproducible for all negative time zones independent of the daytime...

**Comment by Lineflyer** [comment] 2021-08-04 20:10
I tested with branch `preUI_release`. No problem there.

**Comment by Lineflyer** [comment] 2021-08-04 20:16
Thats a perfect opportunity to test `git bisect`. Will be my evening work now.

**Comment by Lineflyer** [comment] 2021-08-04 20:24
And here we go...nice tool:

```
8d709ffb53c1e8f634d64ac6578e3d1dd4602787 is the first bad commit
commit 8d709ffb53c1e8f634d64ac6578e3d1dd4602787
Author: fm-sys <64581222+fm-sys@users.noreply.github.com>
Date:   Sat Jul 17 23:31:34 2021 +0200

    migrate date and time dialog to material (fix #11223)

 .idea/checkstyle-idea.xml                          |   2 +-
 main/res/layout/date_range_selector_view.xml       |  26 +++-
 main/src/cgeo/geocaching/log/LogCacheActivity.java |   2 +-
 .../cgeo/geocaching/log/LogTrackableActivity.java  |   2 +-
 main/src/cgeo/geocaching/ui/DateRangeSelector.java |   6 +-
 main/src/cgeo/geocaching/ui/DateTimeEditor.java    | 148 +++++++--------------
 6 files changed, 72 insertions(+), 114 deletions(-)
```

Now its your job to track the problem down in that commit.

**Comment by eddiemuc** [comment] 2021-08-04 20:34
Have no chance to look in code right now, but my guess is that the date picker returns a date set to 0:00 (midnight) of the picked day for GMT+/- 0. And whenever you are in a negative timezone this is then represented as the previous day (midnight minus x hours is previous day)

**Comment by Lineflyer** [comment] 2021-08-04 20:39
Sound likely. So the new date picker behaves somehow different to the old one when it comes to timezones.

**Comment by fm-sys** [comment] 2021-08-05 09:46
The new date picker handles time zone offsets differently than the old one. Possible solution I found on SO:

https://stackoverflow.com/a/66041015/13513639
```
MaterialDatePicker<Long> materialDatePicker=materialDateBuilder.build();
materialDatePicker.addOnPositiveButtonClickListener(new MaterialPickerOnPositiveButtonClickListener<Long>() {
        @Override
        public void onPositiveButtonClick(Long selection) {
            // Get the offset from our timezone and UTC.
            TimeZone timeZoneUTC = TimeZone.getDefault();
            // It will be negative, so that's the -1
            int offsetFromUTC = timeZoneUTC.getOffset(new Date().getTime()) * -1;
            // Create a date format, then a date object with our offset
            SimpleDateFormat simpleFormat = new SimpleDateFormat("yyyy-MM-dd", Locale.US);
            Date date = new Date(selection + offsetFromUTC);

            mEt_last_date_to_apply.setText(simpleFormat.format(date));
        }
    });

```

**Comment by fm-sys** [comment] 2021-08-07 21:28
Should (hopefully) be fixed with https://github.com/cgeo/cgeo/pull/11431

**Closed by fm-sys** 2021-08-07 21:28 UTC
Labels: Bug, Unverified, Google Play or Beta feedback
