### ISSUE TITLE
After submitting log, no linebreaks in log displayed

### ISSUE THREAD

**Issue by dcjkfgdjhd** [cgeo/cgeo#13869] opened 2023-01-15 09:01 UTC
### Describe your problem!

After submitting a log, c:geo displays the log immediately in the "logs" tab. But if the log text contained paragraphs/line breaks, these are invisible in this log. It will be displayed as one big blob of text.

However, the logtext correctly gets sent to the GC.com website, including the line breaks. After refreshing the cache in c:geo, the linebreaks then also correctly show up in c:geo.

### How to reproduce?

See above.

### Reproducible

Yes

### c:geo Version

2022.12.21

**Comment by Lineflyer** [comment] 2023-01-15 09:23
Are you sure about the line breaks?
What is the case is, that we do AFAIK not have markdown parser ourselves but use the rendered HTML from the server which is only available after refreshing the cache. This means, that e.g. links, horizontal lines and other markdown formattings might be missing. But line breaks should work IMHO.

**Comment by dcjkfgdjhd** [comment] 2023-01-15 10:01
Yes, I am sure. Just observed this behaviour multiple times yesterday.

I just used multiple paragraphs (by twice pressing "enter" on Android keyboard to create an empty line) to structure the text. In the preview, before refresh, that was not there, just one big paragraph.

**Comment by wolverine007** [comment] 2023-01-17 05:57
Recognized the same somewhere in the past - a fresh log is displayed without any linebreaks. 

If I could remember correctly, the found status is also not updated in this case and the cache is staying visible on the map with the "hide found caches" filter being applied. 

Are we maybe doing a refresh of the listing in the background, when the log has been transfered?

**Comment by eddiemuc** [comment] 2023-01-29 16:56
I can't reproduce this, but maybe I didn't understand the issue correctly?

I entered a sample text like this:
![image](https://user-images.githubusercontent.com/6909759/215342096-456f0e43-017c-4344-81c3-ff4dc0bcdeaa.png)

I sent this log, this results in c:geo displaying the "pure" text. It is not yet rendered by the server, notice the emoji-tag at the end. But it contains the line breaks correctly:
![image](https://user-images.githubusercontent.com/6909759/215342138-7969fb6c-2e92-41a6-aee3-a21990901609.png)

When I refresh the cache, then c:geo displays the "server" text, including the emoji and also the line breaks:
![image](https://user-images.githubusercontent.com/6909759/215342176-34d6ca22-338a-404a-933c-a536aebb93de.png)

Any specific circumstances where this is happening?

**Comment by dcjkfgdjhd** [comment] 2023-01-29 17:17
Yes, that is exactly what I did and the linebreak was gone, multiple times.

But I just tested it again, and also could not reproduce the problem. Will keep observing if it happens again.

**Comment by eddiemuc** [comment] 2023-01-29 17:22
> Yes, that is exactly what I did and the linebreak was gone, multiple times.

Were the line breaks gone in the "second" step (when log was not yet formatted by server), in the "third" step (after a cache refresh, when log was formatted by server) or in both steps?

Did you use anything more "advanced" in the logs like formatting markup or html tags?

**Comment by dcjkfgdjhd** [comment] 2023-01-29 17:30
After step 2. After step 3 they looked correct again.

No, nothing special, pure text.

**Comment by dcjkfgdjhd** [comment] 2023-01-29 17:30
The log was relatively long though...

**Comment by eddiemuc** [comment] 2023-01-29 18:25
I tried to reproduce with a very long log, but didn't succeed

**Comment by eddiemuc** [comment] 2023-01-29 18:36
I think I got it. I can reproduce the problem when the log text contains either the character `<` or `&`. Reason is that c:geo in this case interprets text as HTML, and HTML ignores linebreaks. (need to use `<br>` or `<p>` there)

@dcjkfgdjhd : could this be the cause of your problem? Usage of  `<` or `&` in a log?

**Comment by dcjkfgdjhd** [comment] 2023-01-29 18:45
Yes indeed 🙂

It was a bike&hike tour and I wrote that in my log.

**Comment by eddiemuc** [comment] 2023-01-29 19:17
Fixed with PR #13915

**Closed** 2023-01-30 05:59 UTC
Labels: Bug
