### ISSUE TITLE
special owner logs not possible

### ISSUE THREAD

**Issue by oconly** [cgeo/cgeo#7907] opened 2019-10-22 14:00 UTC
If You log a cache, you have only three options (DNF, found or note).
But when You are an owner, then there are more log types possible,
which c:geo doesn´t offer.

c:geo should offer the same log types which You can do via browser.
Regarding opencaching.de, these log types here are missing:
- available
- temporarily not available
- locked

**Comment by Lineflyer** [comment] 2019-10-22 14:08
Duplicate of #4134

**Closed** 2019-10-22 14:09 UTC
Labels: Feature Request, Unverified

**Comment by oconly** [comment] 2019-10-22 20:23
OK, sorry for the duplicate.
But now I know that OKAPI is already prepared for this sicne january:
https://github.com/cgeo/cgeo/issues/7240 
So when does c:geo make use of it?

**Comment by Lineflyer** [comment] 2019-10-22 20:55
As soon as there is a open source contributor is interested in implementing it. Hard to predict...thats as it is in open source projects.

**Comment by bekuno** [comment] 2019-10-22 20:56
@oconly The resources for programming c:geo (= manpower) are not very high. We would be pleased about further contributors in any case.
In the past month we have done a lot to keep c:geo generally usable. 
But an Owner Log for Opencaching is not often required compared to other features.  Maybe there will be time for implementation at some point.
