### ISSUE TITLE
choose service other than the default geocaching.com on first run after installation

### ISSUE THREAD

**Issue by brainrape** [cgeo/cgeo#5587] opened 2016-03-27 13:59 UTC
##### Detailed steps causing the problem:
- Install and start c:geo
- setup asks for geocaching.com login

##### Actual behavior after performing these steps:
default service is geocaching.com

##### Expected behavior after performing these steps:
user should be able to choose service, e.g. geocaching.de, geocaching.pl etc

##### Version of c:geo used:
all

##### Is the problem reproducible for you?
Yes

##### Other comments and remarks:
Since there are many other services suppoted besides geocaching.com, the user should be able to choose a service when setting up their geocaching account. Currently the setup only allows geocaching.com, other services have to be set up manually and there is no option to choose them after installation.

**Comment by kumy** [comment] 2016-03-27 14:18
For me it's a duplicate of #4263.
Closing this one.

**Closed by kumy** 2016-03-27 14:18 UTC
