### ISSUE TITLE
Long press menu - problem with long strings

### ISSUE THREAD

**Issue by Eselter** [cgeo/cgeo#5623] opened 2016-04-03 01:55 UTC
##### Detailed steps causing the problem:
- Open cache detail
- Long press of some word
- Expand menu

##### Actual behavior after performing these steps:
Strings don't fit on context menu. Screen:
![screenshot_20160403-031918](https://cloud.githubusercontent.com/assets/8573382/14230226/85da5106-f94e-11e5-8ddf-4a48a0021ade.png)

##### Is the problem reproducible for you?
Yes

##### System information:
--- System information ---
Device: LG-D802 (cm_d802, LGE)
Android version: 6.0.1
Android build: cm_d802-userdebug 6.0.1 MHC19J 9b915d127a test-keys
Cgeo version: 2016.04.03-NB-30ad068
Google Play services: enabled
Low power mode: active
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: rotation vector
Hide own/found: false
Map strategy: detailed
HW acceleration: enabled (default state)
System language: pl_PL
Geocaching sites enabled:
 - geocaching.com: logged in (Nazwa użytkownika OK) / BASIC
Installed cgeo plugins:  none
--- End of system information ---

##### Other comments and remarks:
When I change strings to shorter (with Apk Editor from play store) all is ok:
![screenshot_20160403-033446](https://cloud.githubusercontent.com/assets/8573382/14230240/c7f9f0fa-f94e-11e5-9400-07ee9133d25e.png)

I don't know what is the best way to solve this problem. Change to shorter strings or maybe is some other way to correct display this menu with sucha a long strings.

**Comment by Bananeweizen** [comment] 2016-04-03 06:39
GC3VWMJ

**Comment by Bananeweizen** [comment] 2016-04-03 06:53
I can reproduce this. If I append "12345678901234567890" to the "Translate to %s" standard translation, then I only see 3 or 4 characters before the numbers. All remaining strings are pushed out the screen (to the left side).

A possible solution might be to shorten the translation terms to "to %s" and "to English" (leaving out the verb). Not sure if that is grammatically okay for all languages.

**Comment by Eselter** [comment] 2016-04-03 08:59
Maybe do some limit in this string for the translators? For example: 20 chars or sth?

**Comment by Lineflyer** [comment] 2016-04-05 17:42
Is this problem specific to some android versions or some launchers? 
For me (Android 5.0.1 on Samsung S4) the whole menu shows up as an "actionbar" on top with shortcuts and three-dot button.

**Comment by Eselter** [comment] 2016-04-05 17:55
Yes this is new text selection in android marshmallow:
http://developer.android.com/about/versions/marshmallow/android-6.0-changes.html#behavior-text-selection

**Comment by Lineflyer** [comment] 2016-04-05 19:43
Seems I need a new test device :) Thanks!

**Comment by Eselter** [comment] 2016-04-05 20:01
I added shorter version to "strings translate_to_sys_lang" and "translate_to_english" for polish language on Crowdin. This fix above problem on my device. You can use them or maybe is better way for fix this problem ;]

**Comment by Eselter** [comment] 2016-04-07 00:02
One more observation. On android 6.0 we have include option to translate selected text. So maybe just delete this custom translate option from menu?
![screenshot_20160407-015814](https://cloud.githubusercontent.com/assets/8573382/14336448/68d21f08-fc64-11e5-9488-5b5d9c996056.png)
![screenshot_20160407-015840](https://cloud.githubusercontent.com/assets/8573382/14336447/68d0e50c-fc64-11e5-95c4-6c7ddffdcf68.png)

**Comment by Lineflyer** [comment] 2016-06-19 20:34
How to continue with this issue.
AFAICS the problem in polish strings was solved by shorten the strings. Open would be to decide whether we want to ommit our own implementation on Android 6.x and rely on the factory feature (is this applied on all devices or a model specific implementation).

**Comment by Bananeweizen** [comment] 2016-06-20 16:26
I'd like to close this issue (menu overflowing). It is fine to have a separate issue to discuss the removal of the translation feature depending on OS version, hardware version or whatever. But since that might take quite some time, a separate issue might help.

**Closed** 2016-06-20 16:28 UTC
Labels: Bug, Frontend Design, low
