### ISSUE TITLE
Geocache details page crashes occasionally

### ISSUE THREAD

**Issue by kirchwitz** [cgeo/cgeo#4922] opened 2015-05-06 01:08 UTC
For some months, c:geo sometimes crashes when displaying the geocache details page. Unfortunately, this bug is not reproducible (can't trigger it directly) but still happens quite often during normal use. I'm running Android 4.4.4 (Samsung S3 LTE, not rooted) with recent releases of c:geo (from Google Play store).

I've send a couple of those automated bug reports (usually like "crash while viewing cache details"), but today's crash (5.5.2015) starts with the (hopefully unique) label "AMK4711A", just in case you want to debug this specific crash.

There are two ways the crash happens.

(1) When I'm on the map screen (OpenAndroMaps locally stored) and touch a geocache icon (traditional, geocaching.com), a small overlay window opens. There I can touch "More details" to launch the geocache details page. And this is when the crashes happen.
(2) When I'm editing the "Personal note" of a geocache and touch "OK" to return to the geocache details page, then c:geo also is likely to crash.

It doesn't matter if GPS, WLAN or Mobile networks (or any combination of it) is switched on or off. There's plenty of memory and disk space available (usually, c:geo is the only app actively running). Rebooting the phone doesn't change anything.

The only common thing of all the crashes is that they always happen when the geocache details page(s) is going to be displayed. There's no crash by just switching back and forth between the sub-pages of the geocache details (like waypoints, overview, description, logs etc.)

If you need additional information, please let me know. If it helps I can assign the same "unique" label (see above) to future crash reports so they can be referenced easily.

**Comment by Lineflyer** [comment] 2015-05-06 07:29
Retrieved this from Google Play for the mentioned label:
```
java.lang.IllegalStateException: Fatal Exception thrown on Scheduler.Worker thread.
   at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:62)
   at android.os.Handler.handleCallback(Handler.java:733)
   at android.os.Handler.dispatchMessage(Handler.java:95)
   at android.os.Looper.loop(Looper.java:146)
   at android.app.ActivityThread.main(ActivityThread.java:5679)
   at java.lang.reflect.Method.invokeNative(Native Method)
   at java.lang.reflect.Method.invoke(Method.java:515)
   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1291)
   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1107)
   at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.OutOfMemoryError
   at android.graphics.BitmapFactory.nativeDecodeStream(Native Method)
   at android.graphics.BitmapFactory.decodeStreamInternal(BitmapFactory.java:727)
   at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:703)
   at android.graphics.BitmapFactory.decodeFile(BitmapFactory.java:460)
   at android.graphics.BitmapFactory.decodeFile(BitmapFactory.java:499)
   at cgeo.geocaching.StaticMapsProvider.decodeFile(StaticMapsProvider.java:330)
   at cgeo.geocaching.StaticMapsProvider.getPreviewMap(StaticMapsProvider.java:314)
   at cgeo.geocaching.CacheDetailActivity$8.call(CacheDetailActivity.java:1278)
   at cgeo.geocaching.CacheDetailActivity$8.call(CacheDetailActivity.java:1273)
   at rx.Observable$1.call(Observable.java:144)
   at rx.Observable$1.call(Observable.java:136)
   at rx.Observable$1.call(Observable.java:144)
   at rx.Observable$1.call(Observable.java:136)
   at rx.Observable.unsafeSubscribe(Observable.java:7495)
   at rx.internal.operators.OperatorSubscribeOn$1$1.call(OperatorSubscribeOn.java:62)
   at rx.schedulers.ExecutorScheduler$ExecutorAction.run(ExecutorScheduler.java:173)
   at rx.schedulers.ExecutorScheduler$ExecutorSchedulerWorker.run(ExecutorScheduler.java:99)
   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
   at java.lang.Thread.run(Thread.java:841)
```

**Comment by SammysHP** [comment] 2015-05-06 09:36
Out of memory caused by static maps. I think it's the combination of map in background and processing of static maps. IIRC we already have an issue for that combination (but that might be obsolete once we use the new version of Mapsforge).

**Comment by Lineflyer** [comment] 2015-05-06 11:20
Never occured to me with my S3 LTE. Strange.
@kirchwitz 
Are you using a Mapsforge offline map?

As a workaround please try to switch off all static maps options in c:geo Menu - Settings - Offline data.

**Comment by Lineflyer** [comment] 2015-05-06 11:20
Probably duplicate of #4868 then.

**Comment by kirchwitz** [comment] 2015-05-06 22:09
Had two more crashes today (6.5.2015), both start with "AMK4711A" in the description (for easier identification). One at around 20:50 (GMT+0200), the other at 21:50 (GMT+0200). Just in case you might want to check that it's still the some out of memory issue. Happened the same way as always, when touching on "More details" on the map to launch the geocache details page.

I'm using offline maps in mapsforge format from http://www.openandromaps.org/ as they have a better selection of details (what to have in the map and what to leave out) than the originals from mapsforge.org

The map I'm ususally working with is not a big one (not the whole country, ie, Germany) but only covers my state (Brandenburg). Just saying that because I'm confused about the fact that it might be an out of memory issue.

Will try the workaround and let you know if things get better.

**Comment by Lineflyer** [comment] 2015-05-07 12:17
Those crashes have the same stack trace.
I always used mapsforge offline maps and static maps in the same way on the same device and never had a problem.. That is strange.
We recently changed the static maps size and made it depending on the display dimensions...maybe something wents wrong here.

Out of memory in this case does not depend so much on the size of the map file. Basically the mapsforge implementation as such takes a lot of memory.. But we IMHO never had the fact that a mapsforge map + a simple static map image is enough to produce a OOM.

I will close #4868 and continue here.

**Comment by kirchwitz** [comment] 2015-05-14 01:44
After I disabled all static maps options (as recommended), c:geo seems to behave better (not a single crash during the last days). Never really used those maps anyway.

Unfortunately, today I had a c:geo crash. As there wasn't a crash for about a week now, I didn't really expect it and I'm not 100% sure if it happened exactly the same way as the crashes that this bug ticket is about. Either it was after touching a geocache icon on the map, or it was (like it happened to me in the past) after touching "More details". I'm really sorry, I can't remember exactly.

To be on the safe side, I sent a Crash Report (13.5.2015) and put the same unique identifier in the description as before (AMK4711A).

**Comment by rsudev** [comment] 2015-05-14 18:48
I am obviously to stupid for the play console. @Lineflyer can you find the mentioned crash report?

**Comment by Lineflyer** [comment] 2015-05-15 00:01
There is no search function. You should filter for device types Samsung S3 and then look at all commentd on all filtered crashes to find it. Sorry, no better way.
I am in Mainz and only on mobile

**Comment by Lineflyer** [comment] 2015-06-18 20:01
@kirchwitz 
If you are still able to kind of reproduce this issue, then please kindly test with 
http://download.cgeo.org/cgeo-RC.apk

It has some memory optimizations in it which has proven to run better on Samsung S3.
So reenable static maps and all function you might have had disabled and try again if you get crashes.

**Comment by Lineflyer** [comment] 2015-06-26 11:53
Closing due to lack of feedback.
I assume that this should be fixed as well as we had no more OOM reports for S3 on Google Play.

**Closed by Lineflyer** 2015-06-26 11:53 UTC
Labels: Bug, Field test

**Comment by kirchwitz** [comment] 2015-06-26 16:13
As I had opened this ticket, please allow me for some final words. I got so used to the workaround of not loading the maps that I finally preferred this setting. Saves time when storing caches, and I've never used the map anyway. It just looks nice but isn't of any real help while going geocaching.

I feel guilty that I don't need the fix any longer but as it was in fact a problem I hope that other users will benefit from the fix. Please accept a very big "Thank You!" for analysing the problem and finally fixing it. Thanks a lot!
