### ISSUE TITLE
Editing cache logs does not take care of existing favorite points

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#15748] opened 2024-05-28 12:53 UTC
### Describe your problem!

When editing existing found logs, where a favorite point was assigned, this fact is not reflected in the edit view.

Found by a user reported on support mail and reproducible for me.

### How to reproduce?

- Open a found cache which you awarded a favorite point
- Tap on your found log and select to edit your log

### Actual result after these steps?

The edit view does not contain the checkbox "Add to favorite" at all.
When sending the edited log the favorite point gets lost (meaning: No longer awarded to the cache)

### Expected result after these steps?

The checkbox "Add to favorites" should be shown in the edit view and reflect the current state of whether or not the user assigned a favorite point to this cache.
Changes to the checkbox state should be send with the edited log (keep, add or remove favorite point depending on previous state).

### Reproducible

Yes

### c:geo Version

2024.05.28-NB

### Additional Information

Ticket 340758

**Comment by eddiemuc** [comment] 2024-05-28 13:47
It is correct that log editing does not support favorite point editing currently. That's not a bug but would be a new feature.

It is not ok that assigned favorite points are lost. That part is a bug imho

**Comment by eddiemuc** [comment] 2024-06-23 16:13
Fixed with #15808

**Closed** 2024-06-29 10:31 UTC
Labels: Bug, Feature Request, Prio - Medium
