### ISSUE TITLE
Any destination wont take correct input

### ISSUE THREAD

**Issue by pennilane** [cgeo/cgeo#4739] opened 2015-03-15 18:02 UTC
Suddenly any destination does not take input coords when DONE pressed. This happens on my phone and tablet. Was OK last week. The coords input get changed when press done

**Comment by rsudev** [comment] 2015-03-15 18:36
Hi, thanks for the bug report. Currently I cannot reproduce this with the current master directly, so I would ask for:
* Information about your devices and the c:geo version (can be fetched easiest in c:geo - about - system page)
* a step-by-step description of what you do, what you see and what you expect instead.

**Comment by pennilane** [comment] 2015-03-15 21:12
So sorry my mistake. When writing down step by step Idealised I was inputting 63 seconds and the app correctly takes that as 1° 03secs. I hadn't spotted the error in my coord of a seconds value greater than 59.
Thanks for rapid response and a great app

**Comment by rsudev** [comment] 2015-03-15 21:31
Thanks for the feedback!
Closing.

**Closed by rsudev** 2015-03-15 21:31 UTC
Labels: Bug, Unverified
