### ISSUE TITLE
Download progress sometimes hangs for new oc caches

### ISSUE THREAD

**Issue by rsudev** [cgeo/cgeo#4054] opened 2014-07-09 17:16 UTC
Not sure if the behaviour is restricted to the exact scenario, but for me regularly the download progress doesn't go away when opening am oc cache I never visited before from a link in the notification mail.
The cache seems to be downloaded though, because if I cancel the progress and select the link again it is displayed immediately.

**Comment by Lineflyer** [comment] 2015-07-27 11:04
This is working flawless for me the last months.
Closing due to non-reproducibility.

**Closed by Lineflyer** 2015-07-27 11:04 UTC
Labels: Bug, OC
