### ISSUE TITLE
Do not show favorite count for caches that cannot receive favorite points

### ISSUE THREAD

**Issue by UniQP** [cgeo/cgeo#7595] opened 2019-05-04 07:48 UTC
Event caches cannot receive favorite points (at least on geocaching.com, not sure about opencaching) but we always show a line "Favorite 0×" in the cache details. It would be nice if we remove the line for such caches.

**Comment by okainov** [comment] 2019-05-06 19:32
How can we determine from the cache, can it receive fav points or not? Or we can just hide fav line all the time when it's zero...

**Comment by Lineflyer** [comment] 2019-05-06 20:07
Didnt we implement a feature already to remove the "Add to favorite" button for cache types, where it is not possible. The same mechanism can probably be reused to hide the fav information.

**Comment by jakedot** [comment] 2019-06-05 09:20
why is this labeled "Feature Request" - IMHO it is a bug?

**Comment by Lineflyer** [comment] 2019-06-05 12:10
Well, showing 0 favorites for those caches is not a bug as it is correct, therefore not a bug in the classical sense. I set both labels now :)

**Comment by emilvidmark** [comment] 2019-09-29 10:23
Hi, I'm new here on this repo and would like to take this as my first issue, how do I assign it?

**Comment by UniQP** [comment] 2019-09-29 10:29
> Hi, I'm new here on this repo and would like to take this as my first issue, how do I assign it?

@emilvidmark By dropping a note that you want to work on the issue. I assigned it to you.

**Comment by emilvidmark** [comment] 2019-09-29 10:36
> > Hi, I'm new here on this repo and would like to take this as my first issue, how do I assign it?
> 
> @emilvidmark By dropping a note that you want to work on the issue. I assigned it to you.

@UniQP Thank you!

**Comment by emilvidmark** [comment] 2019-09-29 11:55
Should a pull request be made to the release or master branch for this? Don't know if it counts as a new feature or not.

**Comment by Lineflyer** [comment] 2019-09-30 20:21
I would consider this a feature rather than a bug. Even more at the moment its more wise to work with ˋmasterˋ as ˋreleaseˋ is kind of a legacy branch at the moment due to the major changes going on on ˋmasterˋ.

So in short: Please towards ˋmasterˋ ;)

**Closed** 2019-10-11 16:21 UTC
Labels: Assigned-non-collab, Bug, Feature Request
