### ISSUE TITLE
[nightly]  OSM will not be displayed

### ISSUE THREAD

**Issue by geocachermgo** [cgeo/cgeo#9270] opened 2020-10-24 13:19 UTC
I'm afraid, this fix was possibly a little bit too quick: in latest nightly the OSM will not be displayed, until you select the map tile entry again. This happens when using "Live map" from main screen as well as "Show list on map".

Moreover zoom level and position are no longer the same between calls of "Live map", instead it seems to use max zoom and a strange position ...

Sorry for not being more precise, but currently I'm out in the woods ...

_Originally posted by @MagpieFourtyTwo in https://github.com/cgeo/cgeo/issues/9188#issuecomment-715911269_

**Comment by geocachermgo** [comment] 2020-10-24 13:21
I was about to report this too, but as a geocaching friend stated: Really hard is to get the STF.

**Comment by geocachermgo** [comment] 2020-10-24 13:36
I was about to report this too, but as a geocaching friend stated: Really hard is to get the STF.

**Comment by geocachermgo** [comment] 2020-10-24 13:46
Procedure to reproduce:
1 Chose offline map
2 Back to main page
3 Chose Live Map
Result: Blank screen instead of map:

![Screenshot_2020-10-24-15-42-31-930_cgeo geocaching](https://user-images.githubusercontent.com/43813636/97083362-b318ce80-160f-11eb-865c-c39edc5136c1.jpg)

**Comment by eddiemuc** [comment] 2020-10-24 14:43
There's also another change in this nightly related to map: adding map attribution. Can't tell now whether this is the cause of the problem. 
I tried to reproduce your problem on emulator without success. Do you have a log for analyzation?

**Comment by MagpieFourtyTwo** [comment] 2020-10-24 17:49
> There's also another change in this nightly related to map: adding map attribution. Can't tell now whether this is the cause of the problem.

Yep, remembered this one afterwards, too.
But what I don't get right now: why does it work when "Combined offline" is selected? Nevertheless, exactly this seems to vote for s/th related to the newly invented attribution ...

> I tried to reproduce your problem on emulator without success. Do you have a log for analyzation?

Sunday evening, earliest.

If you want to go on trying to reproduce: "Best" result (i. e. most probably failing) seems to be with lists, containing caches located on two different map tiles, with your position on one of these two, while "yours" is located on the active tile in map view (instead of "Combined offline").

**Comment by geocachermgo** [comment] 2020-10-24 19:58
Very reproducable for me, I created a logfile. Is there any non-public info in it? Otherwise I can send it to a developer (Eddie?) directly.

**Comment by eddiemuc** [comment] 2020-10-24 21:18
Got the log and have an idea. Hopefully I find the time tomorrow to dig into it. Right now I have to manage a sleepover...

**Comment by eddiemuc** [comment] 2020-10-25 09:32
The following is a modified extract from the logfile I got for this issue, it shows the exceptions which probably lead to the problem. There are lots and lots of these exceptions in the logfile:
(Note: the numbers in the exception message (-585.0 and -188.0) are calculated pixel sizes for display purposes. Those should never be negative - hence the exception.)

```
  8242  8242 W cgeo    : java.lang.IllegalArgumentException: invalid pixelY coordinate 704: -585.0
  8242  8242 W cgeo    : 	at org.mapsforge.core.util.MercatorProjection.pixelYToLatitude(MercatorProjection.java:409)
  8242  8242 W cgeo    : 	at org.mapsforge.core.util.MercatorProjection.fromPixels(MercatorProjection.java:91)
  8242  8242 W cgeo    : 	at cgeo.geocaching.maps.mapsforge.v6.MfMapView.getLatitudeSpan(MfMapView.java:51)
  8242  8242 W cgeo    : 	at cgeo.geocaching.maps.mapsforge.v6.MfMapView.getViewport(MfMapView.java:38)
  8242  8242 W cgeo    : 	at cgeo.geocaching.maps.mapsforge.v6.caches.CachesBundle.getViewport(CachesBundle.java:290)
  8242  8242 W cgeo    : 	at cgeo.geocaching.maps.mapsforge.v6.caches.AbstractCachesOverlay.getVisibleCacheGeocodes(AbstractCachesOverlay.java:66)
  8242  8242 W cgeo    : 	at cgeo.geocaching.maps.mapsforge.v6.caches.CachesBundle.getVisibleCacheGeocodes(CachesBundle.java:190)
  8242  8242 W cgeo    : 	at cgeo.geocaching.maps.mapsforge.v6.NewMap.onPrepareOptionsMenu(NewMap.java:345)
  8242  8242 W cgeo    : 	at android.app.Activity.onPreparePanel(Activity.java:4158)
  8242  8242 W cgeo    : 	at androidx.fragment.app.FragmentActivity.onPrepareOptionsPanel(FragmentActivity.java:502)
  8242  8242 W cgeo    : 	at androidx.fragment.app.FragmentActivity.onPreparePanel(FragmentActivity.java:488)
  8242  8242 W cgeo    : 	at androidx.appcompat.view.WindowCallbackWrapper.onPreparePanel(WindowCallbackWrapper.java:99)
  8242  8242 W cgeo    : 	at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.onPreparePanel(AppCompatDelegateImpl.java:3097)
  8242  8242 W cgeo    : 	at androidx.appcompat.app.AppCompatDelegateImpl.preparePanel(AppCompatDelegateImpl.java:1922)
  8242  8242 W cgeo    : 	at androidx.appcompat.app.AppCompatDelegateImpl.doInvalidatePanelMenu(AppCompatDelegateImpl.java:2176)
  8242  8242 W cgeo    : 	at androidx.appcompat.app.AppCompatDelegateImpl$2.run(AppCompatDelegateImpl.java:271)
  8242  8242 W cgeo    : 	at android.os.Handler.handleCallback(Handler.java:883)
  8242  8242 W cgeo    : 	at android.os.Handler.dispatchMessage(Handler.java:100)
  8242  8242 W cgeo    : 	at android.os.Looper.loop(Looper.java:224)
  8242  8242 W cgeo    : 	at android.app.ActivityThread.main(ActivityThread.java:7520)
  8242  8242 W cgeo    : 	at java.lang.reflect.Method.invoke(Native Method)
  8242  8242 W cgeo    : 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
  8242  8242 W cgeo    : 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
  8242  8242 W cgeo    : [main] Exception when calculating longitude span
  8242  8242 W cgeo    : java.lang.IllegalArgumentException: invalid pixelX coordinate 704: -188.0
  8242  8242 W cgeo    : 	at org.mapsforge.core.util.MercatorProjection.pixelXToLongitude(MercatorProjection.java:355)
  8242  8242 W cgeo    : 	at org.mapsforge.core.util.MercatorProjection.fromPixels(MercatorProjection.java:92)
  8242  8242 W cgeo    : 	at cgeo.geocaching.maps.mapsforge.v6.MfMapView.getLongitudeSpan(MfMapView.java:72)
  8242  8242 W cgeo    : 	at cgeo.geocaching.maps.mapsforge.v6.MfMapView.getViewport(MfMapView.java:38)
  8242  8242 W cgeo    : 	at cgeo.geocaching.maps.mapsforge.v6.caches.CachesBundle.getViewport(CachesBundle.java:290)
  8242  8242 W cgeo    : 	at cgeo.geocaching.maps.mapsforge.v6.caches.AbstractCachesOverlay.getVisibleCacheGeocodes(AbstractCachesOverlay.java:66)
  8242  8242 W cgeo    : 	at cgeo.geocaching.maps.mapsforge.v6.caches.CachesBundle.getVisibleCacheGeocodes(CachesBundle.java:190)
  8242  8242 W cgeo    : 	at cgeo.geocaching.maps.mapsforge.v6.NewMap.onPrepareOptionsMenu(NewMap.java:345)
  8242  8242 W cgeo    : 	at android.app.Activity.onPreparePanel(Activity.java:4158)
  8242  8242 W cgeo    : 	at androidx.fragment.app.FragmentActivity.onPrepareOptionsPanel(FragmentActivity.java:502)
  8242  8242 W cgeo    : 	at androidx.fragment.app.FragmentActivity.onPreparePanel(FragmentActivity.java:488)
  8242  8242 W cgeo    : 	at androidx.appcompat.view.WindowCallbackWrapper.onPreparePanel(WindowCallbackWrapper.java:99)
  8242  8242 W cgeo    : 	at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.onPreparePanel(AppCompatDelegateImpl.java:3097)
  8242  8242 W cgeo    : 	at androidx.appcompat.app.AppCompatDelegateImpl.preparePanel(AppCompatDelegateImpl.java:1922)
  8242  8242 W cgeo    : 	at androidx.appcompat.app.AppCompatDelegateImpl.doInvalidatePanelMenu(AppCompatDelegateImpl.java:2176)
  8242  8242 W cgeo    : 	at androidx.appcompat.app.AppCompatDelegateImpl$2.run(AppCompatDelegateImpl.java:271)
  8242  8242 W cgeo    : 	at android.os.Handler.handleCallback(Handler.java:883)
  8242  8242 W cgeo    : 	at android.os.Handler.dispatchMessage(Handler.java:100)
  8242  8242 W cgeo    : 	at android.os.Looper.loop(Looper.java:224)
  8242  8242 W cgeo    : 	at android.app.ActivityThread.main(ActivityThread.java:7520)
  8242  8242 W cgeo    : 	at java.lang.reflect.Method.invoke(Native Method)
  8242  8242 W cgeo    : 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
  8242  8242 W cgeo    : 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
```

Later in the log I find failing requests to gc.com with boxes where both corner coordinates are the same. E.g. like this one:
  
`  D cgeo    : [OkHttp] 400 [Bad Request] (222 ms) GET https://www.geocaching.com/api/proxy/web/search?box=0.0%2C0.0%2C0.0%2C0.0&take=500&asc=true&skip=0&sort=distance&origin=0.0%2C0.0&ho=1&hf=1&app=cgeo (http/1.1)`

I found these failing requests also with other, legimite coordinates (won't reveil them here), but always both corners are same coordinate

**Comment by eddiemuc** [comment] 2020-10-25 11:42
Ok, I am now able to reproduce the above exceptions with following conclusions:
* Although exceptions occur, my map is drawn. So I fear they are unrelated
* I don't get exactly how `MfMapView.getLatitudeSpan/getLongitudeSpan` is supposed to work. My feeling is that exceptions are thrown when map is "initializing" and called when certain values are still zero (esp zoom level and map center)
* I found a memory leak during the debug process which I will now try to fix. Can't tell though whether this is related to the problem.
* The new Android Studio or library setup or both are not working well on my machine. I constantly have to restart, clear caches and stuff. Can't really work straight currently.

**Comment by moving-bits** [comment] 2020-10-25 11:49
At least this error `java.lang.IllegalArgumentException: invalid pixelY coordinate 704: -585.0` happens since a long time already, but we haven't been able to track it down yet.

**Comment by moving-bits** [comment] 2020-10-25 11:50
But I'm receiving a new error now:
```
2020-10-25 12:49:23.389 13016-13862/cgeo.geocaching E/MapFile: null
    java.nio.channels.ClosedChannelException
        at sun.nio.ch.FileChannelImpl.ensureOpen(FileChannelImpl.java:133)
        at sun.nio.ch.FileChannelImpl.position(FileChannelImpl.java:321)
        at org.mapsforge.map.reader.IndexCache.getIndexEntry(IndexCache.java:95)
        at org.mapsforge.map.reader.MapFile.processBlocks(MapFile.java:553)
        at org.mapsforge.map.reader.MapFile.readMapData(MapFile.java:928)
        at org.mapsforge.map.reader.MapFile.readMapData(MapFile.java:889)
        at org.mapsforge.map.layer.renderer.DatabaseRenderer.executeJob(DatabaseRenderer.java:94)
        at org.mapsforge.map.layer.renderer.MapWorkerPool$MapWorker.run(MapWorkerPool.java:149)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
```

Maybe you close the mapfile after retrieving the attribution, and mapsforge expects it to be still open?

**Comment by eddiemuc** [comment] 2020-10-25 13:18
> But I'm receiving a new error now:
> 
> ```
> 2020-10-25 12:49:23.389 13016-13862/cgeo.geocaching E/MapFile: null
>     java.nio.channels.ClosedChannelException
>         at sun.nio.ch.FileChannelImpl.ensureOpen(FileChannelImpl.java:133)
>         at sun.nio.ch.FileChannelImpl.position(FileChannelImpl.java:321)
>         at org.mapsforge.map.reader.IndexCache.getIndexEntry(IndexCache.java:95)
>         at org.mapsforge.map.reader.MapFile.processBlocks(MapFile.java:553)
>         at org.mapsforge.map.reader.MapFile.readMapData(MapFile.java:928)
>         at org.mapsforge.map.reader.MapFile.readMapData(MapFile.java:889)
>         at org.mapsforge.map.layer.renderer.DatabaseRenderer.executeJob(DatabaseRenderer.java:94)
>         at org.mapsforge.map.layer.renderer.MapWorkerPool$MapWorker.run(MapWorkerPool.java:149)
>         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
>         at java.lang.Thread.run(Thread.java:919)
> ```
> 
> Maybe you close the mapfile after retrieving the attribution, and mapsforge expects it to be still open?

Hm not that I am aware of, but this is worth to check. As a matter of fact, maybe I **should**  close created MapFiles so not to leak any resources...
Do you get that exception when you open files in single-file-mode, in combined-mode or in both cases? And does it lead (in your case) to the problems described by @MagpieFourtyTwo and @geocachermgo ?

**Comment by moving-bits** [comment] 2020-10-25 13:26
> Do you get that exception when you open files in single-file-mode, in combined-mode or in both cases? And does it lead (in your case) to the problems described by @MagpieFourtyTwo and @geocachermgo ?

I only get this error with single maps, not in combined mode, and only on opening a map a second/third/etc. time (first opening of live map does work).
When this error occurs (which seems to be very reliable) the map itself is not shown, only the attribution, so it looks like the problem described in this issue.

**Comment by eddiemuc** [comment] 2020-10-25 13:48
> > Do you get that exception when you open files in single-file-mode, in combined-mode or in both cases? And does it lead (in your case) to the problems described by @MagpieFourtyTwo and @geocachermgo ?
> 
> I only get this error with single maps, not in combined mode, and only on opening a map a second/third/etc. time (first opening of live map does work).
> When this error occurs (which seems to be very reliable) the map itself is not shown, only the attribution, so it looks like the problem described in this issue.

OK, I guess I know the problem then. Thanks for the help, I will issue a PR.

**Comment by eddiemuc** [comment] 2020-10-25 16:47
> At least this error `java.lang.IllegalArgumentException: invalid pixelY coordinate 704: -585.0` happens since a long time already, but we haven't been able to track it down yet.

I debugged into this. My impression is that there is a longer "Initialization phase" of the map view where the "zoom level" is still set to 0. This would mean that one tile fills the whole view, which is not the case, and thus wrong values arecalculated. 
Later in initilaization zoom level is set to something meaningful (e.g. 16), then the calculation works.

**Comment by eddiemuc** [comment] 2020-10-26 17:07
Added PR #9286 to fix the `java.lang.IllegalArgumentException: invalid pixelY coordinate 704: -585.0` type of error

**Comment by MagpieFourtyTwo** [comment] 2020-10-26 23:58
Seems as if the original issue is fixed with 2020.10.27-NB-dfe6fb8 - so it was really the attribution ... strange.

Anyway - there are still two to three regressions: 
1. Map loading is way slower than ... a few days ago ;) 
  e. g.: with ``Show as list`` it takes up to 5 secs until the map is loaded completely (even with just BaWü tile selected),
  which used to happen during a wink of the eye before
2. Between subsequent calls of ``Live Map`` or single cache map, the zoom is always reset to min(last zoom; 100 m)
3. and sometimes the map center seems to be changed between calls ... but this one is not deterministic

**Comment by eddiemuc** [comment] 2020-10-27 06:18
@MagpieFourtyTwo question to 1):
is the map loading slower than before only when you select a single map file or also when you use "combined map"?

**Comment by geocachermgo** [comment] 2020-10-27 06:43
I can confirm 2) and 3). If I change between portait and landscape the redrawn takes about 1s. I think it was faster with the last one. I cannot confirm 5s.

**Comment by Lineflyer** [comment] 2020-10-27 07:14
I can also configm 2) and 3). Not sure about the drawing speed though.

> Anyway - there are still two to three regressions:

I will open new issues for those and feel free to do alike in future.
This will help us keep track of those regressions better than discussing "offtopic" in the original issue.

**Closed by Lineflyer** 2020-10-27 07:14 UTC
