### ISSUE TITLE
[Discussion] Send position to server

### ISSUE THREAD

**Issue by geocachermgo** [cgeo/cgeo#9624] opened 2020-12-29 18:03 UTC
I would like to have the possibilty to send my position to a server, were it can be read by somebody else. At first I thought that this is not something that a caching tool needs to provide.
But maybe, it is.
For me, half of the feature would be suffient: The app needs to call periodically or by user request a freely selectable web-adress (e.g. mgo.com) with the waypoint as GET parameter
http://cgeo.org/position_record?lat=52.345&lon=8.123&ele=79&t=1609261940 
(BTW: very nice 404 poem!)
The storage at my server and display I could handle by myself. (Typically its already stored in the logfile).

During the discussion I realized that allttrails has a feature named lifeline which I manually emulated several times (called my wife, said: I'm going to GCxyz, if I do not call again within 3 h, please send rescue to N50.123 E9.876)
German description: https://support.alltrails.com/hc/de/articles/360019246351-Was-ist-Lifeline-
I think the half-feature would be very simple to realize but would have a very small number of users.
The full feature would be a bigger step, since it would require to additionally provide a server, authorization, DSGVO clearance, ...
So what do you think?

**Comment by SammysHP** [comment] 2020-12-29 18:25
IMHO this is nothing that should be integrated into a geocaching app. In the beginning of c:geo there was such a feature and it was a step in the right direction when we removed it.

And yes, the legal thing would make it very complicated.

**Comment by Lineflyer** [comment] 2020-12-29 18:47
Duplicate of #2226 (which also contains some links to history)

**Closed by Lineflyer** 2020-12-29 18:47 UTC
Labels: Feature Request, Unverified

**Comment by geocachermgo** [comment] 2020-12-29 20:44
Is there a decription available what go4cache did?

**Comment by Lineflyer** [comment] 2020-12-29 21:13
Not that I am aware of.
AFAIR it was just enabled as service in c:geo and from then on send your own position to a central server while the live map of c:geo is used. On the other hand it retrieved position info from server for other users and presented them as color dot on your live map. It also had a web frontend, which was basically a map with positions of cachers, who opted-in.
Its long ago, so I am no longer sure, whether it also provided the other users name/alias or just the dot (=some geocacher with c:geo is there).

I personally still like the idea of such feature (as kind of a community thing) but it would nowadays need a dedicated plugin for sure, and not sure what legal issues might appear.

Anyway lets continue in #2226

**Comment by Lineflyer** [comment] 2020-12-29 21:39
Addon:
According to the ols manual on http://appmanualreader.sourceforge.net/manuals/cgeo/cgeo-help-en.html

it published your anonymous position and the cache you are heading to.

**Comment by geocachermgo** [comment] 2020-12-30 06:54
Thanks, that helped.
So it was (analogous to twitter or hypothetically foursquare) a half-feature within c:geo just supporting this external service and #2226 is about rebuilding this service.
Shall I copy this discussion into #2226 or is it ok to request the reader to jump, and just continue there?

**Comment by moving-bits** [comment] 2020-12-30 10:17
> Shall I copy this discussion into #2226 or is it ok to request the reader to jump, and just continue there?

As this issue (#9624) is already linked to #2226 it's ok to just continue the discussion over there, IMHO.
Or you can add a single item explicitly stating that issue #9624 contains additional info. No need to copy all items.
