### ISSUE TITLE
OC14726 not showing description

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#11455] opened 2021-08-10 21:59 UTC
### Describe your problem!

A certain OC cache is not showing any description text in c:geo.
On the website the cache description is visible.

### How to reproduce?

- Be authenticated to OC.de
- Open OC14726
- Swipe to description tab

### Actual result after these steps?

Empty description

### Expected result after these steps?

Description shown

### Reproducible

Yes

### c:geo Version

2021.08.08-RC

### Additional Information

Did not check any deeper, whether this is an existing problem, a OKAPI problem or a beta regression

**Comment by murggel** [comment] 2021-08-11 16:58
I have same problem with OC109A7

**Comment by moving-bits** [comment] 2021-08-11 17:42
This seems to be triggered by a method checking if text from "short description" is contained at the beginning of the regular description field, and disabling the description field in that case. (See `CacheDetailActivity.potentiallyHideShortDescription()`)

The code for this is pretty old, but the error seems to be triggered by a change from 2016, when the separate "short description" field was merged into the regular description field, and thus the code above not disabling the "short description" but the whole description :-(

But this seems to be a real edge case, since nobody seems to have stumbled upon this in more than five years...

I propose to remove the check whether "short description" is contained in the beginning of the regular description.

**Comment by moving-bits** [comment] 2021-08-11 18:09
In our current release (2021.07.15) the short_description is shown before description, so for some reason the check seem to have failed in that release, but does work now (although at a quick glance I didn't find any code changes triggering this). With removing that check, short_description will always be shown (if non-empty), so it would be the same behavior as in current release, at least visually.

Checked against OC109A7, cannot download OC24726 ("Download der Cache-Details fehlgeschlagen")

**Comment by murggel** [comment] 2021-08-11 19:12
Probably the website for that cache changed?

**Comment by murggel** [comment] 2021-08-11 20:18
Ah ok, the field is the one in the activity not in the html. My mistake 😂

**Comment by bekuno** [comment] 2021-08-12 08:19
> Checked against OC109A7, cannot download OC24726 ("Download der Cache-Details fehlgeschlagen")

It is OC14726 - see the issue description.
There is the same behavior with release 2021.07.15.

**Comment by Lineflyer** [comment] 2021-08-19 08:38
Seamingly same error for:

https://opencaching.pl/viewcache.php?cacheid=84764

OP9EQG

**Comment by Lineflyer** [comment] 2021-08-19 20:55
Another one OC1408C

I wonder if there was a change on the API or its really caused by us.

**Comment by bekuno** [comment] 2021-08-19 21:07
> I wonder if there was a change on the API or its really caused by us.

The problem is as described in https://github.com/cgeo/cgeo/issues/11455#issuecomment-897040437 - we have an old bug in c:geo, which was (re)activated by same code changes in our current release.

**Comment by bekuno** [comment] 2021-08-19 21:12
And as seen in #11486 it is relevant for all connectors which use short and long description.

**Comment by Lineflyer** [comment] 2021-08-19 21:18
I had the time to bisect this issue.
Due to problems with my Android Studio I am not 100% sure its done well, but according to bisecting the causing commit is:


5752706861127595953914a8aec55c5725c61547 is the first bad commit
commit 5752706861127595953914a8aec55c5725c61547
Author: moving-bits <github@moving-bits.net>
Date:   Sat Jun 26 15:35:48 2021 +0200

    enlarge cache size for TabbedViewPagerActivity (#11012)

 main/src/cgeo/geocaching/activity/TabbedViewPagerActivity.java | 1 +
 1 file changed, 1 insertion(+)

**Comment by Lineflyer** [comment] 2021-08-19 21:18
I will try to bisect the GC case as well

**Comment by Lineflyer** [comment] 2021-08-19 21:21
Reading the comments of @bekuno my bisecting looks strange as causing commit....mmh.

**Comment by bekuno** [comment] 2021-08-19 21:47
I suggest to push PR #11463 to release and fix or remove the activity.potentiallyHideShortDescription() code later as proposed in Issue #11464.

**Closed** 2021-08-22 20:55 UTC
Labels: Bug, Connector OC, Google Play or Beta feedback
