### ISSUE TITLE
Title of GC9EE5D (containing an ampersand) not parsed correctly

### ISSUE THREAD

**Issue by MichelTenVoorde** [cgeo/cgeo#11566] opened 2021-08-28 09:27 UTC
### Describe your problem!

The title of GC9EE5D is not parsed correctly, probably because it contains an ampersand.
![GC9EE5D](https://user-images.githubusercontent.com/1790720/131213162-6836dfc9-d003-4f07-80f5-3278e0240b31.png)

Title should be _Lomp & Onbenullig_

### How to reproduce?

Load GC9EE5D either directly from the Search screen or by looking it up on the Map.

### Reproducible

Yes

### c:geo Version

2021.08.15

### System information

```text
## System information

c:geo version: 2021.08.15

Device:
-------
- Device type: IN2023 (OnePlus8Pro_EEA, OnePlus)
- Available processors: 8
- Android version: 11
- Android build: IN2023_15_210602
- Screen resolution: 1440x2851px (411x809dp)
- Sailfish OS detected: false
- Google Play services: disabled - 21.26.21 (150400-387928701)
- HW acceleration: enabled (default state)

Sensor and location:
-------
- Low power mode: inactive
- Compass capabilities: yes
- Rotation vector sensor: present
- Orientation sensor: present
- Magnetometer & Accelerometer sensor: present
- Direction sensor used: rotation vector

Program settings:
-------
- Settings: v8, Count:159
- Set language: en_NL (system default)
- System date format: dd/MM/y
- Time zone: GMT+02:00
- Debug mode active: no
- Last backup: never
- Routing mode: Straight
- Live map mode: true
- OSM multi-threading: true / threads: 4
- Map: Combined (Offline)
  - Id: cgeo.geocaching.maps.mapsforge.MapsforgeMapProvider$OfflineMultiMapSource
  - Atts: belgium.map: / Map data (c) OpenStreetMap contributors /  / croatia.map: / Map data (c) OpenStreetMap contributors /  / finland.map: / Map data (c) OpenStreetMap contributors /  / hungary.map: / Map data (c) OpenStreetMap contributors /  / luxembourg.map: / Map data (c) OpenStreetMap contributors /  / netherlands.map: / Map data (c) OpenStreetMap contributors /  / nordrhein-westfalen.map: / Map data (c) OpenStreetMap contributors /  / slovakia.map: / Map data (c) OpenStreetMap contributors /  / slovenia.map: / Map data (c) OpenStreetMap contributors /  / sweden.map: / Map data (c) OpenStreetMap contributors
  - Theme: none

Filters:
-------
- Hide waypoints: -
- LIVE: None ([:inconclusive=false:advanced=true])
- OFFLINE: None ([:inconclusive=false:advanced=false])

Services:
-------
- Geocaching sites enabled:
   geocaching.com: Logged in (Login OK) / PREMIUM
   Geocaching.com Adventure Lab
- Geocaching.com date format: dd/MMM/yyyy
- Routing: external / BRouter installed: true
- Installed c:geo plugins:  none

Permissions & paths:
-------
- Fine location permission: granted
- Write external storage permission: granted
- System internal c:geo dir: /data/user/0/cgeo.geocaching (123,4 GB free) v2 internal isDir(9 entries)
- Legacy User storage c:geo dir: /data/user/0/cgeo.geocaching (123,4 GB free) v2 internal isDir(9 entries)
- Geocache data: /storage/emulated/0/Android/data/cgeo.geocaching/files/GeocacheData (123,4 GB free) v2 external non-removable isDir(65 entries)
- Internal theme sync (is turned off): /data/user/0/cgeo.geocaching/MapThemeData (123,4 GB free) v2 internal isDir(0 entries)
- Public Folders: #11
  - BASE: /cgeo (User-Defined)[/cgeo[DOCUMENT#0:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo, Av:true, files:>=24, dirs:>=27, totalFileSize:>=6,3 MB, free space: 123,4 GB, files on device: 13045757)
  - OFFLINE_MAPS: /Maps (User-Defined)[/Maps[DOCUMENT#0:p-content://com.android.externalstorage.documents/tree/primary%3AMaps::]] (Uri: content://com.android.externalstorage.documents/tree/primary%3AMaps/document/primary%3AMaps, Av:true, files:19, dirs:1, totalFileSize:3,2 GB, free space: 123,4 GB, files on device: 13045757)
  - OFFLINE_MAP_THEMES: /Maps/_themes (Default)[/Maps/_themes[PERSISTABLE_FOLDER(OFFLINE_MAPS)#1:p-content://com.android.externalstorage.documents/tree/primary%3AMaps::/_themes]] (Uri: content://com.android.externalstorage.documents/tree/primary%3AMaps/document/primary%3AMaps%2F_themes, Av:true, files:0, dirs:0, totalFileSize:0 B, free space: 123,4 GB, files on device: 13045757)
  - LOGFILES: /cgeo/logfiles (Default)[/cgeo/logfiles[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/logfiles]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Flogfiles, Av:true, files:0, dirs:0, totalFileSize:0 B, free space: 123,4 GB, files on device: 13045757)
  - GPX: /cgeo/gpx (Default)[/cgeo/gpx[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/gpx]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Fgpx, Av:true, files:24, dirs:0, totalFileSize:6,3 MB, free space: 123,4 GB, files on device: 13045757)
  - BACKUP: /cgeo/backup (Default)[/cgeo/backup[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/backup]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Fbackup, Av:true, files:0, dirs:0, totalFileSize:0 B, free space: 123,4 GB, files on device: 13045757)
  - FIELD_NOTES: /cgeo/field-notes (Default)[/cgeo/field-notes[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/field-notes]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Ffield-notes, Av:true, files:0, dirs:0, totalFileSize:0 B, free space: 123,4 GB, files on device: 13045757)
  - SPOILER_IMAGES: /cgeo/GeocachePhotos (Default)[/cgeo/GeocachePhotos[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/GeocachePhotos]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2FGeocachePhotos, Av:true, files:>=0, dirs:>=25, totalFileSize:>=0 B, free space: 123,4 GB, files on device: 13045757)
  - ROUTING_BASE: /cgeo/routing (Default)[/cgeo/routing[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/routing]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Frouting, Av:true, files:7, dirs:1, totalFileSize:81,2 KB, free space: 123,4 GB, files on device: 13045757)
  - ROUTING_TILES: /cgeo/routing/segments4 (Default)[/cgeo/routing/segments4[PERSISTABLE_FOLDER(ROUTING_BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/routing/segments4]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Frouting%2Fsegments4, Av:true, files:0, dirs:0, totalFileSize:0 B, free space: 123,4 GB, files on device: 13045757)
  - TEST_FOLDER: [Legacy]/data/user/0/cgeo.geocaching/files/unittest (Default)[/data/user/0/cgeo.geocaching/files/unittest[FILE#1:p-file:///data/user/0/cgeo.geocaching/files::/unittest]] (Uri: file:///data/user/0/cgeo.geocaching/files/unittest, Av:true, files:0, dirs:0, totalFileSize:0 B, free space: 123,4 GB, files on device: -1)
- Map render theme path: 
- PersistedDocumentUris: #1
- TRACK: null
- Persisted Uri Permissions: #2
  - content://com.android.externalstorage.documents/tree/primary%3AMaps (21 Mar, 08:25):RW
  - content://com.android.externalstorage.documents/tree/primary%3Acgeo (21 Mar, 08:25):RW
- Database: /data/user/0/cgeo.geocaching/databases/data (v96, Size:2,7 MB) on system internal storage
```

**Comment by Lineflyer** [comment] 2021-08-28 09:33
Seems a duplicate of #11557 but not connected to the special char in the title.

**Comment by fm-sys** [comment] 2021-08-28 09:33
There was a website change last evening, see #11557. We already have a fix for it, but it is not yet released...

**Comment by fm-sys** [comment] 2021-08-28 09:39
Let's close as duplicate. I've pinned the other issue, so that users can easily it until we have a new release out...

![grafik](https://user-images.githubusercontent.com/64581222/131213592-eec4608e-8639-4b89-a969-8d13efca2fdb.png)

**Closed by fm-sys** 2021-08-28 09:39 UTC
Labels: Bug, Unverified

**Comment by MichelTenVoorde** [comment] 2021-08-28 10:05
Thanks guys.
