### ISSUE TITLE
Mark waypoint on map

### ISSUE THREAD

**Issue by toonburner** [cgeo/cgeo#5375] opened 2016-01-12 12:52 UTC
Feature request:somewhere on the map and mark it as a waypoint, for parking or marking the trailhead for example, as not all caches have these extra waypoints.

**Comment by Lineflyer** [comment] 2016-01-12 21:26
Can you provide more details?
Actually you can create your own waypoints for all saved caches.

**Comment by rsudev** [comment] 2016-01-12 21:56
This is a feature I have on my radar for quite a long time already, but wanted to realize on the new map: Create a waypoint by (long-)tapping interactively on the map, instead of entering coordinates.
This might require in the end even the possibility to move the wp by dragging it to the precise target location.
The first part shouldn't be too hard on my experimental implementation, for the second I currently have no idea how such a thing could be implemented.

**Comment by toonburner** [comment] 2016-01-12 22:48
Yes, you can create way points but not directly on the map. The way cgeo
handles way points at the moment is you manually add the co-ordinates .
What if you dont know them? What if you see somewhere to park on the map?
Ideally you should be able to long press on that point on tbe map to add a
waypoint.

**Comment by Lineflyer** [comment] 2016-01-13 09:20
Linked to #1141 and duplicate of #3693.

**Closed by Lineflyer** 2016-01-13 09:20 UTC
