### ISSUE TITLE
Offline found count

### ISSUE THREAD

**Issue by rsudev** [cgeo/cgeo#987] opened 2012-01-14 16:30 UTC
Suggestion from the german geoclub forum:
For offline logging it would be nice to have a found count as well. So I suggest to introduce a new variable [OFFLINENUM] that relies on some start value that you manually set in the settings and is automatically inceased with every log. It lays the responsibility o n the user that it is correctly set, but allows for convinient offline caching and logging.

**Comment by TofLaBeuze** [comment] 2016-04-18 09:47
Hi c:geo team,
up for this feature request that would be nice : do offline logging with the correct find numbers (by incrementing the last online number).

**Comment by Jorgixhallo** [comment] 2017-03-15 01:11
This feedback has been "buried" here for a long time... I face the same problem and I might have a suggestion (at least partial)...
1: When reopening the log in order to send it, the [NUMBER] gets updated if the user is online.
2: Hide the number (or even the other metadata) and update it only when sending. This could be done in the background and user wouldn't be able to perceive that the "same number" is there while offline.

**Comment by Technical-13** [comment] 2017-12-11 14:29
This is a five year old feature request?  Is it just a lack of coders keeping this from happening or is there a technical limitation making it more difficult to complete?

**Comment by Lineflyer** [comment] 2017-12-11 18:07
Well, technically it is not so easy to keep track of offline numbering but feasible. So it is more lack of interested coders (with time to find a good process for it).

**Comment by SammysHP** [comment] 2017-12-12 05:42
Actually it's not that easy. There are a lot of possibilities how something unexpected can happen.

**Comment by lippih** [comment] 2018-11-15 13:33
Cachebox has a good solution for this feature: There is a field (variable) that you can update online automatically by clicking it, or you can enter your number manually. This number is used for the founds. If you log a found, this number will increase for +1. If you delet a log it decreases for -1. It's very simple but very useful for offline loggers!  Perhaps Cgeo can insert a feature like this?

**Comment by Lukasdoe** [comment] 2019-08-15 20:56
So you say, that probably a new counter should be added to the c:geo startscreen? Is this really mandatory, because I don't really see how it would solve the problems that someone could encounter with offline caching, other than having a visual confirmation whether something has happened. Probably it's better adding such a counter in the "Log Visit" screen.

**Comment by itsbrody** [comment] 2019-12-21 21:49
Coming from GDAK (the app pendant of GSAK), which had a similar feature as described by @lippih  I'd second this, too. Sorrily I'm not a developer, but I'd intensivly test it, when existing.

Regards providing an additional counter for offline logging - I don't see the need - but if this is the cgeo solution, I would suggest the following:
- this counter is editable (part of "Logging" settings; "Log Visit" screen could also be an option)
- on going online, this counter is checked against the online number; if different it's mentioned and update is offered, but not automatically done.
- the offline function itself is best described two comments above.

**Comment by fm-sys** [comment] 2020-06-06 11:51
> do offline logging with the correct find numbers (by incrementing the last online number).

I think, that whould be the best way to implement. Take the last online find number and add up all offline logs whith type "found"

**Comment by fm-sys** [comment] 2020-07-08 20:19
I would like to contribute the code for such a feature, but I have two questions:

- Where could I cache the online found number, so it is stored even if c:geo is closed?
- And where are the signature variables defined? (in which file(s) )

**Comment by moving-bits** [comment] 2020-07-08 21:18
You have two choices for storing the current value: shared preferences and database. Both have different pros and cons:

Shared preferences is easier to start with, but the info relates to the caches and logs state, which is saved in the database, so it probably would be better to store that value in the database.

Shared preference handling:
- define a new preference key in `res/values/preference_keys.xml`
- define getter/setter in `settings/Settings.java`

Database handling:
- would need a new database table - creating a new table for just one value seems a bit like waste, so maybe a generalized `extension` table would help here (having a generalized data structure which would allow saving more of such individual single-use values later)
- database handling is done in `storage/DataStore.java`, see methods for extending the DB, creating the DB, getter and setter routines

**Comment by itsbrody** [comment] 2020-07-09 11:34
> creating a new table for just one value seems
Isn't it a value per login, not only one value
>generalized extension table
could be filled with key/value pairs - comments?

**Comment by moving-bits** [comment] 2020-07-10 18:14
I'm in need for an extension table for another issue as well, a bit more elaborated than just key/value pairs. Will try to add it over the weekend and report back here.

**Comment by fm-sys** [comment] 2020-08-05 09:40
One last question: is there a function for getting the conector (or the cache object) from geocode?

**Comment by moving-bits** [comment] 2020-08-05 17:50
> One last question: is there a function for getting the conector (or the cache object) from geocode?

Look for the `canHandle()` method each connector supports.

(For trackables we even have a `getTrackableConnector()` method, but there does not seem to be an equivalent for cache connectors.)

**Comment by fm-sys** [comment] 2020-08-05 18:10
Just read somewhere, that `ConnectorFactory.getConnector()` maby works... I will try it.

**Comment by Lineflyer** [comment] 2020-08-05 20:59
I only recently found time to look through comments and ongoing PR-developments.
I do see, that @fm-sys PR is titled "Introcude [OFFLINESUM]". That reads like you want to introduce a new signature variable for offline counting finds.

@fm-sys 
Maybe you can briefly draft here the implementation you are currently developing.
I would like to avoid, that you have more work if once it gets merged the testers do think it is not suitable for its purpose.

What came to my mind when reading "[OFFLINENUM]" is, that I usually use [NUMBER] in my signature. I personally have the usecase, that I sometimes log a cache directly (e.g a unspectacular find of a traditional cache) and sometimes only quickly store an offline log. How is the implementation supposed o work in such a case?

**Comment by fm-sys** [comment] 2020-08-05 22:04
When using the [NUMBER] Template there are tow main problems:
- Will not work if there is no Internet connection
- If you do not want to send log entries directly but would like to finish writing them (eg. at home) all next caches get the same (wrong) number

With the OFFLINENUM you can log caches alternately online and offline and the counter will always increase by 1 with every new cache (when logtype is FOUND_IT). And it totally works without internet connection... Also each geocaching service is handled separately. That means that an offline log only increases the counter, if it originates to the connector form the cache that your logging.

I think that should suffice as a brief description... If there are any further questions please ask

**Comment by Lineflyer** [comment] 2020-08-05 22:32
Thanks @fm-sys for your explanation. Sounds reasonable, some questions though:
- Why not change the working mode of [NUMBER] instead of introducing a new variable for the signature. As you describe the working mode, [OFFLINENUM] would work same as [NUMBER] in case of online logging. So we could replace the working mode of [NUMBER] by the desired working mode of [OFFLINENUM], or not?
- Please keep in mind, that besides FOUND_IT you also need to handle WEBCAM_PHOTO_TAKEN and ATTENDED for counting +1.

**Comment by fm-sys** [comment] 2020-08-05 23:06
> Why not change the working mode of [NUMBER] instead of introducing a new variable for the signature.

With my implementation it theoretical could be that the foundnumber is not up to date when you are offline and you had done a log from an other device. Also the number could be higher than the online count on the website. So when you have old offline logs that you don't submit the number in your signature will be higher than displayed left from your log (geocaching.com).

But when you say it's OK anyway I will instead change the working mode of [NUMBER]

**Comment by Lineflyer** [comment] 2020-08-06 21:26
Can you describe the principal you are planning to "sync" with the online find count (like it is currently done for |NUMBER])?

Lets try to use example scenarios for better understading:

1. I am online and logged in, for ease of use I use the "quick offline log" function to log a trail of traditional caches offline to submit the logs later on when I have time to add more text. Today I get all offline logs with the same find count.

2. Find count from website is up to date, then I move abroad and deactivate online connection. I perform several offline logs in c:geo and export them as field note. I transfer the field note to my PC and log them online. Next day I go caching again without data connection. So I would need to update the base find count from which to count from.

**Comment by fm-sys** [comment] 2020-08-06 21:47
### scenario 1
Every cache will get the correct find number (increasing by every log), because the offline logs will also be counted and added to the online number.

### scenario 2
The base find count will gets updated every time you visit the Main Screen and have an internet connection.
Also I would like to implement (not jet done) that the counter gets also updated after submitting a log. So the base count gets updated automatically if you have an internet connection.

Also when using the variable it tries to reload the online counter. So it should be quite safe that the counter gets updated correctly

**Comment by Lineflyer** [comment] 2020-08-06 21:54
Thanks!

So this would mean the offline count planned does deliver what users expect from [NUMBER]. So I guess optimizing this variable instead of introducing a new one is the way to go with the target to best possibly try to catch up offline counting and sync again to online count whenever possible.

Another reason for using the same variable for the signature is, that most user will maybe not plan explicitly for offline logging and change their signature (which is IMHO the most used option for these variables) before going for offline caching.

So everything seems to be in favor for reusing [NUMBER] or is there any expected regression?

**Comment by fm-sys** [comment] 2020-08-06 21:59
> or is there any expected regression?

Not that I know... ;-)

**Closed** 2020-08-07 16:05 UTC
Labels: Assigned-non-collab, Feature Request, Hacktoberfest, Prio - Medium

**Comment by Lomanic** [comment] 2020-08-17 18:29
Will it be released soon? This is the most useful functionality in months, I've been needing this from when I started using cgeo years ago. Maybe I will switch to nightlies just for this.

**Comment by fm-sys** [comment] 2020-08-17 18:54
> 
> 
> Will it be released soon? This is the most useful functionality in months, I've been needing this from when I started using cgeo years ago. Maybe I will switch to nightlies just for this.

I also switched to nightlies just for having this feature ;-) 
But actually that's only half of the truth: I have learned java and got into android programming just because I needed this feature so much... xD

**Comment by moving-bits** [comment] 2020-08-17 18:59
> I also switched to nightlies just for having this feature ;-)
> But actually that's only half of the truth: I have learned java and got into android programming just because I needed this feature so much... xD

That's why we skip some features for a long time to attract programmers (and testers) to join the team :-) (just kidding!) 
But we are a pretty small team, doing all work on c:geo in our spare time, so every contribution is very welcomed!

**Comment by Lomanic** [comment] 2020-08-17 21:25
I know, and I totally understand the struggle of working on a popular open source project on your free time (I'm always impressed by the amount of work you all pour into this) as I experience the same thing on the one I help maintaining. 

I would like to help some day. I think I won't be able to any time soon unfortunately.

I'm already on the beta program, will probably switch to nightlies.

**Comment by Lineflyer** [comment] 2020-08-17 21:46
> I'm already on the beta program, will probably switch to nightlies.

Very welcome to do so and please report any problems you find. This is a very helpful support for our developers.
