### ISSUE TITLE
ANR on first startup and when opening About c:geo

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#9997] opened 2021-02-10 12:41 UTC
I have a user on support mail, who is using our nightly builds and now has the following problem:
- After installing a new nightly build the app runs into ANR on first startup.
- On consecutive startups its working normal, besides the fact, that trying to enter "About c:geo" is still not possible (ANR)
- The users waited up to 2 minutes, but only a black screen remains until the ANR message pops up from system
- The problem starting with nightly build from or around January, 30th and is present since then after each nightly upgrade

To me it looks like a problem of the about activity as this is also potentially opened to show the change log after installation. I can however not reproduce it.

The logfile shows nothing related, but some messages like
```
01-30 21:22:02.181 30271 30271 I Choreographer: Skipped 72 frames!  The application may be doing too much work on its main thread.
```

@moving-bits 
Could it be related to the viewbinding changes in the about activity (from end of January) or the style changes in that activity some days earlier?

**Comment by Lineflyer** [comment] 2021-02-10 14:32
User device:
Samsung S8, Android 9.0

**Comment by moving-bits** [comment] 2021-02-10 21:14
Hm, have not been able to reproduce this in the emulator yet (and don't have a physical Samsung device running on Android 9 available.)

> @moving-bits
> Could it be related to the viewbinding changes in the about activity (from end of January) or the style changes in that activity some days earlier?

Not sure, but even after rechecking the changes regarding viewbindings in about pages still seem pretty basic and are taken 1:1 from the example page in the docs. Strange.

**Comment by moving-bits** [comment] 2021-03-23 20:24
Could this be related to our recent "loop of death" issue? @eddiemuc?

**Comment by eddiemuc** [comment] 2021-03-24 06:28
I don't think it is related to the loop-of-death-thing, but it might be related to SAF taking a long time to scan this users folders because this used to happen on main thread when you open about activity. This is now done on a background thread so should be fixed.

In any case I cannot imagine that this is related to new view binding.

**Comment by moving-bits** [comment] 2021-03-24 19:10
Ok, thanks for cross-checking.

So let's keep an (supporter's ;-)) eye on this for a couple of days, and close here, if no more messages come in related to this.

**Closed** 2021-04-18 18:53 UTC
Labels: Bug, Unverified
