### ISSUE TITLE
optimize the search order in the global search

### ISSUE THREAD

**Issue by bekuno** [cgeo/cgeo#10258] opened 2021-03-25 22:06 UTC
The other is the search mix in the global search for caches and trackable, and the search mix in the trackables search for tracking number and code. The could/should be discussed in an own PR.

_Originally posted by @bekuno in https://github.com/cgeo/cgeo/issues/10231#issuecomment-803658485_

**Comment by bekuno** [comment] 2021-03-25 22:11
To achieve this, we need to divide the trackable search into two parts - search by tracking number and by tracking code.
Then the detailed search could also be extended in this way.

**Comment by fm-sys** [comment] 2021-03-26 07:05
A different approach for "global search" could be that "cache name search" is executed automatically afterwards, if no matching trackable was found. I would like to provide a PR for it...

**Comment by fm-sys** [comment] 2021-03-26 07:13
Btw, related to / duplicate of #5083

**Comment by Lineflyer** [comment] 2021-03-26 10:00
My few cents from users feedback: Many users use the search bar on the main screen as quick search for tracking codes. So this feature should stay.

**Comment by SammysHP** [comment] 2021-03-26 10:06
What about a prefix like "TB:123ABC" like in the search at GitHub? Or too hard for users?

**Comment by fm-sys** [comment] 2021-03-26 10:38
> What about a prefix like "TB:123ABC" like in the search at GitHub? Or too hard for users?

Probably too difficult for average users. 

> Many users use the search bar on the main screen as quick search for tracking codes. So this feature should stay.

Definitely! I'm absolutely with you. My idea was just to execute cache search afterwards, if no matching trackable was found (-> the user probably just entered a trackingcode like looking cache name)

**Comment by Lineflyer** [comment] 2021-03-27 09:52
> Probably too difficult for average users.

 Definitely 

> Many users use the search bar on the main screen as quick search for tracking codes. So this feature should stay.

Sounds reasonable.
In fact a user contaced us some time ago as he tried to search for "Angeln" which gave the error of not finding the TB instead of searching for matching caches.

**Comment by bekuno** [comment] 2021-03-27 14:26
As the feedback results in "let the general global search behavior as is" I changed the issue titel to the proposed change.

**Closed** 2021-03-27 17:26 UTC
