### ISSUE TITLE
Add latest log information in cache preview

### ISSUE THREAD

**Issue by samueltardieu** [cgeo/cgeo#5878] opened 2016-08-04 11:39 UTC
Locus Maps Pro (with Geocaching add-on) adds a preview of what the 5 latest log types were when logs are available. This allows the geocacher to quickly determine if a cache might be worth it or if there is a good chance that the cache is not there anymore. We should do the same thing in cgeo.

![screenshot_20160803-142018](https://cloud.githubusercontent.com/assets/44656/17400539/cf198f98-5a48-11e6-9bbf-649218486c81.png)

**Comment by SammysHP** [comment] 2016-08-04 11:46
Duplicate of #1801.

**Closed by SammysHP** 2016-08-04 11:46 UTC
Labels: Feature Request, Frontend Design
