### ISSUE TITLE
F-droid not finding nightlies

### ISSUE THREAD

**Issue by john-magnus** [cgeo/cgeo#14222] opened 2023-04-24 12:18 UTC
### Describe your problem!

F-droid does not find any releases after 23.04.16 (23.04.16-NB-ba0042c) in the nightlies repository (https:/fdroid.cgeo.org/nightly).

![Screenshot_20230424-140332](https://user-images.githubusercontent.com/1545102/233993321-3201583a-8ecf-4955-8006-d048621c8c6a.png)

### How to reproduce?

Open F-droid
Go to updates, update repositories

### Actual result after these steps?

Nada

### Expected result after these steps?

New nightlies available for update/ install

### Reproducible

Yes

### c:geo Version

2023.04.216

### System information

```text
F-droid version 1.16.3

Device:

Device type: Pixel 7 Pro (cheetah, google)
Available processors: 8
Android version: 13
Android build: TQ2A.230305.008.C1
Screen resolution: 1440x2905px (484x976dp)
Pixel density: 2.9750001
System font scale: 1.0 / used scale: 1.0
Sailfish OS detected: false
Google Play services: enabled - 23.13.12 (190400-519946965)
Memory:  Available:2,3 GB, Total:11,2 GB, Threshold: 216,0 MB, low:false
```

**Comment by SammysHP** [comment] 2023-04-24 13:03
Duplicate of cgeo-fdroid#9.

**Closed by SammysHP** 2023-04-24 13:03 UTC
Labels: Bug, Unverified
