### ISSUE TITLE
Saved log remains after online logging

### ISSUE THREAD

**Issue by alan666notb** [cgeo/cgeo#6171] opened 2016-12-01 14:15 UTC
The latest version of cgeo is failing to remove the 'saved log' entry after logging a cache online if the phone is locked. It's intermittent but it fails quite often - maybe 50% of the time. 

I often type out a log entry, click to upload it and then lock the phone and put it in my pocket while it uploads so I see this happen quite often.

##### Detailed steps causing the problem:
- Load a cache into cgeo
- Got to log an entry and type some text in.
- press the 'Arrow' to upload the log and immediately lock the phone (On my phone, the power button locks it)
- Wait a while until you think the upload has happened
- unlock the phone and view the log entries.

##### Actual behavior after performing these steps:
Often (not always) there is a 'saved log' entry as well as the correctly uploaded log entry. The only way to remove it is to click on it and select 'Clear'. See screenshot below

##### Expected behavior after performing these steps:
The 'saved log' should be deleted after a successful upload.

##### Version of c:geo used:
2016.11.28-RC

##### Is the problem reproducible for you?
Yes, but not always

##### System information:
```--- System information ---
Device: E6683 (E6683, Sony)
Android version: 6.0.1
Android build: 32.2.A.0.253
Cgeo version: 2016.11.28-RC
Google Play services: enabled
Low power mode: inactive
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: rotation vector
Hide own/found: false
Map strategy: auto
HW acceleration: enabled (default state)
System language: en_GB
Log date format: 29/11/2016
Debug mode active: no
Fine location permission: granted
Write external storage permission: granted
Geocaching sites enabled:
   geocaching.com: Logged in (Login OK) / PREMIUM
Geocaching.com date format: dd MMM yy
Installed cgeo plugins:  none
--- End of system information ---
```

##### Other comments and remarks:
The log entry is correctly uploaded, it just the 'saved log' that shouldn't happen.
It doesn't seem to happen if I watch it while it's uploading - only if I lock the phone.

![screenshot_20161201-124750](https://cloud.githubusercontent.com/assets/7459480/20796874/4e27151e-b7d0-11e6-8dc7-6de43ee3630d.png)

**Comment by Lineflyer** [comment] 2017-02-21 22:06
Could not reproduce and no similar issues reported. Closing for now. Feel free to reopen.

**Comment by Lineflyer** [comment] 2019-04-23 22:00
Closing as to no more appearance.

**Closed by Lineflyer** 2019-04-23 22:00 UTC
Labels: Bug
