### ISSUE TITLE
Spoiler images get duplicated on refresh

### ISSUE THREAD

**Issue by SammysHP** [cgeo/cgeo#13674] opened 2022-11-15 22:02 UTC
### Describe your problem!

If you refresh an (OpenCaching?) cache, spoiler images get duplicated every time.

### How to reproduce?

1. Open for example OC175EB
2. Refresh a few times

### Actual result after these steps?

Each times the number of images increases, adding duplicated images.

### Expected result after these steps?

No change in images.

### Reproducible

Yes

### c:geo Version

2022.11.11-NB

**Comment by eddiemuc** [comment] 2022-11-15 22:14
Does this also happen for Gc.com caches?

**Comment by SammysHP** [comment] 2022-11-15 22:50
I was not able to reproduce it with geocaching.com.

**Comment by Lineflyer** [comment] 2022-11-15 22:52
Confirmed for the mentioned OC example.

**Comment by eddiemuc** [comment] 2022-11-16 09:41
I have no access to my c:geo coding infrastructure this week, so I can't fix this immediately

**Comment by eddiemuc** [comment] 2022-11-19 12:55
Fixed with PR #13691.

Turns out this bug has nothing to do with new image gallery but with a wrong handling of spoiler images in OC connector in general (and also in GC and SU connector): on refresh, the new spoilers are just added to offline stored cache without removing the existing spoilers first

**Closed** 2022-11-20 11:38 UTC
Labels: Bug, Connector OC
