### ISSUE TITLE
Deleting geocache in "History" don't work (+related problem)

### ISSUE THREAD

**Issue by gcPhil** [cgeo/cgeo#5949] opened 2016-09-12 16:21 UTC
##### Detailed steps causing the problem:
- open history
- long press on a cache
- press "drop" > Message "Deleted 1 Cache"
##### Actual behavior after performing these steps:
- Cache is still stored (in history and everywhere else)
##### Expected behavior after performing these steps:
- Cache should be deleted (in all lists)
##### Version of c:geo used:

2016.09.06-RC
##### Is the problem reproducible for you?

Yes
##### System information:

Device: SM-G800F (kminiltexx, samsung)
Android version: 4.4.2
Android build: KOT49H.G800FXXU1ANJ2
Cgeo version: 2016.09.06-RC
Google Play services: enabled
Low power mode: inactive
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: rotation vector
Hide own/found: true
Map strategy: auto
HW acceleration: enabled (default state)
System language: de_DE
Log date format: 12/09/2016
Debug mode active: no (cgeo forced to English)
Geocaching sites enabled:
   geocaching.com: Logged in (Login OK) / PREMIUM
Installed cgeo plugins: calendar
##### Other comments and remarks:

There is an **other** probably related Problem: For normal I delete all caches after export field notes in history list from the device by marking it with select mode but that is also not possible any more. In select mode there is no more "drop" or "delete" for this list. I don't want found caches on the device and I don't like to search for them in other lists every time. (Possible with all lists > filter > with offline logs - but deleting in history was much easier.)

**Comment by Lineflyer** [comment] 2016-09-13 13:30
Confirmed.
Are you sure this behaviour changed only recently.
It would be possible it changed starting with release 2016.08.14 due to the multi-list feature.

**Comment by gcPhil** [comment] 2016-09-13 13:40
Yes, you are right the not working "drop" menu changed with 2016.08.14 due to the multi-list feature.

I am not sure if the missing "drop" or "delete" for selected caches also appeared with that version or even before.

**Comment by SammysHP** [comment] 2016-12-12 17:06
This problem appears also in the search result list:

1. Open nearby search
1. Store a cache, it will be labeled "stored offline"
1. Delete this cache via the context menu
1. The cache disappears in the list (**should not happen in search results!**), after a moment it appears again

**Comment by Lineflyer** [comment] 2016-12-13 18:10
Isn't the initially descibred problem the same as #6186 ?
@SammysHP In this case I suggest closing here, continuing in #6186 and maybe open a dedicated issue for your finding (as it is not related to history list directly, so might have another root cause).

**Comment by pstorch** [comment] 2016-12-15 21:22
I found the reason why caches are not deleted from stored lists, when drop in History view.
But again the question about the caches with offline logs? Should we remove them when executing long press + remove in the history list?

**Comment by pstorch** [comment] 2016-12-15 21:40
I've sent PR #6193 but caches with offline logs will still stay on history! Is that what we want?

**Closed** 2016-12-26 15:11 UTC
Labels: Bug, Regression
