### ISSUE TITLE
Found caches shown on map despite filtered out

### ISSUE THREAD

**Issue by geocachermgo** [cgeo/cgeo#15557] opened 2024-04-06 08:52 UTC
### Describe your problem!

Found caches shown on map despite filtered out

### How to reproduce?

Show caches on map (found included)
Change filter to exclude found caches

### Actual result after these steps?

Found caches still shown
![IMG_20240406_105051](https://github.com/cgeo/cgeo/assets/43813636/9eef0ebe-afd2-4711-aad2-cc6bd5b1d8c3)

### Expected result after these steps?

Found caches removed from map

### Reproducible

Yes

### c:geo Version

2024.04.05-NB-bf2adb3

**Comment by Lineflyer** [comment] 2024-04-06 09:23
Cannot reproduce.
@geocachermgo Are you BM or PM?

**Comment by bekuno** [comment] 2024-04-06 09:42
The problem is reproduceable for me when switching the filter with long tap an the menu icon.
It works correct, when switching with the filter menu to the saved filter.

**Comment by geocachermgo** [comment] 2024-04-06 10:43
I'm PM. My sequence is:

Filter for map is set to "no own".
From main page X click "In der Nähe" (Nearby?)
At the result page, X click "map symbol"
 On the map also the found caches appear (ok, since they are not filtered out)
X Click on filter symbol
X Change selection Found from "Alle" to "No"
X Click on confirmation hook
Map is unchanged

X is normal short click. No long clicks in my sequence.

**Comment by murggel** [comment] 2024-04-06 19:30
Same over here, seems, that when the filter changes, caches, which fits the filter-condition are added to the viewport but not removed, if they don't fit the condition.

**Comment by murggel** [comment] 2024-04-06 19:33
Strange - just tried it with selecting a stored filter via long-click and changing the criteria via dialog - different behavior 

I will try to record the effects

**Comment by murggel** [comment] 2024-04-06 19:55
I will try to look into the code tomorrow  - maybe I find something

**Comment by MagpieFourtyTwo** [comment] 2024-04-06 20:07
@murggel 
> video too large, if needed I can send it via support

In the phone's Gallery you can call ``Edit``, then ``Export``. After deselecting ``Original size`` you can reduce resolution and frame rate.  If this is not sufficient, you can use the app ``Video Panda`` to reduce the size even more.  ``Large File`` does the job most of the times, while quality of ``Medium File`` is still good enough to get an idea of what you're describing.

**Comment by MagpieFourtyTwo** [comment] 2024-04-06 20:12
Poss. related to #15470?

**Comment by murggel** [comment] 2024-04-06 21:02
> Poss. related to #15470?

👍 That seems to be my failing scenario

**Comment by murggel** [comment] 2024-04-07 20:12
Hopefully fixed with PR #15576

**Comment by murggel** [comment] 2024-04-22 20:52
@geocachermgo can you please try, if it your workflow now works with the fix for #15470 (should be available in the nightly now)

**Comment by geocachermgo** [comment] 2024-04-23 04:39
I'm using 2024.04.21-NB-be2d1b4.
The sequence I descibed is working correctly with that version.

**Comment by murggel** [comment] 2024-04-23 05:20
Fixed with PR #15576

**Closed** 2024-04-23 05:20 UTC
Labels: Bug, Map: Unified
