### ISSUE TITLE
Favorite filter with not limiting setup stops showing caches on map

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#12807] opened 2022-02-24 20:07 UTC
### Describe your problem!

A user contacted us with a more or less sporadic problem, that his live map stopped showing GC-caches (but still showing labs and opencaching caches).

After some debugging and checking we were able to find a reproducible way.

The problem happens some time (next start?) after applying a favorite point filter with no limitations set.

### How to reproduce?

- Open live map
- Open filter
- Change to advanced
- Add favorite filter
- Don't provide any input to the filter (i.e. leave it on "Absolute" 0 up to >1000)
- Return to map
- Note: The filter info bar is not shown (maybe as there is in fact no real filtering)
- Move the map to trigger loading

### Actual result after these steps?

All GC-caches loaded prior to setting up the filter are still shown
In new areas of the map however only lab and OC-caches (and stored GC-caches) show up.

Consequently after restarting c:geo and using the live map no caches except lab and OC and stored caches show up

### Expected result after these steps?

As the favorite filter element is active but in fact configure to not filter, it should be no difference to the situation if no filter is applied at all.

It looks like a bug to transfer this filter setup into the GC search API only, as the rest (saved, OC, lab) shows as expected.

### Reproducible

Yes

### c:geo Version

2022.02.16

### System information

```text
## System information

c:geo version: 2022.02.16

Device:
-------
- Device type: SM-A515F (a51nsxx, samsung)
- Available processors: 8
- Android version: 11
- Android build: RP1A.200720.012.A515FXXU4EUD7
- Screen resolution: 1080x2186px (411x832dp)
- Pixel density: 2.8875
- System font scale: 1.1 / used scale: 1.1
- Sailfish OS detected: false
- Google Play services: enabled - 22.02.21 (150400-428111784)

Sensor and location:
-------
- Low power mode: inactive
- Compass capabilities: yes
- Rotation vector sensor: present
- Orientation sensor: present
- Magnetometer & Accelerometer sensor: present
- Direction sensor used: rotation vector

Program settings:
-------
- Settings: v9, Count:119
- Set language: de_CH (system default)
- System date format: dd.MM.yy
- Time zone: GMT+02:00
- Debug mode active: no
- Last backup: never
- Routing mode: Walk
- Live map mode: true
- OSM multi-threading: false / threads: 1
- Map: Google: Karte
  - Id: cgeo.geocaching.maps.google.v2.GoogleMapProvider$GoogleMapSource
  - Atts: none
  - Theme: none

Filters:
-------
- Hide waypoints: -
- LIVE: Keine ([:inconclusive=true:advanced=true]AND(favorites:-:-:percentage=false))
- OFFLINE: Keine ([:inconclusive=false:advanced=true]AND(favorites:-:-:percentage=false;type;status;size))

Stored Filters (#0):

Services:
-------
- Geocaching sites enabled:
   geocaching.com: Logged in (Anmeldung OK) / BASIC
- Geocaching.com date format: dd MMM yy
- Routing: internal / BRouter installed: false
- Installed c:geo plugins:  none

Permissions & paths:
-------
- Fine location permission: granted
- Write external storage permission: granted
- System internal c:geo dir: /data/user/0/cgeo.geocaching (59.6 GB free) v3 internal isDir(7 entries)
- Legacy User storage c:geo dir: /data/user/0/cgeo.geocaching (59.6 GB free) v3 internal isDir(7 entries)
- Geocache data: /storage/emulated/0/Android/data/cgeo.geocaching/files/GeocacheData (59.6 GB free) v3 external non-removable isDir(167 entries)
- Internal theme sync (is turned off): /data/user/0/cgeo.geocaching/MapThemeData (59.6 GB free) v3 internal isDir(0 entries)
- Public Folders: #11
  - BASE: /C-geo (User-Defined)[/C-geo[DOCUMENT#0:p-content://com.android.externalstorage.documents/tree/primary%3AC-geo::]] (Uri: content://com.android.externalstorage.documents/tree/primary%3AC-geo/document/primary%3AC-geo, Av:true, files:>=3, dirs:>=8, totalFileSize:>=245.0 MB, free space: 59.6 GB, files on device: 13278715)
  - OFFLINE_MAPS: /C-geo/maps (Default)[/C-geo/maps[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3AC-geo::/maps]] (Uri: content://com.android.externalstorage.documents/tree/primary%3AC-geo/document/primary%3AC-geo%2Fmaps, Av:true, files:2, dirs:1, totalFileSize:244.7 MB, free space: 59.6 GB, files on device: 13278715)
  - OFFLINE_MAP_THEMES: /C-geo/maps/_themes (Default)[/C-geo/maps/_themes[PERSISTABLE_FOLDER(OFFLINE_MAPS)#1:p-content://com.android.externalstorage.documents/tree/primary%3AC-geo::/maps/_themes]] (Uri: content://com.android.externalstorage.documents/tree/primary%3AC-geo/document/primary%3AC-geo%2Fmaps%2F_themes, Av:true, files:0, dirs:0, totalFileSize:0 B, free space: 59.6 GB, files on device: 13278715)
  - LOGFILES: /C-geo/logfiles (Default)[/C-geo/logfiles[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3AC-geo::/logfiles]] (Uri: content://com.android.externalstorage.documents/tree/primary%3AC-geo/document/primary%3AC-geo%2Flogfiles, Av:true, files:1, dirs:0, totalFileSize:377.2 KB, free space: 59.6 GB, files on device: 13278715)
  - GPX: /C-geo/gpx (Default)[/C-geo/gpx[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3AC-geo::/gpx]] (Uri: content://com.android.externalstorage.documents/tree/primary%3AC-geo/document/primary%3AC-geo%2Fgpx, Av:true, files:0, dirs:0, totalFileSize:0 B, free space: 59.6 GB, files on device: 13278715)
  - BACKUP: /C-geo/backup (Default)[/C-geo/backup[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3AC-geo::/backup]] (Uri: content://com.android.externalstorage.documents/tree/primary%3AC-geo/document/primary%3AC-geo%2Fbackup, Av:true, files:0, dirs:0, totalFileSize:0 B, free space: 59.6 GB, files on device: 13278715)
  - FIELD_NOTES: /C-geo/field-notes (Default)[/C-geo/field-notes[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3AC-geo::/field-notes]] (Uri: content://com.android.externalstorage.documents/tree/primary%3AC-geo/document/primary%3AC-geo%2Ffield-notes, Av:true, files:0, dirs:0, totalFileSize:0 B, free space: 59.6 GB, files on device: 13278715)
  - SPOILER_IMAGES: /C-geo/GeocachePhotos (Default)[/C-geo/GeocachePhotos[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3AC-geo::/GeocachePhotos]] (Uri: content://com.android.externalstorage.documents/tree/primary%3AC-geo/document/primary%3AC-geo%2FGeocachePhotos, Av:true, files:0, dirs:0, totalFileSize:0 B, free space: 59.6 GB, files on device: 13278715)
  - ROUTING_BASE: /C-geo/routing (Default)[/C-geo/routing[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3AC-geo::/routing]] (Uri: content://com.android.externalstorage.documents/tree/primary%3AC-geo/document/primary%3AC-geo%2Frouting, Av:true, files:9, dirs:1, totalFileSize:185.3 MB, free space: 59.6 GB, files on device: 13278715)
  - ROUTING_TILES: /C-geo/routing/segments4 (Default)[/C-geo/routing/segments4[PERSISTABLE_FOLDER(ROUTING_BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3AC-geo::/routing/segments4]] (Uri: content://com.android.externalstorage.documents/tree/primary%3AC-geo/document/primary%3AC-geo%2Frouting%2Fsegments4, Av:true, files:2, dirs:0, totalFileSize:185.2 MB, free space: 59.6 GB, files on device: 13278715)
  - TEST_FOLDER: [Legacy]/data/user/0/cgeo.geocaching/files/unittest (Default)[/data/user/0/cgeo.geocaching/files/unittest[FILE#1:p-file:///data/user/0/cgeo.geocaching/files::/unittest]] (Uri: file:///data/user/0/cgeo.geocaching/files/unittest, Av:true, files:0, dirs:0, totalFileSize:0 B, free space: 59.6 GB, files on device: -1)
- Map render theme path:
- PersistedDocumentUris: #1
- UNUSED_TRACK: null
- Persisted Uri Permissions: #1
  - content://com.android.externalstorage.documents/tree/primary%3AC-geo (9. Jan., 11:46):RW
- Database: /data/user/0/cgeo.geocaching/databases/data (v98, Size:4.2 MB) on system internal storage

--- End of system information ---
```

### Additional Information

Support ticket #442562

**Comment by eddiemuc** [comment] 2022-03-01 16:58
This looks like it was a lot of work to isolate the test case. Thanks for the support!

The cause of this was a hidden NPE when minimum range was not set to a value higher than 0. The log should have included a NullPointerException when this happens.

Fixed with PR #12819

**Closed** 2022-03-04 20:47 UTC
Labels: Bug
