### ISSUE TITLE
Supported web addresses resets

### ISSUE THREAD

**Issue by mjarmstr** [cgeo/cgeo#13340] opened 2022-08-16 00:22 UTC
### Describe your problem!

c:geo keeps loosing the setting for opening coord.info links.  
I have c:geo set to open coord.info links so that when I get a notification email from geocaching.com, I can open the like to the cache in c:geo.  Periodically the link will open in Chrome instead and I have to go reselect coord.info as one of the URLs handled by c:geo.  I haven't completely correlated this to app updates, but it does seem to happen at about the same frequency.  I do also have the official geocaching.com app installed, but the URLs open in Chrome not the official app.

### How to reproduce?

- Receive an email from geocaching.comm with a link to a cache.
- Tap on the link.

### Actual result after these steps?

- The link opens in a web browser instead of c:geo
- Navigate to the defaults for the app and reselect coord.info.
- Navigate back to the email and tap the link again.
- The link opens in c:geo

### Expected result after these steps?

- The link opens in c:geo bringing up the cache page

### Reproducible

Unclear

### c:geo Version

2022.08.08

### System information

```text
## System information

c:geo version: 2022.08.08

Device:
-------
- Device type: SM-S906U1 (g0quew, samsung)
- Available processors: 8
- Android version: 12
- Android build: SP1A.210812.016.S906U1UEU2AVF7
- Screen resolution: 1080x2131px (384x757dp)
- Pixel density: 3.09375
- System font scale: 1.1 / used scale: 1.1
- Sailfish OS detected: false
- Google Play services: enabled - 22.26.15 (190400-461192076)

Sensor and location:
-------
- Low power mode: inactive
- Compass capabilities: yes
- Rotation vector sensor: present
- Orientation sensor: present
- Magnetometer & Accelerometer sensor: present
- Direction sensor used: rotation vector

Program settings:
-------
- Settings: v9, Count:188
- Set language: en
- System date format: M/d/yy
- Time zone: CDT
- Debug mode active: no
- Last backup: Apr 14, 7:37 AM
- Routing mode: Car
- Live map mode: true
- OSM multi-threading: false / threads: 1
- Map: Combined (Offline)
  - Id: cgeo.geocaching.maps.mapsforge.MapsforgeMapProvider$OfflineMultiMapSource
  - Atts: massachusetts.map: / Map data (c) OpenStreetMap contributors /  / us-midwest.map: / Map data (c) OpenStreetMap contributors /  / us-west.map: / Map data (c) OpenStreetMap contributors
  - Theme: none

Filters:
-------
- Hide waypoints: -
- LIVE: Hunting ([Hunting:inconclusive=false:advanced=false]AND(status:owned_no:found_no:has_offline_found_log_no:solved_mystery_yes:exclude_disabled:exclude_archived))
- OFFLINE: None ([:inconclusive=false:advanced=true])

Stored Filters (#8):
- Hiding: [Hiding:inconclusive=false:advanced=false]AND(status:exclude_archived))
- High Favorite: [High Favorite:inconclusive=false:advanced=false]OR(favorites:21.0:-:percentage=false;favorites:0.34:-:percentage=true))
- High Favorite Percentage: [High Favorite Percentage:inconclusive=false:advanced=false]AND(favorites:0.1:-:percentage=true;status:owned_no:found_no:has_offline_found_log_no:exclude_disabled:exclude_archived))
- Hunting: [Hunting:inconclusive=false:advanced=false]AND(status:owned_no:found_no:has_offline_found_log_no:solved_mystery_yes:exclude_disabled:exclude_archived))
- Not Recently Updated: [Not Recently Updated:inconclusive=false:advanced=false]AND(stored_since:2592000:9223372036854775807))
- Quick Find: [Quick Find:inconclusive=false:advanced=true]AND(type:EARTH:USER_DEFINED:TRADITIONAL:EVENT:ADVLAB:WEBCAM:CITO:LETTERBOX:WHERIGO:VIRTUAL:MYSTERY;difficulty_terrain:d=1.0:d=2.0:t=1.0:t=2.0;status:owned_no:found_no:has_offline_found_log_no:solved_mystery_yes:exclude_disabled:exclude_archived))
- Unsolved Mysteries: [Unsolved Mysteries:inconclusive=false:advanced=false]AND(type:MYSTERY;status:owned_no:found_no:has_offline_found_log_no:solved_mystery_no:exclude_disabled:exclude_archived))

Services:
-------
- Geocaching sites enabled:
   geocaching.com: Logged in (Login OK) / PREMIUM
   Geocaching.com Adventure Lab
- Geocaching.com date format: MM/dd/yyyy
- Last successful login on geocaching.com: 2022-08-15 19-05
- Routing: internal / BRouter installed: false
- Installed c:geo plugins:  none

Permissions & paths:
-------
- Fine location permission: granted
- Write external storage permission: granted
- System internal c:geo dir: /data/user/0/cgeo.geocaching (130.6 GB free) v3 internal isDir(6 entries)
- Legacy User storage c:geo dir: /data/user/0/cgeo.geocaching (130.6 GB free) v3 internal isDir(6 entries)
- Geocache data: /storage/emulated/0/Android/data/cgeo.geocaching/files/GeocacheData (130.6 GB free) v3 external non-removable isDir(240 entries)
- Internal theme sync (is turned off): /data/user/0/cgeo.geocaching/MapThemeData (130.6 GB free) v3 internal isDir(0 entries)
- Public Folders: #11
  - BASE: /cgeo (User-Defined)[/cgeo[DOCUMENT#0:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo, Av:true, files:>=15, dirs:>=9, totalFileSize:>=3.0 GB, free space: 130.6 GB, files on device: 12812797)
  - OFFLINE_MAPS: /cgeo/maps (Default)[/cgeo/maps[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/maps]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Fmaps, Av:true, files:6, dirs:1, totalFileSize:2.9 GB, free space: 130.6 GB, files on device: 12812797)
  - OFFLINE_MAP_THEMES: /cgeo/maps/_themes (Default)[/cgeo/maps/_themes[PERSISTABLE_FOLDER(OFFLINE_MAPS)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/maps/_themes]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Fmaps%2F_themes, Av:true, files:0, dirs:0, totalFileSize:0 B, free space: 130.6 GB, files on device: 12812797)
  - LOGFILES: /cgeo/logfiles (Default)[/cgeo/logfiles[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/logfiles]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Flogfiles, Av:true, files:1, dirs:0, totalFileSize:38.4 KB, free space: 130.6 GB, files on device: 12812797)
  - GPX: /cgeo/gpx (Default)[/cgeo/gpx[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/gpx]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Fgpx, Av:true, files:0, dirs:0, totalFileSize:0 B, free space: 130.6 GB, files on device: 12812797)
  - BACKUP: /cgeo/backup (Default)[/cgeo/backup[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/backup]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Fbackup, Av:true, files:>=8, dirs:>=7, totalFileSize:>=281.5 MB, free space: 130.6 GB, files on device: 12812797)
  - FIELD_NOTES: /cgeo/field-notes (Default)[/cgeo/field-notes[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/field-notes]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Ffield-notes, Av:true, files:0, dirs:0, totalFileSize:0 B, free space: 130.6 GB, files on device: 12812797)
  - SPOILER_IMAGES: /cgeo/GeocachePhotos (Default)[/cgeo/GeocachePhotos[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/GeocachePhotos]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2FGeocachePhotos, Av:true, files:0, dirs:0, totalFileSize:0 B, free space: 130.6 GB, files on device: 12812797)
  - ROUTING_BASE: /cgeo/routing (Default)[/cgeo/routing[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/routing]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Frouting, Av:true, files:8, dirs:1, totalFileSize:30.3 MB, free space: 130.6 GB, files on device: 12812797)
  - ROUTING_TILES: /cgeo/routing/segments4 (Default)[/cgeo/routing/segments4[PERSISTABLE_FOLDER(ROUTING_BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/routing/segments4]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Frouting%2Fsegments4, Av:true, files:1, dirs:0, totalFileSize:30.2 MB, free space: 130.6 GB, files on device: 12812797)
  - TEST_FOLDER: [Legacy]/data/user/0/cgeo.geocaching/files/unittest (Default)[/data/user/0/cgeo.geocaching/files/unittest[FILE#1:p-file:///data/user/0/cgeo.geocaching/files::/unittest]] (Uri: file:///data/user/0/cgeo.geocaching/files/unittest, Av:true, files:0, dirs:0, totalFileSize:0 B, free space: 130.6 GB, files on device: -1)
- Map render theme path: 
- PersistedDocumentUris: #1
- UNUSED_TRACK: null
- Persisted Uri Permissions: #1
  - content://com.android.externalstorage.documents/tree/primary%3Acgeo (Apr 14, 11:32 AM):RW
- Database: /data/user/0/cgeo.geocaching/databases/data (v99, Size:70.9 MB) on system internal storage

--- End of system information ---
 
```

**Comment by Lineflyer** [comment] 2022-08-16 13:19
I think it correlates with updates of the Groundspeak app as far as I have understood the system.
If this happens: Do you loose any other URLs in the settings or just coord.info?

**Comment by mjarmstr** [comment] 2022-08-16 13:49
Looks like c:geo retained www.coord.info and  geocaching.com.  I don't
recall if I had any others selected since mostly I just want the links in
the emails to open.
I could see it happening with the updates of the Groundspeak app, but the
links don't open in that app, they open in a browser.  I did just check and
I have "Open supported links" disabled for the Groundspeak app.
Another data point, this didn't happen on my old phone, a Moto X4 running
an older version of Android.

**Comment by wolverine007** [comment] 2022-08-17 05:26
Same here, also losing the coord.info link when the official app is updating. Seems they are forcing it to be assigned to their app. Really annoying, but as long as I am able to adjust it... 
So not an issue of cgeo.

**Comment by Lineflyer** [comment] 2022-08-17 09:04
This is an Android12 and above issue:

As the Groundspeak app validates itself as owner of that URLs, the system automatically prefers them as target app for these URLs.

**Comment by eddiemuc** [comment] 2022-08-17 09:55
Does anyone know whether this "new feature" can be "tuned" (away) by using "Better Open With" (https://play.google.com/store/apps/details?id=com.aboutmycode.betteropenwith) or similar apps?

**Comment by rouroni1** [comment] 2022-08-17 14:48
I have one Poco F4GT with Miui 13, android 12.

The issue is the same, when official geocaching app goes an update I must set again the links coord.info , geocaching.com to open again with c:geo (before I disable them for de official app). The eternal game of the cat and the mouse...

The app that I use to be able to access "Open with" is: Miui Hidden Settings ( https://play.google.com/store/apps/details?id=com.ceyhan.sets ). The testing that I've made with "Better open With" didn't work on Miui.

I've already sent an email with this info, and the awnser was that it will be added to the wiki.

Thank you

**Comment by fracz** [comment] 2022-09-26 17:14
In my case, c:geo stopped to handle the coord.info links completely. It just opens in chrome w/o asking. Neither Chrome nor c:geo has default actions set in app settings. This started to happen after upgrade from Miui 12 to 13.

**Comment by moving-bits** [comment] 2022-09-26 18:43
See also our FAQ entry about Android 12, it has an extra Xiaomi section: https://www.cgeo.org/faq#android12

**Comment by Lineflyer** [comment] 2022-12-29 11:50
Nothing more we can do here unless Android changes its implementation.
As the Groundspeak app is the validated owner of the URLs the Android system might (e.g. on update of their app) switch back to open "their" links with their app. Not so nice, but IMHO nothing c:geo can currently do about that.

**Closed by Lineflyer** 2022-12-29 11:50 UTC
Labels: Bug, Unverified

**Comment by moving-bits** [comment] 2022-12-29 19:00
For partner-websites we might ask to get c:geo listed as authorized (see #13018). Not sure if geocaching.com would list us, though... 😃
