### ISSUE TITLE
All lists except history lose their position

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#11028] opened 2021-06-28 15:03 UTC
- Open list of caches, scroll down
- Open a cache further down
- Close cache details again to return to the list

Result:
List is scrolled to top

Expected:
Same list status as before opening cache details

On history list its working.

2021.06.28-NB

**Comment by fm-sys** [comment] 2021-06-28 17:27
This seem to be caused by the new filter framework. Could this be the case?

**Comment by Narrat** [comment] 2021-06-28 17:44
Possible duplicate of 10976?

**Comment by fm-sys** [comment] 2021-06-28 17:49
Yes, you are right. Somehow we have missed that issue. So let's close this one as duplicate...

**Closed by fm-sys** 2021-06-28 17:49 UTC
Labels: Bug, Unverified
